### ISSUE TITLE
specify / implement skinning

### ISSUE THREAD

**Issue by fabrobinet** [KhronosGroup/glTF#100]

**Comment by meshula** [comment]
Some years have passed, and the four weight limitation is an issue. Six weights is common, and our use case has eight. Unreal currently supports a maximum of eight. Is there an open issue, or is this the right place to discuss it? I'm not asking for a variable number of influences per vertex, only that the number of influences be declared in the gltf file.

**Comment by lexaknyazev** [comment]
@meshula See #878.

**Comment by meshula** [comment]
Thanks
