### ISSUE TITLE
TANGENT handedness

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#1019]
@bghgary @sbtron 

Couple questions about `TANGENT` data.
- At the moment only `VEC4` accessors are allowed. Could we allow `VEC3` accessors as well? This shouldn't affect implementations, since shaders will get _w_ component of 1 by default.
- Must _w_ component of all vertices of the same primitive be the same?

**Comment by xelatihy** [comment]
In general it can be change over the same mesh since it is driven by UV derivatives.

**Comment by bghgary** [comment]
> This shouldn't affect implementations, since shaders will get w component of 1 by default.

This will affect implementations. BabylonJS for example currently expects a Float32Array or number[] for the tangents and they are expected to be VEC4 only. I'm sure other parsers will have similar issues.

**Comment by lexaknyazev** [comment]
This could be an issue for initial data loading or CPU processing, sure. 
I meant that from GPU/shaders perspective there's almost no difference between VEC3 and VEC4 with 
`w = 1`. Maybe reduced asset and vertex buffer sizes justify handling of VEC3 case on parse/load.

**Comment by bghgary** [comment]
I agree for shaders.

I don't think we should be making these kind of changes to the spec anymore as it affects the stored bits. Maybe for a dot version update, but even then, I don't know how often handedness is always 1. Do you have data on how often this happens?

**Comment by lexaknyazev** [comment]
By spec definition it's either `1` or `-1`. So it seems to be a convention between tools. 
Stored bits shouldn't be affected since `VEC4` will remain supported forever (at least for 2.x).
I agree with postponing this to the next minor update.

**Comment by bghgary** [comment]
> Stored bits shouldn't be affected since VEC4 will remain supported forever (at least for 2.x).

I'm not sure I follow. Yes, VEC4 will always be supported. I don't mean "stored bits" to mean existing assets. If we add VEC3 to 2.0 (which I'm assuming you are asking about since this issue is tagged for 2.0), then new assets might have a VEC3 float array and implementations will have to support the new type. That is a breaking change for 2.0.

**Comment by lexaknyazev** [comment]
I was thinking that since there's no 100% complete glTF 2.0 implementation yet (at least I'm not aware of such), it could be possible to tweak allowed attribute formats. Anyway, we have more important 2.0 issues, so this one could be addressed later.

Could you clarify one more thing here:
spec definition of _w_ component says that it's a "sign value", but implementation note's example uses it as exact value. What if it equals `2`, or `0`? Are such values valid? (I assume no.) Is it valid for adjacent vertices to have different _w_ values? (Also no.)

**Comment by bghgary** [comment]
> What if it equals 2, or 0? Are such values valid? (I assume no.) 

No, these are not valid. I don't expect runtime implementation to check though.

> Is it valid for adjacent vertices to have different w values? (Also no.)

I'm not sure about this one. I don't see why anyone would do this, but it's also not necessarily wrong if it happens.

**Comment by pjcozzi** [comment]
Discussed on a 3D Formats call.

Spec allows -1/+1 for `w` so no change required.

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#meshes
