### ISSUE TITLE
Node definition provides no way to identify whether it is a joint

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF#1020]
With glTF2.0 we removed the `jointName` property. Without this, it is not possible to tell from a node's definition whether it is a joint — the only indicator is whether it is referenced as a joint by some other node.

This is fine for top-down loading, but prevents bottom-up. three.js implements the latter (perhaps we should change that), so we've worked around it here: https://github.com/mrdoob/three.js/pull/11524

Not sure if any spec change is worthwhile; perhaps a note recommending top-down loading?

**Comment by lexaknyazev** [comment]
> the only indicator is whether it is referenced as a joint by some other node

You meant by some skin, right? I don't think that's a big issue: one simple pass through all skins should be enough to "mark" joint nodes.

**Comment by donmccurdy** [comment]
> I don't think that's a big issue: one simple pass through all skins should be enough to "mark" joint nodes.

Agreed. The indirection was surprising to me, but easy to work around.

**Comment by pjcozzi** [comment]
+1 to a short implementation note in the spec. @donmccurdy would you like to add it?

**Comment by lexaknyazev** [comment]
> a note recommending top-down loading

I'd say about one-time skins traverse instead. `node`/`skin` relations are bidirectional, so it's not quite clear how to define top/down here.

**Comment by donmccurdy** [comment]
Sounds good, if the issue doesn't seem like too much of an edge case to warrant the note.
