### ISSUE TITLE
glTF ray tracing support?

### ISSUE THREAD

**Issue by capitalknew** [KhronosGroup/glTF#1024]
Hello. I suggest also add ray tracers support for glTF (viewers), I have own OpenGL ray tracer engine, that can be real-time. Yes, in hard scenes can huge lags. But, I suggest to add few options, special for ray tracers (with PBR add refractions, IOR, transmissions and colors).

**Comment by pjcozzi** [comment]
@capitalknew once your ray tracing engine supports glTF, feel free to open a pull request to add it to the list in the [README.md](https://github.com/KhronosGroup/glTF#gltf-tools).

As for other ray tracers using glTF, see this Vulkan raster/ray tracer hybrid: http://www.trungtuanle.com/static_page/masterThesis

**Comment by capitalknew** [comment]
My supports glTF, but at now not support animation (despite of BVH dynamic).

**Comment by pjcozzi** [comment]
OK, feel free to add to README.md when ready.  I'm going to close this issue to help keep this repo organized.
