### ISSUE TITLE
PBR Refraction? 

### ISSUE THREAD

**Issue by ghost** [KhronosGroup/glTF#1027]
Hello. Why in glTF none of PBR refractions? Most games, renders, etc. have support real or fake refractions. So I think refractions also good for glTF.

**Comment by pjcozzi** [comment]
@mlimper @bghgary any insights?

**Comment by bghgary** [comment]
https://github.com/KhronosGroup/glTF/issues/822
This was the thread about transparency in general that might give some context into the choice to only support alpha as coverage in glTF 2.0.

The gist of it is that we didn't want to put too much into 2.0 as handling transparency is a complex subject and may be difficult to implement on all platforms (esp. the web). For now, transparent materials (e.g. glass, water, etc.) can be defined with a not-yet-proposed extension or with extras.

**Comment by pjcozzi** [comment]
Closing.  Anyone feel free to open a new issue with a concrete proposal.
