### ISSUE TITLE
GLTF2.0 lose product structure

### ISSUE THREAD

**Issue by ua4192** [KhronosGroup/glTF#1031]
Hi.

Recently I realized about the new converter from collada to GLTF2.0 format available at:
        https://github.com/KhronosGroup/COLLADA2GLTF/releases

I have tried 32bit and 64bit for Windows platform and in both I am experiencing the same issue.
- COLLADA2GLTF-2.0-windows-Release-Win32.zip
- COLLADA2GLTF-2.0-windows-Release-x64.zip

When I convert a collada file to GLTF2.0 I am loosing the real names shown in the product structure of the DAE file. Instead of these names geom_<number> names are addressed.

In the converter I was previously using (1.0) this was not the case.

Could you please fix this issue, I would like to make use of the new GLB 2.0 format due to the obvious advantages but this is really a problem.

Best regards

**Comment by donmccurdy** [comment]
Hi @ua4192 — could you file this issue on the [COLLADA2GLTF issue tracker](https://github.com/KhronosGroup/COLLADA2GLTF/issues/new)? It does sound like something we'll want to fix, I agree, but that would be the best place to track the problem. Thanks!

**Comment by ua4192** [comment]
Hi.

Many thanks for your quick answer.

I have opened the ticket on the proper section:

           https://github.com/KhronosGroup/COLLADA2GLTF/issues/59

Best regards

2017-07-05 16:01 GMT+02:00 Don McCurdy <notifications@github.com>:

**Comment by donmccurdy** [comment]
Thanks!
