### ISSUE TITLE
gLTF Textures in a dynamic context

### ISSUE THREAD

**Issue by nikjazzer** [KhronosGroup/glTF#1032]
Dear glTF Community,

I am working on a cesium project recently where I have to display monthly data for solar irradiation of a 3D city model. I am wondering if glTF supports the possiblity to save various textures (e.g. 12 textures for one 3D building) in just one file. In the best case I needed to find a wayto switch on the various texture layers by accessing one of the files attributes. Is there something like a time stamp/attribute in a gLTF file? If so, how can I access it. 

Thanks for any support. 

See the attached picture for better understanding (I would like to have the 12 month in just one layer and the timeline will send out dynamic information wich eventually activates the relevant monthly layer)

<img width="1433" alt="bildschirmfoto 2017-05-11 um 17 38 00" src="https://user-images.githubusercontent.com/28257358/27873603-fea40d1c-61ac-11e7-860a-78549487d5c7.png">

**Comment by donmccurdy** [comment]
Hi @nikjazzer — The [`.extras`](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#extras) property will probably come in handy for this. Standard glTF loaders will ignore `extras`; it's intended for custom attributes.

You can include extra textures in the glTF file, add metadata in `node.extras` to specify which textures are applicable for each month (using indexes in the `textures` list), and then write logic in your application to swap those textures on the fly.

**Comment by nikjazzer** [comment]
Thanks @donmccurdy for this info. Do you know by any chance if the cesium gLTF loader supports the extra attributes?

**Comment by lexaknyazev** [comment]
>  if the cesium gLTF loader supports the extra attributes?

CC @pjcozzi

**Comment by pjcozzi** [comment]
@nikjazzer if you need further assistant, please post to the [Cesium Forum](https://cesiumjs.org/forum/).
