### ISSUE TITLE
alphaMode Additive question.

### ISSUE THREAD

**Issue by memmottse** [KhronosGroup/glTF#1033]
Is there a specific reason that an Additive option was not added to the alphaMode types?
I've searched through the issues and I haven't been able to find a discussion about it.

Thanks

**Comment by pjcozzi** [comment]
@mlimper or @sbtron do you recall?

**Comment by mlimper** [comment]
@bghgary probably has a more complete picture than me, but if I recall correctly:

* the current state of the spec only supports the alpha modes `BLEND` (assumes that the classic "over" operator is used) and `MASK` (masks out texels to simulate holes in the geometry), plus the trivial `OPAQUE` mode which ignores alpha - see https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#alpha-coverage

* things like refraction etc., for simulating more complex materials like glass, do not exist right now and will have to be subject of further discussion - see https://github.com/KhronosGroup/glTF/issues/1027

@memmottse Could you give an example of your use case for additive blending? It would be interesting to know how relevant this is to the large majority, so we can get an idea if it makes sense to integrate this into future versions, or not.

**Comment by memmottse** [comment]
@mlimper  A specific use case I am looking at currently is a simple animated particle system fire.  I can imagine several use cases though: fake light beams at a theater marque, holographic elements on a star ship bridge, etc.
From an implementation perspective it is a trivial matter of which blend parameters are set on the shader.

**Comment by lexaknyazev** [comment]
While these are perfectly valid use cases, they don't seem to fit PBR Metal-Roughness model (which is glTF 2.0 default material). At some point, even alpha-over was considered to be excluded from spec.

I'd think that something like "effects" material extension should be created for cases like fire or beams.

**Comment by lexaknyazev** [comment]
Given that schema is designed to be forward-compatible, such extension could enable new enum value for `alphaMode` like this:
```json
{
    "materials": [
        {
            "name": "spark",
            "emissiveFactor": [ 1.0, 0.9, 0.8 ],
            "alphaMode": "ADD",
            "extensions": {
                "EXT_material_effects": {
                    "type": "SPARK",
                    "someParameter": 0.5
                }
            }
        }
    ]
}
```

**Comment by memmottse** [comment]
Okay.  That makes perfect sense.  
Thanks.

**Comment by bghgary** [comment]
Sorry for the slow response (just got back from vacation). We didn't include add or multiply for `alphaMode` because it's typically for particle effects which are not currently in the core spec. Without effects, having the ADD mode would seem out of place.

**Comment by andybak** [comment]
> Sorry for the slow response (just got back from vacation). We didn't include add or multiply for alphaMode because it's typically for particle effects which are not currently in the core spec.

Additive transparency has uses far beyond particle effects and it's continuing absence is a real pain point for a lot of real world applications.

**Comment by bghgary** [comment]
> Additive transparency has uses far beyond particle effects and it's continuing absence is a real pain point for a lot of real world applications.

We would need an extension to support this. There was an effort earlier to do something like this: https://github.com/KhronosGroup/glTF/pull/1302. Discussions were on going, but we decided to focus on other priorities at the time. It might be good to voice your concerns there and maybe we can bring it back up.
