### ISSUE TITLE
primitive.material not required, but no default specified and no behavior specified when not set.

### ISSUE THREAD

**Issue by memmottse** [KhronosGroup/glTF#1034]
In my mind we would want this for something like collision primitives, so they just aren't rendered when there is no material set, but the specification does not say either way.

**Comment by donmccurdy** [comment]
Hi @memmottse — Behavior when a material isn't given is defined [here](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#default-material). Specifically, this would mean `pbrMetallicRoughness.baseColorFactor: [1, 1, 1, 1]`.

**Comment by memmottse** [comment]
Sorry, you are correct, I was just looking at the reference section. 
I'll close this.
