### ISSUE TITLE
VRML to glTF what am I doing wrong?

### ISSUE THREAD

**Issue by nbouayad** [KhronosGroup/glTF#1041]
Hello,
I have been working with VRML and GlTf seems promising.
I am writing a converter from VRML to GlTF,but I think that there is something which I am doing wrong because I cannot even convert a simple VRML to GLTF (Please see the attached files,I including a simple vrml, and the coresponding the gltf/bin.
No validation error, but I always get index out of bounds for OGL DrawElement (Using Babylon.js viewer), and I am wondering what am I doing wrong.
Thanks in advance.

[test.zip](https://github.com/KhronosGroup/glTF/files/1153714/test.zip)

**Comment by nbouayad** [comment]
Just a question, does the glb json and bin data must be written in Little Endian too?

**Comment by bghgary** [comment]
@nbouayad The json is text so endianness does not matter. But the buffers must be little endian as well as noted here: https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#binary-data-storage

> Buffer data is little endian.

**Comment by nbouayad** [comment]
Great,I missed that one.Thanks alot!

**Comment by nbouayad** [comment]
Is that also the case for v1?

**Comment by bghgary** [comment]
@nbouayad Yes, I believe this hasn't changed between v1 and v2.

**Comment by nbouayad** [comment]
Fixed,thanks!
