### ISSUE TITLE
VRML material -> GlTf 2.0 material, cannot find a proper way of mapping

### ISSUE THREAD

**Issue by nbouayad** [KhronosGroup/glTF#1042]
Hello,

I am trying to map a VRML material to a GlTf 2.0 material.

A VRML Material (Not talking textures) is defined with the following parameters 

 (Note that all value are between 0f and 1f, values may be set or not)

VRML Ambient Intensity : Float 
VRML Diffuse Color : Float[R,G,B]
VRML Emisive Color : Float[R,G,B]
VRML Shininess : Float
VRML Specular Color : Float[R,G,B]
VRML Transparency : Float

My mapping trial is :

GlTf material.emissiveFactor = VRML Emisive Color
GlTf material.materialPbrMetallicRoughness.metallicFactor = VRML Shininess
GlTf material.materialPbrMetallicRoughness.baseColorFactor = VRML Diffuse Color,1.0f
When VRML  transparency is not 0f
GlTf material.alphaMode = AlphaMode.MASK
GlTf material.alphaCutoff = 1f - VRML  transparency

I still got some VRML parameters not used ,but anyway that does not work,the resulting display is wrong.I also tried the KHR_materials_pbrSpecularGlossiness extension, without success.

On GlTF1.0, I could provide shaders corresponding exactly to that, but now with 2.0, I am not sure.

Thanks for any pointer.

**Comment by donmccurdy** [comment]
Hi @nbouayad - you're probably looking for the KHR_cmnBlinnPhong extension (previously KHR_materials_common). The extension is not finalized, but discussion is ongoing here: https://github.com/KhronosGroup/glTF/issues/947

**Comment by nbouayad** [comment]
Hi @donmccurdy ,problem is that I cannot count on an unofficial extension.Is there a way to blend my parameters to make the material at least looking a bit like the original  model?

**Comment by nbouayad** [comment]
@donmccurdy  Thanks for the answer btw.

**Comment by nbouayad** [comment]
Or, as my parameters are close to the OpenGL library, is there a native extension?

**Comment by bghgary** [comment]
> When VRML  transparency is not 0f
> GlTf material.alphaMode = AlphaMode.MASK
> GlTf material.alphaCutoff = 1f - VRML  transparency

I don't know VRML, but this doesn't seem right to me.  I would expect something more like:
GlTf material.baseColorFactor.a = VRML  transparency
GlTf material.alphaMode = AlphaMode.BLEND

> I also tried the KHR_materials_pbrSpecularGlossiness extension, without success.

Can you elaborate on this or show some screenshots?

**Comment by nbouayad** [comment]
In the case of this model, this does not applies (no transparency) but of course I will be happy to help.
Here is the VRML material:

Material {
					ambientIntensity 1.09756
					diffuseColor 0.82 0.82 0.77818
					specularColor 1.0 1.0 1.0
					shininess 0.59
				}
			}
The GlTF is grey while the VRML looks metallic.

**Comment by nbouayad** [comment]
As far as I see, I am missing ambientIntensity and specularColor,that cannot work.

**Comment by bghgary** [comment]
@nbouayad I'm a bit confused. If you are using the KHR_materials_pbrSpecularGlossiness, your glTF should have an extensions part. Like this in the spec: https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_materials_pbrSpecularGlossiness#extending-materials

**Comment by nbouayad** [comment]
I am not that interested in using any extension,I am just trying to mimic
VRML material using very well know parameters.

**Comment by bghgary** [comment]
@nbouayad I understand. If you can get your material to look close with the spec-gloss, then you can try to convert to metal-rough using an algorithm that I've developed [here](https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_materials_pbrSpecularGlossiness#appendix), but it's going to be a lossy conversion and won't look perfect, but it should look similar.

**Comment by nbouayad** [comment]
Many thanks!I am just wondering why there is no built in extension to call
natine GL functions.In my case,I can translate that into GL calls
easly...Not a critisism.

Le 18 juil. 2017 22:42, "Gary Hsu" <notifications@github.com> a écrit :

@nbouayad <https://github.com/nbouayad> I understand. If you can get your
material to look close with the spec-gloss, then you can try to convert to
metal-rough using an algorithm that I've developed here
<https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_materials_pbrSpecularGlossiness#appendix>,
but it's going to be a lossy conversion and won't look perfect, but it
should look similar.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/KhronosGroup/glTF/issues/1042#issuecomment-316191453>,
or mute the thread

**Comment by nbouayad** [comment]
X3dom is dead,GlTf should try to not do the same (optimized tags are only
generable by a closed source tool,aopt...find the logic for an open source
software).Keep in mind that VRML is widely available as export in all the
major CAD software (industry).

Le 18 juil. 2017 22:47, "Nassim BA" <nassim.bouayad.agha@gmail.com> a
écrit :

> Many thanks!I am just wondering why there is no built in extension to call
> natine GL functions.In my case,I can translate that into GL calls
> easly...Not a critisism.
>

**Comment by nbouayad** [comment]
Right, I could advance on that but I think that I am  having problems with normals.I having black faces.
Even if materials does not match, black faces cannot work.
Please see the files below :
[sample.zip](https://github.com/KhronosGroup/glTF/files/1163430/sample.zip)

sample.wrl : The original VRML
sample.bin + sample.gltf  : The resulting GLTF
sample-vrml-bottom.PNG : Screenshot of the bottom for VRML 
sample-vrml-top.PNG : Screenshot of the top for VRML
sample-glt-bottom.PNG : Screenshot of the bottom for GLTF 
sample-glt-top.PNG  Screenshot of the top for GLTF 

I recompute the normals using normalized sums of face normals.

Thanks



Any help will be appreciated!!!
