### ISSUE TITLE
VRML -> GLTF : Black faces

### ISSUE THREAD

**Issue by nbouayad** [KhronosGroup/glTF#1046]
Hello,
I am writing a VRML to GLTF/GLB conveter.
I am advancing well but I think that I am having problems with normals.I get black faces (I recompute the normals using the normalized sum of faces normals, also tried weighted areas, or weighed angles, but same result).
Even if materials do not match (That is another problem...), black faces look like a bug in my processing (I believe)
Please see the files below (Note that the GLTF mesh is a merge of the VRML shapes) :

[sample.zip](https://github.com/KhronosGroup/glTF/files/1163475/sample.zip)

sample.wrl : The original VRML
sample.bin + sample.gltf : The resulting GLTF
sample-vrml-bottom.PNG : Screenshot of the bottom for VRML
sample-vrml-top.PNG : Screenshot of the top for VRML
sample-glt-bottom.PNG : Screenshot of the bottom for GLTF
sample-glt-top.PNG Screenshot of the top for GLTF

Sorry if It looks dumb, but I am a pragmatic developer, not a 3d expert :)
Any help will be appreciated,I am just stuck.

**Comment by donmccurdy** [comment]
I'm not sure how to help you debug your converter, sorry, but FYI the bufferView `uri` needs to be changed to `sample.bin`. With that change you can preview the model in https://gltf-viewer.donmccurdy.com/.

Here's a version of the model with that corrected:

[sample 2.zip](https://github.com/KhronosGroup/glTF/files/1167004/sample.2.zip)

**Comment by pjcozzi** [comment]
I don't think there are any other actions here.

@nbouayad please keep us posted on your VRML to glTF converter.  We would be happy to list it here: https://github.com/KhronosGroup/glTF#gltf-tools

**Comment by donmccurdy** [comment]
@nbouayad  were you able to get your converter working?
