### ISSUE TITLE
transparency is not clearly exported nor specified

### ISSUE THREAD

**Issue by fabrobinet** [KhronosGroup/glTF#105]
We need specify in "About Shaders" section of the spec how transparency is exported.
Especially when using common profile "details".

The converter needs to be fixed to take into account both A_ONE and RGB_ZERO modes. More mode exists with 1.5 but that would be a good start.

At the moment, only A_ONE is assumed.

**Comment by pjcozzi** [comment]
@tfili any idea what the action would be here?  Is this a converter only issue, perhaps related to #339?

**Comment by tfili** [comment]
Yeah, we would need to change the converter to handle it. We've always needed this change, it just hasn't been that big an issue. I don't think its related to #339. That just looks like a bad exporter since its not using a different `<transparent>` mode, the `<transparency>` is just incorrect.

**Comment by pjcozzi** [comment]
So this is a converter only issue?

**Comment by tfili** [comment]
I think so. It should be in the shader generation. Did you figure out how you are doing the lighting properties for the collada common profile?

**Comment by tparisi** [comment]
Working on it; we're getting close.

**Comment by pjcozzi** [comment]
Pushing post 1.0.

**Comment by pjcozzi** [comment]
Replaced by https://github.com/KhronosGroup/COLLADA2GLTF/issues/105
