### ISSUE TITLE
3dsMax Exporter

### ISSUE THREAD

**Issue by tomspilman** [KhronosGroup/glTF#1053]
I would be best if there was a native 3dsMax Exporter which supported glTF2.  Conversions from Collada or FBX are starting from already flawed data.

**Comment by pjcozzi** [comment]
For sure, we all agree here!

All tool updates will be added here: https://github.com/KhronosGroup/glTF/#gltf-tools

**Comment by pjcozzi** [comment]
Closing as now duplicate with #1077.

**Comment by emackey** [comment]
Issue #1077 became Maya-specific, but it looks like the BabylonJS plugin for 3DS Max can export glTF.  I haven't tried it as I'm not a Max user, but it's linked from the glTF tools section:

http://doc.babylonjs.com/resources/3dsmax_to_gltf

**Comment by donmccurdy** [comment]
https://github.com/facebookincubator/FBX2glTF would be another good option, recently added.

**Comment by zellski** [comment]
Native export is clearly the desired situation — but meanwhile I’m always interested in hearing which forms of content fails to export accurately to FBX for translation.

**Comment by donmccurdy** [comment]
Yeah, FWIW three.js recently dropped its native 3DS Max exporter. It hadn’t been maintained much and wasn’t as reliable as using FBX exports. Would be great to hear results if anyone has been using the BabylonJS plugin or FBX2glTF with Max, agreed.

**Comment by eobet** [comment]
This is closed, but I see no official resolution.

Will there be one?

**Comment by donmccurdy** [comment]
There is one built by the BabylonJS team, with feature support listed at https://github.com/KhronosGroup/glTF/issues/1271 — If you feel that they're lacking important features, or something else is needed, that would be helpful feedback. 🙂

**Comment by alexkowel** [comment]
Verge3D comes with a well-maintained glTF 2.0 exporter for 3ds Max. You can download it [here](https://www.soft8soft.com/get-verge3d/).
