### ISSUE TITLE
Encourage KHX_ prefix?

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#1054]
I wonder if the [extensions page](https://github.com/KhronosGroup/glTF/tree/master/extensions) should encourage the use of the KHX_ prefix for experimental extensions.  Currently, we put out a draft using KHR_ but then end up changing it before it goes through ratification.

I believe @lexaknyazev brought this up before.

**Comment by donmccurdy** [comment]
Is that typically what the KHX_ extension is for? I'd assumed it was for Khronos extensions that were fully ratified, but experimental in some technical way (like a v0 spec).

**Comment by lexaknyazev** [comment]
The KHX story has ended in Vulkan. 
> The KHX author ID was used for experimental extensions, as described in the “Layers & Extensions” appendix of the Vulkan API Specification. As of the initial Vulkan 1.1 public release, all KHX extensions have been promoted to KHR status, and this mechanism is no longer used.

I don't think we need it.

**Comment by donmccurdy** [comment]
Sounds good to me. 👍
