### ISSUE TITLE
Normal Maps Not Working!

### ISSUE THREAD

**Issue by davidpro** [KhronosGroup/glTF#1061]
### Normal Maps are Not Working:

[GLTF2NormalMapsTest.zip](https://github.com/KhronosGroup/glTF/files/1202901/GLTF2NormalMapsTest.zip)

* Maya 2014 x64
* Plugin For Export from Maya to Collada [COLLADA-MAYA-PC-2014 v1.6.58](https://github.com/KhronosGroup/OpenCOLLADA/releases)
* Collada2Gltf [COLLADA2GLTF-2.0-windows-Release-x64](https://github.com/KhronosGroup/COLLADA2GLTF/releases)

Somewhere in the Asset Conversion Pipeline there is an error due to which Normal Maps are not working in gLTF! Can someone check what needs to be done to fix that? I have provided all the files for checking!

**Comment by pjcozzi** [comment]
@davidpro is this duplicate with https://github.com/KhronosGroup/COLLADA2GLTF/issues/67?  If you think this is a COLLADA2GLTF bug, it should just be an issue in that repo.

As a workaround, you could try importing into Blender and then exporting to glTF using https://github.com/KhronosGroup/glTF-Blender-Exporter

**Comment by pjcozzi** [comment]
Feel free to comment in the COLLADA2GLTF repo if you think this is a bug there.
