### ISSUE TITLE
direction property missing in KHR Material Common/KHR lights spec. tables

### ISSUE THREAD

**Issue by andreasplesch** [KhronosGroup/glTF#1063]
##This is a late note for the glTF 1.0 KHR Material Common extension spec. draft.

https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_materials_common#directional
mentions a ```direction``` property as being described in table 2.

However, table 2 (https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_materials_common#common-light-shared-properties) does not include such a property.

The direction is presumably the constant (unit) vector along which the light wave front propagates (imagening an infinitely distant light source).

Rather than a 3d vector, the direction could also be described as a rotation/quaternion of an initial (default) direction (often 0,0,-1). This may mean that the direction is superfluous as it could be defined as 0,0,-1 and then the light be rotated by an associated transform if necessary. (Perhaps this is the reason why direction was not specified in table 2??).

#947 has discussion on the glTF 2.0 version of the extension which presumably will include a similar table.

If there is interest, I could prepare a quick PR for table 2 as a starting point until 2.0 is fully established.

**Comment by stevepg** [comment]
personally,  I don't think the material_common definition should include anything about lights.

**Comment by andreasplesch** [comment]
I agree. I think there is a separate KHR-lights extension for 2.0 (?). There may still be a need for an addendum for v.1.0 users since the draft here became the defacto standard. But there may be no appetite to put any effort into improving 1.0. In this case, this issue may become a reference and I propose ```direction``` to be specified as a unit 3d vector which can be used as the 'Light vector L'  in the shading equations.

**Comment by andreasplesch** [comment]
#945 describes a new KHR-lights extension. Incidentally, https://github.com/UX3D-nopper/glTF/tree/master_lights_blinnphong/extensions/Khronos/KHR_lights#light-types also misses the direction property which is referred to in https://github.com/UX3D-nopper/glTF/tree/master_lights_blinnphong/extensions/Khronos/KHR_lights#directional

**Comment by donmccurdy** [comment]
Yes, #945 is the best reference for `KHR_lights`. Direction is simply the orientation of the node to which the light is attached, so it doesn't require an extra property. Although probably the spec should define that a directional light's base direction is "down" (or whatever it actually is), and any parent node orientation transforms that.

**Comment by andreasplesch** [comment]
Ok, very helpful. That is a definite statement and needs to be explicit since currently the spec. does define an extra property, and I would have expected -Z as the base direction.

**Comment by donmccurdy** [comment]
Oh, hah, well I could also be wrong... My implementation uses `-Z` as the base direction after all, and does not check for this mysterious `direction` property. In any case we should certainly clarify this. Realistically I think that clarification needs to happen in the `KHR_lights` extension, rather than amending the glTF1.0 spec at this point. Suggestions on any other issues with #945 are welcome, also. 🙂

**Comment by McNopper** [comment]
It is -z,  as stated here (see GL_POSITION section):

https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glLight.xml

**Comment by pjcozzi** [comment]
Is this now duplicate with #945?

**Comment by andreasplesch** [comment]
Yes, let me close this. I think this is resolved as -z plus transform.
