### ISSUE TITLE
Spec: Inconsistency about requirement of asset

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF#1064]
In the [Asset](https://github.com/KhronosGroup/glTF/blob/5f3419be34973edf23c701927e1bae9d6d841bda/specification/2.0/README.md#asset) section, the spec says

> Each glTF asset must have an `asset` property. In fact, it's the only required top-level property for JSON to be a valid glTF.

However, in the [properties reference](https://github.com/KhronosGroup/glTF/blob/5f3419be34973edf23c701927e1bae9d6d841bda/specification/2.0/README.md#reference-gltf), `glTF.asset` is marked as not required.

**Comment by bghgary** [comment]
The properties reference is generated by [wetzel](https://github.com/AnalyticalGraphicsInc/wetzel).

The schema correctly indicates that `asset` is required. https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/glTF.schema.json#L153

I'll file an issue on wetzel.

**Comment by pjcozzi** [comment]
@bghgary in the meantime, do you want to just manually patch the spec?

**Comment by bghgary** [comment]
@pjcozzi Sure

**Comment by bghgary** [comment]
@pjcozzi Should we close this issue or wait until wetzel bug is fixed?

**Comment by pjcozzi** [comment]
For sure, thanks for the fix, @bghgary.

@scurest thanks again for submitting the spec bug!  Please let us know of other things you run into and also feel free to open pull requests with minor edits.
