### ISSUE TITLE
spec documentation nitpick

### ISSUE THREAD

**Issue by Alloyed** [KhronosGroup/glTF#1067]
I am implementing a glTF loader library, but have little-to-no experience with the openGL API (hi~). while my target does use opengl under the hood, I am using the higher-level API provided, so I've got to do a little mental decompiling to get my higher-level primitives to match the lower-level ones glTF seems to be built around.

So I was a little thrown off by the fact that the spec uses the terms wrapS and wrapT in the samplers without ever defining what S and T are. it'd be nice to have a little note that explains that S means U means the horizontal axis and vice versa.

**Comment by pjcozzi** [comment]
Thanks for the input @Alloyed!  If you have the time, we would welcome a pull request with a small clarification to the spec.

**Comment by pjcozzi** [comment]
Thanks again @Alloyed!

@lexaknyazev updated in the spec in #1126.
