### ISSUE TITLE
2.0 specification is unclear on how lights should be handled

### ISSUE THREAD

**Issue by Kupoman** [KhronosGroup/glTF#1068]
As far as I can tell, the [2.0 spec](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md) does not mention how to export lights. From my understanding lights should be handled through the [KHR_lights](https://github.com/KhronosGroup/glTF/issues/945) extension. However, this looks like it is still in progress, and is not even mentioned in the [extension registry](https://github.com/KhronosGroup/glTF/tree/master/extensions).

This leaves me with two questions. How should lights be handled for glTF 2.0, and should documentation be updated to answer this question?

**Comment by donmccurdy** [comment]
As you point out, the `KHR_lights` extension is still in progress. In the absence of that extension, there is no way to include lights with a glTF 2.0 asset. But this extension is fairly close to ready, and high-priority, so I think we will have that moving along soon. Suggestions on the open issue for KHR_lights, including docs/wording, would be very welcome. :)

**Comment by FuzzyWuzzie** [comment]
What I don't get is why lights are relegated to an extension, while cameras and PBR materials are built into the spec. Pretty hard to render a scene with 0 lighting information, and the placement and use of lights is roughly similar to cameras—there's an effective standard way to do things (perspective camera, othographic camera vs point light, spot light, directional light).

If something as highly specific as PBR shading is included in the spec, why not something more universal and general like lights?

**Comment by pjcozzi** [comment]
@FuzzyWuzzie I believe it is because most engines will have their own lighting system, and may want to ignore the "scene" lights in an asset, but probably would want to include things like, for example, a car's headlights.

If the extension becomes widely used, it would be promoted to core spec.

**Comment by pjcozzi** [comment]
For the lights extension discussion, please chime in at #945.
