### ISSUE TITLE
Specify version format

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF#1072]
The spec currently says nothing about the format of the `version` and `minVersion` properties, not even that, eg. for the current spec, glTF files should use `"2.0"` (though it does give that in an example).

This means an implementation doesn't actually have enough information to "ensure both major and minor versions can be supported" as the spec says it should; even the meaning of "major version" and "minor version" is undefined. This is also a forwards compatibility hazard since an implementation can't know if it is compatible with a theoretical future 2.X if it doesn't actually know what format this spec might specify for its `version`.

I think this should specified in more detail. It'd even be nice to change the implementation note about how to check `minVersion` and `version` into psuedo-code for the check (in an appendix maybe).

**Comment by bghgary** [comment]
The format is specified, but it is currently hidden in the schema: https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/asset.schema.json#L19

A PR to improve the readme text would be appreciated.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by scurest** [comment]
I should obviously be checking the schema more :)

Some of the 1.0 sample models don't match this pattern by the way: eg. [Avocado](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/1.0/Avocado/glTF/Avocado.gltf) uses `"1.0.1"`. Is that okay?

**Comment by bghgary** [comment]
In 1.x, the version was not strict like in 2.0. You can assume the asset is not a 2.x asset if the version doesn't match the 2.0 schema pattern.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lexaknyazev** [comment]
Do we need to make README more descriptive?

**Comment by sbtron** [comment]
Closing this.
Created a wetzel issue for showing regex pattern in generated markdown.
