### ISSUE TITLE
Implementation of sparse accessors

### ISSUE THREAD

**Issue by javagl** [KhronosGroup/glTF#1074]
I'm currently working<sup>1</sup> on sparse accessors, and wonder what the intended implementation of sparse accessors based on OpenGL should look like.

The most important point for now: Is it valid to assume that the portion of a `bufferView` that is referred to by a sparse accessor has to be *duplicated*? 

Consider the following layout:

    bufferView    |0|1|2|3|4|5|
                  |     |\    |\
                  |     |  \  |  \
                  |     |    \|    \
    accessors     | a0  | a1  | a2  |
   
There is one `bufferView`, and three accessors referring to it. The accessors `a0` and `a1` are "dense" accessors. So far so good, business as usual (i.e. as in glTF 1.0). 

But now comes the accessor `a2`. It refers to the *same* portion of the `bufferView` as `a1`. But assume that `a2` is a **sparse** accessor that actually modifies some of the elements. I think that the respective part of the `bufferView` has to be duplicated before being used. That is: It has to be "instantiated" as a separate buffer with a dedicated `glBufferData` call, before it is used as a vertex attribute with `glVertexAttribPointer`. Otherwise, this part of the buffer would have to be modified and restored, possibly repeatedly, during one rendering pass, and I can't imagine how this could sensibly be implemented.

So is it correct that the part of a `bufferView` that is referred to by a sparse accessor has to be "instantiated" as a dedicated GL buffer, once for each sparse accessor that refers to it?

---

<sup>1</sup> "working" here means: 

- Trying to understand them
- Trying to implement them
- Trying to create a `SimpleSparseAccessor` sample model - AFAIK, there currently are **no** sample models using sparse accessors *at all*, and likely no implementations that support them - at least, three.js and babylon.js do not seem to handle them until now

**Comment by lexaknyazev** [comment]
> So is it correct that the part of a `bufferView` that is referred to by a sparse accessor has to be "instantiated" as a dedicated GL buffer, once for each sparse accessor that refers to it?

It doesn't have to be a new _GL_ buffer, but in general, yes. Sparse accessor operates on the copy of original data. glTF-Validator understands sparse accessors and validates their content.

**Comment by javagl** [comment]
Thanks. 

(There may come up more questions, but this was the most important one for now, so I'll close this and reopen it if necessary)
