### ISSUE TITLE
`IOR` PBR suggestion

### ISSUE THREAD

**Issue by ghost** [KhronosGroup/glTF#1079]
Hello. I suggest two parameters for glTF. Extension: `KHR_materials_pbrDensityIor` (formely `PSM_materials_pbrDensityIor` i.e. *prismarine* render library).

- `densityIorTexture` and `densityIorFactor` (vec3) - IOR of surface, can be used with plastic, non-metallic surfaces, density is something alike subsurface scattering (insider diffuse), it means how much clear surface Insider, third parameter I have no idea
- `baseColorFactor` and `baseColorTexture` (RGB i.e. vec3) - filtering of transparency, not refracted/promised light will reflected or absorbed. 

In general, can be combined with `pbrMetallicRoughness` or specular glossy system. I suggest it, because most engines uses IOR and transparency parameters.

**Comment by emackey** [comment]
We're gathering suggestions for next-gen glTF material settings in #1442.  Merging this issue there, please chime in there with additional comments or suggestions.
