### ISSUE TITLE
glTF 2.0 convention naming

### ISSUE THREAD

**Issue by KageKirin** [KhronosGroup/glTF#1080]
Hello,

I was wondering if there were specific names for a number of glTF (2.0) format conventions.
I.e., from the sample assets, we have "embedded" for assets that contain everything inside the JSON (data and images encoded in base64) and "binary" for glb files.

Are there other conventions already in use?

How would you call the following conventions?
1. glTF file contains:
  - 1 single buffer (i.e. just like glTF-binary) containing only vertices, indices and IBMs
  - all images as URI referencing external files
  - no base64 encoded data
2. as extension of the above:
  - vertex data as interlaced bufferview with several accessors to each vertex attribute set.

Best regards.

**Comment by pjcozzi** [comment]
I don't think we have any formal or defacto names for the two cases you mentioned.

**Comment by KageKirin** [comment]
Internally, I'm going with the following terms:
1. *glTF-lean*: single buffer for vertex attributes, indices and IBMs, and images referenced through URIs to external files
2. *glTF-lean-interleaved*: the vertex data is interleaved, i.e. several Accessors on the same BufferView containing vertex attributes.

If you have a better naming convention, please don't hesitate to share it. Thanks.

**Comment by pjcozzi** [comment]
I don't think there are any more actions here.
