### ISSUE TITLE
computing jointMatrix of skins with a skeleton node

### ISSUE THREAD

**Issue by shrekshao** [KhronosGroup/glTF#1085]
This issue is a question:

The joint matrix can be computed as the formula: 
`jointMatrix[j] = inverse(globalTransform) * globalJointTransform[j] * inverseBindMatrix[j];`

Then if a `skin` has a `skeleton` property, meaning the root of the skeleton is a node instead of the scene root. Does this have effect on the computation of `jointMatrix`? Do I need to multiply some matrix? It seems to me that it doesn't have any impact on the computation, but I'm not sure if my understanding is correct.

Thank you!

**Comment by pjcozzi** [comment]
@shrekshao sorry no one got back to you here.

@lexaknyazev likely knows off the top of his head.

**Comment by shrekshao** [comment]
Based the results shown by my implementation, this doesn't have an impact on the matrix computation... Not sure the reason for it being there. But not a problem for me. I posted this as a question at first and it didn't bother me too much for now.
