### ISSUE TITLE
The default values for metalness

### ISSUE THREAD

**Issue by javagl** [KhronosGroup/glTF#1088]
The default values for textures that are not present are defined to be 1.0, according to [the spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#metallic-roughness-material)

>  If a texture is not given, all respective texture components within this material model are assumed to have a value of 1.0

The default value for `pbrMetallicRoughness.metallicFactor` is defined to be 1.0 as well (see https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#pbrmetallicroughnessmetallicfactor )

Yet, in the implementations that I have seen so far (e.g. also in the reference implementation at https://github.com/KhronosGroup/glTF-WebGL-PBR/blob/master/shaders/pbr-frag.glsl ), the computations for the diffuse colors usually involve lines like these:

    float metallic = u_MetallicRoughnessValues.x;
    metallic = valuesSampledFromMRTexture.b * metallic;
    diffuseColor *= 1.0 - metallic

which basically means that a material that has **all default** values will barely be visible: Its diffuse color will be multiplied with 0.0. 

For example, an "empty", "default" material that only refers to a texture...
```
 {
    "pbrMetallicRoughness" : {
      "baseColorTexture" : {
        "index" : 0
      }
    }
  }
```
will basically be invisible. In order to see *anything*, one has to set the `metallicFactor` to 0.0:
```
{
    "pbrMetallicRoughness" : {
      "baseColorTexture" : {
        "index" : 0
      },
      "metallicFactor" : 0.0
    }
  }
```

This doesn't seem like a sensible default to me. 

However, I know that it will hardly make sense to try and change this now, considering the implications on ratification etc. 

I just wanted to point this out, and ask whether there is a convincing reason of why these defaults have been chosen (except for some sort of "consistency" with other defaults, where the 1.0 makes perfectly sense)

**Comment by Kupoman** [comment]
#940 contains a brief discussion about the default value for metallicFactor and why a default of 1.0 is useful.

Also, while the diffuse color will be 0.0, the baseColor data will be used for specular color if the metallicFactor is 1.0.

**Comment by pjcozzi** [comment]
@javagl any action required here?

**Comment by donmccurdy** [comment]
I'm not sure it's clear that the 'default material' needs to be a physically meaningful one; the default values are also relevant to unnecessary data in the file, ensuring that textures are visible by default, and so on. 

Closing this issue for now, but we can reopen if needed.
