### ISSUE TITLE
KHR_materails_common is listed incorrectly

### ISSUE THREAD

**Issue by DrX3D** [KhronosGroup/glTF#1089]
The KHR_materials_common draft spec (https://github.com/KhronosGroup/glTF/blob/master/extensions/Khronos/KHR_materials_common/README.md) is written against glTF draft 1.0; however, it is listed as an extension for glTF 2.0 (https://github.com/KhronosGroup/glTF/tree/master/extensions). 

Either the link location needs to change or the document needs to be updated to V2.0.

**Comment by DrX3D** [comment]
Issues #947 & #1063 also cover materials_common, but (as far as I can tell) don't mention the mis-listing of the link.

**Comment by donmccurdy** [comment]
IMO the links should perhaps be removed until more stable v2.0 drafts exist. In both of these cases, it feels a bit early to list these as drafts.

**Comment by pjcozzi** [comment]
OK with me to remove, list as in progress, etc.

@donmccurdy can you open a PR for whatever you think is reasonable?
