### ISSUE TITLE
May primitives of a single mesh have different modes?

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF#1090]
I see nothing in the spec to say otherwise, so presumably it would be valid to have a single mesh containing combinations of points, lines, and polygons.

That case seems unlikely to me, and it's not part of the stated goal for primitives:

> Splitting one mesh into primitives could be useful to limit number of indices per draw call.

Do we want to consider adding an implementation note advising against this, and perhaps disallow it in a future version of glTF? Or is there a use case I'm missing?

**Comment by donmccurdy** [comment]
Along the same lines, should it be recommended and/or required that each primitive in a single mesh defines the same attribute types?

**Comment by recp** [comment]
glTF 2.0 says: 

> Each primitive also specifies a material and a primitive type that corresponds to the GPU primitive type (e.g., triangle set).

So I think each primitive can define same or different mode and attribs, why not? One primitive could be tirangles and one another could be triangle fan or triangle strip... One primitive could contains NORMALs and another one could not (to calc flat normals). 

Also there is "Application-specific semantics" term ; if a primitive uses custom semantic for custom shader and other primitives use common materials, I think forcing all attribs to be same may not be good idea here

I think mesh/primitive definition is ok as it is, except POSITION; maybe all primitives must contain POSITION attrib or only one POSITION allowed per mesh like this:

```
{
    "meshes": [
        {
            // common attribs like COLLADA's <vertex>
            "attributes": {
                        "POSITION": 22
             },
            "primitives": [
                {
                    // per primitive attribs
                    "attributes": {
                        "NORMAL": 23,
                        "TANGENT": 24,
                        "TEXCOORD_0": 25
                    },
                    "indices": 21,
                    "material": 3,
                    "mode": 4
                }
            ]
        }
    ]
}
```

**Comment by donmccurdy** [comment]
> So I think each primitive can define same or different mode and attribs, why not? One primitive could be tirangles and one another could be triangle fan or triangle strip... One primitive could contains NORMALs and another one could not (to calc flat normals).

Yeah, that sounds like the correct way to interpret the spec as it is currently written.

> ... maybe all primitives must contain POSITION attrib or only one POSITION allowed per mesh like this:

Simpler as it is; primitives aren't necessarily going to share the same POSITION data. 

***

From the spec:

> ... engines are, of course, free to batch draw calls ...

I had been planning to do some optimizations in three.js based on a mistaken assumption that primitives would share draw mode and attribute types. Sounds like I was incorrect, so IMO it might be nice to add an implementation note.

**Comment by pjcozzi** [comment]
@donmccurdy couldn't you just add a fast path when you detect that all primitives have the same type, attributes, etc?

**Comment by donmccurdy** [comment]
> Couldn't you just add a fast path when you detect that all primitives have the same type, attributes, etc?

That's possible yes. In any case it's good to know what is permitted. I'd be curious what other engines end up doing with primitives, but for now i think this issue can be closed.
