### ISSUE TITLE
"mode" missing in some sample models.

### ISSUE THREAD

**Issue by blitz-research** [KhronosGroup/glTF#1092]
Hi,

Have a look through the sample models, and some appear to be missing the "mode" property for the mesh primtives which is usually "4" for triangles. Is this different now for gltf2.0? Some models have it OK.

For example, I can't find "mode" at all in either the corset.gltf or BarramundiFish.gltf files:

https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Corset/glTF/Corset.gltf
https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/BarramundiFish/glTF/BarramundiFish.gltf

Bye!
Mark

**Comment by alteous** [comment]
The [default is 4](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#primitive). It's not a mandatory property in glTF 2.0.

**Comment by pjcozzi** [comment]
@blitz-research OK to close this?

**Comment by blitz-research** [comment]
Is this docced? I did look...

**Comment by bghgary** [comment]
@blitz-research Yes, it's not in the main section of the spec, but it is specified in the properties reference  as @alteous pointed out in his comment and the [json schema](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/mesh.primitive.schema.json#L27).

**Comment by blitz-research** [comment]
Ok, might be nice if it was also mentioned here though?

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#geometry

**Comment by bghgary** [comment]
@blitz-research The main text of the spec doesn't typically indicate default values as there are a lot of them. Feel free to open a PR with modified wording if you feel strongly about it.
