### ISSUE TITLE
Node hierarchy clarification

### ISSUE THREAD

**Issue by recp** [KhronosGroup/glTF#1096]
Hi,

Recently I got some free time and started to implement glTF 2.0 in AssetKit (http://github.com/recp/assetkit).

I've confused about glTF's node hierarchy,  references are 
representing as array indices, this is clear but the part 
I don't understand is that why child nodes are representing as array indices?

wouldn't something like this be more clear?:

```JSON
"nodes": [
  {
      "mesh": 0,
      "children": [
        {
           "mesh": 1
        },
        {
           "mesh": 2
        },
      ]
  }
]
```

> "That is, no node may be a direct or indirect descendant of more than one node."

```JSON
{
    "nodes": [
        {
            "name": "Car",
            "children": [1, 2, 3, 4]
        },
        {
            "name": "wheel_1"
        },
        {
            "name": "wheel_2"
        },
        {
            "name": "wheel_3"
        },
        {
            "name": "wheel_4"
        }        
    ],
   "scenes": [
        {
            "nodes": [
                0 
            ]
        }
    ],
    "scene": 0
}
```

In this case; can `scene` pick `wheel_1` node as root node ("scene": 1)? 
Is it valid **(because wheel_1 is child node of nodes[0])**? 

I implemented like this; I moved all referenced child nodes inside node, 
since I'm confused I'm considering to set child nodes as instance node (just pointer) instead of moving,
in this way referenced nodes will still remain in same index as ROOT node

**Comment by emackey** [comment]
This is similar to the first question in #1086.

**Comment by javagl** [comment]
The second part of the question is certainly related to #1086 , and will hopefully clarified there.

Regarding the general approach, I can think of some points that may justify the current structure:

- Directly "linlining" the child nodes **in** their parent note might be easier to parse (for humans as well as for libraries), but I could imagine that this avantage vanishes when the node hierarchies become deeper. (It *might* then even become a disadvantage, in terms of performance, but this is just a guess)
- Having all nodes in a flat array allows modeling more than just trees. The section at https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#nodes-and-hierarchy says (emphasis by me):

  > For Version 2.0 conformance, the glTF node hierarchy is not a directed acyclic graph (DAG) or scene graph, but a strict tree. That is, no node may be a direct or indirect descendant of more than one node. This restriction is meant to simplify implementation and facilitate conformance. **The restriction may be lifted later**.

- Most importantly: Nodes can be referenced when they are in an array. In the structure that is shown in your first code snippet, it would nearly be impossible to refer to one of the child nodes, for example, in an animation, to modify its `rotation` or so. There are several places where nodes are referenced, and now, this can easily be done via the node **index**. If they were "inlined", one would need odd workarounds like name-based lookups or even tree paths to identify the relevant node.

**Comment by stevenvergenz** [comment]
Hmm, an interesting wrinkle to the strict tree definition here: can different scenes refer to the same nodes? Wouldn't that violate the strict tree requirement?

```json
"nodes": [
    {"position": [0,1,0], "children": [2,3]},
    {"position": [1,0,0], "children": [2,3]},
    {"mesh": 0},
    {"mesh": 1}
],
"scenes": [
    {"nodes": [0]},
    {"nodes": [1]}
]
```

**Comment by lexaknyazev** [comment]
@stevenvergenz 
I'd say that this structure violates spec because node hierarchy isn't scoped by scenes (at least for now).

**Comment by recp** [comment]
@emackey @javagl thanks, I read #1086 and  then I think I understand  glTF's node hierarchy more clearly

[AssetKit](https://github.com/recp/assetkit) is based on COLLADA specs, and  I modified the structure for glTF to make it more clear and easy to use.  One structure will full support COLLADA 1.4, 1.5+ and glTF 2.0+

So like many other engines my library is scene graph, I need to build/fill scene graph from glTF nodes. I was confused until now. 

My main confusion was abut ownership of child nodes?  I assumed parent nodes will have ownership of child nodes.  **It means that I can make child nodes inline in parent nodes**

like @javagl's example:

```
0
+- 1 // 1 appears only as child of 0
|  +-2
|  +-3
|
+- 4
   +-5
   +-6
```

Confusion (alternative way(for runtime)), maybe it is just implementation related, I don't know.

In this case 1,2,3,4,5 still remain as root nodes,  node-0 just instanced them

```
0
   +-1    // 1 appears as chilf of 1. 0 doesn't have ownership of 1 (instance-node)
1         // also appears as individual (root node). 
   +-2  
   +-3
2
3
4
   +-5
   +-6
5
6

scenes can still access to nodes by indices
```

It looks like weird/stupid but my node data structure has **child nodes** and **instance nodes** term like COLLADA. A node may reference another (even in another scene or document) without having ownership of them, by this; nodes may be re-used in many places, this will save space...

In my implementation, I inlined child nodes into parent like example 1. The second would also work but I didn't want to mak them as instance to avoid extra function call to find actual node...

**Now importing works fine, but I need to test it with more complex files.** 👍

> Most importantly: Nodes can be referenced when they are in an array. In the structure that is shown in your first code snippet, it would nearly be impossible to refer to one of the child nodes, for example, in an animation, to modify its rotation or so. There are several places where nodes are referenced, and now, this can easily be done via the node index. If they were "inlined", one would need odd workarounds like name-based lookups or even tree paths to identify the relevant node.

I'm ok with **id** (names are not uniuqe) lookups because I have already an id tree for document :) I created an **id** for every gltf node(in later I may change this to only referenced nodes) by their indices like node0, node1, node2.... this makes references  unbroken and clear. They will be accessed by their id and this maybe slower than accesing by indices, in some places after resolved id/url I'm caching the target pointer so it seems enough for now.

**Comment by recp** [comment]
> Hmm, an interesting wrinkle to the strict tree definition here: can different scenes refer to the same nodes? Wouldn't that violate the strict tree requirement?

I think scene.nodes is just **pointer**s array of **root** nodes (in my case instance nodes) not array of nodes, so in this case I think different scenes may refer to same nodes at the same time

**Comment by pjcozzi** [comment]
Any action here?  Any spec clarifications or potential tutorial updates?

**Comment by lexaknyazev** [comment]
Node hierarchy definitions have been clarified with #1358.
There's no notion of "node instancing" in glTF 2.0, i.e., a parent owns all its child nodes.
