### ISSUE TITLE
Binary glTF length confusion

### ISSUE THREAD

**Issue by ethanjyx** [KhronosGroup/glTF#1101]
Hey there,
I have some confusion about the binary glTF format. In the spec https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#header it says:

```
The 12-byte header consists of three 4-byte entries:

uint32 magic
uint32 version
uint32 length
```

so I tried to get the header information by reading the binary file with php:
```
localhost> =file_get_contents('/home/jyx/glb/Duck.glb', false, null, 0, 12)
"glTF\001\000\000\000\324\035\002\000"
```
Version seems to be 001 which makes sense since it is glTF 1.0.
Is the length 324035002 here?

When I try to get the filesize from PHP, I got:
```
localhost> =filesize('/home/jyx/glb/Duck.glb')
138708
```
the value becomes 138708 which is different from above.

**Comment by lexaknyazev** [comment]
For glTF 1.0, please refer to [KHR_binary_glTF](https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_binary_glTF) extension.

Version and Length are written as 32-bit little-endian unsigned integers. 
First 12 bytes of v1.0 Duck.glb are:
```
0x67, 0x6C, 0x54, 0x46 - "glTF" ASCII string
0x01, 0x00, 0x00, 0x00 - 1
0xD4, 0x1D, 0x02, 0x00 - 138708
```

**Comment by scurest** [comment]
Those escaped sequences are in [octal](https://en.wikipedia.org/wiki/Octal). The first one is 0o324 = 212, the second is 0o035 = 29, the third is 0o002 = 2 and the fourth is zero. So reading them in LE order gives 212 | (29 << 8) | (2 << 16) = 138708.
