### ISSUE TITLE
Shared vertex buffers between distinct skinned meshes

### ISSUE THREAD

**Issue by AurL** [KhronosGroup/glTF#1107]
Hi, 

Since glTF 2.0, `bindShapeMatrix` has been removed and should be premultiplied to Inverse Bind Matrices or mesh data, but in some cases it now requires data duplication.

In this sample, geometry data (except joint/weights) are shared between all the cubes and skeletons are distincts: 
![image](https://user-images.githubusercontent.com/4066133/30802258-29a78948-a1e6-11e7-9ec8-1cd863f2fb85.png)

We have two solutions:
- bake the bindShapeMatrix data into invBindMatrices: skins need to be duplicated, and it can be an issue (for example on Sketchfab we would need to duplicate bones)
- bake the bindShapeMatrix into mesh data: shared buffers need to be duplicated.

In both cases, we need to duplicate one or the other, depending on how the engine handles the data at the end.

Is there any workaround with this? Any hint?

Thanks in advance

**Comment by AurL** [comment]
Also, while working on glTF animation export, I spotted a case that doesn't seem to be supported by the current specification, due to the fact that transformation from mesh space to bone space is "frozen" in inverseBindMatrices.

Let's consider this [blender sample](https://github.com/KhronosGroup/glTF/files/1332735/animatedRig.zip) with a cube that is skinned but also animated by solid animation.
This case is easily reproductible in Blender, and gives this result:

![animatedrig](https://user-images.githubusercontent.com/4066133/30855161-45bc8380-a2b4-11e7-8bd8-41a2fee21c3d.gif)

I could agree that it's kind of an edge case, that it could be ok with 98% of the models, and I don't see any reason to use such trick (even if it's supported on Sketchfab), but I think it is worth mentioning it. 
Maybe some of you have already dealt with such models.

**Comment by pjcozzi** [comment]
@AurL sorry for the slow response.

@lexaknyazev do you know?

**Comment by pjcozzi** [comment]
Let's move the discussion to #1285 for a potential advanced skinning solution in the future.
