### ISSUE TITLE
Meshes/nodes in joints hierarchy

### ISSUE THREAD

**Issue by AurL** [KhronosGroup/glTF#1108]
Hi, 

Tell me if I'm wrong, but the specification doesn't seem to allow having regular nodes/meshes in a joint hierachy (or it's maybe not clear), and we have a lot of samples on Sketchfab in this case.

If it's actually not allowed, what's the main reason of this restriction?
If we take the simple case of a mesh, a possible workaround would be to consider it as a skinned mesh and fill a `JOINTS_0` accessor with the index of the parent bone and `WEIGHTS_0` with only 1's, but it's not ideal.

Any hint on this?

Thanks in advance

**Comment by lexaknyazev** [comment]
@AurL
> the specification doesn't seem to allow having regular nodes/meshes in a joint hierachy

There's no such restriction. Please, point out what in spec makes you think so.

**Comment by AurL** [comment]
I'm thinking about [this part](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#joint-hierarchy), or just "joint hierarchy" that could mean that it's restricted, but I guess that my understanding might be biased by the restrictions mentionned in [this comment](https://github.com/KhronosGroup/glTF/issues/723#issuecomment-254674004), that have not been applied.

**Comment by Nehon** [comment]
I think specifications could use a clarification on this, and maybe some implementation guidelines, as it seems to be a confusing point ( for example in this issue https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/74).

**Comment by pjcozzi** [comment]
Does anyone want to open a pull request to clarify the spec here?

**Comment by Nehon** [comment]
Hello, I created a PR.

**Comment by pjcozzi** [comment]
Cool, thanks @Nehon!

**Comment by pjcozzi** [comment]
@AurL thanks again for the report.  @Nehon added a note in #1200.

**Comment by donmccurdy** [comment]
@AurL any chance you could clarify the types of samples where this occurs on Sketchfab? Are these all cases where regular nodes or meshes are children of a joint hierarchy, or can you think of a case where regular nodes would be sandwiched between joints? Example:

![screen shot 2018-07-09 at 10 59 16 am](https://user-images.githubusercontent.com/1848368/42470099-611c6186-836e-11e8-83b7-70c31672a277.png)
