### ISSUE TITLE
Validator - Position accessor without bounds and Morphs targets

### ISSUE THREAD

**Issue by noalak** [KhronosGroup/glTF#1112]
Hi,

Issue:
Wrong validator error message and wrong validation when mesh has morph targets

To reproduce:
Use the AnimatedMorphCube.gltf file inside glTF samples. Validation => OK
Remove the min and max properties of the very first accessor (which is the **normal** accessor of the **base mesh**).
Validation =>
"type": "MESH_PRIMITIVE_**POSITION**_ACCESSOR_WITHOUT_BOUNDS",
"path": "#/meshes/0/primitives/0/**targets**/0/POSITION",

Comments:
Why the error message is talking about **position** when i modified the **normal** accessor?
Why a change on the **base mesh** accessor has consequence on the **morph target** accessor?
Why the min and max properties of the normal accessor of the base mesh are 'required' when using morph targets but not otherwise ?

Attached the gltf file:
[AnimatedMorphCube.zip](https://github.com/KhronosGroup/glTF/files/1349133/AnimatedMorphCube.zip)

Noalak

**Comment by lexaknyazev** [comment]
@noalak 
Thanks for the bug report. That was an issue with validator and it has been fixed. [Online hosted version](http://github.khronos.org/glTF-Validator/) has been updated (you may need to force-reload webpage with Ctrl-F5).

For future validation issues, please use [glTF-Validator](https://github.com/KhronosGroup/glTF-Validator/issues) repo.
