### ISSUE TITLE
Annotation/classifcation/semantic extension for Machine Learning community

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#1121]
Just came across https://www.shapenet.org/, which is a repo of models and per-model/per-mesh classification.  The models are available as OBJ+MTL.

Perhaps glTF would be very useful here, especially with an extension to include the classifications.

Anyone from the ML community interested? :grinning:

**Comment by themmes** [comment]
I came across the glTF format because of this issue. Classifications/semantics would be very useful. Maybe some inspiration; the CityGML standard (or personal preference the jsonified version: http://www.cityjson.org/en/0.3/).

**Comment by pjcozzi** [comment]
Duly noted. :+1:

If you experiment with any ideas here, please let us know!

**Comment by pjcozzi** [comment]
This is still a great idea, but perhaps OK to close until there is a concrete proposal?
