### ISSUE TITLE
Vendor extension request: GOOGLE

### ISSUE THREAD

**Issue by timgoog** [KhronosGroup/glTF#1123]
Please add a "vendor extension prefix" for Google.

**Comment by pjcozzi** [comment]
@timgoog added in #1124.  Really looking forward to your work with glTF!  Thanks for your contributions.

**Comment by aaronfranke** [comment]
Where can we find specs for the `GOOGLE_` extensions? There aren't any PRs in this repo, and the contact information may as well be non-existent (how do I get from the front page of Google to contacting Google about glTF?).

**Comment by lexaknyazev** [comment]
Many prefixes were reserved just for name and/or scope protection without any publicly available extensions.
