### ISSUE TITLE
Cesium_RTC reference links broken

### ISSUE THREAD

**Issue by nitrologic** [KhronosGroup/glTF#1132]
The links provided in the CESIUM_RTC extension README named Ohlarik08 are broken.

It is difficult to understand the value to the GLTF specification of adding a center position for an asset using an **application specific** coordinate system. 

The inference that vertex positions are not already relative to center of model and that model center position is not already controlled by translation component of root asset matrix could benefit from better explanation.

**Comment by pjcozzi** [comment]
@shunter do you have the new link to the "Precisions, Precisions" article?

**Comment by shunter** [comment]
http://help.agi.com/AGIComponents/html/BlogPrecisionsPrecisions.htm

Other Insight3D blog posts are listed here: http://help.agi.com/AGIComponents/html/GraphicsBlog.htm

**Comment by pjcozzi** [comment]
Thanks @shunter @nitrologic.  Fixed in #1134.
