### ISSUE TITLE
[Question] why not add uv tiling and offset to gltf format ?

### ISSUE THREAD

**Issue by sonygod** [KhronosGroup/glTF#1141]
[Question] why not add uv tiling and offset to gltf format ?
I 've search this  repo ,but all of give me one answer ,it's not necessary  to support that, because you
have some Tool like substance to export that.
hey,it's kidding .  
what about unity,ue4,babylon.js  ..so on . all of them support this important feature .
current we consider use gltf for our main 3d format , use unity as exporter  

our model include some material like fabric,wood,and all of that need uv tiling and offset..

**Comment by emackey** [comment]
I'm not sure I understand.  glTF already supports horizontal and vertical [wrapping modes](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#samplerwraps) such as `CLAMP_TO_EDGE`, `REPEAT`, and `MIRRORED_REPEAT`.  One can make repeating tiles of fabric or wood using that.  Are you talking about some other form of UV tiling?

What do you mean by "offset"?  In a 3D modeling package I can add an offset to existing UV coordinates, and the offset is baked into the model on export.  Is there some other offset I'm missing?  I think glTF may be lacking the ability to animate UV scaling and offset over time, is that what you mean?

**Comment by sonygod** [comment]
![image](https://user-images.githubusercontent.com/748320/32358505-9d573474-c081-11e7-94d4-1b2c3ad686e4.png)
![image](https://user-images.githubusercontent.com/748320/32358509-abc53e20-c081-11e7-8eb0-8a2d8222329a.png)

wrapping modes seem can't control tiling and offset .

**Comment by sonygod** [comment]
[demo](https://sketchfab.com/models/9e89219ec99442488b651366a6e0879e)
my leather material was missing detail when no offset and tiling.
![image](https://user-images.githubusercontent.com/748320/32359120-3f2e0364-c086-11e7-99b4-552d83018fe3.png)

the originally  
![image](https://user-images.githubusercontent.com/748320/32359120-3f2e0364-c086-11e7-99b4-552d83018fe3.png)

**Comment by emackey** [comment]
Thanks for the reference @AurL.  There is an extension being developed for this in #1015.

**Comment by AurL** [comment]
Nice! 
Thanks @emackey , I'll take a look at it.

**Comment by donmccurdy** [comment]
Closing this issue to consolidate, please follow https://github.com/KhronosGroup/glTF/pull/1015 for progress on this extension.
