### ISSUE TITLE
Validator passes, but glTF viewer shows nothing...

### ISSUE THREAD

**Issue by chipweinberger** [KhronosGroup/glTF#1143]
I'm making an FBX to glTF 2.0 converter.

Can anyone give me a suggestion as to why the viewer does not show anything on this input?

In the viewer website (https://gltf-viewer.donmccurdy.com/), I'm dragging the whole folder into it since my gltf is not a single file. The files are named "fe0ad98.obj34.verts.bin" etc in the same directory as the .gltf json file.

```
{
  "asset": {
    "version": "2.0",
    "generator": "FrogGLTF2Exporter Version:0.1"
  },
  "buffers": [
    {
      "name": "fe0ad98.obj34.verts",
      "uri": "fe0ad98.obj34.verts.bin",
      "byteLength": 9276
    },
    {
      "name": "fe0ad98.obj34.indices",
      "uri": "fe0ad98.obj34.indices.bin",
      "byteLength": 9054
    },
    {
      "name": "fe0ad98.obj34.UVs",
      "uri": "fe0ad98.obj34.UVs.bin",
      "byteLength": 6184
    },
    {
      "name": "fe0ad98.obj34.normals",
      "uri": "fe0ad98.obj34.normals.bin",
      "byteLength": 9276
    },
    {
      "name": "fe0ad98.obj34.vertColors",
      "uri": "fe0ad98.obj34.vertColors.bin",
      "byteLength": 9276
    }
  ],
  "bufferViews": [
    {
      "buffer": 0,
      "byteLength": 9276,
      "byteOffset": 0,
      "byteStride": 12,
      "target": 34962,
      "name": "fe0ad98.obj34.verts"
    },
    {
      "buffer": 1,
      "byteLength": 9054,
      "byteOffset": 0,
      "target": 34963,
      "name": "fe0ad98.obj34.indices"
    },
    {
      "buffer": 2,
      "byteLength": 6184,
      "byteOffset": 0,
      "byteStride": 8,
      "target": 34962,
      "name": "fe0ad98.obj34.UVs"
    },
    {
      "buffer": 3,
      "byteLength": 9276,
      "byteOffset": 0,
      "byteStride": 12,
      "target": 34962,
      "name": "fe0ad98.obj34.normals"
    },
    {
      "buffer": 4,
      "byteLength": 9276,
      "byteOffset": 0,
      "byteStride": 12,
      "target": 34962,
      "name": "fe0ad98.obj34.vertColors"
    }
  ],
  "accessors": [
    {
      "byteOffset": 0,
      "componentType": 5126,
      "normalized": false,
      "count": 773,
      "type": "VEC3",
      "bufferView": 0,
      "name": "fe0ad98.obj34.verts",
      "min": [
        -1.88389,
        -1.48596,
        -1.9246
      ],
      "max": [
        0.281129,
        0.91895,
        0.393707
      ]
    },
    {
      "byteOffset": 0,
      "componentType": 5123,
      "normalized": false,
      "count": 4527,
      "type": "SCALAR",
      "bufferView": 1,
      "name": "fe0ad98.obj34.indices",
      "min": [
        0
      ],
      "max": [
        773
      ]
    },
    {
      "byteOffset": 0,
      "componentType": 5126,
      "normalized": false,
      "count": 773,
      "type": "VEC2",
      "bufferView": 2,
      "name": "fe0ad98.obj34.UVs",
      "min": [
        0.00717166,
        0.00888079
      ],
      "max": [
        0.998932,
        0.99423
      ]
    },
    {
      "byteOffset": 0,
      "componentType": 5126,
      "normalized": false,
      "count": 773,
      "type": "VEC3",
      "bufferView": 3,
      "name": "fe0ad98.obj34.normals",
      "min": [
        -0.992264,
        -1,
        -0.997322
      ],
      "max": [
        1,
        0.999561,
        0.99915
      ]
    },
    {
      "byteOffset": 0,
      "componentType": 5126,
      "normalized": false,
      "count": 773,
      "type": "VEC3",
      "bufferView": 4,
      "name": "fe0ad98.obj34.vertColors",
      "min": [
        3.94903e-38,
        1.01332e-29,
        6.5861e-43
      ],
      "max": [
        3.94903e-38,
        1.01332e-29,
        6.5861e-43
      ]
    }
  ],
  "meshes": [
    {
      "primitives": [
        {
          "attributes": {
            "POSITION": 0,
            "NORMAL": 3,
            "TEXCOORD_0": 2,
            "COLOR_0": 4
          },
          "mode": 4,
          "indices": 1
        }
      ],
      "name": "fe0ad98.obj34.mesh"
    }
  ],
  "nodes": [
    {
      "name": "FbxRootNode",
      "children": [
        1
      ]
    },
    {
      "name": "fe0ad98.obj FbxId:33",
      "mesh": 0
    }
  ],
  "scenes": [
    {
      "nodes": [
        0
      ],
      "name": "rootScene"
    }
  ],
  "scene": 0
}
```

**Comment by chipweinberger** [comment]
Of course it's possible the .bin files are messed up, I'm going to check that as well.

**Comment by donmccurdy** [comment]
Nothing obvious so far, but FYI you can drag-and-drop .ZIP files into GitHub comments.

**Comment by zellski** [comment]
There’s no material definition at all. I’m not sure how dependably that’s handled in different loaders and systems. Which one are you using?

I’d be happy to help debug but yeah a reproducing ZIP file would be helpful.

**Comment by lexaknyazev** [comment]
Drag-n-drop validator checks only embedded (data-uri) and GLB binary payloads atm.

**Comment by chipweinberger** [comment]
I'm using this viewer:
https://gltf-viewer.donmccurdy.com/

On monday at work I'll add a default material and see if that fixes things. 

Thanks for the tip on .zip files. Ill post the *.bins on monday!

**Comment by chipweinberger** [comment]
Ah Zellski, I see you're making a Fbx to Gltf 2 converter as well =) If my work lets me open source this, it'll be fun to compare our solutions =)

**Comment by pjcozzi** [comment]
@chipweinberger first, thanks for using the validator when writing your converter - this is exactly what the community needs to ensure a robust ecosystem!

Soon, the VSCode plugin will have validation - using the same validator - in addition to the ability to view in three engines.  Keep an eye on #1081.

Just curious - is there a reason you are writing a FBX-to-glTF converter instead of using [FBX2glTF](https://github.com/facebookincubator/FBX2glTF/)?  Was FBX2glTF not available when you started?  Or do you have some unique use cases?

**Comment by zellski** [comment]
I'm curious too -- but if it turns out you do need to write your own, for whatever reason, by all means let's trade insights and observations. Are you linking against the Autodesk SDK or using a reverse-engineered parser?

I love the converter. It's catching a good 2/3 of my errors. The remaining are almost always me somehow managing to get an 0.0 in the alpha slot of the diffuse multiplier. :)

**Comment by chipweinberger** [comment]
The reason - I started working on this before the facebook incubator project was posted =) ...at least as far as im aware.

Im using the 2015 FBX SDK right now for no particular reason other than I know it worked. upgrading it to 2017 is on my todo list.

Zellski, my work gave my the tentative go ahead to open source my code. I took a look at yours and I think you could borrow a few good organizational ideas from mine that will simplify your code.

**Comment by chipweinberger** [comment]
Also I just want to add the validator is awesome. Awesome job to those who worked on it.

**Comment by chipweinberger** [comment]
[PantherBossGltf.zip](https://github.com/KhronosGroup/glTF/files/1448556/PantherBossGltf.zip)

I added a default material. Still no luck in the online viewer....

**Comment by chipweinberger** [comment]
My guess is that my .bin files are messed up.

I believe this is the issue:
I represent my vertex buffer as as std::vector<std::array<float, 3>> which I thought was contiguous. But apparently std::array is not guaranteed to be sizeof(float) * 3....

**Comment by chipweinberger** [comment]
Or... perhaps using int32_t indices is causing a problem? How many bytes is SCALAR?

**Comment by chipweinberger** [comment]
Found another error, my bin indices are uint32_t but I was classifying them as UNSIGNED_INT. I'll check all my bins and make sure.

**Comment by chipweinberger** [comment]
[PantherBossGltf.zip](https://github.com/KhronosGroup/glTF/files/1448592/PantherBossGltf.zip)

Hmm, that still did not fix it. And it turns out std::arrays are still tightly packed even though thats not their spec. So no idea what's wrong at the moment.

**Comment by chipweinberger** [comment]
[PantherBossGltfSimple.zip](https://github.com/KhronosGroup/glTF/files/1448620/PantherBossGltfSimple.zip)

I removed everything but the indices and vertices... in order to simplify the mesh. Still no output in the viewer.

**Comment by zellski** [comment]
Hey Chip --

At a first glance; your index setup looks okay in the .gltf, but in the actual indices.bin file it looks like you're writing 32-bit uints:
```
00000000: 0000 0100 0200 0300 0400 0000 0500 0200  ................
00000010: 0600 0500 0600 0700 0800 0900 0d0a 000d  ................
```
You can only use 16-bit indexes in glTF 2.0, and furthermore you'd specified that the data was going to be shorts:
```
    {
      "byteOffset": 0,
      "componentType": 5123,
      "normalized": false,
      "count": 4527,
      "type": "SCALAR",
      <snip>
```
(5123 is `UNSIGNED_SHORT`)

So I think that by itself can easily explain a complete breakdown in loading.

It's also a little peculiar that while the buffer sizes are given as 9276 and 9054 bytes, the files on disk are 9301 and 9073 respectively.

This is fun stuff, though, isn't it? :)

**Comment by zellski** [comment]
Oh, wait, sorry -- I had been eyeing an old file. It appears you fixed the indices.bin in the latest upload. I'll look some more.

**Comment by chipweinberger** [comment]
Thanks Zellski! Yes I fixed that error.
I think I'm on to something...

Using the program HexToolkit, I'm taking a look at the floats and there are some pretty weird numbers in it.

But when I printf the floats directly I'm seeing different numbers. The correct numbers. I'm not sure if there is some bug in HexToolkit, but the difference is surprising.

<img width="1406" alt="hexview" src="https://user-images.githubusercontent.com/1863934/32476942-9a23fa2a-c32f-11e7-9b59-55743289d56a.PNG">

**Comment by zellski** [comment]
Okay, if you're using Chrome and https://gltf-viewer.donmccurdy.com/, when you get the bounding sphere error you can expand the BufferGeometry object provided in the error message and inspect its contents.

If you eyeball attributes you'll see that while the positions start out reasonable, like so:

![image](https://user-images.githubusercontent.com/714167/32476880-30d4c70c-c32f-11e7-9a1a-aed8be735956.png)

but they derail after a while, and end up containing just junk:

![image](https://user-images.githubusercontent.com/714167/32476897-55ff0196-c32f-11e7-8d14-d1233f874b9f.png)

(sorry about the gigantic screencaps).

Given that you start off writing correct floats, it feels like this should be something fairly obvious... the file size mismatch also seems like it could be a good lead to pursue.

**Comment by chipweinberger** [comment]
I'm wondering if it is that std::vector<std::array<float,3>> is not contiguous after all. Time to quickly check.

**Comment by zellski** [comment]
I believe std::vector guarantees that &vec[0] always points to the first of a contiguous array of in-memory elements. You just can't stash the pointer and assume it'll be valid a millisecond later.

**Comment by chipweinberger** [comment]
I feel like the error is right under my nose and I'm just not noticing it.

I write the file with this:

fwrite(&bufs[i].rawData[0], 1, bufs[i].byteLength, bufFile);


Where rawData is a vector<char>, and the bufs[i].byteLength is 9276. 

But the output file has a byte size of 9,301...

**Comment by chipweinberger** [comment]
`
	struct Vec3{
		float m[3];
	};

	std::vector<Vec3> vs;
	vs.resize(flatMesh.vertices.size());

	for (int i = 0; i < flatMesh.vertices.size(); i++){
		vs[i].m[0] = flatMesh.vertices[i][0];
		vs[i].m[1] = flatMesh.vertices[i][1];
		vs[i].m[2] = flatMesh.vertices[i][2];
	}

	FILE* bufFile;
	fopen_s(&bufFile, (vertBuf->name.data() + "try2").c_str(), "w");
	fwrite(&flatMesh.vertices[0], 1, flatMesh.vertices.size() * 4 * 3, bufFile);
	fclose(bufFile);
`


What could I be doing wrong? I'm getting the same result....

**Comment by chipweinberger** [comment]
`	struct Vec3{
		float m[3];
	};

	std::vector<Vec3> vs;
	vs.resize(flatMesh.vertices.size());

	for (int i = 0; i < flatMesh.vertices.size(); i++){
		vs[i].m[0] = flatMesh.vertices[i][0];
		vs[i].m[1] = flatMesh.vertices[i][1];
		vs[i].m[2] = flatMesh.vertices[i][2];
	}

	FILE* bufFile;
	fopen_s(&bufFile, (vertBuf->name.data() + "try2").c_str(), "w");
	fwrite(&vs[0], 1, flatMesh.vertices.size() * 4 * 3, bufFile);
	fclose(bufFile);`


What Could I be doing wrong?

**Comment by chipweinberger** [comment]
The 'vs' floats look 100% fine. But after writing them to disk the hex editor shows weird 1.235e-20 number all over the place.

**Comment by chipweinberger** [comment]
Ahhh, found the error. I wasn't in binary mode. with printf God damn im so stupid. Thanks a ton for your help.

**Comment by chipweinberger** [comment]
FIXED IT. It works!  Wahooo! Thanks a ton zellski!!

**Comment by zellski** [comment]
Haha, awesome, glad to hear it. Good times!

**Comment by lexaknyazev** [comment]
Small correction to https://github.com/KhronosGroup/glTF/issues/1143#issuecomment-342369725: glTF 2.0 supports uint32 indices, but some clients (based on GLES 2.0 without `OES_element_index_uint`) may not render such geometry.

**Comment by chipweinberger** [comment]
lexaknyazev, that's very good to know. I was wondering about that. I'll have my code default to shorts unless it needs more and throw a warning on screen during conversion. Thanks.
