### ISSUE TITLE
glTF 1.0 uriref

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF#1149]
The glTF 1.0 schema still shows `uri` format, where glTF 2.0 switched to `uriref` in #838.

Is it worth making this change retroactive to 1.0?

I ask because the VSCode glTF extension is showing schema warnings for all glTF 1.0 uri refs, which is pretty much every model.

**Comment by pjcozzi** [comment]
If it's important to the VSCode plugin then make the change I suppose; otherwise, I don't expect many bug fixes to go into the 1.0 spec and schema.
