### ISSUE TITLE
Extension prefix reservation process

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#1157]
[Prefixes.md](https://github.com/KhronosGroup/glTF/blob/master/extensions/Prefixes.md) gives very informal description of prefix reservation process and doesn't answer to following questions:
1. Given that anyone (including non-members) could claim any prefix, how should possible conflicts be resolved? E.g., we've reserved `FB` prefix for Facebook. What prevents someone from claiming `FACEBOOK`? Should we verify that a person rightfully represents the organization?

2. Could individuals claim prefixes (or they should use `EXT`)?

3. Should it be possible to un-reserve the prefix? E.g., it's likely that there won't be any `AVR` extensions.

/cc: @pjcozzi @sbtron @bghgary

**Comment by pjcozzi** [comment]
I'm open to input, but I suggest we only add process as we need when we need it.  Is there anything pressing now?

> Given that anyone (including non-members) could claim any prefix, how should possible conflicts be resolved? E.g., we've reserved FB prefix for Facebook. What prevents someone from claiming FACEBOOK?

Use our best judgement to make sure people don't unreasonably claim prefixes that others are likely to use.

> Could individuals claim prefixes (or they should use EXT)?

Yes, so can projects, e.g., `CESIUM`.

> Should it be possible to un-reserve the prefix? E.g., it's likely that there won't be any AVR extensions.

Sure, if it is inactive, we can use our judgement to reassign/remove it.

**Comment by donmccurdy** [comment]
Closing, please reopen or propose changes to Prefixes.md if needed.
