### ISSUE TITLE
XMP tags in glTF/GLB files

### ISSUE THREAD

**Issue by jmlg10** [KhronosGroup/glTF#1161]
Hello,

I was wondering if it could be possible to add XMP support in glTF/Glb files.

The goal is to be able to embed metadata schemas like IPTC (but related to 3D) and or tags files to help search and asset management

**Comment by pjcozzi** [comment]
I am not familiar with XMP or IPTC, but glTF does allow extensions via adding properties to `extras` objects or through extensions, see https://github.com/KhronosGroup/glTF/tree/master/extensions#about-gltf-extensions

Would this work for your use case?

**Comment by pjcozzi** [comment]
OK to close this?  Or is there more discussion?

**Comment by jmlg10** [comment]
I suppose,
Apparently I don't get a lot of audience about this topic.
We shall see later.
Thanks

**Comment by donmccurdy** [comment]
Closing this issue, but note that some relevant conversation is continuing in https://github.com/KhronosGroup/glTF/issues/839.
