### ISSUE TITLE
2.0/figures/dictionary-objects.png many vs single relationships

### ISSUE THREAD

**Issue by zellski** [KhronosGroup/glTF#1170]
This is definitely minor, but it looks to me like the dictionary-objects.png erroneously suggests:
- that a node can reference multiple meshes (removed between 1.0 and 2.0?)
- that a skin references multiple accessors (was this ever true?)

**Comment by pjcozzi** [comment]
This could have been an oversight when updating the spec for 2.0.  Feel free to open a PR with both fixes.

**Comment by zellski** [comment]
I was hoping whoever originally created the .png might still have some source document. But it not I can take a pass at photoshop copy-and-paste of pixel regions. :-)

**Comment by lexaknyazev** [comment]
@zellski 
Source file is in the repo:
https://github.com/KhronosGroup/glTF/raw/master/specification/2.0/figures/pptx/figures.pptx

**Comment by zellski** [comment]
Well today I learned something. Thank you!

**Comment by pjcozzi** [comment]
I may also be the guilty party who made the figures...many years ago.

**Comment by pjcozzi** [comment]
Fixed in #1175
