### ISSUE TITLE
README states Archilogic Web-based 3D is glTF 2.0 but it isn't

### ISSUE THREAD

**Issue by mohamedmansour** [KhronosGroup/glTF#1172]
The readme states Archilogic is using glTF 2.0, but they are really using glTF 1.0. I exported the scene to glTF, and cannot load it in a-frame since it says it isn't gltf2.0. I had to use old version of a-frame to make it work.

**Comment by donmccurdy** [comment]
That's probably my mistake, we'll correct it.

/cc @AVGP curious to know if there's a particular feature or tool your team depends on from glTF 1.0?

**Comment by pjcozzi** [comment]
@mohamedmansour in the meantime, the [gltf-pipeline 2.0 branch](https://github.com/AnalyticalGraphicsInc/gltf-pipeline/tree/2.0) should be able to convert 1.0 to 2.0.

**Comment by AVGP** [comment]
Oh bummer, yeah - we need to update our glTF importer & exporter!

2017-12-06 15:13 GMT+01:00 Patrick Cozzi <notifications@github.com>:

**Comment by pjcozzi** [comment]
Updated in #1192.

@AVGP feel free to open a pull request when you update to glTF 2.0.
