### ISSUE TITLE
glb has at most one BIN chunk ?

### ISSUE THREAD

**Issue by andreasplesch** [KhronosGroup/glTF#1177]
https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#glb-file-format-specification reads at first as if multiple chunks, including multiple BIN chunks are allowed. In addition,  https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#glb-stored-buffer seems to suggest that a second buffer object could refer to a second BIN chunk.
So it took looking at a few loaders to confirm that at least in praxis only a single BIN chunk is expected.
It is very possible that I overlooked more specific language. If not, it may be helpful to explicitly state that only the first BIN chunk is used for a (single) buffer. Subsequent chunks may exist for custom data, presumably.

**Comment by javagl** [comment]
The second link says

> glTF Buffer referring to GLB-stored BIN chunk, must have buffer.uri property undefined, and **it must be the first element of buffers array;**

(e.b.m). Also, the "Table 1" from the first link says that there may be only "0 or 1" BIN chunk. So indeed, there is only one BIN chunk supported right now. Suggestions about how to make the wording clearer are certainly welcome.

Maybe helpful as a backtrace: The current structure is a generalization of the `KHR_binary_glTF` extension from glTF 1.0: https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_binary_glTF#binary-gltf-layout There, the structure was more rigid. The concept of "chunks" that was introduced in 2.0 indeed aims at supporting *additional* binary data - for example, for other extensions.

**Comment by andreasplesch** [comment]
I missed the Occurrences column in Table 1. I think because the column is never referenced in the text.

The Binary buffer section at
https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#binary-buffer
says:

> This chunk contains the binary payload for geometry, animation key frames, skins, and images. See glTF specification for details on referencing this chunk from JSON.

What about

> This chunk contains the binary payload for geometry, animation key frames, skins, and images. _**There is at most one chunk of this type.**_ See the  GLB-stored Buffer section for details on referencing this chunk from JSON.

? How are other paragraphs or sections in the specification referred to best ?

The reference at
https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#glb-stored-buffer
> glTF Buffer referring to GLB-stored BIN chunk, must have buffer.uri property undefined,

just misses a definite article to help clarify:

> glTF Buffer referring to **the** GLB-stored BIN chunk, must have buffer.uri property undefined,

**Comment by significant-bit** [comment]
+1 for clarifying the wording. I'm writing a new glTF importer and it was unclear whether more than one BIN chunk was allowed. The glTF 2.0 Quick Reference Guide has a diagram that led me to think more chunks were possible (possibly other BIN chunks):

[ header ][ chunk 0 JSON ][ chunk 1 BIN ] ...

So many possibilities lurk in that ellipsis!

After careful reading I saw that only one BIN chunk was allowed. The "0 or 1" mentioned by @javagl and  no way to specify _which_ BIN chunk buffer 0 will use.

**Comment by donmccurdy** [comment]
> How are other paragraphs or sections in the specification referred to best ?

We could link to the #glb-stored-buffer section here.

> [ header ][ chunk 0 JSON ][ chunk 1 BIN ] ...

To clarify, there certainly can be additional chunks, and as far as I know the BIN chunk does not have to be second. So this would be valid:

[ header ][ chunk 0 JSON ][ chunk 2 CUSTOM ][ chunk 3 BIN ] ...

But as you've said here, there cannot be more than 1 BIN chunk. I think **Table 1** in the *Chunks* section is clear, but suggestions on clearer wording elsewhere would be welcome.

For reference, here is how three.js parses GLB chunks: 

https://github.com/mrdoob/three.js/blob/r88/examples/js/loaders/GLTFLoader.js#L415-L442

**Comment by lexaknyazev** [comment]
> as far as I know the BIN chunk does not have to be second

Validator allows that, but we should check with other loaders (esp. non-Web) whether it's the case.

**Comment by zellski** [comment]
Does the spec explicitly state that a BIN chunk present in the .glb file ***must*** be referenced from the JSON metadata? I can find only obligations on the buffer entry's structured in order for it to reference the chunk; nothing about the obligations imparted by the existence of the chunk.

Obviously it's rather silly to smack a BIN chunk onto a file that never uses it, but is it forbidden?

A two-minute perusal of glTF-Validator source doesn't yield any obvious place an issue is filed for the situation of a BIN chunk without a BIN-specific buffer.

**Comment by lexaknyazev** [comment]
@zellski That's not forbidden per spec (should it?), but such situation should generate a warning at least. 
I'll update the validator soon.

**Comment by andreasplesch** [comment]
> But as you've said here, there cannot be more than 1 BIN chunk. I think Table 1 in the Chunks section is helpful, but suggestions on clearer wording elsewhere would be welcome.

To me adding 

> **_There is at most one chunk of this type._** 

would suffice but it sounds as if you had other wording in additional sections in mind ?

> as far as I know the BIN chunk does not have to be second

although the spec. currently does seem to suggest that. For example the table is preceded by:

> Chunks must appear in exactly the order given in the Table 1.

 If second place is where most/all loaders expect or accept the BIN chunk, actually requiring second place may be an opportunity to tighten the spec. as this should help implementers a bit.

**Comment by zellski** [comment]
Regarding dictating BIN is second, I recall a stated design principle of the format is that with the right extension, a single file GLB could be streamed — with coarse preview information in an early chunk, before full fidelity in the canonical BIN? That part of the file may also be where you’d want to put a preview image and so forth. In fact I think you could make a strong case that the BIN chunk is often the last. :)

**Comment by andreasplesch** [comment]
Ok, good point. I think then that the option of not being second also would need to be made explicit.

**Comment by pjcozzi** [comment]
Closing via #1231.

Thanks for bringing this up, @andreasplesch!

**Comment by andreasplesch** [comment]
Glad to contribute.
