### ISSUE TITLE
occlusionTexture.strength vs occlusionFactor

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF#1178]
`occlusionTexture.strength` is a bit of an outlier compared to glTF 2.0's naming of `fooFactor` properties. I've seen a fair number of Sketchfab glTF exports make that mistake ([example](https://sketchfab.com/models/0970f30574d047b1976ba0aa6f2ef855)).

For now, @AurL thought you may want to know about the issue.

In a future version, should we consider changing that, or would it just make things more confusing?

**Comment by bghgary** [comment]
See here: https://github.com/KhronosGroup/glTF/pull/830#discussion_r99901222

**Comment by donmccurdy** [comment]
Oh that makes enough sense then, I forgot `normalScale`. Not sure if there's a preferred way to ping Sketchfab but other than that this can be closed.

**Comment by bghgary** [comment]
@AurL has been responsive to pings from this repo, so I'm good with closing.
