### ISSUE TITLE
Default material definition

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#1182]
From [Meshes](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#meshes):
> If `material` is not specified, then a default material is used.

From [Default Material](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#default-material):
> The default material, used when a mesh does not specify a material, is defined to be a material with no properties specified. **All the default values of `material` apply.** Note that this material does not emit light and will be black unless some lighting is present in the scene.

There's a bit of vagueness in the "default values of `material`". Applying default values from the JSON-Schema to an empty `material` object will result in this (ignoring alpha and double-sided):
```json
{
    "materials": [
        {
            "emissiveFactor": [ 0.0, 0.0, 0.0 ]
        }
    ]
}
```

Notice that `pbrMetallicRoughness` isn't there but its [description](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#material) says:
> When not specified, all the default values of `pbrMetallicRoughness` apply.

Effectively this means that these two materials are the same:
```js
{
    "materials": [
        {
            // empty material
        },
        {
            "pbrMetallicRoughness": { }
        }
    ]
}
```

This may lead to the following questions:
- Should `{ }` be the default value for `pbrMetallicRoughness` schema-wise?
- Does it imply that all materials (wrt future spec versions and extensions) should have reasonable PBR MR representation?

/cc: @pjcozzi @bghgary @donmccurdy

**Comment by bghgary** [comment]
> Should `{ }` be the default value for `pbrMetallicRoughness` schema-wise?

Will adding it simplify implementations when there is a default value? I don't see any benefit to code generators.

> Does it imply that all materials (wrt future spec versions and extensions) should have reasonable PBR MR representation?

I'm not following this implication. Instead, I think the implication goes more like this. Because we want the asset to be [forward compatible](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#versioning), materials are expected to always have a PBR MR representation for all 2.x assets except when the material has an extension that is marked as required in the asset, in which case the MR properties will be ignored.

**Comment by significant-bit** [comment]
I'm interpreting default material a bit differently:  if unspecified in the file, use the target software's default material. In both Blender and Unreal it's ok to have a surface with no material. Not a glTF-defined material with default values. In a game dev workflow I'd much rather have a model without material (from Blender) come in (to Unreal) with no materials so you can author a material from scratch (in Unreal).

Of course if materials are defined in the file, import them as is!

**Comment by gkv311** [comment]
> I'm interpreting default material a bit differently: if unspecified in the file, 
> use the target software's default material. 

Yeah, this is how I interpret default material in Open CASCADE CAD Assistant while reading glTF and other formats.

Though I understand that this contradicts specs, but applying default material from application settings (keeping material "undefined" in data model) sounds more useful for me than applying defaults specified in specs.

**Comment by donmccurdy** [comment]
> Does it imply that all materials (wrt future spec versions and extensions) should have reasonable PBR MR representation?

This sounds hard to ensure — for example many KHR_technique_webgl materials are not going to have reasonable fallbacks in PBR MR. The default PBR material is probably as good a fallback as anything in that case.

> materials are expected to always have a PBR MR representation for all 2.x assets except when the material has an extension that is marked as required in the asset, in which case the MR properties will be ignored.

+1.

> I'm interpreting default material a bit differently: if unspecified in the file,
use the target software's default material.

I think that's probably a good call for the software you mention... how/if we should adjust the spec to clarify this case I'm not sure.

**Comment by lexaknyazev** [comment]
>> Should `{ }` be the default value for `pbrMetallicRoughness` schema-wise?

> Will adding it simplify implementations when there is a default value? I don't see any benefit to code generators.

My concern here is that it's mentioned _only_ in JSON-Schema description - easy to overlook. I'm not sure about making `{ }` a default though. Future assets with, e.g., `"minVersion": "2.5"` may have a new core PBR model, so having `pbrMetallicRoughness` implicitly defined could be confusing.

> Because we want the asset to be forward compatible, materials are expected to always have a PBR MR representation for all 2.x assets except when the material has an extension that is marked as required in the asset, in which case the MR properties will be ignored.

I see. That means that both materials in the following example are incorrect unless an asset uses `extensionsRequired`, right? Also, it sounds like the validator should issue a warning when there's a non-required material extension without PBR MR fallback.
```json
{
    "materials":[
        {
            "extensions": {
                "KHR_materials_pbrSpecularGlossiness": {
                    "diffuseFactor": [ 0.5, 0.5, 0.5, 1 ]
                }
            }
        },
        {
            "pbrMetallicRoughness": {},
            "extensions": {
                "KHR_materials_pbrSpecularGlossiness": {
                    "diffuseFactor": [ 0.5, 0.5, 0.5, 1 ]
                }
            }
        }
    ]
}
```

**Comment by bghgary** [comment]
> My concern here is that it's mentioned only in JSON-Schema description - easy to overlook.

Feel free to add/update wording for this.

> I'm not sure about making `{ }` a default though. Future assets with, e.g., `"minVersion": "2.5"` may have a new core PBR model, so having `pbrMetallicRoughness` implicitly defined could be confusing.

I suppose this is possible, but I think we will probably increment the major version if we changed the default material model.

> That means that both materials in the following example are incorrect unless an asset uses `extensionsRequired`, right?

Yes.

> Also, it sounds like the validator should issue a warning when there's a non-required material extension without PBR MR fallback.

+1 if it's easy to do which I'm not sure it will be. Having missing metallic roughness value may be correct if the SG extension looked like this or something close to it:

```json
{
    "materials":[
        {
            "extensions": {
                "KHR_materials_pbrSpecularGlossiness": {
                    "diffuseFactor": [ 0.0, 0.0, 0.0, 1.0 ],
                    "specularFactor": [ 1.0, 1.0, 1.0 ],
                    "glossinessFactor": 0.0
                }
            }
        }
    ]
}
```

**Comment by lexaknyazev** [comment]
Tightened in the new spec draft.
