### ISSUE TITLE
inconsistency around animation/sampler/output requirement

### ISSUE THREAD

**Issue by zellski** [KhronosGroup/glTF#1183]
So in the formal schema we're told only 'weights' may take an integer component type:

https://github.com/KhronosGroup/glTF/blob/9e6bdca9f7eeeb2eda7cd963c1b2e5e8899ea721/specification/2.0/schema/animation.sampler.schema.json#L35-L39

However, the table in the spec itself suggests the rotation quaternion can also accept normalized integers:

![image](https://user-images.githubusercontent.com/714167/34011777-1590bcda-e0c6-11e7-9914-6b7615bd1b8b.png)

Finally, glTF-Validator [does allow normalized integer rotation](https://github.com/KhronosGroup/glTF-Validator/blob/476e90d67b73bef38a3263d3add1e4b0cbb3c344/lib/src/base/members.dart#L154-L172).

**Comment by lexaknyazev** [comment]
Spec's readme and the validator are correct, description in JSON-Schema should be updated.

**Comment by zellski** [comment]
I'll see about a PR in a bit.
