### ISSUE TITLE
Animation duration?

### ISSUE THREAD

**Issue by blitz-research** [KhronosGroup/glTF#1184]
Hi,

How do I know the duration of an animation? Do I have to work out max of max "input" times?

Bye,
Mark

**Comment by lexaknyazev** [comment]
Animation sampler input accessors must have both `min` and `max` properties. So the total duration of an animation would be `max(all max values of samplers inputs) - min(all min values of samplers inputs)`.

**Comment by pjcozzi** [comment]
@blitz-research OK to close this?

**Comment by blitz-research** [comment]
Close away!

**Comment by emackey** [comment]
Just an update on this.  It was decided in #1327 that all animations start at zero, but remain clamped to the initial keyframe until the time of the first keyframe.  So the `min` values are irrelevant to the duration of animations now.  The total duration in seconds is just the `max` of all max values of input samplers within a given animation.
