### ISSUE TITLE
Check SpecGloss / MR fallback example

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#1185]
[Example with both material models](https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_materials_pbrSpecularGlossiness#best-practices) doesn't seem to match conversion math (both [code](https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_materials_pbrSpecularGlossiness/examples) and [online tool](https://bghgary.github.io/glTF/convert-between-workflows/)).

/cc @bghgary @sbtron

**Comment by bghgary** [comment]
Good catch. I'll update it.
