### ISSUE TITLE
Ability for animation to target material properties

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#1191]
E.g. for texture animation effects.

Original glTF 1.0 proposal and discussion: https://github.com/KhronosGroup/glTF/issues/142#issuecomment-27644840

**Comment by donmccurdy** [comment]
https://github.com/KhronosGroup/glTF/pull/1301 proposes a solution for this; I think it will be important to support eventually. Closing this issue to focus discussion there.
