### ISSUE TITLE
Another: Clarification on bufferView.target for indices

### ISSUE THREAD

**Issue by zellski** [KhronosGroup/glTF#1199]
[The spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#primitiveindices) tells us, "... the `bufferView` referenced by the `accessor` should have a `target` equal to 34963 (ELEMENT_ARRAY_BUFFER)".

Does the use of "_should_" here suggest it's a recommendation rather than a requirement? Is it okay to leave it out? Reason for uncertainty: official sample models (e.g. [Avocado](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Avocado/glTF/Avocado.gltf#L37-L42)) include, and validator accepts, `bufferViews` without `.target`, even when targeted by `Mesh.Primitive.indices` accessors.

**Comment by lexaknyazev** [comment]
Some engines (e.g. Babylon) ignore that field, others may use it to create GPU buffers before loading accessors and binary data. Anyway, the same `bufferView` cannot be used for different "targets" (e.g. both indices and attributes).

**Comment by zellski** [comment]
Right. Yeah. And in the validator you use setUsage() for that. But glTF is valid then even if it leaves out the target field? Even for an index accessor?

**Comment by lexaknyazev** [comment]
It's valid, yes. Maybe, that field will be required or removed in future versions.

**Comment by zellski** [comment]
Thank you!
