### ISSUE TITLE
KHR_common_materials lights needs updating from key value pairs to array indices to be consistent with gltf2.

### ISSUE THREAD

**Issue by chipweinberger** [KhronosGroup/glTF#1207]
In this example for instance,

https://github.com/KhronosGroup/glTF/blob/master/extensions/Khronos/KHR_materials_common/schema/examples/lights.json

"ambient_light_id", "directional_light_id", "point_light_id" would be replaced with arrays instead of key value pairs in order to be consistent with Gltf2.

**Comment by chipweinberger** [comment]
It appears the extension is for Gltf 1.0 only. Nevermind. The repo should split extensions into 1.0 and 2.0 folders.

**Comment by zellski** [comment]
There's been copious discussion about what to replace KHR_common_materials with for glTF 2.0, e.g.
- https://github.com/KhronosGroup/glTF/issues/947
- https://github.com/KhronosGroup/glTF/pull/1095
culminating, most immediately, in
- https://github.com/KhronosGroup/glTF/pull/1163

and specifically for lights,
- https://github.com/KhronosGroup/glTF/issues/945

**Comment by chipweinberger** [comment]
Thanks for getting me up to speed with those links. It's quite helpful.

**Comment by chipweinberger** [comment]
In your opinion, are any of them close enough to being ratified that it's worth implementing?

**Comment by zellski** [comment]
I suspect https://github.com/KhronosGroup/glTF/pull/1163 is likely to go through before anything else, but I'm holding off myself for now. And note that it only covers a sliver of what KHR_materials_common did, focusing on the most obvious use-case; the completely unlit. Not really that helpful for a FBX converter, though, where the author likely generally wanted Phong or Lambert.
