### ISSUE TITLE
Gltf Extensions should be split into 1.0 and 2.0 folders in the repo

### ISSUE THREAD

**Issue by chipweinberger** [KhronosGroup/glTF#1208]
I just spent 10 minutes trying to figure out why KHR_materials_common seemed so 'off', only to later realize its only for 1.0. This should be reflected in the folder structure.

Extensions/1.0/Khronos/KHR_materials_common

**Comment by chipweinberger** [comment]
Is this the 2.0 version of the spec? https://github.com/KhronosGroup/glTF/issues/947

Confused at the moment...

**Comment by Kupoman** [comment]
What about extensions that are compatible with multiple versions of glTF. Would they be duplicated across folders?

**Comment by chipweinberger** [comment]
That's best and most clear, yes. 1.0 is basically dead. It's there for legacy and should not be worked on or updated anymore. So copy whatever extensions support 1.0 right now into the 1.0 folder, and forget about them.  Going forward any new extensions or updates that could technically support 1.0 & 2.0 should just be maintained in the 2.0 folder, as extension spec changes to 1.0 should not happen anymore.. 

As for another more important edge case, take KHR_material_common. A 2.0 version is being worked on for gltf 2.0, but there will still be the 1.0 version that has some amount of use use.

**Comment by donmccurdy** [comment]
+1 for splitting extensions into 1.0 and 2.0 folders.

When we moved from glTF 1.0 to 2.0 the extensions did not "roll up", and we've been gradually defining the 2.0 versions. I'm assuming that for any glTF 2.X releases, the 2.0 extensions remain valid? Not sure if there's a precedent on this yet, but that would be my vote.

**Comment by pjcozzi** [comment]
I agree with @donmccurdy on both points.  Will run it by the Khronos working group tomorrow.

**Comment by pjcozzi** [comment]
Also, thanks for bringing this up @chipweinberger!

**Comment by donmccurdy** [comment]
Here's a PR: https://github.com/KhronosGroup/glTF/pull/1214

About whether extensions "roll up" with 2.X releases, it is our current expectation that the 2.0 extensions remain valid, but this could depend on details of the (hypothetical) 2.X change and extensions involved.

**Comment by pjcozzi** [comment]
@chipweinberger thanks for bring this up.  #1214 was merged.
