### ISSUE TITLE
Shadeless material in glTF

### ISSUE THREAD

**Issue by AurL** [KhronosGroup/glTF#1215]
We are thinking about adding a metadata in glTF to know if a model should be rendered shadeless, since we have a bunch of them (especially 3D scans or anime/drawing models) that are available in glTF but look different when imported in other engines (where they are rendered as lit).

Examples:
https://sketchfab.com/models/0970f30574d047b1976ba0aa6f2ef855
https://sketchfab.com/models/311d052a9f034ba8bce55a1a8296b6f9
https://sketchfab.com/models/38aedc02c0b2412babdc4d0eac7c6803

Before doing this, we wondered if the topic had already been discussed, and how would you would address the issue?

Thanks,

**Comment by donmccurdy** [comment]
Hi @AurL, good timing! Would https://github.com/KhronosGroup/glTF/pull/1163 provide the right metadata?

**Comment by AurL** [comment]
@donmccurdy  Nice, thanks for pointing this out. 
For now we are thinking about keeping original materials and set metal and roughness to 0 and 1 (or another high value) respectively. We did some quick tests and the diff is "acceptable" and most of the engines will support it without the need of the extension, but we don't exclude the possiblity of switching to the extension if it makes sense.

(btw, it looks like I missed several mentions in glTF issues because of notifications not showing)

**Comment by donmccurdy** [comment]
Sounds good. There's still some ongoing discussion for fallback behavior, but I think we'd encourage you to `"set metal and roughness to 0 and 1 (or another high value)"` _AND_ include `KHR_materials_unlit` on the material and listed under `optionalExtensions` — the extension is essentially just a flag to let extension-aware engines know it's shadeless.

**Comment by zellski** [comment]
Tiny nit: @donmccurdy, I think you meant to say `extensionsUsed`?

@AurL I will add an option that was discussed in the extension issue -- in fact, it was the basis for its original design -- if you don't care about vertex-coloured materials, and you don't intend to use `KHR_materials_unlit`, you can get essentially perfect behaviour by using emissiveTexture rather than baseColorTexture, and then essentially null out all diffuse lighting considerations using baseColorFactor = [0, 0, 0, 1]. Provided your engine treats emissive fairly simply (e.g. no post-processing bloom), then this is as close to unlit as you can trick PBR into being.

**Comment by AurL** [comment]
@donmccurdy yes, it would make sense to have fallback + extension to allow engines to correctly handle the model, we will discuss this and maybe add it if it really makes sense for our use.

@zellski yes, the fallback you're talking about was our first "solution" to solve the export of shadeless model into glTF Standard PBR materials, but the issue is that we don't want to make any assumption on the engines that will use the assets. It could be a good workaround if the conditions are validated (and it will probably be the case most of the time), but we don't want to deliver an asset that would mess up the rendering if it's included to a scene rendered with postprocess where the emission has an impact.

Thanks for following up 👍

**Comment by donmccurdy** [comment]
Oops yes, meant to say `extensionsUsed`. 😅

**Comment by AurL** [comment]
It looks like we will actually add the unlit extension in our exports, as it's almost no effort.

@donmccurdy do you take vertex colors into account here ? https://khr-materials-unlit-bhyuetkweu.now.sh/

I'm testing the unlit extension on [this model](https://sketchfab.com/models/f85bd7bc74e64acb820351b5c93b89e6) that is coloured by vertex colors and I get everything black.

(BTW, If you are looking for more sample, I can suggest you to take a look at the [downloadable Tiltbrush models](https://sketchfab.com/search?features=downloadable&q=tag%3Atiltbrush&sort_by=-likeCount&type=models) here or some quill models like [this one](https://sketchfab.com/models/82c7414bb71742279826bf7764534f05) or [this one](https://sketchfab.com/models/cc14e3b4eab54e21b1e1f665b249f63f). There are the "drawing" models I was mentionning.)

**Comment by donmccurdy** [comment]
> It looks like we will actually add the unlit extension in our exports, as it's almost no effort.

Great! 🙂

> do you take vertex colors into account here ? https://khr-materials-unlit-bhyuetkweu.now.sh/

Oops, looks like that's a bug. Certainly vertex colors should be taken into account; we'll fix that.

**Comment by AurL** [comment]
Ok, thanks!
Should we follow [these changes](https://github.com/KhronosGroup/glTF/pull/1163/files) to add the extension in our glTF export ?

Also, we are aiming to push fixes/improvements in the incoming weeks, so I wanted to know how mature was the extension ? If we can go for the current state or if it's safer to wait more ? 
For what I understand, the extension will have no parameters, it's just a declaraction that means that just a few channels of the standard material should be used. It's the way it's currently set in our ongoing updates, as we output this:
```
  "materials": [
    {
      "doubleSided": true,
      "emissiveFactor": [
        0,
        0,
        0
      ],
      "extensions": {
        "KHR_materials_unlit": {}
      },
      "name": "Scene - Root",
      "pbrMetallicRoughness": {
        "baseColorFactor": [
          1,
          1,
          1,
          1
        ],
        "metallicFactor": 0,
        "roughnessFactor": 1
      }
    }
  ],
```

(Note: our export code doesn't yet clean parameters when they have default value)

**Comment by donmccurdy** [comment]
That's correct; the extension will have no parameters.

I think the extension is stable enough. From the other thread:

> Current status of the PR is:
> 
> * [x] Schema and use of baseColor values and vertex colors seem solid at this point
> * [ ] More discussion of use cases is welcome, as this could affect fallback recommendations
> * [ ] Recommended fallback material should be clarified further
> * [ ] One additional prototype implementation would be helpful to check things over

If you all would like to go for it, that addresses our "one additional implementation" task. 🙂

**Comment by zellski** [comment]
@AurL We've embraced this extension full-bore at Facebook and will be recommending it for e.g. photogrammetry uploads.

**Comment by AurL** [comment]
Ok, thanks @donmccurdy @zellski.
We will push the update that adds the empty extension for shadeless (unlit) models.

**Comment by AurL** [comment]
@donmccurdy Just to let you know that the extension is now added to glTF exported from Sketchfab, but only for new/updated models. We will need to regenerate all glTF files on Sketchfab in the incoming weeks so the extension will be included in all downloadable shadeless models soon.

For now, you can see it in this sample (an old scan I made: https://sketchfab.com/models/c918aef928ad4acf9cae164244868070)

If you have any place where we can test the result, don't hesitate to share.

**Comment by zellski** [comment]
That’s great news! We will be consuming this extension at the imminent FB launch as well.

**Comment by donmccurdy** [comment]
Sounds good! 🎉

> If you have any place where we can test the result, don't hesitate to share.

Here is a viewer with patched support: https://khr-materials-unlit-ooddguuati.now.sh/

Vertex colors should be working there, fixed from the previous version.

**Comment by donmccurdy** [comment]
Closing this issue, let's use #1163 if there's more to discuss.
