### ISSUE TITLE
Vertex color

### ISSUE THREAD

**Issue by blitz-research** [KhronosGroup/glTF#1224]
Hi,

I'm just adding support for COLOR_0 in mesh primtives to my gltf loader and aren't quite sure what to do with the actual colors.

Should vertex colors replacing lighting altogether, or should I modulate metallic roughness baseColor with them or something? I tried this with BoxVertexColors and it looks kind of washed out, esp.  when compared to other online viewers such as:

https://gltf.insimo.com/

Also, are the vertex colors sRGB or linear?

Bye!
Mark

**Comment by blitz-research** [comment]
Actually, I seem to get pretty ool results adding vertex color to emissive....

**Comment by andrewvarga** [comment]
@blitz-research I think the vertex color should be multiplied with the base color as described here:
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/VertexColorTest

**Comment by donmccurdy** [comment]
The vertex colors should be stored in linear color space, as well
