### ISSUE TITLE
How to implement vertex colors?

### ISSUE THREAD

**Issue by blitz-research** [KhronosGroup/glTF#1225]
Hi,

I'm just adding support for COLOR_0 in mesh primtives to my gltf loader and aren't quite sure what to do with the actual colors.

Should vertex colors replacing lighting altogether, or should I modulate metallic roughness baseColor with them or something? I tried this with BoxVertexColors and it looks kind of washed out, esp.  when compared to other online viewers such as:

https://gltf.insimo.com/

Also, are the vertex colors sRGB or linear?

Bye!
Mark

**Comment by blitz-research** [comment]
...adding vertex colors to emissive is also an option.

**Comment by zellski** [comment]
There is one critical line in the spec that I believe indicates what should happen here:

"In addition to the material properties, if a primitive specifies a vertex color using the attribute semantic property `COLOR_0`, then this value acts as an additional linear multiplier to `baseColor`."

Maybe start with that, and if the washed-out-ness remains an issue we can tackle that?

**Comment by blitz-research** [comment]
D'oh! I've read through the mesh specs about 3 times today - never occured to me to check material!

It still looks a bit washed out but that may be my mistake - at least I know what I/m supposed to do now.
