### ISSUE TITLE
Confusion around buffer sizes

### ISSUE THREAD

**Issue by blgrossMS** [KhronosGroup/glTF#1228]
I am writing a GLB exporter for the UnityGLTF library: https://github.com/KhronosGroup/UnityGLTF 

In doing this I have become confused as to what the max buffer size is. The GLB specification clearly states that it only deals in uint32's for all sizes of buffers and the glb itself: https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#binary-gltf-layout 

However, buffer size for referencing .bin's is less clear. The specification simply says "integer": https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#reference-buffer 

The UnityGLTF library interpreted this to mean int32, however from what I can tell from the JSON specification (http://ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) and this GitHub thread (https://github.com/stedolan/jq/issues/143) JSON does not actually specify how large the number field can be for integers (though it is usually interpreted to be int53 based on JavaScript's interpretation of Number). 

The questions is:
Is the UnityGLTF library non-conformant in that it should accept buffers larger than int32 (either uint32, int53, or uint64)? Which would mean that GLB serialization would fail if given a buffer larger than uint32?

**Comment by DanHolbert** [comment]
It would be great to get clarification on this. Hopefully, the answer is at least uint32.

**Comment by lexaknyazev** [comment]
I'd say that uint32 should be supported by all tools.
Given that buffer size can't be negative, why does UnityGLTF use signed type?

**Comment by blgrossMS** [comment]
UnityGLTF can use unsigned types, my broader question is what is the max buffer size (if there is one)?
