### ISSUE TITLE
Unhelpful descriptions in the schema for the animation objects  e.g. "gltf_detailedDescription"

### ISSUE THREAD

**Issue by chipweinberger** [KhronosGroup/glTF#1229]
I've found the gltf_detailedDescription of the animation objects and properties to be very unhelpful in remembering what Samples and channels are.  I think they could use some work. 

I've offered some of my own improvements here. This is just a start. Please feel free to offer more improvements. If someone could make a pull request it would definitely improve things as a user of the schema!

**What is an Animation Channel?  (e.g. the " "description" in the schema)**
**Original:** Targets an animation's sampler at a node's property.
**Mine**: Channels take generalized animation movements (called Animation Samplers) and apply them to specific nodes/meshes.

**What is an Animation Sampler?**
**Original:** Combines input and output accessors with an interpolation algorithm to define a keyframe graph (but not its target).
**Mine:**   Animation Samplers describe some generalized animation movement. Perhaps it defines a "bounce" movement or something else, by specifying timestamped keyframes. But telling gltf where to apply this movement in the scene is the job of the Animation Channel.

**What is the Animation.channel property?**
**original**: "An array of channels, each of which targets an animation's sampler at a node's property. Different channels of the same animation can't have equal targets.",
**mine**:An array of channels. Channels take the animation movements (Samplers) and apply them to specific nodes/meshes. Multiple of identical channels are not allowed

**What is the Animation.samplers property?**
**original**: ""An array of samplers that combines input and output accessors with an interpolation algorithm to define a keyframe graph (but not its target).",
**mine**: An array of generalized animation movements (samplers)

**What is the Animation Sample::Input property?:**
**Original:** The index of an accessor containing keyframe input values, e.g., time. That accessor must have
componentType `FLOAT`. The values represent time in seconds with `time[0] >= 0.0`, and strictly increasing values, i.e., `time[n + 1] > time[n] 

**Mine:** An accessor containing the keyframe timestamps. This accessor must be type FLOAT and represents time in seconds.  Timestamps must be >= 0 and strictly increasing values, i.e., `time[n + 1] > time[n].

**What is the  Animation Sample::Output: property?**
**Original:** The index of an accessor containing keyframe output values. When using TRS animations,
the `accessor.componentType` of the output values must be `FLOAT`. When using morph weights,the `accessor.componentType` of the output values must be `FLOAT` or a normalized integer where eachoutput element stores values with a count equal to the number of morph targets. 
**Mine:** The animation movement data. The index of an accessor containing the keyframes. When using TRS animations, the `accessor.componentType` of the output values must be `FLOAT`. When using morph weights,the `accessor.componentType` of the output values can be `FLOAT` or a normalized integer where each output element stores values with a count equal to the number of morph targets.

**Comment by pjcozzi** [comment]
Hi @chipweinberger, thanks for the suggestions, we are also looking to improve the spec and schema.

@lexaknyazev @bghgary or anyone else - do you want to review and open a PR based on this?

**Comment by lexaknyazev** [comment]
First of all, `animation.sampler.output` section is a bit outdated and should be synced with schemas first, see #1266.

Not a very strong opinion, but some of this information is already present in spec's [Animations](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#animations) section. We usually regard schemas' descriptions as more formal and `README.md` as more approachable. So, I'd be in favor of documentation updates as long as they are aligned with that distinction (e.g., schema descriptions shouldn't contain examples).

There's also a [glTF-Tutorials](https://github.com/KhronosGroup/glTF-Tutorials) repo with more explanations and examples (e.g. see [Animations Tutorial](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_007_Animations.md)). 

/cc @javagl

**Comment by chipweinberger** [comment]
There is definitely a balance to strike between the two. I may have overdone it on the approach-ability aspect, but I think some of the descriptions offer almost no insight.

**Comment by javagl** [comment]
The `description` is placed into the properties summary table, and the `gltf_detailedDescription` is placed into the properties reference. So for example, regarding your suggestion about the **Animation Sampler**: Here, one could keep the original `description`, and add a more detailed one (similar to yours) as the `gltf_detailedDescription`. 

I'd have to go through the suggestions one by one, and compare them with the latest state of the spec (maybe after re-generating the reference from the latest state - this is currently in the queue). But in general, I think that a "balance" in this case could be to keep the `description` as short, formal, technical and concise as possible, but use the `gltf_detailedDescription` to add a few more (approachable) words, maybe also about how the element relates to others.
