### ISSUE TITLE
Best-practices for caching world-space matrices?

### ISSUE THREAD

**Issue by dakom** [KhronosGroup/glTF#1237]
I asked this at Stackoverflow but it doesn't seem to be getting views: https://stackoverflow.com/questions/48641073/caching-world-space-transform-from-gltf

Generally, should something like this be written as an extension?

The use-case I have in mind is where the glTF is not only read into memory and transformed into draw calls - but rather it's used as like a declarative source of truth for re-renders, and the data generated from the first-pass needs to be cached somewhere.

**Comment by donmccurdy** [comment]
glTF is primarily intended for transmission to a runtime engine; most engines will still want to load it into their own data structures. Using it as an in-place data structure for realtime changes is not an area where we've formally defined behavior, but you can use the extension or extras mechanisms I think.

Example:

```
"nodes": [
  {
    "name": "Player",
    "mesh": 0,
    "extras": {
      "cachedMatrixWorld": [ 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1 ]
     }
  }
]
```

If you think you'll be persisting that data somewhere, allowing users to download glTF files, or defining some non-trivial structure, an extension might be more appropriate:

```
"nodes": [
  {
    "name": "Player",
    "mesh": 0,
    "extensions": {
       "MYAPP_runtime": {
         "cachedMatrixWorld": [ 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1 ]
       }
     }
  }
]
```

More info on extensions [here](https://github.com/KhronosGroup/glTF/tree/master/extensions).

**Comment by dakom** [comment]
perfect, thanks!

**Comment by dakom** [comment]
FYI - it might be helpful to mention this along side this paragraph:

> Alternatively, and as a potential performance improvement, an implementation could cache the global transforms, detect changes in the local transforms of ancestor nodes, and update the global transforms only when necessary. The different implementation options for this will depend on the programming language and the requirements for the client application, and thus are beyond the scope of this tutorial.

- https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_004_ScenesNodes.md

**Comment by pjcozzi** [comment]
Thanks @dakom.

CC @javagl
