### ISSUE TITLE
Registering S8S vendor prefix

### ISSUE THREAD

**Issue by alexkowel** [KhronosGroup/glTF#1240]
Hello, Verge3D framework uses glTF 2.0 by default and utilizes several extensions : S8S_v3d_data, S8S_v3d_material_data, S8S_v3d_camera_data and others. There is no published/written standard yet however it would be very helpful to have a registered prefix for these. The company behind Verge3D is called Soft8Soft so the prefix is S8S.
Thanks!

**Comment by pjcozzi** [comment]
Sure thing, added in #1242.  Looking forward to the extensions!
