### ISSUE TITLE
Support for Curve Data

### ISSUE THREAD

**Issue by apurvaojas** [KhronosGroup/glTF#1258]
Do we have any specs for the Bezier curve and path type object data..?

**Comment by donmccurdy** [comment]
Hi @apurvaojas — glTF files do not store curve data. Unlike a lot of 3D formats, we store as nearly as possible what is needed by a 3D engine to render the data (typically, that's triangles), and require exporters to convert the data during export. To take Blender as an example, that means that you must [convert curves to meshes](https://blender.stackexchange.com/questions/2917/how-can-curves-be-converted-to-meshes) if your exporter does not do this automatically. If you have created a curve and are having trouble exporting it from a particular tool, there may be things that tool can do to help.

**Comment by syoyo** [comment]
FYI, I have added curves primitive support as my own extension.

https://github.com/syoyo/tinygltfloader/tree/master/examples/alembic_to_gltf

Curves is important for rendering hair strands, and its getting common for realtime renderings > https://www.fxguide.com/fxfeatured/ue4-real-time-hair-advances/

**Comment by Igor-dvr** [comment]
Still no plans to support curves? Maybe gltf external references can help with that?
