### ISSUE TITLE
Restrict animation sampler output re-usage to the same interpolation mode?

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#1265]
What if two animation samplers use the same output accessor with different interpolation modes?
```json
{
    "accessors": [
        {
            "type": "SCALAR",
            "componentType": 5126,
            "count": 36
        },
        {
            "type": "SCALAR",
            "componentType": 5126,
            "count": 12
        },
        {
            "type": "VEC4",
            "componentType": 5126,
            "count": 36
        }
    ],
    "animations": [
        {
            "samplers": [
                {
                    "input": 0,
                    "output": 2,
                    "interpolation": "LINEAR"
                },
                {
                    "input": 1,
                    "output": 2,
                    "interpolation": "CUBICSPLINE"
                }
            ],
            "channels": [
                {
                    "sampler": 0,
                    "target": {
                        "node": 0,
                        "path": "rotation"
                    }
                },
                {
                    "sampler": 1,
                    "target": {
                        "node": 1,
                        "path": "rotation"
                    }
                }
            ]
        }
    ]
}
```
The spec implicitly allows this.

/cc @bghgary @emackey @pjcozzi @donmccurdy

**Comment by lexaknyazev** [comment]
I'm having hard time imagining any real scenario for this given that sampler output for cubic splines looks like
```
in_tan0, value0, out_tan, in_tan1, value1, out_tan1, ...
```
In what case does linear interpolation between tangents and values make any sense?

**Comment by donmccurdy** [comment]
Oh, ok that would certainly be invalid since the accessor lengths could not be right, yes? A validation error there makes sense. But LINEAR and STEP sharing an accessor might be plausible.

**Comment by lexaknyazev** [comment]
> that would certainly be invalid since the accessor lengths could not be right, yes?

The example above uses different inputs, so lengths match.

> LINEAR and STEP sharing an accessor might be plausible

Agree.

**Comment by pjcozzi** [comment]
Perhaps update the spec such that each targeted `node`/`path` in an animation must be unique?  Or is there a reasonable use case?

**Comment by lexaknyazev** [comment]
Each `node`/`path` pair must be unique already. This issue is about reusing binary data.

**Comment by lexaknyazev** [comment]
As of `2.0.0-dev.1.7`, glTF-Validator issues an error on using the same accessor as an animation sampler output with cubic spline and non-cubic spline data. The spec should be updated to reflect that.

**Comment by donmccurdy** [comment]
There is a good point mentioned in https://github.com/KhronosGroup/glTF/issues/1267 ...

> One issue with this change that I did not mention, is that while [ restricting accessor IDs ] would allow for greater flexibility for loaders implementation, it would make it a bit more complex for developers of "optimiser" tools such as gltf-pipeline, as it would need to be considered when de-duplicating accessors.

The same thing applies here: if we're going to add restrictions on accessor reuse, we should be aware that optimizers do become more complex, and perhaps write some best practice for optimizers. I've seen [one optimizer in the wild already](https://gist.github.com/mattdesl/aea40285e2d73916b6b9101b36d84da8) that de-duplicates accessors without comparing their purposes.

**Comment by donmccurdy** [comment]
Good to hear pros/cons but I don't think the use cases we've identified (yet) justify the limitation on optimizers...

**Comment by lexaknyazev** [comment]
Whatever optimizers do, they shouldn't produce invalid files. E.g. accessors with vertex/index/animations data have different alignment requirements and their usage restrictions are already in the spec.

This particular issue is about virtually impossible case that is shown in the first post above. There's no chance that spline tangents interleaved with spline values could be reused as something else, especially when they contain rotations (because of quaternion normalization requirement).

**Comment by donmccurdy** [comment]
What I mean is that if we have these two accessors:

```js
[
  "accessors": [
    ...
        {
            "bufferView": 1,
            "byteOffset": 7032,
            "componentType": 5126,
            "count": 586,
            "type": "VEC3"
        },
        {
            "bufferView": 1,
            "byteOffset": 7032,
            "componentType": 5126,
            "count": 586,
            "type": "VEC3"
        }
  ]
]
```

... I'm not aware of any existing restrictions currently in the spec that would prohibit an optimizer from blindly "de-duplicating" this. I agree the particular case you want to forbid is exceedingly unlikely. But the benefits of the restriction are vague, and the inconvenience to an optimizer is significant, so I'm nervous about it.

**Comment by lexaknyazev** [comment]
Existing restrictions are mostly inherited from buffer views (e.g., an asset has to use different buffer views for vertices and indices, so the same accessor cannot be re-used for both; also alignments). They shouldn't cause any issues with typical de-duplication routines.

**Comment by donmccurdy** [comment]
I'm assuming that two accessors have precisely the same JSON properties, and point to the same buffer view... it would seem like a very natural de-duplication routine would catch the case I show above? 

A higher-level question, aside from the fact that it's unlikely, is there benefit to disallowing this?

**Comment by lexaknyazev** [comment]
> A higher-level question, aside from the fact that it's unlikely, is there benefit to disallowing this?

Theoretical possibility of the same accessor being interpreted as containing cubic splines in one case and plain values in the other may lead to unnecessary runtime burden.

It's much more likely that an exporter linking the same output accessor for different interpolation types has a bug.

**Comment by lexaknyazev** [comment]
I think we can leave this issue as it is: a validation issue with no spec change.
