### ISSUE TITLE
Sync spec with JSON schemas

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#1266]
Properties Reference section is outdated and needs to be synced with schemas. Could we make this happen automatically on each schemas update? 

Also, "Last updated" date is incorrect.

/cc @pjcozzi @donmccurdy @javagl

**Comment by javagl** [comment]
It's somewhat embarassing that I didn't manage to tackle https://github.com/KhronosGroup/glTF/issues/1013 yet. I'm not sure how the update could be done automatically, but I can try to run wetzel over the latest spec this week and provide the result as a PR (possibly, with manual tweaks for 1013)

**Comment by pjcozzi** [comment]
@bghgary or one of his colleagues may be the best to advise on updating re-generating the schema.

It will be a bigger change to do it automatically for each update and may not be worth it until we start significant future spec work.

**Comment by bghgary** [comment]
This is what I'm running locally from the wetzel\bin folder:
> wetzel\bin>node wetzel.js ../../glTF/specification/2.0/schema/gltf.schema.json -l 2 -p schema -i "['gltfid.schema.json', 'gltfchildofrootproperty.schema.json', 'gltfproperty.schema.json']"

If I remember correctly, we didn't add the auto link flag `-a` because there were cases where it incorrectly linked references that should not have been linked.

**Comment by javagl** [comment]
The `-a` flag indeed seems to add references/links in texts very aggressively (basically, using a RegEx), and causes some not-so-pretty results. But I think it should be possible to at least add the respective links dedicatedly in the "Type" column of the Properties table. I'd give this a stab ASAP. 

(BTW: Maybe someone here want to share their thoughts on https://github.com/AnalyticalGraphicsInc/wetzel/issues/29 ?)

**Comment by emackey** [comment]
Note the -a flag takes a parameter (from memory I think it's `-a=cqo`) that links code-quoted references only.  If you can get that working, it's far less aggressive than full auto-link.

**Comment by javagl** [comment]
OK, I tried that. The resulting output when using `-a=cqo` is shown at https://github.com/javagl/glTF/blob/d0b6dee76f5c14ac2e13cb5f459ca3b2b406ab2f/specification/2.0/README.md#properties-reference 

**but** there are still some formatting issues:

- Capitalization of type names
- Camel-case types like `bufferView` are by default formatted as `buffer.view`, which is clearly not intended. 
- Some places where the type link should be inserted are not in code quotes (but leaving out the `cqo` is too aggressive, and cannot be used either)

If desired, I can create a PR for this state. But in this case, I should at least manually replace all `buffer.view` appearances with `bufferView`, right?

Beyond that, I'd try to find solutions for this directly in wetzel.

**Comment by emackey** [comment]
If I recall correctly, the capitalization changed intentionally at some point, but the change was only applied to the schema titles and not to the wetzel output.  If the new result from wetzel looks OK, then I wouldn't worry about keeping it the same as before, as it's better to have it be in sync with the tool.

The camel-case thing sounds like a bug in wetzel.

For places where the link should be inserted, would it be OK to add code quotes to the schema?  Again just looking for ways to reduce the friction on future re-runs of this tool.

**Comment by javagl** [comment]
>  reduce the friction on future re-runs of this tool.

+1, any manual tweaking will cause headaches (regardless of whether this means quick, local fixes in wetzel for generating the glTF output, *or* manually editing the output). 

So I'll try to fix this CamelCase issue, create a PR for that in wetzel, and then create a PR for the corresponding output here.

**Comment by javagl** [comment]
Further (small) steps here. 

I dug up the PR where the CamelCase issue was introduced: https://github.com/KhronosGroup/glTF/pull/1014 : Basically, the original `title` of the schemas have been converted into a more elaborate, human-readable form. While it is good that e.g. the `"sampler"` has been made more specific and called `"Animation Sampler"` , the fact that `"bufferView"` was renamed to `"Buffer View"` caused some of the downstream pipeline to break. This opened some can of worms, and https://github.com/AnalyticalGraphicsInc/wetzel/pull/22 was created to fix... some of it, but not all. 

I now tried to retain the "type name" (that is, basically the name of the JSON schema file excluding the `schema.json` part) in the schema, and use it where appropriate. The result can be seen at

https://github.com/javagl/glTF/tree/update-properties-from-schema/specification/2.0#objects

It's still not perfect: Some links are not leading to the right anchors (for some links, there is a `reference` prefix added - I'll still have to figure out some details there). But if the *general* formatting and link structure is OK, I'd try to fix the linking and create the PRs.
