### ISSUE TITLE
Does the `extensions/2.0/Khronos/KHR_technique_webgl` references the `arrayValues.schema.json` in `specification/1.0`?

### ISSUE THREAD

**Issue by alexchicn** [KhronosGroup/glTF#1279]
In `extensions/2.0/Khronos/KHR_technique_webgl/schema/technique.parameters.schema.json`, the property - `properties.value` references the `arrayValues.schema.json` that just exists in `specification/1.0`.

Need copy the `arrayValues.schema.json` to `specification/2.0`?

**Comment by donmccurdy** [comment]
Note that the `KHR_technique_webgl` extension is very much still a draft, and not implemented in tools yet — see https://github.com/KhronosGroup/glTF/issues/1217. But thanks we will make sure that is corrected as we move forward with the extension!

**Comment by pjcozzi** [comment]
Should we consolidate this issue into #1217?
