### ISSUE TITLE
[bufferView.byteLength] how does stride affect this value?

### ISSUE THREAD

**Issue by chipweinberger** [KhronosGroup/glTF#1281]
Is the length the  buffer view "spans" the underlying raw buffer? Or is it the number of bytes in the view itself? e.g. if stride was 4, is it length *4 or just length?

I have not seen this specified in the spec. 

Chip

**Comment by zellski** [comment]
It’s the raw byte count — the byteStride is really mostly there for vertex attritbute accessors, I think, and especially interleaved ones. It’s accessor.count you would multiply by stride.

**Comment by chipweinberger** [comment]
Ah yes. So the length the buffer view "spans" the underlying raw buffer.

It would not even make sense for it to be "the number of bytes in the view itself" since we don't know how big each element is (which is specified in the accessor).

**Comment by lexaknyazev** [comment]
@chipweinberger 
Could this issue be closed or do you think the spec could be more explicit?

**Comment by chipweinberger** [comment]
It could definitely be clarified, because stride makes it ambiguous alone.  

Maybe, "The total length of the buffer. The length from the first byte in the buffer to the last byte in the buffer".

**Comment by chipweinberger** [comment]
The other interpretation of "the number of elements in the buffer view" does not make sense, because buffer views are not concerned with elements (despite having a stride value), but I still think the clarification would solve this ambiguity 100%.
