### ISSUE TITLE
WEB3D_quantized_attributes link is broken

### ISSUE THREAD

**Issue by eodabash** [KhronosGroup/glTF#1282]
This link has been broken since last week:

https://github.com/KhronosGroup/glTF/blob/master/extensions/Vendor/WEB3D_quantized_attributes/README.md

Is this a known issue, or was it intentionally removed?

**Comment by javagl** [comment]
The extensions have been moved into version-specific directories - here, the `1.0` part was added, so the new link is 

https://github.com/KhronosGroup/glTF/blob/master/extensions/1.0/Vendor/WEB3D_quantized_attributes/README.md

(If the old link still appears somewhere (maybe in another README), just drop a note here, then it will be fixed quickly)

**Comment by eodabash** [comment]
Ah I see, thanks. I was just trying to read the spec for the extension and every link I followed from Google was taking me there. 

A few quick examples:
https://github.com/KhronosGroup/glTF/issues/588
https://cesium.com/blog/2016/08/08/cesium-web3d-quantized-attributes/
https://www.khronos.org/assets/uploads/developers/library/overview/gltf-overview.pdf

**Comment by javagl** [comment]
Thanks for the hints. 

The link in the issue has been updated. 
The link in the blog entry could probably only be updated by the Cesium team (@pjcozzi )
The task to update the links in the overview is already scheduled as of https://github.com/javagl/gltfOverview/issues/3 

If there are no objections, I'd close this issue later today. 

(If there are further outdated links, they could still be mentioned here, and if necessary, the issue can be reopened)

**Comment by pjcozzi** [comment]
Thanks @eodabash!

We'll fix the Cesium blog post link.
