### ISSUE TITLE
BaseColor factor & texture

### ISSUE THREAD

**Issue by Selmar** [KhronosGroup/glTF#1286]
Looking at the material model, I do not understand why the base color map is inside the `pbrMetallicRoughness` object. Surely any material model would have a base color texture? 

The `pbrSpecularGlossiness` extension has it as well, however it is called diffuse instead of baseColor. 

Is there an idea I am missing, or is this something that could be addressed?

**Comment by emackey** [comment]
The baseColor is different from diffuseColor, in that baseColor affects the reflected specular color of metallic surfaces, and the diffuse color of non-metallic surfaces.

Models using `pbrSpecularGlossiness` should not supply a baseColor texture, as they already supply their own diffuse and specular color textures indpendently.

**Comment by donmccurdy** [comment]
One additional note is that because baseColor and diffuseColor do not store the same information with metal/rough and spec/gloss workflows, models wishing to use spec/gloss with a "fallback" to metal/rough (which is more widely supported) would need to include both textures. Hence the need for separate properties.

**Comment by Selmar** [comment]
Thanks for the replies! I could have read a bit more before posting an issue, sorry.

Reading the appendix of the `pbrSpecularGlossiness` extension, it seems like the conversion is straightforward (baseColor = specular), but with what I know about these models, I assume the metallic property would ruin any simple conversion. Of course, there's also different texture packing in this case.

I guess we can conclude I was missing something. 👍
