### ISSUE TITLE
Animations targeting matrix nodes

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF#1287]
Our sample models all seem to have animations that target existing properties in nodes.  For example, [AnimatedTriangle line 11](https://github.com/KhronosGroup/glTF-Sample-Models/blob/c589f377c84b4767ef1532e51e92173f47b1eb42/2.0/AnimatedTriangle/glTF-Embedded/AnimatedTriangle.gltf#L11) shows the identity rotation:

```
"nodes" : [
    {
      "mesh" : 0,
      "rotation" : [ 0.0, 0.0, 0.0, 1.0 ]
    }
  ],
```

This `rotation` serves no purpose, but it is the target of an animation that happens later in the same file.

The Khronos Blender exporter produces files that don't have this explicit target, and can for example produce an animation that targets a node's rotation, without explicitly including a rotation field in the node in question.

Is this allowed?  Seems like it should be, and I filed an issue with Cesium to add support for it: https://github.com/AnalyticalGraphicsInc/cesium/issues/6323

This raised another question though:  What if the target node uses a `matrix` for orientation, but still has animations targeting things like `rotation`?  The spec disallows use of both in the node definition, but I don't think we disallow an animation from targeting a rotation on a node that only contains a matrix.  Perhaps this is something the validator could look for (or already does?)

**Comment by lexaknyazev** [comment]
Nodes with defined `matrix` cannot be targeted. The validator checks that.

**Comment by donmccurdy** [comment]
In fact I discovered this rule while working on `THREE.GLTFExporter` because the validator required it. 😅

> Is this allowed? Seems like it should be, and I filed an issue with Cesium to add support for it: 

Agreed. Assuming default `rotation` values should be sufficient in my opinion.

**Comment by najadojo** [comment]
Why is it that nodes that use a matrix aren't animatable? Our implementation decomposes the matrix during import and we allow animation on any node.

**Comment by emackey** [comment]
Good question.  If it were supported by glTF, every implementation would have to identify and decompose any matrix on any animated node.  Typically glTF has trended towards placing the burden on the exporter, not the runtime, where possible.  So in this case, the exporter would be responsible for decomposing any matrix as needed to get animatable targets.

I'm curious to hear other opinions though, if people don't agree with that assessment.

**Comment by donmccurdy** [comment]
I could see this being an extra decompose step for tools or engines that operate on glTF files “in place”, but practically don’t know of any examples. For threejs, TRS animations on nodes loaded with matrix transforms are certainly fine.

**Comment by emackey** [comment]
> For threejs, TRS animations on nodes loaded with matrix transforms are certainly fine.

So, in ThreeJS, if a node has a matrix with a rotation, and also an animation targets that node with a different rotation, does the user end up seeing a combination of the two rotations?  Or does the animation's rotation completely overwrite the matrix rotation?

**Comment by donmccurdy** [comment]
The matrix and TRS properties are kept in sync by three.js automatically. While loading the model in three.js, we use the following:

```js
if ( nodeDef.matrix !== undefined ) {

  node.applyMatrix( new THREE.Matrix4().fromArray( nodeDef.matrix ) );

} else {

  if ( nodeDef.transation !== undefined ) {

    node.position.fromArray( nodeDef.translation );

  }

  // ... similar for rotation/scale

}
```

These are equivalent, because `.matrix` and TRS properties are kept in sync automatically:

```js
applyMatrix ( matrix ) {

  this.matrix.multiplyMatrices( matrix, this.matrix );
  this.matrix.decompose( this.position, this.quaternion, this.scale );

}
```

**Comment by scurest** [comment]
The matrix -> TRS decomposition isn't unique. Quoting from [here](https://github.com/gltf-rs/gltf/issues/21#issuecomment-325210103)

> A matrix is a TRS matrix if and only if
> 
> 1. the last row is [0 0 0 1]
> 2. the columns of its upper-left 3x3 subblock are non-zero and pairwise orthogonal.
> 
> The only if direction is just direct computation. The if direction is from  
> ![trs](https://user-images.githubusercontent.com/11024420/29751969-cd7d8faa-8b1a-11e7-8b9d-36185d966a0a.png)  
> By (2), the middle matrix is orthogonal and the ± is chosen to make it have determinant +1 so that it is a rotation.

So not only do you have a choice between q and -q for one given rotation matrix but you have a choice of where to put the signs on the scale factors.

For example, take the rotation property of `AnimatedTriangle.gltf` here

https://github.com/KhronosGroup/glTF-Sample-Models/blob/01343b024ebea781f2a1d1470bdad3e526845874/2.0/AnimatedTriangle/glTF-Embedded/AnimatedTriangle.gltf#L8-L13

and replace it with

      "rotation" : [ 0.0, 1.0, 0.0, 0.0 ],
      "scale": [-1.0, 1.0, -1.0]

You can check this has the same matrix (the identity) but when it's animated in the viewer the result is different than than the original file (because it has an additional scaling applied), so if it were given by a matrix, the result of animation would depend on how the implementation decomposed it.

Because of this, I think the current rule that nodes with a `matrix` cannot be transformed is a good idea.

**Comment by lexaknyazev** [comment]
@emackey @donmccurdy 
Should we add more notes to the spec or could we just close this issue?

**Comment by emackey** [comment]
@najadojo Do you have a pressing need for this?  Or just something the toolchain happens to support right now?

If no one has started using animations on matrix nodes, and the validator already flags this as invalid, I'm OK with just closing this issue.  @scurest provides some good reasoning why the results can be indeterminate.

**Comment by najadojo** [comment]
No explicit need just our importer supports it. Its always best to be explicit in the spec, if its not already there, otherwise the validator becomes the spec.

**Comment by pjcozzi** [comment]
@emackey any chance you can update the spec here to be more clear that a `matrix` is not allowed in this case?

**Comment by emackey** [comment]
Just found it, it's already in the spec:

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#transformations

> When a node is targeted for animation (referenced by an animation.channel.target), only TRS properties may be present; `matrix` will not be present.

https://github.com/KhronosGroup/glTF/blob/b2860d26da547fa6a14131c12dc6a605fd382770/specification/2.0/schema/node.schema.json#L5
