### ISSUE TITLE
Help to undestand some details about the schema.

### ISSUE THREAD

**Issue by vpenades** [KhronosGroup/glTF#1292]
Sorry to open multiple questions on one issue, this is mostly for clarification, and by all means, I'm not an expert on json schemas.

- Most class declarations inherit from `gltfProperty` which defines `extensions` and `extras` , but then, in derived classes, they're re-declared. Is this done on purpose? it seems redundant to me.
- If class inheritance definition is possible, why perspective and orthographic cameras don't derive from camera? some for materials.
- This one is just out of curiosity: why `AnyOf` enumerations are defined the way they are? some use all capital letters like `SCALAR, VEC2, VEC3`, etc, some other don't, like `Path's translation, rotation, etc`, some are serialized with integers, some others with strings. I don't see the rationale behind it.
- Why `CameraPerspective `has an `AspectRatio `property? the aspect ratio depends on the viewport dimensions, which is only known at render time.
- In Root gltf definition, most collections are defined with `MinItems = 1`, and if we're strict, it would mean that a gltf document would only be valid if having at least one image, one texture, one node, one of everything. As per the current schema, a model with no animations would be invalid.

**Comment by emackey** [comment]
I can address the last one:

> In Root gltf definition, most collections are defined with `MinItems = 1`

You're still allowed to omit the array entirely.  For example, omitting `images` is allowed, but having an empty array of `images: []` is disallowed.  If the array is present at all, it must not be empty.

**Comment by lexaknyazev** [comment]
> Most class declarations inherit from `gltfProperty` which defines `extensions` and `extras` , but then, in derived classes, they're re-declared. Is this done on purpose? it seems redundant to me.

That's the way how "inheritance" works in JSON-Schema v4. We'll move to the latest JSON-Schema spec as soon as it's stabilizes (see #929).

> If class inheritance definition is possible, why perspective and orthographic cameras don't derive from camera? some for materials.

The design of `camera` object is glTF 1.0 legacy. Discussion in #101 may provide some background.

> This one is just out of curiosity: why `AnyOf` enumerations are defined the way they are? some use all capital letters like `SCALAR, VEC2, VEC3`, etc, some other don't, like `Path's translation, rotation, etc`, some are serialized with integers, some others with strings. I don't see the rationale behind it.

Again, these came from glTF 1.0. All integer enums match OpenGL / WebGL definitions. glTF's own enums use upper case. Lower case enums correspond to the names of existing properties. We've decided to not change that for glTF 2.0.

> - Why `CameraPerspective `has an `AspectRatio `property? the aspect ratio depends on the viewport dimensions, which is only known at render time.

When this property is undefined, the aspect ratio will match the viewport. Some use cases may need to force a specific aspect ratio (e.g., square).
