### ISSUE TITLE
How to handle transparency?

### ISSUE THREAD

**Issue by recp** [KhronosGroup/glTF#1293]
Is there a property to set whole mesh/primitive opacity/alpha like COLLADA's one? If `alphaMode` == `BLEND` then can I assume that every pixel's opacity comes from **baseColorTexture**'s (metallic-roughness) or **diffuseTexture**'s (specular-glossiness) alpha channel? 

Since there is no parameter like `material.opacity` we can't animate transparency, right?

**Comment by emackey** [comment]
I believe what you wrote is correct.  Recently I made a model to test glTF's existing alpha options, and opened a PR in https://github.com/KhronosGroup/glTF-Sample-Models/pull/156.  I'm still looking for feedback on how well this model covers all of core glTF's alpha options, but I think everyone has been at GDC all week. 😄

**Comment by emackey** [comment]
Hey, guess what, we do have the parameter you asked for.  It's `material.pbrMetallicRoughness.baseColorFactor[3]` (the last component of baseColorFactor), and I just tested that it works in ThreeJS, BabylonJS, and CesiumJS with blended materials.  The default value is `1.0` as you might expect.

https://github.com/KhronosGroup/glTF/blob/846a13bff8cfca3cf403598b0f7a409d5724b5e2/specification/2.0/schema/material.pbrMetallicRoughness.schema.json#L16

**Comment by recp** [comment]
I missed that! It seems there is no need to extra parameter, if there are no extra feedbacks/comments we can close this for now
