### ISSUE TITLE
Additional Vertex Primitives

### ISSUE THREAD

**Issue by CentaurMare** [KhronosGroup/glTF#1294]
COLOR_0 is the per vertex diffuse color multiplier on the diffuse map and the base colour factor. When it is a vec4 it includes alpha channel.

I would like to invite discussion about including additional per vertex attributes to the glTF 2.0 specification, specifically, but not limited to...

EMISSIVE_0 (vec3) per vertex emissive color. This should have an associated target.EMISSIVE_0 so it can be the target of animations to include nice glow effects.

OCCLUSION_0 (vec3) per vertex occlusion map (ambient color?). Not sure if it would be meaningful to allow it to be an animation target.

METALLICROUGHNESS_0 (vec2) as a multiplier on the metallic-roughness map or the per vertex metallic-roughness if the map is not included.
  I can imagine this as an animation target, for example metal object transition from dirty to clean, but maybe not so useful.

and possibly,

KHR_SPECULARGLOSSINESS_0 (vec4) as a multiplier on the specular-glossiness map or the per vertex specular-glossiness, providing rgb of specular color and glossiness multiplier (or power?) in the alpha channel (not limited to range 0.0 - 1.0).

**Comment by lexaknyazev** [comment]
1. There could be an extension that enables these semantics. The spec explicitly allows this. No schema change is needed.

2. An engine could run into the maximum number of vertex attributes. From [webglstats.com](https://webglstats.com/):
   - WebGL 1.0:
     - 16 - 87.7%
     - 32 - 12.2%
   - WebGL 2.0:
     - 16 - 77.8%
     - 32 - 22.2%

**Comment by takahirox** [comment]
Two thoughts.

1. Do most of major engines support additional Vertex Primitives? Three.js `MeshStandardMaterial` (=PBR material) supports only color vertex. It can't handle any other additional vertex primitives. So doing that in extension would be better than in core, if many engines don't support.

2. Doing that with `KHR_technique_webgl` isn't good? Even engines which don't support additional vertex primitives can handle if they support custom shader. Three.js can do.

**Comment by donmccurdy** [comment]
This would be best as its own extension, I think. There is a proposal (specifically for metal-rough PBR) in https://github.com/KhronosGroup/glTF/pull/1235.

**Comment by CentaurMare** [comment]
I don't want to see glTF tied down to specific engines, or even to OpenGL itself. It should have universal support. 'The JPEG of 3D' if I recall.
Perhaps 'MPEG of 3D' if the model includes animations? :)
So I'm not worried about engines hitting any hardware or OpenGL driver limits, and I really don't care what attributes the major engines currently support or don't support, as I'm not using any of them.
So far my own engine (C#/OpenTK) is below the vertex attribute limit on my laptop, although I haven't implemented features such as shadows and depth-peeling.
Including Joint matrices, Morph Weights, Target Position/Normal/Tangent, my vertex shader is at 13 attributes (I have an extra one beyond the spec for drawing wire-frame) - so if the limit is 16, then I guess I am pretty close to the limit!

For me it has been a learning exercise writing shaders and following the spec for my own glTF viewer in C# - I even wrote my own JSON parser, yes I'm nuts, but I don't like 3rd party libraries and enjoy the challenge.

As there would need to be a second weights array to allow position/normal/tangent morphing on the same mesh, the target.EMISSIVE_0 idea can be scrapped.

I considered a second material per primitive, and a material blend weight under animation control, but it would be horrible to implement!

I'd really like to see animated strobe lights and other animated emissive lighting somehow. Any suggestions?

**Comment by lexaknyazev** [comment]
> I don't want to see glTF tied down to specific engines, or even to OpenGL itself. It should have universal support. 'The JPEG of 3D' if I recall.

Universal support means finding the balance between feature richness and compatibility with existing ecosystem. The core glTF 2.0 is meant to be compatible with WebGL 1.0 (with uint indices and commonly available GLSL extensions) level hardware / engines. Future core versions and/or extensions may raise the bar.

Runtime media formats from other domains (image / audio / video) also have implementation-driven limitations (like maximum resolution or bit-depth).

Developers are free to use custom attributes (starting with `_`) and `extras` for application-specific JSON fields. As new functionality matures, they could define and standardize a [multi-]vendor extension.

> I considered a second material per primitive, and a material blend weight under animation control, but it would be horrible to implement!

What's horrible about that?

> I'd really like to see animated strobe lights

Initially, this could be a material's flag (or you could use `emissiveFactor`) controlled by an animation with STEP interpolation.

**Comment by najadojo** [comment]
I'm working on a proposal for animated properties that would allow a material's emissiveFactor to change over time. Its not ready to share yet but hopefully shortly.

**Comment by CentaurMare** [comment]
@lexaknyazev 

>> I considered a second material per primitive, and a material blend weight under animation control, but it would be horrible to implement!<<

>What's horrible about that?<

**Two materials per mesh!**
The more I think about that, the more it makes sense (and not horrible at all) - so perhaps what is needed is two materials per mesh:  The second material could be used on the reverse side under some flagged conditions, like what they do in Sketchup.

So the only vertex attribute required is a BLEND_0 attribute to blend smoothly between the primary and secondary materials!

Animate the BLEND_0 attribute with target.BLEND_0 and weights provided by a new weights field?

This would work with all Emissive, Normal, Ambient, Diffuse, SpecularGlossiness, MetallicRoughness maps and even COLOR_0 attributes and alpha, and should work regardless of what extensions are used in the materials.

That would be so amazing to see an animated object such as an apple go from smooth and red to wrinkly and brown over time by just supplying different normal maps and diffuse maps to two materials and altering the BLEND_0 attribute with an animation.

@donmccurdy, is this easily achievable with your glTF viewer and other engines?

**Comment by donmccurdy** [comment]
> ...so perhaps what is needed is two materials per mesh: The second material could be used on the reverse side under some flagged conditions, like what they do in Sketchup.

This part can *almost* be done within the current spec, by creating a mesh with two primitives using the same accessors. Each primitive would have a different material. The hitch is that you would need the `KHR_techniques_webgl` extension to set front/back-sided flags on each material, and that isn't complete yet. It's also not settled whether the culling flags will stay in that extension.

> That would be so amazing to see an animated object such as an apple go from smooth and red to wrinkly and brown over time by just supplying different normal maps and diffuse maps to two materials and altering the BLEND_0 attribute with an animation.
> 
> @donmccurdy, is this easily achievable with your glTF viewer and other engines?

The built-in three.js materials cannot do this; blending between two arbitrary materials would be quite hard I think. You could likely make such an effect with `KHR_techniques_webgl`, when it is finished. To me this overlaps with https://github.com/KhronosGroup/glTF/issues/1250 and https://github.com/KhronosGroup/glTF/pull/1235. Morph targets may animate COLOR_0 (or ROUGHNESS_0 + METALNESS_0 as proposed by #1235). 

To me there are three key ideas here

1. Animation of material properties like `baseColorFactor` and `emissiveFactor`.
2. Animation of light `color` and `intensity`.
2. Allow additional material vertex attributes like ROUGHNESS_0 and METALNESS_0.
3. Allow morph targets to target COLOR_0, ROUGHNESS_0, METALNESS_0, ...

Can't speak for other engines but (1) and (2) are the easiest to implement I expect.

**Comment by CentaurMare** [comment]
>This part can almost be done within the current spec, by creating a mesh with two primitives using the same accessors.<

In that case, rather than two materials, it could just be superimposed primitives (shared accessors), with different materials. To work within the existing spec, have one primitive that is animated (shrink or expand the mesh slightly) to show one or the other material, disadvantage is that it would be subject to z-fighting artifacts.

A much better solution may be to have one primitive outside the other, and target the alpha channel of the COLOR_0 of the outer primitive with an animation somehow. This would negate the need for dual materials and BLEND_0 weights.

**Comment by donmccurdy** [comment]
Oh sorry, I was not suggesting two primitives for animated blending between materials. Just for "second material could be used on the reverse side" case.

Animated material changes could probably work the way you suggest. Easier to update the alpha through a uniform corresponding to `material.baseColorFactor[3]` unless you need to animate the effect on a vertex-by-vertex basis. But alpha blending has implications for sorting in WebGL.

**Comment by CentaurMare** [comment]
>Oh sorry, I was not suggesting two primitives for animated blending between materials. Just for "second material could be used on the reverse side" case.<

I know, I was just running with that train of thought. :)

>But alpha blending has implications for sorting in WebGL<

Yeah, it was a bad idea. I didn't realise there was sorting involved.
My engine renders in two passes, first the opaque primitives, then the blend primitives.
I attempted to write an Extended-ZBuffer for really nice alpha blending like you achieve, it worked, but it was slow and there were artifacts.
I haven't attempted 'depth peeling', and anyway it is not part of the spec.

Given the limitations of OpenGL/WebGL, it would be best to not add any more primitive attributes, at least until the hardware and drivers catch up.

Animating the emissive factor in a material would be really useful.
Animating base color factor, not so much.

>Animation of light color and intensity<

When I mentioned strobe lights, I meant as part of the model emissive materials, not as part of the scene lighting. I don't think scene lighting should be bundled into glTF.

**Comment by donmccurdy** [comment]
> When I mentioned strobe lights, I meant as part of the model emissive materials, not as part of the scene lighting. I don't think scene lighting should be bundled into glTF.

It won't be part of the core specification, but there is interest in a [KHR_lights extension](https://github.com/KhronosGroup/glTF/pull/1223). I haven't seen any requests for animation there, at this point. Wouldn't expect lights to be as widely supported as core features, of course.
