### ISSUE TITLE
Hdri/lighting in facebook gltf

### ISSUE THREAD

**Issue by matthiasPe** [KhronosGroup/glTF#1295]
Hi,

i have an issue with a gltf i am creating for on facebook.
I created my gltf files out of substance painter. After placing the glb file on facebook there is no hdr on a pc or mac but on mobile there is a hdr for reflections.

I tried to solve this by adding a hdri in my gltf file but i couldn't figure this out.
With this online viewer https://pissang.github.io/clay-viewer/editor/ a hdri was added but it changed my materials and if i change the parameters in this editor/viewer nothign changed in facebook. i tried changing the files from png to jpg to see if this made a difference using this packer https://glb-packer.glitch.me/. 

How can i change this with for instance my own hdri?

**Comment by Vinc3r** [comment]
I think your issue is more a facebook issue than a gltf itself. Here [their doc'](https://developers.facebook.com/docs/sharing/3d-posts/glb-tutorials?locale=en_US) if it's can help.

**Comment by lexaknyazev** [comment]
glTF 2.0 assets don't contain environment lighting information. 
Maybe @zellski could answer about facebook's behavior.

**Comment by zellski** [comment]
There's no way for end users to upload radiance/irradiance maps for the environment. In fact I don't believe we have image-based **lighting** at all (yet). None of this is a matter of hdr/png/jpg; we just don't look for an environment map in the asset at all, nor does glTF have an extension that'd let us do so in a standardised way (yet). You can reasonably expect some of these features to be added over time. For now, though, you're stuck with choosing a simple 2D background image (which does help a lot in providing a pleasant visual contrast.)

If there's a component to your question that's not about the environment map, please clarify and I will be happy to answer.

**Comment by matthiasPe** [comment]
Would there be a way to include lights in my scene just to create for instance a 3 point light setup?
Or in for instance a model with headlights to place spotlights in particular spaces?

**Comment by donmccurdy** [comment]
Closing as there is no action we can take right now. The `KHR_lights` is not finished yet, but getting closer.
