### ISSUE TITLE
glTF-Generator-Registry

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF#1297]
Had the crazy  idea of creating an open, machine-readable registry of tools that write glTF, indexed by `asset.generator` ID globs. I'm thinking of using it so that when users drag a model into my viewer and validation fails, I can show a URL where they should report the bug. Someone using a wrapper around other tools (web version of COLLADA2GLTF, for example) may not know where to report the problem otherwise.

Since other tools (validator, VSCode extension, Facebook?) could potentially use this, thought I'd put this in a new repository and publish to NPM later:

https://github.com/donmccurdy/glTF-Generator-Registry

If there's interest in making it more official-ish, I'm also happy to transfer it over as KhronosGroup/glTF-Generator-Registry.

**Comment by CentaurMare** [comment]
My current version of my Sketchup Exporter has generator as 'Sketchup glTF Exporter by Centaur' which would work for a registry.

Microsoft has a version number in theirs, 'Microsoft GLTF Exporter 2.2.8-b3', which might be problematic for your registry, but then you can't really report issues to Microsoft.

**Comment by CentaurMare** [comment]
Since you are considering changing the asset field in the spec, why not add an asset.generatorIssues field so that the generator can include a url or email address?

**Comment by donmccurdy** [comment]
We could do that yes, but I like that the registry could even include a homepage, description, etc. without adding any weight to the asset. And I sort of doubt `generatorVersion` will happen either, since it assumes these tools are actually versioned (and do we require semver, or something?). So wildcards it is, heh. This also aligns nicely with proposed `asset.license`, which would use SPDX IDs that can be mapped to more information about the license.

**Comment by Kupoman** [comment]
If there is a better format to follow for generator string, I would be happy to change blendergltf to follow it. I would like to retain the version information some where in the asset data.

**Comment by bghgary** [comment]
> Microsoft has a version number in theirs, 'Microsoft GLTF Exporter 2.2.8-b3', which might be problematic for your registry, but then you can't really report issues to Microsoft.

Users can report issues by using the feedback hub or the "Give feedback" buttons/links inside the apps.

**Comment by donmccurdy** [comment]
> If there is a better format to follow for generator string, I would be happy to change blendergltf to follow it. I would like to retain the version information some where in the asset data.

I agree, I'm glad you're including version information and would like more exporters to do this. For the moment there is no better place to put the version information. I'll put a note in #839 but I don't think it's a pressing issue.

> Users can report issues by using the feedback hub or the "Give feedback" buttons/links inside the apps.

Is it possible to link through to the feedback hub app? Or I can just include some kind of text instructions if not.

**Comment by bghgary** [comment]
> Is it possible to link through to the feedback hub app?

I think it is possible through a URL, but I'm not sure how to do it yet. I think text instructions is fine for now. Use `Apps` Category and `Paint 3D` Subcategory in the Feedback Hub.

**Comment by pjcozzi** [comment]
Killer idea @donmccurdy, let's do it!

If you are OK with it, I think it would be great for this to live in the Khronos GitHub organization.

@outofcontrol can transfer the repo if you agree.

**Comment by donmccurdy** [comment]
Happy to transfer it over — @outofcontrol I don't have that permission on the GitHub organization but let me know if I should do anything here.

**Comment by zellski** [comment]
@lexaknyazev I was just wondering about that. Facebook will shortly tear apart and reassemble all uploaded glTF for internal distribution. Right now I replace the generator entirely, but adding makes some sense.

**Comment by zellski** [comment]
Additionally, should we advocate some common pattern for <identifier> vs <version>? Perhaps:

```
"asset": {
  "generator": "Facebook Internal glTF Transmutator (0.99.3); Microsoft GLTF Exporter (2.2.8-b3)"
  ...
}
```

Alternately we can wait for 2.1 and do:

```
"asset" {
  "generators": [{
     "id": "Facebook Internal glTF Transmutator",
      "version": "0.99.3"
    }, {
     "id": "Microsoft GLTF Exporter",
      "version": " 2.2.8-b3"
    }]
}
```

**Comment by SamuelTS** [comment]
I used a comma as generator separator in [my plugin](https://github.com/SamuelTS/SketchUp-PBR-Plugin) since it performs after [another plugin](https://extensions.sketchup.com/content/gltf-exporter).
`{"asset":{"generator":"Sketchup glTF Exporter by Centaur, PBR extension for SketchUp"}`

**Comment by lexaknyazev** [comment]
@zellski The second option (with array) may work better for debugging purposes. It could have more fields like:
```json
"asset" {
  "generators": [{
      "id": "Facebook Internal glTF Transmutator",
      "version": "0.99.3",
      "cmdline": "--option_a 24 --use_flag_b"
    }, {
      "id": "Microsoft GLTF Exporter",
      "version": "2.2.8-b3",
      "arch": "arm64"
    }]
}
```

Imo, comma-separated string is a fine start for now.

**Comment by Marlamin** [comment]
Could something like this also be used/adapted for importers/apps that can open glTF? I'm working on a new site for my exporter and it would be neat to show an automated up-to-date list of apps on my site that can import glTF models exported with my exporter. I often get the question of "but in what can I use these files" and something like this (but the other way around) could be the answer.

**Comment by donmccurdy** [comment]
I'm not crazy about the idea of comma-separated generators in existing field, to me that seems similar to other requests in #839 that can be handled with `asset.extras.generators = [...]` for now and addressed in a future spec update or extension later.

@Marlamin what kinds of importers/apps do you have in mind? The README of this repo lists [many tools](https://github.com/khronosgroup/gltf#gltf-tools), varying from optimizers, validators, engines, to end-user applications. The current/easy option would be to link to any sections there that seem appropriate. 

Not sure how helpful a flat JSON list of all of those tools would be, without metadata to filter it down somehow? Depends on your use case I guess but I imagine you want to list a few good examples rather than an exhaustive list of things that read glTF.

**Comment by Marlamin** [comment]
@donmccurdy Mostly 3D applications (some of which hopefully getting official support at one point) such as Blender, 3DS Max, Cinema 4D, Paint 3D etc. Stuff end-users/non-devs can use to manipulate/use models in. I guess you're right in saying that'll vary per use case (even within my userbase) and it'll be tough to make a good list for everyone without having a ton of filters/metadata. Linking to the readme should be fine as an initial solution but a lot of it is stuff meant for devs, not users. I'll think about this some more and maybe get something going myself as I'll need such a list at one point anyways (when glTF adoption grows beyond the list in readme, which I feel it might soon). Great idea, can't wait to get my exporter to a state where it's usable enough to be added to this list. :)

**Comment by donmccurdy** [comment]
Registry is up and useable, and I'm using it to provide links to docs and bugs in https://gltf-viewer.donmccurdy.com/ now. The list is not exhaustive, but covers everything I could find quickly. I think this bug can be closed, but PRs and suggestions are still welcome.

<img width="755" alt="screen shot 2018-07-11 at 8 15 28 pm" src="https://user-images.githubusercontent.com/1848368/42610612-37b0e6b6-8547-11e8-8da5-45b73aeb3103.png">

<img width="755" alt="screen shot 2018-07-11 at 8 15 30 pm" src="https://user-images.githubusercontent.com/1848368/42610614-3a03c690-8547-11e8-8ae4-7539d36e27a0.png">
