### ISSUE TITLE
Specification of textures can be confusing

### ISSUE THREAD

**Issue by ale64bit** [KhronosGroup/glTF#1310]
I find these details can be slightly confusing in the spec:

1. Why the scaling factor of occlusion and emissive textures differ? i.e. the occlusion [strength](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#occlusiontextureinfostrength) is part of the occlusion texture info and the [emissiveFactor](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#materialemissivefactor) is outside the emissive texture object. This can be confusing.
2. The [baseColorTexture](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#pbrmetallicroughnessbasecolortexture) and [emissiveTexture](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#materialemissivetexture) specify the values are in sRGB. The others ([metallicRoughnessTexture](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#pbrmetallicroughnessmetallicroughnesstexture), [normalTexture](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#materialnormaltexture) and [occlusionTexture](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#materialocclusiontexture)) specify the values are linear. In the [Metallic-Roughness Material section](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#metallic-roughness-material) it's mentioned that *"Texture content must be converted to linear space before it is used for any lighting computations."* immediately after referring to the `metallicRoughnessTexture`: this can be confusing.

**Comment by bghgary** [comment]
> 1. Why the scaling factor of occlusion and emissive textures differ?

This is because emissive factor can stand alone by itself. Occlusion strength can only exist when occlusion texture is set.

> 2. ...

+1 on this. I will fix it.

**Comment by ale64bit** [comment]
> This is because emissive factor can stand alone by itself. Occlusion strength can only exist when occlusion texture is set.

Makes sense. Thanks for clarification!
