### ISSUE TITLE
Animation signed normalized data formula

### ISSUE THREAD

**Issue by bghgary** [KhronosGroup/glTF#1317]
@lexaknyazev

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#animations

|`accessor.componentType`|int-to-float|float-to-int|
|-----------------------------|--------|----------------|
| `5120`&nbsp;(BYTE)          |`f = max(c / 127.0, -1.0)`|`c = round(f * 127.0)`|
| `5122`&nbsp;(SHORT)         |`f = max(c / 32767.0, -1.0)`|`c = round(f * 32767.0)`|

The range of signed byte is from `-128` to `127` and signed short is `-32768` to `32767`. As written, `-128` and `-32768` will never be used. Is that expected?

Original PR: #991

**Comment by lexaknyazev** [comment]
Yes. This normalization rule matches OpenGL 3.0+, [Vulkan](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#fundamentals-fixedconv),  and [Direct3D](https://msdn.microsoft.com/en-US/library/windows/desktop/dd607323(v=vs.85).aspx#integer_conversion).

**Comment by bghgary** [comment]
Thanks!
