### ISSUE TITLE
Node tree in 2.0

### ISSUE THREAD

**Issue by dakom** [KhronosGroup/glTF#1321]
The docs state:

> For Version 2.0 conformance, the glTF node hierarchy is not a directed acyclic graph (DAG) or scene graph, but a strict tree. That is, no node may be a direct or indirect descendant of more than one node. This restriction is meant to simplify implementation and facilitate conformance. The restriction may be lifted later.

"The restriction may be lifted later" feels a bit ominous ;) - if a renderer adheres to the spec today, and then this restriction is lifted, that could break the renderer even if it doesn't break exporters (since a renderer would likely parse the gltf into its own runtime structure and make certain assumptions based on this restriction)

**Comment by pjcozzi** [comment]
@dakom thanks for the feedback.  If the restriction was lifted, it would, of course, be in a future 3.x version where a breaking change is allowed.

@lexaknyazev @bghgary I suggest we just remove "The restriction may be lifted later."  I don't think it adds any value and clearly is creating some confusion.  What do you think?

**Comment by bghgary** [comment]
> @lexaknyazev @bghgary I suggest we just remove "The restriction may be lifted later." I don't think it adds any value and clearly is creating some confusion. What do you think?

+1 from me. I have had discussions about this many times and it makes sense to me to remove it.

**Comment by lexaknyazev** [comment]
+1, let's clarify these as well (question is virtually the same): #1086, #1096.

**Comment by pjcozzi** [comment]
@lexaknyazev any chance you want to make the spec change? ☺️

**Comment by pjcozzi** [comment]
Bump @lexaknyazev??? 😀

**Comment by lexaknyazev** [comment]
Will open a PR to address those.

**Comment by lexaknyazev** [comment]
Fixed with #1358.
