### ISSUE TITLE
Force a node to be the inverse of another node at runtime?

### ISSUE THREAD

**Issue by Ziriax** [KhronosGroup/glTF#1322]
Maya has this feature called "segment scale compensation", that undoes the scale of a parent joint, allowing each joint to be scaled non-uniformly without introducing skewing. This is on by-default, since rarely you want skewing in rigs.

In our [Maya2glT](https://github.com/Ziriax/Maya2glTF) exporter we now have experimental support to deal with this, by creating two glTF nodes for each Maya joint that has segment-scale-compensation enabled (one for the rotation and scaling, another one for the translation and inverse-parent-scale). We bake all the animation into these nodes. This works fine for simple playback.

However, to correctly implement this even when the nodes are scaled at runtime (e.g. when mixing two animations or in a game), the node that stores in the inverse-parent-scale should by updated too.  This is cumbersome.

It would be a nice feature to have a flag that indicates that a node is always the inverse of another node.

This would also help to implement pivot points (although it is more efficient to offset the geometry when exporting, wouldn't it be for the fact that Maya has two potentially different pivot points, one for scaling, one for rotation, but this feature is rarely used)

For example, the complete formula to construct a [Maya transformation matrix](http://download.autodesk.com/us/maya/2009help/api/class_m_transformation_matrix.html) involves many of these inverses. I'm sure other DCC software has similar inverses.

```
     -1                       -1
  [Sp]x[S]x[Sh]x[Sp]x[St]x[Rp]x[Ro]x[R]x[Rp]x[Rt]x[T]
```

Does an extension already exist for doing this?

Thanks,
Peter Verswyvelen

**Comment by pjcozzi** [comment]
@Ziriax thanks for the idea and all your work on the Maya exporter.  I don't believe an extension like this exists.  You may want to first try it out as a vendor extension and see what the community thinks.

**Comment by Ziriax** [comment]
In our case (WonderMedia) it just happens to work out fine without an extension because we do animation blending in the log-scale domain (aka multiplicative blending). When doing so the inverse of the blended scale is the blended inverse scale, so we do not need an extension :-) 

I'll put in the backlog.

Thanks!

**Comment by zellski** [comment]
I know this is months old, but... I think that if we were going to add support in glTF for Segment Scale Compensation, what we should add is configurable transform inheritance at the node level, which as I'm sure you know is how the Maya feature is implemented at the FBX level. That format allows several different ways that a local node's world matrix can be computed from its local matrix & parent's world matrix, including "do not inherit scale at all". It would solve an ancient FBX2glTF limitation.

(I'm not crazy about the idea of adding this to glTF, I imagine it would be tricky to implement in many engines, and I've gotten used to telling all artists to always turn off SSS!)
