### ISSUE TITLE
Clarification needed for embedded buffer mimetypes

### ISSUE THREAD

**Issue by jessey-git** [KhronosGroup/glTF#1323]
I think there needs to be some clarification on acceptable mimetypes for embedded buffer base64 data.

On the one hand there's the actual spec and 32 out of 34 samples from glTF-Sample-Models that seems to imply the use of : data:application/octet-stream;base64

On the other hand is the the Picture diagram (colored boxes) and 2 out of 34 samples that seems to imply the use of : "data:application/gltf-buffer;base64

Which one is correct?

**Comment by scurest** [comment]
Cf #1180

**Comment by lexaknyazev** [comment]
Closing as duplicate. #944 tracks IANA approval process.
