### ISSUE TITLE
Add my webgl library?

### ISSUE THREAD

**Issue by PrincessGod** [KhronosGroup/glTF#1328]
Hi, I create a webgl2.0 based library [czpg.js](https://github.com/PrincessGod/CraZyPG),
and there is a gltf loader [sample](http://princessgod.com/CraZyPG/gltfloader.html),
also added into [gltf-test](https://github.com/cx20/gltf-test).

So i was wandering if it is possible to add my library into README list?

**Comment by emackey** [comment]
Great job on the gltf-test suite!  Looks like everything except Draco is passing.

For faster service on this, feel free to open a PR to this repo to add it to the README.  Otherwise we'll get to it next time someone sweeps through the backlog in #1058.  Thanks!
