### ISSUE TITLE
Meshes with no POSITION semantic

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#1332]
The 2.0 spec doesn't require POSITION attribute semantic to be present. We need to check with implementations if that's the case and update them or the spec (or add an impl. note).

- [x] **Validator** flags that as an error.
- [x] **three.js** - mixed (see below)
- [x] **Babylon** - no error
- [x] **Cesium** - bug (see below)

/cc @donmccurdy @bghgary @emackey

**Comment by takahirox** [comment]
Three.js: Renders nothing without any errors

**Comment by takahirox** [comment]
Three.js: Renders nothing without any errors

**Comment by emackey** [comment]
Cesium says:

> Uncaught TypeError: Cannot read property 'center' of undefined

Sounds like an undefined bounding sphere.  I'm sure we would fix this, particularly if it becomes needed for the KHR_technique_webgl extension.

**Comment by recp** [comment]
> The 2.0 spec doesn't require POSITION attribute semantic to be present. 

Is it a bug of spec? 

Since `primitives` has/have POSITION attrib I presume that we are talking about primitive's POSITION attrib

Is there a special meaning (or use case) of mesh/primitive with no position (or just POSITION )? I guess no POSITION attribute also means there are no positions data in mesh/prim, am I right here?

> articularly if it becomes needed for the KHR_technique_webgl extension.

May I ask why it would be needed in WebGL side? (Sorry I didn't follow `KHR_technique_webgl` updates)

**Comment by lexaknyazev** [comment]
> I guess no POSITION attribute also means there are no positions data in mesh/prim, am I right here?

Yes.

> May I ask why it would be needed in WebGL side?

Custom vertex shader could generate `gl_Position` based on some other data (like app-specific custom attribute).

**Comment by bghgary** [comment]
> Could glTF-Asset-Generator have test cases for this (both indexed and non-indexed)?

I've added an issue for it.

**Comment by recp** [comment]
> Custom vertex shader could generate gl_Position based on some other data (like app-specific custom attribute).

I didn't think this part, thanks for clarification. A sample model (not specific to WebGL extension) about this would be wonderful to test importer and render engines. I like glTF's sample/test models.
