### ISSUE TITLE
normalization for position and normals

### ISSUE THREAD

**Issue by jackcaron** [KhronosGroup/glTF#1334]
Is there a particular reason to not support normalization for positions and normals?

Could be extremely useful to reduce some of the data, particularly for normals. For positions, it requires proper analysis of the point set before doing it (*but that can be an option on the glTF writer*). And because Draco is not supported everywhere (*not on Facebook when I'm writing this*), we need anything that can help make those files smaller.

**NOTE:** I actually don't know if it's not officially supported, could depend on the glTF reader used, but it's not in the specs. And it could be actually supported for any mesh attributes and simply be defined in the accessor.

**Comment by lexaknyazev** [comment]
> Is there a particular reason to not support normalization for positions and normals?

I think the main reason is the need to store qunatization parameters somewhere. There was a separate extension [WEB3D_quantized_attributes](https://github.com/KhronosGroup/glTF/tree/master/extensions/1.0/Vendor/WEB3D_quantized_attributes) for glTF 1.0. It should be possible to update it for 2.0 if there's enough interest.

AFAIU, Facebook will support Draco someday.

**Comment by gkjohnson** [comment]
I agree with this -- I was surprised that it wasn't an option for normals, at least. I'd like support for quantized positions, as well, though.

> But for normals (and tangents), I think there would be a very small lost in precision. With SHORT, that still give you 64K values possible to express values between -1 and 1. Which is quite good. So you can save half the size to store these.

For some uses I'm happy with BYTE precision. I'd prefer a smaller download size to the precision gains in some cases.

**Comment by zellski** [comment]
We will support Draco at Facebook, but can't make any prediction when.

For what it's worth, we've had a few occasions internally where we were mildly surprised by this constraint. We wanted to generate geometry-dominated models as compactly as possible, and the loss in precision would've been tolerable. (The same goes for animation translations.)

I agree with @lexaknyazev though, that the format would need to be able to communicate a linear range to map onto, for each individual attribute. Mapping to [0, 1] or [-1, 1] and trusting the loader to intuit what to do seems insufficient.

**Comment by jackcaron** [comment]
@donmccurdy I could see that as an extension without any extra attributes, like the *KHR_materials_unlit*, where it informs the *glTF* importer that this primitive might use normalized values. And those values are described in the accessors.

**Comment by lexaknyazev** [comment]
Addressed by the `KHR_mesh_quantization` extension.
