### ISSUE TITLE
Lack of scale/offset for texture samplers is a major limitation, should be addressed

### ISSUE THREAD

**Issue by bhouston** [KhronosGroup/glTF#1335]
Just a quick note that the lack of per-texture scale and per-texture offset is a major compatibility limitation with a lot of models and it can not effectively be fixed without adding multiple UV channels to glTF, which increases the size of the files.  Per-texture scale/offset are allowed in both Collada, and FBX, the two high quality transfer formats.

I have an outstanding 2-year old PR to Three.JS that enabled this as well here: https://github.com/mrdoob/three.js/pull/8278

In my experience (and Clara.io has more than 1M models at this point) more than 60% of all high quality CG models utilize per-texture scaling and per-texture offsets in order to achieve their effects.

The only models that to do not generally use per-texture scale/offset is unwrapped and baked models.  That is a large component of models, but it is far from the majority of all models in existence.

**Comment by donmccurdy** [comment]
> In my experience (and Clara.io has more than 1M models at this point) more than 60% of all high quality CG models utilize per-texture scaling and per-texture offsets in order to achieve their effects.

Thank you, this sort of data is very valuable to us. 👍

As @lexaknyazev says we are quite close. I have an [implementation for three.js](https://github.com/mrdoob/three.js/pull/13831), but without your PR #8278, it is of limited use.

**Comment by donmccurdy** [comment]
Closing this issue, please track #1015 for updates. :)
