### ISSUE TITLE
Morph Targets with different accessors count

### ISSUE THREAD

**Issue by sjfricke** [KhronosGroup/glTF#1339]
What are the rules in place if I have a

```
"meshes": [
    {
      "primitives": [
        {
          ...
          "targets": [
            {
              "NORMAL": 3,
              "POSITION": 4,
              "TANGENT": 5
            }
        ...
```

And the `accessors` at 3, 4, and 5 have different `accessors.count`

First I am not sure if a model can have a different number of `NORMAL` vec3 then `POSITION` since its all a per-vertex change.

I guess not sure if this something that is implict and not stated in the spec or something to be aware of when parsing to not assume the same count, which if later then how does one handle that

**Comment by lexaknyazev** [comment]
That's implicit. All "base" accessors of a primitive must have the same `count` and each "morphed" accessor must have the same `count` and `type` as the "base" accessor of the same semantic.

**Comment by sjfricke** [comment]
Ok good to know!

I guess I didn't read it as "morphed to base" **comparing** because it **list** `POSITION`, `NORMAL`, and `TANGENT` valid types of `vec3` and `FLOAT`. Also you can't just go `type` for `type` cause the `TANGENT` has the note about why it has to drop from a `vec4` to a `vec3`

**Comment by lexaknyazev** [comment]
Ah, forgot about `TANGENT`'s special case. Do you think the spec should be clarified somehow about `count`?

**Comment by sjfricke** [comment]
Well it has the 

> `POSITION` accessor **must** have `min` and `max` properties defined.

part, maybe it should be added there in a subsection about "targets's accessor requirements"
