### ISSUE TITLE
SameFileError

### ISSUE THREAD

**Issue by derivou** [KhronosGroup/glTF#1341]
Hi, it is my first experience with gltf 2.0. I exported from Blender 2.79b an animated object with material and shape keys but it exported stops saying : raised SameFileError mentionning file .../myfile.jpg and ...\\myfile.jpg is the same. I could not find any ref to this in differents comments ?

**Comment by donmccurdy** [comment]
This is a bug in the Blender exporter — see https://github.com/KhronosGroup/glTF-Blender-Exporter/issues/208. I think it will be fixed soon, meanwhile you can work around it by changing the name of the image in the texture panel or saving to another folder.

**Comment by derivou** [comment]
Thanks ; work around made perfectly the job for export.
