### ISSUE TITLE
JSON must use UTF-8 encoding without BOM

### ISSUE THREAD

**Issue by bghgary** [KhronosGroup/glTF#1345]
@lexaknyazev 

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#json-encoding

> 1. JSON must use UTF-8 encoding without BOM.

Is there a specific reason why we restrict it to "without BOM"? Can we add some validation to the validator?

https://github.com/KhronosGroup/glTF/issues/831 seems to talk about this, but I see no discussion on BOM.

**Comment by lexaknyazev** [comment]
From [RFC-7159 (JSON), section 8.1](https://tools.ietf.org/html/rfc7159#section-8.1)
> Implementations MUST NOT add a byte order mark to the beginning of a JSON text.  In the interests of interoperability, implementations that parse JSON texts MAY ignore the presence of a byte order mark rather than treating it as an error.

Also it allows loaders to not support full UTF-8 charset because all glTF-defined strings are ASCII-representable.

The validator will refuse to load an asset starting with BOM in some cases, I'll investigate to make that consistent across all builds/inputs.

**Comment by bghgary** [comment]
> The validator will refuse to load an asset starting with BOM in some cases

http://github.khronos.org/glTF-Validator/ doesn't fail.

Here is an asset with a UTF-8 BOM:
[AssetWithBOM.zip](https://github.com/KhronosGroup/glTF/files/2028882/AssetWithBOM.zip)

**Comment by lexaknyazev** [comment]
@bghgary What kind of validation result would you prefer?
- refuse to read an asset as if JSON is broken; or
- read as usual but issue an additional error.

**Comment by bghgary** [comment]
I would prefer the second if it's not too much trouble.

**Comment by lexaknyazev** [comment]
The validator update will land today. Do we need any spec changes?

**Comment by bghgary** [comment]
> Do we need any spec changes?

I don't think we should remove the restriction from the spec, but it might be useful to have an implementation note similar to what you referenced earlier in RFC-7159 (JSON), section 8.1.
