### ISSUE TITLE
Request for MOZ Prefix

### ISSUE THREAD

**Issue by robertlong** [KhronosGroup/glTF#1349]
Mozilla would like to register the MOZ vendor prefix. I'll be submitting a PR for our first vendor extension proposal shortly. Thanks!

**Comment by aaronfranke** [comment]
Where can we find specs for the `MOZ_` extensions? There aren't any PRs in this repo, and the contact information may as well be non-existent (how do I get from the front page of Mozilla to contacting Mozilla about glTF?).
