### ISSUE TITLE
Relax requirement for morph target's POSITION?

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#1357]
The spec says this for **morph target**'s POSITION:
> `POSITION` accessor **must** have `min` and `max` properties defined.

I don't think this requirement serves any good since these are bounds of _deltas_ of positions. Adding them to the mesh's bounding box won't produce the bounding box of a morph target.

Is there any implementation that actually uses these values?

/cc @bghgary @donmccurdy @emackey

**Comment by donmccurdy** [comment]
`position.min + targetPosition.min — position.max + targetPosition.max` still gives a valid bounding box, just not a minimal/tight one, yes? It doesn't seem useless to me, but admittedly we're not using them in our implementation.

**Comment by lexaknyazev** [comment]
> just not a minimal/tight one

Depending on values, it may be completely useless: think of a polygon-to-star morphing.

**Comment by emackey** [comment]
Not sure I understand.  Could morphing ever produce a final position that was higher than @donmccurdy's `position.max + targetPosition.max` ?  If not, I would think this would still be useful for non-tight bounding volume computations.

That said I don't know much about the morphing implementation in Cesium or whether these are used there.

**Comment by lexaknyazev** [comment]
> Could morphing ever produce a final position that was higher...

I can't think of any example of that. Nevertheless, I'm questioning usefulness of a "non-tight" volume computed this way.

**Original figure**
![image](https://user-images.githubusercontent.com/3479527/40874139-8fa1d1c6-667c-11e8-8765-3a04db2cd5bf.png)

Real bounding box from positions:
`(-0.95; -0.81) -> (0.95; 1.00), area: 3.44`

**Deltas (clockwise, starting from the top)**
![image](https://user-images.githubusercontent.com/3479527/40874182-33c9d71c-667d-11e8-818e-1e65527e0a1d.png)

Deltas bounds:
`(-0.59; -0.62) -> (0.59; 0.50)`

**Morphed figure**
![image](https://user-images.githubusercontent.com/3479527/40874158-e2a28c80-667c-11e8-8095-bc8e6c3b0d48.png)

Real bounding box from positions:
`(-0.95; -1.00) -> (0.95; 1.00), area: 3.80`

Computed bounding box from deltas bounds:
`(-1.54; -1.43) -> (1.54; 1.50), area: 9.00`

**Comment by donmccurdy** [comment]
I think I'd still be comfortable using these (oversized) bounds for things like frustum culling or switching LODs; but certainly that's no good for a physics bounding box...

**Comment by emackey** [comment]
Yes, loose bounding volumes are useful in Cesium where the render space is potentially the entire inner Solar System.  Being off by 6 meters isn't a big deal at all.  Being off by 300% isn't ideal, but is better than "infinity" as a bounding volume.

**Comment by donmccurdy** [comment]
I think I’d vote to keep this requirement.
