### ISSUE TITLE
Tighten format for attribute semantic names with indices

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#1360]
The spec says:
> `TEXCOORD`, `COLOR`, `JOINTS`, and `WEIGHTS` attribute semantic property names must be of the form `[semantic]_[set_index]`

> All indices for indexed attribute semantics, must start with 0 and be continuous: `TEXCOORD_0`, `TEXCOORD_1`, etc.

It's still unclear:
* Is using numbers with more than one digit allowed: `TEXCOORD_10`?
* Are leading zeros allowed: `TEXCOORD_02`?

As of now, the validator marks all semantics with more than one digit as invalid.

/cc @emackey @donmccurdy @bghgary

**Comment by donmccurdy** [comment]
+1 for forbidding leading zeros. I would be inclined to allow multi-digit numbers, if we were to set limits they should be based on something other than digits.

**Comment by lexaknyazev** [comment]
Could we formalize the restriction with something like this: `/_([0-9]$|[1-9][0-9]+$)/`?

**Comment by donmccurdy** [comment]
That, or an English equivalent, looks good to me.
