### ISSUE TITLE
Custom semantics in morph targets?

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#1363]
The spec says:
> Application-specific semantics must start with an underscore, e.g., `_TEMPERATURE`.

The spec should be more explicit whether this applies to morph targets (I'd say yes).

/cc @bghgary @donmccurdy @emackey

**Comment by donmccurdy** [comment]
I would say yes as well; that seems to follow from the requirement that morph target names match the vertex attribute semantics. The requirement should require to semantics in general, regardless of their use.

**Comment by lexaknyazev** [comment]
@bghgary @emackey any objections?

**Comment by emackey** [comment]
Agreed with Don.

**Comment by bghgary** [comment]
Sounds right to me.

**Comment by donmccurdy** [comment]
Oh, the spec also states:

> Each target ... is a dictionary mapping a primitive attribute to an accessor containing Morph Target displacement data, currently only three attributes (POSITION, NORMAL, and TANGENT) are supported. 

So, morph targets on COLOR and application-specific semantics would not be allowed without an extension.

**Comment by lexaknyazev** [comment]
It says "supported", not "allowed". As far as I remember, there wasn't any intention to disallow custom attributes in morph targets. Could we check with implementations?

**Comment by donmccurdy** [comment]
Ah, I see. three.js will ignore unknown morph target attributes, but the asset will load fine.

**Comment by donmccurdy** [comment]
Opened #1464.

**Comment by donmccurdy** [comment]
> It says "supported", not "allowed". As far as I remember, there wasn't any intention to disallow custom attributes in morph targets. 

Maybe I'm picking nits here, but how would you define "supported"? If an implementation is allowed but not required to write/read morph targets on application-specific semantics, would an implementation be allowed but not required to write/read morph targets on `COLOR`?

If the meaning was simply that implementations don't _have_ to support `COLOR` I'd implement it in a second. 😇

**Comment by lexaknyazev** [comment]
Morphed `COLOR` is definitely interesting.
Current spec language could be interpreted the same way as the case with having three UVs (which is technically allowed but not widely supported).

**Comment by emackey** [comment]
> currently only three attributes (POSITION, NORMAL, and TANGENT) are supported.

So, "supported" is a reference to existing implementations?  Maybe we could clarify that, something along the lines of:

> Currently only three attributes (POSITION, NORMAL, and TANGENT) are commonly supported, but others such as COLOR and even application-specific semantics that start with an underscore (e.g., _TEMPERATURE) are allowed.
