### ISSUE TITLE
OPENGL Size 3x and 4x 

### ISSUE THREAD

**Issue by pepodmc3** [KhronosGroup/glTF#1371]
It would be great if Kronos support 3x and 4x OpenGL size, so, games like Shining Force would look even better in 3d fights.

At the moment, Kronos only support 2x opengl size and its not enough, 3x and 4x would get better results.

Windows 7

**Comment by emackey** [comment]
I'm going to close this since it doesn't seem related to glTF.  Maybe try asking the question on an OpenGL discussion forum.
