### ISSUE TITLE
Proposal: Unity JsonUtilitity Serialization Option.

### ISSUE THREAD

**Issue by StephenHodgson** [KhronosGroup/glTF#1380]
I'd like to start the discussion about making the Json Serialization options open to developer needs.

Right now the Newtonsoft dll is a hard dependency that every asset package seems to have conflicts with.  I'd like to keep the existing functionality, but add a native Unity Json Serialization option for those that don't want to have Newtonsoft in their projects.

**Comment by lexaknyazev** [comment]
Is it something specific to Unity plugin? If so, https://github.com/KhronosGroup/UnityglTF would probably be a better place for this discussion.

/cc @robertlong @sbtron

**Comment by StephenHodgson** [comment]
Whoops I thought I raised the issue on the UnityglTF repository. My apologies.

**Comment by StephenHodgson** [comment]
Moved to https://github.com/KhronosGroup/UnityGLTF/issues/199
