### ISSUE TITLE
Question regarding spline interpolation

### ISSUE THREAD

**Issue by mseddon** [KhronosGroup/glTF#1382]
I am assuming that `CUBICSPLINE` samplers must accommodate for the fact that t in P(t) is *not* 1:1 with time between keyframes during animation, but the variable `t` could be easily misinterpreted by the naive implementor. We surley must correct for this during playback. Is this correct? If so can I recommend a non normative note about this in the spline interpolation appendix for potential implementors, since to the untrained eye spacing is very tricky and I would hate for developers and animators to clash over this :)

**Comment by bghgary** [comment]
> &nbsp;&nbsp;&nbsp;&nbsp;***p***(*t*) = (2*t*<sup>3</sup> - 3*t*<sup>2</sup> + 1)***p***<sub>0</sub> + (*t<sup>3</sup>* - 2*t*<sup>2</sup> + *t*)***m***<sub>0</sub> + (-2*t*<sup>3</sup> + 3*t*<sup>2</sup>)***p***<sub>1</sub> + (*t*<sup>3</sup> - *t*<sup>2</sup>)***m***<sub>1</sub>
> 
> Where
> 
> &nbsp;&nbsp;&nbsp;&nbsp;*t* is a value between 0 and 1  

*t* is the parameter to the parametric equation. 

> Where at input offset *t*<sub>*current*</sub> with keyframe index *k*
> 
> &nbsp;&nbsp;&nbsp;&nbsp;*t* = (*t*<sub>*current*</sub> - *t*<sub>*k*</sub>) / (*t*<sub>*k*+1</sub> - *t*<sub>*k*</sub>)  

*t*<sub>*current*</sub> is the "time between keyframes" that you mentioned.

Feel free to open a PR adding any wording that clarifies this.

**Comment by mseddon** [comment]
Ah, so the curve parameter *is* time, and we use it directly? In which case that is how I read the spec, I just didn't intuitively believe it to be correct.

My confusion arose from looking at animation curve editors. I was under the impression that we were using the spline directly as a 2d graph, with time on the x axis, value on the y (think animation curve editor). Here, in p(t) -> (x,y), t is not linearly proportional to x, so you would have to resort to something like de casteljau's algorithm to map x -> t, then plug this t into p(t) to get the correct value.

The only difference between this and using the parameter directly is the speed that the object would move along the path, not the path itself, so I'm trying to be very careful to get this right. I assume then that animation tools perform some correction to the spline rendering in the curve editor itself, rather than the curve displayed is the actual curve. Am I understanding correctly? Thanks!
