### ISSUE TITLE
[Clarification] Should I animate nodes that are NOT part of the scene?

### ISSUE THREAD

**Issue by Raveler** [KhronosGroup/glTF#1383]
Hey,

If one of the nodes that is being animated is not directly part of the scene (for example, it may be a node from a skeleton hierarchy that is not contained within the scene itself), should I animate it or not?

For an example, see the attached gltf file. If I load it with ThreeJs, it does not animate, because the skeleton nodes are not part of the scene. But this is not specified in the specs anywhere as far as I can see. What should I do? Animate them or not?

[SimpleSkinNoChildren.txt](https://github.com/KhronosGroup/glTF/files/2175287/SimpleSkinNoChildren.txt)

**Comment by donmccurdy** [comment]
From the spec's discussion of `skin.skeleton` —

> The index of the node used as a skeleton root. When undefined, joints transforms resolve to scene root.

The spec is ambiguous on this — do just transforms resolve to the scene root if the joint isn't in the scene at all? What if `skin.skeleton` is a transformed node, but some of the joints are nowhere in the scene graph, do they resolve to that node or to the scene root? If we remove `skin.skeleton`, do all joint transforms resolve to scene root? 

I can't think of any way to implement joints outside of the scene without appending them to the scene at runtime, so from the perspective of reducing the many edge cases in skinning, it would be nice to tighten this up in some (probably distant) future version...

Also consider:

> For Version 2.0 conformance, the glTF node hierarchy is not a directed acyclic graph (DAG) or scene graph, but a disjoint union of strict trees. That is, no node may be a direct descendant of more than one node. This restriction is meant to simplify implementation and facilitate conformance.

If a joint is referenced _only_ by a skin (it has no parent node), can it be reused in multiple scenes? Or does that imply that it is a child of two scenes, and therefore a descendant of multiple nodes?

**Comment by bghgary** [comment]
> I can't think of any way to implement joints outside of the scene without appending them to the scene at runtime, so from the perspective of reducing the many edge cases in skinning

**Comment by bghgary** [comment]
> I can't think of any way to implement joints outside of the scene without appending them to the scene at runtime, so from the perspective of reducing the many edge cases in skinning

If we end up separating the skeleton from the node hierarchy completely in the future and suppose we did what I said [here](https://github.com/KhronosGroup/glTF/issues/1285#issuecomment-372813534), then I think we explicitly should disallow the joint nodes to be referenced by the scene. If this works out, then I don't see any issue with multiple scenes referencing the same joint nodes.

**Comment by donmccurdy** [comment]
That makes sense, and if we think that's the right direction for the future then certainly it should remain valid now. But it does still leave some things to be defined about resolving joint transformations. Even if we remove `skin.skeleton`, I think this wording from its definition should remain:

> When a joint has no parent, its transform resolves to the scene root.

**Comment by bghgary** [comment]
> this wording from its definition should remain

+1

**Comment by lexaknyazev** [comment]
@bghgary @donmccurdy 
As discussed offline, all joints must belong to the _same_ scene as a skinned mesh. This leaves out one more edge case when a skinned mesh itself doesn't belong to any scene. Should we disallow that as well?

**Comment by lexaknyazev** [comment]
The `skeleton` property should point to the closest common root (that must exist anyway) or to its parent (incl. transitive).
`skeleton` property is not required for rendering or playing an existing animation of a skinned mesh.

**Comment by bghgary** [comment]
> edge case when a skinned mesh itself doesn't belong to any scene

I'm not sure we should disallow this. I can imagine someone wanting to store skinned meshes in a glTF that is used to transmit that data by itself similar to materials or textures that are unreferenced.

**Comment by lexaknyazev** [comment]
OK, so the rule is:
> When a skinned mesh belongs to a scene, all joints used by it must belong to the same scene.

right?

**Comment by lexaknyazev** [comment]
@bghgary @donmccurdy
Can we move forward with the rule proposed above?

**Comment by donmccurdy** [comment]
Assuming I understand correctly, I think `skinned mesh` should say `skin`. A mesh may be stored with skinning-related attributes without being used by a skin. Conceivably that same mesh could be used by two different skins, each skin having different bones. The mesh is valid either way, so the rule should effectively be:

> When a skin is referenced by a scene node, all joints used by the skin must belong to the same scene.
