### ISSUE TITLE
Optical transparency extension

### ISSUE THREAD

**Issue by MiiBond** [KhronosGroup/glTF#1385]
As we know, glTF's PBR model does not include optical transparency and, because of that, common materials such as glass and transparent plastic cannot be represented. I would like to propose a simple extension to handle the majority of cases where assets need optical transparency.

As we all know, transparency is hard. Aside from the render order issues, we also have issues stemming from the thickness (volume) of the material which dramatically affects the visual appearance and complicates the rendering. As such, I'm limiting this extension to "thin" materials. i.e. surfaces.

Aside from that, I'm less concerned about the rendering capabilities of an implementing runtime. No matter how we define this, transparency rendering is going to be different between runtimes. Take, for example, multiple, inter-penetrating transparent objects. Some renderers might use OIT while others, who don't, won't be able to render this correctly.

So, transparent surfaces...

The primary thing that differentiates a transparent surface from an opaque one is the transmission of light through the surface, towards the camera. Some of this light is absorbed (think tinting) and some is scattered. Additionally, the path of the light is bent depending on the refractive index of the material.

### Transmission
Transmission is the percentage of non-reflected light that passes through the surface. e.g. For clear glass, this would be 1.0.
`transmissionFactor` - Scalar
`transmissionTexture` - Texture2D

### Absorption
The surface tints the light coming through it by absorbing light rays and this absorption varies by wavelength. We already know the surface's albedo (baseColor), which describes the percentage of light not absorbed. Therefore, the tinting of the transmitted light can be done by simply multiplying it by the baseColor. No additional property is needed.

### Scattering
The amount of scattering of the surface essentially defines how much the direction of light rays are randomly altered as they pass through. This is primarily affected by the surface roughness so no additional parameter is needed. This affects the blurriness of the transmitted light and is an example of where different runtimes will produce different results, depending on their capabilities. Some might just ignore this effect.
_We could also make this an RGB color to allow for different scattering amounts at different wavelengths. Anyone have use for that?_

### Index of Refraction
This is the ratio of the velocity of light in a vacuum to its speed in this substance. Effectively, it describes the amount that light is bent as it passes from a vacuum into the surface.
`ior` - Scalar
_This is usually given as a single value but could be a 3-vector color if we wanted to support chromatic aberration. Anyone have use for that?_

_All of these values could probably be scaled by some sort of `thickness` parameter._

This is obviously a very simplistic view of transparent objects but I'm trying to hit the most common use cases for optical transparency (glass and plastic).  A future `EXT_materials_volume_transparency` or something could cover more advanced features.

Thoughts?

**Comment by emackey** [comment]
I'm no expert here, just wanted to chime in and mention that Substance Painter can bake a `thickness` texturemap based on high-res geometry.  So if you have a surface that has changing thickness across its area, that can be represented by a texture.

**Comment by MiiBond** [comment]
Oh, interesting. That's definitely something that could be included. Maybe the thickness info is best left for a second, more advanced transparency extension? The advanced extension would also include things like `interiorColor` and would be useful for SSS.

**Comment by MiiBond** [comment]
Do people feel like transparency settings should be broken up into multiple extensions? I'm starting to second guess this. Maybe we *should* include the thickness value along with some diffusion/scattering information. This would make it far harder for runtimes to implement the whole spec, of course. Would we require implementations to support it all or would it be okay if some implementations ignored some of the parameters?

If we add a `thickness` value (where the default would be 1.0):
**Absorption** could be re-expressed in terms of Beer's Law, `exp(-k*d)`, where k is the absorption coefficient (which would be 1.0 - baseColor) and d is the distance travelled (i.e. the thickness).
**Diffusion** (scattering) - I'm not too clear how this could be represented. Can we define this in terms of a density and colour and basically model it as coloured fog?
**Dispersion** - basically separating `ior` for each wavelength, R, G and B. This is important for seeing the chromatic separation in refracted light.

Does anyone have any good reference for physically-based rendering of transparent materials?

**Comment by naikrovek** [comment]
Am I missing something? PbrMetallicRoughness supports the alpha channel of baseColor.

I have many glTF models with transparency.

**Comment by emackey** [comment]
@naikrovek The existing alpha channel system isn't physically-based, and can't handle things like scattering and IoR etc.

**Comment by emackey** [comment]
@pramanc Wow, [Moment-Based OIT](https://cg.ivd.kit.edu/english/mboit.php) looks cool.  Thanks for mentioning that!

**Comment by Ziriax** [comment]
@pramanc @emackey  Actually all the statistical moment approximations are insanely cool, if you have GDC Vault, [this lecture](http://www.gdcvault.com/play/1023864/Rendering-Antialiased-Shadows-with-Moment) about moment shadow mapping is where it all started I guess (University of Bonn, Christoph Peters).

It is being applied now to many things, like [Real-Time Image-Based Lighting of Dynamic Scenes with
Moment Soft Shadow Mapping](http://cg.cs.uni-bonn.de/aigaion2root/attachments/KneiphofCESCG2017.pdf) and others.

It is an extension to good old variance shadow mapping (VSMs).

**Comment by MiiBond** [comment]
Yeah, moment OIT looks awesome.
I was hoping to keep implementation details like this out of the spec. I think the extension should describe the properties of the surface and assume implementations will strive to achieve as close to the "ground truth" (i.e. depth-peeling) as possible. What is going to be possible in WebGL 1.0 is never going to be the same as what an offline renderer can do.

**Comment by MiiBond** [comment]
Just added the first, very rough, spec for this extension. #1468

**Comment by donmccurdy** [comment]
As #1468 has been merged, I think this can be closed. Feel free to re-open if not. Discussion for the core spec ongoing in https://github.com/KhronosGroup/glTF/issues/1442.
