### ISSUE TITLE
Question about cubicspline interpolation and rotations

### ISSUE THREAD

**Issue by clintbrewer** [KhronosGroup/glTF#1386]
Questions around Cubic Spline interpolation for Rotation quaternions

snip---------------------
"
"LINEAR" The animated values are linearly interpolated between keyframes. When targeting a rotation, spherical linear interpolation (slerp) should be used to interpolate quaternions. The number output of elements must equal the number of input elements.
"CUBICSPLINE" The animation's interpolation is computed using a cubic spline with specified tangents. The number of output elements must equal three times the number of input elements. For each input element, the output stores three elements, an in-tangent, a spline vertex, and an out-tangent. There must be at least two keyframes when using this interpolation.
"
snip---------------------

For LINEAR, it is very clear that the spec expects us to use Slerp, and that is working great.

but for CUBICSPLINE it is not completely clear if we should be doing something different for Rotations
" Supported interpolation values include LINEAR, STEP, and CUBICSPLINE. See Appendix C for additional information about spline interpolation."

then Appendix C shows the one equation and mentions
"When the sampler targets a node's rotation property, the resulting p(t) quaternion must be normalized before applying the result to the node's rotation."

Can we clarify that it is intended for Translation, Rotation, and Scale to all use this same equation and not some other Quaternion slerping version?

For instance I work in Unreal which has the templatized  FMath::CubicInterp(     
when input is a quaternion that resolves to: FQuat::Squad
which gives very close but differnet results at the end points, compared to the math in  Appendix C.

The math in Appendix C does work correctly and matches the results I see in Blender, and other viewers, but it would be great to just add a little extra clarity in this section

Thanks!

**Comment by pjcozzi** [comment]
@bghgary? 😄

**Comment by bghgary** [comment]
> Can we clarify that it is intended for Translation, Rotation, and Scale to all use this same equation and not some other Quaternion slerping version?

@clintbrewer Yes, the cubic spline math is intended for quaternion rotations as well. Do you want to open a PR with the wording for this?

**Comment by clintbrewer** [comment]
Thank you for the clarification @bghgary  and @pjcozzi   I can make a suggested wording change PR

**Comment by andreasplesch** [comment]
So the p and m variables of Appendix C can stand for quaternions in addition to vertex positions, right ?

**Comment by bghgary** [comment]
Not vertex positions, no. The terms are confused perhaps.

The spline vertex is can be either a transform position/scale as a Vector3, a transform rotation as a Quaternion, or a morph target weight as a scalar.

See the `channel.path` table in middle of https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#animations

**Comment by andreasplesch** [comment]
Ok. That is very clear.

**Comment by donmccurdy** [comment]
Seems like this has been answered – feel free to reopen if not. :)
