### ISSUE TITLE
extension

### ISSUE THREAD

**Issue by MackeyK24** [KhronosGroup/glTF#1389]
Prefix: CVTOOLS
Vendor: Canvas Tools
Github: https://github.com/MackeyK24/CanvasTools

**Comment by pjcozzi** [comment]
Hi @MackeyK24 - is Canvas Tools a company or a project?  The GitHub page is pretty bare.  Do you have any more info on it and the extensions you are exploring?  Thanks!

**Comment by MackeyK24** [comment]
Canvas Tools is a project, it is going to be my next generation of Unity to WebGL export pipeline

It will be the underlying library of my my new PlayCanvas Exporter and will replace the lib I use in my current Baybylon Toolkit 

Check out https://www.babylontoolkit.com to get idea of what is used to make Pure WebGL games

**Comment by pjcozzi** [comment]
Gotcha, thanks @MackeyK24.  Added in #1393.

Good luck with the project and keep us posted on your progress!
