### ISSUE TITLE
Should a material using KHR_materials_unlit still use emissive?

### ISSUE THREAD

**Issue by gstanlo** [KhronosGroup/glTF#1391]
`When present, the extension indicates that a material should be unlit and use available baseColor values, alpha values, and vertex colors while ignoring all properties of the default PBR model related to lighting or color`

Emissive is not under `pbrMetallicRoughness`. Does this imply that the final color should really be baseColor + emissiveColor?

**Comment by donmccurdy** [comment]
Emissive should be ignored (and occlusion, for that matter). While they're not under `pbrMetallicRoughness` they are meant to be part of the default glTF PBR material. I'd rather list all of the properties unlit materials _do_ use, rather than being exhaustive about what they don't (which may change if new properties are added), so related to https://github.com/KhronosGroup/glTF/issues/1390 perhaps this extension should list out each of the baseColor properties along with alpha-related properties?

**Comment by gstanlo** [comment]
How about the case where you have a material that can fallback to using `pbrMetallicRoughness`? In that case, the emissive should be used and might be providing important detail. When used by a renderer supporting the unlit extension, it would lose that detail if it doesn't use the emissive texture. 

If the emissiveness were baked into the baseColor texture, then it would break the pbrMetallicRoughness fallback renderer. 

Instead if emissiveness is used when using the unlit extension, wouldn't it look correct in both renderers?

**Comment by donmccurdy** [comment]
Our [recommended unlit usage](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_unlit#extension-compatibility-and-fallback-materials) is to set baseColor and omit emissive. This means that in engines that don't support the unlit extension, you will see shading, but we consider that acceptable for a couple of reasons:

(1) While emissive _might_ look correct in both renderers, an emissive material is conceptually not the same thing as a shadeless material, and you may also get unwanted side effects in renderers that treat emissives as light sources
(2) using both baseColor and emissive may give unexpected side effects when the two are added together
(3) unlit materials may use vertex colors, which an emissive fallback currently could not
(4) the unlit extension is simple, and quite likely to be widely supported

**Comment by gstanlo** [comment]
I see, thanks.

**Comment by juj** [comment]
Does there exist a test scene with KHR_materials_unlit + emissive (and KHR_materials_unlit + occlusion)?

The behavior that KHR_materials_unlit materials should ignore emissive is not obvious. I was not able to find a wording/mention in the spec on emissive, or in the KHR_materials_unlit extension about how it is expected to interact with emissive and occlusion - before stumbling to this issue.

It might be a good idea to add an explicit section to KHR_materials_unlit about "KHR_materials_unlit + emissive" and "KHR_materials_unlit + occlusion" to state that the expectation is that emissive and occlusion should be ignored.

**Comment by donmccurdy** [comment]
A quick test scene:

[BoxUnlitEmissive.zip](https://github.com/user-attachments/files/24438357/BoxUnlitEmissive.zip)

Created by dropping a [basic box](https://github.com/KhronosGroup/glTF-Sample-Assets/blob/main/Models/Box/README.md) into https://gltf.report and executing:

```javascript
import { KHRMaterialsUnlit } from '@gltf-transform/extensions';

const unlitExtension = document.createExtension(KHRMaterialsUnlit);
const unlit = unlitExtension.createUnlit();

for (const material of document.getRoot().listMaterials()) {
    material
        .setBaseColorFactor([0.8, 0.0, 0.0, 1.0])
        .setEmissiveFactor([0.0, 1.0, 0.0])
        .setExtension('KHR_materials_unlit', unlit);
}
```

I think I agree that this can/should be more explicitly said in the `KHR_materials_unlit` spec.

**Comment by juj** [comment]
Thanks - added the cube to my test CI.

<img width="1434" height="1071" alt="Image" src="https://github.com/user-attachments/assets/02b0c206-9d9a-48a6-869a-d373218060ac" />

Renders well as red (in my default skybox scene). Looks like it would come out as yellow if emissive incorrectly added to unlit:

<img width="1436" height="1078" alt="Image" src="https://github.com/user-attachments/assets/a26069fc-ad19-42ae-a92a-e8e5afe560a8" />
