### ISSUE TITLE
Add Implementation Note for how shaders can conform to material doubleSided

### ISSUE THREAD

**Issue by ggetz** [KhronosGroup/glTF#1402]
Include an implementation note for how shaders should include normal and tangent-space calculations to conform to the value of a material's `doubleSided` property.

See conversation in KHR_techniques_webgl extension PR for details: https://github.com/KhronosGroup/glTF/pull/1296#discussion_r203444638

**Comment by lexaknyazev** [comment]
Addressed in the current version of the spec.
