### ISSUE TITLE
STEP interpolation, first interval

### ISSUE THREAD

**Issue by andreasplesch** [KhronosGroup/glTF#1409]
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#animation-samplerinterpolation
says:
```
"STEP" The animated values remain constant to the output of the first keyframe, until the next keyframe. The number of output elements must equal the number of input elements.
```
key frames as keys and output:
```
start - - | - - | - - | -
out   x x 6 x x 8 x x 9 x
```
Start is t=0. The vertical bars are key frames. The first key frame has an output value of 6. x are the values which I want to get right.

Clamping before the first key frame means
```
start - - | - - | - - | -
out   6 6 6 x x 8 x x 9 x
```
This is also consistent with what the STEP interpolation language says.

The 'next key frame' is the second one, so 'until' should mean continuing like this:

```
start - - | - - | - - | -
out   6 6 6 6 6 8 x x 9 x
```

Is continuing without a change after the first key frame the intended meaning ? It probably is.

The alternative is to use 8 for the interval between key frames one and two.

Then the value steps:

```
start - - | - - | - - | -
out   6 6 6 6 6 8 8 8 9 x
```

and then again, also clamping after the last key frame

```
start - - | - - | - - | -
out   6 6 6 6 6 8 8 8 9 9
```

Does that look correct ?

**Comment by javagl** [comment]
As for the second part: That's how I'd interpret it.

The question about whether the value of the first key frame is "extended forward" (before the *time* of the keyframe) is actually discussed in https://github.com/KhronosGroup/glTF/issues/1327 , regardless of the interpolation scheme.

**Comment by andreasplesch** [comment]
Let me close since there is not much uncertainty. Please feel free to reopen if there is more discussion to have, eg. the interpretation is incorrect.
