### ISSUE TITLE
Should animations be applied on top of local transforms, summed with or replace them?

### ISSUE THREAD

**Issue by moll** [KhronosGroup/glTF#1425]
Hey,

The spec on animations is a little light on how local transforms (existing TRS props on a node) interact with animations. I wasn't able to find an answer in other issues/questions here either, apart from https://github.com/KhronosGroup/glTF/issues/1368 whose interpretation I'm not yet convinced by. Thought I'd bring it up in hopes the spec will eventually perhaps get a concrete example or two about this as well.

So, given a node with a local translation property that gets rotated through an animation, is that translation applied after the rotation or before it (so the translation also gets rotated)? Should there be a local rotation property on the node, too, would the final rotation be their sum instead (product of two quaternions)?

Because the `matrix` property is disallowed when animating, I'm leaning towards interpreting it as animations _replace_ only those local properties they clash with and the final local transformation would be a single combined matrix of untouched local and replaced properties created in the [reverse] order of T * R * S. Otherwise why disallow `matrix` if one could just multiply the resulting matrix from the animation with the local one, right.

Thanks!

**Comment by moll** [comment]
As I was creating this issue, @zellski gave his clarification in https://github.com/KhronosGroup/glTF/issues/1368#issuecomment-414072825 that's in line with my interpretation above. However, that raises another question --- what happens if two animation channels refer to the same node with the same path (animating the same property)? I don't think I've seen a warning that this mustn't happen in the spec so far, so...

**Comment by scurest** [comment]
It's addressed in the [property reference for `animation`](file:///home/bryce/glTF_README.md%20at%20master%20%C2%B7%20KhronosGroup_glTF.html#reference-animation). The description for `channels` is

> An array of channels, each of which targets an animation's sampler at a node's property. **Different channels of the same animation can't have equal targets.**

(Presumably `target`s are equal when their `node` and `path` properties are equal.)

**Comment by scurest** [comment]
It's addressed in the [property reference for `animation`](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#reference-animation). The description for `channels` is

> An array of channels, each of which targets an animation's sampler at a node's property. **Different channels of the same animation can't have equal targets.**

(Presumably `target`s are equal when their `node` and `path` properties are equal.)

**Comment by zellski** [comment]
It does seem like some version of '**Different channels of the same animation can't have equal targets.**' could be meaningfully repeated in the main body, or illustrated with a small example. I bet a PR would be welcome!

**Comment by bghgary** [comment]
The asset generator project also has a test for overriding the local transform from an animation. Test 05 from https://github.com/KhronosGroup/glTF-Asset-Generator/blob/master/Output/Animation_NodeMisc/README.md

**Comment by donmccurdy** [comment]
Seems like this is answered, but if someone wants to suggest an additional note in the spec please feel free.

**Comment by moll** [comment]
Ah, I think I forgot to close it myself. :innocent: Thanks, others, for the answers above, too!
