### ISSUE TITLE
Should Occlusion apply to IBL and lights or just IBL?

### ISSUE THREAD

**Issue by sbtron** [KhronosGroup/glTF#1427]
Some background discussion here - https://github.com/BabylonJS/Exporters/issues/291

Should occlusion affect IBL and lights both or just IBL?
Currently Babylon was applying to occlusion to both (with an option to just do it for IBL) but other packages might just be doing it for IBL.  The core spec doesn't specify anything on this but as lights and environment extensions come along we do need to specify what the expected behavior is. 
 
Curious to know what other packages are doing and if there is a standard practice around this already?

//cc @echadwick-wayfair @sebavan

**Comment by echadwick-wayfair** [comment]
Ambient occlusion is meant to occlude only indirect lighting (ambient), not direct lighting (light sources). 

Direct lighting is light emitted from a strong light source, and striking our model's surface directly, with nothing occluding the light (or very little occlusion, for example our atmosphere somewhat attenuates the direct lighting from the sun, but it's still pretty bright). Direct light examples are the sun, a light bulb, a car headlight, etc.

Indirect lighting occurs when direct lighting bounces off surfaces and illuminates our model's surface. These are secondary, tertiary, etc. light bounces. This is also called ambient lighting. 

Ambient occlusion mimics the way a model's crevices reduce the effect of secondary bounces (as the lighting bounces more and more across the creases of a surface, more of the energy is absorbed).

Some early research might help illuminate this (sorry!) 
https://link.springer.com/chapter/10.1007/978-3-7091-6453-2_5

**Comment by echadwick-wayfair** [comment]
But... if the IBL contains imagery of light sources and these are stored in HDR, then the IBL is basically casting direct lighting. Over-bright pixels are casting sun-like lighting into our scene.

So having it as an option seems like it might make the most sense?

**Comment by emackey** [comment]
Our current reference PBR shader [applies the ambient occlusion to both analytic lights and IBL](https://github.com/KhronosGroup/glTF-WebGL-PBR/blob/88eda8c5358efe03128b72b6c5f5f6e5b6d023e1/shaders/pbr-frag.glsl#L297-L298).  This is helpful for engines where self-shadowing is not enabled, as ambient occlusion becomes a form of self-shadowing.

**Comment by echadwick-wayfair** [comment]
Hmm. that could certainly be an option for those who want it. But I believe it shouldn't be the default. 

If there is no self-shadowing then it may look better at first glance. However it's not physically correct, and ends up making the model look "dirty" as if the crevices are filled with light-absorbing black dust.

**Comment by donmccurdy** [comment]
FYI, further discussion in https://github.com/KhronosGroup/glTF/issues/915.

**Comment by emackey** [comment]
Closing this in favor of #915.

I think it's well established at this point that occlusion only affects indirect (IBL) sources, not punctual lights.  I'll leave #915 open in case any wording still needs to be updated.
