### ISSUE TITLE
material.normalTexture should link to material.normalTextureInfo

### ISSUE THREAD

**Issue by andreasplesch** [KhronosGroup/glTF#1430]
In the de facto specification document, the normalTexture material property of type object here

https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#reference-material

should link and refer to the material.normalTextureInfo object definition here:

https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#reference-normaltextureinfo

just like the json schema does. Otherwise, the type of object remains undefined, eg. it is necessary to look up the json schema.

Suggestions:

Replace

`A tangent space normal map.`

with

`A tangent space normal map object of type normalTextureInfo.`

and link normalTextureInfo and perhaps `object` below.

**Comment by bghgary** [comment]
This is a dupe of #1013. The fix from @javagl addressed this specific issue.

**Comment by andreasplesch** [comment]
OK, this is recognized and fixed in @javagl 's fork. Perhaps the fix will find its way here as well.
