### ISSUE TITLE
Blending in glTF 

### ISSUE THREAD

**Issue by Morozoov8** [KhronosGroup/glTF#1434]
Hello! I have some question about blending in  OSG.JS glTF loader. I write osg loader and use this [](https://github.com/jesesun/osgdb_gltf) for base. 
		In OSG.JS blendFunction is uses: 
`this._defaultBlendFunc = new BlendFunc();
   this._transparentBlendFunc = new BlendFunc('SRC_ALPHA', 'ONE_MINUS_SRC_ALPHA');`
   
		[](https://github.com/cedricpinson/osgjs/blob/master/sources/osgPlugins/ReaderWriterGLTF.js
I made the same but nothing happened. I can't see windows or brakeLights in model ZIS-101-3. For blending I get alpha-channel from baseColor value, in model zis-101 alpha-channel is zero. Is it normal? 
What blending in osg.js need except blendFunction?
		https://sketchfab.com/models/a361c0f7b7e041fc8f3437a5cbec681a

**Comment by donmccurdy** [comment]
I think you may have better luck with this question over on the osg.js repository issues — this repo covers the specification of the glTF format, but we're not involved with the OSG.js loader and aren't familiar with its implementation or use. Most likely, models loaded with OSG are treated the same once they're loaded, regardless of what format they originally were. 

https://github.com/cedricpinson/osgjs
