### ISSUE TITLE
Blending in glTF

### ISSUE THREAD

**Issue by Morozoov8** [KhronosGroup/glTF#1436]
I have misunderstanding about blending in glTF specification:
 
>  "BLEND" The alpha value is used to composite the source and destination areas. 
>  The rendered output is combined with the background using the normal painting operation (i.e. the Porter and Duff over operator).

Should I use only alpha-channel in materials or someting else? 
For example I found two different models on sketchfab.
Hebie:
[https://sketchfab.com/models/beac1b607f2544708891b2491886e87f](url)
ZIS-101:
[https://sketchfab.com/models/a361c0f7b7e041fc8f3437a5cbec681a](url)
 Herbie in glass materials has not zero alpha channel:

>   "name": "Windows",
>       "pbrMetallicRoughness": {
>         "baseColorFactor": [
>           0,
>           0,
>           0,
>           0.68999999999999995

 In the same time model ZIS-101 contain zero in alpha channel in all glass materials.
 So first question is next how I should to understand BLEND material?
 
 Next question about realization blending. Does blend function work after fragment shader or maybe in shader?

**Comment by emackey** [comment]
The [AlphaBlendModeTest](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AlphaBlendModeTest) sample model demonstrates the blend modes that are currently available in glTF.

There is a [gltf-test project](https://github.com/cx20/gltf-test/#feature-test-models) that tests how this model and others behave in various WebGL-based engines.
