### ISSUE TITLE
Animation: quaternion vs. axis-angle

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#144]
I assume this was discussed at length, and, if so, we can just move on; I don't want to slow us down.

Both my implementation and @tparisi's use quaternions for rotation, which means that we have to convert the glTF axis-angle representation to a quaternion.  I suspect that most non-trivial implementations will also quaternions, and it's no problem for the converter to output these.

So why did we go with axis-angle?  To lower the barrier to entry?  Would using quaternions plus having some quaternion-to-rotation-matrix and quaternion-interpolation examples be more in tune with the glTF vision - "avoid client-side work?"

**Comment by pjcozzi** [comment]
Given that we haven't tested this in our engines and time is tight, I suggest we do not include this in the draft 1.0 spec.

**Comment by pjcozzi** [comment]
Any thoughts on pushing this post 1.0?

**Comment by tparisi** [comment]
It's easy enough implement and pretty common. I think we should consider
keeping this for 1.0

On Tue, Sep 1, 2015 at 6:09 AM, Patrick Cozzi <notifications@github.com>
wrote:

> Any thoughts on pushing this post 1.0?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KhronosGroup/glTF/issues/144#issuecomment-136713934>.
>



-- 


Tony Parisi                             tparisi@gmail.com
Founder, Third Eye                http://www.thirdeye.gl/
Follow me on Twitter!             http://twitter.com/auradeluxe
Read my blog at                     http://www.tonyparisi.com/
Learn WebGL                         http://learningwebgl.com/
Mobile                                    415.902.8002
Skype                                     auradeluxe

Read my books!
*Learning Virtual Reality*
http://www.amazon.com/Learning-Virtual-Reality-Experiences-Applications/dp/1491922834


*Programming 3D Applications in HTML5 and
WebGLhttp://www.amazon.com/Programming-Applications-HTML5-WebGL-Visualization/dp/1449362966
<http://www.amazon.com/Programming-Applications-HTML5-WebGL-Visualization/dp/1449362966>WebGL,
Up and Running*
http://www.amazon.com/dp/144932357X

**Comment by pjcozzi** [comment]
Will you be able to test the converter and a client-side implementation in time for 1.0?

If not, we _could_ consider pushing 1.0 or target it for 1.0.1 or an extension.

**Comment by tfili** [comment]
Have we decided what we are going to do here?

**Comment by tparisi** [comment]
Let's stick with axis angle for now... easy to add a `quaternion` property post 1.0 in a backward-compatible way.

**Comment by tparisi** [comment]
@pjcozzi close or leave open?

**Comment by pjcozzi** [comment]
> Let's stick with axis angle for now... easy to add a quaternion property post 1.0 in a backward-compatible way.

This is OK-ish, but then we are requiring implementations to convert to quaternion for animation so they can use SLERP (#156).  Why not store quaternion initially as I originally said:

> Both my implementation and @tparisi's use quaternions for rotation, which means that we have to convert the glTF axis-angle representation to a quaternion. I suspect that most non-trivial implementations will also quaternions, and it's no problem for the converter to output these.

> So why did we go with axis-angle? To lower the barrier to entry? Would using quaternions plus having some quaternion-to-rotation-matrix and quaternion-interpolation examples be more in tune with the glTF vision - "avoid client-side work?"

@tfili @tparisi is this not feasible given our timeline?  If so, why exactly is hard about it?

**Comment by tparisi** [comment]
@pjcozzi it's super-easy. my importer is already converting from axis-angle so why bother?

So do you want to just define `rotation`  as a quaternion instead? or have a separate `quaternion` property?

I'm good with either. 

So, I changed my mind: now that we're changing the converter and loaders for 1.0 anyway, we might as well get this right.

**Comment by pjcozzi** [comment]
> So do you want to just define rotation as a quaternion instead?

Yes, I think this is all that is needed for the schema change.

**Comment by tparisi** [comment]
then let's do it

**Comment by tfili** [comment]
Looking at some of Fabrice's changes on dev-0.9 that had quaternion changes in it, he was exporting the quaternion as `[x,y,z,w]`. Looking around it looks like most graphics related things (as well as OpenCOLLADA) represent them as `[w, x, y, z]`. I think we should probably have the scalar part first like most other things. Is that ok with everyone?

**Comment by tfili** [comment]
Also, we want to mention that quaternions should be unit length.

**Comment by pjcozzi** [comment]
Three popular WebGL engines have `w` first:

* http://threejs.org/docs/#Reference/Math/Quaternion
* https://github.com/BabylonJS/Babylon.js/wiki/How-to-handle-rotations-and-translations
* https://cesiumjs.org/Cesium/Build/Documentation/Quaternion.html

**Comment by pjcozzi** [comment]
Sorry, I mean they have `w` last.

**Comment by tparisi** [comment]
Oh x,y,z,w in that order please!

**Comment by tfili** [comment]
Ok. I'll change it to that.

**Comment by pjcozzi** [comment]
I agree with `w` being last.  I did some more research and asked some folks and, for example, Unity and Unreal have w last.

Please check these off when they are done:

TODO
* [ ] @tfili - update converter
* [ ] @tparisi - update spec
* [ ] @pjcozzi - update schema

**Comment by pjcozzi** [comment]
@tparisi please close this when you update the spec.  Thanks again for the code change, @tfili!

**Comment by tfili** [comment]
dev-1.0 updated at bb391e0ce45698c687fb1891034a9cd16f4e74fb

**Comment by pjcozzi** [comment]
@tparisi once you update the spec we can close this.

**Comment by tparisi** [comment]
there's actually no language either way about quaternion vs. axis angle. I will add quaternion language. Can you give ma

**Comment by tparisi** [comment]
@pjcozzi I added language please review.

**Comment by pjcozzi** [comment]
Looks good.  I made the unit quaternion explicit in 38dc6e8d8e9b8d9ce5f8f4b084f2101ea71826d3.

**Comment by pjcozzi** [comment]
Also mentioned `w` is last: f3be7fb222624ba6a430964a0184206e21814094
