### ISSUE TITLE
Whitespace in URIs

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF#1449]
We know from [the spec's comments on URIs](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#uris) that reserved characters must be percent-encoded.

Do spaces always need to be encoded too, or are they ever allowed to appear in a glTF URI without encoding?

/cc https://github.com/KhronosGroup/UnityGLTF/issues/241

**Comment by lexaknyazev** [comment]
RFC3986 is a bit vague about the necessity of encoding:
> These characters are called "reserved" because they may (or may not) be defined as delimiters by the generic syntax, by each scheme-specific syntax, or by the implementation-specific syntax of a URI's dereferencing algorithm. If data for a URI component would conflict with a reserved character's purpose as a delimiter, then the conflicting data must be percent-encoded before the URI is formed.

For example, when a filename containing space character (0x20) is used in a HTTP request, it must be percent-encoded to conform to HTTP request line syntax. On the other hand, while using the same filename with local filesystem, such encoding is not needed.

I think, that "reserved" chars should be percent-encoded within glTF only in cases when there's some ambiguity with using them in different contexts. For example: `"uri":"data?low"` vs `"uri":"data%3Flow"`.

**Comment by donmccurdy** [comment]
It wasn't immediately obvious to me what "and decode" or "accept both forms" should mean, so I tried writing out what I think that would look like:

| case | context | result |
|--|--|--|
| `data?low` | HTTP | Make request with string as-is, resolving to path `data` with fragment `?low` |
| `data%3Flow` | HTTP | Make request with string as-is, resolving to path `data?low` |
| `data?low` | disk | Parse URI, decode, read file named `data` |
| `data%3Flow` | disk | Parse URI, decode, read file named `data?low` |
| `data low` | HTTP | Make request with string as-is, resolving to path `data low` |
| `data%20low` | HTTP | Make request with string as-is, resolving to path `data low` |
| `data low` | disk | Parse URI, decode, read file named `data low` |
| `data%20low` | disk | Parse URI, decode, read file named `data low` |

It's worth noting a few things here:

(1) A file path is not necessarily a URI.
(2) Clients cannot safely decode percent-encoded characters without first parsing the URI to its components.
(3) A URI cannot be used as a filepath without first parsing the URI to its components. For example, JavaScript's `decodeURI` is insufficient to resolve a file path.

If clients will use the URI as an HTTP URL, or any other context where valid URIs are expected, no parsing or decoding should be needed — it is up to the recipient of the HTTP request to resolve the resource correctly. If clients will use the URI as something else, like a file path, they must parse and decode the URI first. If the client does that, I believe they'll end up supporting both encoded and unencoded spaces  (or other non-reserved characters), by default.

**Comment by lexaknyazev** [comment]
A few nits (just for accuracy):
- `?low` is a query, not a fragment;
- `data low` with HTTP will be automatically rewritten to `data%20low` before transmission by user-agent.

I'd say that clients should always treat references as URIs, i.e., parse & decode - not just copy-paste.

**Comment by donmccurdy** [comment]
> I'd say that clients should always treat references as URIs, i.e., parse & decode - not just copy-paste.

I think we're on the same page here, but would not phrase this as "should always ... parse and decode" because some clients (e.g. web) can simply use the URI as a URI. Decoding is necessary only to resolve the resource through an interface that doesn't understand URIs.

**Comment by emackey** [comment]
Per offline discussion, spaces can be either encoded or unencoded inside glTF URI strings.  We don't think the spec needs an update, but we do need some sample models to test viewer conformance with percent-encoded characters.  @bghgary has linked an issue above to the Asset Generator to create these samples.

**Comment by vpenades** [comment]
Following the discussion in [Slack](https://khronosdevs.slack.com/archives/CDRQGHM3J/p1586366289067700?thread_ts=1586342278.067400&cid=CDRQGHM3J), I've been having issues with escaped URIs.... 

I'm mostly interested on file system resolution; I would like to know which options are valid, and which should give validation errors.

My current strategy is to try the with the URI string "as is", and if it fails, try to decode, or decode the string and try again:

| Literal  |Json URI|Texture system name| Outcome|
|-|-|-|-|
|0|texture.png|texture.png| ✔️  |
|1|texture 1.png|texture 1.png| ✔️  |
|2|texture%201.png|texture 1.png|🔴 `texture%201.png` not found <br>✔️ After Decoding URI|
|3|texture 1.png|texture%201.png|🔴 `texture 1.png` not found <br>✔️ After Encoding URI|
|4|texture%201.png|texture%201.png| ✔️  |

If the URI is escaped by default, and just one load attempt is done, I believe this would be the outcome:

| Always<br>Decode|Json URI|Texture system name| Outcome|
|-|-|-|-|
|0|texture.png|texture.png|✔️ |
|1|texture 1.png|texture 1.png|✔️ |
|2|texture%201.png|texture 1.png|✔️ |
|3|texture 1.png|texture%201.png| 🔴 `texture 1.png` not found |
|4|texture%201.png|texture%201.png|🔴 `texture 1.png` not found |

Right now, I've found use case 2 with gltf models being exported by the Blender plugin. This particular case can be fixed if I always decode the URI... but then, use cases 3 and 4 will fail. In particular, I am not sure if case 4 always failing would be the right thing...

**Comment by bghgary** [comment]
URI should always be decoded before using it in a file path. I would not expect case 3 and 4 of the second table to work. Case 1 of the second table happens to work by cirmumstance. It's technically not a correct URI but it will likely work in some (many?) software.
