### ISSUE TITLE
Skinning: Can a node be in multiple skins?

### ISSUE THREAD

**Issue by julienduroure** [KhronosGroup/glTF#1454]
Can a node be in multiple skins?

For example : 

{
skins: [
{"inverseBindMatrices":0,"joints": [1,2,3,4]},
{"inverseBindMatrices":1,"joints": [2,3,6]},
]
}

**Comment by julienduroure** [comment]
Seems to be the case in this file:
https://github.com/julienduroure/gltf2-blender-importer/files/2293274/VRoidTwo.gltf.zip
And I want to know how to handle it

**Comment by donmccurdy** [comment]
/cc https://github.com/KhronosGroup/glTF/issues/1403.

The spec does not prohibit this, to my understanding. Whether it is supported consistently is another question. For most of the edge cases in #1403, I think we would like to collect examples,  compare handling in existing implementations, document the cases, and (if necessary) tighten the spec in the future.

**Comment by Selmar** [comment]
This is in my experience a very common use case. In reality, those nodes are simply part of the same skeleton (which is not explicitly referenced). 

As an example, in 3ds Max, several skinned meshes may use the same nodes as joints. The Babylon exporter currently exports all skins separately, sometimes even duplicating the exact same joints list.

Note that different skins may in theory have different inverse bind matrices for the same joints (although I feel this is perhaps more an indication of a problem than a feature).

I don't know what you mean by "how to handle it", this seems like a very implementation-dependent question? What is your problem with it?

**Comment by Ziriax** [comment]
The inverse bind matrix is the coordinate system of the mesh as seen from the joint. So if you have two meshes at different positions in the world that you bind to the same joint, the joint will have two different inverse bind matrices. So that is perfectly valid imo. For example, the head of a character can be detached from the body, but both head and body share the same joints.

**Comment by Selmar** [comment]
@Ziriax Thanks, it seems I didn't understand this properly. (I completely ignore the inverse bind matrices in our implementation..)

However, does that also mean a skin object can actually not be shared between differently positioned meshes, as the inverse bind matrices are per-skin and not per-mesh? If so, what is then the point of having a separate `skin` object?

**Comment by donmccurdy** [comment]
@julienduroure is it plausible to duplicate the skin at import, if you run into this? This case is currently considered valid, and works in tests on several engines, but feedback from the DCC tool perspective is also helpful.

/cc @bghgary

**Comment by donmccurdy** [comment]
Example: https://bghgary.github.io/glTF-Assets-Viewer/?manifest=https://raw.githubusercontent.com/KhronosGroup/glTF-Asset-Generator/v0.6.0/Output/Manifest.json&folder=2&model=8

**Comment by donmccurdy** [comment]
The example above works correctly, and the spec allows it, so I think we can say this is valid.

**Comment by donmccurdy** [comment]
> However, does that also mean a skin object can actually not be shared between differently positioned meshes, as the inverse bind matrices are per-skin and not per-mesh? If so, what is then the point of having a separate skin object?

The separate skin object allows you to specify a separate `inverseBindMatrices` entry, if needed. If multiple meshes can share the same joints and the same `inverseBindMatrices`, then they can also share a single skin. In either case, the joint hierarchy does not need to be duplicated.

**Comment by Selmar** [comment]
@donmccurdy Reading it back now it all makes sense, thanks.
