### ISSUE TITLE
Alpha coverage is underspecified

### ISSUE THREAD

**Issue by romainguy** [KhronosGroup/glTF#1457]
The [glTF 2.0 specification](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0) is very vague on how alpha coverage should be supported. I do agree with what this phrase from the spec:
> There is no perfect and fast solution that works for all cases. 

I however believe that the spec could be more opinionated here. Here are several issues that could (and should IMO) be addressed by the spec:

- There is no mention of premultiplied alpha vs non-premultiplied alpha (it's kind of implied by the mention of Porter-Duff SourceOver blending mode for the `BLEND` case, but it should be more explicitly described).
- There is no mention of whether opacity is applied to specular lighting. In `BLEND` mode I think this should be explicitly disallowed.
- If opacity doesn't affect specular lighting, a new alpha coverage mode ('FADE') should probably be added to have this capability. This can be useful for specific effects like fading an object in & out.

**Comment by MiiBond** [comment]
I believe that the term "alpha coverage" implies a simple over operator so lighting is not considered. i.e. it should currently work as a fade. This is why, I'd like an extension for simple optical transparency. See #1385 
I agree that the spec should be more explicit about this though. I know the implementation in Babylon already doesn't treat this as pure alpha coverage (though, they've added an option to).

**Comment by emackey** [comment]
Some additional comments on blending modes are in #1033 and #822.

**Comment by emackey** [comment]
Specifically, `BLEND` mode is only for coverage, not transparency or translucency:

> Use this mode for materials that simulate geometry such as gauze cloth or animal fur.

A gauze cloth with near-zero coverage would not have much if any specular reflection.

Proper support for transparency/translucency is being discussed in #1385, and generally the future of glTF materials is being brainstormed in #1442.

**Comment by donmccurdy** [comment]
Some of this (premultiplied alpha, FADE mode) could perhaps be covered more explicitly in a possible [KHR_blend extension](https://github.com/KhronosGroup/glTF/pull/1302).

**Comment by donmccurdy** [comment]
> There is no mention of premultiplied alpha vs non-premultiplied alpha

The spec does say, `The stored texels [of baseColorTexture] must not be premultiplied`. I'm not sure if I missed that before or if the clarification was added.

**Comment by romainguy** [comment]
I don't remember seeing it before either. And does it mean the texture is not store premultiplied or that you should not alpha multiply the RGB channels during shading? And if so, why?

**Comment by lexaknyazev** [comment]
> The stored texels **MUST NOT** be premultiplied.

This sentence in the spec refers to the state in which the data is stored. I don't think that multiplication during shading is generally called "premultiplication".

Feel free to reopen if there are more clarifications needed.
