### ISSUE TITLE
Clarify zero-length tangent vectors

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#1461]
This issue has been brought up several times in different glTF tools repos. In some cases, exporters write tangent vector as zero. 

We need the spec to clarify whether it's allowed and to provide some implementation guidelines for better ecosystem consistency.

**Comment by emackey** [comment]
Also zero-length normal vectors.  The Blender exporter writes zero-length normals for degenerate triangles.

**Comment by donmccurdy** [comment]
I'm OK with disallowing zero-length tangents as well.

**Comment by gleblebedev** [comment]
Not unit size normal vectors could be used to store ambient occlusion information. A normal with a zero length indicates that vertex should not be lit by a light source.

**Comment by emackey** [comment]
@gleblebedev For an individual game engine, tricks like that can be quite useful, but in glTF the goals include broad compatibility across a wide range of platforms and engines.  The spec already states that normals must be "normalized" (meaning unit-length), and I think it's just an oversight that tangents were not already specified that way as well.  Various open-source implementations and sample viewers for glTF will automatically normalize both these vectors to protect against invalid data.

Degenerate geometry should not be included in a glTF.  Unlit geometry should be tagged with the [KHR_materials_unlit](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_unlit) extension.  Ambient occlusion has a texture channel allocated when needed.
