### ISSUE TITLE
Packing of tangents for cubic spline morph weight curves

### ISSUE THREAD

**Issue by scurest** [KhronosGroup/glTF#1462]
Is the output accessor for a sampler with CUBICSPLINE interpolation that is used by a channel with target `weights` packed as `aaaavvvvbbb` or `avbavbavbavb`?

The docs for `interpolation` say

> **CUBICSPLINE** The animation's interpolation is computed using a cubic spline with specified tangents. The number of output elements must equal three times the number of input elements. For each input element, the output stores three elements, an in-tangent, a spline vertex, and an out-tangent. There must be at least two keyframes when using this interpolation.

This is slightly confusing since for weights curves there are going to be 3k, not 3, elements, where k is the number of morph targets. But reading the other interpolation docs suggest that "output element" means a sequence of k scalars in this case. So do I read this correctly as meaning it should be `aaaavvvvbbbb`?

**Comment by donmccurdy** [comment]
It should be `aaaavvvvbbbb`, see https://github.com/KhronosGroup/glTF/issues/1344 for details. We discussed this but still need to clarify in the spec.

**Comment by donmccurdy** [comment]
Closing to merge with #1344.
