### ISSUE TITLE
Is there a way to apply bump map?

### ISSUE THREAD

**Issue by Ma-Kn** [KhronosGroup/glTF#1469]
I am making a program to convert my model to GLTF.

but, GLTF does not have parameters for bump maps.
I looked at other converters and applied the bump map to the normal map.
Is this the right way?
Is there a difference in appearance when bump map is applied to normal map
I am concerned.

**Comment by donmccurdy** [comment]
You'll need to convert classic bump maps into normal maps. Just using the bump map as a normal map will give the wrong result, but some exporters should be able to do this for you. For example in Blender: https://blender.stackexchange.com/questions/56638/how-to-generate-a-normal-map-from-a-bump-map
