### ISSUE TITLE
Adobe Dimension glTF models

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF#1484]
Here's a test model that a coworker of mine exported from Adobe Dimension: [AGI_Coffee_Cup.zip](https://github.com/KhronosGroup/glTF/files/2578436/AGI_Coffee_Cup.zip)

This model uses Draco compression, and has two primitives (a cup and a lid).  There seem to be some "dummy" accessors at the top though, that contain a degenerate triangle at the origin, with zero size:

```
  "accessors": [
    {
      "bufferView": 0,
      "componentType": 5126,
      "count": 3,
      "type": "VEC3",
      "max": [
        0,
        0,
        0
      ],
      "min": [
        0,
        0,
        0
      ]
    },
```

This renders fine in Babylon, but breaks in Cesium.  Cesium trusts the accessor min/max values, which are all zeros, and computes a zero-radius bounding sphere, and then decides that the primitives never need to render based on that radius.

Is this a proper use of Draco?  Our official samples do something different with the accessors, and avoid the need for this dummy degenerate triangle outside of the Draco stream.  Is it OK for engines to rely on the accessor min/max information in Draco compressed models?

/cc @MiiBond @lexaknyazev @FrankGalligan

**Comment by donmccurdy** [comment]
Related: https://github.com/KhronosGroup/glTF/issues/1267#issuecomment-436316902

**Comment by MiiBond** [comment]
Yes, this is known. I misread the spec and never noticed the mistake because the user can only get Draco compression when they use our "publish" feature. This takes the user to the Babylon viewer which displays the model correctly. We don't yet provide a download link for the glTF.

I have a fix for this now so it'll be in the next prerelease of Dimension. www.adobeprerelease.com

Thanks.

**Comment by emackey** [comment]
Awesome, thanks!  Closing this to merge with issue #1267.

**Comment by bghgary** [comment]
Just for context, Babylon calculates the bounds instead of using the min/max. There is a [backlog item](https://github.com/BabylonJS/Babylon.js/issues/4102) to use the min/max instead.
