### ISSUE TITLE
collada2GLTF LineSegments issue

### ISSUE THREAD

**Issue by ua4192** [KhronosGroup/glTF#1487]
Hello.

I have tried with all releases of collada2gltf and in all them I am facing the same issue.

I have downloaded and tested all releases from:
 https://github.com/KhronosGroup/COLLADA2GLTF/releases

When you try to convert a collada file which contains LineSegments elements inside, the convertor fails and doesn't generate the GLB or GLTF file.

Tested versions:
https://github.com/KhronosGroup/COLLADA2GLTF/releases/download/v2.1.4/COLLADA2GLTF-v2.1.4-windows-Release-x64.zip
https://github.com/KhronosGroup/COLLADA2GLTF/releases/download/v2.1.3/COLLADA2GLTF-v2.1.3-windows-Release-x64.zip
https://github.com/KhronosGroup/COLLADA2GLTF/releases/download/dependencies/COLLADA2GLTF-dependencies-windows-Release-x64.zip
https://github.com/KhronosGroup/COLLADA2GLTF/releases/download/v2.1.2/COLLADA2GLTF-v2.1.2-windows-Release-x64.zip
https://github.com/KhronosGroup/COLLADA2GLTF/releases/download/v2.1.1/COLLADA2GLTF-v2.1.1-windows-Release-x64.zip
https://github.com/KhronosGroup/COLLADA2GLTF/releases/download/v2.1.0/COLLADA2GLTF-v2.1.0-windows-Release-x64.zip
https://github.com/KhronosGroup/COLLADA2GLTF/releases/download/v2.0.0/COLLADA2GLTF-v2.0.0-windows-Release-x64.zip

Is there any fix available for this?

Best regards

**Comment by donmccurdy** [comment]
I think you'll probably want to file this issue on the COLLADA2GLTF repository: https://github.com/KhronosGroup/COLLADA2GLTF

**Comment by emackey** [comment]
Migrated to https://github.com/KhronosGroup/COLLADA2GLTF/issues/216
