### ISSUE TITLE
Extensions design inconsistencies

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#1491]
Different extensions have different assumptions regarding their further extensibility. We need to provide some guidelines and optionally align existing schema files.

**EDIT:** table updated to reflect merged PRs.

| Object | Additional properties | `extras`/`extensions` | `name` |
|-------------------------------------------------------------------|-----------------------|-----------------------|---------|
| `KHR_draco_mesh_compression` | No | No | No |
| `KHR_lights_punctual` root | ✔️ | ✔️ | No |
| `KHR_lights_punctual` `light` | ✔️ | ✔️ | ✔️ |
| `KHR_lights_punctual` `light/spot` | ✔️ | ✔️ | No |
| `KHR_lights_punctual` `node` | ✔️ | ✔️ | No |
| `KHR_materials_pbrSpecularGlossiness` `material` | ✔️ | ✔️ | No |
| `KHR_materials_unlit` `material` | ✔️ | ✔️ | No |
| `KHR_techniques_webgl` root | ✔️ | ✔️ | No |
| `KHR_techniques_webgl` `program`, `shader`, `technique` | ✔️ | ✔️ | ✔️ |
| `KHR_techniques_webgl` `material` | ✔️ | ✔️ | No |
| `KHR_techniques_webgl` `technique/attribute`, `technique/uniform` | ✔️ | ✔️ | No |
| `KHR_texture_transform` | ✔️ | ✔️ | No |
| `EXT_lights_image_based` root | ✔️ | ✔️ | No |
| `EXT_lights_image_based` `light` | ✔️ | ✔️ | ✔️ |
| `EXT_lights_image_based` `scene` | ✔️ | ✔️ | No |

The core spec design is:
- root level arrays elements inherit from `glTFChildOfRootProperty`, thus having `extras`, `extensions`, and `name` and allowing additional properties; [1]
- internal objects with defined fields inherit from `glTFProperty`, thus having `extras`, `extensions` and allowing additional properties. [2]

Current state of extension objects prevent implementations from re-using already existing inheritance chains leading to more potential ecosystem fragmentation.

**Proposal**
Reduce the number of configurations in the table above by making following changes (hoping it's not too late):

- `KHR_lights_punctual`
  - [x] Align root object, `node` and `light/spot` with [2]
- `EXT_lights_image_based`
  - [x] Align `light` with [1]
  - [x] Align root object and `scene` with [2]
- `KHR_texture_transform`
  - [x] Align with [2]

- [ ] Set up a checklist for future extensions proposals that includes inheritance design.

/cc: @pjcozzi @bghgary @emackey @MiiBond @donmccurdy

**Comment by donmccurdy** [comment]
> Current state of extension objects prevent implementations from re-using already existing inheritance chains leading to more potential ecosystem fragmentation.

I'm not sure I understand this line.

But your proposal, and aiming to have everything be consistent, sounds fine. Aligning with [1] and [2] should strictly loosen requirements on extensions, correct? So I think that is a fairly safe bug fix to make.

**Comment by lexaknyazev** [comment]
Looks like this idea got several thumbs up, so we can proceed with making changes.

@donmccurdy 
> Aligning with [1] and [2] should strictly loosen requirements on extensions, correct?

Yes.

>> Current state of extension objects prevent implementations from re-using already existing inheritance chains leading to more potential ecosystem fragmentation.

>I'm not sure I understand this line.

Thinking in OOP terms, it's quite convenient to rely on something like
```
abstract class GltfProperty {
  extras;
  extensions;
}

abstract class GltfChildOfRootProperty extends GltfProperty {
  name;
}

class KHR_lights_punctual_Light extends GltfChldOfRootProperty {
  /// name, extras, and extensions are already here from ancestors
  /// so only object-specific fields need to be defined
}

class KHR_lights_punctual_Node extends GltfProperty {
  /// extras and extensions are already here from ancestors
  /// so only object-specific fields need to be defined
}
```

Otherwise, developers would need to manually go through each object's fields on a case-by-case basis.

**Comment by lexaknyazev** [comment]
PRs are ready:
#1488, #1495, #1496

**Comment by pjcozzi** [comment]
@MiiBond any update here?

**Comment by MiiBond** [comment]
I've merged #1495 but I wasn't sure of the protocol for merging #1488 since it's my own change. I assume one of the approvers should merge?

**Comment by emackey** [comment]
All 3 PRs are merged now.

@lexaknyazev OK to close?

**Comment by lexaknyazev** [comment]
@emackey 
I've updated the table above with PR changes. Looks like we also have `KHR_draco_mesh_compression` not aligned with others.

Also, we should write needed guidelines to ensure this design for future extensions.
