### ISSUE TITLE
model - "look at camera" even possible in glTF?

### ISSUE THREAD

**Issue by zen85** [KhronosGroup/glTF#1497]
i have an application that shows an avatar. on certain events i want it to look it at the direction of the camera. so it turns its head or at least the eyes in that direction.

does anybody no of an example? after days of searching i did not find anything like that in a three.js example with gtlf but it should be possible because there is an example where the model follows the mousepointer where they use sea3d with an underlying json model...: 
http://sunag.github.io/sea3d/Examples/Programmer/Three.JS/demos/dianna.html

Since i can imagine that this is an issue mainly with the gtlf-model,  i am asking here where to look to get further on that?

**Comment by donmccurdy** [comment]
Once you have loaded your model into three.js, it doesn't particularly matter what the original file format was. In the end it is just a `THREE.Mesh` or `THREE.SkinnedMesh` or a hierarchy of multiple objects. Controlling an avatar will depend very heavily on how you created that avatar — does it have a skeleton? If so, perhaps you can use something like:

```js
var neckBone = model.getObjectByName('my_avatar_neck');
neckBone.lookAt( camera.position );
```

If you get stuck you can get advice on the three.js forum (http://discourse.threejs.org/).
