### ISSUE TITLE
Support for WebGL UNPACK_*

### ISSUE THREAD

**Issue by fabrobinet** [KhronosGroup/glTF#15]
For now, let's use this bug to decide how extensions should be specified.

From Patrick comments.
"Consider support for `UNPACK_FLIP_Y_WEBGL`, `UNPACK_PREMULTIPLY_ALPHA_WEBGL`, and `UNPACK_COLORSPACE_CONVERSION_WEBGL`._"

**Comment by pjcozzi** [comment]
Almost 5 years later...extensions are pretty well specified.
