### ISSUE TITLE
Should accessor have a name property?

### ISSUE THREAD

**Issue by Ziriax** [KhronosGroup/glTF#1508]
According to the [schema](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0/schema), a GLTF `accessor` can have a name? 

This is not mentioned in the spec explicitly, but I want to modify our [Maya2glTF](https://github.com/WonderMediaProductions/Maya2glTF) exporter so that it can assign and export accessor names.

This can be a tremendous help for debugging/diagnostics , e.g. when an accessor has non-unit-length elements, a good accessor name can immediately give a hint.

**Comment by bghgary** [comment]
Yes, accessors can have a name. For example, all the asset generator accessors have names:

https://github.com/KhronosGroup/glTF-Asset-Generator/blob/master/Output/Material/Material_00.gltf#L18

**Comment by Ziriax** [comment]
Good news, then it is just the GLTF lib from COLLADA2glTF that I use that doesn't write these names for some reason.

I'll provide a patch request to that repository, closing this then.

Thanks!
