### ISSUE TITLE
GLTF animation channel name?

### ISSUE THREAD

**Issue by Ziriax** [KhronosGroup/glTF#1510]
According to the schema, a GLTF `channel` doesn't have a `name`. This is correct?

I ask this question because our Maya2glTF is now filling in a lot more `name` properties, also for `channel`, but that seems incorrect (the validator complains).

**Comment by lexaknyazev** [comment]
Only root-level array elements have names.

/cc @pjcozzi

**Comment by emackey** [comment]
Such non-root names weren't included in the glTF 2.0 schema, but can still be placed inside an `extras` object to retain the information.

**Comment by Ziriax** [comment]
Perfect, thanks for clarification! 

It was a bit confusing because the `GLTF::Channel` from the `COLLADA2GLTF/GLTF` library that we use derives from `GLTF::Object`, and so gets a name when assigning one, so the mistake was easy to make.
