### ISSUE TITLE
shader is wrong in diagram

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/glTF#1516]
<img width="398" alt="screen shot 2018-12-19 at 0 25 10" src="https://user-images.githubusercontent.com/234804/50163823-9e3cc700-0324-11e9-95d1-6e6c423aa0f4.png">

The shader above will not compile as `position` is a `vec3`. Suggest changing it to a `vec4` as `w` defaults to 1 anyway

**Comment by javagl** [comment]
Thanks for reporting this. I'm closing the issue here, but opened it at https://github.com/javagl/gltfOverview/issues/4 to track it there. Maybe I can allocate some time during the holidays to create an update.
