### ISSUE TITLE
typo in diagram

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/glTF#1517]
<img width="469" alt="screen shot 2018-12-19 at 0 28 42" src="https://user-images.githubusercontent.com/234804/50164072-186d4b80-0325-11e9-9cb8-28d9ab59b229.png">

s/byeOffset/byteOffset/

**Comment by javagl** [comment]
Thanks for reporting this. Closing the issue here, and opened https://github.com/javagl/gltfOverview/issues/5 instead.
