### ISSUE TITLE
Do you support particle systems

### ISSUE THREAD

**Issue by Carolineliu** [KhronosGroup/glTF#1521]

**Comment by emackey** [comment]
There are no particle systems included with core glTF 2.0.  But proposals for extensions are always welcome.

**Comment by Carolineliu** [comment]
I am so sad.

**Comment by emackey** [comment]
Can you describe more about what software you're using, or which software packages you might want to have export particle systems, import particle systems, and use them?

**Comment by Carolineliu** [comment]
I am  using Cesium.

**Comment by Carolineliu** [comment]
Can I make a flame model by it?

**Comment by emackey** [comment]
Cesium has an [Introduction to Particle Systems here](https://cesiumjs.org/tutorials/Particle-Systems-Tutorial/) and some [reference documentation here](https://cesiumjs.org/Cesium/Build/Documentation/ParticleSystem.html).  glTF doesn't currently play a role in this itself, but of course you can assign a particle system to a model in your app.

**Comment by Carolineliu** [comment]
I try it,but I think that effect are not up to expectation.

**Comment by donmccurdy** [comment]
Custom effects like fire are not something we can really put into the glTF model format; there would need to be consensus among engines about how to implement it first, or at least room for glTF to create consensus, and I don't think that is true today.

Extensions like KHR_techniques_webgl can be used for effects like fire, although (1) the extension is not yet finished, (2) it's TBD which exporters will implement it, and (3) an exporter that supports `KHR_techniques_webgl` is not necessarily going to include all of its particle effects.

Maybe there are some specific features related to particle systems that would make sense for glTF? I'd be happy to see proposals for something like that, but will close this issue for now.

**Comment by TristonH55** [comment]
Is it possible to make my character https://gyazo.com/c0eb6caa80e1c6c150781ba2e7230b0e that has particle effect and hue saturation node work as a Gltf... if so how ? (Blender)
