### ISSUE TITLE
Change `skin`, `mesh`, `camera`, `light` on `Node` to something more flexible

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/glTF#1527]
As it is there are these special fields on `Node`.  `skin`, `mesh`, `camera`,  That seems unflexible. As new types are added node becomes one of those types that all kinds of unrelated data is dumped into that are often complained about in software engineering.

It seems like those should be removed because if/when new objects are added there will be more and more of these properties on `Node`. 

Instead they should point the other way.

`light` and `camera` would contain a reference to their node

```
   cameras: [
        {
            "name": "Finite perspective camera",
            "type": "perspective",
            "node": 3,   // <------------------------
            "perspective": {
                "aspectRatio": 1.5,
                "yfov": 0.660593,
                "zfar": 100,
                "znear": 0.01
            }      
        },
   ],
```

Meshes it would arguably be better to had a `meshInstance` which would reference a mesh and a node

```
meshInstances: [
  { mesh: 3, node: 1 },
  { mesh: 3, node: 2 },
  { mesh: 4, node: 5 },
],
```

For skins the skin maybe should reference the mesh and the node 

```
skins: [
        {
            "inverseBindMatrices" : 7,
            "node": 6,  // <-----------
            "mesh": 1,  // <-----------
            "joints" : [
                6,
                7,
                8,
                9,
                10,
                11
            ],
            "skeleton" : 1
        }
    ],
```

For skins this would also remove the circular reference. Right now a node references a skin and a skin references a bunch of nodes (the joints).

Also see #889, #13, #1433 etc .

Various engines can solve this however they choose. If both a camera and a light point to the same node then if you have an engine has different kinds of nodes in it's scene graph that engine can generate 2 children, a light, and a camera. A component based engine would add components to that node, as many as are specified, yet other engines don't even store things in the scene graph, they only use it to get matrix data so they'd be covered as well.

**Comment by aaronfranke** [comment]
This will never happen, and is completely backwards. This does not improve things for anyone. Not asset creation tools, not game engines, not conceptually. It is in fact worse because it prevents sharing one resource with many nodes, and it requires resources to have knowledge of which nodes they apply to, which is backwards. This issue should be closed.
