### ISSUE TITLE
joint indices padding for vertex joints and weights

### ISSUE THREAD

**Issue by kcoley** [KhronosGroup/glTF#1530]
The glTF specification indicates for joints the following:
> The number of joints that influence one vertex is limited to 4 per set

However, the spec does not indicate what joint index value should be used when there are less than four joints influencing a vertex, and the "padded" joint index values are multiplied with a weight of zero.  Should the joint index be any index within the skin, or does the value of the index matter (can it be a non-existing index)?

**Comment by najadojo** [comment]
In our loader we validate that the joints index values are in the range of the joint array. We will fail to load an asset that uses a non-existent index. We also read the joints completely and then the weights completely (in that order). I would really rather not scan through that data looking for weight == 0 to ignore a joint value.

**Comment by lexaknyazev** [comment]
For tightening padding, I can see two options (the spec needs to be updated):
- use `0`;
- use maximum possible integer value for a given type (e.g. `255` for `uint8`) and disallow using this value as an actual index (basically, replicating primitive restart design).

Regardless of chosen approach, the weight must be `0.0` and joint values should never point to a random non-existing index. Also keep in mind, that like with many other skinning issues, the validator doesn't check for that yet.

**Comment by bghgary** [comment]
The Babylon.js exporters are/were using the count of joints. This is arguably slightly harder to handle than the `maximum possible integer` option. @kcoley is updating the exporters to use `0`.

I would prefer the first option to use `0` so that it is less likely to be an issue for importers.

**Comment by lexaknyazev** [comment]
FWIW, zeros should also compress better.
