### ISSUE TITLE
[Proposal] Standardized glTF File Icon

### ISSUE THREAD

**Issue by StephenHodgson** [KhronosGroup/glTF#1536]
Wondering if anyone has thought of making a standardized glTF file icon.

**Comment by emackey** [comment]
The Khronos Logo & Trademark page is here:

https://www.khronos.org/legal/trademarks/

For icons that are smaller than 50 pixels, the glTF logo gets shortened to just the "TF" part, like this:

![gltf_logobug_48px_nov17](https://user-images.githubusercontent.com/1235080/51411958-e32c6700-1b37-11e9-837e-e70f487af913.png)

That might make a good file icon...
