### ISSUE TITLE
Binary glTF, embedded textures

### ISSUE THREAD

**Issue by gokulsukumar03** [KhronosGroup/glTF#1544]
How to export Binary glTF, embedded textures in blender.

**Comment by donmccurdy** [comment]
Hi @gokulsukumar03 – this repository is about the glTF format itself, I might suggest https://github.com/KhronosGroup/glTF-Blender-IO or the Blender forums for Blender issues. https://github.com/KhronosGroup/glTF-Blender-IO

Also see the (in progress) docs for glTF in Blender 2.8 here: https://gltf-blender-io-docs-fuznnktuig.now.sh/addons/io_gltf2
