### ISSUE TITLE
How to archive stale pull requests?

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#1548]
There are several glTF spec/extension [pull requests](https://github.com/KhronosGroup/glTF/pulls) that are potentially good ideas but have lost momentum.  They would benefit from someone picking them back up if they are a priority enough for someone to bring over the finish line.

How should we archive these PRs?  For example:
* Just close them.  They will still show up in searches.
* Assign the `archive` label (or whatever name we like) and keep them open.
* Assign the `archive` label and close them.

**Comment by emackey** [comment]
I don't think we need a label, just close them.  Future users are more likely to search for a topic of interest rather than an archive label.

**Comment by pjcozzi** [comment]
Seems like folks are OK with just closing them - works for me - will do as we review them, thanks!
