### ISSUE TITLE
gltf renderer in android

### ISSUE THREAD

**Issue by gokulsukumar03** [KhronosGroup/glTF#1551]
Can we have gltf renderer for Android?

**Comment by emackey** [comment]
Yes.  There are some mentions of Android under the [Viewers and Debugging section](https://github.com/KhronosGroup/glTF#viewers-and-debugging) of the README.  Several game engines (Unity, Unreal, Godot, Ogre, others) can import glTF and many of them can build for Android.  JavaScript engines like BabylonJS and ThreeJS can display a glTF inside a WebView component on Android.  For users, there are some apps including one named "glTF Viewer" that can directly load and display glTF files.

Let us know if you come across any Android packages supporting glTF that we don't have listed in the main README, and we'll probably add a link at some point.  Thanks!

**Comment by donmccurdy** [comment]
Filament is another: https://github.com/google/filament/

**Comment by javagl** [comment]
There have been some experiments for using JglTF in Android, e.g. https://github.com/javagl/JglTF/issues/4#issuecomment-451564983 . But the actual *viewer* does not (yet) properly support glTF 2.0, so this is far from an "out-of-the-box" solution. Maybe, one day, I'll be able to invest more time here and bring it into a state that is really usable...
