### ISSUE TITLE
Compute tangents with UV attribute type different than float

### ISSUE THREAD

**Issue by jjcasmar** [KhronosGroup/glTF#1564]
glTF 2.0 requires the loader generates tangents using MikkTSpace if they are not provided. For this, the UVs are necessary. 

The UVs can be define using Float, UnsignedByte or UnsignedShort data types but it doesn't say how to convert the byte and short types to the float one until the Animation section.

I think there should be a clarification on this. Do we have to use the same formulas as in the animation section?

**Comment by scurest** [comment]
Cf. https://github.com/KhronosGroup/glTF/issues/1086#issuecomment-326996184
