### ISSUE TITLE
GLTF Custom Vertex Attributes

### ISSUE THREAD

**Issue by Kif11** [KhronosGroup/glTF#1570]
Is there specs for storing custom vertex attributes in GLTF? Like name should start with _ or be upper or lower case?

Possibly related to https://github.com/KhronosGroup/glTF/issues/563
Also related to this https://github.com/mrdoob/three.js/issues/15868

**Comment by donmccurdy** [comment]
Uppercase and prefixed with a `_`. See [this section](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#meshes) in the spec:

> Valid attribute semantic property names include POSITION, NORMAL, TANGENT, TEXCOORD_0, TEXCOORD_1, COLOR_0, JOINTS_0, and WEIGHTS_0. Application-specific semantics must start with an underscore, e.g., _TEMPERATURE.

You could also use additional vertex color or UV attributes, of course. Less ideal semantically but easier in DCC tools. :)

**Comment by Kif11** [comment]
Thank you for pointing this out. I wasn't reading careful enough.

**Comment by EliCDavis** [comment]
For people looking at this thread in the future it can be found page 39 here
https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.pdf
