### ISSUE TITLE
Bug Report: Export cancelled after vertex optimization failure

### ISSUE THREAD

**Issue by BaldSavant** [KhronosGroup/glTF#1577]
![Babylon_BugReport](https://user-images.githubusercontent.com/17505845/54055622-7f6f0380-41a2-11e9-9363-64351aabd173.png)

The above is an image showing an error message I got while trying to export. My first export failed with an incomprehensible error message which I eventually pulled in a programmer to help me understand. I then tried it without Optimize vertices enabled, since said programmer advised that that seemed to be what the error message was trying to say. That export succeeded, and then gave me a useful error message that directly tells me the issue and enables me to debug it in the file. I found the culprit was a corrupt UV Set present in my maya file.

This is merely a bug report to denote the error and how I resolved it.

**Comment by bghgary** [comment]
Hi @BaldSavant.

This repo is for glTF issues while your issue is for a BabylonJS exporter. Please file it in this repo: https://github.com/BabylonJS/Exporters.

Thanks!
