### ISSUE TITLE
Extension serialization Issue with KHR_lights_punctual and EXT_lights_image_based

### ISSUE THREAD

**Issue by vpenades** [KhronosGroup/glTF#1578]
I was trying to implement `KHR_lights_punctual`, and I've found an issue that makes serialization a lot more complicated.

Most extensions just add a single object to a particular node in the gltf model. So when reading a gltf model, and given each extension object has a mapped class, it's easy to tell the JSON reader which class to instantiate when a particular extension is found.

But `KHR_lights_punctual` and `EXT_lights_image_based` add several different objects to different parts of the gltf model.

For example `KHR_lights_punctual` requires two different extension objects at two different places: a collection of lights at the gltf root level, and an index reference object at the node level.

The problem is that, although both represent completely different objects, they're represented in the JSON with exactly the same name.

This makes impossible to map a particular JSON property name to a specific class; in javascript everything might look cool and nice, but for other languages this is a big pain.

I guess at this point in time it's impossible to fix, but please, refrain from doing this for future extensions; JSON instances should be mapeable to specific and uniquely identifiable structures.

**Comment by bghgary** [comment]
> This makes impossible to map a particular JSON property name to a specific class; in javascript everything might look cool and nice, but for other languages this is a big pain.

Can you elaborate on this and give an example? That will help with understanding the pain points.

**Comment by donmccurdy** [comment]
> This makes impossible to map a particular JSON property name to a specific class; in javascript everything might look cool and nice, but for other languages this is a big pain.

I'm not sure it's realistic to expect JSON property names to be unique across all objects in a schema. For example, any number of things may need to reference nodes or accessors. It may be worth looking at something like [cgltf](https://github.com/jkuhlmann/cgltf), which has support for KHR_lights_punctual in a non-JavaScript language.

The structure here (a top-level list of resources, with node-level extensions referring to it) is chosen to avoid duplication of reused objects, similar to how meshes, textures, and other core glTF resources work.

**Comment by vpenades** [comment]
@bghgary Hi

Yes, this is related to writing a JSON parser able to read the full schema. The idea of having a schema is to be able to generate serialization code programatically.

Now, the most usual way of writing serialization code is to map a specific key to a specific class, so when the parser finds a given key, it instantiates the appropiate class. Notice that this rule is only valid as long as the mapping is one to one.

With the introduction of extensions where a specific key can map different classes, depending of the context, the rule of one to one mapping is broken. So a naive parser is no longer possible.

So, in a "one to many" schema, a parser needs to know its own context to know the meaning of a given key.

For example, `KHR_lights_punctual` does not mean the same thing if found in the model's root, or in a node.

In my parser, I've just been able to handle this case because I support hand coded parsing, but I see it as an unnecessary hurdle.

As I said, since these extensions are already closed and official, I don't expect any changes, and after all, I am already handling this case.... but I do hope for next gltf version, to be more restrictive regarding extensions and parsing rules.

**Comment by bghgary** [comment]
> I'm not sure it's realistic to expect JSON property names to be unique across all objects in a schema. 

+1

>  generate serialization code programatically

Without looking at code, it's hard to know how hard it would be, but I think it should still be possible to do this programmatically if the code takes the context into account. If the `KHR_lights_punctual` is under scene vs. under node, the generator can prefix the class name with the context (or namespace it).
