### ISSUE TITLE
Animation: input parameter type

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#158]
Possible values for an animation `parameter`'s type depend on if it is being sampled for input or output.  I believe that an input needs a scalar type.  Questions/comments:

* Should we allow all scalars or just `FLOAT`?
* Should we explicitly define the `TIME` semantic as a `FLOAT`?
* Given that a parameter, in theory, could be sampled as both input and output, we would have to word the spec that if a parameter if ever referenced as input to a sampler, it must have a scalar (or `FLOAT` pending above questions) type.

```json
"TIME": {
  "bufferView": "bufferView_393",
  "byteOffset": 0,
  "count": 78,
  "type": "FLOAT"
}
```

**Comment by pjcozzi** [comment]
@tfili is this easy for you to do in COLLADA2GLTF?

> count for animations is now removed from the schema (6ed6748). @fabrobinet can you update the converter?

**Comment by pjcozzi** [comment]
@tfili see the question above, https://github.com/KhronosGroup/glTF/issues/158#issuecomment-135403654

**Comment by tfili** [comment]
Removed `count` from animations in 9ec4d7098c7e185351f0efdd3460fbf9d6730d1c.

**Comment by pjcozzi** [comment]
Thanks @tfili
