### ISSUE TITLE
How to add vendors extensions to extend glTF?

### ISSUE THREAD

**Issue by Krakean** [KhronosGroup/glTF#1581]
Hello.
Downloaded GLTF. Downloaded GLTF-Sharp-Loader. Created .cs files using generator.
Question: how can I add for example this extension - https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Vendor/MSFT_texture_dds ? What .json file in GLTF/2.0/schema folder I should modify to add this extension to "known list of extensions" so GLTF-Sharp-Loader will create .cs file for this newly added extension  and general gltf schema will be know that such extension is "connected" and extended gltf?

**Comment by emackey** [comment]
Hi @Krakean, sorry this is the wrong place to ask such a question.  Maybe try asking on the [SharpGLTF repo](https://github.com/VPenades/SharpGLTF/issues).
