### ISSUE TITLE
Node property "name" has no type in the JSON schema

### ISSUE THREAD

**Issue by rawnsley** [KhronosGroup/glTF#1584]
The [name property](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/node.schema.json#L82) in the node schema ([and](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/material.schema.json#L8) [other](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/animation.schema.json#L24) [places](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/texture.schema.json#L16)) has no mandated [type](https://cswr.github.io/JsonSchema/spec/basic_types/), but [the specification says](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#nodename) it's a string.

**Comment by Ybalrid** [comment]
I'm currently adding a few of the missing ones

**Comment by Ybalrid** [comment]
So, I've added the type "string" to all the names, and the type "object" to all the "extensions". There's probably a few more missing fields in theses schema, but it would require spending a bit more time on the matter.

Changes are in the associated PR linked above

**Comment by emackey** [comment]
Hi @rawnsley and @Ybalrid, it's a little confusing, but these restrictions are already in place, with no PR needed.  Each glTF schema at the root level contains this:

```
"allOf": [ { "$ref": "glTFChildOfRootProperty.schema.json" } ],
```

And, each glTF schema below the root level contains this:

```
"allOf": [ { "$ref": "glTFProperty.schema.json" } ],
```

The [glTFProperty](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/glTFProperty.schema.json) schema defines `extensions`, referencing the [extension](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/extension.schema.json) schema that requires it to be an object.

Likewise, the [glTFChildOfRootProperty](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/glTFChildOfRootProperty.schema.json) schema further builds on the glTFProperty one, to add `name` as a string.

![vscode-numericName](https://user-images.githubusercontent.com/1235080/54688058-511eeb80-4af3-11e9-88bd-8d62a958d66b.png)

If you try editing a glTF file in VSCode, and for example put a numeric value in as the name, you'll see that VSCode produces two separate messages for the same error.  One message is labeled as coming from the glTF Validator, but the other is more anonymous.  This second message actually comes from VSCode's own JSON validation code, which is comparing the document against the glTF schemas, and is finding these restrictions included in the schema directly.

So I don't think any change is needed in this particular case.  I'm sure there are mistakes still waiting to be found elsewhere though, please do keep an eye out, thanks!

**Comment by rawnsley** [comment]
@emackey I thought I must be missing something, but then why restate the empty property definitions in the node schema?

**Comment by emackey** [comment]
That's a question for @lexaknyazev, but, my (limited) understanding is that it's required because of the way property inheritance works (or don't work) in the current version of JSON schema definitions we're using.  Sorry I don't know in more detail on that one.

**Comment by Ybalrid** [comment]
So, I closed my PR where I added the types in the "sub" schema files.

**Comment by bghgary** [comment]
> why restate the empty property definitions in the node schema?

See #252, corresponding PR #769, and the specific issue https://stackoverflow.com/questions/22689900/json-schema-allof-with-additionalproperties
