### ISSUE TITLE
Validated glTF files can not be viewed

### ISSUE THREAD

**Issue by SalehChoueib** [KhronosGroup/glTF#1587]
I have spent some time creating a glTF exporter using the tinyglTF library. I am exporting out of 3D Slicer which uses VTK for 3D rendering. The exporter will create glTF files that are valid according to http://github.khronos.org/glTF-Validator/ . However, when I upload the files to a glTF viewer, nothing is rendered. I was wondering if anyone may have an idea as to why this happens, or has experienced this before.

**Comment by javagl** [comment]
Can you provide one of the models (preferably as plain .glTF+BIN files, or embedded)? Maybe a manual inspection will shed some light on this.

**Comment by SalehChoueib** [comment]
Hi @javagl , 
    
       Thank you for your response. Unfortunately GitHub does not support gltf files, but for the purposes of doing a manual check I suppose a plain text file will do, which is attached. I tried windows 3D viewer, and a few online "gltf viewers", none of which gave me any error messages. 


[USprobe.txt](https://github.com/KhronosGroup/glTF/files/3034789/USprobe.txt)

**Comment by donmccurdy** [comment]
@SalehChoueib you can drag ZIP archives into Github comments. This file is missing its `.bin` binary and isn't debuggable without that.

**Comment by SalehChoueib** [comment]
@donmccurdy Here is the bin file along with the gltf file. Thank you for the suggestion. 
[USprobe.zip](https://github.com/KhronosGroup/glTF/files/3035215/USprobe.zip)

**Comment by donmccurdy** [comment]
Validation on this model comes up with 62,000 errors, so I think it's safe to assume the exporter has got something wrong here. Note that you'll need to include both files when validating, or else the binary payload cannot be checked. https://gltf-viewer.donmccurdy.com/ also provides a validation report in the lower left, using the same validation library.

**Comment by emackey** [comment]
Looks like the vertex indicies are invalid.  Now that the .bin file is there, the validator is reporting that they're way out-of-bounds.

The contents of that index buffer decode like this in VSCode:

```
    0
16777216
33554432
33554432
50331648
    0
50331648
67108864
    0
67108864
83886080
    0
83886080
100663296
    0
...
```

Maybe there's a byte order problem?

**Comment by SalehChoueib** [comment]
@donmccurdy @emackey  Thank you for your replies. It seems, like Don mention, I was not uploading the bin file along with the gltf file in the validator.

**Comment by emackey** [comment]
I'm going to close this since there's no change needed to glTF itself.  But let us know if you get the export working.  Looks like the exporter is not respecting glTF's byte order when it comes to writing integers for vertex indices.
