### ISSUE TITLE
Missing default values in schema2 Sampler.

### ISSUE THREAD

**Issue by vpenades** [KhronosGroup/glTF#1589]
I've noticed that in the `sampler.schema.json` Sampler specification, Both `WrapS `and `WrapT `have a defined default value.

But both `TextureInterpolationMode `and `TextureMipMapMode`  don't have any default value.

They also don't have the "required" attribute, which I believe is contradictory.

I would suggest to either introduce default values for these two parameters, or mark them as required.

For now, I am using LINEAR value for both as default value.

**Comment by lexaknyazev** [comment]
From [Samplers](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#samplers) section:
> When filtering options are defined, runtime must use them. Otherwise, it is free to adapt filtering to performance or quality goals.
