### ISSUE TITLE
converter should discard constant animations when they equal to the initial TRS in node.

### ISSUE THREAD

**Issue by fabrobinet** [KhronosGroup/glTF#159]
So we should just zap the animation if say for scale in node we have [1,1,1] and we got all keys the same [1,1,1]. If we have a different initial transform in the node but still constant keys in animations then should we trim the animation and just keep first and last key.

Note: we may want to track this also at the OpenCOLLADA level to get better data in the first place.

**Comment by pjcozzi** [comment]
If this comes up often in practice, please submit an issue to https://github.com/KhronosGroup/COLLADA2GLTF/issues
