### ISSUE TITLE
What is the current ambient occlusion standard?

### ISSUE THREAD

**Issue by Siccity** [KhronosGroup/glTF#1593]
I'm writing an importer using examples from the gltf examples repo. I've seen some models use the red channel in the metallic map as AO, while others had a completely black red channel. I can't support one without breaking the other.

So, where does ambient occlusion go?

Additionally: I haven't found the AO at all in the specular workflow files

**Comment by donmccurdy** [comment]
If the material has an AO texture, it must specify [`occlusionTexture`](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#materialocclusiontexture) in the material definition.

The occlusion texture _may_ be the same texture as `metallicRoughnessTexture`, but is not required to be (for example, using separate UVs for AO is common). In any case, AO is always sampled from the red channel of `occlusionTexture`. If `occlusionTexture` isn't specified, or isn't the same as the `metallicRoughnessTexture`, then the red channel of `metallicRoughnessTexture` could certainly be black.

The exact same `occlusionTexture` property is used in spec/gloss materials, but it is never packed with the spec/gloss texture (which is already using 4 channels).

**Comment by Siccity** [comment]
That makes sense, thanks!

**Comment by emackey** [comment]
@Siccity If you like, we'd welcome a PR to add GLTFUtility to README.md, maybe under [Game and Rendering Engines](https://github.com/KhronosGroup/glTF#game-and-rendering-engines) or in [Converters, Importers, and Exporters](https://github.com/KhronosGroup/glTF#converters-importers-and-exporters), whichever you think is more appropriate.

**Comment by Siccity** [comment]
@emackey I already submitted a link to GLTFUtility in https://github.com/KhronosGroup/glTF/issues/1058 for this purpose.
I'd appreciate it if you added it under [Game and Rendering Engines](https://github.com/KhronosGroup/glTF#game-and-rendering-engines), thanks.
