### ISSUE TITLE
Does glTF have plan to support OSL, RSL or MDL for shader?

### ISSUE THREAD

**Issue by alexchicn** [KhronosGroup/glTF#1595]
I know OSL/RSL is for the offline renderer and GLSL/HLSL is for the real-time renderer.
But I also want to render the glTF scene in Renderman or Blender by an offline renderer like pbrt.v3, tungsten, or appleseed.

By the way, Nvidia's MDL might support both offline and real-time.

**Comment by emackey** [comment]
The next-gen material for glTF is under discussion in #1442.  Take a look in particular at the [Dassault Systèmes proposal](https://github.com/KhronosGroup/glTF/issues/1442#issuecomment-479876304), and if you have feedback you can use that thread for discussion.

**Comment by donmccurdy** [comment]
Just to be specific – the glTF PBR materials can be implemented in any of these shader languages, but the glTF 2.0 file format itself does not contain shaders. Just a declarative representation of the PBR material properties. The specification explains how to correctly implement the PBR material from those properties.

**Comment by alexchicn** [comment]
Yes, I know glTF PBR material is a representation. But it is impossible to use only one material on all surfaces of meshes.
The glTF is excellent, and I hope the next-gen material of glTF supports more materials for runtime, ray-tracing or path-tracing.

Thanks.
