### ISSUE TITLE
Should LINEAR animation explicitly support one keyframe?

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF#1597]
In https://github.com/KhronosGroup/glTF-Blender-IO/pull/417#pullrequestreview-224870973, @UX3D-becher writes:

> Although the glTF specification to my knowledge would allow single keyframes with linear interpolation, some engines expect at least two.

Sometimes a single keyframe is used as part of a larger animation simply to set a constant value for use in that channel during the animation.  So, I think it is reasonable to expect that engines should respect an individual keyframe (a sampler of length one) as a constant value, regardless of the type of interpolation chosen for the animation.

Thoughts?

**Comment by pjoe** [comment]
Agreed, I will try and make a test file to check most common engines.

**Comment by pjoe** [comment]
Here is a sample from blender exported with and without sampling:
[linear_anim.zip](https://github.com/KhronosGroup/glTF/files/3067705/linear_anim.zip)

And for reference how it look inside blender:
![linear_blender](https://user-images.githubusercontent.com/1846572/55943106-35b48580-5c46-11e9-87f0-b11d652b5725.gif)

The animation part in gltf:
```json
{
    "animations" : [
        {
            "channels" : [
                {
                    "sampler" : 0,
                    "target" : {
                        "node" : 4,
                        "path" : "translation"
                    }
                }
            ],
            "name" : "Cube.002Action",
            "samplers" : [
                {
                    "input" : 13,
                    "interpolation" : "LINEAR",
                    "output" : 14
                }
            ]
        },
        {
            "channels" : [
                {
                    "sampler" : 0,
                    "target" : {
                        "node" : 5,
                        "path" : "translation"
                    }
                }
            ],
            "name" : "Cube.003Action",
            "samplers" : [
                {
                    "input" : 15,
                    "interpolation" : "LINEAR",
                    "output" : 16
                }
            ]
        }
    ]
}
```

**Comment by pjoe** [comment]
As far as I can tell this works correctly in:

- babylonjs (https://sandbox.babylonjs.com/)
- three.js (https://gltf-viewer.donmccurdy.com/)

Will test in other engines too :)

**Comment by donmccurdy** [comment]
Agreed that STEP and LINEAR should reasonably support a single keyframe. I'm less sure about CUBICSPLINE, since first and last tangents are expected to be zero.

**Comment by scurest** [comment]
What's the problem with the first and last tangents being zero on a CUBICSPLINE sampler?

**Comment by donmccurdy** [comment]
I'd just be less surprised if that hit bugs in implementations. No reason it shouldn't work though.

**Comment by bghgary** [comment]
FYI, the glTF-Asset-Generator repo has tests for this specific case.

https://github.com/KhronosGroup/glTF-Asset-Generator/tree/v0.6.1/Output/Positive/Animation_NodeMisc (Model 03)

**Comment by lexaknyazev** [comment]
Only the `CUBICSPLINE` sampler type is required to have two keyframes. `LINEAR` and `STEP` have no extra restrictions.

@emackey 
Do you think the spec needs any more clarifications there?

**Comment by emackey** [comment]
No, I think it's clear now.
