### ISSUE TITLE
Minimum Viable Quad Support?

### ISSUE THREAD

**Issue by zellski** [KhronosGroup/glTF#1599]
So... Catmull-Clark Subdivision is pretty great. We use it a fair bit. As I've understood things, it really wants to work on quads –– a primitive that glTF does not natively support, but quite easily could?

Extending the `mesh:primitive:mode` enum is probably not the right call. But it seems to me there are many plausible solutions. Many would need `extensionsRequired`, and maybe that's fine, but there's (less efficient, though, I think) designs that would remain drawable glTF for core loaders.

Has anyone else done work on, or thought about. adding quad/ngon support?

**Comment by zellski** [comment]
I'm going to retract my query/suggestion; there are simpler ways to unblock ngon support in the short term, and I imagine full native representation is a consideration for glTF > 2.

**Comment by lexaknyazev** [comment]
@zellski could you please elaborate on "simpler ways to unblock ngon support"? 
Going forward (glTF 3.0+), I'd expect any non-triangle geometry to be compatible with GPU tessellation.

**Comment by zellski** [comment]
My original thought, now abandoned, was to annotate each quad-tessellated mesh primitive with a required extension –– just a marker, which would indicate that `mode` should be ignored, and that vertex indices should be consumed four at a time. Like:

```
            "primitives": [
                {
                    "attributes": {
                        "NORMAL": 1,
                        "POSITION": 2,
                        "TEXCOORD_0": 13
                    },
                    "indices": 0,
                    "mode": 4,
                    "material": 3
                    "extensions": {
                        "FB_quad_primitive": {}
                    }
                }
            ]
```

But I want to avoid a required extension, and an encoding that's incompatible with anything else, unless absolutely necessary. I suppose if such an extension were proposed and implemented in the tooling ecosystem, it would be a decent way to do.

Until then, the simple workaround we decided on internally is an **optional** marker extension, which communicates that in addition to the mesh being interpretable as core glTF, the original polygons may also be reconstructed by consuming triangles as strips, using vertex order to signal which triangle belong to which polygon. Each lumped-together set of triangles are expected to be coplanar and otherwise well-behaved, else the asset is invalid. (I don't know if this is an obvious & well-known trick in the 3D community; I didn't come up with it myself.)

I think the only costs are bloated geometry representation (not a big deal for us, since with sub-div the mesh is fairly coarse) and the fact that optimising pipelines can't take liberties with index order (e.g. Draco compression is likely out), at least not without some care.

I'm happy to write up a FB_* extension PR for this, but I don't know if this solution has general applicability?
