### ISSUE TITLE
Normal/tangents computations with morph targets

### ISSUE THREAD

**Issue by jjcasmar** [KhronosGroup/glTF#1603]
Lets say we have a mesh which doesn't have tangents or normals. The specification requires to compute normals and tangents for that mesh. 

If that mesh also has morphtargets, do we need to compute normals and tangents for each morph target?

If the weight for the morph target is animated, do we need to compute normals and tangents at each interpolated mesh?

**Comment by vpenades** [comment]
As far as I know:

Answers to 1 and 2:, yes, you need to compute normals and tangents for each morph target.

Answers to 3; no, theoretically, the interpolation is some by the shader in real-time, so you don't need to pre compute for each linear step.
