### ISSUE TITLE
About generating the schema documentation

### ISSUE THREAD

**Issue by javagl** [KhronosGroup/glTF#1607]
During one of the previous calls, we considered to use [jsonschema2md](https://github.com/adobe/jsonschema2md) for generating the properties reference that is currently created with [wetzel](https://github.com/AnalyticalGraphicsInc/wetzel) and contained in the spec README at https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#properties-reference 

I gave jsonschema2md a really quick try. The current output is linked at
https://github.com/javagl/glTF/tree/jsonschema2md-output/specification/2.0#properties-reference

There are some obvious issues:

First of all: the generator uses draft-07 by default. We currently have draft-04. This is also supported, but there are some of the expected quirks with 'anyOf' for the glTF enum constants. The current output for these is not useful: https://github.com/javagl/glTF/blob/jsonschema2md-output/specification/2.0/accessor.schema.md#type-type
Additionally, the generator reports several "Unknown types", and does not contain as many cross-links and details as the output of wetzel, but it's hard to say in how far this could be improved if we updated to a later JSON schema version (added IDs - see below).
(Related: "JSON-Schema v6 updates roadmap" https://github.com/KhronosGroup/glTF/issues/929)

Beyond that:

- The current schema does not contain IDs. This seems to cause some trouble for the generator.
(Side note: We could add IDs regardless of which generator is used, because it is recommended as a "best practice" anyhow)

- By default, the generator creates one MD file for each schema file. It could/should be possible to create a single file, but this would have to be done by jsonschema2md - otherwise, the links and anchors could not be handled properly.
(Side note: We might also consider pulling the "Properties Reference" out of the main README. The current readme has 150KB and a bit clumsy to edit - especially when we intend to let the properties reference be generated automatically in the future...)

- The gltf_detailedDescription is not handled, of course

If we pursue the idea of using jsonschema2md, I can try to investigate which of these issues could be fixed with reasonable effort.

(It may be worth noting that the current state of the README is also not entirely up to date. A more recent version of the output can be found at https://github.com/javagl/glTF/tree/update-properties-from-schema/specification/2.0#properties-reference )

**Comment by emackey** [comment]
Would be great to separate the auto-generated portion of the README out to its own file.
