### ISSUE TITLE
sRGB when textures are missing

### ISSUE THREAD

**Issue by jjcasmar** [KhronosGroup/glTF#1608]
I'm a bit confused about the interpretation of the baseColorTexture being stored in sRGB space. 

Quoting from the spec

> If a texture is not given, all respective texture components within this material model are assumed to have a value of 1.0. If both factors and textures are present the factor value acts as a linear multiplier for the corresponding texture values. The baseColorTexture is in sRGB space and must be converted to linear space before it is used for any computations.

Does this mean that if the texture is not given, the (1,1,1,1) value must be interpreted already as linear or is sRGB and must be converted to linear space?
Which one is correct?
outputColor = (1,1,1,1) * baseColorFactor
or
outputColor = convert_sRGBToLinear(1,1,1,1) * baseColorFactor?

Thanks

**Comment by emackey** [comment]
The `baseColorFactor` and all other factors are expressed as linear values, not sRGB.  This was done because some systems will decode sRGB in hardware, so the factor multiplication needs to take place after the values have already been converted to linear.

**Comment by jjcasmar** [comment]
I understand that, but its not the question I asked. As its worded, it says that if the texture is not given, we must consider to have a constant value of (1,1,1,1) (`all respective components are assumed to have a value of 1.0`). Does this means that we have to convert (1,1,1,1) from sRGB to linear space and then multiply that result by the baseColorFactor?

**Comment by emackey** [comment]
Ah, sorry.  Most implementations optimize this part out, and just use the baseColorFactor directly.  It is presumed that `convert_sRGBToLinear(1,1,1,1)` is sufficiently close to (1, 1, 1, 1) as to not have any meaningful effect on the result.  Certainly, if one is using the "power of 2.2" real-time approximation for the sRGB transfer function, the result is exactly (1, 1, 1, 1), and does not impact the calculation.

**Comment by jjcasmar** [comment]
Okay, thanks. Now its clear
