### ISSUE TITLE
GLTF Exporter

### ISSUE THREAD

**Issue by bigidea-kz** [KhronosGroup/glTF#1615]
Hello
I export a model from a blender with two materials that use the one texture. The exportable file is obtained with two textures, why not use one texture?

Sorry for my english

3d soft: Blender 2.79b
Exporter: GLTF 2.0
Export to: Glb, Gltf, Gltf + bin + textures

**Comment by donmccurdy** [comment]
@bigidea-kz could you open an issue on https://github.com/KhronosGroup/glTF-Blender-IO instead? This repository is for the format itself, not the Blender exporter.

Please include the file as well (you can put ZIP attachments in github comments). I'd also suggest testing on Blender 2.8 if you can.
