### ISSUE TITLE
Wrong transformations on export. 

### ISSUE THREAD

**Issue by ranqiz** [KhronosGroup/glTF#1616]
Hello, 

GLTF is not exported with the same transformations as in Blender. Transformations are always reset, to middle of the scene. This is a big issue when dealing with AR. If this isn't a bug, is there a solution to export with good transformations? 

What I've tested: 
Parenting to empty, changing bounding box by adding ground plane, changing pivot point, combination with transforming on Y axis (was thinking this maybe will somehow work because GLTF is Y up), basically I've tested every scenario, and the file ALWAYS stays the same. Not moved a bit.

**Comment by donmccurdy** [comment]
Could you open a bug on the exporter (https://github.com/KhronosGroup/glTF-Blender-IO) and include the `.blend` file to reproduce the problem? This repository is for the file format itself, not the Blender exporter.
