### ISSUE TITLE
3DS Export issues / 2020 update?

### ISSUE THREAD

**Issue by CMatthewsSRG** [KhronosGroup/glTF#1626]
1 - When I am exporting from max (2019) in the format of GLTF, the file type when dragged into the sandbox viewer gives me an error "Failed to load". However when I export and run the file loads. Not sure what is happening here. The textures also seem to not load even though the pathing is nested in the same folder as the GLTF file from Max. 

2 - Max is updating to 2020 and will there be a 2020 release for this exporter? I did drag in the 2019 to test if it runs and it does load up to the execution of export but then fails.

**Comment by donmccurdy** [comment]
What 3DS Max exporter are you using? This repository is for the glTF file format itself, I think you might be looking for the BabylonJS 3DS Max exporter here: https://github.com/BabylonJS/Exporters

**Comment by Drigax** [comment]
Hi @CMatthewsSRG, I currently maintain the Babylon.JS 3dsMax exporter, If you have any issues, feel free to contact us on our forum: www.forum.babylonjs.com or open an issue on the BabylonJS/Exporters repo.

There is currently someone working on a 2020 version of the exporter, but we're currently running into a bug in 3dsMax 2020 and are blocked until that is resolved. Also feel free to check https://github.com/BabylonJS/Exporters/issues/534 for progress on this issue as well.
