### ISSUE TITLE
extension mechanism

### ISSUE THREAD

**Issue by jjcasmar** [KhronosGroup/glTF#1628]
glTF says that any glTF object can have an extension property. 
I understand that we can do something like 
```
"nodes": [
{"extensions": ...
]
```
but can we do something like this?
```
"materials": [
{"pbrMetallicRoughness": {
   "extensions": [...]
}
]
```
?

**Comment by emackey** [comment]
Yes.  `pbrMetallicRoughness`, like all non-root glTF objects, inherits from `glTFProperty`.

https://github.com/KhronosGroup/glTF/blob/536951550759057da9ea6376e5b8f4a0a6311580/specification/2.0/schema/material.pbrMetallicRoughness.schema.json#L6

In [glTFProperty.schema.json](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/glTFProperty.schema.json), `extras` and `extensions` are defined.

If you haven't already, please register a [prefix](https://github.com/KhronosGroup/glTF/blob/master/extensions/Prefixes.md) for your organization's extensions.
