### ISSUE TITLE
Mention Discontinuous Animation in Spec?

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/glTF#1635]
I don't see any mention of supporting discontinuous animation in the spec. The spec supports it implicitly. Should it be explicit to make it clear that viewers and tools should expect it?

Discontinuous animation is supported implicitly by having 2 inputs with the same times.

```
Inputs:  0, 10, 10, 20
Outputs: 5,  5,  7,  7
```
will output 5 from t=0 to t=10 and instantly jump to 7 and stay 7 from t=10 to t=20. There is no distance between the 2 inputs with 10 so there is nothing between them. No possibility that there is a bad interpolation between 5 and 7.

This is important for teleporting, bouncing, uv animation, etc....

I see references to using sampling on animation and that's fine but any sampler needs to recognize when an animation is discontinuous and put the appropriate keys or whatever in the data and viewers/loaders need to be aware that consecutive keys might have the same inputs. That makes it seem like maybe the issue should be mentioned in the spec?

As a reference [Granny3D](http://www.radgametools.com/granny/sdk.html) makes explicit mention of support of discontinuous curves.

**Comment by scurest** [comment]
The spec currently explicitly disallows that. From [Properties Reference > animation sampler.input](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#animation-samplerinput-white_check_mark)

> The values represent time in seconds with `time[0] >= 0.0`, and strictly increasing values, i.e., `time[n + 1] > time[n]`.

There was discussion in #704 (in particular https://github.com/KhronosGroup/glTF/issues/704#issuecomment-246209647).

**Comment by greggman** [comment]
Oh, I see. So glTF is not useful for discontinuous animations which are common and required for many animations. Good to know. I'll use some other format.
