### ISSUE TITLE
How to Import gltf/glb into unity if it requires a custom extension (e.g "KHR_materials_pbrSpecularGlossiness")

### ISSUE THREAD

**Issue by khizerawan** [KhronosGroup/glTF#1636]
I am Using MRTK's GltfUtility (a gltf file loader from microsoft mixed reality toolkit) to import gltf/gb files at runtime. gltf and glb Files are being loaded without any problem, but when it comes to a glb file which requires an extension, that MRTK file loader fails. and logs a message - > ("Required Extension Unsupported: KHR_materials_pbrSpecularGlossiness")
and i have no clue how to add that extension, or Even does that importer do supports extensions or not???

i am sorry if this is the wrong place to ask this question, but i couldnt find any support page which clearly defines this kind of issues.

I have found the git of that extension.... but my problem is this is my first time to work with gltf/glb. and I have never dived much into structure of 3D files.
I am a bit confused, that do i really need to write some code in unity script or i need to change something/property in the gltf json file....!!!!

**Comment by bghgary** [comment]
Probably makes the most sense to ask here: https://github.com/microsoft/MixedRealityToolkit-Unity/issues.

The MixedRealityToolkit probably doesn't support the spec/gloss extension as the error message suggests. Looking at the [code](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/9ab0e9b69afe45f7856b5731436ae427c3fe7cc4/Assets/MixedRealityToolkit/Utilities/Gltf/Serialization/GltfUtility.cs#L167), it doesn't look like any extension is supported.
