### ISSUE TITLE
Clarify color space for vertex colors

### ISSUE THREAD

**Issue by vilya** [KhronosGroup/glTF#1638]
I think the spec needs some clarification about whether per-vertex colors are required to be linear or sRGB values.

There is a line in the "Metallic-Roughness Material" section of the spec which says

> In addition to the material properties, if a primitive specifies a vertex color using the attribute semantic property COLOR_0, then this value acts as an additional linear multiplier to baseColor.

which implies that the color values are supposed to be linear, but linear could also have other meanings in this context. Then there's also the line in the "Coordinate System and Units" section that says

> RGB color values use sRGB color primaries.

which seems to imply that vertex colors should actually be sRGB instead.

If vertex colors are indeed supposed to be linear, then perhaps the wording in the spec should be changed to something like:

"In addition to the material properties, if a primitive specifies a vertex color using the attribute semantic property COLOR_0, then this value acts as an additional multiplier to baseColor. The vertex colors are required to be stored as linear values and do not require conversion from sRGB."

**Comment by emackey** [comment]
Vertex colors are linear, not sRGB.

> > RGB color values use sRGB color primaries.
> 
> which seems to imply that vertex colors should actually be sRGB instead.

No, this is talking about colorspace reproductions, not linear/sRGB transfer functions.  There's a long discussion of this in https://github.com/KhronosGroup/glTF/pull/1606#discussion_r281733808, but it seems it's still a possible source of confusion.

**Comment by vilya** [comment]
Thanks for the clarification @emackey. For me at least I didn't read "linear multiplier" as meaning the vertex colors were linear, I took it to mean that the multiplication was linear (as opposed to polynomial or exponential, I guess?). 

Sketchfab's glTF exporter gets this wrong (it writes out vertex colors in linear or sRGB, depending on a per-model setting) so it seems I'm not the only one to be confused by the wording.

**Comment by atteneder** [comment]
Interesting decision though. A little remark:

To me it's out of question that calculations have to be done in linear space.

But sRGB does a better job at storing colors perceptually uniform, especially at limited bit depth like UNSIGNED_BYTE ( here's a great, interactive explanation of this https://ciechanow.ski/color-spaces )

Of course, converting color space at run-time, prior to uploading the colors to the GPU (or even converting them in the shader) is not not a good idea.

So i guess if you want to have precise vertex colors, export them as FLOAT or at least UNSIGNED_SHORT.

**Comment by lexaknyazev** [comment]
@atteneder 
Ideally, we'd have an sRGB vertex format that would perform hardware sRGB decoding from `uint8` on the GPU prior to vertex shader stage (like sRGB texture formats) but it's not the case.

On the other hand, there's no practical reason to use sRGB curve with `uint16` or `float32` data types because even with linear encoding `uint16` gives better precision than `uint8` with sRGB. Since the vertex color attribute can be either of these types, an engine would need to have different code paths depending on the attribute type.

So your conclusion is correct: when `uint8` linear is not enough, `uint16` or `float32` should be used for vertex colors.

**Comment by atteneder** [comment]
@lexaknyazev Thanks for the insight!
Yeah, a good compromise that makes (implementing) glTF easier.

**Comment by vilya** [comment]
Just to be clear, I wasn't arguing that vertex colours should be in sRGB. I just think the wording in the spec should make it clearer that they're linear. 

If people do actually want to be able to store vertex colours in sRGB, for whatever reason, then I guess a glTF extension would be the right way to do it.

**Comment by zeux** [comment]
Note that when vertex colors are stored as 8-bit, sRGB is going to be substantially more efficient at using the available precision for encoding with small perceptual error. I intuitively expected vertex colors to be in sRGB space just like texture contents for base_color texture is.

**Comment by garyo** [comment]
I'm a bit confused. If I have a uniformly colored object with a material base color `C`, glTF interprets `C` as sRGB and uses it to color the object. Similarly if I have a white object and a texture for it that has the same sRGB color `C`, the object will look the same.
Now if I have that white object with no texture, and apply the _linear_ version of that color, `C_linear = C.convertSRGBToLinear()` as the vertex color of all vertices, I believe the claim is that the object will still look the same ("Vertex colors are linear, not sRGB"). But if, as the spec says,

> this value acts as an additional linear multiplier to baseColor.

I don't see how this could work. `C_linear` will be multiplied by white, giving `C_linear` for the final base color. The object will come out darker. Where is the fault in my reasoning?

**Comment by donmccurdy** [comment]
@garyo Maybe this illustration helps — all colors must be linear when you use them in the shader program. Both `baseColorFactor` and the `COLOR_0` vertex attribute are already linear in the glTF file, but `baseColorTexture` is not and needs to be converted.

![IMG_0152](https://user-images.githubusercontent.com/1848368/89361203-8348d300-d67f-11ea-8f9e-26a7000cc187.jpeg)

Having determined the combined base color in the shader (and done the rest of the PBR lighting), the result is typically converted back to sRGB and displayed on screen.

> If I have a uniformly colored object with a material base color C, glTF interprets C as sRGB and uses it to color the object.

If you're referring to a constant base color on the material (i.e. `baseColorFactor`, then no, it would be interpreted as linear. It's worth noting that when you choose a color like `#428098` in Blender or other artist-friendly software, for a material color or a vertex color, it's automatically going to convert those to linear values when writing the glTF file.

**Comment by garyo** [comment]
Thanks, that is super helpful! That diagram should be in the spec! :-) Based on that, the spec _ought_ to say:

> this value acts as an additional linear multiplier to the linearized baseColor.

And as for the material base color, I was actually thinking of a color as passed into three.js:
```
  THREE.MeshBasicMaterial({ color: "#fd0855"})
```
which hopefully gets interpreted as sRGB, but then (as you point out) linearized during the glTF export.
(But now I'm double-thinking myself -- in three.js if I have renderer.outputEncoding set to THREE.sRGBEncoding, should I be converting that material color to linear? OK, off topic for this issue.)

**Comment by donmccurdy** [comment]
> I was actually thinking of a color as passed into three.js ... which hopefully gets interpreted as sRGB...

Unfortunately not, you would need to convert it with `convertLinearToSRGB` if you want it to match `#fd0855` in your CSS. Happy to discuss that more in https://discourse.threejs.org/t/when-exporting-to-gltf-what-color-space-is-used-for-vertex-colors/17642. It is handled correctly coming from a glTF file, but requires some care when creating the materials yourself.

**Comment by termhn** [comment]
> Of course, converting color space at run-time, prior to uploading the colors to the GPU (or even converting them in the shader) is not not a good idea.

> Ideally, we'd have an sRGB vertex format that would perform hardware sRGB decoding from uint8 on the GPU prior to vertex shader stage (like sRGB texture formats) but it's not the case.

> On the other hand, there's no practical reason to use sRGB curve with uint16 or float32 data types because even with linear encoding uint16 gives better precision than uint8 with sRGB. Since the vertex color attribute can be either of these types, an engine would need to have different code paths depending on the attribute type.

@atteneder @lexaknyazev 

These seem like very odd conclusions to me. A software implementation of the sRGB EOTF (i.e. srgb to linear) is a complete nonissue performance wise, but the extra GPU memory needed for float32 vertex colors over uint8 vertex colors could absolutely be an issue if you are trying to do a high polygon/vertex count model with vertex colors (also for keeping asset sizes down). Surely sRGB just makes much more sense here in all cases?

**Comment by atteneder** [comment]
@termhn Granted, avoiding sRGB EOTF might be premature optimization (I didn't do benchmarks). If it's negligible (performance is not an issue), but memory is short, you got a good point.

The problem is, it's already ratified this way. I presume that adding an sRGB vertex color format would mean changing/complement the specification (or create an extension). That means more implementation work and (for some platforms) more shader variants/complexity. I get your point. I'm just not sure if the benefits justify the changes.

**Comment by donmccurdy** [comment]
There's also a question of established tools here: 3D engines I'm familiar with expect vertex colors to be linear, and have no option to change that, other than writing a custom shader. Not all can compile custom materials at runtime.

An option used by optimization tools like gltfpack, gltf-pipeline, or gltf-transform — mainly for keeping asset sizes small on the web —  would be to store vertex colors in uint16 attributes quantized to 11-12 bits. That's still 16-bits per component in GPU memory of course, but the asset will compress further with gzip for transmission.

**Comment by lexaknyazev** [comment]
The spec language around `COLOR_0` attribute usage has been updated. sRGB-encoded vertex colors would require an extension.

**Comment by katSchmid** [comment]
Does baseColorFactor have a default?

**Comment by javagl** [comment]
See https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#reference-material-pbrmetallicroughness : Yes, `[1,1,1,1]`
