### ISSUE TITLE
Normal and tangent vectors must be orthogonal?

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF#1639]
Does the spec clarify that `NORMAL` and `TANGENT` vectors must be orthogonal?  And does the validator test for this?

Related, there is a question about zero-length tangents in #1461, and it's not clear to me that the spec actually calls for the `xyz` components of the tangent vector to be normalized.  We may need to clarify that those components must be normalized and must be orthogonal to the supplied normal vector (even in case of custom normal vectors that don't exactly match the geometry).

For example, [this sample code](https://github.com/KhronosGroup/glTF-Sample-Viewer/blob/341fd8f907cf49ff2f3662746c7586043628cf0d/src/shaders/primitive.vert#L104-L106) will produce a non-normalized bitangent if the two vectors are not exactly orthogonal.

```
    vec3 normalW = normalize(vec3(u_NormalMatrix * vec4(getNormal().xyz, 0.0)));
    vec3 tangentW = normalize(vec3(u_ModelMatrix * vec4(tangent.xyz, 0.0)));
    vec3 bitangentW = cross(normalW, tangentW) * tangent.w;
    v_TBN = mat3(tangentW, bitangentW, normalW);
```

This is following a glTF Slack conversation with @vpenades.

**Comment by vpenades** [comment]
I believe that the only way to guarantee orthogonal normal and tangent vectors at the pixel shader, is to ensure that the normal and tangents fed to the vertex shader are orthogonal and unit length.

For example, if you have a tangent of unit length at one vertex, and a half length tangent at another vertex, it doesn't matter if the tangent and normal are orthogonal in the vertex shader.... the pixel shader interpolation will probably skew the vectors, so after re-normalization in the pixel shader, they will no longer be orthogonal.

**Comment by scurest** [comment]
If morph targets are being used, even if the normals and tangents stored in each individual target are orthogonal, the final blended normal and tangent won't usually be.

**Comment by emackey** [comment]
Sounds like implementations need to take care of renormalizing as needed.  That can be an implementation detail, and the spec will get tightened just for the glTF data in #2047.
