### ISSUE TITLE
proposal for morph & interaction with skin

### ISSUE THREAD

**Issue by fabrobinet** [KhronosGroup/glTF#164]
over to Tony

**Comment by emilian0** [comment]
Is this a good example of a node instantiating a morph with skinning ?
```
"luckyNode": {
  "children": [],
  "morphs": ["myFirstMorph"] ,
  "skeletons": ["skeleton-root_1"],
  "skin": "skin_1"
}
```
I agree with Tony on that we can assume the morph to be applied first followed by the skinning. 
I am not sure about the value of allowing these operations to be reordered.

**Comment by pjcozzi** [comment]
Updated in #826
