### ISSUE TITLE
Animation sampler Input & output matching sizes (and possible bug in InterpolationTest Sample)

### ISSUE THREAD

**Issue by YTN0** [KhronosGroup/glTF#1644]
Am new to this, so forgive me if this is a stupid question... I am in the midst of trying to write a GLTF loader / renderer. I currently have the absolute basics working, and am working on implementing animations. 

I have simple animations working which supports step and linear interpolation. I have not implemented cubic spline yet.

I have been testing using the InterpolationTest sample which is uploaded to github viz.

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/InterpolationTest

I am running into an issue with the Linear Scale test. The sampler outputs don't match the inputs viz. there are 5 inputs and 15 outputs. 

Unless I am reading the spec wrong, the outputs should match the inputs for linear and step. I believe outputs are only different for cubic spline (which I haven't gotten into yet).

From debugging and looking at the json version of the file, it looks like the linear scale animation is actually set in the file as CUBICSPLINE and not LINEAR.

Could someone please validate my assumptions viz. inputs and outputs should match for step and linear and that there is a bug in the InterpolationTest sample for the Linear Scale animation?

Thanks!

**Comment by emackey** [comment]
Hi @YTN0,

The `Scale` animations supply values for `x`, `y`, and `z` separately.  That's why you're seeing three output values there.

For "CubicSpline Scale", you'll actually find nine values per keyframe.  These are ordered `in x`, `in y`, `in z`, `x`, `y`, `z`, `out x`, `out y`, `out z`.

**Comment by emackey** [comment]
I closed the issue but let us know if you have more questions.  Thanks.

**Comment by kevinmoran** [comment]
Hi there! Can I ask, what is the format of the tangents for cubic spline samples? For example, here's a translation sample I came across when playing around with loading a GLTF file:
```
[-0.029064, 0.052901, 0.000000] // in-tangent
[2.571981, 1.267634, 0.018146] // keyframe translation value
[-0.029064, 0.052901, 0.000000] // out-tangent
```
As you can see, the two tangents are identical, so it's unclear how to calculate bezier control points from this. Do I subtract the in-tangent and add the out-tangent? Giving:
```
[2.601045,1.214733, 0.018146] // in-control-point
[2.571981, 1.267634, 0.018146] // keyframe translation value
[-2.542917, 1.320535, 0.018146] // out-control-point
```
Thanks!

**Comment by emackey** [comment]
@kevinmoran The glTF Tutorials are probably the best resource on that:

https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_007_Animations.md#cubic-spline-interplation

**Comment by kevinmoran** [comment]
@emackey Brilliant, thanks so much for the quick answer. I should have gone through the tutorials in detail, I will do now!
