### ISSUE TITLE
The evaluation order of skinning and morph targets

### ISSUE THREAD

**Issue by syoyo** [KhronosGroup/glTF#1646]
Is there an explicit definition of the evaluation order of skinning and morph targets when the glTF model contain both information?(e.g. skinning then morph, morph then skinning). 

I have glimpsed the specification but couldn't find an explicit description of the evaluation order of skinning and morph.

An expected behavior may be morph then skinning, but sometimes we want skinning then morph for corrective blendshapes https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2018/ENU/Maya-CharacterAnimation/files/GUID-B8755F24-7C24-4066-B6F8-2DE6954DC2BF-htm.html

**Comment by donmccurdy** [comment]
I know that threejs applies morph before skinning, but don't think the specification mentions this, and it probably should.

> ... but sometimes we want skinning then morph for corrective blendshapes

Unfortunately I don't think there is much ability in engines for toggling this ordering around, so an option in the spec would be pretty much unsupported.

**Comment by meshula** [comment]
Morph / skin / corrective is also desirable, from an art perspective...

**Comment by donmccurdy** [comment]
I won't argue they couldn't be desirable, but does anything that isn't a DCC tool support them? Search results don't seem promising on [Unity](https://forum.unity.com/threads/corrective-blendshapes-in-unity.625468/) or [Unreal](https://answers.unrealengine.com/questions/662260/how-do-you-set-up-corrective-morphs.html), and I don't think we can justify adding features that only DCC tools support.

**Comment by syoyo** [comment]
> I know that threejs applies morph before skinning,

@donmccurdy Thanks! So at least we are better to send PR to mention the ordering of `skin` and `morph` evaluation order.

> Search results don't seem promising on Unity or Unreal 

Hmm...  it needs more detailed design discussion how glTF-next will support complex animation/rigging system if we want to support it as an glTF standard...
(Probably we'll need to introduce modifier stack feature)

For a while, I am planning to use glTF extension to specify the ordering of morph and skin to support skinning-before-morph feature.

**Comment by meshula** [comment]
It might only exist in bespoke AAA engines? Certainly we did morph/skin/corrective in ours. I would argue that Unity and Unreal as an Occam's razor is overly restrictive. At the same time, I appreciate that if other gamedevs don't speak up there's no proof that anyone besides a few high end studios need it. So I'm raising a hand.

**Comment by donmccurdy** [comment]
Yes, I certainly don't mean to say Unity and Unreal must have a feature for glTF to support it. But as a general philosophy I would want to see bespoke features use vendor or EXT_ extensions, rather than going directly in the glTF spec or a KHR_ extension, for long-term simplicity of the format. If a feature becomes widely portable at a later date, it can always be brought into the format then.

**Comment by bghgary** [comment]
We have been talking about this on the WG calls. The way it works in Babylon.js, morph targets change the vertex positions, normals, etc. while skinning changes the world matrix. The updated world matrix then is applied to the updated vertex positions, normals, etc. The order doesn't matter in this case.

@meshula @syoyo Can you give more details on how the order can affect the result?

**Comment by UX3D-nopper** [comment]
Actually, it depends which morphing data we do store in glTF:
- T-Pose, A-Pose etc.
- Acting pose

Think we do need to clarify this in glTF. Then, we can also clarify the calculation order.

**Comment by syoyo** [comment]
>  morph targets change the vertex positions, normals, etc. while skinning changes the world matrix. 

I see. 

> Actually, it depends which morphing data we do store in glTF:
> T-Pose, A-Pose etc.
> Acting pose

We need to clearify that morph data should be stored in their `local` space(or `rest` pose. i.e. before the skinning was applied) in glTF.

**Comment by meshula** [comment]
@bghgary Two examples might help to illustrate order. (1) PRE: A piece of clothing might be morphed to shape it to a character, against the rest pose. The morphed shape is skinned into the character's animated pose. (2) POST: A character has problematic geometry due to unusually shaped shoulders. There's no amount of skin-weighting that gives the artist control over the deformation of certain vertices near the shoulder in a particular dramatic pose. The artist poses the character in this dramatic pose, and sculpts the vertices to look good, and this corrective shape is blended in whenever the dramatic pose is reached.

**Comment by bghgary** [comment]
I understand there is a conceptual difference from a DCC tool perspective, but I'm struggling to find a difference in the runtime/shader/math. It would be great if someone can provide some concrete examples with source from a DCC tool.

**Comment by meshula** [comment]
It's runtime as well, if you've created shapes using a workflow like this, and want to use them as the artist created them, http://help.autodesk.com/view/MAYAUL/2016/ENU/?guid=GUID-B8755F24-7C24-4066-B6F8-2DE6954DC2BF you are going to need to apply them post skinning. The shapes are simply stored as a delta versus the skinned vertices, so the values in the shape are just added to skinned result. Nothing fancy. Correctives can be added on correctives, but that is not nearly as common.

**Comment by bhouston** [comment]
We discussed this on the call today.

Currently glTF stores morph targets as deltas/offsets in object space (object space delta morph targets):

https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_018_MorphTargets.md

These object space delta morph targets must be applied to the stored mesh positions prior to skinning.  These resulting new positions are then deformed using the bone matrices and then blended together to get the final positions.

If you want to apply morphs after skinning, you need to convert the object space delta morphs from object space into tangent space.  This tangent space will deform based on the skinning operation and thus you when you add in the morphs in the tangent space it will be applied properly.

It is straight forward to convert tangent space to object space delta morph targets and vice versa.  You just need to compute your tangent space for the mesh in question and then do the conversion.

Summary:

Object space delta morph targets
- What is currently stored in glTF
- must be applied prior to skinning.

Tangent space delta morph targets
- Can be calculated from object space delta morph targets.
- Can be applied before or after skinning
- Often called corrective morph targets

**Comment by syoyo** [comment]
@bhouston Thanks!

 > Currently glTF stores morph targets as deltas/offsets in object space (object space delta morph targets):

So at least we are better to describe this(object space delta) in glTF 2.0 spec. Then, additionally, we can describe tangent space delta morph targets for post-skinning blendshapes.

> NOTE: One need to be clear what defines the tangent space. A simple position mesh by itself does not fully define a unique tangent space I believe.

glTF Mesh has `TANGENT` attribute https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#meshes 

For tangent space delta mesh morph, we can use this attribute.

**Comment by lexaknyazev** [comment]
@syoyo 
`POSITION`, `NORMAL`, and `TANGENT` attributes are all used for object-space deltas.

Tangent-space deltas would require either a new set of attributes, or a flag that would repurpose those existing attributes.

**Comment by bhouston** [comment]
@lexaknyazev I believe @syoyo is referring to the fact that tangents on the base mesh definition can be used to the define the tangent space in which the tangent space delta morph targets would lie.

Tangent space delta morphs must have a tangent space definition on the original mesh, but not on the morphs themselves.

The morphs themselves, while they need to be defined in tangent space, only really require delta position & normal, not necessarily a tangent for each morph target.

I actually haven't encountered having tangents or UVs in each morph target before.  I've only encountered positions/delta positions and normals per morph target.  I know it is theoretically possible to morph tangents and UVs in addition to just position and normals, I just haven't seen it.  I am unsure if other file transfer formats support this.

**Comment by bghgary** [comment]
@bhouston It seems like you have more knowledge on this. Will you be comfortable opening a PR adding an implementation note or perhaps even a normative section to the spec?
