### ISSUE TITLE
[Help]: Animation

### ISSUE THREAD

**Issue by andre-ferreira** [KhronosGroup/glTF#1647]
Hello,

So i have read the tutorial pages about skinning and animation and i understand what i have to do to parse the gltf file. What is not clear to me is what needs to be calculated at runtime and what can be calculated at load.

Can i just at load create vector of joint matrices (one for each joint) for each key frame and then at runtime interpolate the poses between keyframes? Or do i need to recalculate everything at runtime, always going through the node hierarchy?

Many thanks.

**Comment by prideout** [comment]
At run time you need to apply the animation to the affected nodes, then traverse the transform hierarchy in order to recompute the joint matrices.

Ordinarily you wouldn't bake the matrices at load time since individual animations can typically be toggled on or off.
