### ISSUE TITLE
EXT_lights_image_based: what's the color space of the specularImages

### ISSUE THREAD

**Issue by 06wj** [KhronosGroup/glTF#1648]
sRGB or linear colorspace?

link:[EXT_lights_image_based](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Vendor/EXT_lights_image_based)

**Comment by bghgary** [comment]
I believe it is sRGB, but @MiiBond can confirm.

You might also consider looking at https://github.com/KhronosGroup/glTF/pull/1612 which has a proposed KHR extension for IBL.

**Comment by MiiBond** [comment]
Should be linear values, packed as RGBD.

**Comment by 06wj** [comment]
In the [example](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?category=tutorialModels&model=EnvironmentTest&scale=0.3&type=glTF-IBL) of BabylonJS, it's converting to linear space first.

```
vec3 fromRGBD(vec4 rgbd) {
    rgbd.rgb = toLinearSpace(rgbd.rgb);
    return rgbd.rgb/rgbd.a;
}
```

**Comment by bghgary** [comment]
Yes, I'm discussing with @MiiBond. Stay tuned.

**Comment by MiiBond** [comment]
Hey, sorry. I was mis-remembering this. Yeah, @bghgary is right. The RGB channels of the RGBD are sRGB-encoded. Not linear.

**Comment by 06wj** [comment]
Thanks for the response.

**Comment by emackey** [comment]
The readme for this extension doesn't mention sRGB that I can find.  Does it need an update?
