### ISSUE TITLE
Can orphaned nodes affect the transforms of shared meshes?

### ISSUE THREAD

**Issue by prideout** [KhronosGroup/glTF#1649]
We've seen glTF assets that define two parallel node hierarchies: one that is rooted into a scene, and one that does not belong to a scene.  They both contain references to a single set of meshes.  It appears that Cinema4D is exporting assets in this way to separate an "animation hierarchy" from a "modeling hierarchy".

More generally, if a given mesh is referenced by more than one node, does it take on the transform of all those nodes? In what order do the transforms compose together?

Somewhat related to #1358 and #1547.

**Comment by scurest** [comment]
Every node with a `mesh` property creates a new instance of the mesh with the transform of that node. A mesh itself doesn't have a transform.

**Comment by prideout** [comment]
Is it an error for a node to exist that is never referenced by any scene hierarchies?

**Comment by scurest** [comment]
No, there do not even have to be any scenes in a file.
