### ISSUE TITLE
Support for object / pivot transforms

### ISSUE THREAD

**Issue by rogersachan** [KhronosGroup/glTF#1650]
Object-only and pivot transforms are not supported (the latter can be implemented by hacks but not ideal). OpenGEX describes their implementation as the following:  "Node transforms are separated into distinct components, where one applies to the node and all of its child nodes, and the other applies only to the node's object, enabling local pivot transforms."

**Comment by donmccurdy** [comment]
I'm inclined to say that object-only and pivot transforms are much more appropriate for interchange formats (which OpenGEX and COLLADA are) than for a last-mile format like glTF. These features introduce significant complexity for the runtime implementation, and are likely to be sources of inconsistencies among implementations. See [last-mile vs interchange](http://nickporcino.com/posts/last_mile_interchange.html) for context here.

I would also call out the often-missed disclaimer at the top of the OpenGEX comparison:

> Note that although glTF is intended primarily to be a run-time format, whereas OpenGEX and Collada were designed primarily to be pipeline formats, it is included here because many people see glTF as a viable pipeline format.

glTF is, indeed, not presently intended to be a pipeline format.

I think this distinction may be relevant to https://github.com/KhronosGroup/glTF/issues/1654 and https://github.com/KhronosGroup/glTF/issues/1653 as well, so before I reply on those, is there a particular use case or workflow you are after, in which glTF needs these features?

*** 

Aside – The title of this issue doesn't seem to match the issue description, possible typo here?

**Comment by donmccurdy** [comment]
A bit more background. For several of these features...

- Object / pivot transforms
- Per-instance material binding
- Support for world specification

... the [Godot team has argued rather well](https://godotengine.org/article/small-defense-gltf) that the features are much more suitable for a pipeline format than for a runtime format.
