### ISSUE TITLE
Support for infinite, point, spot, and ambient light nodes

### ISSUE THREAD

**Issue by rogersachan** [KhronosGroup/glTF#1651]
If this is planned or eventually added, attenuation model support would be ideal as well with support for multiple attenuation functions. This is supported in collada but not in gLTF.

**Comment by donmccurdy** [comment]
Point, spot, and directional lights are provided by the [KHR_lights_punctual](https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_lights_punctual/README.md) extension to glTF 2.0.

The goals of glTF are significantly different from those of COLLADA, and supporting everything COLLADA supports is a definite non-goal. Unfortunately I don't think multiple attenuation models would be portable enough to be consistently implemented across engines. We've omitted ambient lights intentionally, at least for now, to focus on more modern techniques like IBL and perhaps spherical harmonics for lighting, along with the analytical/punctual lights extension mentioned above.
