### ISSUE TITLE
Is the order of nodes in a scene strict?

### ISSUE THREAD

**Issue by ibozhilov** [KhronosGroup/glTF#1657]
We have the following scene:
`"scenes": [
    {
      "name": "Scene",
      "nodes": [
        0,
        1,
        3,
        6
      ]
    }
  ]`
Is it required for all clients to load the nodes in this specific order? Can we count on all the clients loading the nodes in the specified order? At the end is scenes[0].nodes[2] always node[3] in all clients?

**Comment by lexaknyazev** [comment]
`scenes[x].nodes` lists top-level nodes of a scene `x`. These numbers (0, 1, 3, 6 in the example above) refer to elements of the top-level `nodes` array.

The loading result should not depend on the order of `scenes[x].nodes`, i.e., `"scenes": [ { "name": "Scene", "nodes": [ 1, 0, 6, 3 ] } ]` should yield the same result.

**Comment by donmccurdy** [comment]
> At the end is scenes[0].nodes[2] always node[3] in all clients?

No, I would not assume that the hierarchy in the glTF file will exactly match the node hierarchy created by the client – if you need a unique identifier on a node, it is best to assign that node a unique name. A client may decide to change the hierarchy in various ways – adding a root node to handle orientation changes, treating primitives as a single object or splitting them into multiple objects, and so on.

> The loading result should not depend on the order of scenes[x].nodes...

If the order of the nodes is a meaningful part of "the loading result" for someone's use case, then it does depend on the order of the nodes in the glTF file. While I doubt any tools are intentionally resorting nodes, there are reasons the structure may come out different (see above). For identifying particular objects or ordering, it would be better to use node names or extras, e.g. you might assign `node.extras.sortOrder = 4` if that's something your application needs.

**Comment by ibozhilov** [comment]
Thanks. I understand.
