### ISSUE TITLE
KHR_draco_mesh_compression question?

### ISSUE THREAD

**Issue by 461316334** [KhronosGroup/glTF#1661]
```json
"mesh" : {
    "primitives" : [
        {
            "attributes" : {
                "POSITION" : 11,
                "NORMAL" : 12,
                "TEXCOORD_0" : 13,
                "WEIGHTS_0" : 14,
                "JOINTS_0" : 15
            },
            "indices" : 10,
            "mode" : 4,
            "extensions" : {
                "KHR_draco_mesh_compression" : {
                    "bufferView" : 5,
                    "attributes" : {
                        "POSITION" : 0,
                        "NORMAL" : 1,
                        "TEXCOORD_0" : 2,
                        "WEIGHTS_0" : 3,
                        "JOINTS_0" : 4
                    }
                }
            }
        }
    ]
}
```

like the code before, what is the number mean in the path  `mesh.primitives[0].extensions.KHR_draco_mesh_compression.attributes.POSITION` etc.

**Comment by lexaknyazev** [comment]
These are indices of accessor objects from the top-level `accessors` array. They can be used for initializing graphics pipeline (like creating VAOs) before the decompressed data is available.

**Comment by 461316334** [comment]
do you mean that its useless after i have the decompressed data?

**Comment by lexaknyazev** [comment]
It depends on the overall engine design. For example, position accessor still have min/max values that can be used for simple bounding boxes.

**Comment by 461316334** [comment]
as your word, its harmless to change the order 01234 to 43210 if i also change the order of accessor .but the threejs canot load the file that i have changed.

**Comment by donmccurdy** [comment]
Unlike `primitive.attributes.*`, the integers in `KHR_draco_mesh_compression.attributes.*` are not accessor indices – they are unique IDs of the attributes stored in the Draco-compressed buffer. They cannot be changed without recompressing that buffer.

**Comment by lexaknyazev** [comment]
Oops. I forgot that compressed meshes have two sets of "attribute-to-index" mappings. Only those that are in the core  `mesh.primitives[].attributes` refer to accessors.
