### ISSUE TITLE
Quantized geometry support

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/glTF#1670]
Today glTF doesn't support non-floating point attributes in geometry accessors with very few exceptions. To reduce the size of glTF assets, it's very useful to use quantized attributes - for example, normalized 8-bit storage for normals, or 16-bit storage for position and UV data.

I'm the author of [gltfpack](http://meshoptimizer.org/#gltfpack), which can produce optimized glTF files that rely on two, currently unspecified, features:

- quantized geometry (16-bit positions/texture coordinates, 8-bit or 16-bit normals/tangents, 8-bit joint weights)
- attribute/index compression (this is implemented in a general fashion as bufferView compression so it allows to support both geometry and animation compression in a general way without altering the structure of glTF file like Draco does)

In this issue I'd like to discuss the standardization of support for quantized geometry. Specifically what I'd like to do is to draft an extension that:

1. Relaxes the restrictions on geometry attributes to allow the full set (8/16 bit with or without normalization) of component types for positions and texture coordinates, and allow 8/16 bit normalized component types for normals and tangents.
2. Relaxes the restriction on normals/tangents to not require the length of 1 - quantization introduce an error in the encoding which makes attaining length of 1 impossible

While texture coordinates today already support 8/16-bit normalized storage, I'd like to propose allowing unnormalized storage as well, and maybe signed storage. This allows to represent texture coordinates outside of the 0..1 normalized range, which is important for some models.

Unlike existing WEB3D_quantized_attributes (for glTF 1.0), I am not intending to propose *any* extra JSON attributes - it's *just* about unlocking the use of extra types. This is because you can already get most of the benefit of quantization with existing matrix transforms; while there are some restrictions (for example, for geometry storage this effectively limits the dequant matrix to have a uniform scale because non-uniform scale would distort the normal direction), this makes support of this extension trivial.

In fact, three.JS and Babylon JS already "de facto" support this extension in that they already handle all possible component types for geometry attributes correctly - so official support would be as easy as officially marking this extension as supported with no further code changes.

Finally, there's the question of namespacing the extension. There's two possibilities - putting the extension in MESHOPT_ namespace (MESHOPT_quantized_geometry) or KHR (KHR_quantized_geometry). I would like to propose going the KHR route directly because of how simple the extension is and how core this feature is (it has nothing to do with meshoptimizer/gltfpack other than gltfpack relying on its existence).

I would like to draft the extension but first I wanted to gather feedback on the proposed route to not spend too much time iterating on the extension draft if some of the suggestions just don't make sense. Once I get a sense of the general support of this direction or necessary alterations I'm happy to submit a PR with the extension text.

**Comment by zeux** [comment]
Worth noting is that the motivation behind quantized attributes is twofold:

- Reducing the transmission size
- Reducing the size in GPU memory

So the optimally behaving loaders would preserve the quantized attribute streams all the way throughout the pipeline, like three.JS and Babylon.JS mostly do, but loaders are always free to decode the streams into float32 buffers if that's easier.

As a strawman, a basic PBR-compatible asset needs a position, normal, tangent, and a texture coordinate. A full float32 encoding uses 12 bytes for position, 12 bytes for normal, 16 bytes for tangent and 8 bytes for UV. glTF today *only* allows to compress UV data to 4 bytes (16-bit normalized unsigned int; 8-bit is impractical for UV generally), so the best you can do is 12+12+16+4 = 44 bytes per vertex.

With this proposal, you'd be able to use 8 bytes for position (including a 2-byte padding required by glTF to keep streams 4b aligned), 4 bytes for normal, 4 bytes for tangent and 8 bytes for UV, for a total of 8+4+4+8 = 24 bytes per vertex, with minimal quality loss (in some cases you might want a 16 bit normal storage to keep reflection fidelity which would increase this to 28 bytes per vertex, assuming tangents are still fine at 8 bits which they usually are) - and the resulting asset would still be entirely compatible with WebGL1 restrictions on vertex input attributes.

**Comment by lexaknyazev** [comment]
Couple comments.

1. "Unlocking" additional vertex attribute types means that backwards-compatible fallback is not possible. This means that the suggested extension must always be present in the asset's `extensionsRequired` array. For the expected workflow (`gltfpack` output for immediate rendering) this might work, though.

2. Using node's translation and scale as quantization params means that the quantized mesh cannot be easily reused in other nodes without copying the transforms. This also will be an issue for skinned meshes since they ignore local node transforms, so quantization params would need to be baked into joints. Again, this might work for the expected workflow but it would likely be an issue for DCC importers.

**Comment by zeux** [comment]
> backwards-compatible fallback is not possible

Yes, that's correct. I think this is a reasonable restriction.

> quantized mesh cannot be easily reused in other nodes without copying the transforms

You can reuse the mesh, since you can use a separate node with the dequant transform (dequantization usually should be applied before all other transformations anyway).

For skinned meshes, the most convenient option is to bake the matrix into the joint bind matrices - you don't need to affect the joints themselves, which is convenient.

I'm not sure OTOH what would happen with the meshes during a DCC import process, but in a way all of this is somewhat similar to how DCC export/import tools handle coordinate system transforms - glTF doesn't have a first-class support for coordinate system specification and the way most tools deal with that is by adding extra root nodes with the relevant transformation; in this proposal, you'd get extra leaf nodes instead.

**Comment by zeux** [comment]
FWIW I tried importing a gltfpack-processed file and Blender 2.8 actually imports it; the normals seem to be discarded, presumably it expects a float32 encoded stream, but everything else is in tact, including joint bindings, and the scene is correctly displayed.
