### ISSUE TITLE
Mesh cameras?

### ISSUE THREAD

**Issue by Siccity** [KhronosGroup/glTF#1672]
Hello, i'm working on an importer for Unity [here](https://github.com/Siccity/GLTFUtility).

Just a small what-if:
How should I handle nodes that have specified both a camera and a mesh index? Does one precede the other? Do i construct a camera with a mesh? Is this valid?

**Comment by donmccurdy** [comment]
See https://github.com/KhronosGroup/glTF/issues/1433 — I would suggest thinking of this case as a node having a mesh and a camera as children, similar to:

```
- node1
  - node2
    - mesh
  - node3
    - camera
```

While assigning multiple references to a node is technically valid, it is not a use case I would encourage or particularly expect to see.

**Comment by Siccity** [comment]
Alright, thanks :)
