### ISSUE TITLE
How should implementations deal with index counts that don't match the primitive requirements

### ISSUE THREAD

**Issue by maapp** [KhronosGroup/glTF#1674]
The current specification doesn't mention the (recommended) behavior of implementations when encountering data which is not fit for rendering.

We got a glTF file from a customer which had an index buffer with 5 indices for a TRIANGLES primitive. First this caused actually crash in a third party loading library (we're following up there independently), but we then came to the question what the recommended way to handle this is.
Should we drop the last two indices? Should we drop the whole primitive?

Also (probably because it isn't specified) the glTF validator didn't emit an error or warning and declared the asset valid. I suspect that this might trip up other implementations and it would be good to get some clarification in the specification.

**Comment by lexaknyazev** [comment]
> Also (probably because it isn't specified) the glTF validator didn't emit an error or warning and declared the asset valid. 

Technically, warnings do not invalidate an asset. The validator issues a warning when the number of indices (or vertices when index buffer is not used) does not match declared primitive type.

Pasting the following glTF into VS Code yields:
> Number of vertices or indices (5) is not compatible with used drawing mode ('TRIANGLES').",

```json
{
    "asset": {
        "version": "2.0"
    },
    "accessors": [
        {
            "componentType": 5121,
            "type": "SCALAR",
            "count": 5
        },
        {
            "componentType": 5126,
            "type": "VEC3",
            "count": 10,
            "min": [0, 0, 0],
            "max": [1, 1, 1]
        }
    ],
    "meshes": [
        {
            "primitives": [
                {
                    "indices": 0,
                    "attributes": {
                        "POSITION": 1
                    }
                }
            ]
        }
    ]
}
```

Do you think that it should be an error?

**Comment by maapp** [comment]
I think it would warrant to be an error. Implementations need to post process / validate the given data to create sensible draw calls at all.

**Comment by zeux** [comment]
I feel like this should be clarified in the spec one way or the other. My preference would be to make it an error (retroactively breaking some scenes that are currently technically valid).

**Comment by JoshKlint** [comment]
If that happens, it's not a GLTF file, and there is nothing for the spec to say about it.

Depending on your application's usage you may want to allow some leniency. If it is a model converter I would be very liberal with the rules, but if it's an in-house engine I would be strict.

**Comment by emackey** [comment]
Quoting #1908:

> This clarification has been integrated into the new AsciiDoc version of the spec. Thanks!
