### ISSUE TITLE
misleading example for joint matrix usage in gltf overview

### ISSUE THREAD

**Issue by infobeisel** [KhronosGroup/glTF#1676]
the [gltf overview](https://raw.githubusercontent.com/KhronosGroup/glTF/master/specification/2.0/figures/gltfOverview-2.0.0b.png) in the section "Combining the joint matrices to create the skinning matrix" as well as the[ skinning example ](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_020_Skins.md#the-skinning-joints-and-weights) both suggest a reference implementation using OpenGL and glsl (it is not explicitly stated though). 

But accessing a uniform or shader storage buffer or array using vertex attributes as indices leads to unexpected behaviour in general, because the input data for the array access is not a dynamically uniform expression (i.e. can change within the invocation) as far as i understand. 
Coincidentally in the skinning example (second link) the joint indices are the same for all vertices, so in this case it could work, but that is not guaranteed.

Either these examples should be somehow adapted to work in general or deleted. I think it will lead to a lot of headache for graphics programmers.

**Comment by javagl** [comment]
Thanks for bringing this up. The overview is maintained in a different repo, let's continue the discussion there - I have opened https://github.com/javagl/gltfOverview/issues/10 for that.
