### ISSUE TITLE
Can extensions make required schema elements optional?

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/glTF#1680]
I'm trying to finalize some details in the JSON schema of a MESHOPT_compression (name TBD) extension before proposing it.

Briefly, the extension allows to use meshopt attribute/index compression on entire bufferViews. For each bufferView that uses the extension, it's necessary to specify the encoding mode (attribute or index), element stride & count, as well as the compressed buffer data (buffer/offset/length).

It's vital that this is specified per buffer view - this allows efficient loading of compressed data into GPU memory (each buffer view can be decompressed into the GPU memory directly), and keeps existing accessor structure identical so the integration into existing loaders is trivial (e.g. see https://github.com/zeux/meshoptimizer/blob/master/demo/babylon.MESHOPT_compression.js).

What I would like to do is to support two workflows:

1. Data is unconditionally compressed; loading the glTF file requires the extension support
2. Data is provided in both compressed and raw form; loaders that don't support the extension can load the raw data from a separate buffer

Right now my drafts only support 1. To support 1 and 2, I would need the JSON structure to look something like this for optional support (note that raw data is in buffer 0, compressed data is in buffer 1):

```json
{
  "buffer": 0,
  "byteLength": 8192,
  "byteOffset": 0,
  "byteStride": 8,
  "target": 34962,
  "extensions": {
    "MESHOPT_compression": {
      "mode": 0,
      "count": 1024,
      "byteStride": 8,
      "buffer": 1,
      "byteOffset": 0,
      "byteLength": 1248
    }
  }
}
```

and like this for required support (note missing `buffer` for raw data; compressed data is in buffer 0):

```json
{
  "byteLength": 8192,
  "byteStride": 8,
  "target": 34962,
  "extensions": {
    "MESHOPT_compression": {
      "mode": 0,
      "count": 1024,
      "byteStride": 8,
      "buffer": 0,
      "byteOffset": 0,
      "byteLength": 1248
    }
  }
}
```

However, glTF specification says that `buffer` in `bufferView` is required - so the second snippet is invalid. Is there a good way to resolve this?

**Comment by lexaknyazev** [comment]
It should be possible to define a dummy `buffer` object without `uri`.

**Comment by zeux** [comment]
Interesting - yeah, this seems to work. Thanks!
