### ISSUE TITLE
Help getting inverse bind matrices

### ISSUE THREAD

**Issue by carmineos** [KhronosGroup/glTF#1689]
Hi I am trying to understand how to correctly get the inverse bind matrices.
My current model loads fine without skin, nodes that should be joints are already transformed how they should be.
![blender_2019-10-22_17-49-37](https://user-images.githubusercontent.com/24431753/67308258-169e8680-f4fa-11e9-84fa-3c5bdc7701bb.png)

Once I add the skin, using either nothing either inverted matrix of the TRS I use for such nodes as inverse bind matrices, it looks like transformation is done twice
![blender_2019-10-22_17-39-02](https://user-images.githubusercontent.com/24431753/67308239-10100f00-f4fa-11e9-8de2-c3e9655e7cd3.png)
![blender_2019-10-22_17-38-35](https://user-images.githubusercontent.com/24431753/67308244-12726900-f4fa-11e9-82be-9c751d32e59f.png)

Could you help me understanding the correct inverse bind matrices I need?
*That ZupToYup node is just a root node I add at the end to the glTF since content is originally in Z-up

Btw, Slack invite link is no longer available

**Comment by javagl** [comment]
@carmineos  If you managed to resolve this issue on your own, a small hint about the reason for the issue (or how you resolved it) might be helpful for future readers.

**Comment by carmineos** [comment]
I got the global transform matrix as described [here](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_004_ScenesNodes.md#global-transforms-of-nodes)  and then i've just calculated the inverted.

```csharp
public Matrix GetGlobalTransform(Bone bone)
{
	List<Bone> hierarchy = new List<Bone>();
	var parent = bone.Parent;
	while (parent != null)
	{
		hierarchy.Add(parent);
		parent = parent.Parent;
	}

	hierarchy.Reverse();
	var matrix = Matrix.Identity;
	foreach (var b in hierarchy)
		matrix = matrix * Util.TRS(b.Translation, b.Rotation, b.Scale);

	matrix = matrix * Util.TRS(bone.Translation, bone.Rotation, bone.Scale);
	return matrix;
}
```

where TRS is described [here](https://forums.inovaestudios.com/t/math-combining-a-translation-rotation-and-scale-matrix-question-to-you-math-magicians/5194/2)
```csharp
public static Matrix TRS(Vector3 pos, Quaternion q, Vector3 s)
{
	Matrix result = new Matrix();
	// Rotation and Scale
	// Quaternion multiplication can be used to represent rotation. 
	// If a quaternion is represented by qw + i qx + j qy + k qz , then the equivalent matrix for rotation is (including scale):
	// Remarks: https://forums.inovaestudios.com/t/math-combining-a-translation-rotation-and-scale-matrix-question-to-you-math-magicians/5194/2
	double sqw = q.W * q.W;
	double sqx = q.X * q.X;
	double sqy = q.Y * q.Y;
	double sqz = q.Z * q.Z;
	result.M11 = (float)(1 - 2 * sqy - 2 * sqz) * (float)s.X;
	result.M12 = (float)(2 * q.X * q.Y - 2 * q.Z * q.W);
	result.M13 = (float)(2 * q.X * q.Z + 2 * q.Y * q.W);
	result.M21 = (float)(2 * q.X * q.Y + 2 * q.Z * q.W);
	result.M22 = (float)(1 - 2 * sqx - 2 * sqz) * (float)s.Y;
	result.M23 = (float)(2 * q.Y * q.Z - 2 * q.X * q.W);
	result.M31 = (float)(2 * q.X * q.Z - 2 * q.Y * q.W);
	result.M32 = (float)(2 * q.Y * q.Z + 2 * q.X * q.W);
	result.M33 = (float)(1 - 2 * sqx - 2 * sqy) * (float)s.Z;
	// Translation
	result.M14 = (float)pos.X;
	result.M24 = (float)pos.Y;
	result.M34 = (float)pos.Z;
	result.M44 = 1.0f;
	// Return result
	return result;
}
```
