### ISSUE TITLE
Khronos Slack invite is broken

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF#1690]
Filing a separate issue for a problem mentioned in #1689, we link to this page on our readme for Slack access...

https://www.khronos.org/news/permalink/khronos-developer-slack-5bfc62eb261764.20435008

... and the Slack link there no longer works.

**Comment by KhronosKris** [comment]
Hi @donmccurdy , this is resolved now. 

For the record, please always use www.khr.io/slack to invite others to the developer Slack. :)
