### ISSUE TITLE
Convert quaternion to matrix code?

### ISSUE THREAD

**Issue by JoshKlint** [KhronosGroup/glTF#1692]
I am having some trouble loading some models and want to make sure I am calculating rotation the same way GLTF does. Is there a standard bit of code somewhere that converts a GLTF quaternion to a 4x4 or 3x3 matrix?

**Comment by emackey** [comment]
Not sure if this helps, but:  [Cesium.Matrix3.fromQuaternion](https://github.com/AnalyticalGraphicsInc/cesium/blob/8cc27c83cf55a8533ce056f8047f7516d16447b3/Source/Core/Matrix3.js#L239)
