### ISSUE TITLE
Negative transformation scale

### ISSUE THREAD

**Issue by JoshKlint** [KhronosGroup/glTF#1697]
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#transformations

> Implementation Note: If the determinant of the transform is a negative value, the winding order of the mesh triangle faces should be reversed. This supports negative scales for mirroring geometry.

According to what I am reading, the indice order should be reversed if a node has a negative scale in its transformation. This makes little sense, as meshes can potentially be shared across different nodes, some of which may be reversed and some not. Face direction should be a per-mesh property, not a per-node property. Am I misunderstanding this?

**Comment by JoshKlint** [comment]
I think I get it. At some point someone was asked "what happens if the scale inverts the faces" and this was the answer. It is true that you could save some VRAM if you had a separate mesh object that included the triangle order and a "mesh data" object that was shared between meshes that contains the vertex arrays, but it seems like a really obscure optimization.

This is a design decision I disagree with, but at least the expected behavior is clearly explained.

**Comment by donmccurdy** [comment]
I think this implementation note should be removed. Negative scales will invert single-sided faces, and that's OK.

**Comment by bghgary** [comment]
This implementation note is there to support mirrored geometry. Both Unity and Unreal do this.

For the history, see https://github.com/KhronosGroup/glTF/pull/971#issuecomment-304392357 and the corresponding PR https://github.com/KhronosGroup/glTF/pull/985.

**Comment by JoshKlint** [comment]
Well, at least the correct behavior is explicitly stated. Thanks for the info.

**Comment by JoshKlint** [comment]
> I think this implementation note should be removed. Negative scales will invert single-sided faces, and that's OK.

Now that it's in, this is actually critical. I have encountered GLTF files that use a negative scale on one axis and if you don't follow this rule the faces will be inverted from what you would expect.

**Comment by donmccurdy** [comment]
I see, thanks – looks like this was added to three.js as well, in r89, and I'd missed it. https://github.com/mrdoob/three.js/pull/12787.

@JoshKlint to your original question...

> ... meshes can potentially be shared across different nodes, some of which may be reversed and some not. Face direction should be a per-mesh property, not a per-node property. Am I misunderstanding this?

...the same mesh can be can be reused, uploaded to the GPU once, and rendered with different states of [`gl.frontFace`](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/frontFace) for example. So reversed face direction does not really interfere with reuse of the mesh in practice.
