### ISSUE TITLE
new extension reserved prefix SKYLINE

### ISSUE THREAD

**Issue by kipodon** [KhronosGroup/glTF#1704]
Hi,
I would like to register new extension reserved Prefix named SKYLINE
This is for 
Skyline Software Systems, Inc. 
we are the provider of 3D earth visualization software. and would like to export the data we create to gltf (and b3dm)

for more information look at
https://www.skylinesoft.com/

Thanks,
Alon.

**Comment by pjcozzi** [comment]
Sure thing, added in #1707!
