### ISSUE TITLE
Request for vendor extension registration: ALCM_

### ISSUE THREAD

**Issue by vspdi** [KhronosGroup/glTF#1708]
As mentioned in the Readme for vendor extensions I would like to register the extension for my company, because we are currently working on an extension that will be submitted via PR in a few weeks. PR will be submittet via this forked Repo [alchemistenag/glTF](https://github.com/alchemistenag/glTF/), but work ins in progress...

* The name of the prefix: `ALCM_`
* The name of the vendor using the prefix: Alchemisten AG
* Vendor's contact information: You can contact me directly via <viktor.spadi@alchemisten.ag>

Thanks in advance folks, btw. glTF rocks 🚀

**Comment by pjcozzi** [comment]
Sure thing, thanks for contributing, added in #1710.
