### ISSUE TITLE
Need to interact GLTF file in threejs or babylonjs

### ISSUE THREAD

**Issue by sureshwisdom** [KhronosGroup/glTF#1709]
Hi, 
I have created a 3D model in Sketchup pro and exported as GLTF then loaded in three.js. It is working well. Here I need to interact with the GLTF file like creating animations for the existing model dynamically (like a factory production line, If it got down animation should stop then again continue when it's up). and Need to change colors dynamically.  Please guide me. 
![Capture](https://user-images.githubusercontent.com/18713981/69031901-25535d00-0a16-11ea-8d84-eb40112dd6f8.JPG)

**Comment by donmccurdy** [comment]
I'd suggest using the three.js or babylonjs forums for this type of question. Once you've loaded a glTF model into one of these frameworks, interaction no longer depends on the file format used to load it. It's just a THREE.Mesh or similar object understood by the engine. 

https://discourse.threejs.org/
