### ISSUE TITLE
Request for vendor extension registration: FX_

### ISSUE THREAD

**Issue by candy520** [KhronosGroup/glTF#1712]
Hello, I would like to register the extension for my company.

The name of the prefix: FX_
The name of the vendor using the prefix: FOXIT SOFTWARE INC.
Vendor's contact information: liqian_mu@foxitsoftware.com

Thank you.

**Comment by pjcozzi** [comment]
Sure thing @candy520, added in #1714.

Looking forward to your contributions to the glTF ecosystem!

**Comment by donmccurdy** [comment]
@candy520 would you prefer to use the full name as the prefix, `FOXIT_`? There are other prefixes similar in length (GOOGLE, CESIUM, WEB3D, ADOBE) so the longer version would be fine and probably clearer. I opened this issue thinking the prefix request was coming from [SideFX](https://www.sidefx.com/). 😅

**Comment by candy520** [comment]
@donmccurdy  Thank you for your advice. Sounds good！That's fine to us too.

**Comment by emackey** [comment]
Updated to `FOXIT_`.
