### ISSUE TITLE
Do primitives in morphed mesh should have same count targets?

### ISSUE THREAD

**Issue by shrinktofit** [KhronosGroup/glTF#1716]
The spec stores 'weights' field to mesh instead of primitive. Does it mean primitives in morphed mesh should have same count targets? Or morphed mesh should have only one primitive?

```json
"meshes": {
  "primitives": [
    {
      "attributes": {  "POSITION": 0  }
      "targets": { "POSITION": 1 }
    },
    {
      "attributes": {  "POSITION": 2, "Normal": 3  }
      "targets": { "POSITION": 4, "Normal": 5 }
    },
  ],
  "weights": "[how-many?]"
}
```

**Comment by zeux** [comment]
https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#morph-targets:

> All primitives are required to list the same number of targets in the same order.

**Comment by shrinktofit** [comment]
> https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#morph-targets:
> 
> > All primitives are required to list the same number of targets in the same order.

Sorry...
