### ISSUE TITLE
Any C++ simple scene-graph capable of managing all data in GLTF?

### ISSUE THREAD

**Issue by cesss** [KhronosGroup/glTF#1723]
The README mentions a few engines that can import/export GLTF, but they are full-blown engines that offer a vast amount of features I don't need. On the other hand, there are simpler C++ viewers, but they don't allocate a scene-graph that mirrors the GLTF data, they just allocate a serialized representation of the GLTF file for optimum GPU performance.

There's tinygltf, but it just parses, without creating a C++ hierarchy, IIRC.

What I'd like to have is a C++ class hierarchy mirroring the contents of a GLTF file. Are you aware of any project doing this? If affirmative, could you mention it in the README?

**Comment by Peach1** [comment]
[This is the closest thing for a C++ glTF scene graph](https://github.com/SaschaWillems/Vulkan-glTF-PBR/blob/master/base/VulkanglTFModel.hpp) it defines Node, Mesh, AnimationSampler to mirror GLTF at runtime, and it supports major features like animation. All the core classes are there and you can extend the code or use it as a base to take out just what you need. The full GLTF scene hierarchy gets allocated at runtime there. I recommend to heavily modify/fork & port open source glTF projects to fit your needs, it saves a lot of time compared to having to read the GLTF spec 2.0 and manually implementing everything.

**Comment by vinjn** [comment]
My project melo might be the closest one to your needs.
I am using it in DX Raytracing, Vulkan Raytracing, OptiX applications so it should be API-agnostic.
https://github.com/jing-interactive/melo/

**Comment by sancelot** [comment]
I have similar request : 

I want being able to load and display gltf file : no problem, api exists 
I want being able to retrieve my graphic elements and change programmatically their position : No API
Ideally I want to manipulate a scene graph

**Comment by donmccurdy** [comment]
I might also suggest looking at the [cgltf](https://github.com/jkuhlmann/cgltf) project. I'll close this issue out for now — if there are more alternatives I would recommend ensuring that they're listed at http://github.khronos.org/glTF-Project-Explorer/.
