### ISSUE TITLE
Clarify bufferView data

### ISSUE THREAD

**Issue by fiesh** [KhronosGroup/glTF#1737]
> When a buffer view contain vertex indices or attributes, they must be its only content, i.e., it's invalid to have more than one kind of data in the same buffer view.

Apart from the missing _s_, I don't understand what "kind of data" means.  Does it mean a `bufferView` must not hold both indices and attributes, or does it mean a `bufferView` must not hold attributes that have say different component types?

**Comment by emackey** [comment]
I think it's saying that a single buffer view cannot contain both indices and attributes.  But it sounds like this part could use some clarification.

One of the design goals of accessors and bufferviews is to allow proper data interleaving, when desired, of vertex attributes in the buffer.  See the [glTF Tutorial on data interleaving](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_005_BuffersBufferViewsAccessors.md#data-interleaving) for more details.

**Comment by donmccurdy** [comment]
Or put differently — if a buffer view contains vertex attributes, it must only contain vertex attributes. If it contains indices, it must only contain indices. Mixing the two, or other data types (animation samplers, image data, ...) would create obstacles for runtimes.

**Comment by fiesh** [comment]
Ok that makes sense.  Thanks for the clarification.

A wording like _A buffer view must not contain both indices and attributes_ would probably be clearer than talking about _kind of data_.

**Comment by lexaknyazev** [comment]
This language was refined in the AsciiDoc spec release.
