### ISSUE TITLE
Clarifying Image URI Support

### ISSUE THREAD

**Issue by tfmertz** [KhronosGroup/glTF#1744]
I'm helping build a GLTF Model Importer and wanted some clarification on Image URI formats, specifically:
> a URI to an external file in one of the supported images formats, or

Does this mean GLTF supports loading Remote Images? For example,
```
http://example.com/uploads/texture.png
```
is a valid image uri?

If so, is there a sample model using this, thanks!

**Comment by donmccurdy** [comment]
Remote images (i.e. absolute URIs) are allowed. However, note that clients are not required to support them — I would not expect model upload sites like Sketchfab or Facebook to support absolute URIs, for security reasons.

See: https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#uris

Here is a sample:

[BoxTextured.gltf.zip](https://github.com/KhronosGroup/glTF/files/4089324/BoxTextured.gltf.zip)

**Comment by tfmertz** [comment]
Thanks for the clarification, example, and link. Very helpful!
