### ISSUE TITLE
java.io.FileNotFoundException

### ISSUE THREAD

**Issue by coolrukshan** [KhronosGroup/glTF#1746]
I am trying to load a .gilf from url. i have uploaded my gLTF file to github and get the url ("https://raw.githubusercontent.com/coolrukshan/testApp/master/mod/Jaguar.gltf"), but i am getting an error

java.util.concurrent.CompletionException: java.util.concurrent.CompletionException: java.io.FileNotFoundException: https://raw.githubusercontent.com/coolrukshan/testApp/master/mod/Jaguar.bin

plz advise me on this matter

**Comment by donmccurdy** [comment]
@coolrukshan your `.gltf` file contains a reference to a `.bin` file of the same name, as well as an image file. The exporter or source of the file should have provided all of these, and you'll need to host them all in the same directory. If you'd prefer to pack all of the model's resources into a single (`.glb`) file, you can do so with tools like glTF-Pipeline, gltfpack, or https://glb-packer.glitch.me/.

**Comment by coolrukshan** [comment]
@donmccurdy Thanks for your comment

**Comment by javagl** [comment]
The error message is Java, so you're probably (?) using https://github.com/javagl/JglTF , right? 
If so: The .BIN file seems to be there. So the loader *should* be able to load the asset. This *might* be an issue that is specific for JglTF, and you could consider reopening it at https://github.com/javagl/JglTF/issues ...

**Comment by javagl** [comment]
(An aside: I just downloaded the .GLTF file and dropped it into the validator at http://github.khronos.org/glTF-Validator/ , and it seems to contain some errors. You might consider fixing them first, because when trying to load an invalid asset, this may basically cause "arbitrary" other errors...)

**Comment by coolrukshan** [comment]
Thanks all for your comments, I did not upload the .bin file and the resources to the same folder. So I fixed that issue and now it worked.

It will be great if someone advise me how I use .glb  file instead of .gltf.

**Comment by cx20** [comment]
@coolrukshan I have checked [Jaguar.gltf](https://github.com/coolrukshan/testApp/blob/master/mod/Jaguar.gltf) and [out_t.glb](https://github.com/coolrukshan/testApp/blob/master/mod/out_t.glb) in your repositories and both seem to contain errors.

Could you try to convert .gltf to .glb by following the steps below?
1. Go to https://sandbox.babylonjs.com/
2. Drag and drop the .gltf file and related resources.
![image](https://user-images.githubusercontent.com/1833979/73009242-856de180-3e53-11ea-8355-5d42eb8ad76e.png)

3. Click the icon at the bottom right of the screen to display the Inspector.
![image](https://user-images.githubusercontent.com/1833979/73009348-b817da00-3e53-11ea-91f6-d3b88538f56e.png)

4. Click "Export to GLB" in the "Tools" tab.
![image](https://user-images.githubusercontent.com/1833979/73009480-0331ed00-3e54-11ea-9317-7ca0b552a08f.png)

**Comment by coolrukshan** [comment]
You guys are awesome......

**Comment by coolrukshan** [comment]
Hi all,
i did convert the .gltf to .glb form babylon.js

url = "https://github.com/coolrukshan/testApp/blob/master/mod/scene.glb";


ModelRenderable.builder()
                .setSource(this, RenderableSource.builder().setSource(
                        this,
                        Uri.parse(url),
                        RenderableSource.SourceType.GLB).build())
                .setRegistryId(url)
                .build()
                .exceptionally(new Function<Throwable, ModelRenderable>() {
                    @Override
                    public ModelRenderable apply(Throwable throwable) {
                        runOnUiThread(new Runnable() {
                            @Override
                            public void run() {
                                Toast.makeText(MainActivity.this,throwable.toString(),Toast.LENGTH_LONG).show();
                            }
                        });

                        return null;
                    }
                })
                .thenAccept(modelRenderable -> {
                    Vector3 worldPosition = scene.getCamera().getWorldPosition();
                    Node node = new Node();
                    node.setRenderable(modelRenderable);
                    Random random = new Random();
                    float x = random.nextInt(8) - 4f;
                    float y = random.nextInt(2) - 2f;
                    float z = random.nextInt(2);

                    Vector3 position = new Vector3( x, y, -z - 1f);
                    node.setWorldPosition(position);
                    node.setLocalRotation(Quaternion.axisAngle(new Vector3(0, 1f, 0), 300));
                    node.setOnTapListener(new Node.OnTapListener() {
                        @Override
                        public void onTap(HitTestResult hitTestResult, MotionEvent motionEvent) {
                            node.setLocalRotation(Quaternion.multiply(node.getLocalRotation(),
                                    Quaternion.axisAngle(Vector3.up(), motionEvent.getX())));
                        }
                    });
                    scene.addChild(node);
                    
                });


now getting an error 

java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to import '/data/user/0/com.test.augment/cache/1579835704849-0/model_source.glb'

**Comment by cx20** [comment]
@coolrukshan The error in the `.glb` file seems to have been resolved by the conversion using [Babylon.js Inspector](https://sandbox.babylonjs.com/). However, I think that it is not displayed due to a problem with the usage of the library. At least the URL on github is incorrect and needs to be corrected.
```
NG) https://github.com/coolrukshan/testApp/blob/master/mod/scene.glb
OK) https://raw.githubusercontent.com/coolrukshan/testApp/master/mod/scene.glb
```

**Comment by cx20** [comment]
@coolrukshan How is your progress?
Unfortunately, this repository is not a repository for libraries, but a repository for `glTF` specifications, so I don't think we can get any more answers.
Your code seems to be similar to [the code using ARCore](https://stackoverflow.com/questions/54812199/can-i-load-a-gltf-or-glb-file-from-the-external-storage) for the library, I think you should learn how to use [ARCore](https://developers.google.com/ar).

**Comment by coolrukshan** [comment]
Hi all, 
I have converted a sample module by using Babylonjs. After the conversion colors are not converted properly. Is they are any setting that I need to do in Babylonjs.

![Screenshot 2020-02-11 at 11 45 21](https://user-images.githubusercontent.com/1064747/74214869-1c94bf00-4cc5-11ea-8d97-cc029d219f47.png)

This is how it looks in app 

![1581401973656](https://user-images.githubusercontent.com/1064747/74214906-3c2be780-4cc5-11ea-8f87-d1cec1577d0e.JPEG)

**Comment by cx20** [comment]
Hmm, interesting. I tried to display [potato chip](https://github.com/coolrukshan/testApp/blob/master/mod/potato_chip.glb) models in several libraries, but each one looks different.

|[![image](https://user-images.githubusercontent.com/1833979/74219879-62677c80-4cf1-11ea-9595-cf6e4182e06c.png)](https://cx20.github.io/gltf-test/examples/threejs/index.html?url=https://rawcdn.githack.com/coolrukshan/testApp/4ef0fbf3c690d6bb9ca977c33a341d534f7a6938/mod/potato_chip.glb&scale=0.005)|[![image](https://user-images.githubusercontent.com/1833979/74219893-6b584e00-4cf1-11ea-870c-77cc1dcc48e0.png)](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?url=https://rawcdn.githack.com/coolrukshan/testApp/4ef0fbf3c690d6bb9ca977c33a341d534f7a6938/mod/potato_chip.glb&scale=0.005)|
|:--------:|:--------:|
|[![image](https://user-images.githubusercontent.com/1833979/74219915-77dca680-4cf1-11ea-9c8a-a890a5c4ea83.png)](https://cx20.github.io/gltf-test/examples/playcanvas/index.html?url=https://rawcdn.githack.com/coolrukshan/testApp/4ef0fbf3c690d6bb9ca977c33a341d534f7a6938/mod/potato_chip.glb&scale=0.005)|[![image](https://user-images.githubusercontent.com/1833979/74219929-81fea500-4cf1-11ea-9308-f7129f719750.png)](https://cx20.github.io/gltf-test/examples/filament/index.html?url=https://rawcdn.githack.com/coolrukshan/testApp/4ef0fbf3c690d6bb9ca977c33a341d534f7a6938/mod/potato_chip.glb&scale=0.005)|

**Comment by cx20** [comment]
@coolrukshan Tuning the Metallic Workflow parameters in the [Babylon.js Inspector](https://sandbox.babylonjs.com/) may help. After adjusting the parameters, export to a `glb` file and try again.

![image](https://user-images.githubusercontent.com/1833979/74248459-f3a71500-4d2a-11ea-8a7c-f7a9d1f85f18.png)

![image](https://user-images.githubusercontent.com/1833979/74248785-79c35b80-4d2b-11ea-92a0-59e514cbd872.png)

**Comment by coolrukshan** [comment]
It works ...... Thanks  @cx20 ....
