### ISSUE TITLE
[compression]Potential "cracking" problems after mesh splitting 

### ISSUE THREAD

**Issue by kmammou** [KhronosGroup/glTF#175]
To meet WebGL constraints, the converter splits any mesh with a number of vertices higher than 65535 vertices into a set of sub-meshes. In order to avoid cracking problems, the bounding box of the original mesh need to be used for quantization, when encoding the sub-meshes.

**Comment by pjcozzi** [comment]
This would be a Draco issue now if it is one at all.

CC @FrankGalligan
