### ISSUE TITLE
Request for prefix "MPEG"

### ISSUE THREAD

**Issue by haudiobe** [KhronosGroup/glTF#1754]
Dear all, 

MPEG has decided to not develop a new scene description format for their MPEG-I project "Coded Representation of Immersive Media" from scratch, but to extend glTF 2.0 using the vendor extension mechanism.

Hence, MPEG requests the prefix "MPEG".

Contact Persons:
- Thomas Stockhammer <tsto@qti.qualcomm.com>,  Qualcomm Incorporated, MPEG-I scene description Breakout Group chair
- Leonardo Chiariglione <Leonardo@chiariglione.org>, MPEG Convenor
- Youngkwon Lim <young.l@samsung.com>, Samsung, MPEG systems chair

For more information on the status and the processes, please refer to one of our public documents here:
[w19072.zip](https://github.com/KhronosGroup/glTF/files/4165253/w19072.zip)

If you have any questions, please do not hesitate to contact me.

Best regards

Thomas

**Comment by emackey** [comment]
@haudiobe That sounds amazing, thanks!  PR #1755 opened.

**Comment by emackey** [comment]
Done.

**Comment by haudiobe** [comment]
Guys,

thanks a lot. Can you please change: 
"Motion" => "Moving"

We are the Moving Pictures Expert Group (MPEG). 

Thanks

Thomas

**Comment by emackey** [comment]
@haudiobe Sorry about that, I should have been more careful.  Fixed now.

**Comment by emackey** [comment]
Actually I copied your comment, but the website puts the `s` in a different place.  I think I'll change it to match what's on the website.

**Comment by emackey** [comment]
Done

**Comment by haudiobe** [comment]
Thanks
