### ISSUE TITLE
MORE SHADER DATA

### ISSUE THREAD

**Issue by ClinToch** [KhronosGroup/glTF#1757]
Make glTF able to support
*Transmission/Glass shader data
*Alpha/Opacity data

**Comment by javagl** [comment]
It's not entirely clear (for me) what you mean, but ...

- one extreme is the "techniques" extension (basically inherited from glTF 1.0), which allows you to include *arbitrary shader code* in glTF: https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_techniques_webgl
- the other extreme are the next-gen materials, which are summarized in https://github.com/KhronosGroup/glTF/milestone/2 , and which go far, far beyond "support for some additional data"

**Comment by donmccurdy** [comment]
>  *Alpha/Opacity data

glTF provides alpha now, with OPAQUE, MASK, and BLEND modes. These are quite similar to the alpha modes in Blender.

As @javagl mentions, physically-based transparency is on our roadmap for future glTF extensions.

> one extreme is the "techniques" extension

Note that this extension has been in draft state for a while, and isn't ratified. I would recommend sticking to the alpha modes for current workflows.
