### ISSUE TITLE
Optimize mesh partitioning algorithm to achieve better compression ratios 

### ISSUE THREAD

**Issue by kmammou** [KhronosGroup/glTF#176]
To meet WebGL constraints, the converter partitions any mesh with a number of vertices higher than 65535 vertices into a set of sub-meshes. The current mesh splitting algorithm does not take into account the impact on the compression efficiency. A better approach would consists in splitting the mesh into a set of sub-meshes with the same number of vertices, while minimizing the number edges to be cut. This problem is equivalent to the graph partitioning problem described here http://en.wikipedia.org/wiki/Graph_partition

**Comment by pjcozzi** [comment]
@FrankGalligan relavant to Draco?
