### ISSUE TITLE
Bone orientations don't match mesh

### ISSUE THREAD

**Issue by Leadwerks** [KhronosGroup/glTF#1763]
I am working on adding animation support to our GLTF loader. In this model, the starting positions of bones are shown with blue spheres. I recognize the pose as part of the running animation. (The character is leaning forward and holding a gun.) The model loads and animates correctly in the Windows 3D object viewer.
![anim](https://user-images.githubusercontent.com/108503/74412539-56d99a00-4e46-11ea-9fc3-347208c53591.jpg)
Why doesn't the starting bone orientation match the model pose?

**Comment by germangb** [comment]
The buffer data of the mesh may not match the bind pose of the skeleton.

I found that `project_polly` is an example of this. In that scene the buffer data of the eyeballs and their skeleton didn't match.

**Comment by germangb** [comment]
Also, since I'm not familiar with this specific model, are you sure this particular orientation correspond to the initial orientation (the way it's defined in the json part of gltf) and *not* the first frame of animation?

**Comment by donmccurdy** [comment]
Let's have this discussion on the forum, since the issue on this model doesn't seem related to glTF specification itself.
