### ISSUE TITLE
Add an optimization process to unify duplicated vertices

### ISSUE THREAD

**Issue by kmammou** [KhronosGroup/glTF#177]
COLLADA exporters may introduce unnecessary duplicated vertices, which would hurt compression efficiency. An optimization process, which would unify vertices with the same attributes need to be implemented in order to avoid such a problem.

**Comment by pjcozzi** [comment]
@leerichard42 do you think we cover this sufficiently in gltf-pipeline that we can close this?

**Comment by leerichard42** [comment]
Yes, I think we should be able to merge vertices before we remove unused vertices, which would  make the latter more efficient.

**Comment by pjcozzi** [comment]
Yeap, it would be its own stage.  I think it could go before or after removing unused vertices, I'm not sure which is better in the general case, e.g., removing unused vertices first would also make this more efficient.

BTW to do this efficiently, we should consider a spatial hash table with a hashing function like the one in [Optimized spatial hashing for collision detection of deformable objects](http://matthias-mueller-fischer.ch/publications/tetraederCollision.pdf).

I'll add this to https://github.com/AnalyticalGraphicsInc/gltf-pipeline/issues/1 and close this.
