### ISSUE TITLE
Is it possible (valid) to have metallicFactor greater than 1

### ISSUE THREAD

**Issue by ranbuch** [KhronosGroup/glTF#1781]
What is the maximum valid values for `metallicFactor`, `roughnessFactor` fields?

What about `normalTexture.scale`, `occlusionTexture.strength` and `emissiveFactor`?

If they are valid, do you happened to know how will they convert to `USDZ` or will Google's [scene-viewer](https://developers.google.com/ar/develop/java/scene-viewer) respect those kind of values?

Thanks.

**Comment by donmccurdy** [comment]
Maximum values are defined here (as well as in the schema files) —

- https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#pbrmetallicroughnessmetallicfactor
- https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#occlusiontextureinfostrength
- https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#materialemissivefactor

A correct implementation of glTF is expected to support the full range of values. But conversion to USDZ, I don't know.

Normal scale is not bounded.
