### ISSUE TITLE
Deviation(+=) or substitution(=)? How does sparse values are related from their base values?

### ISSUE THREAD

**Issue by shrinktofit** [KhronosGroup/glTF#1793]
The spec says that sparse values are deviated from their base values:

> The following fragment shows an example of sparse accessor with 10 elements deviating from the initialization array.

> Sparse storage of attributes that deviate from their initialization value.

However at some points, the spec says that sparse values should substitute their base values:

> A sparse accessor min and max properties correspond, respectively, to the minimum and maximum component values once the sparse substitution is applied.

And in sample models repository, the screenshot of `SimpleSparseAccessor` shows that sparse values should do substitue.

I'm confused..

**Comment by javagl** [comment]
That also caused some confusion for me. In fact, when I created the initial version of the `SimpleSparseAccessor` example (see https://github.com/KhronosGroup/glTF-Sample-Models/issues/99#issuecomment-327335065 ), I also assumed that the values that are obtained from the sparse accessor should be *added*  (`+=`) to the original position, but this is **not** the case.

The values are really supposed to *substitute* (i.e. *replace*) the original values. 

I'm not a native English speaker, but the confusion seems to stem from the term "deviate". It *seems* to suggest that the values *are* "*the deviations*". But after reading it again, this is not what the spec says. It only says that the values "*do* deviate" (roughly meaning that "they are different"), but not that they *are* "the deviations". 

Maybe the misinterpretation could be avoided by simply rephrasing statements like

> The following fragment shows an example of sparse accessor with 10 elements deviating from the initialization array.

to something like

> The following fragment shows an example of sparse accessor with 10 elements that are different from the values in the initialization array.

(But I'm not sure whether this can simply be changed without another ratification...)

**Comment by emackey** [comment]
I'm not the author but yes, I agree that the word "deviate" here is just a fancy way of saying "is different from the norm" without any implication of it being stored as a delta or not.  It merely implies that there is such a thing as a normal, non-deviated value, not the storage mechanism.

Khronos does not require re-ratification just to clarify wording.  If this can be edited to make it clear to a broader range of readers, I'm all for it.  PRs welcome!
