### ISSUE TITLE
OSG.JS (loader) link points to a porn website

### ISSUE THREAD

**Issue by bouviervj** [KhronosGroup/glTF#1795]
Please check: 

http://osgjs.org/

**Comment by cedricpinson** [comment]
I archived the website here https://cedricpinson.github.io/osgjs-website/

**Comment by javagl** [comment]
The tables in the main glTF readme have been replaced with the [glTF Project Explorer](https://github.com/KhronosGroup/glTF-Project-Explorer) and the offending link has therefore been removed with https://github.com/KhronosGroup/glTF/pull/1796

The project explorer already contained the updated/archived link for OSG.JS (details at https://github.com/KhronosGroup/glTF-Project-Explorer/pull/44 )
