### ISSUE TITLE
Alpha mask distinct from base color image

### ISSUE THREAD

**Issue by topheg** [KhronosGroup/glTF#1802]
I'm trying to use textures with an alpha channel, with MASK alpha mode. However, using png makes my models way too big.
I'm wondering if there's a way to use distinct images for the base color (that way JPEG could be used) and the alpha mask (that would be stored as a 1-channel image). 
I can't find anything like that in the specs, but maybe there are extensions that allow this ?

**Comment by lexaknyazev** [comment]
Using [WebP](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Vendor/EXT_texture_webp) instead of PNG is the simplest way to achieve JPEG-like size for textures with alpha channel.

A more advanced solution based on GPU block compressed formats is WIP.

**Comment by topheg** [comment]
Thanks ! I started using webp, but didn't see the extension, nor that it allows to fallback to png when not supported.
