### ISSUE TITLE
Request for SPECTRUM vendor prefix

### ISSUE THREAD

**Issue by adamshaylor** [KhronosGroup/glTF#1804]
Hello,

We are exploring glTF for use in product customization. To make this feasible, we will probably need to create our own vendor extensions. Although we’re in the exploratory phase at the moment, we’d like to do the right thing by reserving `SPECTRUM` as our vendor prefix to avoid clashes with others down the road.

- Website: https://spectrumcustomizer.com/
- Contacts:
  - @adamshaylor
  - @tomfalkner
  - @bwaldron

Regards,

Adam Shaylor
_Spectrum – Product Customization Platform_

**Comment by pjcozzi** [comment]
Sure thing, added in #1805.

We look forward to collaborating, @adamshaylor, @TomFalkner, and @bwaldron.
