### ISSUE TITLE
Backward convert glTF to obj

### ISSUE THREAD

**Issue by SystemDiagnosticss** [KhronosGroup/glTF#1807]
Is it possible convert glTF to obj ? 
If we have animation convert some one gltf-frame to obj ?

**Comment by javagl** [comment]
Technically, it may be possible, *with limitations*. The biggest challenges that I can think of are 

1. How to determine the *exact* state of the animation that should be exported
2. How to handle the materials

In general, the "big tools" like Blender, 3ds max or Maya usually have *importers* for glTF (and many other formats), and *exporters* for OBJ/MTL (and many other formats). So it should, technically, be possible to load a glTF, play the animation into the desired state, and then export this state as OBJ (although I have not yet tried this, don't know which tool might be best suited, or whether there are caveats).

The biggest limitation could be the materials: If the glTF has a complex PBR material, then boiling this down to an MTL that resembles the original material could be a challenge. Although [the MTL format](http://paulbourke.net/dataformats/mtl/) is surprisingly sophisticated (with cube maps refraction, reflection and detailed illumination models and whatnot), there are *very* few tools that actually support this in all depth, and sensibly mapping a PBR material to these parameters could be difficult.
