### ISSUE TITLE
ThreeJs texture color rendering 

### ISSUE THREAD

**Issue by AshWilliams1992** [KhronosGroup/glTF#1808]
Hi,

first of all I want to thank you for the great job, I can finally achieve my PLA animation without any problem: for this model I have just a color rendering problem that I can't achieve, I hope someone will help.

What I have is an texture for my apple, but for some reason is too red, like I've added a multiply red color.

This is the correct version ( .dae file ):
![MelaDae](https://user-images.githubusercontent.com/48948044/81130085-cf558000-8f89-11ea-8a53-64b2fc12313b.PNG)

This is the gltf file:
![MelaFactor](https://user-images.githubusercontent.com/48948044/81130100-e09e8c80-8f89-11ea-8310-06897c95248d.PNG)

And this is the UVmap that I use:
![UV](https://user-images.githubusercontent.com/48948044/81130118-eeeca880-8f89-11ea-8275-354ec5cfa651.jpg)

I'm wondering if the issue is cause by the red background color of the texture? Why I don't have this problem with a .dae file?

About my configurations, the lights are the same ( color and intensity ) and the metalness is set to 0.

Thanks

**Comment by donmccurdy** [comment]
Could you confirm whether the glTF model appears correct in existing viewers?

- https://gltf-viewer.donmccurdy.com/
- https://sandbox.babylonjs.com/

Lighting and colorspace sometimes require configuration, see the THREE.GLTFLoader documentation for example. If the model looks incorrect (compared to the original DAE) you may need to report a bug to the software used to convert the model.

**Comment by AshWilliams1992** [comment]
Thank you so much @donmccurdy , the gltf-viewer it's been very helpful: it was working there, so I started playing with the WebGLRenderer. The trick was apply this line of code

`renderer.gammaOutput = true;`

to apply the gamma correction to the rendered.

This is the solved issue
https://github.com/mrdoob/three.js/issues/6593#issuecomment-120756513

**Comment by donmccurdy** [comment]
Glad to hear! In more recent versions of three.js that setting has been renamed:

```js
renderer.outputEncoding = THREE.sRGBEncoding;
```
