### ISSUE TITLE
Hint to optimize picking

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#181]
Most picking implementations assign a unique color, i.e., an ID, to each primitive/mesh/node/asset, and then use a fragment shader to render the color to a texture for read back.

If we know the fragment shader doesn't discard or write an alpha of zero when blending, we can optimize picking by using a trivial fragment shader that just passes through the color.  Otherwise, we need to create a new fragment shader that runs the entire glTF fragment shader, and then outputs the color if the fragment survives.

If glTF had a hint to know this, an implementation could optimize its picking implementation quite a bit.

**Comment by pjcozzi** [comment]
Is this possible now with PBR - just want to know that a material is opaque and doesn't discard in the fragment shader?

**Comment by bghgary** [comment]
With glTF 2.0, you can now check the [`alphaMode`](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#alpha-coverage) to see if the material is opaque or not.
