### ISSUE TITLE
Question: Animation Sampler Output

### ISSUE THREAD

**Issue by Siccity** [KhronosGroup/glTF#1812]
I have a simple animated file which I exported from Blender 2.8
Inspecting the `translation` animation channel, following it to its sampler, I see that `input` points to this accessor:
```json
{
    "bufferView" : 4,
    "componentType" : 5126,
    "count" : 5,
    "max" : [
        1.6666666666666667
    ],
    "min" : [
        0
    ],
    "type" : "SCALAR"
}
```
which contains these 5 values `[0.00, 0.41, 0.83, 1.25, 1.66]`

This is the keyframe times and this works fine.

This is the `output` accessor:
```json
{
    "bufferView" : 5,
    "componentType" : 5126,
    "count" : 15,
    "type" : "VEC3"
}
```
Why do I have 15 VEC3 values and not just 5, one for each of the input values?
If the X Y and Z channels were separated the type would be SCALAR, right?
Three.js imports it correctly.

[animtest.zip](https://github.com/KhronosGroup/glTF/files/4598453/animtest.zip)

**Comment by lexaknyazev** [comment]
> Why do I have 15 VEC3 values and not just 5, one for each of the input values?

Because the translation animation in the asset uses `CUBICSPLINE` interpolation. In such a case, there are two more pieces of data for each value: in- and out-tangents. Hence 3 times more values in the output accessor.

**Comment by Siccity** [comment]
Ah, that makes sense! How are these values laid out? `val,in,out,val,in,out`, `in,val,out,in,val,out` `val,val,in,in,out,out`... ?

**Comment by donmccurdy** [comment]
The layout is `in,val,out...`, see https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#appendix-c-spline-interpolation.

**Comment by markm72homeruns** [comment]
Can someone tell me what is in the output of the ROTATION if you have CUBICSPLINE? Is the tangent vector the x y z and throw away the 4th param. then the quat , then the same out tangent in x y z ignore the fourth?
