### ISSUE TITLE
glTF implementation compatibility issues

### ISSUE THREAD

**Issue by dracolytch** [KhronosGroup/glTF#1817]
Hey folks,

I was trying to get started with glTF recently, and ran into what looks like a compatibility issue. I took a glTF export from SolidWorks, and brought it into Unity (using the Khronos-provided loading code), and had issues with missing parts and wrong orientation (orientation is semi-expected, but the missing parts is a big problem). As a sanity-check, I brought the same model into Blender, and got the same problems, leading me to believe the issue appears to be on the SolidWorks export side.

I've found another work-around in this case, but I thought I'd provide the heads-up that I'm seeing some compatibility issues in the wild.

The files are proprietary, and I cannot provide them as an example.

**Comment by donmccurdy** [comment]
Could you confirm whether the SolidWorks export passes https://github.khronos.org/glTF-Validator/ and displays correctly in viewers like https://sandbox.babylonjs.com/? I'm guessing you're correct that it's an issue on the SolidWorks exporter, but these tools may help to confirm that.
