### ISSUE TITLE
glTF come e dove iniziare 

### ISSUE THREAD

**Issue by pdm1968** [KhronosGroup/glTF#1819]
salve a tutti , mi chiamo Pietro 
e sono nuovo su tutti i fronti e non ho alcuna idea di come iniziare a progettare con glTf...non ho molto tempo in realta' , perche' tra lavoro e altre cose importanti , la mia giornata e' abbastanza piena , ma nel mio tempo libero , con molta molta tranquillita' , mi piacerebbe fare qualcosa di creativo ( che sia modellazione di personaggi o strutture statiche ) ....purtroppo non parlo inglese , ma ad ogni modo , potreste aiutarmi a capire come iniziare a comprendere l'utilizzo di glTF e dove / come iniziare ? un grazie a tutti e scusate . PS : glTs lo posso innanzitutto arpire e usare su window 10 con una Intel Hd graphics 3000 , o necessito di una Opengl -->>( in tal caso non potrei mai iniziare nulla ...) anche perche' il mio portatile Dell ha gia' 7 anni purtroppo 
a presto e grazie per avermi letto :)
viaggiatorelibero@outlook.it

**Comment by donmccurdy** [comment]
Unfortunately I'm not sure any of this project's maintainers speak Italian, sorry. I'll do my best with Google Translate here. If you're interested in doing creative projects like 3D modeling, I would recommend starting with free 3D software like [Blender](https://www.blender.org/features/), which can be used to create glTF files.

This GitHub repository includes the technical details of the glTF file format — but you do not need to understand those details when using artist software like Blender.
