### ISSUE TITLE
 Missing chapter on Tangent-space definition?

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/glTF#1827]
There is a link to the Tangent-space definition under Concepts -> Geometry -> Meshes that doesn't lead anywhere. It seems that this chapter is currently missing from the spec.

Link: https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#tangent-space-definition

**Comment by tombsar** [comment]
+1 There are a few implementation notes relating to tangent space at the end of the Meshes subsection, but not a full subsection as indicated in the contents.

> Implementation note: When tangents are not specified, client implementations should calculate tangents using default MikkTSpace algorithms. For best results, the mesh triangles should also be processed using default MikkTSpace algorithms.

> Implementation note: Vertices of the same triangle should have the same tangent.w value. When vertices of the same triangle have different tangent.w values, tangent space is considered undefined.

> Implementation note: When normals and tangents are specified, client implementations should compute the bitangent by taking the cross product of the normal and tangent xyz vectors and multiplying against the w component of the tangent: bitangent = cross(normal, tangent.xyz) * tangent.w

It seems to me as though they intend for us to just use the MikkTSpace code (http://www.mikktspace.com/) and not think too hard about it.

**Comment by lexaknyazev** [comment]
That section has been clarified in the AsciiDoc specification release.
