### ISSUE TITLE
Cannot Load More than 4 animations of a GLTF model

### ISSUE THREAD

**Issue by jewel998** [KhronosGroup/glTF#1833]
I recently was testing my model and it turned up that it is only able to load 4 animations for my model, even when I added more than 4 NLA in my model, it's not even showing on the controls menu. I hope you can help me out with this.

And I would be very thankful if you could help me out with rendering a terrain along with my GLTF model. Thank You!

**Comment by Drigax** [comment]
You may want to open this bug in https://github.com/KhronosGroup/glTF-Blender-IO, for help with the blender glTF exporter, and in the appropriate repo for whatever program you're loading your model into

**Comment by jewel998** [comment]
Thank You, but the problem isn't in the exporter, it's exporting the animations accordingly, I checked the file, but the loader isn't able to fetch more than 4 Animation Clips.

**Comment by donmccurdy** [comment]
In that case you may need to report the issue to the program you're loading the model in — this is the repository for the file format itself, and certainly the file format supports more than four animations. :)
