### ISSUE TITLE
How to compress vertex and index of line primitive？

### ISSUE THREAD

**Issue by yuz1** [KhronosGroup/glTF#1839]
Triangle primitive can be compressed using Draco. Can line primitive be compressed with Draco？

**Comment by donmccurdy** [comment]
Line primitives cannot be compressed with Draco. What viewer(s) do you need to load this model in? Depending on what they support you may be able to reduce the model's size with:

a. gzip (applied with something like [gzip-cli](https://www.npmjs.com/package/gzip-cli))
b. quantization (applied with [gltfpack](https://github.com/zeux/meshoptimizer/tree/master/gltf))
c. [meshopt compression](https://github.com/KhronosGroup/glTF/pull/1830) (applied with [gltfpack](https://github.com/zeux/meshoptimizer/tree/master/gltf))
