### ISSUE TITLE
Request for vendor extension: SEIN

### ISSUE THREAD

**Issue by dtysky** [KhronosGroup/glTF#1840]
Could I register a vendor extension prefix?

Prefix: SEIN  
Project: [Sein.js](https://github.com/hiloteam/Sein.js)  
Contacts: [https://seinjs.com](https://seinjs.com)  
Vendor: [Hiloteam](https://github.com/orgs/hiloteam/people)  
Upcoming extension proposal: https://github.com/hiloteam/Sein.js/blob/master/src/Resource/GlTFLoader.ts#L300

**Comment by pjcozzi** [comment]
Hi @dtysky!  Thanks for your interest in contributing to the glTF ecosystem.  We added the `SEIN` prefix in #1842.
