### ISSUE TITLE
removing unused objects from a glTF 2.0 file

### ISSUE THREAD

**Issue by tawfik741** [KhronosGroup/glTF#1844]
I used opencascade's module to export from step to glb . I tried to read the glb file with blender and it works just fine . I then imported it to babylon and it crashed . I posted the file on Khronos's glTF validator and it reported lots of unused meshes . I would like to know if there is a way to remove these unused meshes and if there is other ways to optimize glTF files and babylon import

**Comment by donmccurdy** [comment]
I'd be a bit surprised if unused meshes were causing Babylon to crash — how many are you talking about, and how large is the file? And were there other validation warnings from the Khronos validator? You might find it easier to trim things in Blender then export back to glb. 

If you did just want to trim unused meshes, you could do something like this with [glTF-Transform](https://gltf-transform.donmccurdy.com/):

```js
const fs = require('fs');
const path = require('path');
const { NodeIO, Root } require ('@gltf-transform/core');

// Read file.
const io = new Node(fs, path);
const doc = io.read('original.glb');

// Remove unused meshes.
const unused = [];
doc.getRoot().listMeshes().forEach((mesh) => {
  const parents = mesh.listParents();
  if (parents.length === 1 && parents[0] instanceof Root) {
    unused.push(mesh);
  }
});
unused.forEach((mesh) => mesh.dispose());

// Write file.
io.write('trimmed.glb', doc);
```

If the file is OK according to the validator but still isn't working in babylon, I would recommend filing an issue on the babylon repo.

**Comment by tawfik741** [comment]
Hi Don , thank you for your code snippet ( really nice library btw ) it wasn't because of unused meshes but because of the fact that after performing tessellation , i should have welded the primitives to their parent node , i asked how to do that with babylonjs on stackoverflow and you responded to my question [here](https://stackoverflow.com/questions/63156435/how-to-optimize-babylons-glb-reader-by-welding-primitives) .
