### ISSUE TITLE
Should primitive attributes have the same count?

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/glTF#1845]
I could have sworn that glTF specification imposes a restriction on accessors used within the same primitive, requiring the exact same number of elements (`count`) for all of them.

However, I can't find this in the specification. Am I just missing the text somewhere?

glTF-Validator performs this validity check and emits `meshPrimitiveUnequalAccessorsCount` error.

The only relevant notes I can find are:

1.
> All Morph Target's accessors must have the same count as the accessors of the original primitive.

Which can be interpreted as "for each attribute type, morph target accessor for that type must have a count matching the accessor with the same attribute type for the original primitive".

2.
> When the indices property is not defined, GL's drawArrays function should be used with a count equal to the count property of any of the accessors referenced by the attributes property (they are all equal for a given primitive).

Which is hidden in parentheses in an implementation note and could apply to non-indexed meshes only.

**Comment by bghgary** [comment]
I don't see anything either. @lexaknyazev?

@zeux Do you want to create a PR for the spec?

**Comment by zeux** [comment]
@bghgary Yeah, just created a PR for this.
