### ISSUE TITLE
Request for PTC Vendor prefix

### ISSUE THREAD

**Issue by PaulJPremakumar** [KhronosGroup/glTF#1851]
Hello,

Onshape, A PTC Business supports glTF today, but we would like to add more information to the glTF representation. We have an extension in the works, and hence request a vendor prefix.

Prefix: PTC
Company: PTC Inc
Website: https://www.ptc.com/

Thank You,
Paul Premakumar

**Comment by emackey** [comment]
Hi @PaulJPremakumar, PTC is registered now.  Thanks!
