### ISSUE TITLE
EXT_mesh_gpu_instancing sample models

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF#1855]
The [EXT_mesh_gpu_instancing](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Vendor/EXT_mesh_gpu_instancing) extension includes a `samples` folder with 3 different versions of the same basic sample model.

- [ ] `teapots_galore_id.gltf` has a severe error, where bufferView 10 does not fit within the byte length of the buffer, as reported by the glTF Validator.
- [ ] `teapots_galore_T4x3` uses `"type": "MAT4x3"` which is not described in the README or the schema.
- [ ] `teapots_galore.gltf` includes several `extras.arrayIndex` which don't belong in an official sample.
- [ ] The sample model(s) should be moved to glTF-Sample-Models.

I'm thinking we probably only want `teapots_galore.gltf` and not the other two versions, as an official sample.

Also, do any WebGL engines implement this extension yet?

**Comment by donmccurdy** [comment]
three.js is not merged yet, see https://github.com/mrdoob/three.js/pull/18913. I believe Babylon had implemented it, too.

**Comment by donmccurdy** [comment]
On second thought... I agree the spec repo isn't the right place, but do we want vendor and multi-vendor extensions to be hosted on glTF-Sample-Models? Would we need separate Khronos and Vendor folders, maybe?

Wherever we put it, I would suggest just keeping one of the current examples. I'd like to make a more practical example at some point, too, but don't know when I will get to that.

**Comment by emackey** [comment]
Oh good point.  Maybe just multi-vendor extensions could be allowed?  We do have [one model in there](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/EnvironmentTest) already that uses `EXT_lights_image_based`.

Of the three instancing models here, I believe only one of them is actually valid (the `teapots_galore.gltf` one).  The other two should be dropped I believe.

**Comment by emackey** [comment]
FWIW, AGI's STK 12.1 will also support `EXT_mesh_gpu_instancing`.  We added it in anticipation that 3D Tiles might start using it at some point.

**Comment by bghgary** [comment]
> Maybe just multi-vendor extensions could be allowed? We do have one model in there already that uses EXT_lights_image_based.

I don't know. I put this there in anticipation that we will have a KHR version of an IBL extension. If the intention is to just be a multi-vendor extension, I'm not sure.

> Of the three instancing models here, I believe only one of them is actually valid (the teapots_galore.gltf one). The other two should be dropped I believe.

Yes, I think this is right. We should have removed the incorrect ones. For reference, Babylon.js has this extension implemented and we are using [this asset](https://github.com/BabylonJS/Assets/tree/master/meshes/TeapotsGalore) in our automated testing. I haven't checked if this matches one of the ones listed earlier, but I believe we copied the one from the spec.

**Comment by ieremius** [comment]
Not sure where the best place to ask this is...the EXT_mesh_gpu_instancing [spec](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/EXT_mesh_gpu_instancing) mentions the notion of using the extension for fur. Does anyone know of a model (sample or for purchase) that does fur? I only know of the teapot model for this extension.

**Comment by DrX3D** [comment]
I can remove the teapost_galore model and move it into the new Sample Asset repo as part of PR #2263. I would also remove the teapots_galore_id folder entirely. There would not be any issues with having a model using this extension in the repo because the extension has been approved to enter the ratification process. 

Would do this resolve all issues on this issue?

**Comment by javagl** [comment]
(Maybe obvious) Nitpicks:

- It should then be `TeapotsGalore` (or a different name, but `CamelCase`)
- The asset still causes warnings, `BUFFER_VIEW_TARGET_MISSING	bufferView.target should be set for vertex or index data`. Before becoming a sample asset, this should be fixed.
- The asset contains some noise - namely, some `extras: { arrayIndex... }` properties, probably created by the exporter. It would be good to remove this...

(I can do the latter, if there's a PR/branch to work on - maybe even after the model was renamed/added elsewhere)
