### ISSUE TITLE
load .obj mtl material data

### ISSUE THREAD

**Issue by HappyKuTou** [KhronosGroup/glTF#1856]
**Describe the issue**

I have to convert obj to gltf
data in obj mtl file is not pbr data
how can I fill the gltf material struct after load obj mtl file

**To Reproduce**

- OS win10
- Compiler vs2019 

**Expected behaviour**

I need to write mtl data in gltf material struct

**Screenshots**
this is gltf material struct 
![image](https://user-images.githubusercontent.com/42768162/91420304-17751700-e887-11ea-95ef-a81b9b200997.png)

this is obj mtl file
![image](https://user-images.githubusercontent.com/42768162/91420380-35427c00-e887-11ea-8387-84871447f1d5.png)

**Comment by emackey** [comment]
Hi @HappyKuTou, this is the repository for the glTF file format itself, not any particular tool.

You might find some tools that can do this, such as [obj2gltf](https://github.com/CesiumGS/obj2gltf) and [Blender](https://www.blender.org/).

For additional tools, check out the [glTF Project Explorer](http://github.khronos.org/glTF-Project-Explorer/).

**Comment by HappyKuTou** [comment]
thanks

Ed Mackey <notifications@github.com> 于2020年8月28日周五 上午1:05写道：

**Comment by andrewvarga** [comment]
You can also try [glTFEditor](https://www.gltfeditor.com/) that can import obj files.
