### ISSUE TITLE
Index texture map

### ISSUE THREAD

**Issue by gjcope** [KhronosGroup/glTF#1859]
We (Smithsonian Institution) are currently using glTF and are generating one texture map outside of the spec. It's an index map using color to define regions, in our case regions of interest on a collections object or interactive regions. We use it for gpu-based selection as well as to visualize the regions. We would love to be able to pack it in our glbs. Does this sound appropriate for a vendor specific extension? If so, any pointers on where to begin? A material extension seems like overkill. Thanks!

**Comment by donmccurdy** [comment]
Is the extra texture **(A)** associated with a particular mesh or material? Or **(B)** applied to the entire `.glb` file?

If **(B)**, the simplest method would just be to add the texture to the file — without attaching it to a material — with some recognizable name or `extras` property to identify it. You don't need an extension to do that. The glTF Validator will warn you about an unused texture, but it's still a valid file.

If **(A)**, or if you want a more formally defined structure for other reasons, then I might suggest a vendor specific extension. A good extension to imitate would be [KHR_materials_transmission](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_transmission), which defines only a single texture and a factor. In this case you might not need a factor.

**Comment by donmccurdy** [comment]
That said — depending on the tools involved in your pipeline, an extension might not be as much work as you think. Engines like three.js and babylon.js have extension mechanisms built into their glTF loaders, where you can attach your own code for custom behaviors.

**Comment by gjcope** [comment]
Thanks for following up @donmccurdy ! The texture is more (A) than (B). It is specific to the uv space of a particular mesh. In most of our current use cases we only have one model which essentially makes it (B), but we would like to support this functionality with multi-model scenes so (A) is more approriate.

I will take a stab at the vendor specific extension. Thank you for the tip. We are using Three.js so sounds like it shouldn't be too big of a lift.

**Comment by donmccurdy** [comment]
On the authoring side, https://gltf-transform.donmccurdy.com/extensions.html might be helpful. The implementation of `KHR_materials_transmission` there could be modified to handle your texture. If you are already generating `.glb` files from your own pipeline maybe it's easier to implement the extension there, but if they're coming from third-party tools like Blender a script like this would be easier than starting from scratch.

**Comment by gjcope** [comment]
Thanks so much for all the help!

**Comment by gjcope** [comment]
@donmccurdy Sorry to resurrect this, but I ran into a question in preparing to put together the extension described above. It looks to me like some parsers (including your Blender importer) discard 'unused' objects unless, in some cases, there is an option to not do so. Some brief testing showed that whether I added the new image object by itself or referenced by an extension as a texture, it was still considered 'unused' as of course the new extension is not supported.

Is potentially losing an image (or other type) asset that is referenced by an unsupported extension through 3rd party import/export just an inherent risk of using said unsupported extensions? It's not a huge deal for us in particular, but would be a bummer to have to take Blender (and possibly other tools) out of our pipeline.

**Comment by donmccurdy** [comment]
You're correct that an image referenced by an unknown extension will appear unused to Blender. I think it's a reasonable feature request for the Blender addon to read/write unused textures, but it doesn't now, and that's probably an inherent risk with DCC tools.

The Blender addon does include some APIs to help you extend it, too, so you could teach it about your extension: https://github.com/KhronosGroup/glTF-Blender-IO/issues/1140#issuecomment-663688371

Blender will also read/write `.extras` (or Custom Properties in Blender terminology) that could contain key/value data. Depending on your workflow that could be a useful way to keep something attached to a material, like the name of the additional texture, so you can re-associate them later. The raw data of the texture cannot go in `.extras`, though.
