### ISSUE TITLE
Add GRIFFEL extension prefix for Griffel Studio

### ISSUE THREAD

**Issue by ibober** [KhronosGroup/glTF#1861]
http://griffelstudio.com/ is planning to develop AEC industry-specific extension for glTF. Please, add GS extension prefix.
@ibober , https://www.linkedin.com/in/kirya/

**Comment by emackey** [comment]
Hi @ibober,

We'd like to avoid adding (more) prefixes that are short enough to be potentially ambiguous.  Would you be able to use a longer extension prefix, such as `GRIFFEL_` or even `GRIF_`?

**Comment by emackey** [comment]
@ibober Is this a reasonable suggestion?  I ask because at least within my normal circles, "GS" stands for Geospatial Solutions, and I think it would be clearer if this prefix were `GRF` or `GRIFFEL` or similar.

**Comment by ibober** [comment]
I understand, sure! `GRIFFEL` is good. Thanks @emackey

**Comment by emackey** [comment]
Done.
