### ISSUE TITLE
Multiple animations from seperate objects?

### ISSUE THREAD

**Issue by lojimoji** [KhronosGroup/glTF#1865]
Hello, Im new to all this and couldn't figure it out. We have a simple car to export as gltf. I want to rotate the tires in the front , and the ones in the back, you know spinning, but they are 2 different objects... How do I do this?? When exported only the ones in the front work. I read here under a similar issue that "If you have two NLA tracks with the same names on different objects, you should get a single merged animation out that affects both." .. I tried to that but nothing changed. 
Here is a screenshot, possibly Im doing something wrong but take a look ...- ah never mind. It worked :) I was using the default name for the tracks: Nlatrack - I changed that on both track to animm and it worked thanks good day

**Comment by donmccurdy** [comment]
Sounds like you solved this, but let us know if you need anything else! :)
