### ISSUE TITLE
KHR_XMP: tighten JSON-LD usage

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#1871]
There are issues of various severity wrt JSON-LD that the XMP extension spec should address asap.

### Define `packets` term

For the `packets` property to be seen by the JSON-LD processing tools, it should be defined in the `@context`. We could use a URN (e.g. `urn:khronos:xmp:packets`), a URL (e.g. `http://schema.khronos.org/xmp/packets`), or a blank node identifier (e.g. `_:packets`). Also since JSON-LD arrays are _unordered_ by default, we need to mark them as ordered by adding `@container` if we want to preserve the semantics:
```json
{
  "@context": {
    "dc": "http://purl.org/dc/elements/1.1/",
    "packets": {
      "@id": "_:packets",
      "@container": "@list"
    }
  },
  ...
}
```

### Expanded term definition

Any term could be defined using an object rather than a string. Such [definition](https://www.w3.org/TR/json-ld11/#expanded-term-definition) could have some extra fields that may conflict with or override (e.g. `@language`) the definitions derived from the IRI. These two examples evaluate alike. Note that enabling `@prefix` is required for expanded definitions in 1.1 processing mode to achieve the same semantics.
```json
{
  "@context": {
    "dc": {
      "@id": "http://purl.org/dc/elements/1.1/",
      "@prefix": true
    },
    "packets": {
      "@id": "_:packets",
      "@container": "@list"
    }
  },
  "packets": [
    {
      "dc:publisher": [
        "Company"
      ]
    }
  ]
}
```

```json
{
  "@context": {
    "dc": "http://purl.org/dc/elements/1.1/",
    "packets": {
      "@id": "_:packets",
      "@container": "@list"
    }
  },
  "packets": [
    {
      "dc:publisher": [
        "Company"
      ]
    }
  ]
}
```

### Clarify JSON-LD version

The latest published version is [JSON-LD 1.1](https://www.w3.org/TR/json-ld11/) dd 16 July 2020. Among other changes it allows specifying JSON-LD version inside a context (note that it's a number):
```json
{
  "@context": {
    "@version": 1.1,
    ...
  },
```
According to the [JSON-LD](https://www.w3.org/TR/json-ld11/#json-ld-1-1-processing-mode) and [JSON-LD Processing](https://www.w3.org/TR/json-ld11-api/#dfn-processing-mode) specs, 1.1 is now the default value.

### Disallow external contexts

In addition to dictionary, JSON-LD allows `@context` to be a string or an array like:
```json
{
  "@context": "myExternalContextDefinition",
  ...
}
```
or
```json
{
  "@context": [
    "myExternalContextDefinition",
    {
      "dc": "http://purl.org/dc/elements/1.1/"
    }
  ],
  ...
}
```
While the existing JSON-Schema prevents that, we should add an extra note to the readme that external contexts are not supported.

### Default vocabulary and base IRI support

Any namespace could be set as default to shorten the document by using `@vocab` keyword. Additionally, there could be a base IRI. Should we support those? For example, these three documents evaluate alike.

```json
{
  "@context": {
    "@vocab": "http://purl.org/dc/elements/1.1/",
    "packets": {
      "@id": "_:packets",
      "@container": "@list"
    }
  },
  "packets": [
    {
      "publisher": [
        "Company"
      ]
    }
  ]
}
```

```json
{
  "@context": {
    "@base": "http://purl.org/dc/elements/",
    "@vocab": "1.1/",
    "packets": {
      "@id": "_:packets",
      "@container": "@list"
    }
  },
  "packets": [
    {
      "publisher": [
        "Company"
      ]
    }
  ]
}
```

```json
{
  "@context": {
    "dc": "http://purl.org/dc/elements/1.1/",
    "packets": {
      "@id": "_:packets",
      "@container": "@list"
    }
  },
  "packets": [
    {
      "dc:publisher": [
        "Company"
      ]
    }
  ]
}
```

### Value objects

Any value inside a packet, could be represented as a value object, so these two examples evaluate alike. Should we support that?
```json
{
  "@context": {
    "dc": "http://purl.org/dc/elements/1.1/",
    "packets": {
      "@id": "_:packets",
      "@container": "@list"
    }
  },
  "packets": [
    {
      "dc:publisher": [
        {
          "@value": "Company"
        }
      ]
    }
  ]
}
```
```json
{
  "@context": {
    "dc": "http://purl.org/dc/elements/1.1/",
    "packets": {
      "@id": "_:packets",
      "@container": "@list"
    }
  },
  "packets": [
    {
      "dc:publisher": [
        "Company"
      ]
    }
  ]
}
```

---

There are probably other edge cases, but resolving these would be a good start.

**Comment by weegeekps** [comment]
Agreed that we should address these asap. A couple thoughts:

I'm interested if some of these points have been fully decided in the discussions taking place for [the JSON-LD serialization of XMP](https://www.iso.org/standard/79384.html). @emilian0, do you or Leonard have any insight here that you can share with us?

I feel like default vocabulary and baseURI support has a negative effect on the flexibility of XMP. I'm comfortable with us saying, "okay, this is allowed," but I believe we should explicitly discourage it. Part of the power of XMP is the ability to quickly mix and match fields from a variety of namespaces. While the Dublin Core covers a lot of the typical cases, I expect a lot of the community will also heavily use the `xmpRights` and hopefully our `model3d` namespace we're creating in 3DCommerce.

**Comment by lexaknyazev** [comment]
Having a default vocabulary doesn't prevent adding more terms with named prefixes.

**Comment by weegeekps** [comment]
In that case I think it should be fine. Only thought that comes to mind is visual display of the fields. Do we expect tools to add the prefix themselves to the field name? In order to properly display the field so a user could reference, I feel like we'd have to do so, but that's added complexity in the output that viewers will have to deal with.

**Comment by lexaknyazev** [comment]
The main concern for viewers is that all prefixes are defined and exist only locally. They could be arbitrarily named and that would still be a valid JSON-LD. The viewers have to expand all names and then compact them to a more convenient form.

Here's a nice tool to see how it works: https://json-ld.org/playground/

**Comment by lexaknyazev** [comment]
Given how compact IRIs are expanded, there are even more options. These three documents represent the same data.
```json
{
  "@context": {
    "dc": "http://purl.org/dc/elements/1.1/",
    "packets": {
      "@id": "_:packets",
      "@container": "@list"
    }
  },
  "packets": [
    {
      "dc:publisher": [
        "Company"
      ]
    }
  ]
}
```
```json
{
  "@context": {
    "foo": {
      "@id": "http://purl.org/dc/elements/1.1/publisher"
    },
    "packets": {
      "@id": "_:packets",
      "@container": "@list"
    }
  },
  "packets": [
    {
      "foo": [
        "Company"
      ]
    }
  ]
}
```
```json
{
  "@context": {
    "foo": "http://purl.org/dc/elements/",
    "packets": {
      "@id": "_:packets",
      "@container": "@list"
    }
  },
  "packets": [
    {
      "foo:1.1/publisher": [
        "Company"
      ]
    }
  ]
}
```

**Comment by weegeekps** [comment]
Thanks for sharing the tool. Playing around with it some cleared up a lot. I'm wondering how many, if any, viewers will actually perform full JSON-LD validation. I actually expect most will just read in the packet and go from there. I do still think we need to ensure that we support JSON-LD properly, or at least as properly as is defined in the JSON-LD Serialization of XMP.

I am planning on trying to purchase a copy of the ISO spec. I [found where I can see it's table of contents](https://www.iso.org/obp/ui/#iso:std:iso:16684:-3:dis:ed-1:v1:en) and it appears to have a section devoted to handling the namespace serialization. I'm curious to know what limitations it has in place. I will report back with my findings as soon as I can.

**Comment by weegeekps** [comment]
That was an easy purchase...

There is a section within the ISO document that explicitly specifies that for JSON-LD serialization of XMP data, the keys should always use Compact IRI form. Given that, we should probably explicitly disallow the usage of `@vocab` and `@base`.

**Comment by lexaknyazev** [comment]
Compact IRI is defined as:
> A compact IRI has the form of prefix:suffix and is used as a way of expressing an IRI without needing to define separate term definitions for each IRI contained within a common vocabulary identified by prefix.

This should exclude prefix-less terms (like the second example in the post above) and expanded IRIs like:
```json
{
  "@context": {
    "packets": {
      "@id": "_:packets",
      "@container": "@list"
    }
  },
  "packets": [
    {
      "http://purl.org/dc/elements/1.1/publisher": [
        "Company"
      ]
    }
  ]
}
```

**Comment by emilian0** [comment]
Thanks @lexaknyazev for bringing up these concerns. I agree that we want to fix the specs to conform with JSON-LD asap. 
As @weegeekps mentioned I think it could be enough to support `enough` JSON-LD as is specified in the XMP serialization via JSON-LD specs. I suggest to be even more restrictive(for instance disallow value objects) to make it easier for viewers to parse the metadata. 
Adam does the JSON-LD serialization of XMP allow value objects or expanded term definitions?
I am going to ping Leonard as well, I agree it would be great to have his take on this. Thanks

**Comment by lexaknyazev** [comment]
I see two perspectives here.

- Must KHR_XMP object be a valid JSON-LD payload? If so, does `packets` array belong to JSON-LD data?
- Could any equivalent JSON-LD document be used instead? (At this point, certainly no.)

JSON-Schema and JSON-LD have a fundamental difference: the former is designed around pre-defined objects with fixed fields, while the latter allows every document to have a unique structure.

**Comment by weegeekps** [comment]
> Adam does the JSON-LD serialization of XMP allow value objects or expanded term definitions?

Yes, value objects are allowed. However, they are neither required or encouraged so I think there is no harm in us disallowing them within KHR_xmp.

> Must KHR_XMP object be a valid JSON-LD payload? If so, does packets array belong to JSON-LD data?

This is a tough question. I can see a case for making the KHR_xmp payload valid JSON-LD. At the same time, I wonder if it's best if `packets` belongs to the extension itself and each object within the array valid JSON-LD.

> Could any equivalent JSON-LD document be used instead? (At this point, certainly no.)

No, and I don't know that this is a goal we should aim for. I would hope that editors and other tools are the primary means of annotating glTF files with XMP metadata, and so static reuse of XMP metadata will be uncommon. This is especially true if we restrict a bit further than the ISO spec currently does, which I believe is probably a prudent action.

**Comment by emilian0** [comment]
>Yes, value objects are allowed. However, they are neither required or encouraged so I think there is no harm in us disallowing them within KHR_xmp.

Great, let's disallow them then! Any objections?

> Could any equivalent JSON-LD document be used instead? 

I side with @weegeekps  => No. My take : it is not necessary , it is too much to require full JSON-LD parsing capabilities from a glTF viewer that wants to display glTF metadata.

> Must KHR_XMP object be a valid JSON-LD payload? If so, does packets array belong to JSON-LD data?

I would love to be able to claim that KHR_xmp conforms with the JSON-LD serialization of XMP as specified by ISO, with added restrictions to keep the glTF format runtime friendly. My take is that, if by adding `"packets": { "@id": "_:packets", "@container": "@list" }` we can make that claim, we should just do it. 
This could open up opportunities to reuse JSON-LD XMP tools with glTF-KHR_xmp. Please let me know your thoughts.

**Comment by lexaknyazev** [comment]
The `packets` term above is made up just to make the content of KHR_XMP visible from a generic JSON-LD perspective. We should check if there's any similar concept in the ISO spec.

Btw, it there an Adobe version of the same document without ISO paywall?

**Comment by emilian0** [comment]
> The packets term above is made up just to make the content of KHR_XMP visible from a generic JSON-LD perspective. We should check if there's any similar concept in the ISO spec.

Thanks. @weegeekps would you be able to confirm? I agree @lexaknyazev if this is just a made up term then there is no value, and now I see your point Adam about having each object within the `packets` being a JSON-LD.

> Btw, it there an Adobe version of the same document without ISO paywall?

I investigated a little, I believe the answer to that is NO.

**Comment by weegeekps** [comment]
The `packets` concept doesn't have anything similar defined within the ISO spec. I don't think there is any harm in us defining it to be visible to the JSON-LD tools however. In the event that a viewer or loader does want to use a JSON-LD library, it's a lot easier for them to just take the entire KHR_xmp chunk object and throw that in as the input. Additionally, it doesn't appear to prevent others from taking the JSON and throwing it into a standard parser; in the case of those users they can simply ignore the `packets` definition within `@context`.

**Comment by lexaknyazev** [comment]
There are two principal questions wrt defining `packets`.

- What's its expanded name? We can choose from URN, URL, or a blank node identifier unless the ISO spec disallows some of these.
- Do we need to enforce that `packets` is ordered on JSON-LD level? If not, we may leave `@context` as-is and simply rename `packets` to always use the expanded name.

**Comment by weegeekps** [comment]
@lexaknyazev, @emilian0, myself, and a few others met this morning to discuss this further. Here are some decisions we've made:

* Individual packets should be JSON-LD compliant.
* Rather than have `@context` at the top, each packet should have it's own `@context`.
* Expanded term definitions are restricted for KHR_xmp.
* Prefixes should only use [A-Za-z0-9_] and should not start with a number or underscore.
* Disallow multiple prefixes for the same namespace and aliases for namespaces.
* Discourage using multiple versions of a namespace.
* Disallow value objects except for the language alternatives use case.
* Require use of `@language` and `@value` within an array for language alternatives.
* Call out in spec that XMP data types are always preferred.
* Define a JSON Schema for KHR_xmp. This includes defining schemas for DC, XMP, xmpRights, etc.

We are hoping this will solve the edge cases we've currently identified.

**Comment by lexaknyazev** [comment]
We may also need to discourage using IRIs for namespace values (i.e. restrict to URLs), see https://www.w3.org/International/wiki/IRIStatus.

**Comment by emilian0** [comment]
As was mentioned today during the call, these issues came up because we attempted to comply with the JSON-LD serialization of XMP as specified by ISO, but we didn't achieve this goal. We could avoid these issues by dropping the support for JSON-LD.

Rationale:
Following the conversation above, I believe we have no intention of supporting the full JSON-LD XMP serialization as specified by ISO (which is still work in progress), mostly because it would be too much of a burden for viewers to parse. Even with the restrictions discussed above to make it easier for viewers to handle JSON-LD packets, we still won't be able to claim that our XMP serialization is a subset of the serialization specified by ISO (it would just be another way to serialize XMPs via JSON-LD). 
At this point it appears to me that making packets comply with JSON-LD would just be an unnecessary burned.
@weegeekps @lexaknyazev (and everyone) please feel free to chime in. Thanks!

**Comment by lexaknyazev** [comment]
> Even with the restrictions discussed above to make it easier for viewers to handle JSON-LD packets, we still won't be able to claim that our XMP serialization is a subset of the serialization specified by ISO (it would just be another way to serialize XMPs via JSON-LD).

With the restrictions and changes above, each element of KHR_XMP's `packets` array will be a valid JSON-LD document compliant with the ISO XMP spec.

**Comment by emilian0** [comment]
> With the restrictions and changes above, each element of KHR_XMP's `packets` array will be a valid JSON-LD document compliant with the ISO XMP spec.
Thanks @lexaknyazev , my concern is that the `packets` concept is purely KHR_xmp (it is not part of JSON-LD serialization of XMP by ISO). But I understand your point, each single packet will be a subset and a valid JSON-LD serialization of XMP). Do you think it is worth making each packet JSON-LD compliant ? Would that enable better interop with the ISO ecosystem?

**Comment by lexaknyazev** [comment]
Here's what would be possible wrt ISO JSON-LD interop.

```js
const packets = gltf.extensions.KHR_XMP.packets;
for (let packet in packets) {
  // process packet with a generic JSON-LD/ISO/XMP tool
}
```

It would be much easier for services like search engines to re-use their existing JSON-LD ecosystem than making something more custom to accommodate the current design. Otherwise, we should remove all references to JSON-LD and still add some of the restrictions mentioned above to improve portability and compatibility of payloads.

**Comment by emilian0** [comment]
Right, I see a value there, thanks. I take it back and I support proceeding as previously planned (making packets JSON-LD compliant).

**Comment by lexaknyazev** [comment]
Fundamentally, there two breaking changes proposed: moving the `@context` inside (so that each packet is a valid JSON-LD document) and requiring a specific form of serializing language alternatives. Here's an example of the latter.

The document defined like
```json
{
  "@context": {
    "dc" : "http://purl.org/dc/elements/1.1/"
  },
  "dc:title" : {
    "en-us" : "MyModel",
    "it-it" : "Mio Modello"
  }
}
```
isn't fully visible to JSON-LD because the keys inside `dc:title` do not start with a prefix and JSON-LD has no knowledge that it's actually a special container. As a result, a JSON-LD parser would return an empty object for `dc:title`.

This could be fixed in two ways. One is to add an extra term definition for every property of language alternative type:
```json
{
  "@context": {
    "dc" : "http://purl.org/dc/elements/1.1/",
    "dc:title" : { "@container": "@language" }
  },
  "dc:title" : {
    "en-us" : "MyModel",
    "it-it" : "Mio Modello"
  }
}
```

The second option is to write language alternative values in their expanded form:
```json
{
  "@context": {
    "dc" : "http://purl.org/dc/elements/1.1/"
  },
  "dc:title" : [
    {
      "@language": "en-us",
      "@value" : "MyModel"
    },
    {
      "@language": "it-it",
      "@value" : "Mio Modello"
    }
  ]
}
```

The ISO spec defines the second approach as the way of serializing XMP language alternatives with JSON-LD.

**Comment by weegeekps** [comment]
Do we have an idea of how widespread usage of JSON-LD is by search engines and other tools? My fear is that we may end up making wide breaking changes for a small subset of the wider community. I do still see the value in supporting JSON-LD, but during our brief discussion yesterday there was definitely some concern that was well placed regarding handling those breaking changes. Given that we do have some production implementors, I'm concerned we will need to continue to support the original schema.

Regarding language alternatives, I think adding an extra term definition is actually a great idea for anything that uses language alternatives. That provides us with a easy path forward for migration from the old schema to the new. The `@context` can be copied into the packet, and then for every field of language alternative type present, we can add the term definition. It does diverge from the ISO spec, but given our situation it seems like a smarter path forward. Updating the implementations to support this change will be far easier than adjusting them to use `@language` and `@value`.

**Comment by weegeekps** [comment]
During the 3DCommerce call this morning there was significant concern regarding breaking changes against the schema at this point. In order to gauge the impact of a breaking change, we're looking at creating a public survey to gauge how widespread is the usage of the current KHR_xmp extension and JSON-LD. From that survey we can decide our next steps for a JSON-LD compliant KHR_xmp extension.

I do think we should continue discussing what a JSON-LD compliant KHR_xmp extension looks like. It feels like eventually we should go that route, but how we get there could be different based on the results of the survey. It's seeming increasingly likely that we will need a different extension (perhaps KHR_xmp_jsonld?) if we make breaking changes regardless, and will need to deprecate the existing KHR_xmp.

**Comment by lexaknyazev** [comment]
Google suggests JSON-LD as the description format for webpages:
https://developers.google.com/search/docs/guides/intro-structured-data

I think it would be easy to miss adding those individual term definitions because they likely won't be enforceable via JSON-Schema. Moreover, they'll probably confuse existing non-JSON-LD parsers anyway.

**Comment by weegeekps** [comment]
Thanks, @lexaknyazev. I still think we should perform the survey but Google SEO is definitely a big impact. I'm not sure I agree with them confusing non-JSON-LD parsers but perhaps I'm missing something. To a JSON parser it should just be a typical JSON object with a key-value pair. I believe the parsers I've used for .NET, JS, Rust, and Cpp would have no issues. Depending on the Java parser used there could be some issues, but most parsers are pretty permissive of unexpected values.

Given the push-back we've seen in both 3DFormats and 3DCommerce if we have to change the schema we will 100% need to coin a new extension and deprecate the existing one. That seemed to be the only palatable path forward for others if we have to make breaking changes.

**Comment by lexaknyazev** [comment]
I mean that currently the `@context` is supposed to contain prefixes as keys and string ids as values. For an expanded term definition there, a key would no longer be a prefix and the value be an object instead of a string.

If we have legitimate concerns about breaking compatibility with existing implementations, we should also ask them what's the actual schema that they support (think all other restrictions). Given numerous edge cases presented earlier, it could be possible that the current implementations are broken anyway.
