### ISSUE TITLE
exporting with armature change the scale!

### ISSUE THREAD

**Issue by mshamaseen** [KhronosGroup/glTF#1873]
It has been a full day now trying to export gltf object with armature, gltf exporter always makes it insanely huge, I've tried everything but it ain't work!

here is the blend file
https://drive.google.com/file/d/1_8SuvIerOYu5Uch4aEJ3HstCGpJZRaMD/view?usp=sharing

and the glb file:
https://drive.google.com/file/d/1fAB6k4b37LqFaw2ZN3z-PjiWKIN61qmc/view?usp=sharing

**Comment by donmccurdy** [comment]
Hi! If you're exporting with Blender 2.80+, then I think you'll want to report this issue on the addon's own repository: https://github.com/KhronosGroup/glTF-Blender-IO

This repository is for the file format, not any particular exporter.
