### ISSUE TITLE
Request for VRMC Vendor prefix

### ISSUE THREAD

**Issue by ousttrue** [KhronosGroup/glTF#1874]
We are making an extension for humanoid avatar models for use in VR.

Prefix: VRMC
Company: VRM Consortium
Website: https://vrm-consortium.org/

We are already in beta and have formulated 1.0.
We will register the extension when 1.0 is available.
https://github.com/vrm-c/vrm-specification/tree/master/specification

**Comment by emackey** [comment]
Done.
