### ISSUE TITLE
Question: Animating TEXCOORD0 value with Morph Targets

### ISSUE THREAD

**Issue by ozgurozansen** [KhronosGroup/glTF#1879]
Is this even possible to animate UV maps of any mesh by changing the TEXCOORD property with morph targets?
Lets say I have two different meshes with exactly same vertex count. These 2 meshes uses the same texture with different UV maps. If I blend these two meshes with a morph target (which is apparently possible), can I also blend their UV maps by blending their TEXCOORD0s? Otherwise, doesn't it supported by the glTF and are there any plans to support this feature? Thanks.

**Comment by donmccurdy** [comment]
Any vertex attribute can have morph targets — including TEXCOORD_0 — but note the word of caution in the spec here:

> "*Currently only three attributes — POSITION, NORMAL, and TANGENT — are commonly supported.*"

I'm not aware of any software that has a concept of morph targets on UVs, regardless of the input format, so you would likely need to implement that yourself.

Perhaps a more common technique would be animating a UV offset defined in [KHR_texture_transform](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_texture_transform)? There's similarly no way to include animation of a UV offset in a glTF file currently, but this is something that could be scripted in your application or requested from glTF in the future.
