### ISSUE TITLE
KHR_draco_mesh_compression attributes

### ISSUE THREAD

**Issue by Siccity** [KhronosGroup/glTF#1880]
I am writing an importer, currently trying to load weights and joints correctly from a draco compressed primitive.
I am using [DracoMeshLoader.cs#L255-L271](https://github.com/google/draco/blob/7e25df9c21bffb9aad89ecbea7677dfeadc791b0/unity/DracoMeshLoader.cs#L255-L271) as reference.

From the sample models repository, I managed to extract most weights using AttributeType.GENERIC with index 1, and joints as AttributeType.GENERIC with index 0. However, when importing files from other sources these indexes are switched around. Weights will be 0 and joints will be 1. I don't know where to determine which index to use. I thought it would be the associated attributes in the gltf file but they don't seem to correlate at all.

How do I determine the generic attribute index of weights and joints when importing a draco file?

```json
// model: personal test file test1.glb
// weights: 0
// joints: 1

"KHR_draco_mesh_compression": {
	"bufferView": 0,
	"attributes": {
		"POSITION": 0,
		"NORMAL": 1,
		"TEXCOORD_0": 2,
		"WEIGHTS_0": 3,
		"JOINTS_0": 4
	}
}
```
```json
// model: sample BrainStem.gltf
// weights: 1
// joints: 0

"KHR_draco_mesh_compression": {
	"bufferView": 16,
	"attributes": {
	"JOINTS_0": 0,
	"NORMAL": 1,
	"POSITION": 2,
	"WEIGHTS_0": 3
	}
}
```

**Comment by donmccurdy** [comment]
The `KHR_draco_mesh_compression.attributes` property contains the unique IDs for each attribute in the primitive — the IDs can vary from mesh to mesh, so you must always use the IDs given by this property. Note that the Draco library provides two independent ways to look up a property:

1. `GetAttributeByUniqueId`
2. `GetAttributeId` + `GetAttribute`

glTF files should always be decoded using (1). Here is another example, if it's helpful:

https://github.com/donmccurdy/glTF-Transform/blob/d5168745f8d214c294cc2c6e53cf20d40f85b2e0/packages/extensions/src/khr-draco-mesh-compression/draco-mesh-compression.ts#L64-L74

**Comment by Siccity** [comment]
Ah! I didn't know of the GetAttributeByUniqueId. I think that was my missing piece! I will check it out tomorrow and close this issue if it solved my issue.

Thanks!
