### ISSUE TITLE
Question about unlit extension

### ISSUE THREAD

**Issue by robotjam** [KhronosGroup/glTF#1882]
I've been trying to work out how to use the unlit extension in blender but I'm totally lost, I've looked around and cant see any documentation about how you used it with the shader editor. Any help would be really appreciated.

**Comment by donmccurdy** [comment]
This repository is for the glTF file format — for issues with the glTF Blender addon, you would want to file issues on https://github.com/KhronosGroup/glTF-Blender-IO to reach the right people.

From the [Blender docs](https://docs.blender.org/manual/en/2.90/addons/import_export/scene_gltf2.html):

> To create Shadeless (Unlit) materials, use the Background material type.

[Other options](https://github.com/KhronosGroup/glTF-Blender-IO/pull/1209) will be available in an upcoming release. Alternatively, you can export a normal PBR material and convert it to unlit with https://glb-packer.glitch.me/ or https://gltf-transform.donmccurdy.com/cli.html.
