### ISSUE TITLE
Deprecate specific modes in mesh in future glTF

### ISSUE THREAD

**Issue by McNopper** [KhronosGroup/glTF#1883]
In a future version of glTF, following type of primitives should be removed:
- LINE_LOOP
- TRIANGLE_FAN

see https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/mesh.primitive.schema.json

Reason for this is, that modern graphics API's do not directly support these types:
Metal https://developer.apple.com/documentation/metal/mtlprimitivetype
WebGPU https://gpuweb.github.io/gpuweb/#primitive-topology
Vulkan https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#drawing-primitive-topologies

This change does reduce the complexity for a glTF compliant renderer and the removed features should be resolved in the tool exporters.

**Comment by lexaknyazev** [comment]
Closing for the same reasoning as in https://github.com/KhronosGroup/glTF/issues/1471#issuecomment-942578002.
