### ISSUE TITLE
Question: Video/Image Sequence/GIF to be used as a Texture in GLTF

### ISSUE THREAD

**Issue by shaykh-qasim** [KhronosGroup/glTF#1895]
Hello, 

I have a Television model in **GLTF**, I want to use a **video as a texture** in the tv screen, how can I do so? What extension is to be used and how can I implement it? 
Or **any workaround** to achieve something similar if the image sequence as textures is not supported?

Thanks.

**Comment by donmccurdy** [comment]
Hi @shaykh-qasim — there is not an official extension for video textures in glTF. Depending on the 3D engine you're using, you could certainly load a model and then attach a video texture to a specific submesh, e.g. a TV "screen". To do this, you'll probably get better help from the forums of whatever 3D framework you use.

It would also be possible to implement a custom extension, similar to the discussion in https://github.com/KhronosGroup/glTF/issues/1859. This is a bit more advanced.

Finally, you can show a sequence of static images with flipboard-style animation. A quick way to set that up would be to export one mesh+texture for each frame, then animate them with the `sequence` command in the [glTF-Transform CLI](https://gltf-transform.donmccurdy.com/cli.html).

**Comment by j-conrad** [comment]
Regarding the 'flipboard-style' animation technique, there is an add-on for Blender made by Mozilla that allows you to attach a component called **uv-scroll** with simple controls to specify offset increments. When you export from Blender as a .glb, the component will be embedded in the model as a glTF extension. (This add-on also adds support for lightmaps, among other features.)
The Blender add-on: 
https://github.com/MozillaReality/hubs-blender-exporter

Using **uv-scroll**:
https://www.youtube.com/playlist?list=PLCxaiaRxTL69_GbaTY0RElleY37oeooSh

**Comment by donmccurdy** [comment]
Thanks @j-conrad!

@shaykh-qasim let us know if you have other questions, or the Slack or Forums (https://community.khronos.org/) can be a good place for open-ended discussions.
