### ISSUE TITLE
"OpenGL conventions" aren't really "+X is right and +Y is up. +Z points toward the viewer"

### ISSUE THREAD

**Issue by jdashg** [KhronosGroup/glTF#1902]
This is the GLU convention but by default, OpenGL's clip space with default DEPTH_TEST is +Z *away* (far). (Yes it's left-handed!)
Here's an example with the default clip-space and DEPTH_TEST: https://jdashg.github.io/misc/webgl/webgl-clipspace.html

**Comment by bghgary** [comment]
I'm not sure I understand what you are getting at. Are you saying there is an issue with the spec? If so, can you point out where in the spec there is an issue?

**Comment by jdashg** [comment]
The quoted text is from the spec (I think) here: https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#materialnormaltexture

Assuming this text is normative, it needs to be clarified. It cannot be both "OpenGL conventions" and "+Z points toward the viewer".

**Comment by bghgary** [comment]
Ahh, you are talking about the normal texture. Do you want to open a PR to clarify and we can discuss in the PR?

The text that should be modified is here: https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/material.schema.json#L18

We are in the middle of doing to updates to the generated parts of the spec, so I'm not sure the spec README itself should be modified right now. @emackey?

**Comment by jdashg** [comment]
Will do!
