### ISSUE TITLE
Specular Glossiness and Metallic Roughness formulas give different results

### ISSUE THREAD

**Issue by Gpinchon** [KhronosGroup/glTF#1903]
I've tried to implement the two different workflows, given here : 
https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_materials_pbrSpecularGlossiness/README.md
https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#appendix-b-brdf-implementation

I ended up with this code for Spec-Gloss : 
```
SetCDiff(values.Diffuse.rgb * (1 - max(values.Specular.r, max(values.Specular.g, values.Specular.b))));
SetF0(values.Specular);
SetAlpha(pow(1 - values.Glossiness, 2));
```
And this code for Metal-Rough :
```
SetCDiff(mix(values.BaseColor.rgb * (1. - 0.04), vec3(0), values.Metallic));
SetF0(mix(vec3(0.04), values.BaseColor.rgb , values.Metallic));
SetAlpha(values.Roughness * values.Roughness);
```
But these formulas give me different results when they shouldn't...
For F0 : 
![F0](https://user-images.githubusercontent.com/8039212/99191825-b8c98600-276f-11eb-86d4-a5ca2c0ba7df.PNG)
For Alpha (seems right) :
![alpha](https://user-images.githubusercontent.com/8039212/99191834-c67f0b80-276f-11eb-9eac-16267c43826e.PNG)
For CDiff :
![CDiff](https://user-images.githubusercontent.com/8039212/99191855-dac30880-276f-11eb-82f2-f596845fae02.PNG)

The model I used : https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SpecGlossVsMetalRough

**Comment by bghgary** [comment]
I'm just guessing, but perhaps the rgb values are not in linear space in the shader?

**Comment by Gpinchon** [comment]
Sorry for the late response, both shaders are bound and compiled the same way with the same flags, do you mean the output rgb or the textures ? All textures are RGB8 or RGBA8 and UNORM, but maybe I am missing something...
Also, after reworking the lighting of my engine, I got this result, which looks "kind of" the same I guess...
![specglossmetalrough result](https://user-images.githubusercontent.com/8039212/100892559-bfb7fe80-34ba-11eb-9498-54ee67849801.PNG)
Is this rendering valid or are they supposed to look exactly the same ?
Environment used : Footprint Court from hdrlabs + 1 directionnal light.

**Comment by bghgary** [comment]
> do you mean the output rgb or the textures ?

The interpretation of the textures in the shader. The baseColor textures from MR, diffuse/specular textures from SG are stored as sRGB whereas the remaining textures (e.g. metallic/roughness texture, occlusion, normal, etc.) are stored in linear space. If this isn't done right, there will be differences.

> Is this rendering valid or are they supposed to look exactly the same ?

It's hard to tell with this screenshot because it's so dark. There is probably something wrong since it should not be so dark with the footprint environment (even without a directional light). Also, the specular on the red cap doesn't look the same to me.

**Comment by Gpinchon** [comment]
> The interpretation of the textures in the shader. The baseColor textures from MR, diffuse/specular textures from SG are stored as sRGB whereas the remaining textures (e.g. metallic/roughness texture, occlusion, normal, etc.) are stored in linear space. If this isn't done right, there will be differences.

Ah ! I will look into that then ! I am using SDL2_Image to load the textures and I think it might overlook the embedded calibration...

> It's hard to tell with this screenshot because it's so dark. There is probably something wrong since it should not be so dark with the footprint environment (even without a directional light). Also, the specular on the red cap doesn't look the same to me.

Ah yes sorry, the output of my engine is linear, I turned off sRGB output for now, which is why it's so dark.
I will post update as soon as I fixed my issue, it could be useful for anyone encountering the same issue.

**Comment by emackey** [comment]
Let us know if you find a mistake in the formulas.  Thanks!
