### ISSUE TITLE
Extensions implementation

### ISSUE THREAD

**Issue by Siccity** [KhronosGroup/glTF#1921]
I am writing an importer in C#, and I want to support third party extensions.
What is the best way to approach this?

Do I need to carefully insert a slew of delegate 'hooks' that a plugin can regiser to, or should i perform standard import if possible, and then call the extension afterwards? Or call it before standard import?
Is there a general rule of when to inject the extensions, and what happens if multiple conflicting extensions are present?

**Comment by bghgary** [comment]
Probably better to use the [forums](https://community.khronos.org/c/gltf-general) for this question as GitHub issues are for the specification.

**Comment by Siccity** [comment]
Thank you, I asked on the forums

**Comment by bghgary** [comment]
For reference, this is the forum thread: https://community.khronos.org/t/extensions-implementation/106656
