### ISSUE TITLE
Transmission example snippet doesn´t match the spec

### ISSUE THREAD

**Issue by technik** [KhronosGroup/glTF#1924]
In the readme for KHR_materials_transmission, under the Extending Materials section, there is a code snippet that reads like this:

```
materials: [
  {
    "extensions": {
       "KHR_materials_transmission": {
         "transmissionFactor": 0.8,
         "transmissionTexture": 0
       }
    }
  }
]
```
transmissionTexture is an int index there, but according to the spec it should be a texture info, so the correct version would be:
```
materials: [
  {
    "extensions": {
       "KHR_materials_transmission": {
         "transmissionFactor": 0.8,
         "transmissionTexture": {
           "index": 0
         }
       }
    }
  }
]
```

**Comment by bghgary** [comment]
Good catch. https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_transmission#extending-materials

Would you like to open a PR to fix it since you found it?

**Comment by emackey** [comment]
Thanks @technik!
