### ISSUE TITLE
What if there are some vertices have zero weight sum in a skinned mesh?

### ISSUE THREAD

**Issue by shrinktofit** [KhronosGroup/glTF#1929]
The spec says:

> The joint weights for each vertex must be non-negative. No joint may have more than one non-zero weight for a given vertex.

I have a FBX model in which there are some vertices are not affected by any joints in a skinned mesh:
[character_01_sit.zip](https://github.com/KhronosGroup/glTF/files/5799932/character_01_sit.zip)

Convert this FBX into glTF, using FBX2glTF, a vertex that is not affected by any joints has:
```
JOINTS_0  (0, 0, 0, 0)
WEIGHTS_0 (0, 0, 0, 0)
```

Our engine incorrectly render this sort of vertices but [three.js](https://threejs.org/editor/) does. I found that three.js treat `WEIGHT_0` as `(1, 0, 0, 0)` if its components are all zero: https://github.com/mrdoob/three.js/blob/4457273fe29f5b4b56dee33270986ee94947c0f2/build/three.js#L19622. And it works perfectly at least for this model. `(1, 0, 0, 0)` means **the first affecting joint(usually the `0` joint ) deforms this vertex in full weight**. I wonder if this is intended or just work?

**Comment by shrinktofit** [comment]
I also posted a similar question on FBX forum: https://forums.autodesk.com/t5/fbx-forum/what-if-there-are-some-vertices-not-affect-by-any-bones-in-a/td-p/9994873

**Comment by emackey** [comment]
[The spec says](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#skinned-mesh-attributes) that weights must sum to 1.0. The exact wording here was recently refined a bit in #1749.  So I think the model is technically invalid if it supplies all zero weights.  Does the glTF Validator flag your model with this problem?

Side note, the Blender exporter has a related issue: https://github.com/KhronosGroup/glTF-Blender-IO/issues/1151

**Comment by lexaknyazev** [comment]
@shrinktofit 
A glTF asset with weights sum that isn't `1.0` is invalid. Therefore, rendering result is undefined.

@donmccurdy
Do you have any insights into three.js approach of replacing weights with `(1, 0, 0, 0)`?

**Comment by donmccurdy** [comment]
It looks to me like three.js just avoids avoids transforming the vertex when given `0,0,0,0` as weights:

https://github.com/mrdoob/three.js/blob/66b9fa344ce01581033d171e1de09dd86bd5a3d7/src/renderers/shaders/ShaderChunk/skinning_vertex.glsl.js

@shrinktofit would that explanation fit the behavior you're seeing, or does it really seem to be weighted to the first bone somehow?

**Comment by shrinktofit** [comment]
@donmccurdy  

I saw it from source code.

If all components are zero, replaced with `(1, 0, 0, 0)`:

https://github.com/mrdoob/three.js/blob/94c1a4b86f53c91b61ec4ca3299b4ad02422ddb8/src/objects/SkinnedMesh.js#L77-#L104

three.js marked it as `// do something reasonable`.

Yes replacing with `(1, 0, 0, 0)` avoids zero vertex position. But it does indeed take the "first"(`JOINTS_0[0]`) bone transformation.

---------

Applying to FBX loader:

https://github.com/mrdoob/three.js/blob/4457273fe29f5b4b56dee33270986ee94947c0f2/examples/js/loaders/FBXLoader.js#L1223-L1224

**Comment by donmccurdy** [comment]
Ah you're right, thanks. The reasoning for this is discussed in https://github.com/mrdoob/three.js/issues/15319. We're aware that glTF doesn't allow this case, but we do see models with this problem anyway and try to handle it for glTF and other formats.

**Comment by lexaknyazev** [comment]
No spec action here. Engines are free to fix incorrect assets as they see fit.
