### ISSUE TITLE
Broken GLTF Model

### ISSUE THREAD

**Issue by ManishJu** [KhronosGroup/glTF#1932]
The GLTF toy car model when imported in the latest release or developments builds of Blender imports 8 extra cameras with it :
Link to model : https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/ToyCar
Tested with Blender 2.83, 2.91, 2.92 beta
Screen shot in Blender :
![gltf bug](https://user-images.githubusercontent.com/24234466/104927732-b0710f80-5999-11eb-960d-1be27c3d18b0.PNG)

**Comment by emackey** [comment]
This particular toy car is quite small, about 4cm long in fact, not even 2 inches long.  Perhaps the size could use some adjustment, but that's what's in the model currently.

Blender's default camera icon is 1 meter long.  So the cameras you see here are some 25 times as large as the car.

Multi-select all of the cameras, by clicking the top one in the list and then shift-clicking the bottom one:

![Blender-many-cameras-1](https://user-images.githubusercontent.com/1235080/104932411-9a515800-5975-11eb-9b0e-8d59c60e716a.png)

The top one turns yellow, this is the "active" one.  The rest are a reddish-orange, these are "selected" ones.  Go into camera properties, Viewport options, and change the size to 0.01m.  Only the "active" camera will change.

![Blender-many-cameras-1b](https://user-images.githubusercontent.com/1235080/104932794-1350af80-5976-11eb-8e82-a7069a40df66.png)

Then right-click the size and select "Copy to Selected":

![Blender-many-cameras-2](https://user-images.githubusercontent.com/1235080/104932918-39764f80-5976-11eb-8c53-257a61e19c84.png)

All of the cameras should look smaller now.

![Blender-many-cameras-2b](https://user-images.githubusercontent.com/1235080/104933641-2adc6800-5977-11eb-815c-08c3410c4419.png)

To try out the different cameras, select only a single camera from the list, and press CTRL - NUMPAD 0.  The chosen camera will become the new default camera, and the viewport will zoom to look through its lens.

**Comment by lexaknyazev** [comment]
@emackey 
Maybe we should also mention multiple cameras is the asset's readme.
