### ISSUE TITLE
KHR_materials_variants: Why is mappings not an array of material ids?

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/glTF#1937]
I suspect this is too late to change, but I thought I'd at least ask what the rationale is.

When looking at the variants extension, it seems to me that the core idea is very simple:

- On a scene level, an array of named variants is declared
- On a primitive level, for each variant there's an override that replaces the original primitive.material reference with a variant-specific one

The simplest way to model this would be to specify an array of material indices that matches the length of the variants array. This is consistent with e.g. how morph targets are defined.

So instead of:

```
        "extensions": {
          "KHR_materials_variants" : {
            "mappings": [
              {
                "material": 2,
                "variants": [0, 3],
              },
              {
                "material": 4,
                "variants": [1],
              },
              {
                "material": 5,
                "variants": [2],
              },
            ],
          }
        }
```

You'd simply have:

```
        "extensions": {
          "KHR_materials_variants" : {
            "mappings": [2, 4, 5, 3]
          }
        }
```

This is much more concise, and also simpler to represent in-memory as instead of an array-of-structs-that-contains-an-array you just have an array of primitives, which is quicker to parse and more efficient to store. It's also the natural runtime representation for engines that want to support switching between different variants.

Any holes in the mappings array can just be plugged with the primitive material.

Why was the current representation chosen?

**Comment by donmccurdy** [comment]
I can speculate that one advantage of the more verbose layout might be the ability to associate application data (extras, or other extensions?) with a primitive:variant mapping. For example, a model of a car with `[basic, standard, deluxe]` variants might contain different captions for the seats in each variant, describing features specific to that variant. There would be no obvious place to store that information if the mappings were simply integers, although something like another parallel array could still be contrived.

But, I have no idea if that was the original motivation. @jercytryn, @sleroux, or @pushmatrix might be able to say. I suspect it is too late to change in any case, at least for the current extension within glTF 2.0. We can always use feedback for future specification versions.

**Comment by sleroux** [comment]
> I can speculate that one advantage of the more verbose layout might be the ability to associate application data (extras, or other extensions?)

This was one of the primary motivators behind moving in this direction vs using an index-based integer array. In fact the [glTF 2.0 schema ](https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_materials_variants/schema/glTF.KHR_materials_variants.schema.json) does include `extras` and `extensions` as possible extension points for each of these dictionaries. As far as how these would be used, there were some thoughts that configurator programs would be able to associated additional metadata into these fields if needed.

**Comment by zeux** [comment]
Thanks! I see the reasoning, although it still makes me wonder whether an array would be better - there's already a precedent for morph targets to use array-based named annotations, and I don't think extensibility through "extensions" is something that will happen in glTF seeing as there's no precedent for nested extensions.

For my use case it ocurred to me that a slightly flatter representation of a list of pairs is still reasonably convenient to work with internally, so I can represent the inner arrays of variants as multiple entries in the mappings array. It's not perfect but it's easier to work with than the raw glTF representation.
