### ISSUE TITLE
KHR_materials_variants: Uniqueness of material indices is overly strict

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/glTF#1941]
KHR_materials_variants contains the following language:

> Across the entire mappings array, each variant index and each material must be used no more than one time.

It makes sense that the variant index must be used no more than one time - duplicate indices would create ambiguity.
However, I don't think the specification should restrict the duplicate occurrence of materials.

Per #1937, mappings are represented as objects to allow for application extensibility - to specify data with `extras`.
The restriction above maintains that an application must use the same extras data for any two variants that happen to have an identical material (or duplicate the material).

This is overly restrictive; if the extras data contains variant/mesh-specific annotations, this data doesn't have to match between different variants even if they use the same material.

I propose to change the language to:

> Across the entire mappings array, each variant index must be used no more than one time.

Since this is a relaxation of the current requirements, it shouldn't present compatibility issues wrt assets, assuming that existing implementations don't have the same restriction internally.

**Comment by lexaknyazev** [comment]
Probably the intention was to force exporters to group mappings per-material. Otherwise there would be no need for `variants` to be an array.

I agree that such a restriction goes directly against extensibility goal.

/cc @jercytryn, @sleroux, @pushmatrix, @donmccurdy
