### ISSUE TITLE
bufferView for indices. Is there any rules where indices are located in buffer? 

### ISSUE THREAD

**Issue by NukeBird** [KhronosGroup/glTF#1942]
Hello everyone! 

While coding glTF parser using test models and official tutorials I got a question. Can I assume that all EBOs will be located at the beginning of buffers? 

Currently I'm using buffers as VBOs, bufferView and accessors are just some kind of metadata to get offsets, strides and etc. and primitives are actual VAOs. Even in modern OpenGL it seems VAO can be located only at the beginning of buffer (there is no offset argument in glVertexArrayElementBuffer(GLuint vaobj, GLuint buffer))

If this assumption is wrong please tell me how to do it right

And one more question: should I really load buffers as VBOs? Or should I load bufferViews as VBOs instead? In this case I will get more small buffers and will be sure EBO will get dedicated buffer. Though I'm not sure if its good or not (maybe 1 buffer for multiple primitives will be better?)

**Comment by lexaknyazev** [comment]
- glTF's buffers correspond to binary files (or BIN chunks in GLB)
- glTF's buffer views with attributes correspond to GPU array buffers
- glTF's buffer views with indices correspond to GPU element array buffers

Besides geometry, glTF's buffers may contain image, animation, and skinning data.

**Comment by NukeBird** [comment]
Oh! So my last guess wasn't wrong at all and I should interpret buffers like some kind of data located in CPU memory. It makes a lot of sense now, thank you!

Hm... If talking about animations/samplers/etc. I do understand how skinning works on CPU side, but can I actually load animators to video memory and do all the animation on GPU? Or it doesn't make sense?

> glTF's buffer views with attributes correspond to GPU array buffers

I checked tinygltf's implementation and seems bufferView::target can be one of GL_VERTEX_ARRAY/GL_ELEMENT_ARRAY_BUFFER so I can differentiate VBOs and EBOs (seems like official tutorial saying the same). But how then I can figure out is it image/animation something else? Maybe there are some kind of marks? Will be cool to be able greedly load all the data without looking to other meta structs

**Comment by NukeBird** [comment]
> But how then I can figure out is it image/animation or something else? 

Wait, hold up. Target is optional? If so its not a trouble at all

**Comment by lexaknyazev** [comment]
> can I actually load animators to video memory and do all the animation on GPU?

Why not? Assuming that SSBO support is available, an application could offload as much work to GPU as it wants.

> Target is optional?

Yes and it's actually a potential issue: some exporters omit it even for GPU-designated buffer views.

**Comment by NukeBird** [comment]
> Yes and it's actually a potential issue: some exporters omit it even for GPU-designated buffer views.

Oh... Sad to know :(

Anyways, thank you for help!
