### ISSUE TITLE
Request OFT vendor extension prefix

### ISSUE THREAD

**Issue by chubei-oppen** [KhronosGroup/glTF#1957]
Hi there, we hope to register a vendor extension prefix. We're using glTF to deliver 3D models for ecommerce businesses.

- The name of the prefix: OFT
- The name of the vendor using the prefix: OppenFuture Technologies
- Vendor's contact information: https://www.hololux.cn/en/

**Comment by donmccurdy** [comment]
Opened https://github.com/KhronosGroup/glTF/pull/1963 — any concerns with this prefix?

**Comment by chubei-oppen** [comment]
Thanks @donmccurdy. We’re trying to define extensions to suit special needs for certain models, for example [16 bit normal map](https://github.com/oppenfuture/glTF/tree/hpnormal/extensions/2.0/Vendor/OFT_texture_highPrecisionNormal) (I know it sounds strange).

**Comment by lexaknyazev** [comment]
@chubei-oppen 
Nothing strange about that. What platforms are you targeting? With most native APIs, one could use 16-bit PNG normal maps and upload them as UNORM16 texture format. No glTF modifications are required to enable this path. Unfortunately, this is not possible in WebGL yet.

**Comment by chubei-oppen** [comment]
Yes out target platforms include WebGL. We're hoping to deliver one model for as many platforms as possible.
