### ISSUE TITLE
question: How to maintain the models parent-child tree structure in GLTF?

### ISSUE THREAD

**Issue by AtticusLv** [KhronosGroup/glTF#1961]
I have a model, it's format is IFC. In IFC format , model has a parent-children tree structure, 
.eg 
ParentModel
|- Child1Model
    |- Child1-1Model
|- Child2Model
|- Child3Model

But when it is converted into GLTF model, the whole structure turns into a flat one.

Is there any way to get the structure info in gltf?

**Comment by javagl** [comment]
I think that will largely depend on the tool that you are using to convert the input into a glTF asset. In glTF, each "model" (i.e. each `mesh`) is attached to a `node`, and it's certainly possible to represent such a hierarchy.
