### ISSUE TITLE
Request for Prefix: "CITRUS"

### ISSUE THREAD

**Issue by KenzieMac130** [KhronosGroup/glTF#1962]
Hello, I am requesting to register the `CITRUS` prefix for extensions produced for my engine [Citrus Toolbox](https://github.com/KenzieMac130/CitrusToolbox).

The engine is targeting a _bring your own tools_ approach to game content rather than use a central editor. glTF will be used heavily throughout the asset pipeline. The glTF format will need to be extended internally for various uses, such as:

* Object spawners
* Special material support
* Extended lighting features
* Middleware integration
* Physics and Collision
* Particle effects
* Audio sources
* Curves
* Navigation
* Level logic
* Etc.

Info:

* Prefix: CITRUS
* Project Name: Citrus Toolbox
* Link: https://github.com/KenzieMac130/CitrusToolbox

Thank you for your' time!

**Comment by donmccurdy** [comment]
Sorry for the delay in response here — I've opened https://github.com/KhronosGroup/glTF/pull/1996 to add this to the prefix registry. 👍
