### ISSUE TITLE
Material Variant - Unable to Switch Between Two Transparent Materials

### ISSUE THREAD

**Issue by methot-ilya-3ds** [KhronosGroup/glTF#1965]
I noticed unusual behavior in my object as I was using the Material Variant extension.

In this example I am trying to change the materials of two meshes, "Red Glass" and "Reflectors" using material variant extension. The materials should be changed to "Invisible" which is a material that is completely transparent (Alpha channel of 0)

The problem is that neither Red Glass or Reflectors successfully switch to the transparent material. Instead, they remain the same color and texture throughout all the 7 variants that I have setup.

Here are the materials in question:
<details>
<summary> Materials </summary>

```
{
      "alphaMode": "BLEND",
      "doubleSided": true,
      "emissiveFactor": [
        0,
        0,
        0
      ],
      "name": "RedGlass",
      "pbrMetallicRoughness": {
        "baseColorFactor": [
          0.4941176176071167,
          0,
          0,
          0.5
        ],
        "metallicFactor": 1,
        "roughnessFactor": 0.21808511018753052
      }
    },
    {
      "alphaMode": "BLEND",
      "doubleSided": true,
      "emissiveFactor": [
        0,
        0,
        0
      ],
      "name": "Invisible",
      "pbrMetallicRoughness": {
        "baseColorFactor": [
          0,
          0,
          0,
          0
        ],
        "metallicFactor": 0,
        "roughnessFactor": 0.5
      }
    },
    {
      "alphaMode": "BLEND",
      "doubleSided": true,
      "emissiveFactor": [
        0,
        0,
        0
      ],
      "name": "Yellow",
      "pbrMetallicRoughness": {
        "baseColorFactor": [
          1,
          0.6000049710273743,
          0,
          0.75
        ],
        "metallicFactor": 0,
        "roughnessFactor": 1
      }
    },
```

</details>

and the meshes

<details>

<summary> Meshes </summary>

```
{
      "name": "RedGlass",
      "primitives": [
        {
          "attributes": {
            "POSITION": 0,
            "NORMAL": 1
          },
          "extensions": {
            "KHR_materials_variants": {
              "mappings": [
                {
                  "material": 0,
                  "variants": [
                    0
                  ]
                },
                {
                  "material": 2,
                  "variants": [
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7
                  ]
                }
              ]
            }
          },
          "indices": 2,
          "material": 0
        }
      ]
    },
{
      "name": "Reflectors",
      "primitives": [
        {
          "attributes": {
            "POSITION": 11,
            "NORMAL": 12,
            "TEXCOORD_0": 13
          },
          "extensions": {
            "KHR_materials_variants": {
              "mappings": [
                {
                  "material": 3,
                  "variants": [
                    0
                  ]
                },
                {
                  "material": 2,
                  "variants": [
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7
                  ]
                }
              ]
            }
          },
          "indices": 14,
          "material": 3
        }
      ]
    }
```

</details>

**Comment by donmccurdy** [comment]
Hi @methot-ilya-3ds — It sounds like you're describing a bug in some particular piece of software (which software?). You're correct that a material with alpha of 0 should not be visible. Reporting the issue directly to the software's authors may be necessary to get help; this repository is about the design and specification of the file format itself.

**Comment by methot-ilya-3ds** [comment]
I thought that there may be an issue in how the Material Variant Extension handles switching between two these two materials. It seems that the bug is related to the extension itself since otherwise the extension is able to switch from material to material just fine with a majority of other materials.  

I think my use-case is a fringe scenario anyway so let's just shelf this bug unless someone else comes forward with the same problem.

**Comment by donmccurdy** [comment]
The [`KHR_materials_variants` extension](https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_materials_variants/README.md) only defines what _should_ be done by an implementation of the extension. It is just a written document with technical details, not code, and it is up to an engine (e.g. Unity, Unreal, three.js, etc.) to implement that correctly. Certainly, switching to an invisible material should hide the object as you say. :) If this is not the case then the bug must be reported to model viewer: https://github.com/google/model-viewer/issues.
