### ISSUE TITLE
x orientation button missing

### ISSUE THREAD

**Issue by mike44** [KhronosGroup/glTF#1967]
When I export my blend files from a x-plane addon the addon is back forwarded. F.ex. my airplane sits inverted with the back forward on the runway in FS2020 but is fine in X-Plane.
Could we get a switch alike the y up for the x axis in the Blender exporter? Many thanks

**Comment by javagl** [comment]
This repository is for the glTF standard itself. When you talk about a feature request for the blender exporter, I assume that this should be discussed in https://github.com/KhronosGroup/glTF-Blender-IO . If nobody disagrees, I think this one can be closed.

**Comment by donmccurdy** [comment]
Following up in https://github.com/KhronosGroup/glTF-Blender-IO/issues/1375.
