### ISSUE TITLE
May "BIN" chunk be present, with chunkLength=0?

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF#1975]
The specification is clear that [buffer.byteLength](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#bufferbytelength-white_check_mark) must be ≥1. However, it is less clear whether the "BIN" chunk must have non-zero length, if it is not referenced by a buffer. This question becomes relevant when serializing a file without binary data, e.g. containing only a camera, a light, or a node hierarchy, as there are two ways to approach it:

1. Omit the BIN chunk.
2. Include the BIN chunk with zero length, and do not write any buffers to the root JSON object.

Testing briefly, both ways appear to be supported in common web viewers.

**Comment by lexaknyazev** [comment]
For consistency, zero-length BIN chunks should not be used since they cannot be referenced anyway.

**Comment by donmccurdy** [comment]
Sounds good to me. I was curious whether any GLB readers would fail — the BIN chunk is not required, but omitting it is probably very rare — but couldn't find examples while testing. Is it worth clarifying this in the spec, perhaps with "SHOULD" rather than "MUST" language?

**Comment by lexaknyazev** [comment]
The clarification has been included in the new spec draft.
