### ISSUE TITLE
glTF json with chinese characters:  escaped? unescaped?

### ISSUE THREAD

**Issue by vpenades** [KhronosGroup/glTF#1978]
Short question is, which one of those is correct?  are both correct?

```json
"meshes" : [
      {
         "name" : "你好",          <-unescaped?
         "primitives" : [, , , ]
      },
      {
         "name" : "\u4f60\u597d",  <-escaped?
         "primitives" : [, , , ]
      }
]
```

**Comment by bghgary** [comment]
According to https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#json-encoding:

> All strings defined in this spec (properties names, enums) use only ASCII charset and must be written as plain text, e.g., "buffer" instead of "\u0062\u0075\u0066\u0066\u0065\u0072".
> > **Implementation Note**: This allows generic glTF client implementations to not have full Unicode support. Application-specific strings (e.g., values of "name" properties or content of extras fields) may use any symbols.

@lexaknyazev Any other comments?

**Comment by lexaknyazev** [comment]
@vpenades 
These two names are identical from JSON point of view.

**Comment by vpenades** [comment]
@lexaknyazev yes, they're the same, and by default the json writer I'm using writes "\u4f60\u597d" ... but I was asked if it could be possible to write strings unescaped, as in "你好" ... so before doing it, I wanted to be sure if this is something allowed by the schema.

@bghgary just clarified it to me:  if the schema only supports ASCII characters for compatibility, then "\u4f60\u597d" is legal, and "你好" is not.

**Comment by lexaknyazev** [comment]
It's still valid to write `"你好"` as a value as long as the file uses UTF-8.

**Comment by vpenades** [comment]
> It's still valid to write `"你好"` as a value as long as the file uses UTF-8.

From the spec, provided by bghgary:  "_All strings defined in this spec (properties names, enums) use only ASCII charset_"

So I think writing "你好" is disallowed

**Comment by lexaknyazev** [comment]
That note doesn't apply to user-provided values.

**Comment by lexaknyazev** [comment]
In practice, that note is for the spec writers, not for implementors. It disallows something like:
```
{
   "𝐧𝒶𝕞𝔢": "value"
}
```

**Comment by vpenades** [comment]
Oh, I see what you mean, so 你好 is allowed as a value.

What about URLs?  I am aware that white spaces need to be escaped, so in such scenario, what about a string like this: " 你好 5.jpg"  how would it be encoded?

**Comment by lexaknyazev** [comment]
URLs are more tricky as they technically undergo two transformations and our docs are not quite precise.

Consider these:
1. `"uri": "你好.jpg"`
2. `"uri": "\u4f60\u597d.jpg"`
3. `"uri": "%E4%BD%A0%E5%A5%BD.jpg"`

The first and the second are the same but they are not valid URIs because they contain non-ASCII characters. The third is a valid URI but it is technically not the same string as the first two. The safest approach is to encode non-ASCII chars to UTF-8 and percent-encode each octet (option 3).

In practice, many modern systems support IRIs, so they will likely accept either of these options.

**Comment by vpenades** [comment]
For uri's  I think that approach is too complicated, I mean: the parser I'm using is able to automatically encode "你好" into "\u4f60\u597d" and then decode it back, automatically, so it's transparent to the code.

But, as you said, URIs are manually preprocessed before writing the json, and postprocessed after reading it, to encode and decode percent-encoding.  But applying two consecutive encodings seems like a bit overkill.

I understand why uri's have that sort of encoding: it's for cases where resources are requested over media that can't support certain URLs, like http urls requiring not having white spaces....  but shouldn't this be up to the client?  I mean, if you have to request a texture URI, _you know_ whether you're requesting it from an http network of from the hard drive, and apply URI transformations based on the media requirements.

Right now this is what happens: URIs are encoded with percent-encoding,  just to be percent-decoded on load.  if I request a file from hard drive, I use the URI as is (it's been percent-decoded and unescaped already), but if I want to load the texture from http, I have to escape and percent-encode it again, so I can't see the point of why the URIs have this requirement, other than conform to the URI specification, which is only valid on certain medias.

**Comment by lexaknyazev** [comment]
> URI specification, which is only valid on certain medias

URI spec itself is media-agnostic, although you're right that it's mostly relevant to HTTP.

The current spec language uses the "URI" term, so percent-encoding is technically a requirement. It's not enforced, though. I'd expect the spec to switch to IRIs at some point to better reflect the established behavior.

See also https://github.com/KhronosGroup/glTF-Sample-Models/pull/305.

**Comment by vpenades** [comment]
Okey, I think I have an idea of what's allowed/disallowed... now I have something to work with.

I also hope these restrictions are relexed some day, although I guess that would mean a breaking change.

**Comment by lexaknyazev** [comment]
The updated spec with character encoding clarifications has been released.
