### ISSUE TITLE
My character's limbs seem to be tearing my character's clothes?

### ISSUE THREAD

**Issue by mrParabol** [KhronosGroup/glTF#1979]
My character's feet are visible through the shoe of my character that I exported from the blender to the godot.
os: manjaro
blender : 2.92

blender image:
![2-my-boots](https://user-images.githubusercontent.com/28789841/116942435-3f204880-ac7a-11eb-877d-91a7e15187bb.png)

godot image:
![1-my-boots](https://user-images.githubusercontent.com/28789841/116942453-4ba4a100-ac7a-11eb-851b-e91afdc52421.png)

My blender, godot files and the files I exported as glb are also on the link.
https://disk.yandex.com.tr/d/sVIzHRJXbbFGkQ

Thank you very much for your attention.

**Comment by donmccurdy** [comment]
Please see reply at https://github.com/KhronosGroup/glTF/issues/1976#issuecomment-831424821. A good way to approach debugging would be to export your GLB and then test it at least two viewers:

- Godot
- https://gltf-viewer.donmccurdy.com/
- https://sandbox.babylonjs.com/
- https://github.khronos.org/glTF-Sample-Viewer-Release/

If it displays incorrectly in only one viewer, report a bug to that viewer. If it displays correctly in several, report a bug to the exporter. Assuming the latter, https://github.com/KhronosGroup/glTF-Blender-IO/issues/1390 is probably the place to report this.
