### ISSUE TITLE
error:Material is incompatible with mesh primitive

### ISSUE THREAD

**Issue by Youmyin** [KhronosGroup/glTF#1981]
Hi,I used babylonjs exporters for 3dsmax2018 to export the model into a glTF file, then imported the file into sandbox, and found that all the textures could not be displayed.

I tested the exported glTF file through the glTF Viewer website, and errors were reported as follows:
![image](https://user-images.githubusercontent.com/54265150/117771948-3b3b8a00-b269-11eb-90d9-15e5bdcb8a06.png)
![image](https://user-images.githubusercontent.com/54265150/117771967-42629800-b269-11eb-9303-e9760f4c171b.png)

The following is the error of vscode when I import it into the react project：
![image](https://user-images.githubusercontent.com/54265150/117772665-fe23c780-b269-11eb-9990-5fb1b427ed44.png)

How can I solve this problem?

**Comment by donmccurdy** [comment]
Hi @Youmyin! I think you may need to report this problem at https://github.com/BabylonJS/Exporters/. This repository is for the glTF file format, and the maintainers of the exporters may not be monitoring here.

But to guess, you may need to create a UV / texture coordinate map in 3DS Max before exporting, if you haven't already.

**Comment by Youmyin** [comment]
Ok,thanks!
