### ISSUE TITLE
Compressed morph target support with KHR_draco_mesh_compression

### ISSUE THREAD

**Issue by jespertheend** [KhronosGroup/glTF#1984]
It seems most tools igore morph targets when compressing meshes at the moment. (#1353 related)
Is there anything that needs to change about the glTF spec to support compressed morph targets?

With all of our projects so far we've encountered a point where we wanted to start using morph targets but ended up having to make compromises because download size gets ten times as big without draco.

**Comment by donmccurdy** [comment]
At minimum, another extension (similar to `KHR_draco_mesh_compression`) would be needed to allow Draco compression to be used with morph targets, perhaps treating the morph target attributes as generic vertex attributes. There may be more optimal ways to do this with the Draco library, or ways to enhance the Draco library to handle morph target attributes as sparse data, I'm not sure.

The `KHR_mesh_quantization` and `EXT_meshopt_compression` extensions do provide ways to compress morph targets today. The [gltfpack](https://github.com/zeux/meshoptimizer/tree/master/gltf) tool should let you compare the size of both. Quantization should let you reduce geometry size by 2-4x; Meshopt by more than that.

**Comment by jespertheend** [comment]
Oh wow, I guess I severely underestimated the capabilities of gltfpack simply because I forgot to add the `-cc` flag. It seems this is pretty much on par with draco compression.
Thanks! We'll be using this from now on. Feel free to close this issue :)
