### ISSUE TITLE
Disney BRDF link has been hijacked

### ISSUE THREAD

**Issue by RichardTea** [KhronosGroup/glTF#1992]
The 2.0 specification readme has a link titled "Burley, B. (2012): Physically-Based Shading at Disney."
This links to:
https://disney-animation.s3.amazonaws.com/library/s2012_pbs_disney_brdf_notes_v2.pdf

This AWS target has been hijacked and currently contains an advert, possibly also phishing. Please remove the link ASAP.

If possible, please find a true link to the paper.

**Comment by emackey** [comment]
@RichardTea Thanks for the heads-up!  And thanks to @lexaknyazev for the quick fix.

**Comment by RichardTea** [comment]
Excellent, I'll redact the link from this issue so people don't follow it :)
