### ISSUE TITLE
KHR_materials_transmission: Undefined function χ^- in the definition of V_T

### ISSUE THREAD

**Issue by pierremoreau** [KhronosGroup/glTF#2002]
In the KHR_materials_transmission extension, _V<sub>T</sub>_ is defined as using the heaviside function _χ<sup>+</sup>_ in the first term, and the (AFAICT) undefined function _χ<sup>-</sup>_ in the second term. Is the second supposed to be _χ<sup>+</sup>_ like in the first term, and similar to the definition of _V_ in Appendix B of the 2.0 specification?

**Comment by proog128** [comment]
Looks like the simplification is wrong, we need the same terms as in G_T instead. I created a pull request that fixes the issue and adds a bit of explanation. I hope it's correct now.
