### ISSUE TITLE
Add light property animations

### ISSUE THREAD

**Issue by Alexeyt89** [KhronosGroup/glTF#2011]
Currently with "light" extension it is possible to save light nodes to glTF2.0
The nodes have "color" "intensity" "innerConeAngle" and "outerConeAngle" properties.
As EXT_property_animation extension has stuck in discussions for over a year and in the end it is not likelly to support light animations (https://github.com/KhronosGroup/glTF/pull/1301#issuecomment-819078987) , I suggest that another extension should be created specifically to have the possibility to animate these properties.

**Comment by aaronfranke** [comment]
This is now possible thanks to the [glTF Object Model](https://github.com/KhronosGroup/glTF/blob/main/specification/2.0/ObjectModel.adoc) and the [KHR_animation_pointer](https://github.com/KhronosGroup/glTF/pull/2147) extension.

For example, an animation can have the target set to this to animate the color of light 0:

```json
"target": {
    "path": "pointer",
    "extensions": {
        "KHR_animation_pointer": {
            "pointer": "/extensions/KHR_lights_punctual/lights/0/color"
        }
    }
}
```

This issue can be closed as resolved.
