### ISSUE TITLE
Not able to load the part without normals

### ISSUE THREAD

**Issue by sandeeppster** [KhronosGroup/glTF#202]
Hello,
I am trying to load part, but can see anything. This part is a bit different, as it does not have normals :P
This part loads correctly in Three.js, maybe because they calculate the normals if not in the file. Why I want to load a file without normals, this will reduce the file size drastically. If you want I can give that file to you, didnt find anything here to attach the file with the issue.
Looking forward to your reply.

**Comment by pjcozzi** [comment]
Closing given the new three.js glTF loader.
