### ISSUE TITLE
How to know the coordinates and high-level data in the GLTF model

### ISSUE THREAD

**Issue by ITzhaowen** [KhronosGroup/glTF#2020]
I've got the GLTF model. But there is a problem with rendering the height, and I want to know how to get the coordinates and the height from the GLTF data. I need your help. Thank you

**Comment by donmccurdy** [comment]
The general process here is:

1. Traverse the scene graph top-to-bottom, tracking the current world matrix as you go.
2. Each time you reach a mesh, read the mesh primitives' `POSITION` min/max properties, normalize them if needed, and use the world matrix to transform them into world space.
3. The union of all node bounding boxes in world space forms an axis-aligned bounding box (AABB) for the scene.

With animation involved you may have more choices to make here but that's the general approach; implementation in any particular programming language or engine would look a bit different.

If you just need a one-off answer for a particular model, you can open it in https://gltf.report/ and check the "Inspect" tab for the BBOX_MIN and BBOX_MAX values.
