### ISSUE TITLE
Does glTF support multiple samplers for the same animation target/property?

### ISSUE THREAD

**Issue by mijalk0** [KhronosGroup/glTF#2023]
For a given animation, can a single targeted node **and** property be animated using more than one sampler?

Asking because I'm confused whether glTF supports animations using varying interpolation algorithms. For instance, can the rotation of a given node be animated linearly by one sampler, and then proceed to use cubic spline through another sampler, all within the same animation? To be clear, the inputs would not have any overlap.

My intuition says no because the specification doesn't seem to touch on this (I couldn't find anything at least). Please correct me if I'm misinterpreting any aspect of the specification.

**Comment by lexaknyazev** [comment]
It is implicitly forbidden by this line in the properties reference (it will be more visible in the upcoming document update):
https://github.com/KhronosGroup/glTF/blob/c6a5521ebd1469aba076949a97f150bf3591b63f/specification/2.0/schema/animation.schema.json#L10

I think the rationale was to avoid even the possibility of input overlaps that would lead to ambiguities.
