### ISSUE TITLE
Bring back the spec readme

### ISSUE THREAD

**Issue by technik** [KhronosGroup/glTF#2036]
I just realized the spec has moved from the old readme to https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html.
While I suppose the idea is to unify the documentation with other Khronos specs, having everything directly in the repo was very convenient and easy to navigate (and contribute to). Also, Github's formatting is a lot better, and rendered the spec very easy to read. Would it be possible to bring back the readme.md as it was before? (even if the doc also exists in the Khronos registry).

**Comment by technik** [comment]
I spoke too soon, the spec is still available in the repo. It's just one more click away now, here: https://github.com/KhronosGroup/glTF/blob/main/specification/2.0/Specification.adoc. Maybe adding a link to that in the old readme.md would make it easier for other people to find the new doc, as it is not obvious if you're not used to using AsciiDoc.

**Comment by javagl** [comment]
+1 for that, I also looked at the base directory yesterday, until I remembered "Oh, wait, GitHub does render adoc files...". If nobody is opposed, I'd extend the README.md with a hint like 

> "The AsciiDoc markup source file can also be viewn in GitHub, by opening the `(link)Specification.adoc`"

**Comment by lexaknyazev** [comment]
@technik 
FYI: GitHub formatting is missing the auto-generated Properties Reference section and some math expressions (namely projection matrices and PBR equations).

@javagl 
Please open a PR.

**Comment by emackey** [comment]
> Also, Github's formatting is a lot better, and rendered the spec very easy to read.

Maybe some style tweaks are in order?

- Our new output uses a Serif font for most text, but GitHub uses sans-serif throughout.
- We don't have any margins, even on the widest monitors.

**Comment by javagl** [comment]
I have opened a PR with a short hint. I included a disclaimer about the missing references and math renderings, because otherwise (and maybe regardless of that...) people will file issues for that.

**Comment by donmccurdy** [comment]
Would it be confusing (and/or a lot of trouble) to provide a fully-rendered version of just the `.adoc`-equivalent content somewhere? I understand that the spec hasn't actually become any more complex (the clarified normative language is great!), but — to me, at first glance — the new format feels overwhelming in a way that the previous markdown document somehow didn't. It's a 184-page PDF, in which 2/3rds of the pages (and 2/7ths of the TOC) are machine-generated, broken down as:

- 1. 1/3rd written content
- 2. 1/3rd property references
- 3. 1/3rd JSON schema files

Presumably the spec is not complete (in terms of IP) without each of those three, but from a readability perspective I'm finding myself wishing I could hide or collapse (3) and possibly even (2).

***

Related — when I open the (much longer) COLLADA spec PDF in Firefox, the table of contents is collapsed by default. When opening the glTF spec PDF, it's fully expanded. No idea why that is, does the PDF itself control this? 🤷‍♂️

**Comment by lexaknyazev** [comment]
> Presumably the spec is not complete (in terms of IP) without each of those three

JSON schema files are not normative but the properties reference is. Let's continue the discussion in #2041.

> No idea why that is, does the PDF itself control this? 🤷‍♂️

Yes, the PDF specification allows controlling the viewer's initial state.
