### ISSUE TITLE
instruction to blender integration is not given

### ISSUE THREAD

**Issue by Roshankiran67890** [KhronosGroup/glTF#2069]
I am trying to find a way how to make this work on blender and I am not finding a way to do this even after 3 hours of search in google.

If the documentation included a way how to use this in Blender it would be very useful.

Thank you.

**Comment by donmccurdy** [comment]
This is the repository for the file format itself – we don't maintain Blender or other 3D modeling software. But you can find the Blender documentation for glTF import/export at the link below:

https://docs.blender.org/manual/en/latest/addons/import_export/scene_gltf2.html
