### ISSUE TITLE
What's the meaning/usage of mesh.weights if mesh.primitive have morph targets?

### ISSUE THREAD

**Issue by wsw0108** [KhronosGroup/glTF#2093]
example gltf: https://github.com/cx20/gltf-test/blob/82ea59035859dba3a3bfd2a6b075532d69f4af01/tutorialModels/SimpleMorph/glTF/SimpleMorph.gltf#L33

The weights used in [formula](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#morph-targets) are from accessor.

**Comment by lexaknyazev** [comment]
The `weights[0,1,...]` symbols in the formula represent currently active weights, no matter where they come from.

From the later text of the same section:
> A mesh with morph targets MAY also define an optional `mesh.weights` property that stores the default targets' weights. These weights MUST be used when `node.weights` is undefined. When `mesh.weights` is undefined, the default targets' weights are zeros.

So `mesh.weights` are used only when `node.weights` is undefined and there's no active animation targeting the `node.weights`.

**Comment by wsw0108** [comment]
Thanks for your brief answer.

Does there has an example gltf with `node.weights` and no active animation targeting the `node.weights`?

**Comment by emackey** [comment]
> Does there has an example gltf with `node.weights` and no active animation targeting the `node.weights`?

Yes:  https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MorphPrimitivesTest

**Comment by wsw0108** [comment]
@emackey thanks very much
