### ISSUE TITLE
Outdated extensions list in Reference Card

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF#2099]
The glTF 2.0 Reference Card (see https://www.khronos.org/developers/reference-cards/) lists available extensions, as of time of writing. That list is now quite outdated:

> ### Existing extensions
> The following extensions are developed and maintained on the Khronos GitHub repository:
>
> - **Specular-Glossiness Materials** 
> https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_pbrSpecularGlossiness
> This extension is an alternative to the default Metallic-Roughness material model: It allows to define 
> the material properties based on specular and glossiness values.
> - **Unlit Materials**
> https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_unlit
> This extension allows the definition of materials for which no physically based lighting computations 
> should be performed. 
> - **Punctual Lights**
> https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_lights_punctual
> This extension allows adding different types of lights to the scene hierarchy. This refers to point lights,
> spot lights and directional lights. The lights can be attached to the nodes of the scene hierarchy.
> The following extensions are developed and maintained on the Khronos GitHub repository:
> - **WebGL Rendering Techniques**
> https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_techniques_webgl
> With this extension, it is possible to define GLSL shaders that should be used for rendering the
> glTF asset in OpenGL or WebGL 
> - **Texture transforms**
> https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_texture_transform
> This extension allows defining offset, rotation, and scaling for textures, so that multiple textures
> can be combined in order to create a texture atlas

Notably, `KHR_materials_pbrSpecularGlossiness` is now archived, `KHR_techniques_webgl` was never ratified, and numerous other extensions have been published. I'm not sure if any other changes to the reference card are needed, but it might be a good idea to update this section, or just remove it in favor of a link to the full list on GitHub.

**Comment by javagl** [comment]
Yes, this definitely needs an update. I'd probably not remove the section about extensions entirely, but rather "generalize" it - talking about the general mechanism of extensions (maybe say a few words about the _current_ `KHR` ones), and point to the extension registry instread. 

Several tasks have piled up in the past few weeks, but I might be able to address some of them now (i.e. in the coming weeks). Among them would be several updates for the `glTF-Tutorial`, which includes some tweaks for the "Skinning" section that should also be aligned with a corresponding update of the overview. 

(BTW: This could also be tracked in https://github.com/javagl/gltfOverview/issues , but it's OK to have that here).

**Comment by javagl** [comment]
Could such a list make sense, or could this be both too detailed (because of the length of the list) and not detailed enough (because of the shortness of the descriptions) at the same time...?

![glTF Overview Extensions](https://user-images.githubusercontent.com/5597569/141650787-93c68b03-2cec-4af7-ab2b-04d9e2940db4.png)

**Comment by elmajime** [comment]
Hi, what will be the alternative for KHR_materials_pbrSpecularGlossiness if it is archived?

**Comment by donmccurdy** [comment]
@elmajime apologies if you already know some of this, but, metal/rough and spec/gloss are two alternative workflows for PBR materials. By archiving `KHR_materials_pbrSpecularGlossiness` we are focusing future efforts on the metal/rough workflow.

Converting spec/gloss to metal/rough is not totally trivial, but ultimately both workflows can represent the same range of materials. Not all metal/rough materials require a specular parameter — and are often more efficient to render without the additional texture memory — but when necessary  `KHR_materials_specular` can be combined with the metal/rough PBR workflow to provide that flexibility.

You can find one implementation of a spec/gloss → metal/rough conversion in the [gltf-transform](https://gltf-transform.donmccurdy.com/) tool – this removes `KHR_materials_pbrSpecularGlossiness` from the material and replaces it with equivalent metal/rough parameters and `KHR_materials_specular`.

```shell
gltf-transform metalrough input.glb output.glb
```

**Comment by emackey** [comment]
@elmajime See also the [conversions section](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_materials_specular/README.md#conversions) of `KHR_materials_specular`.

**Comment by javagl** [comment]
<sup>Considering this as a heads-up (the actual update of the reference cart is still pending):</sup>

I assume that the list that I showed above would be better than the list that was incomplete and contained outdated extensions, so I'll do this update soon, and trigger an update of the PDF on the Khronos website afterwards - unless someone has an alternative suggestion of how the extensions should be presented there.

**Comment by javagl** [comment]
An updated version of the reference card is released at https://github.com/javagl/gltfOverview/releases/tag/v2.0.0c

The extensions section now contains a list of the currently ratified extensions:

![glTF Overview Extensions Update](https://user-images.githubusercontent.com/5597569/184540686-fff74946-b525-4896-8c54-519fc4dbbfb2.png)

Yes, the summaries are _very_ short, and can not do more than mention some keywords for the overall purpose of the extensions, but I think that it's reasonable to have this here, even if it can not convey all the details. 

The update has been forwarded to Khronos, and the reference card on the Khronos page may be updated at some point. (This is somewhat independent from the update in the repo, so I think it's OK to close this issue).

**Comment by emackey** [comment]
Hi @javagl, we ended up renaming it `KHR_materials_variants` (note the `s` on the end of both words), to match the naming of the other materials extensions.

https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_materials_variants

**Comment by javagl** [comment]
I _knew_ it 🙂 I've been carefully looking for typos, but didn't have that on the radar. 
(At least, a chance to fix the missing `.` at the end of the `EXT_materials_iridescence` line...)

Thanks @emackey . The fixed release is https://github.com/javagl/gltfOverview/releases/tag/v2.0.0d
