### ISSUE TITLE
Vendor Extension Request - ShapeDiver

### ISSUE THREAD

**Issue by snabela** [KhronosGroup/glTF#2103]
I would like to request vendor extension SHAPEDIVER to be added to Prefixes.md

The name of the prefix: SHAPEDIVER
The name of the vendor requesting the prefix: ShapeDiver
The vendor's URL and/or contact information: https://www.shapediver.com

**Comment by emackey** [comment]
Apologies for the delay on this!  It's registered now.

**Comment by snabela** [comment]
> Apologies for the delay on this! It's registered now.

Many thanks!
