### ISSUE TITLE
Question: using gltf-pipeline to write a GLB WITHOUT enbedding the texture?

### ISSUE THREAD

**Issue by aTanguay** [KhronosGroup/glTF#2116]
We're making many assets that share the same textures, so we're obvously looking to save badnwidth and not have copies of that same texture embedded in a pile of GLBs. I can't seem to force gltf-pipeline to make a GLB from a GLTF without embedding these textures. Is there a command line option I'm missing? Thanks!

**Comment by donmccurdy** [comment]
You may be looking for this repository: https://github.com/CesiumGS/gltf-pipeline

That said – conventionally `.gltf` has external dependencies and `.glb` does not. Nothing prohibits a `.glb` having external dependencies, but it's unusual and not a default option in tooling. If you need this support it could be implemented in a JavaScript/Node.js script, by first [compressing an asset with gltf-transform](https://gltf-transform.donmccurdy.com/classes/extensions.dracomeshcompression.html) and then [serializing it to `.glb` without the textures](https://github.com/donmccurdy/glTF-Transform/issues/207#issuecomment-928846347).
