### ISSUE TITLE
Request for TENCENT vendor prefix

### ISSUE THREAD

**Issue by kongxiaojian123** [KhronosGroup/glTF#2118]
Please add a "vendor extension prefix" for Tencent.

**Comment by javagl** [comment]
What is the contact information that should go into the "Contacts" column in the [Prefixes table](https://github.com/javagl/glTF/blob/prefixes-mx-and-snap/extensions/Prefixes.md#registered-vendor-prefixes)?

**Comment by kongxiaojian123** [comment]
> What is the contact information that should go into the "Contacts" column in the [Prefixes table](https://github.com/KhronosGroup/glTF/blob/main/extensions/Prefixes.md#registered-vendor-prefixes)?

Company or Project Name:  `Tencent, Inc.`

Contacts:  `https://www.tencent.com`
