### ISSUE TITLE
Meta: making the latex formulas readable in dark mode

### ISSUE THREAD

**Issue by gsimone** [KhronosGroup/glTF#2124]
Recently GitHub introduced a way to specify images for dark/light modes exclusively, meaning the formulas in the .md files could be made readable in every case: https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/

eg.
```html
<!-- Additional \color{white} and #gh-dark-mode-only suffix -->
<img src="https://render.githubusercontent.com/render/math?math=\color{white} \displaystyle \text{MicrofacetBTDF} = \frac{G_T D_T}{4 \, \left|N \cdot L \right| \, \left| N \cdot V \right|}#gh-dark-mode-only" />

<!-- Additional #gh-light-mode-only suffix -->
<img src="https://render.githubusercontent.com/render/math?math=\displaystyle \text{MicrofacetBTDF} = \frac{G_T D_T}{4 \, \left|N \cdot L \right| \, \left| N \cdot V \right|}#gh-light-mode-only">
```

You should see the correct color here depending on your preference on dark/light mode:

<img src="https://render.githubusercontent.com/render/math?math=\color{white} \displaystyle \text{MicrofacetBTDF} = \frac{G_T D_T}{4 \, \left|N \cdot L \right| \, \left| N \cdot V \right|}#gh-dark-mode-only" />
<img src="https://render.githubusercontent.com/render/math?math=\displaystyle \text{MicrofacetBTDF} = \frac{G_T D_T}{4 \, \left|N \cdot L \right| \, \left| N \cdot V \right|}#gh-light-mode-only">

**Comment by javagl** [comment]
Not entirely sure why this was closed, but a _very_ high-level comment: Most of the documentation/specification has been moved to AsciiDoc. I don't know how this plays together with the proposal shown here. But if this proposal is _not_ compatible with AsciiDoc (e.g. when it is no longer possible to generate a standalone PDF from the resulting documentation), that could be a reason why this did not receive any further comments.
