### ISSUE TITLE
Absolute URIs and document merging

### ISSUE THREAD

**Issue by mtaylor-tbpm** [KhronosGroup/glTF#2130]
I see that absolute URIs are allowed for buffers and images in GLTFs - https://github.com/KhronosGroup/glTF/issues/1744

When I try to merge several documents using absolute URIs I receive an error similar to below.  Are absolute URIs not supported when merging?  Works fine when bin and image files are local

ENOENT: no such file or directory, open '/private/var/folders/cj/_hjswxvd1t96yq12dxfjy1040000gn/T/3D/c2d67310-a647-4d27-abe2-6c422daa85e8/https:/tbpmdatastorestaging.blob.core.windows.net/assets/ki/nodes/gladly/gd261/3d/gd261_root-legs-ml_fram1.bin'

Note - the error message is pre-pending the GLTF path and removing one of the forward slashes after https:   The URIs in the GLTFs are correctly formatted.

**Comment by donmccurdy** [comment]
Hi @mtaylor-tbpm! This repository tracks development of the glTF specification and extensions, but not any particular software. What software are you using when attempting to merge these documents? It may be necessary to file an issue with that software rather than here. There's nothing in the specification that would the merge from working.

**Comment by mtaylor-tbpm** [comment]
I'm only using gltf-transform/core in NodeJS.  I'm saving multiple GLTFs locally that use remote URIs, ultimately to merge then write a GLB   

    for (const gltfFile of gltfFiles) {
      let gltfPath = path.join(workingFolder, gltfFile);
      document.merge(io.read(gltfPath));    <--- FAILS HERE
    }

**Comment by donmccurdy** [comment]
Ok! Could you open a discussion at https://github.com/donmccurdy/glTF-Transform/discussions? Note that you'll need to update to glTF Transform v2.x to load remote URLs with NodeIO.

**Comment by mtaylor-tbpm** [comment]
Never mind, I figured it out.  Was missing an await on io.read.  Thanks again for your help!
