### ISSUE TITLE
"Cast Shadow" Blender option is not exported

### ISSUE THREAD

**Issue by abernier** [KhronosGroup/glTF#2133]
It seems the Blender "Cast Shadow" option for lights
![L0bKY~2](https://user-images.githubusercontent.com/76580/158555595-ebf3be1e-119a-41c8-8bcd-aabe7ba492c7.jpg)
is not exported.

In Threejs, because of that, we have to traverse the scene and manually re-enable `.castShadow = true` for lights: https://discourse.threejs.org/t/blender-cast-shadow-not-preserved-for-lights/35980

Do you think this value could be exported?

Thank you

**Comment by donmccurdy** [comment]
Hi @abernier! The repository for the Blender addon is here: https://github.com/KhronosGroup/glTF-Blender-IO/

But I should note that the glTF format itself (defined by the spec in this repository) does not currently define whether lights cast shadows (or which objects are affected by those shadows) and so Blender won't be able to implement that immediately. A few people have expressed an interest in that feature as a glTF extension, perhaps something will be proposed eventually.

In the meantime – if you have control of the three.js application where you're loading this model, you may wont to use Blender's "Custom Properties" to mark lights that should cast shadows, and enable Custom Properties in the export options. The properties will be preserved in the export and three.js will load them as `object.userData`. You may also need to check `object.parent.userData`.
