### ISSUE TITLE
Calling illuminance "intensity" is worth avoiding

### ISSUE THREAD

**Issue by erich666** [KhronosGroup/glTF#2135]
I've been looking at various apps and how they specify physical lights in their user interface. It's a minor point, but I hope you can avoid using "intensity" as the name for the parameter. Something neutral like "scale," "multiplier," or "brightness" would be better, I believe. Or store "illuminance" separately, though that could be confusing and I dislike it. We've kind of run out of words for describing lights in English, but "intensity" implies "[luminous intensity](https://en.wikipedia.org/wiki/Luminous_intensity)," measured in candelas. Which of course makes little sense for directional lights like the sun, where your proposal properly uses illuminance, in lux.

Like I say, a minor point, but "intensity" is misused by so many apps that it'd be nice to avoid the term or use it properly. I've seen "intensity" as sometimes non-physical and unitless (like in FBX, Unreal Editor, and Unity), it's sometimes used for "intensity and exposure" (a camera-centric description used in [Arnold](https://docs.arnoldrenderer.com/display/A5AFMUG/Lights#Lights-Exposure) and Houdini, among others), and sometimes misused entirely. This confusion gets propagated by web pages like [this one](https://www.lumitex.com/blog/light-measurement), which says "Lux is a standardized unit of measurement of the light intensity" when earlier they correctly said that a candela was "The SI base unit of luminous intensity." Please don't add to the confusion.

_gets off soapbox_

**Comment by pjcozzi** [comment]
@erich666 thanks for the vocab insights!

@McNopper any thoughts on this given [KHR_lights_punctual](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_lights_punctual/README.md)?

**Comment by UX3D-nopper** [comment]
At first, we can't change the parameter anymore. This would break the compatibility.
However, we could bettere clarify - for the end user and the coder - what this intensity means. The current wording is like this:

Brightness of light in. The units that this is defined in depend on the type of light. point and spot lights use luminous intensity in candela (lm/sr) while directional lights use illuminance in lux (lm/m2)

@erich666 Maybe you can fork and make a pull request where aditional notes are explaining your concerns in a positive way. Please cross check with @lexaknyazev if this is possible at all.

**Comment by erich666** [comment]
Thanks for the fast response. I understand it's too late to change the name. I'll see if I can think of some way to improve the docs. But, TBH, probably won't - it already clearly states "intensity" is luminous intensity for local light sources, actually illuminance in lux for those at infinity (the right choices). People will cope. It's already a crazy world to try to combine full sunlight (100k lux) with local lights (more in the 100 candelas range) - people tend to fudge (I do!) if both are in a scene, e.g., an interior with sun coming in the window, and if there's no global illumination rendering to bounce light around. Me, I'm happy to see you add physical lighting units in any form, so, thanks!

FWIW, [Wikipedia notes](https://en.wikipedia.org/wiki/Irradiance#SI_radiometry_units) the same problem with the word "intensity" for radiometric unit descriptions, e.g., "Irradiance is often called [intensity](https://en.wikipedia.org/wiki/Intensity_(physics)), but this term is avoided in radiometry where such usage leads to confusion with [radiant intensity](https://en.wikipedia.org/wiki/Radiant_intensity)." Their page about illuminance shows less frustration in this area :).

Anyway, I said my piece, so I'll close this one.
