### ISSUE TITLE
coordinate system 3.4: +-X coord wrong

### ISSUE THREAD

**Issue by zlice** [KhronosGroup/glTF#2149]
Is this correct? https://github.com/KhronosGroup/glTF/blob/8e798b02d254cea97659a333cfcb20875b62bdd4/specification/2.0/Specification.adoc#34-coordinate-system-and-units

It looks like +X is right, not -X

**Comment by scurest** [comment]
If you're standing so +Z is forward and +Y is up, then +X is on your left and -X is on your right, is presumably what it means.

![coordinate-system](https://user-images.githubusercontent.com/11024420/164976725-651a81f9-5c2e-4b9e-976e-f1a062c24736.png)

**Comment by zlice** [comment]
I see. Guess the wording or how I look at it confused me. I'll close.

**Comment by javagl** [comment]
Just a cross link: https://github.com/KhronosGroup/glTF/pull/2139 - this has caused some confusion...
