### ISSUE TITLE
Clarify the mesh.primitive.attribute description

### ISSUE THREAD

**Issue by gurdep** [KhronosGroup/glTF#2153]
In the glTF specification, the [meshes-overview](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#meshes) states that the `mesh.primitives` correspond to the vertex attribute data of the mesh.

In the json [schema](https://github.com/KhronosGroup/glTF/blob/82506c076d64d00612f077c05f78aaf4e55f151c/specification/2.0/schema/mesh.primitive.schema.json#L11) for `mesh.primitives`, the description states that an attribute is 
> "A plain JSON object, where each key corresponds to a mesh attribute semantic and each value is the index of the accessor containing attribute's data."

Could somebody clarify what exactly does the attribute accessor, which is referred by an attribute in `mesh.primitives`, contains?  Is it only data for mesh vertices? 

thanks

**Comment by javagl** [comment]
Although it is not perfectly clear for me what the core of the question is, I'll try:

The attributes are indeed data that is associated with mesh vertices. This will usually be the POSITION, in most cases it will also be the NORMAL and the TEXCOORD_n. The list of attributes that are part of the core specification is given in the "meshes-overview" section that you already linked to. 

**Very** roughly speaking, the attribute data can be imagined like an "array", and the index that is used for accessing this array is exactly the vertex index. So when there is a mesh primitive like this:
```
{
    "meshes": [
        {
            "primitives": [
                {
                    "attributes": {
                        "POSITION": 22,
                        "TEXCOORD_0": 25
                    },
                    ...
                }
            ]
        }
    ]
}
```
then, on the implementation side, this could be imagined like this:
```
// The data from the attribute accessors
vec3 POSITION[] = new vec3[n];
vec2 TEXCOORD_0[] = new vec2[n];

// Three vertex indices for one triangle:
int index0 = ...;
int index1 = ...;
int index2 = ...;

// Position and texture coordinate for the first vertex of the triangle
vec3 position0 = POSITION[index0];
vec2 texcoord0 = TEXCOORD_0[index0];
...
```
**NOTE**: This is oversimplified. When actually rendering this data with OpenGL/WebGL, then you will **NOT** access these element individually. Instead, the accessor data is directly uploaded to the GPU. (In fact, that's one of the reasons why the data is stored like this: It is tailored for efficient GPU upload and rendering). See https://en.wikipedia.org/wiki/Vertex_buffer_object for the related functions.

**Comment by gurdep** [comment]
thanks @javagl Marco, 
for the clarification. Much appreciate the examples and links you provided. 

1. I am curious to know how would one introduce new attributes or Application-specific attributes as stated here 
> Application-specific attribute semantics MUST start with an underscore, e.g., _TEMPERATURE. Application-specific attribute semantics MUST NOT use unsigned int component type. 

Given your clarification, would this also mean that the attribute data for `application-specific` attributes is associated with mesh vertices? 

2. Another question, I am trying to understand the following statement from the gltf2.0 specification
> When positions are not specified, client implementations SHOULD skip primitive’s rendering unless its positions are provided by other means (e.g., by an extension). 

So in case a gltf2.0 file contains a mesh with only application-specific attributes as the one below; would a gltf2.0 loader skip rendering the following mesh primitive? **Note**: This is completely theoretical.  
```javascript
{
    "meshes": [
        {
            "primitives": [
                {
                    "attributes": {
                        "_TEMPERATURE": 22
                    },
                    ...
                }, 
            ]
        }
    ]
}
```


3. the json schema for `mesh.primtives` states the there should be atleast one property for `attributes` in [minProperties](https://github.com/KhronosGroup/glTF/blob/82506c076d64d00612f077c05f78aaf4e55f151c/specification/2.0/schema/mesh.primitive.schema.json#L12). But If one only wants to provide `POSITION` attribute for a mesh (which is expected to be rendered) through an external means (e.g. an extension) but no attributes in `mesh.primtives.attributes`. Would that mean that the following json is not gltf2.0 complaint? basically, `mesh.primitives.attributes` can not be an empty json object. 

```javascript
{
    "meshes": [
        {
            "primitives": [
                {
                    "attributes": {
                    },
                    ...
                    "extensions": [
                        "xyz_EXT_position": { 
                            "POSITION" : 23
                        }
                    ]
                }, 
                ...  
            ]
        }
    ]
}
```
**Note**: This is completely theoretical.

**Comment by javagl** [comment]
> I am curious to know how would one introduce new attributes or Application-specific attributes as stated here
> ...
> Given your clarification, would this also mean that the attribute data for application-specific attributes is associated with mesh vertices?

That's right. Normally, each vertex has a POSITION and maybe a TEXCOORD and a NORMAL. But you could also assign "arbitrary" other properties to each vertex. For example, you could define an attribute `_TEMPERATURE`, and create your own, special glTF renderer that, for example, can display the value of the `_TEMPERATURE` attribute for each vertex, when hovering over this vertex with the mouse. 

---

> I am trying to understand the following statement from the gltf2.0 specification
> > When positions are not specified, client implementations SHOULD skip primitive’s rendering unless its positions are provided by other means (e.g., by an extension).
> So in case a gltf2.0 file contains a mesh with only application-specific attributes as the one below; would a gltf2.0 loader skip the following mesh completely? 

The specification text says *"...skip primitive’s **rendering**..."*. When you talk about a **loader** (for example, some glTF loader library), then this loader could still allow you to access this data in some form. So it **could** be possible to load the asset that you described, and access the data, with *pseudocode* like
``` 
Asset asset = load(thisAsset);
float temperature = asset.meshes[0].primitives[0].attributes["_TEMPERATURE"][vertexIndex];
```
The point of the statement in the spec is: It's not possible to render anything without the POSITION attribute. There might be other ways for providing the positions, or other information that may be stored in attributes, and the spec does not disallow that. It only answers the question of "What should a renderer to when there are no positions?".

---

Question 3 is ... not so easy to answer, and actually a good catch. Your example, even if purely theoretical, could be some sort of "point cloud" that _only_ consists of "positions", but where the actual positions are not stored as a POSITION attribute, but in an extension object.

@lexaknyazev Any thoughts on question 3?

**Comment by lexaknyazev** [comment]
Question 3 is a great edge case that is not explicitly covered by the spec.

In general, glTF 2.0 prioritizes portability over flexibility. This means that some applications may have a hard time squeezing their _custom contents_ into glTF 2.0 _standard form_.

Unfortunately, the intersection of the aforementioned requirements (`attributes` object being mandatory, while the `POSITION` attribute being technically optional) does not make much sense for the purpose of providing alternative geometry representations without per-vertex data. So an extension in that area would likely have to define a new top-level array.

**Comment by gurdep** [comment]
thank you @javagl and @lexaknyazev for providing response to my questions.
