### ISSUE TITLE
glb file with multiple buffers

### ISSUE THREAD

**Issue by Siccity** [KhronosGroup/glTF#2168]
Hello! I'm toying around with a glb exporter and wondering if having more than one binary buffer is allowed for .glb files. I haven't succeeded in loading one in either Windows 3D viewer or at https://gltf-viewer.donmccurdy.com/ . But, this may be due to errors on my part.
The documentation reads:
> The first chunk always contains the JSON data. The remaining chunks contain the binary data.

Which seems to imply that this should be possible

**Comment by lexaknyazev** [comment]
The table in the [Section 4.4.3.1.](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#chunks-overview) allows only one `BIN` chunk.
