### ISSUE TITLE
Different JSON schema versions in KHR extensions

### ISSUE THREAD

**Issue by UX3D-haertl** [KhronosGroup/glTF#2184]
The glTF schema uses version 2020-12 while the KHR extensions use version Draft 4.
Would it make sense to update the extensions to the same version?
There are some differences between the schemas:
- exclusiveMinimum, exclusiveMaximum are boolean in Draft 4, but numbers in newer versions. (This is used in e.g. the light extension)
- in Draft 4 the required field must contain at least one string
- Draft 4 only specifies "uri" as value for "format", newer version additionally support "uri-reference"

These are some more changes, but I think the exclusiveMinimum/Maximum rule is the only one where the extensions schemas needed to be changed.

**Comment by javagl** [comment]
Although the _title_ is the exact opposite, I think this is already tracked in https://github.com/KhronosGroup/glTF/issues/2049 , so I think it's OK to close this. (Drop me a note if not)
