### ISSUE TITLE
unify scenes axis-up

### ISSUE THREAD

**Issue by fabrobinet** [KhronosGroup/glTF#22]
All converted scenes should come with the same axis-up. Y-UP.

**Comment by pjcozzi** [comment]
@tparisi for the draft 1.0 spec, add:

> The model's up axis is the `y` axis.

**Comment by tparisi** [comment]
OK; I think I should put in a whole section on coordinate system etc.

**Comment by pjcozzi** [comment]
Sure, whatever you think.
