### ISSUE TITLE
converter refactoring and cleanup

### ISSUE THREAD

**Issue by fabrobinet** [KhronosGroup/glTF#220]
In order to facilitate implementation of upcoming features I'll focus a bit on reorganizing and refactoring as it became a bit too fat...
Especially to ease:
- the split of glTF part to be able to create a glTF framework
- split of glTF + OpenCOLLADA part to be able to create a collada2gltf lib
- inclusion of new compression methods
- pre/post processing of geometry

**Comment by pjcozzi** [comment]
OBE - the 2.0 branch of COLLADA2GLTF is basically a complete rewrite.
