### ISSUE TITLE
Unclear licenses for multi and single vendor extensions

### ISSUE THREAD

**Issue by kofi-de-com** [KhronosGroup/glTF#2210]
Hello, I'm interested in using several EXT_* and vendor extensions in a commercial context. To understand licensing requirements and properly attribute copyright I'd like to get those clarified.

https://github.com/KhronosGroup/glTF/blob/main/LICENSE.adoc specifically excludes single vendor extensions from the Khronos IP framework. Could you please share your progress regarding "We are working on determining full details of these licenses in each case." 

Unfortunately https://github.com/KhronosGroup/glTF/tree/main/extensions#multi-vendor-extensions-for-gltf-20 states that multi vendor extensions are excluded as well.

To perhaps simplify the scope of this request I'd like to know specifically what license [EXT_lights_image_based](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Vendor/EXT_lights_image_based/README.md) and
[MSFT_texture_dds](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Vendor/MSFT_texture_dds/README.md) are under.

Thank you

**Comment by lexaknyazev** [comment]
It's true that only Khronos-ratified extensions are covered by the Khronos IP framework. In all other cases, extension authors/contributors should be contacted directly to clarify IP-related issues.

For these two extensions, @bghgary may know the details.

**Comment by bghgary** [comment]
I'm the one who asked @kofi-de-com to post this issue. 😄 

Should individual vendors put licenses on each extension?

**Comment by bghgary** [comment]
We should probably check for these before merging vendor extensions in the future. I will see what license(s) we should put for the Microsoft ones.
