### ISSUE TITLE
Specification for `KHR_lights_punctual` requires renderers to scale RGB channels differently depending on hue and saturation. — Lumens are not a physically based unit.

### ISSUE THREAD

**Issue by will-ca** [KhronosGroup/glTF#2213]
The [`KHR_lights_punctual` extension](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_lights_punctual/README.md) specifies the use of lumens to represent lamp power:

> ### Directional
> 
> Directional lights are light sources that act as though they are infinitely far away and emit light in the direction of the local -z axis. […] Its intensity is defined in lumens per metre squared, or lux (lm/m<sup>2</sup>).
> 
> ### Point
> 
> Point lights emit light in all directions from their position in space; rotation and scale are ignored except for their effect on the inherited node position. […] Point light intensity is defined in candela, which is lumens per square radian (lm/sr).
> 
> ### Spot
> 
> Spot lights emit light in a cone in the direction of the local -z axis. […] Spot light intensity refers to the brightness inside the `innerConeAngle` (and at the location of the light) and is defined in candela, which is lumens per square radian (lm/sr).

However, lumens are not a hard physical measure. Because the human eye has different sensitivities to different wavelengths of light, and because RGB maps more or less to physical *radiant* flux rather than perceptual *luminous* flux (I.E. RGB(1,1,1) maps to the flat broadband spectrum of white sunlight, with roughly equal power but different luminance contributions from all three primary colour wavebands, which you can tell by how RGB(0,0,1) on a computer monitor generally looks perceptually darker than RGB(0,1,0)), the spec as currently written means that model viewers will have to account and compensate for human spectral sensitivity/luminous efficiency; A blue lamp with an "intensity" value of `1.0` has to radiate a lot more power, and also produce much higher RGB values (which will further lead to issues with clipping), in order to output the same lumens as a green lamp with the same "intensity" value of `1.0`.

~~I think this also further means that the per-channel mappings between lamp colour input RGB values and physical lamp power are further going to have to be nonlinear/inconsistent with respect to hue and intensity. At zero or low saturation, the scaling factor from perceptual luminous flux-as-specified to physical radiant flux-as-simulated needs to be the same across all three RGB channels, in order to preserve the hue, or lack thereof. But at higher saturations, lamps will have to behave as I describe above, with blue and red lights scaling up or green lights scaling down in power and in RGB in order to emit the same specified lumens.~~

~~Neither the [Three.JS](https://gltf-viewer.donmccurdy.com/) nor the [Khronos Group](https://github.com/KhronosGroup/glTF-Sample-Viewer) reference model viewers currently implement this behaviour. Red, green, and blue lamps of the same strengths produce the same physical rather than the same perceptual brightnesses. Per the spec as written, that is incorrect; Differently coloured lights must output different physical power and different encoded RGB values in order to emit the same perceptual lumens.~~ Actually, I suppose it's not like coloured lamps get scaled to their wattage either— The strength is its brightness if it were white, and the colour is a mask on that. But still it is very weird that you cannot multiply a colour channel by the nominal strength to get the real emitted strength.

If requiring these behaviours is not intentional, then as it's probably too late to change the unit, perhaps it could be specified that all luminance to irradiance conversions should done assuming the same luminous effiency regardless of wavelength? Or if it is intentional, I wonder if it would be worth explicitly mentioning these effects in the extension document, as this is in my view not a particularly obvious behaviour.

**Comment by will-ca** [comment]
Looking back on what I had to do for https://github.com/KhronosGroup/glTF-Blender-IO/pull/1760, there's also another problem here: The choice of lumens-based units for specifying light strength means that any reasonable, physically based light source like a household lightbulb (much less the sun, car foglights, etc.) is likely going to have a strength that is numerically in the hundreds or the low thousands. Since 3D authoring and viewing programs generally try to keep their base values around `1.0`, that also creates compatibility issues, and, to my knowledge, means that currently *no* tools or viewers implement default behaviours that can work nicely with the spec as written.

The bigger problem is still as in the issue post: Lumens are *not* a physically based unit, and so using them in the specification of a physically based format means that either (1) rendering pipelines will have to jump through a lot of silly hoops and will force arcane behaviour onto users or (2) everyone will ignore that particular part of the spec (as is apparently currently the case).

**Comment by will-ca** [comment]
Another thought: Since all/most applications seem to already be ignoring the units part of the spec anyway, maybe it would still be possible to change it? If we just swap out "lm" for "W" (so we get W/m² for directionals and W/r² for points and spots), then we get much saner numbers that actually work with existing viewers (e.g. appear to be what Three.JS actually expects), are much nicer to convert to from existing tools (e.g. in Blender with no conversion needed for suns and simply division by `4pi` for spots and points), and, most importantly, are actually physically based on the amount of energy being emitted, reflected, and detected in the scene (and thus don't imply the need for a weird colour space transform to match a *perceptual* metric).

Just replacing every instance of "lm" with "W" in the spec would basically match the *de jure* spec to what is already *de facto* the standard that in actuality the entire ecosystem seems to be built on and assume, I think.

And presumably once the unit in the spec is saner, it will also be easier for non-conformant implementations to fix their own bugs— E.G. The unsuitability of lumens in a PBR workflow and the difficulty of trying to find a sane way to convert from physical watts to perceptual lumens has explicitly held up https://github.com/KhronosGroup/glTF-Blender-IO/issues/564 for over three years.

**Comment by donmccurdy** [comment]
Note to future readers — We believe this question has been resolved in https://github.com/KhronosGroup/glTF/pull/2214#issuecomment-1279640547. In short, it's common in many tools for people to implicitly use a "unitless" workflow where the exposure is left at its default value, and lighting intensities are adjusted to look good at that exposure. In photometric lighting pipelines, this often means light intensities have values near 1.

For scenes authored with physically-based lighting in the correct units, it is necessary to adjust exposure appropriately for the scene. In most current viewers, exposure adjustment must be done by hand.
