### ISSUE TITLE
Z component range of normalTexture is unspecified

### ISSUE THREAD

**Issue by erich666** [KhronosGroup/glTF#2223]
See https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#_material_normaltexture

Here it says:

> 5.19.5. material.normalTexture
> The tangent space normal texture. The texture encodes RGB components with linear transfer function. Each texel represents the XYZ > components of a normal vector in tangent space. The normal vectors use the convention +X is right and +Y is up. +Z points toward > the viewer. If a fourth component (A) is present, it MUST be ignored. When undefined, the material does not have a tangent space > normal texture.

The problem is that there are two different value ranges used for the Z component in the normal texture itself. Most of the normal textures in [the sample models for glTF 2.0](https://github.com/KhronosGroup/glTF-Sample-Models) appear to use the range -1 to 1 for Z, the same as for X and Y components. For example, the [NormalTangentTest_Normal.png files](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/NormalTangentTest/glTF/NormalTangentTest_Normal.png) appear to use this range.

However, the normal textures named [TestMap_Normal.png](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/TextureTransformMultiTest/glTF/TestMap_Normal.png) (there are three total, all the same) use a range of 0 to 1, not -1 to 1, for its Z component. This can be seen at pixel 394,303, which has a triplet (242,89,82). Any time there's a Z (blue) value lower than 127, it means that the Z range is likely 0 to 1.

This is often not a big deal. Most applications nowadays use -1 to 1 (even though 0 to 1 would give a bit more precision - negative Z values make no sense for tangent maps). Also, because of this confusion, some shaders will ignore the Z component entirely and derive it from X and Y. However, this is not what the spec says - it is silent. Viewers that use the Z as-is will differ in their rendering from those ignoring and rederiving Z.

Also, issues such as [adding object space normal textures](https://github.com/KhronosGroup/glTF/issues/1284), which does need -1 to 1 for the Z range, means it's worth making it clear that this is the range that _all_ normal textures should use, what the exact format is. For more background about this area, see [my page](https://github.com/erich666/McUsd/tree/usdwga/test_assets/NormalsTextureBiasAndScale).

I would propose making a small addition [in the spec](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#_material_normaltexture), adding after:

> The normal vectors use the convention +X is right and +Y is up. +Z points toward > the viewer. 

Something like:

> The normal texture has values that represent direction vectors, with the range 0-255 mapped to mean -1 to +1, for all three channels. These normals are assumed to be normalized once converted to the -1 to +1 range.

I would also recreate the TestMap_Normal.png image, having it properly have a -1 to +1 range for the Z component, too. The texture could be recreated using the NormalMap-Online tool, as described [here](https://github.com/erich666/McUsd/tree/usdwga/test_assets/NormalsTextureBiasAndScale#normal-map-creation).

**Comment by erich666** [comment]
Using [NormalMap-Online](https://cpetry.github.io/NormalMap-Online/), I negated [the TestMap_blur.png image](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/sourceModels/TextureTransformMultiTest/TestMap_blur.png), negated the red channel (always needed), and set the z-range from -1 to +1 in the tool, then output. Here it is.
![NormalMap_z_fixed](https://user-images.githubusercontent.com/803995/199839131-caf5c402-8c79-45e6-ae3e-8156a7aea726.png)

**Comment by lexaknyazev** [comment]
Spec provides range mappings in the [Section 3.9.3](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#additional-textures):
> After dequantization, texel values **MUST** be mapped as follows: _red_ [0.0 .. 1.0] to X [-1 .. 1], _green_ [0.0 .. 1.0] to Y [-1 .. 1], _blue_ (0.5 .. 1.0] maps to Z (0 .. 1]. Normal textures **SHOULD NOT** contain blue values less than or equal to 0.5.

Incorrect normal textures in the sample models repo should definitely be fixed.

**Comment by erich666** [comment]
That's great that the normal texture format is specified - I missed that, thanks! And thanks for the fast response. I admit to reading what you quoted and being concerned at first, as it said "maps to Z (0 .. 1], not noticing that it gives the unusual (0.5 .. 1.0] range for blue. Whew, good.

It's interesting the spec then says, "Normal vectors MUST be normalized before being used in lighting equations. When scaling is used, vector normalization happens after scaling." Good enough, and you'd be surprised how many are not. I would have preferred "Normal vectors MUST be normalized in the normal texture map," but there's a (weak) argument that, even if they were, normalizing when in floats gives a "closer to length one" result.

Anyway, great, good enough, no changes needed for the spec. That means there's then just one minor issue: the [TestMap_blur.png image](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/sourceModels/TextureTransformMultiTest/TestMap_blur.png) violates the glTF spec. It maps blue [0.0 .. 1.0], not blue (0.5 .. 1.0], to z [0 .. 1]. Like I said, pixel 394,303 has a triplet of (242,89,82) - the blue value is too small, because they're using the wrong mapping. I'll report this problem as an issue for [the sample models repo](https://github.com/KhronosGroup/glTF-Sample-Models). Closing this one.

**Comment by erich666** [comment]
I've generated the related issue, it is at https://github.com/KhronosGroup/glTF-Sample-Models/issues/364
