### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'morphTargetDictionary')

### ISSUE THREAD

**Issue by weiyunpeng** [KhronosGroup/glTF#2233]
```js
let body = model.getObjectByName("body").children[0] as THREE.Mesh;
 if (!body.morphTargetDictionary) {
    body = body.parent.children[1] as THREE.Mesh;
 }
```

TypeError: Cannot read properties of undefined (reading 'morphTargetDictionary')

**Comment by donmccurdy** [comment]
It sounds like this is a question about three.js, and not the glTF format specification. I'd recommend posting in one of the three.js community links below, and including complete code or a demo to reproduce the issue.

three.js community —

[questions](https://stackoverflow.com/questions/tagged/three.js)
[discord](https://discord.gg/56GBJwAnUS)
[forum](https://discourse.threejs.org/)
