### ISSUE TITLE
Animation keyframe count and order?

### ISSUE THREAD

**Issue by jeannekamikaze** [KhronosGroup/glTF#2244]
To count the number of keyframes in an animation, do we need to count the number of unique time values in the input arrays of the samplers?

And similarly, is there any (time) order guarantee in how the samplers or the channels are given? The [spec](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#animations) mentions the following, I'm not sure if "mapping of timelines" refers to this sort of time order:

> glTF 2.0 defines only storage of animation keyframes, so this specification doesn’t define any runtime behavior, such as: order of playing, auto-start, loops, mapping of timelines, etc.

I am trying to load glTF models into an engine. Knowing the amount of keyframes in an animation ahead of time seems useful, as well as guaranteeing that the keyframes are given in time order so that the application can load them into an array and then expect to walk over them in sequence during playback. For all this, having a 'keyframe' data structure and defining animations as a sequence of such keyframes I think would be useful, but I don't know what was the motivation behind the more loose definition in the spec. Perhaps I'm too caught up with the concept of a keyframe, but I think this could be related to the discussion going on in https://github.com/KhronosGroup/glTF/issues/1665.

Thank you.

**Comment by donmccurdy** [comment]
I believe most engines would consider keyframes to be a "per-track" concept. The number of keyframes on the translation track may be quite different from the number of keyframes on the rotation track, for example. If your engines's structure requires consolidating tracks to form a keyframe, then yes, I think you'd need to count unique time values among multiple input samplers.

Keyframe order is required to be "strictly increasing" by the spec:

> The [input sampler] values represent time in seconds with time[0] >= 0.0, and strictly increasing values, i.e., time[n + 1] > time[n].

The glTF Validator will check for this condition, as well.

**Comment by jeannekamikaze** [comment]
Interesting, thank you. I was not familiar with this idea of splitting translation/rotation into separate tracks. Not really sure how that would look like, for example, for a walk or run cycle. It seems that if you wanted the animation to look correct, you'd have to apply whatever transformations are given anyway. What benefit is there from splitting translation/rotation like that?

In Blender, at least from a UI perspective, the keyframes seem to mix translation/rotation/any other property you want to animate:

![Screenshot from 2023-01-18 16-45-34](https://user-images.githubusercontent.com/1595451/213330178-5b0fd7b6-dcaa-4b28-b5e7-e4feb80bf08e.png)

> Keyframe order is required to be "strictly increasing" by the spec

Missed that bit of the spec, thank you.

**Comment by donmccurdy** [comment]
Probably different software has different terms here, but in glTF terminology:

- An **animation** (or "clip") represents a meaningful action, like a run or walk cycle.
- A **channel** (or "track") represents a series of keyframes affecting one property of one object.
- A **keyframe** is a time at which a value is stored in a channel, defining curves used to interpolate any other values not stored by the channel.

An animation is composed of many channels, each operating on different properties and objects. While it's possible that all channels _might_ store values at exactly the same times, it's not usually what you want. As an animator, why should a finger have keyframes at the same times as the legs, in a walk cycle? Ideally you want as few keyframes as possible, which means each channel should use only the keyframes that it needs to represent motion.

One exception here is when animation has been "baked", such that every channel contains a value for every frame, often at 24 or 30 FPS, as in your screenshot above. This is done when the animation software (like Blender) uses interpolation methods that cannot be represented directly in the export format, so it generates lots of new keyframes instead. It's harder for an artist to work with the animation data once this has been done, and also wastes space and computation time. Ideally you resample and remove the excess keyframes, but not all exporters do this.

**Comment by jeannekamikaze** [comment]
I see. I get the part that keyframes should be sparse like in the walk cycle you mentioned above. What I meant is that I find odd that the rotation of a node is stored in a different channel/track than its translation (e.g. the leg's translation/rotation in the walk cycle), since at the end of the day one needs to compose both to compute the joint matrix. I suppose that the way glTF intends this is that you walk over the channels given a time value t and apply the relevant translations when you find them, and the rotations, and the scalings, touching node targets in no particularly defined order. Then, once all the transformations have been applied, you do another pass to compute the joint matrices. Is that correct?

(Thank you for your time and explanations, by the way.)

**Comment by jeannekamikaze** [comment]
Yeah, I think I get the idea, thank you. The glTF arrangement makes more sense now than what I had in mind.
