### ISSUE TITLE
obsolete links in Draco spec.

### ISSUE THREAD

**Issue by andreasplesch** [KhronosGroup/glTF#2248]
Urls to three.js example use of draco in https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_draco_mesh_compression/README.md
became unavailable and lead to 404s.

https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/DRACOLoader.js in

** Conformance **
...
[ThreeJS (non-normative)](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/DRACOLoader.js)

,and also
https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/DRACOLoader.js in

** Resources **
[ThreeJS  Loader](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/DRACOLoader.js)

The current, equivalent url would be
https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/DRACOLoader.js

To avoid future problems, the permalink would be
https://github.com/mrdoob/three.js/blob/596a98774d288db545a0ab21dc394c347ebea97c/examples/jsm/loaders/DRACOLoader.js

As a side note, the linked three.js loader only decodes compressed data but does not show glTF related processing. The code for draco extension processing is in
https://github.com/mrdoob/three.js/blob/dev/examples/jsm/loaders/GLTFLoader.js

Another useful resource is the KHR sample viewer which processes the draco extension mostly in
https://github.com/KhronosGroup/glTF-Sample-Viewer/blob/master/source/gltf/primitive.js

**Comment by donmccurdy** [comment]
- /cc https://github.com/KhronosGroup/glTF/pull/2254

**Comment by andreasplesch** [comment]
Thanks.
