### ISSUE TITLE
Joints vertex attribute in reference guide/overview should be uvec4?

### ISSUE THREAD

**Issue by jeannekamikaze** [KhronosGroup/glTF#2249]
The [spec](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#skinned-mesh-attributes) says:

> JOINTS_n: unsigned byte or unsigned short

But in the [reference guide](https://www.khronos.org/files/gltf20-reference-guide.pdf) and [overview](https://raw.githubusercontent.com/KhronosGroup/glTF/main/specification/2.0/figures/gltfOverview-2.0.0b.png) (which are great!), `a_joint` appears as a `vec4` in the code snippet under section *"Combining the joint matrices to create the skinning matrix"*. In [GLSL](https://www.khronos.org/opengl/wiki/Data_Type_(GLSL)#Vectors), a `vec4` is 4 floats; `uvec4` would be 4 unsigned integers, which seems to be the more appropriate type for joint indices?

**Comment by jeannekamikaze** [comment]
I think that `vec4` may have slipped from the fact that `WEIGHTS_n` are either floats or normalized unsigned bytes/shorts, in which case they would indeed map to `vec4` in GLSL. But `JOINTS_n` can't possibly be normalized, right? They are indices after all.

**Comment by javagl** [comment]
One might consider to bring this up in https://github.com/javagl/gltfOverview , but it's probably better to have a few more eyes looking at this: I might need to refresh my memory about some aspects of the implementation on the GLSL level.

Some first thoughts:

The ("pseudo-but-supposed-to-be-realistic") code in the overview says `attribute vec4 a_joint;`, and at the place where this data is _used_, it says `u_jointMatrix[`**`int`**`(a_joint.x)]` - so it is anticipating that the input is floating point, but actually supposed to be an index, and using it as an `int` value.

---

The question is then: How is this attribute data "filled" with the data from the glTF asset? 

In my implementation, that data is passed to GL as 
```
        glBindVertexArray(glVertexArray);
        glBindBuffer(target, glBufferView);
        glVertexAttribPointer(
            attributeLocation, size, type, false, stride, offset);
        glEnableVertexAttribArray(attributeLocation);
```
with the relevant `size` and `type` parameters being
```
            int size = accessorModel.getElementType().getNumComponents();
            int type = accessorModel.getComponentType();
```
For the joint data, one would have something like `size=4` and `type=GL_UNSIGNED_SHORT`. My knowledge about low-level GL/GLSL details is a bit shaky, but the [documentation of `glVertexAttribPointer`](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glVertexAttribPointer.xhtml) says

> For glVertexAttribPointer, if normalized <sub>[...(not the case here)...]</sub>. Otherwise, values will be converted to floats directly without normalization.

I read that as GL automagically converting stuff from the `glVertexAttribPointer` call into the desired `vec4`, even when the input originally was a 4D `unsigned short` vector. 

Can someone confirm or correct me here?

(It does seem to work, by the way - the data does arrive in the shader as a `vec4`, filled with `float` values that correspond to the `unsigned short` values from the accessor. But I'd like to know that this is really what the spec means by the "direct conversion to float")

**Comment by scurest** [comment]
> think that vec4 may have slipped from the fact that WEIGHTS_n are either floats or normalized unsigned bytes/shorts

No, the reason it's like that is uvec4 attributes / glVertexAttribIPointer didn't exist in WebGL1. The way javagl describes it was the normal way to do it: pass it with glVertexAttribPointer, which makes it appear as a vec4 in the shader, which is cast to int for indexing.

If you're using WebGL2 (or another more modern API) you can use a uvec4 instead, yes. The overview isn't wrong though, I guess it could just be considered an older way of doing things.

**Comment by jeannekamikaze** [comment]
You must be right, I missed that second part of `glVertexAttribPointer`. It looks like if you wanted to read `uvec4` in a shader you should call `glVertexAttrib*I*Pointer()` instead:

> For glVertexAttribIPointer, only the integer types GL_BYTE, GL_UNSIGNED_BYTE, GL_SHORT, GL_UNSIGNED_SHORT, GL_INT, GL_UNSIGNED_INT are accepted. **Values are always left as integer values.**

**Comment by jeannekamikaze** [comment]
Ok, thanks guys, my misunderstanding then (again :smile:).
