### ISSUE TITLE
Is front-facing positive or negative determinant?

### ISSUE THREAD

**Issue by rsahlin** [KhronosGroup/glTF#2252]
Searching through the 2.01 version of the glTF specification I cannot find specification of which winding is declared as front-facing.
There are references to facingness, winding etc but I can't seem to find if clockwise- or counter-clockwise is considered as front facing.
If I remember correctly this has been in the specification previously - is the omission intentional?

What I currently can find regarding facingness is this:

```
When a mesh primitive uses any triangle-based topology (i.e., triangles, triangle strip, or triangle
fan), the determinant of the node’s global transform defines the winding order of that primitive. If
the determinant is a positive value, the winding order triangle faces is counterclockwise; in the
opposite case, the winding order is clockwise
```

I cannot find if front-facing equals to a positive or negative determinant.

**Comment by javagl** [comment]
It's subtle, so wait until someone confirms or disagrees with what I'm saying here:

I think that the determinant does not determine (sic) which faces are front facing. It only determines the _criterion_ which is used to _decide_ which faces are classified as being "front-facing". 

There's also this implementation note:

> Switching the winding order to clockwise enables mirroring geometry via negative scale transforms

which presumably refers to [the description of the `glFrontFace` function](https://www.khronos.org/opengl/wiki/Face_Culling#Winding_order) that says

> Which side is considered the "front" side is controlled by this function

If my interpretation is correct, then the text from the specification could be elaborated to answer your question like this:

- If the determinant is positive, and the vertices are in counterclockwise order, then the triangle is front-facing
- If the determinant is negative, and the vertices are in counterclockwise order, then the triangle is back-facing
- If the determinant is positive, and the vertices are in clockwise order, then the triangle is back-facing
- If the determinant is negative, and the vertices are in clockwise order, then the triangle is front-facing

Anyone feel free to correct me here...

---

An aside:

> _"... the winding order triangle faces ..."_

I wonder whether that should be _"...the winding order **of** triangle faces ..."_

**Comment by emackey** [comment]
Per discussion on the Khronos 3D Formats call today, @javagl's interpretation is correct.

**Comment by bghgary** [comment]
There are also various unit test models here: https://github.com/KhronosGroup/glTF-Asset-Generator/tree/master/Output/Positive/Node_NegativeScale
