### ISSUE TITLE
Will the glTF support int or uint for custom attribute?

### ISSUE THREAD

**Issue by insar-dev** [KhronosGroup/glTF#2256]
Will the glTF support int or uint for custom attribute?

125 (UNSIGNED_INT) is only allowed when the accessor contains indices.

![image](https://user-images.githubusercontent.com/1676595/218999078-248d9356-276d-4221-9227-066399018424.png)

**Comment by javagl** [comment]
The name `_FEATURE_ID_0` suggests that this may be intended for the use in the proposed [`EXT_mesh_features`](https://github.com/KhronosGroup/glTF/pull/2082) extension. The proposal carries [an implementation note](https://github.com/CesiumGS/glTF/blob/proposal-EXT_mesh_features/extensions/2.0/Vendor/EXT_mesh_features/README.md#feature-id-by-vertex) that says

> Because glTF accessors do not support `UNSIGNED_INT` types for 32-bit integers in vertex attributes, `FLOAT` may be used instead allowing integer feature IDs up to 2<sup>24</sup>. For smaller ranges of feature IDs, `UNSIGNED_BYTE` or `UNSIGNED_SHORT` may be used. As with other vertex attributes, each element of a feature ID accessor must align to 4-byte boundaries.

Regardless of that: No, glTF does not support `UNSIGNED_INT` for mesh attributes, and most likely never will (except for the case where support for this attribute may be added with a dedicated extension).
