### ISSUE TITLE
Request for BENTLEY vendor prefix

### ISSUE THREAD

**Issue by pmconne** [KhronosGroup/glTF#2259]
Hello from [Bentley Systems](https://www.bentley.com/)!
We plan to implement a handful of extensions shortly.

**Comment by javagl** [comment]
Can you confirm:

- Prefix: `BENTLEY` 
- Company or Project Name: **Bentley Systems** (any suffix like "**Inc."**?)
- Contacts: `https://www.bentley.com/` (Any specific mail addresses to add? These are not strictly necessary, but some people add them)
