### ISSUE TITLE
onProgress callback in the three.js loader

### ISSUE THREAD

**Issue by benbro** [KhronosGroup/glTF#226]
It will be useful to have onProgress callback in the three.js loader

```
load: function ( url, onLoad, onProgress, onError )
```

example:
https://github.com/mrdoob/three.js/blob/master/src/loaders/ObjectLoader.js#L15

Is it possible to also get a callback when the textures are also loaded?

Thanks

**Comment by pjcozzi** [comment]
@tparisi do you still want to keep this open in this repo?

**Comment by tparisi** [comment]
Yes please keep any Three.js issues open here until I can bring the latest into the Three.js mainline

**Comment by pjcozzi** [comment]
Can we close this given the new three.js glTF loader?

**Comment by pjcozzi** [comment]
Closing since the glTF loader has went through a few iterations since this was opened.

Please open a new issue in the three.js repo if this is still relevant.

CC @donmccurdy
