### ISSUE TITLE
Deprecate non WebGPU compatible vertex formats

### ISSUE THREAD

**Issue by greggman** [KhronosGroup/glTF#2266]
WebGPU doesn't support attributes of size 1 and 3 for 8bit and 16bit data.

In other words, normalized int16 x 3 (common for compressing positions and normals) and uint8 x 3 (common for rgb vertex colors)  That also includes float16 x 3 if such a format exists in WebGL

I know it's called **gL**TF but one goal is that the data is usable straight from the file.

For WebGPU, when formats like these appear in the file, most likely the data will have to be re-packed at load time.

Note that these restrictions are present because they exist in one or more of Vulkan/DX12/Metal so this isn't just a WebGPU issue.

**Comment by lexaknyazev** [comment]
glTF 2.0, Section 3.6.2.4. Data Alignment:
> For performance and compatibility reasons, each element of a vertex attribute MUST be aligned to 4-byte boundaries inside a `bufferView` (i.e., `accessor.byteOffset` and `bufferView.byteStride` MUST be multiples of 4).

For example, this means that `unorm8x3` is always stored as `unorm8x4`.

**Comment by donmccurdy** [comment]
@lexaknyazev I'd interpreted that requirement as meaning `bufferView.byteStride` must be padded to multiples of 4 bytes. But `accessor.componentType` for a 16-bit POSITION accessor does not need to be (and cannot be) "VEC4", correct? 

I don't know the WebGPU API so well, but does this mean that the example `gpuFormatForAccessor (accessor)` given at https://toji.github.io/webgpu-gltf-case-study/#primitive-pipelines should be modified to consider the buffer view's stride, not just the accessor?

**Comment by lexaknyazev** [comment]
16-bit `POSITION` accessor is of `VEC3` type but its elements are stored with two extra trailing bytes to ensure correct alignment.

**Comment by greggman** [comment]
[KHR_mesh_quantization](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_mesh_quantization/README.md) does not follow that 4 byte alignment restriction

**Comment by lexaknyazev** [comment]
> [KHR_mesh_quantization](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_mesh_quantization/README.md) does not follow that 4 byte alignment restriction

In which case? It says:

> Note that to comply with alignment rules for accessors, each element needs to be aligned to 4-byte boundaries; for example, a `BYTE` normal is expected to have a stride of 4, not 3.

**Comment by greggman** [comment]
Oh! Thanks for pointing that out!
