### ISSUE TITLE
glTF consultant wanted

### ISSUE THREAD

**Issue by JojoJaro** [KhronosGroup/glTF#2275]
Dear community,

I am working on a software tool which exports glTF to be used in commercial rendering software.
My tool is based on Matlab and I am using the export from the following toolbox:
[https://de.mathworks.com/matlabcentral/fileexchange/123955-gltf-for-matlab]

The glTF I am exporting is not perfect for the rendering step behind. Unfortunately my knowledge and the possibilities of the Matlab toolbox are limited. That is why I am looking for someone who might be able to help us. I guess an online meeting together with my rendering guy would be the the best starting point to explore the issues and possible solutions.

Is here anybody who might be able to help? I guess the most important competence would be to understand the structure of the glTF file itself. Of course, I would be willing to compensate for the service.

Thanks a lot in advance!
Best,
JojoJaro

**Comment by javagl** [comment]
This repository is for maintaining the glTF specification itself. Issues here should be used for pointing out problems with the specification (like inconsistences if there were any, or requests for clarifications), or for discussing extension proposals.

Requests for consulting services should probably go somewhere else, like general job networking sites, ... or _maybe_ the forum at https://community.khronos.org/c/gltf-general/45 , even though that also focusses on _technical_ discussion.

That being said... if you described with a little more detail what "not perfect for the rendering" actually means, one could probably give some more helpful hints. (and... I could probably provide "consulting" to some extent, if it's not too specific for the Matlab tools that you pointed to)

**Comment by javagl** [comment]
Many technical questions can probably be discussed publicly, either in the forum, or by opening an issue in the repository that seems to be hosting the source code of the MATLAB project that you linked to: https://github.com/rohan-collins/MATLAB-GLTF  

(In doubt, my mail address is `gltf` AT `marco-hutter.de`, but I could imagine that more people would like to know more about what can be done with that MATLAB glTF project).

**Comment by rohan-collins** [comment]
Hey guys, I'm the author of the MATLAB toolbox. FWIW, my toolbox currently exports glTF files with all options in the standard, and all of the ratified material extensions (as well as some others). Unfortunately I am no artist and I was unable to help @JojoJaro with what he was looking for, but I'm happy to chime in if it's something specific to the toolbox.

**Comment by javagl** [comment]
> does the GLTF format provide sufficient parameters to generate photorealistic renderings (i know this is a really general question, but maybe people with experience in GLTF immediately say NO, or hopefully YES:)

glTF uses a standard model for Physically Based Rendering (PBR). It may appear like a detail, but glTF rather describes _the properties of materials_. It is up to the renderer to generate nice images from that. But to get an idea, you might want to look at
- the sample models at https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0
- the glTF sample viewer at https://github.khronos.org/glTF-Sample-Viewer-Release/

---

> does it help for photorealistic renderings if vertex-normals are included in the GLTF file, or is this something that the rendering tool does anyway (and in a tool specific way)?

Here is a photorealistic rendering of a black cat in a completely dark room:

![BlackCat](https://user-images.githubusercontent.com/5597569/229881410-88f631b9-c9eb-429a-975c-a2fbf4e5c3bb.png)

This can be achieved without vertex normals. 

But seriously: The term "photorealistic" has some degrees of freedom. There are certainly different renderers that claim to produce "photorealistic" results, but as soon as there is _any_ difference between their results, one of them must be "wrong". Trying to _quantify_ the degree of realism requires a "gound truth", and that's hard to obtain for artificial environments. 

More information about this topic can be found, for example, at https://modelviewer.dev/fidelity/ (warning, that's a large page...)

For your question specifically: glTF models usually *do* include vertex normals. Without vertex normals, glTF will use flat shading. When you have a model without vertex normals, it's sometimes possible to compute some sort of "smooth default normals", but the details depend on the model.

---

> does a general library exist, which lists the required GLTF parameters to generate different surface appearances? Something like "silver shiny steel", "mat/dull/flat steel", "titanium sheet metal", "rough 3D-printed nylon", silicone rubber", stuff like this...

Most 3D modeling tools offer some sorts of material libraries, and most of them can be exported to glTF. Quick websearches bring up things like https://blender-materials.org/ , for example.

---

> is UV mapping required for rendering "single-material" surfaces, or only required if for example wrapping a texture/image onto a surface

Usually, a _photorealistic_ appearance of objects _requires_ some textures. Even a seemingly homogenous material has _slight_ variations in it, and textures are also used for other effects (like normal maps or varying roughness). So unless you want to model something like "flawless red plastic" or "perfectly polished gold", you'll need textures, and therefore, UV coordinates.

**Comment by JojoJaro** [comment]
Thanks a lot for these infos and links, that definitely of great help! I will try to dig into it and get back soon..!

**Comment by javagl** [comment]
Since this is not an issue for the glTF specification itsefl, I'll close it for now.
