### ISSUE TITLE
Simple default schema for materials?

### ISSUE THREAD

**Issue by meshula** [KhronosGroup/glTF#228]
Hey all, we're having a discussion about materials on the Alembic group, https://groups.google.com/forum/#!topic/alembic-discussion/aD-YTv6gd1c and thought I would bring the question over here too. The basic thought is that beyond a basic material schema (such as https://github.com/KhronosGroup/glTF/blob/master/specification/material.schema.json - Alembic's schema is similar), maybe it would be nice to have a simple schema with suggested standard names and interpretations for a very small number of properties. The discussion on the Alembic board is towards providing the minimum for a physically based set of parameters. 

The motivation for such a minimal standard interpretation is that if a chunk of data is available with a standard material described in it, quick previewers and other pipeline tools could do a reasonably good job of representing a mesh.

**Comment by mlimper** [comment]
I had something similar in mind for the very simple (but very well-specified) X3D material model:
https://github.com/KhronosGroup/glTF/issues/411

@meshula: At our institute we are definitely also interested in working on a physically-based material model for use with glTF... ([here's](http://examples.x3dom.org/Demos/hare3d/images-deferred-pbs/) a Demo, but don't wonder about the pre-rendered g-Buffers) ... might make sense to synch at some point, so please feel free to get in touch if you're interested.

**Comment by pjcozzi** [comment]
Closing as duplicate with #84.  Let's move the design discussion there.
