### ISSUE TITLE
Comparing 2 very simple gltf generated files with same node matrices, because of different results

### ISSUE THREAD

**Issue by Baruchware** [KhronosGroup/glTF#2289]
Hello everyone!

I am trying to make my own converter from a specific file format to gltf.
In order to understand some details I usually compare the output of another converter against mine.

so here I do have a very simple model, composed by 8 meshes, each mesh is of course under a node, and the nodes have their own matrices.

comparing the output of these 2 converters, the matrices (local and global) are identical, but the visual orientation I get is different.
in order to let you understand better what I mean I share with you some images:

This is the output from my under development converter
![immagine](https://github.com/KhronosGroup/glTF/assets/53627894/429aac8c-69ad-4f1b-9273-c356b7d5befb)

And this is the output from another converter I found (this is correct)
![immagine](https://github.com/KhronosGroup/glTF/assets/53627894/f72eb79d-d66a-4635-83b4-d6c511de3539)

As you can see the global transform of the last node on these branches is identical, do you guys have some hints on what could be the reason? from the docs I didn't found anything that could help on this specifically.

100% is an error by my code, but if you guys may have an hint, I would be very happy!

**Comment by javagl** [comment]
The only reason that I could imagine right now is that _the geometry data itself_ is different. It might be that the `POSITIONS` of the mesh are once rotated and once not rotated (and the _additional_ global transform of the node that the mesh is attached to causes a "right" or "wrong" result). 

What do the `POSITIONS` of the meshes contain in both cases?

**Comment by Baruchware** [comment]
thank you a lot javacl!
I do really appreciated your suggestion, it helped me understand the issue. 
In the end I just checked the positions and they were the same, my problem was that the accessors were all pointing to the same `byteOffset`.
Probably this is a noobish issue with gltf, I am sorry for that :bowtie:.
I hope this can help other people.

Have a good day ser! :blush:
