### ISSUE TITLE
How to normalize the anisotropyTexture?

### ISSUE THREAD

**Issue by echadwick-wayfair** [KhronosGroup/glTF#2290]
I'm having difficulty resolving normalization issues with the anisotropyTexture in the [AnisotropyBarnLamp sample model](https://github.com/KhronosGroup/glTF-Sample-Models/pull/366).

The specification does not seem to state whether this texture needs to be normalized. 
> https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_materials_anisotropy
> 
> The anisotropyTexture, when supplied, encodes XY components of the direction vector in tangent space as red and green values, and strength as blue values, all stored with linear transfer function. After dequantization, red and green texel values MUST be mapped as follows: red [0.0 .. 1.0] to X [-1 .. 1], green [0.0 .. 1.0] to Y [-1 .. 1]. Blue does not require remapping. 

However if it isn't normalized, as far as I understand we're likely to see lighting artifacts when the surface is rendered.

We need an anisotropyTexture with a sweep gradient if we want to simulate a surface with radial micro-grooves, such as the bottom of a frying pan.
![fryingpan from Ebay https://www.ebay.com/itm/165840535226](https://github.com/KhronosGroup/glTF/assets/40177036/043137d1-057f-4fbc-8769-af0f1d1233ff)

I made six simple models to test with:
1. AnisotropySweep_NormalizedNegOnePosOne.gltf
2. AnisotropySweep_NormalizedNegOnePosOne_Mirrored.gltf
3. AnisotropySweep_NormalizedZeroOne.gltf
4. AnisotropySweep_NormalizedZeroOne_Mirrored.gltf
5. AnisotropySweep_NotNormalized.gltf
6. AnisotropySweep_NotNormalized_Mirrored.gltf
[OneMeterCube_AnisotropySweeps.zip](https://github.com/KhronosGroup/glTF/files/11511243/OneMeterCube_AnisotropySweeps.zip)

There are two types of gradients. One is a gradient sweep from white to black across 360 degrees. The other is "mirrored" to avoid the discontinuity where white is right next to black.

There are three types of normalization:
1. None
2. Red and Green channels normalized to (-1,1). Blue channel is unchanged since it represents AnisotropyStrength.
3. Red and Green channels normalized to (0,1). Blue channel unchanged.

AnisotropySweep_NormalizedNegOnePosOne texture, and its RGB channels:
![AnisotropySweep_NormalizedNegOnePosOne](https://github.com/KhronosGroup/glTF/assets/40177036/b99ed451-6b8c-408c-9378-c8f8278bce04)

AnisotropySweep_NormalizedNegOnePosOne_Mirrored texture, and its RGB channels:
![AnisotropySweep_NormalizedNegOnePosOne_Mirrored](https://github.com/KhronosGroup/glTF/assets/40177036/19a74a4f-d57c-4025-bf2d-31b468dd8a46)

AnisotropySweep_NormalizedZeroOne texture, and its RGB channels:
![AnisotropySweep_NormalizedZeroOne](https://github.com/KhronosGroup/glTF/assets/40177036/38d437d8-2f9a-4bc1-9611-51ecbd0d3499)

AnisotropySweep_NormalizedZeroOne_Mirrored texture, and its RGB channels:
![AnisotropySweep_NormalizedZeroOne_Mirrored](https://github.com/KhronosGroup/glTF/assets/40177036/39dbdcb4-ca0d-4c15-89c6-4893c3d54ff8)

AnisotropySweep_NotNormalized texture, and its RGB channels:
![AnisotropySweep_NotNormalized](https://github.com/KhronosGroup/glTF/assets/40177036/796677ac-ecb0-49f0-bbbf-b3be848d2f2d)

AnisotropySweep_NotNormalized_Mirrored texture, and its RGB channels:
![AnisotropySweep_NotNormalized_Mirrored](https://github.com/KhronosGroup/glTF/assets/40177036/74613efc-5074-4648-b451-f58700eafe21)

The "NormalizedNegOnePosOne" textures were normalized with Adobe Substance Designer using this function graph:
![AdobeSubstance3DDesigner_normalized-1+1](https://github.com/KhronosGroup/glTF/assets/40177036/316c7ee8-5eb8-4c86-911b-a82646bf85ed)

The "NormalizedZeroOne" textures were normalized with Adobe Substance Designer using this function graph:
![AdobeSubstance3DDesigner_normalized0+1](https://github.com/KhronosGroup/glTF/assets/40177036/55f14161-d823-4bc6-8331-78489865244d)

How they render in Three.js https://raw.githack.com/mrdoob/three.js/dev/editor/index.html
![2023-05-18 15_51_34-ThreeJS](https://github.com/KhronosGroup/glTF/assets/40177036/aef8fffe-8b46-4bbc-8651-d0f5a40bb22a)
They are in alphabetical order left to right:
1. AnisotropySweep_NormalizedNegOnePosOne.gltf
2. AnisotropySweep_NormalizedNegOnePosOne_Mirrored.gltf
3. AnisotropySweep_NormalizedZeroOne.gltf
4. AnisotropySweep_NormalizedZeroOne_Mirrored.gltf
5. AnisotropySweep_NotNormalized.gltf
6. AnisotropySweep_NotNormalized_Mirrored.gltf

Where the blue channel is black, there seem to be zero reflections in Three.js. This seems like it might be incorrect since the anisotropyStrength should only be affecting the anisotropy layer? If we want to mask out parts of the material to remove anisotropy, how do we keep regular non-anisotropic reflections intact?

Also which normalization should be applied? The fourth and sixth examples seem to offer the best result. So I'm inclined to go with a mirrored sweep that's normalized (0,1). But that's contrary to the spec which indicates (-1,1).

**Comment by echadwick-wayfair** [comment]
Here's what the Normalize Vec2 node does:
![2023-05-18 16_30_25-Adobe Substance 3D Designer](https://github.com/KhronosGroup/glTF/assets/40177036/ac2a7d58-58b1-4f56-b1dd-97e8090c5a35)

**Comment by emackey** [comment]
@echadwick-wayfair It looks like number 4 here "AnisotropySweep_NormalizedZeroOne_Mirrored" is correct.

> After dequantization, red and green texel values MUST be mapped as follows: red [0.0 .. 1.0] to X [-1 .. 1], green [0.0 .. 1.0] to Y [-1 .. 1].

This part of the spec is here because PNG and other formats cannot store values in the -1 to 0 range, they can only store positive values representing 0 to 1.  So, your second node graph "NormalizedZeroOne" is doing the correct thing here: First, it remaps the zero-to-one range, multiplying by 2 and subtracting 1 to get into the -1 to 1 range.  Then, the normalization happens on two channels in that range.  Finally, the result is mapped back (multiply 0.5, add 0.5) to get into the 0 to 1 range again for storing in a new image.  This is exactly right.

The "sweep" textures look incorrect to me.  They look like a full sweep from +1 to -1 (encoded as zero, black) around 360 degrees, reaching zero (encoded as 0.5, medium gray) on the far side.  This would be OK for an angle encoded in a texture, but is not what we want here (and indeed, the large discontinuity is the thing we're avoiding with this design).  Instead, we want separate X and Y values.  Let's consider the X values in isolation here:

![mostly hand-drawn diagram showing the value of x at various points on a circle](https://github.com/KhronosGroup/glTF/assets/1235080/5a2cfac2-46c3-4ef8-8873-0b778c48dcd8)

In the above diagram, I've doodled the value of "X" on a circle at various points.  It's +1 on the right, -1 on the left, zero in the middle.  But since images can't encode -1, the values get remapped.  So the red channel is bright on the right, medium in the middle, and dark on the left.  The "sweep" of X values is literally a sine wave, going positive and negative and back as they make their way around (and indeed `sin` and `cos` are often used to draw circles).

I don't know if this helps make it clearer why the channels look the way they do.  The "sweep" ones are incorrect because we don't want the value of X to suddenly flip from -1 to +1 at any point along the circle.  Other software uses an "angle texture" for that, and with an angle texture you get a sudden jump from 360 degrees back to 0 at some point, so things look bad if you zoom in on the pixels where that jump happens.  If you think of X and Y coordinates on a circle, they can move in any direction and not suffer a jump or discontinuity like that.

**Comment by echadwick-wayfair** [comment]
> @donmccurdy Any chance that gltf-transform could normalize a two-channel (red, green range -1 to 1) vector field texture? This is different from normalizing a typical normal map because the Z channel must be preserved but excluded from normalization.

It would be great to have a 2-channel normalizer in gltf-transform. Additionally, I could export the Substance 3D Designer graph as a standalone tool, which could be run via the free Substance 3D Player app. It's a GUI, and Artists will be familiar with the workflow.

**Comment by donmccurdy** [comment]
> Any chance that gltf-transform could normalize a two-channel (red, green range -1 to 1) vector field texture?

I don't think that would be much trouble. I should be able to take a look in the next couple weeks, after the next three.js release (with anisotropy support) is out.

**Comment by donmccurdy** [comment]
Steps:

1. Open model in https://gltf.report/
2. Open the "Script" tab, and paste the script below:

```typescript
import { getPixels, savePixels } from 'ndarray-pixels';
import { Texture, vec2 } from '@gltf-transform/core';
import { Anisotropy } from '@gltf-transform/extensions';
import { vec2 as glVec2 } from 'gl-matrix';

for (const material of document.getRoot().listMaterials()) {
    const anisotropy = material.getExtension<Anisotropy>('KHR_materials_anisotropy');
    if (!anisotropy) continue;

    const texture = anisotropy.getAnisotropyTexture();
    if (!texture) continue;

    await normalizeRotationRG(texture);
}

async function normalizeRotationRG(texture: Texture) {
    const pixels = await getPixels(texture.getImage(), texture.getMimeType());

    const rotation = [0, 0] as vec2;

    for (let x = 0; x < pixels.shape[0]; x++) {
        for (let y = 0; y < pixels.shape[1]; y++) {
            rotation[0] = pixels.get(x, y, 0);
            rotation[1] = pixels.get(x, y, 1);
            
			remap(rotation, [0, 255], [-1, 1]);
            glVec2.normalize(rotation, rotation);
            remap(rotation, [-1, 1], [0, 255]);

            pixels.set(x, y, 0, Math.round(rotation[0]));
            pixels.set(x, y, 1, Math.round(rotation[1]));
        }
    }

    const image = await savePixels(pixels, texture.getMimeType());
    texture.setImage(image);
}

function remap(vector: number[], domain: vec2, range: vec2) {
    for (let i = 0; i < vector.length; i++) {
        vector[i] = range[0] + (range[1] - range[0]) * (vector[i] - domain[0]) / (domain[1] - domain[0]);
    }
}
```

4. Run the script. Note that the script executes against, and replaces, the current state of the document in the viewer. To make changes to the script and test them, be sure to press "undo" to get back to the original state, before re-running the script.

***

Testing against the latest version of AnisotropyBarnLamp.glb (https://github.com/KhronosGroup/glTF-Sample-Models/pull/366), I see a significant difference in the texture itself, but no visible change in the rendering of the model.

| before | after |
|---|---|
| ![image](https://github.com/KhronosGroup/glTF/assets/1848368/2849ee37-d7cc-4d76-b126-64840c40ba77) | ![image](https://github.com/KhronosGroup/glTF/assets/1848368/32147d0f-8665-438f-998d-be812b8e456c) |

Does this seem like the correct approach?

**Comment by echadwick-wayfair** [comment]
I see clipping at the extremes of the red and green channels, and artifacting in red and green where the blue channel has antialiasing (especially visible on the text at bottom right).

**Comment by echadwick-wayfair** [comment]
Here is a non-normalized version of the anisotropy texture if that helps with your testing: ![AnisotropyBarnLamp_anisotropy_Non-Normalized](https://github.com/KhronosGroup/glTF/assets/40177036/b82b192d-3044-460a-8001-6d8b288393e5)

**Comment by donmccurdy** [comment]
If you zoom into the text and compare before/after in the viewport, the difference is very subtle (and not obviously better or worse than the original to my eye). Despite how it looks in an image viewer, I think the "artifacts" shown may be a valid result of per-pixel normalization here.

<img width="1624" alt="Screenshot 2023-05-31 at 2 21 56 PM" src="https://github.com/KhronosGroup/glTF/assets/1848368/8ee392f7-9d13-4244-bf78-07f4f86add5c">

**Comment by echadwick-wayfair** [comment]
I see some significant artifacting on the text in your screenshot, maybe this was the lossy PNG version?

Here's another comparison, and I agree the differences are minimal. This is in Babylon.js Sandbox. The top two are from the glTF-Sample-Assets PR. The bottom model has the "after" texture from above.

![anisotropy-normalizations](https://github.com/KhronosGroup/glTF/assets/40177036/49dd6294-8150-494b-8da7-01a6b732280d)

**Comment by donmccurdy** [comment]
I'm working from the copy at https://github.com/KhronosGroup/glTF-Sample-Models/pull/366#issuecomment-1569067288, downloaded 11:30am this morning. While I can see artifacts in the screenshot as well, those are also visible before normalization, so perhaps I have the wrong copy... Here's a video toggling normalization on/off a few times, it's quite subtle.

https://github.com/KhronosGroup/glTF/assets/1848368/bebc61b7-18fe-4c86-a2ac-7ecfe4266440

**Comment by echadwick-wayfair** [comment]
glTF.Report uses Three.js I think? It looks like there are some issues with the anisotropy implementation in Three.js. I've been discussing this with @elalish too, [over here](https://github.com/KhronosGroup/glTF-Sample-Models/pull/366#issuecomment-1569067288).

The latest GLB in both glTF Sample Viewer and Three.js:
![2023-06-01 09_09_31](https://github.com/KhronosGroup/glTF/assets/40177036/9c3408ca-0ffc-4a47-9f07-f0f45d03a08b)

There are two issues I think:
1. Stairstepped aliasing where the blue channel of the anisotropyTexture is black.
2. Metallic value has been zeroed where the blue channel of the anisotropyTexture is black.

The IBL is Microsoft's high-contrast studio lighting from the Babylon.js Sandbox, just for consistency.
https://github.com/BabylonJS/Assets/blob/master/environments/studioSoftbox2Umbrellas_panorama_radiance.hdr

**Comment by echadwick-wayfair** [comment]
This has been resolved, see https://github.com/KhronosGroup/glTF-Sample-Models/pull/366#issuecomment-1569067288
