### ISSUE TITLE
Request for WG vendor prefix

### ISSUE THREAD

**Issue by mixtur** [KhronosGroup/glTF#2299]
Hi guys. Webgears would like to oficially request the WG vendor prefix. Here is our web site if you need it for the table https://webgears.app/.

**Comment by DrX3D** [comment]
The sequence 'WG' is frequently used for 'Working Group' and might cause confusion with infrequent users of the extension repo. Is there a variant of that prefix that would work for you?

**Comment by mixtur** [comment]
I see. How about WGE?

**Comment by javagl** [comment]
@DrX3D Any objections to `WGE`?

Otherwise, I'd add the information as
`WGE`
Company name: **Webgears Inc.**
(No mail address)
