### ISSUE TITLE
proposal: specifying compression extensions

### ISSUE THREAD

**Issue by fabrobinet** [KhronosGroup/glTF#230]
As a high-level guidance this proposal reuses some concepts learned from GL APIs and extend them to mesh compression:  
- have a common API (here properties) for compression (with GL, that's for textures).
- let different implementations be specified via extensions.  

Notes:
- as a concrete example of implementation we will use Open3DGC, this said, the proposal should be flexible for other kinds as well…
- currently, the JSON generated in the converter is NOT synced up with this proposal - yet. Ideally we'll get feedback before implementing.

For mesh compression the entities we want to compress - wether they are vertices or indices - are streams of float, int…. can be interdependent/connected and thus all needed at the same time to be able to decompress, but for more flexibility they will appear as separate streams, each represented as an `accessor`. Depending on cases, it is the extension itself that should specify the info that is required (for instance if indices are required when decompressing vertices to get connectivity info).
> Given that, consistency checks should be made depending on each extension requirements

This proposal covers the compression of:
- animations
- meshes
note: morphing will come later, and should be heavily based on same principles.  

In animations accessors contains all the datas and all streams can be compressed separately without dependency. (not connectivity info needed)

The compressed accessor is just declared like any other accessor...

```
"accessors": {
    "accessor_0": {
        "bufferView": "bufferView_707",
        "byteOffset": 843648,
        "byteStride" : 12102
        "count": 501,
        "type": 5126
    }
...
```

It is just when accessing the bufferView that we figure that we have to decompress it:

```
"bufferView_708": {
    "compression" : {
        "type": "Open3DGC",
        "extras" : {
            "mode" : "ascii"
        }
    }
    "buffer": "compressedBuffer",
    "byteLength": 1000,
    "byteOffset": 0
}
```

We have introduced the `compression` property. It hold:
- `type` of compression
- extras: specific datas to this `type` of compression

The `bufferView` indicates the `byteOffset` and `byteLength` to be read from compressedBuffer to decompress the datas.

As mentioned earlier meshes need connectivity info, so one potential issue with the above definition would be to attempt to uncompress a datas "too soon", e.g when reading the glTF asset if one attempts to decompress bufferViews regardless of the context.
So to prevent this, we either can:
- specify that `bufferView` with `compression` should never be decompressed without context (if not access via a `mesh` or `animation`).
- or just add say a `autonomous`(or whatever better name...)  property in the `compression`property, so that we know if bufferView can be uncompressed right away.

That's for the general idea. Based on feedback, implementation will start and iterations are likely to happen after a first pass...

**Comment by pjcozzi** [comment]
@kainino0x have you reviewed this discussion in detail?  Can we now close this as duplicate with #398?

**Comment by pjcozzi** [comment]
I talked with @kainino0x and we are going to continue all mesh compression discussion in #398.

**Comment by kainino0x** [comment]
As mentioned in the proposal in #398, I don't want to create any sort of set structure for mesh compression extensions.

> While the three libraries I've looked at (Open3DGC, OpenCTM, webgl-loader) all work similarly, there could easily be other libraries which would be very difficult to shoehorn into this structure.
