### ISSUE TITLE
How to set mipmaps textures

### ISSUE THREAD

**Issue by newpeople123** [KhronosGroup/glTF#2301]
Gltf2.0 supports mipmaps textures. After specifying the texture filtering method in the sampler, do you need to provide a texture with mip or a non mip texture that will be automatically generated by the engine loading gltf?

**Comment by javagl** [comment]
Usually, there are no further steps necessary (beyond setting the sampler configuration). Engines that support mipmaps and honor this configuration will then automatically generate the mipmaps.

**Comment by newpeople123** [comment]
sure,thank you very mush
