### ISSUE TITLE
how to use schema.json to extend gltf 

### ISSUE THREAD

**Issue by chen21439** [KhronosGroup/glTF#2317]
[[featureIdTexture.schema.json](https://github.com/CesiumGS/glTF/blob/3d-tiles-next/extensions/2.0/Vendor/EXT_mesh_features/schema/featureIdTexture.schema.json).](https://github.com/CesiumGS/glTF/tree/3d-tiles-next/extensions/2.0/Vendor/EXT_mesh_features)

for example in the document,it use shema.json to generate featureId for each vertex,i want to know waht  software  can do this ,can you give me more information

**Comment by javagl** [comment]
GitHub issues are not a forum. This is not an issue with the glTF specification. It is also not an issue with the glTF-Tutorials. I'll close this here, and write a _little_ bit more at https://github.com/KhronosGroup/glTF-Tutorials/issues/87
