### ISSUE TITLE
Why is the official capitalization glTF instead of GLTF?

### ISSUE THREAD

**Issue by aaronfranke** [KhronosGroup/glTF#2332]
I've been using glTF for years at this point, but I always found is strange that it's capitalized as "glTF". Why?

> glTF™ (GL Transmission Format) is a royalty-free specification

It comes from GL Transmission format, where the GL is for OpenGL. If we shorten Transmission Format to TF we would get GL TF. Why is it that when we combine these into one word, the "gl" becomes lowercase, but TF stays uppercase?

Lowercasing "gl" is inconsistent with other Khronos group standards. The GL Shading Language is shortened to GLSL, but if it were following the same pattern as glTF, it should be called "glSL", but it's not. "glTF" is the only acronym in Khronos that does this (as far as I know). Even just looking in the context of glTF and Khronos, it's not consistently lowercase, for example [UnityGLTF](https://github.com/KhronosGroup/UnityGLTF) is all caps, and the description is "Unity3D library for ... GLTF 2.0 assets".

In general, having a mixed-case acronym is quite unusual. There's only a few exceptions in the wild, usually for minor words like "a", "of" and "the", like "NaN" being "not a number". Usually when names have both acronyms and lowercase letters, it's because part of the name is a word, like "WebGL" or "OpenXR". But "gl" is not a word.

Furthermore, there is a problem with people confusing the l for an I (confusing the lowercase L `l` for an uppercase i `I`). This is especially problematic on Wikipedia which enforces an uppercase letter for the page name in the URL, making it "GlTF" `GlTF`, which looks nearly identical to "GITF" `GITF`. A reader looking at the URL would likely have no clue that there's supposed to be a lowercase letter in there.

I can't think of any reason to make "gl" lowercase. So: Why is it lowercase?

**Comment by javagl** [comment]
It's not a real answer, but ... 11 years ago, someone made [a proposal](https://www.khronos.org/pipermail/public_webgl_khronos.org/2012-November/006162.html) (called "WebGLTF" back then...). Shortly after that, the [`glTF` repository was created](https://github.com/KhronosGroup/glTF/tree/7f8f0e16c04d4c8cf6027aa64b0a29d202e9e002). Somewhere between that, people decided that the name should be 'glTF'. Maybe someone from back then wants to chime in here, but it's hard to imagine that they had Wikipedia URLS in mind...

**Comment by lexaknyazev** [comment]
Although glTF 1.0 was made for WebGL 1.0 (OpenGL ES 2.0), the primary focus was still on "Transmission Format"; derivation from GL was secondary so lower case.

This became even more relevant with glTF 2.0, which does not specifically target any graphics API.

**Comment by aaronfranke** [comment]
Ok, that makes sense. "gl" indicates its history with OpenGL, but it is no longer closely related to it. Thanks.
