### ISSUE TITLE
Can GLTF model structure be customized with additional properties?

### ISSUE THREAD

**Issue by nRammm** [KhronosGroup/glTF#2334]
Hi ,I'm a beginner for GLTF. 
I'm basically trying to use GLTF models as input for [Azure Remote Rendering](https://learn.microsoft.com/en-us/azure/remote-rendering/).

I have a custom formatted model which has certain model properties associated with it. For example let the custom model be a building and it has various properties like Length/Area/Volume/Mass/Angle of a pillar or any other objects in the model. Is there a way to include these properties in GLTF json structure? If yes , will that be a valid GLTF file?
Also does GLTF maintains any unique id for each objects in the model? If no , can that be customized as well?

**Comment by javagl** [comment]
It is _technically_ possible to just add anything to a glTF JSON file, and it will not affect the validity (as long as it does not interfere with the _existing_ properties, of course). But this is 

# not recommended!!!

No application will know how to produce or consume these properties, and any application that reads and then writes the glTF asset will likely throw away this data.

---

A _slightly_ more portable way is to use the [`extras`](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#reference-extras) property that is basically defined for every glTF property. So you could have something like 
```
  "nodes" : [
    {
      "mesh" : 0,
      "extras": {
          "myCustomData": { 
              "mySpecificValue": 12345
          }
      }
    }
  ],
```
to store your `myCustomData` object with its `mySpecificValue`. But this is still only _application-specific_. You'd still have to expect third-party applications to ignore or remove this data. 

---

The most portable way is to use an _extension_ to store this data. There are different extensions to store various forms, for example, [`KHR_xmp_json_ld`](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_xmp_json_ld/README.md), but the details will heavily depend on the application case.

---

> Also does GLTF maintains any unique id for each objects in the model? If no , can that be customized as well?

glTF does not maintain unique IDs. There recently has been a discussion about that, at https://github.com/KhronosGroup/glTF/issues/1051#issuecomment-1744560817 .
