### ISSUE TITLE
Converting SpecularGlossiness back to MetallicRoughness

### ISSUE THREAD

**Issue by vpenades** [KhronosGroup/glTF#2342]
A while ago, I noticed SpecularGlossiness  has been archived.

Also, more material extensions have been introduced, like Specular and IOR

I was wondering if it's possible to easily _transfer_ the properties of SpecularGlossiness back to MetallicRoughness with the help of the newer extension.

Or is it a more complex process, which would require to do texture conversions?

Is there an official approach on how to deal with MetallicRoughness on models in the wild, now that it's been archived?

**Comment by donmccurdy** [comment]
Some resources:

- [KHR_materials_specular / Conversions](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_materials_specular/README.md#conversions)
- Discussion: https://github.com/KhronosGroup/glTF/pull/1719#issuecomment-674365677
- Implementation in glTF Transform: https://github.com/donmccurdy/glTF-Transform/blob/fad253d2925056f62b828137d5148d6a11c72e39/packages/functions/src/metal-rough.ts#L49-L127

It is necessary to either rewrite textures (probably an offline process) or wrap textures in an expression (e.g. using a shader graph or custom GLSL replacing the texture lookup, as input to a PBR surface definition).

For three.js users we've encouraged during the conversion offline, as the texture rewrites are a bit slow.

```bash
npm i --global @gltf-transform/cli

gltf-transform metalrough in.glb out.glb
```

**Comment by vpenades** [comment]
ouch!, I hoped there would be some easy conversion path, so I could get rid of the extension on load.

Given the conversion is non trivial, I guess I'll have to keep the extension around for backwards compatibility.

Thanks!
