### ISSUE TITLE
Should image have a name property?

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#235]
Same question as #234 but for an `image`.
```json
"images": {
        "image_0": {
            "path": "duckCM.png"
        }
    }
```
When I first did the schema I probably carried this over from COLLADA.  Do we want to keep a `name` property here?

**Comment by tfili** [comment]
Should we be doing this with lights and cameras as well?

**Comment by tparisi** [comment]
yes -

On Thu, Oct 1, 2015 at 4:46 PM, Tom Fili <notifications@github.com> wrote:

> Should we be doing this with lights and cameras as well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KhronosGroup/glTF/issues/235#issuecomment-144879165>.
>



-- 


Tony Parisi                             tparisi@gmail.com
Follow me on Twitter!             http://twitter.com/auradeluxe
Read my blog at                     http://www.tonyparisi.com/
Learn WebGL                         http://learningwebgl.com/
Mobile                                    415.902.8002
Skype                                     auradeluxe

Read my books!
*Learning Virtual Reality*
http://www.amazon.com/Learning-Virtual-Reality-Experiences-Applications/dp/1491922834


*Programming 3D Applications in HTML5 and
WebGLhttp://www.amazon.com/Programming-Applications-HTML5-WebGL-Visualization/dp/1449362966
<http://www.amazon.com/Programming-Applications-HTML5-WebGL-Visualization/dp/1449362966>WebGL,
Up and Running*
http://www.amazon.com/dp/144932357X

**Comment by tfili** [comment]
Added name property to lights, cameras and images in dev-1.0 branch at 1d4370f856d8f913d0fcab3165abe2368061b659

**Comment by pjcozzi** [comment]
@tfili did you also confirm that all names are propagated from COLLADA to glTF?

What about ids (#9)?

**Comment by pjcozzi** [comment]
@tfili did you see this:

> did you also confirm that all names are propagated from COLLADA to glTF?

**Comment by tfili** [comment]
@pjcozzi I'll double check when I get home.

**Comment by tfili** [comment]
@pjcozzi Looks like skins didn't have it but I added it with 2e9edf0a5de181e277e863b8f40c4f0d0b75d0d3

**Comment by pjcozzi** [comment]
Great, thanks @tfili!

**Comment by tparisi** [comment]
thanks @tfili
