### ISSUE TITLE
Length unit clarification

### ISSUE THREAD

**Issue by alteous** [KhronosGroup/glTF#2350]
Hi, I would like to clarify [section 3.4](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#coordinate-system-and-units)  which states:

> The units for all linear distances are meters.

Does this apply to mesh positions in their original form or the positions after transformation in the scene? Both are equally valid scenarios.

I'm wondering if, for example, a cubic metre measured in millimetres (i.e., 1000x1000x1000 units) placed in the scene with a uniform scale factor of 0.001 would be incorrect.

**Comment by lexaknyazev** [comment]
This is further clarified in [Section 3.7.4](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#instantiation):
> After applying the node’s global transform, mesh vertex position values are meters.
