### ISSUE TITLE
GRIFFEL_bim_data.schema.json is an invalid json schema

### ISSUE THREAD

**Issue by teddemunnik** [KhronosGroup/glTF#2373]
`GRIFFEL_bim_data.schema.json` appears to be an invalid json shema.

The [`item`](
https://github.com/KhronosGroup/glTF/blob/ae1a90baf009203760304f06ed5645402de9dc09/extensions/2.0/Vendor/GRIFFEL_bim_data/schema/GRIFFEL_bim_data.schema.json#L20C18-L20C34)  property in ` properties/nodeProperties/items/properties/properties` should be `items`.

**Comment by javagl** [comment]
I think that it's not _invalid_ in the strictest sense: The `item` in this case just counted as an [additional property](https://json-schema.org/understanding-json-schema/reference/object#additionalproperties) (and _arbitrary_ ones are allowed by `draft-04` by default). 

But it clearly was the intention to make sure that the `properties` array in the JSON itself (not the JSON schema, but the JSON) was supposed to only contain IDs (integer values). (Right now, I think that the schema would allow arbitrary objects...)

PR in https://github.com/KhronosGroup/glTF/pull/2375
