### ISSUE TITLE
Question about Accessor's Min-Max bounds with normalized data.

### ISSUE THREAD

**Issue by vpenades** [KhronosGroup/glTF#2387]
Lets say I have an array of bytes and an accessor that has the normalization flag enabled, so the byte values are scaled to values between 0 and 1.

In that scenario, if the accessor has min-max bounds defined, should the values be set

- Between 0 and 255 as per the accessor's input?
- Between 0 and 1 as per the accessor's output?

Right now gltf-validator seems to be checking the bounds as per the accessor's input, that is, 0 and 255. Is that correct?

**Comment by lexaknyazev** [comment]
Here's the spec language for min/max: https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#_accessor_max
> `normalized` property has no effect on array values: they always correspond to the actual values stored in the buffer.
