### ISSUE TITLE
Technique parameter questions

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#239]
I'm writing the schema for techniques and want to confirm several things:

1) `values` is either a scalar or an array, depending on `type`, e.g., 
```json
                "light0Color": {
                    "type": 35665,
                    "value": [1, 1, 1]
                },
```
I want to confirm that we prefer this over making `value` an array of size one for scalar values.  What we have now makes the spec slightly more complicated, but it is slightly better code-wise for my implementation.

2) Do we want (a) `type` to always be required, or (b) `type` to be optional if `semantic` is provided and have a sensible default.  For example:

(a) Required:
```json
                "modelViewMatrix": {
                    "semantic": "MODELVIEW",
                    "type": 35676
                }
```
(b) Optional:
```json
                "modelViewMatrix": {
                    "semantic": "MODELVIEW"
                }
```

3) Should we rename `source` to `node`?  Or will this property reference other types?
```json
                "lightTransform": {
                    "source": "directional_light_node_id",
                    "type": 35676
                }
```

4) We have a list of semantics for uniforms ([#83](https://github.com/KhronosGroup/glTF/issues/83#issuecomment-24095883)), but what are the semantics for attributes.  So far, I know of:

* `JOINT`
* `JOINT_MATRIX`
* `WEIGHT`
* `POSITION`
* `NORMAL`
* `TEXCOORD_0` (and others I suspect)

**Comment by pjcozzi** [comment]
@tfili we can close this issue once we rename a [technique parameter's](https://github.com/KhronosGroup/glTF/blob/spec-1.0/specification/schema/techniqueParameters.schema.json) `source` to `node` in the converter.  The 0.8 schema already has this update, but Cesium is looking for `source` so I suspect the converter is not updated.

**Comment by tparisi** [comment]
Sorry I'm lost on this one. It's currently `source` why not just keep that?

**Comment by tparisi** [comment]
And in fact, if we want to start dealing with issues I brought up r/e a light's direction #409 then we could in fact use a `target` attribute similar to animation channels. e.g. 

```javascript
                "light0Direction": {
                    "source": "directionalLight1",
                    "target": "direction",
                    "type": 35665
                },

**Comment by pjcozzi** [comment]
We decided on `node` above because it is consistent with glTF, when we reference something by id, we use the type as the name: bufferViews have a `buffer` property, accessors have a `bufferView` property, etc.

However, I am happy to pause on this rename until lights are solid.

**Comment by tparisi** [comment]
Actually I meant `path` but I wrote `target` so it should be

```javascript
                "light0Direction": {
                    "source": "directionalLight1",
                    "path": "direction",
                    "type": 35665
                },
```

**Comment by tparisi** [comment]
But it could be `node` just as well as `source`; I get your consistency argument and it is more explicit.

So I say go for it. LMK when the converter change is made. I also need converted models for the Three.js loader to test it.

**Comment by pjcozzi** [comment]
Sounds good.

**Comment by tparisi** [comment]
Changed source->node in d84a366.

**Comment by pjcozzi** [comment]
Thanks @tparisi.  @tfili this just needs a converter update for us to close it.

**Comment by pjcozzi** [comment]
@tfili is the converter updated?

**Comment by tfili** [comment]
The source->node change is in dev-1.0 branch.

**Comment by pjcozzi** [comment]
Nice.
