### ISSUE TITLE
Undefined behaviour in KHR_materials_volume

### ISSUE THREAD

**Issue by UX3D-haertl** [KhronosGroup/glTF#2390]
As described in this sample viewer issue: https://github.com/KhronosGroup/glTF-Sample-Viewer/issues/489

The KHR_materials_volume spec defines the following equation:

> σt = -log(c) / d

where `c` is `attenuationColor` and `d` is `attenuationDistance`.
If any of the color components are zero this leads to undefined behaviour.
This can be tested with e.g. Sample Viewer or three.js.

In the sample viewer issue the introduction of an epsilon value is suggested.
Clarification for this issue should be added to the specification.

**Comment by emackey** [comment]
TODO: We should test this with a sample model using various colors, some of which have zeros in certain color channels, to confirm if the epsilon solution is working correctly.

**Comment by emackey** [comment]
Test model created.  This is based on AttenuationTest, but the blocks here lose all red, then all red and green, then half blue, then finally attenuation color becomes completely black.

[AttenuationToZero.zip](https://github.com/user-attachments/files/15538794/AttenuationToZero.zip)

![screenshot](https://github.com/KhronosGroup/glTF/assets/1235080/c9957c08-9aa5-4d20-84d1-e79cda121b6f)

**Comment by UX3D-haertl** [comment]
The issue is only visible with a large attentuation distance. I this changed model the left most material has an epsilon in the red channel while the second cube has red set to 0. Both have a attentuation distance of 30.
![grafik](https://github.com/KhronosGroup/glTF/assets/50208655/6dc9852a-1ca5-4065-b6e0-293e6bba6885)
[AttenuationToZero_Dist.zip](https://github.com/user-attachments/files/15545349/AttenuationToZero_Dist.zip)

**Comment by UX3D-haertl** [comment]
Here the epsilon is 1e-7 if I use an epsilon of 1e-64 the colors match roughly. But such values hardly make sense for e.g. 8 bit colors and I don't think the color output is the expected result.
Also since log(0) is undefined behaviour in GLSL the result can vary based on the driver implementation of the specific graphic crad.
https://registry.khronos.org/OpenGL-Refpages/es3.0/html/log.xhtml

**Comment by emackey** [comment]
We want to avoid `log(0)` of course, and I don't think having zeros in the color makes any physical sense unless the material is intended to be completely opaque in that color channel. Should we warn users not to place zeros there?  Or should there be special case code to avoid calling `log(0)` and instead set that component to 100% absorption?  Seems like the latter would hurt performance and add complexity.

If the 1e-7 epsilon is used, perhaps I'll contribute a warning to the validator to tell users to stay away.

**Comment by emackey** [comment]
Remember this is color per distance here.  "After 1 meter, red loses half its strength, and after another meter, red loses half its remaining strength" is a valid absorption per distance rate.

But, "After one meter, green is completely absorbed" is a different statement, no?  How fast was green absorbed?

**Comment by lexaknyazev** [comment]
The current code is
```glsl
vec3 attenuationCoefficient = -log(attenuationColor) / attenuationDistance;
vec3 transmittance = exp(-attenuationCoefficient * transmissionDistance);
```

Let's inline the `attenuationCoefficient` removing both minus signs:
```glsl
vec3 transmittance = exp((log(attenuationColor) / attenuationDistance) * transmissionDistance);
```

Let's regroup a bit:
```glsl
vec3 transmittance = exp(log(attenuationColor) * (transmissionDistance / attenuationDistance));
```

Both `exp` and `log` could be removed now:
```glsl
vec3 transmittance = pow(attenuationColor, transmissionDistance / attenuationDistance);
```

**Comment by emackey** [comment]
That simplification looks great!  We should test it with the original AttenuationTest sample asset as well as the ones provided in this thread.  Perhaps we should include the simplified math in the spec too?
