### ISSUE TITLE
3.7.3.3 how many non-zero weights per vertex

### ISSUE THREAD

**Issue by tksuoran** [KhronosGroup/glTF#2393]
> Joints MUST NOT contain more than one non-zero weight for a given vertex.

What does that mean, exactly?

**Comment by donmccurdy** [comment]
The line was added in a larger set of clarifications by #1997. The intended meaning is closer to:

"A vertex MUST NOT contain more than one non-zero weight for the same joint."

Probably this wording could be improved further.
