### ISSUE TITLE
3.7.2.1 COLOR_0 is special?

### ISSUE THREAD

**Issue by tksuoran** [KhronosGroup/glTF#2394]
> All components of each COLOR_0 accessor element MUST be clamped to [0.0, 1.0] range.

Is it intentional that clamping only applies to the first color attribute?

**Comment by lexaknyazev** [comment]
Only the `COLOR_0` attribute has defined usage - an additional base color multiplier. If an asset has also, e.g., `COLOR_1`, its usage is not defined hence no clamping is required.
