### ISSUE TITLE
Request for MANYFOLD vendor prefix

### ISSUE THREAD

**Issue by Floppy** [KhronosGroup/glTF#2398]
Hi; I'd like to request a vendor prefix for Manyfold, a web application for 3d print file management, as I intend to create a glTF extension for progressive transmission of mesh data (different to LOD which I see is already a thing).

Prefix: MANYFOLD
Organisation: Manyfold
Website: https://manyfold.app 
Contact: James Smith <james@floppy.org.uk>

**Comment by emackey** [comment]
Done
