### ISSUE TITLE
Bone Animation, not using Skinning

### ISSUE THREAD

**Issue by Winteradio** [KhronosGroup/glTF#2408]
I am currently working on creating a simple viewer for bone animation using the glTF format before implementing skinning animation. However, it seems that the documentation and guides available mostly integrate bone (with simple cubes placed at joint positions) animation as part of skinning. There appears to be no separate guide specifically for using bones on their own.

Additionally, I am curious whether it is challenging to implement only bone animation using the animation data from within glTF, given that these animations are typically designed to interpolate the values of bones, rather than directly representing their movements.

**Comment by javagl** [comment]
This repository contains the specification of glTF itself. Issues here are intended for things that refer to the _specification_.  General questions about implementations should rather be asked elsewhere, for example, in the forum at https://community.khronos.org/c/gltf-general/45 , or ... in a repository that is somehow closer to the _implementation_ side.

---

That said... I don't fully understand what the question is. But I also needed a bit of time to get things like the [Skinning sections of the tutorial](https://github.com/KhronosGroup/glTF-Tutorials/blob/main/gltfTutorial/gltfTutorial_019_SimpleSkin.md) right. The latest updates there happened in a pull request, where @emackey provided some really helpful descriptions, e.g. around

- https://github.com/KhronosGroup/glTF-Tutorials/pull/64#issuecomment-969058924
- https://github.com/KhronosGroup/glTF-Tutorials/pull/64#issuecomment-970419863

Maybe that already helps.

**Comment by Winteradio** [comment]
I'm sorry for just leave question for this repo. I'll take a closer look at the example.
I'll leave a question post related to implementation on the site you provided.

Thank you for checking the question.

**Comment by javagl** [comment]
Yes, maybe the tutorial can be extended with further information about the _implementation_. If this is the case, you can open an issue with _specific_ questions or suggestions at https://github.com/KhronosGroup/glTF-Tutorials/issues . But depending on where and how you want to implement this (in Three.js or BabylonJS or so...), then you might receive quicker (and more focussed) help at other places, like the forums.

**Comment by UltraEngine** [comment]
I don't see why there would be any problem when not using skins. I visualize skeletons and load animations from other glTF files with no issues. It would be just the same as displaying a BVH file or something like that.
