### ISSUE TITLE
In KHR_texture_transform extension, uv should be "fract" before transforming？

### ISSUE THREAD

**Issue by PrimaryFantasty** [KhronosGroup/glTF#2412]
[Current](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_texture_transform/README.md):
```
varying in vec2 Uv;

uniform vec2 Offset, Scale;
uniform float Rotation;

mat3 translation = mat3(1,0,0, 0,1,0, Offset.x, Offset.y, 1);
mat3 rotation = mat3(
    cos(Rotation), sin(Rotation), 0,
   -sin(Rotation), cos(Rotation), 0,
                0,             0, 1
);
mat3 scale = mat3(Scale.x,0,0, 0,Scale.y,0, 0,0,1);

mat3 matrix = translation * rotation * scale;
vec2 uvTransformed = ( matrix * vec3(Uv.xy, 1) ).xy;
```

But in [CesiumJS 1.96](https://github.com/CesiumGS/cesium/blob/1.96/Source/Scene/processPbrMaterials.js#L697):
``` glsl
  fragmentShader +=
    "vec2 computeTexCoord(vec2 texCoords, vec2 offset, float rotation, vec2 scale) \n" +
    "{\n" +
    "    rotation = -rotation; \n" +
    "    mat3 transform = mat3(\n" +
    "        cos(rotation) * scale.x, sin(rotation) * scale.x, 0.0, \n" +
    "       -sin(rotation) * scale.y, cos(rotation) * scale.y, 0.0, \n" +
    "        offset.x, offset.y, 1.0); \n" +
    "    vec2 transformedTexCoords = (transform * vec3(fract(texCoords), 1.0)).xy; \n" +
    "    return transformedTexCoords; \n" +
    "}\n\n";
```

The difference between them is that interpolated UVs has been "fract" before transforming，and they make different effect.
So what kind of them should I take?

**Comment by javagl** [comment]
(Just a cross-link to the forum post: https://community.cesium.com/t/why-modified-the-behavior-of-khr-texture-transform-extension-since-cesiumjs-1-97/32984 )

**Comment by scurest** [comment]
The fract is incorrect.

**Comment by javagl** [comment]
Thanks @scurest , I also _suspected_ that. I'm not entirely sure how to confirm that to an extent that would allow closing this issue. Using https://github.com/cx20/gltf-test to look at the [`TextureTransformTest`](https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/TextureTransformTest), namey [rendered in CesiumJS](https://cx20.github.io/gltf-test/examples/cesium/index.html?category=tutorialModels&model=TextureTransformTest&scale=1.0&type=glTF), it looks correct:

![Cesium Texture Transform Test](https://github.com/KhronosGroup/glTF/assets/5597569/543b5a49-9778-4782-aef1-3cede4e49b8a)

With the small caveat that it's not clear whether the model contains texture coordinates where `fract` would actually make a difference. (I suspect such models are rare to begin with).

I'd vote to close this, saying that the `fract` does not seem to make sense (and is also not used in the sample GLSL code of the specification). So I assume that this **was** a bug in earlier CesiumJS version, but has been fixed with the "Model" rewrite that happened in 1.97.

**Comment by PrimaryFantasty** [comment]
> The fract is incorrect.分形不正确。

Thanks for your reply!

**Comment by PrimaryFantasty** [comment]
> Thanks @scurest , I also _suspected_ that. I'm not entirely sure how to confirm that to an extent that would allow closing this issue. Using https://github.com/cx20/gltf-test to look at the [`TextureTransformTest`](https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/TextureTransformTest), namey [rendered in CesiumJS](https://cx20.github.io/gltf-test/examples/cesium/index.html?category=tutorialModels&model=TextureTransformTest&scale=1.0&type=glTF), it looks correct:
> 
> ![Cesium Texture Transform Test](https://private-user-images.githubusercontent.com/5597569/340307288-543b5a49-9778-4782-aef1-3cede4e49b8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2Mjg1NDUsIm5iZiI6MTcxODYyODI0NSwicGF0aCI6Ii81NTk3NTY5LzM0MDMwNzI4OC01NDNiNWE0OS05Nzc4LTQ3ODItYWVmMS0zY2VkZTRlNDliOGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTdUMTI0NDA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzM5MzdjMGFjN2JiNWViYTQzMzE4MmNjN2ViNTA1ZDBiYTcxZTNmZjZkMmM3ODRiYmFjNzQ0MTRlNzNkNzcwYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gbOO0yOod0_8-c3TT3PBL8P2WlQRIIO4P-i5TuiizHc)
> 
> With the small caveat that it's not clear whether the model contains texture coordinates where `fract` would actually make a difference. (I suspect such models are rare to begin with).
> 
> I'd vote to close this, saying that the `fract` does not seem to make sense (and is also not used in the sample GLSL code of the specification). So I assume that this **was** a bug in earlier CesiumJS version, but has been fixed with the "Model" rewrite that happened in 1.97.

Thank you!
In fact, The first time I found it was that in [ Esri I3S uvRegion](https://github.com/Esri/i3s-spec/blob/master/docs/1.7/geometryUVRegion.cmn.md), which contains the concept of uvRegion. Certainly, It's different from"KHR_texture_transorm", I tried converting it into glTF by adding a custom glTF extesion in Cesium to adapt "uvRegion", but the same to you, I'm not sure the meaning of this detail, cause of CesiumJS 1.96, 1.97 and "uvRegion" in I3S.

**Comment by PrimaryFantasty** [comment]
![image](https://github.com/KhronosGroup/glTF/assets/36122477/d308254e-cbe1-4c8f-9418-40a63756463c)
@javagl I made a typo, sry~

**Comment by emackey** [comment]
Sounds like this was resolved.  Please re-open if any spec issues remain to be addressed here, thanks.
