### ISSUE TITLE
Request for MODUPLAY vendor prefix

### ISSUE THREAD

**Issue by ModuplayMatthewH** [KhronosGroup/glTF#2445]
Hello. Moduplay Group Pty Ltd would like to request the MODUPLAY vendor prefix.

**Comment by javagl** [comment]
To confirm:

The exact name will be
**Moduplay Group Pty Ltd.**

The website will be https://moduplaygroup.com.au/ 
(and **not** https://moduplay.com.au/)

A mail contact could be added (like `name at example.com`), although this is not strictly required.

**Comment by ModuplayMatthewH** [comment]
Yes, I can confirm that is correct.

Company name: Moduplay Group Pty Ltd.

Website: https://moduplaygroup.com.au/

Mail contact can be: matthew.h at moduplay.com.au
