### ISSUE TITLE
proposal for video property

### ISSUE THREAD

**Issue by fabrobinet** [KhronosGroup/glTF#245]

**Comment by cvan** [comment]
Have there been any discussions to consider this for 2.0? If an extension were to be proposed, any advice on the schema? @pjcozzi, @fabrobinet, any ideas?

**Comment by pjcozzi** [comment]
@cvan thanks for the interest.  This is not in the scope for 2.0, but we would very much welcome an extension.  I don't know enough about video to provide guidance on the schema, but you can check out the spec and schemas for the other extensions [here](https://github.com/KhronosGroup/glTF/tree/master/extensions).

**Comment by pjcozzi** [comment]
Closing, but feel free to open a new issue if you have a concrete proposal or even detailed use cases.
