### ISSUE TITLE
Does GLTF 2.0 permit shared nodes?

### ISSUE THREAD

**Issue by Densaugeo** [KhronosGroup/glTF#2461]
I attempted to create a .gltf file consisting of several gears. There is a mesh for a gear tooth, and each gear is a node with several teeth arranged in a circle. However, when I attempt to place a second gear in the same scene it isn't rendered (I am using three.js for display).

The spec for `node-children` states: "Each element in the array MUST be unique" and "Each element in the array MUST be greater than or equal to 0", so there is no obvious restriction on this.

Someone in another issue thread on this repo (https://github.com/KhronosGroup/glTF/issues/1547) claims that "We specify that a node cannot be a child of two different nodes", but I cant find that in the spec so I don't know if it's current.

I can find very little on Google about this topic. There's a few discussions of "joint nodes", but those seem to be something else.

Can I get a clarification on whether the spec permits multiple references to the same node?

**Comment by javagl** [comment]
[Section 3.5.2. Nodes and Hierarchy](https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#nodes-and-hierarchy) of the specification says

> The node hierarchy **MUST** be a set of disjoint strict trees. That is node hierarchy **MUST NOT** contain cycles and each node **MUST** have zero or one parent node.

**Comment by javagl** [comment]
(So the answer to the question in the title is "No" 🙂 )

**Comment by Densaugeo** [comment]
Didn't see that section earlier, that is pretty clear.

**Comment by donmccurdy** [comment]
One very pedantic exception – different _scenes_ may contain references to the same (root) _nodes_. So client implementations do need some capability to instantiate a particular node more than once.  But as @javagl mentions, reuse of a node within a scene is not allowed, and so in practice the reuse of data within a scene means having different nodes that point to the same resources (meshes, lights, etc.).
