### ISSUE TITLE
textures

### ISSUE THREAD

**Issue by fl4re** [KhronosGroup/glTF#248]
There are a few things to do to in the run-time to get textures. Here's below a set of those settings, and their gltf equivalent

+ set texture coordinates into the shader
WebGL
```
gl.bindBuffer(gl.ARRAY_BUFFER, glBuffer);
gl.vertexAttribPointer(location, 4, gl.FLOAT, false, 0, 0);
 
```
gltf:
```
  "techniques": {
    "technique0": {
      "parameters": {    
        "texcoord0": {
          "semantic": "TEXCOORD_0",
          "type": 35664
        }
      },
      "passes": {
        "defaultPass": {
          "instanceProgram": {
            "attributes": {
              "a_texcoord0": "texcoord0"
            }
          }
        }
      }
    }
  }

```

+ set the uniform to a texture unit
WebGL
```
gl.uniform1i(location, textureUnitIndex);
```
gltf:
```
    "techniques": {
        "technique0": {
            "parameters": {
                "diffuse": {
                    "type": 35678
                },
            },
            "passes": {
                "defaultPass": {
                    "instanceProgram": {
                        "uniforms": {
                            "u_diffuse": "diffuse"
                        }
                    }
                }
            }
        }
    },
```

2) make sure the texture unit contains the right texture
WebGL
```
gl.activeTexture(gl.TEXTURE0 + textureUnitIndex);
gl.bindTexture(gl.TEXTURE_2D, someTexture);
```

gltf
```
"materials": {
  "blinn3-fx": {
    "instanceTechnique": {
      "technique": "technique0",
        "values": {
          "diffuse": "texture_image_0"
        }
      }
  }
}
```

The issue is that the bindTexture step is implicit in gltf. The value is correctly available in the material using the technique, (except for textureUnit which is not provided in glrf) but the state has to be managed by the run-time, like another states. 
So, rather than making this step special and implicit, could we add the information inside the "states": of the pass, like we are already doing for the rest of the state.

```
"states": {
   "blendEnable": 0,
   "cullFaceEnable": 1,
   "depthMask": 1,
   "depthTestEnable": 1,
   "bindTexture": "diffuse"    <-- this should be added as explicit state setup for shader
}
```

The "diffuse" refer to the uniform, which value is set by the material. There is still no textureUnit value provided by glTF so the run-time has to go through some internal logic to deal with this and make sure the same textureUnit value is used when calling setUniform, and calling bindTexture.

I think we should also consider adding textureUnit - as a suggested value for the run-time to use. This could enable the compiler or optimizer or end-user to calculate textureUnits for optimizing gl commands.

**Comment by pjcozzi** [comment]
If we want to change this, please provide a concrete JSON proposal.  At this point we have implementations in major engines, including Cesium, Three, and BabylonJS that have not had issues here so I suggest we close this issue.

**Comment by pjcozzi** [comment]
No update so closing.  We can revisit post 1.0 if needed.
