### ISSUE TITLE
states

### ISSUE THREAD

**Issue by RemiArnaud** [KhronosGroup/glTF#249]
A technique can have states.
But what do they signify exactly?

1) the difference between the WebGL default state and the state needed by this technique?
or
2) the set of states and values that are important for this technique

In order to do lazy state management, and minimize the number of WebGL calls, I would be better if if was the second case.

in the first case, one has to know what the default state values are, and when applying a technique, it has to reset the state to the default value if they are not listed in the technique. But there are several states that a technique does not care about at all. So this is wasteful.

In the second case, only the states listed in the Technique need to be checked, and set if different. In the second case even if the state is the same as the default state value, it has to be listed explicitly in the Technique.

**Comment by pjcozzi** [comment]
Closing as duplicate with #85.
