### ISSUE TITLE
Investigate JSON Schema 4

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#252]
The glTF schema is written using JSON Schema 3.

I'll look into [JSON Schema 4](http://json-schema.org/documentation.html).  We'll use it if it adds value, which will mean switching the validator from [JSV](https://github.com/garycourt/JSV) to [JJV](https://github.com/acornejo/jjv) (or another validator that supports Schema 4).

**Comment by pjcozzi** [comment]
I don't plan on moving from JSON Schema 3 to 4 right away, but here's:
* [A guide on moving from 3 to 4](https://github.com/json-schema/json-schema/wiki/ChangeLog)
* [A guide on JSON schema](http://spacetelescope.github.io/understanding-json-schema/) in general

**Comment by sbtron** [comment]
Wanted to hit this up again as we are looking into implementing a native glTF parser using [rapidJSON](https://github.com/miloyip/rapidjson/).  rapidJSON needs JSON Schema 4. I can work on updating to the schema needed to go from 3 to 4. Are there any other updates needed around validators etc. if the schema was updated from 3 to 4?

**Comment by pjcozzi** [comment]
This would be fantastic.

For some examples using JSON Schema 4, check out how we use it for 3D Tiles (including validation):

https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/schema#3d-tiles-json-schema

It would not be required right away, but we would also very much welcome a contribution to update wetzel:

https://github.com/AnalyticalGraphicsInc/wetzel

which is a small Node.js tool I wrote to generate the property references in the spec from the schema.

There is also a C# loader that was generated from the schema that we would have to determine the best path forward for; I'm not sure if it is being maintained:

https://github.com/KhronosGroup/glTF/tree/master/loaders/CSharp

**Comment by pjcozzi** [comment]
Fixed in #769 and friends
