### ISSUE TITLE
meshes vs instanceSkin

### ISSUE THREAD

**Issue by RemiArnaud** [KhronosGroup/glTF#255]
This is related to #100, I thought it would be better to create an new issue to discuss a specific design matter rather than adding to #100. 

In node, we can have meshes and instanceSkin

Design wise, I think we can improve this bringing better uniformity. Basically, I think we either should have instanceMesh and instanceSkin, or we can have meshes and skins in node.

Basically an instanceXX - as in instanceProgram - enable referencing a shared/read-only object and augmenting or specializing it with additional parameters. so far we have made node reference specific objects, and not use instances. This may create a bit of duplication, but its a simpler design, and so far the duplications have been minor, and it IMHO it fits better a run-time format.

So, could we change a bit the skin design, so that node can reference a specific skin, rather than using a instanceSkin?

Other questions: can we have both skins and meshes in a node?
Also noticed: a node can have many meshes (meshes: []) but only one instanceSkin ?

**Comment by pjcozzi** [comment]
If we want to consider this for 1.0, please provide an concrete JSON schema proposal.

**Comment by pjcozzi** [comment]
Seeing no proposals, closing.

**Comment by tparisi** [comment]
Hold on, wasn't this really just a naming thing? Why not just go with `meshes` and `skin` as the property names on the node (vs instanceSkin)

In general I think we could ditch the 'instance' naming and simply things. A material could have a `technique` property instead of `instanceTechnique`-- you and I just discussed this earlier today.

**Comment by pjcozzi** [comment]
I'm not sure it is as simple as a rename, I think there is a semantic difference.  @fabrobinet any chance you recall?

If this is just a rename, then, yes, I am all for dropping the `instance` prefix.

**Comment by tparisi** [comment]
Beyond the rename, I don't think we want to contemplate a redesign right now.

Do you like the technique rename idea too?

**Comment by pjcozzi** [comment]
> Do you like the technique rename idea too?

Yes, but let's see the schema proposal.

**Comment by tparisi** [comment]
For which, the new materials/techniques/common design?

**Comment by pjcozzi** [comment]
I'm not sure what you are talking about anymore, but let's keep all material discussion in #84.

**Comment by pjcozzi** [comment]
For 1.0 for this issue I suggest we either

(1) do nothing, or
(2) "flatten" `instanceSkin` into `node` (like we did with the other instance properties for program and technique), e.g.,

**Before**
```json
        "Geometry-mesh019Node": {
            "children": [],
            "instanceSkin": {
                "meshes": [
                    "Geometry-mesh019"
                ],
                "skeletons": [
                    "locator047Node",
                    "locator051Node"
                ],
                "skin": "Controller-mesh019"
            },
            "matrix": [...],
            "name": "Cesium_Man"
        }
```

**After**
```json
        "Geometry-mesh019Node": {
            "children": [],
            "meshes": [
                "Geometry-mesh019"
             ],
            "skeletons": [
                "locator047Node",
                "locator051Node"
            ],
            "skin": "Controller-mesh019",
            "matrix": [...],
            "name": "Cesium_Man"
        }
```

This explicitly implies that a node can't have both a skin and meshes (for rendering), which we already say in the schema (https://github.com/KhronosGroup/glTF/issues/255#issuecomment-38458912).

@tparisi @tfili what do you think?  I'm OK with either option.  Let's try to converge ASAP.

**Comment by tparisi** [comment]
In general I am for simplifying

Tony Parisi
tparisi@gmail.com
415.902.8002

**Comment by tfili** [comment]
I'm good with simplifying as well.

**Comment by pjcozzi** [comment]
OK, let's do it.

* [ ] @tfili - update converter
* [ ] @pjcozzi - update schema
* [ ] @tparisi - update spec - if needed.

**Comment by tfili** [comment]
Updated converter in dev-1.0 at fb40b4c4c9cc303d8e925ed1ebe60b33873aa895

**Comment by pjcozzi** [comment]
@tparisi please close this when the spec is updated.

**Comment by tparisi** [comment]
@pjcozzi please review the language thanks

**Comment by pjcozzi** [comment]
Looks good.
