### ISSUE TITLE
converter - making skin optional

### ISSUE THREAD

**Issue by RemiArnaud** [KhronosGroup/glTF#256]
In COLLADA it is very easy for a loader to ignore skins and just use meshes if so desired.
In glTF, it is not so easy, especially considering the json and shaders are fairly different.

So, could we have an option in the converter, so the output would contains meshes only if so desired?

**Comment by pjcozzi** [comment]
I'm not sure if this is still an issue, but please submit to https://github.com/KhronosGroup/COLLADA2GLTF/issues if it is.
