### ISSUE TITLE
Windows build has dependant dll's

### ISSUE THREAD

**Issue by dlannan** [KhronosGroup/glTF#265]
Seems the windows build has a Debug MSVCP and MSVCR dll dependancy. Probably worth adding a link or adding to the download package.

**Comment by sayangel** [comment]
@dlannan just came across this thread. Currently my workflow is split between Unity and WebGL. As you mentioned, getting consistent output is difficult. Would love to learn about your Unity->UTF8 pipeline.

**Comment by dlannan** [comment]
Hi there - I did this all around a year ago. I still have the exporting tools, and they are being integrated in a 'bigger + badder' application based around Unity3D itself. I'm happy to share some of the code for this, I'll try to organize a github repo with the exporter in it.

To clarify the usage:  
- I use Unity3D as the "scene builder" and prepare a scene how I want. 
     This allows me to use all the 'import' methods of Unity3D to bring in the assets. I only support 
     basic shader setups (1 or 2 textures) and collapse materials in objects.
- Then I export the whole scene (or a single Object) to the UTF8 format
- Then I use my own ThreeJS setup to load in the assets and place them correctly. As I mentioned I have my own scene structure for this (it effectively reflects the Unity3D Node hierarchy). 

So if any of this sounds useful Id be happy to pass on some of the work. BTW - good luck with the VR, we recently have just completed a few man months of VRs (Oculus) + OVR + GreenScreen testing for use in simulators. Interesting results. Looking forward to more Hololens type toys :)

**Comment by sayangel** [comment]
hey @dlannan awesome! this is along the lines of what I've been looking for. Would really appreciate anything you'd be able to share and if I can help in any way I'd be happy to contribute. I've been trying to do the inverse of what you're doing and set up a scene in ThreeJS and load that into Unity. But I think what you've built will certainly help and maybe it's better if I go Unity to ThreeJS.

Thanks for the response! would love to hear more about your VR work too. Sounds really cool.

**Comment by sayangel** [comment]
hey @dlannan any updates? let me know if you need any help!

**Comment by dlannan** [comment]
Hi, 
So sorry.. Im currently flat out with work. 1 week of QA and such on my project to go. Should have some time after that.
I could possibly find the parts and put it in a zip, but it probably wont be very usable.
I'll hopefully get to it soon, please bump this in a week's time. :)




dlannan

From: sayangel
Date: 2015-05-20 02:14
To: KhronosGroup/glTF
CC: dlannan
Subject: Re: [glTF] Windows build has dependant dll's (#265)
hey @dlannan any updates? let me know if you need any help!

**Comment by dlannan** [comment]
Hi again,
Good news and bad news. I found the code - took a fair amount of digging, seems I didnt have it in my normal repo setup. I found what seems to be a broken version. I'll get it working again and put on github. The basic idea is it takes the OBJExporter for Unity and that was converted to generate UTF8 compliant output. It currently only supported 1 material per mesh, which is a little limiting, but that can be easily extended. I'll get back to you in a day or so once its all online.
Cheers,
Dave Lannan

**Comment by dlannan** [comment]
More good news. I also found why the export code was broken - I stopped using it. I forgot I had built my own OBJ -> UTF8 convertor tool, with a ThreeJS loader. Will have this up soon.

**Comment by dlannan** [comment]
To those that might be interested:
https://github.com/dlannan/unity-utf8exporter

**Comment by sayangel** [comment]
@dlannan awesome!! thanks for taking the time to dig this up. I'll take a look and let you know how it goes/make any PRs if I make useful changes :)
