### ISSUE TITLE
cube mapping proposal

### ISSUE THREAD

**Issue by fabrobinet** [KhronosGroup/glTF#266]
Right now cube mapping proposal is mixed with filtering discussion here: https://github.com/KhronosGroup/glTF/issues/40 let's discuss the schema in this issue

**Comment by pjcozzi** [comment]
I just we pass on this for 1.0 to keep us focused.

**Comment by pjcozzi** [comment]
Any thoughts on pushing this post 1.0?

**Comment by pjcozzi** [comment]
Pushing post 1.0.

**Comment by pjcozzi** [comment]
Close as duplicate with #835?

**Comment by lexaknyazev** [comment]
+1
