### ISSUE TITLE
Separate profile info from core spec

### ISSUE THREAD

**Issue by fabrobinet** [KhronosGroup/glTF#267]
And clearly provide:
- OpenGL ES 2.0
- WebGL 1.0 profiles

**Comment by pjcozzi** [comment]
This is in the schema (API, e.g., WebGL, and version, e.g., 1.0.3 will be separate properties in the [1.0 schema](https://github.com/KhronosGroup/glTF/blob/spec-1.0/specification/assetProfile.schema.json)).

I don't think we have the bandwidth to create an ES 2.0 profile for the draft glTF 1.0.  @tparisi what do you think?

**Comment by pjcozzi** [comment]
These are separate in the schema and glTF 1.0 will only have a WebGL profile.
