### ISSUE TITLE
Split meshes for skinning according to the maximum number of uniforms 

### ISSUE THREAD

**Issue by fabrobinet** [KhronosGroup/glTF#283]
... available per profile spec or as passed in argument in config file.

**Comment by pjcozzi** [comment]
I believe we just ran into this issue in practice: the vertex shader for a skinned model does not compile because it exceeds the uniform limit.  The model is attached here: https://groups.google.com/forum/#!topic/cesium-dev/nSFWk7snrXE

**Comment by pjcozzi** [comment]
Replaced by https://github.com/KhronosGroup/COLLADA2GLTF/issues/110
