### ISSUE TITLE
OSX 10.8 Build Issue

### ISSUE THREAD

**Issue by Digicrat** [KhronosGroup/glTF#287]
I successfully built the gltf converter on this machine running OSX 10.8.5 a month or two ago using the directions at https://github.com/KhronosGroup/glTF/wiki/converter and xcodebuild.  

I just did an update and am unable to rebuild the converter.  The root error I'm seeing is below apparently related to 'unordered_map'.  I found the link to a prebuilt binary of the latest version which is working fine for me in the interim.  

014-06-16 11:31:56.871 xcodebuild[28380:317]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-3575/Xcode3Sources/XcodeIDE/Frameworks/DevToolsBase/pbxcore/SpecificationTypes/XCGccMakefileDependencies.m:78
Details:  Failed to load dependencies output contents from ``/Users/edelldj1/Code/SCSA/htdocs/externals/glTF/converter/COLLADA2GLTF/COLLADA2GLTF.build/Debug/collada2gltfConvert.build/Objects-normal/x86_64/COLLADA2GLTFWriter.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “COLLADA2GLTFWriter.d” couldn’t be opened because there is no such file." UserInfo=0x7fce8eeba910 {NSFilePath=/Users/edelldj1/Code/SCSA/htdocs/externals/glTF/converter/COLLADA2GLTF/COLLADA2GLTF.build/Debug/collada2gltfConvert.build/Objects-normal/x86_64/COLLADA2GLTFWriter.d, NSUnderlyingError=0x7fce8eef9340 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/edelldj1/Code/SCSA/htdocs/externals/glTF/converter/COLLADA2GLTF/COLLADA2GLTF.build/Debug/collada2gltfConvert.build/Objects-normal/x86_64/COLLADA2GLTFWriter.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, F) [F = <lambda at /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-3575/Xcode3Sources/XcodeIDE/Frameworks/DevToolsBase/pbxcore/SpecificationTypes/XCGccMakefileDependencies.m:168:73>]
Thread:   <NSThread: 0x7fce8ff23220>{name = (null), num = 22}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
In file included from /Users/edelldj1/Code/SCSA/htdocs/externals/glTF/converter/COLLADA2GLTF/GLTF/GLTFExtraDataHandler.cpp:11:
/Users/edelldj1/Code/SCSA/htdocs/externals/glTF/converter/COLLADA2GLTF/GLTF/GLTFExtraDataHandler.h:11:10: fatal error:
      'unordered_map' file not found
# include <unordered_map>

```
     ^
```

1 error generated.

**Comment by pjcozzi** [comment]
Replaced by new problems, lol, https://github.com/KhronosGroup/COLLADA2GLTF/issues/91, that will be fixed!
