### ISSUE TITLE
Can glTF handle all FBX content? Add more optional(!) node properties.

### ISSUE THREAD

**Issue by McNopper** [KhronosGroup/glTF#289]
I wonder, if the humanoid.fbx asset from the FBX SDK can be represented with glTF. If not, I strongly recommend to have more additional transformation properties - like the ones available in FBX - to have in a glTF node.

Also, I would like to see - beside Quaternions - to have the possibility to define the rotations just with euler angles e.g. RzRyRx.

**Comment by pjcozzi** [comment]
@McNopper @zellski OK to close this?

**Comment by McNopper** [comment]
A very old one :-) Sure.
