### ISSUE TITLE
How to support multi-animations in the one glTF file?

### ISSUE THREAD

**Issue by games** [KhronosGroup/glTF#298]
How to support multi-animations in the one glTF file?

example:
I have a monster model, and it have several actions, like attack, run, idle. so does the glTF support merge all animations into one file and can obtain them from name?

thanks

**Comment by borismus** [comment]
Multiple animations within a single glTF file is pretty important for any serious applications. Does the multiple animationClip style that @games proposes work already?

**Comment by pjcozzi** [comment]
@borismus glTF allows multiple animations in one glTF asset.  What exactly are you asking for?  Blending them so that, for example, a run and jump animation can be combined into a "running jump?"

**Comment by emadurandal** [comment]
May I also participate in the discussion?
I want to make a flashy action 3D game with WebGL, and I would like to use glTF for that purpose.
Both Animation state changing and animation blending are important using one glTF file.

In glTF 1.0, `animations` can have multiple `animation`s.
In my short experience so far, `animation` was defined for each part of the model in a glTF file.

```
"animations": {
    "animation_0": {
        "channels": [
            {
                "sampler": "animation_0_rotation_sampler",
                "target": {
                    "id": "Skeleton_torso_joint_1",
                    "path": "rotation"
                }
            }
        ],
        "parameters": {
            "TIME": "animAccessor_0",
            "rotation": "animAccessor_1"
        },
        "samplers": {
            "animation_0_rotation_sampler": {
                "input": "TIME",
                "interpolation": "LINEAR",
                "output": "rotation"
            }
        }
    },
    "animation_1": {
        "channels": [
            {
                "sampler": "animation_1_rotation_sampler",
                "target": {
                    "id": "Skeleton_torso_joint_2",
                    "path": "rotation"
                }
            }
        ],
        "parameters": {
            "TIME": "animAccessor_2",
            "rotation": "animAccessor_3"
        },
        "samplers": {
            "animation_1_rotation_sampler": {
                "input": "TIME",
                "interpolation": "LINEAR",
                "output": "rotation"
            }
        }
    },
```

First, in general (not limited to glTF), each part of the model usually has an individual timeline and keyframe.
What I'm interested in is whether `parameters` can have more than one `TIME` and related parameter(e.g. rotation) like this.

```
        "parameters": {
            "TIME0": "animAccessor_0", // for chest
            "TIME1": "animAccessor_1", // for neck
            "TIME2": "animAccessor_2", // for head
            "rotation0": "animAccessor_3" // for chest
            "rotation1": "animAccessor_4" // for neck
            "rotation2": "animAccessor_5" // for head
        },
```

If It's not allowed, We have to define an animation for each part of the model.
But, if It's allowed, We can cram movements of all parts of the model into one `animation`. Then, We can define `animation_0` as "Walk" and `animation_1` as "Run".

Actually,  Can `parameters` have more than one `TIME` and related parameter(e.g. rotation)? And Is there a tool that can output in such a form?

Or, to realize multiple animations in one glTF file, does it have to be extended (e.g. introducing a new concept such as AnimationClip element)?

I'm sorry to have become a long sentence. But, my friends and I are very curious about this topic.

**Comment by lexaknyazev** [comment]
@emadurandal 

Most of your points are addressed in the upcoming glTF 1.1:
https://github.com/lexaknyazev/glTF/tree/master-test/specification/1.1#animations

**Comment by kyasbal-1994** [comment]
As long as I see the spec glTF 1.0, I didn't find any documents helps library determine which animation should be played automatically.
Is that depends on implementation of libraries,right?  
But I wonder it should be specified with scene tag.

I guess this is one of confusing point about animation since we don't know when the animation can be started actually. (Most of libraries starts animation automatically and loops automatically I guess...)

**Comment by emadurandal** [comment]
@lexaknyazev Thank you. I'll check it!

**Comment by pjcozzi** [comment]
> As long as I see the spec glTF 1.0, I didn't find any documents helps library determine which animation should be played automatically.
That is depends on implementation of libraries,right?
But I wonder it should be specified with scene element.

Please join the discussion in #1137.
