### ISSUE TITLE
Hot to load a *.gltf to Three.js?

### ISSUE THREAD

**Issue by Hamabama** [KhronosGroup/glTF#326]
Hi guys! Thanks for your great job and sorry if it is not a proper place for asking such questions. I would like to try out gltf format models in Three.js but I can't find any tutorial step by step. Online or offline converters spit out a bunch of files or just a *.gltf but *.js. However in the examples of Three GLTF loaders they load a *.js file? How to get such format? I don't see any options for it in the converters. Thank you.

**Comment by pjcozzi** [comment]
@tparisi what is the latest here?  Is this still work-in-progress?

**Comment by tparisi** [comment]
The Three.js loader was a updated to the dev-9 format a while back. It's all merged into the trunk. There is one bug big with skinning-- basically not working correctly at all now-- which is on my list.

**Comment by pjcozzi** [comment]
OK to close this?

**Comment by tparisi** [comment]
Yes. Closed.
