### ISSUE TITLE
Skinned Mesh Props not loading

### ISSUE THREAD

**Issue by digitaledge** [KhronosGroup/glTF#330]
Actually I am trying to load skinned props for our Game Character in three.js.

Problem is that the Loader is able to load a Mesh thats bound and skinned to a whole Skeleton, but its actually not loading a Mesh thats bound only to a few of these bones.

As example if you want to load a Hat mesh thats only skinned to the head bones, the loader fails with errors. If you skinpaint weights to the full skeleton on this head, it loads fine (but breaks ofc).

Any idea how to solve this?  

Thanks

**Comment by tparisi** [comment]
@digitaledge I know it's been a while but if you can, please get me a test case for this. I'm working on this stuff now... finally :-)

**Comment by pjcozzi** [comment]
@digitaledge do you know if this is still an issue in the latest three.js glTF loader?  It now loads all glTF sample models correctly.

**Comment by pjcozzi** [comment]
Please submit an issue in the three.js repo if this is still an issue.
