### ISSUE TITLE
Converter from string to string

### ISSUE THREAD

**Issue by yarray** [KhronosGroup/glTF#336]
Hi,

Recently I'd like to integrate the collada-glTF converter to a web service (the data will be passed in/out as string). I tried to reuse the code from the converter but the facade class GLTFAsset seemed quite designated to read/write files. Intermediate file is an option but performance will be an issue. Also /dev/stdin is not quite acceptable since I have to deploy the application to a windows machine finally.

Could there be some easy API so one can convert from string to string? I think it will be quite useful for integrating the converter to other programs.

**Comment by pjcozzi** [comment]
Replaced by https://github.com/KhronosGroup/COLLADA2GLTF/issues/113
