### ISSUE TITLE
Shader optimization problem

### ISSUE THREAD

**Issue by chris-cooper** [KhronosGroup/glTF#338]
As per [this Cesium issue](https://github.com/AnalyticalGraphicsInc/cesium/pull/2299), the glTF shader generated from an exported Maya 'surface' shader is not optimal.  This results in the shader getting optimized by WebGL which causes one of the vertex attributes to be dropped.

Files can be found [here](https://github.com/AnalyticalGraphicsInc/cesium/tree/aa695c0722e3b60b01a4c8b5dbd9a6c1cc436598/Specs/Data/Models/test-shader-optimize)

**Comment by pjcozzi** [comment]
Potentially not a bug and OBE with glTF 2.0 PBR.
