### ISSUE TITLE
Trouble converting Agisoft PhotoScan model

### ISSUE THREAD

**Issue by chris-cooper** [KhronosGroup/glTF#339]
PhotoScan exports a valid collada model that can be viewed in meshlab.  The converted glTF model isn't viewable in Cesium or glTF-webgl-viewer.  I'll send through the model to @fabrobinet.

**Comment by pjcozzi** [comment]
@chris-cooper do you have an example model exported from PhotoScan?  If so, please send to @tfili.

**Comment by tfili** [comment]
Looking at the sample model PhotoScan doesn't seem to add an authoring tool so its impossible to detect if we need to invert transparency automatically.

**Comment by chris-cooper** [comment]
Thanks for having a look @tfili.  Fyi I did report the transparency issue to Agisoft so it's possible they may fix it at some stage.

**Comment by fabrobinet** [comment]
so for now, the work-around is to use the invert transparency option the converter.

**Comment by pjcozzi** [comment]
@fabrobinet any spec related changes recommended here?

**Comment by fabrobinet** [comment]
It's just that by convention the parameter was named `transparency` and we will name it `opacity`, so if we mention the conventions of naming yes it does impact the spec, but "slightly" as it is not really either core property or value change.

**Comment by fabrobinet** [comment]
Also, we need to be able to map `transparency` to `opacity` when using the `details` property see #361

**Comment by pjcozzi** [comment]
I _think_ it is OK to close this, please chime in if that is not the case.
