### ISSUE TITLE
Image elements in a profile_COMMON don't work

### ISSUE THREAD

**Issue by tfili** [KhronosGroup/glTF#340]
If an image is defined in the profile instead of in the library_images the image ends up in the gltf with a empty source.

**Comment by fabrobinet** [comment]
@tfili looking at collada spec only possible parent element of `<image>` is `<library_images>` so if such situation happened, that's probably an exporter issue.

**Comment by tfili** [comment]
@fabrobinet In the 1.5 spec this is the case. In 1.4.1 it can have a variety of parents including library_images, effect, profile_CG, profile_GLSL, profile_COMMON,
profile_GLES, technique (FX) (in profile_CG, profile_COMMON, profile_GLES,
profile_GLSL)

**Comment by fabrobinet** [comment]
Ah yes, my bad, I didn't assumed that changed. Sorry, I can't remember/find if you sent me a test file for this, if not, could you send over email ? thank you.

**Comment by mingweiLIU** [comment]
Hey, have you ever fixed this bug? or still need a test file for this case, since I have some files just in this form and it won't read the image, I may provide one.

**Comment by pjcozzi** [comment]
Replaced by https://github.com/KhronosGroup/COLLADA2GLTF/issues/114
