### ISSUE TITLE
Why isn't the json data written as binary data?

### ISSUE THREAD

**Issue by pwnedary** [KhronosGroup/glTF#348]
Is it not a bit counter-intuitive considering that your goal is to be simple and fast?

**Comment by fabrobinet** [comment]
Take a browser nowadays, all the JSON parsing is done for you. So it is simple AND fast. Also the big payload isn't in the JSON...  Yes, you could certainly load a big binary blob and parse it using typed array API to be fast but I wouldn't call that so "simple".

We actually considered another form of binary JSON can you remind me @pjcozzi ? but that's post v1.0.

**Comment by pwnedary** [comment]
Well, I'm programming in C/C++ so JSON is a big hassle. Guess this file format isn't for me. Sorry if I've bothered you.

I just think it's strange - a format for OpenGL, where native applications are more widespread.

**Comment by fabrobinet** [comment]
@pwnedary there are tons of C++ JSON library, not to mention that they are part of SDK if you use iOS (and probably Android too). But it is true that the first version of glTF is targeting more web and mobile that desktop.

**Comment by pjcozzi** [comment]
@fabrobinet for binary, we considered http://msgpack.org/.  @tfili and I are actually looking at this now.

**Comment by isral** [comment]
> 
> 
> @fabrobinet for binary, we considered http://msgpack.org/. @tfili and I are actually looking at this now.

Is it already implemented or already rejected?
I'm looking for pure binary gltf (no textual json) and I stumble to this issue.

**Comment by donmccurdy** [comment]
@isral glTF remains a JSON-based format today. If you need a good C loader, I would suggest [cgltf](https://github.com/jkuhlmann/cgltf). Or if you do prefer to avoid JSON entirely, you could reformat a `.gltf` file with MessagePack and deserialize the binary data in your application.

**Comment by emackey** [comment]
We've had good results from [tinygltf](https://github.com/syoyo/tinygltf) which is a header-only library for C++
