### ISSUE TITLE
Minify glTF JSON

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#35]
There should be a converter option (off by default) to minify the JSON created to reduce its size.

There are several JavaScript minifiers available, but given that we can't change the names of any of the JSON properties, we probably just need to remove whitespace, which we won't need a third-party minifier for.

**Comment by pjcozzi** [comment]
@kainino0x did we add this to COLLADA2JSON or did we revert it?

**Comment by kainino0x** [comment]
We reverted it because my fix didn't work correctly.

**Comment by pjcozzi** [comment]
Moving to gltf-pipeline so it is useful to all exporters/converters, see https://github.com/AnalyticalGraphicsInc/gltf-pipeline/issues/1.
