### ISSUE TITLE
COLLADA export from CityEngine doesn't render?

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#350]
Details here: https://groups.google.com/forum/#!searchin/cesium-dev/Avikesh/cesium-dev/pi20u3DWPTc/RIjgI6sBfEMJ

**Comment by fabrobinet** [comment]
Worked-around the issue with this PR (merged) https://github.com/KhronosGroup/glTF/pull/354/files.

The exporter who produced this model should probably not export RGB_ZERO opaqueMode - though it could acceptable for color, but for texture it is really not recommended, maybe that is not the intent and an exporter bug ?

The test model now looks now similar in my viewer than Preview, so closing this one.

**Comment by pjcozzi** [comment]
Awesome, thanks @fabrobinet.
