### ISSUE TITLE
Three.js loader skinning broken

### ISSUE THREAD

**Issue by tparisi** [KhronosGroup/glTF#356]
This is a result of the changes to get to dev-9 format. The animations break the geometry.

**Comment by amirebrahimi** [comment]
After doing some fixup in my local branch, I've tracked this down to a resource loading issue as well. Because inverseBindMatrices is a resource it is possible that it is not available at the time handleSkin is being called. Since I don't understand the overall architecture that much yet, I'm not sure how to delay handleSkin until after the inverseBindMatrices has loaded.

**Comment by amirebrahimi** [comment]
So, here was the workaround I came up with: https://github.com/amirebrahimi/glTF/commit/b0ee7b74d194da727c19878ca85e2dbfa6a304e3

There is likely a more elegant solution. I'm willing to clean this up and initiate a pull request if you like, however, I think the plan was to move all this over to the threejs repo anyway.

**Comment by tparisi** [comment]
@amirebrahimi  Please do the PR and I'll have a look. I was planning to do the move to Three.js later on this month so let's not wait.

**Comment by amirebrahimi** [comment]
Sure thing. Here you go: https://github.com/KhronosGroup/glTF/pull/394

**Comment by tparisi** [comment]
@tfili @pjcozzi guys I posted two models to sampleModels: brainsteam and monster. They are both still in the broken state where the animation data seems to be off. Can you test against Cesium in their current state, and also Tom please convert to 1.0 format when the converter is ready to go (DAEs are in there).

**Comment by pjcozzi** [comment]
Cesium doesn't render these either.  @tfili and I can look at this, but we need to focus on the material and quaternion changes first.

**Comment by tparisi** [comment]
no that's fine let's make those changes first. but then let's nail skinning soon after.

**Comment by pjcozzi** [comment]
Should be fixed in @cx20's new loader.
