### ISSUE TITLE
Minify GLSL

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#36]
To reduce asset size, the converter should have an option (off by default) to minify the generated GLSL.

Removing whitespace and comments is obvious (that is actually all my WebGL engine does now), but minification can be much more aggressive by renaming functions, variables, and even uniforms (and the glTF JSON) in the extreme case.

We can investigate some tools:
* https://code.google.com/p/glsl-unit/wiki/UsingTheCompiler ([online version](http://glslunit.appspot.com/compiler.html), [discussion](https://groups.google.com/forum/?fromgroups#!topic/webgl-dev-list/RkGgA0t9IUA))
* http://www.ctrl-alt-test.fr/?page_id=7 ([online version](http://ctrl-alt-test.fr/minifier/))
* https://github.com/chrisdickinson/glslmin
* Cesium script for removing whitespace and comments.  https://github.com/AnalyticalGraphicsInc/cesium/blob/b19/Tools/buildTasks/extractShaderComments.js

**Comment by zz85** [comment]
I came to this issue by chance, just wanted to add that there's an online/js version of glsl-optimizier if anyone's interested to try it. http://zz85.github.io/glsl-optimizer/

**Comment by pjcozzi** [comment]
Cool, thanks for sharing @zz85!

**Comment by pjcozzi** [comment]
Moving to gltf-pipeline so it is useful to all exporters/converters, see https://github.com/AnalyticalGraphicsInc/gltf-pipeline/issues/1.
