### ISSUE TITLE
Documentation for binary file

### ISSUE THREAD

**Issue by adius** [KhronosGroup/glTF#360]
Is there any documentation on the structure of the binary file.
I want to create it from mesh data, but have no idea where to get started.

**Comment by pjcozzi** [comment]
As long as byte alignment is correct (see #167), the binary file can be laid out any way the tool generating it wants.  In the glTF JSON, `bufferView`s point into sections of the binary data (and `accessor`s point into `bufferView`s) so this is what defines the layout, not the glTF spec itself.
