### ISSUE TITLE
Conversion issue

### ISSUE THREAD

**Issue by satishkashyap** [KhronosGroup/glTF#363]
Facing an error in conversion of a SketchUp Collada model to glTF. Have tried multiple options to convert a wind turbine but end up losing 2 blades of the turbine in the conversion. The rest of the structure is intact. Please suggest..

**Comment by RemiArnaud** [comment]
Hard to tell anything without the model. Could be a problem with sketchup exporter, could be a problem with glTF converter. 
Can you first check your model is correct to begin with. If you have access to a mac, double click on the dae to open the model in preview. On a PC you can use FBX preview to load/display .dae but it is not as reliable. 

I don't know if sketchup can import .dae. If it can, try importing the model in sketchup. More reliable are the openCollada import/export plig-ins for Max and Maya. Blender works most of the time but has issues with skeletons and animations - but you have none of that in sketchup so you should be fine.

**Comment by fabrobinet** [comment]
@satishkashyap  You need to provide a test-case to repro so that we can look at the issue. Thank you.

**Comment by satishkashyap** [comment]
Have emailed the files - input dae as well as output gltf. 

@RemiArnaud - To confirm that dae is working, have opened it in VisualStudio. The dae exported from SketchUp is fine. However, the converted file has only one blade (out of three). The rest of the turbine structure is in order...

**Comment by fabrobinet** [comment]
@satishkashyap thanks - how did you figure the glTF file was missing 2 blades ? by watching in a viewer, if so which one ? or by inspecting the glTF file ?

**Comment by satishkashyap** [comment]
@fabrobinet - I checked the glTF file in Cesium by placing it on the map..

**Comment by fabrobinet** [comment]
@pjcozzi this could be a dup of https://github.com/AnalyticalGraphicsInc/cesium/issues/1754 . What do you think ? can check with the model @satishkashyap sent to both of us ?

**Comment by satishkashyap** [comment]
@pjcozzi @fabrobinet & @RemiArnaud Find the final image rendered by Cesium..

![image](https://cloud.githubusercontent.com/assets/11258076/6435676/ee50a114-c0c8-11e4-9dbe-b9a90bee6a6c.png)

**Comment by pjcozzi** [comment]
This is a Cesium bug that we will have a fix for soon: https://github.com/AnalyticalGraphicsInc/cesium/issues/1754

@satishkashyap keep an eye on the above issue.
