### ISSUE TITLE
glTF and SRC

### ISSUE THREAD

**Issue by mlimper** [KhronosGroup/glTF#364]
Hi all,

maybe you have already heard about the SRC (Shape Resource Container) format, especially if you're involved in the X3D(OM) community.
It's something we have designed last year, partially deriving it from glTF, we also published a paper about that on Web3D 2014 (see project page: http://x3dom.org/src).

The paper provides a comparison between glTF and SRC, discussing the reasons for not taking the current state of glTF as-is.

**So, an interesting question is:**
Are there any chances the the changes proposed by SRC could, at some point, find their way into glTF?
It could be useful for us to refer to SRC as a subset of glTF, and it could also be useful if glTF would provide the benefits of SRC (like progressive streaming).

Thanks in advance.

Regards,
Max

P.S.: If you prefer discussion via email instead of the issue tracker, you can also write me to
max dot limper at igd dot fraunhofer dot de

P.P.S.: Just for completeness, there was another interesting paper at last Web3D which also proposed a format for streaming binary data (entitled Blast), and it also includes a brief discussion about glTF (http://dl.acm.org/citation.cfm?doid=2628588.2628599&CFID=626140191&CFTOKEN=41679963). So, it seems there's a need for streaming and efficient handling of binary data.

**Comment by MBARIMike** [comment]
These changes would help open up a whole range of applications. One example is fast isosurface renderings from atmospheric and oceanographic forecast models.

**Comment by mlimper** [comment]
FWIW, although not using SRC, this are demos illustrate the kind of streaming capabilities we are currently missing in glTF:
http://examples.x3dom.org/pop-pg13/happy.html
http://x3dom.org/pop/

**Comment by pjcozzi** [comment]
@mlimper sorry for long delay, we are interested in collaborating.  glTF supports extensions and perhaps it would make sense to see if we could define an extensive for progressive streaming.  We are currently focused on one for mesh compression, #398.  Let's do a call soon.

**Comment by mlimper** [comment]
Thanks - just send me an email if you have a free spot for a short call, should not take too much time.
We also would like to present the SRC extension at the glTF BOF at SIGGRAPH (although we don't have a confirmation yet for an official presentation), this could also be an opportunity to discuss this in person with everyone who is interested.

**Comment by pjcozzi** [comment]
* Binary glTF is being discussed in #400 
* External glTF references is being discussed in #37 
* Leaving this open as a reminder for an SRC extension for incremental loading and vertex shader decompression

**Comment by pjcozzi** [comment]
Closing now that we are collaborating on extensions. :+1:
