### ISSUE TITLE
Wrong types in techniquePassStates

### ISSUE THREAD

**Issue by MarcoHutter** [KhronosGroup/glTF#366]
techniquePassStates.properties.enable.items should be an enum:
https://github.com/KhronosGroup/glTF/blob/master/specification/techniquePassStates.schema.json#L11

techniquePassStates.properties.functions.properties.blendEquationSeparate.items should be an integer (instead of a number)
https://github.com/KhronosGroup/glTF/blob/master/specification/techniquePassStates.schema.json#L37

techniquePassStates.properties.functions.properties.blendFuncSeparate.items should be an integer (instead of a number)
https://github.com/KhronosGroup/glTF/blob/master/specification/techniquePassStates.schema.json#L48

**Comment by pjcozzi** [comment]
Thanks!  Fix coming in #367.

**Comment by pjcozzi** [comment]
Thanks again for the report.
