### ISSUE TITLE
JSON refer other JSON?

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#37]
In our quest to balance simplicity and flexibility, I'd like to open the discussion for if glTF JSON should be able to reference other JSON.  This would be useful for storing large node hierarchies across several files, where only a few of them may need to be loaded based on visibility, LOD, etc.  It would also be useful for sharing parts of the JSON, e.g., materials, among multiple assets, which can reduce overall bandwidth.

I'm happy to draft up some example JSON (probably after GDC).

My feeling on this is yes because of the above use cases and that it matches the flexibility with everything else in glTF - buffers, images, and shaders.

I'm interested in other thoughts...

**Comment by pjcozzi** [comment]
@mlimper let's use this issue to discuss your approach to this with SRC and how we could use it in glTF or an extension (it should probably be core spec though).

**Comment by mlimper** [comment]
Within SRC, there is a two-level addressing schema for meshes / mesh data and textures:

* A hash symbol is used to address a mesh or texture: http://foo.bar.myDataFile.src#myMesh
* A dot symbol is used to address a specific attribute of a mesh: http://foo.bar.myDataFile.src#myMesh.colors

(also see Figure 7 in the paper, for example: http://x3dom.org/src/files/Web3d2014_SRC.pdf)

This assumes that meshes and textures are first-class citizens of the SRC file, which share the same scope (and hence cannot have similar names). For the original idea of using SRC to externalize X3D Shape Data, this was sufficient - but this approach is probably not general enough for glTF, I suppose.

**Comment by pjcozzi** [comment]
Thanks @mlimper.  I will need to implement this in Cesium before I am comfortable suggesting it for the core glTF spec.  I'm not sure I can do that in time for the draft 1.0 spec, but we could propose it as an extension, and then put it in the 1.1 spec.

I agree that the SRC approach is not general enough, but I think it generalizes easy enough.  Here's an example (assuming an `external_glTF` extension):

**commonMaterials.gltf**

```javascript
{
    "materials": {
        "glass" : {
            // ...
        }
    }    
}
```

**model.gltf**

```javascript
{
    "extensions": {
        "external_glTF" : {
            "commonMaterials" : "commonMaterials.gltf"
        }
    },
    "meshes" : {
        "a-geometry" : {
            "primitives" : [{
                "material" : "commonMaterials#glass"
            }]
        }
    }
}
```

Basically, any referenced property name with an `#` identifies an object in an external glTF file.

Here's a more complicated example with multiple external files creating the classic diamond of death.

**commonShaders.gltf**

```javascript
{
    "shaders": {
        "commonShader": {
            // ...
        }
    }
}
```

**commonMaterials.gltf**

```javascript
{
    "extensions": {
        "external_glTF" : {
            "commonShaders" : "commonShaders.gltf"
        }
    },
    // Reference "commonShaders" somewhere
    "materials": {
        "glass" : {
            // ...
        }
    }    
}
```

**commonNodes.gltf**

```javascript
{
    "extensions": {
        "external_glTF" : {
            "commonShaders" : "commonShaders.gltf"
        }
    },
    // Reference "commonShaders" somewhere
    "nodes": {
        "arm": {
            // ...
        }
    }
}
```

**model.gltf**

```javascript
{
    "extensions": {
        "external_glTF" : {
            "commonMaterials" : "commonMaterials.gltf",
            "commonNodes" : "commonNodes.gltf"
        }
    },
    "meshes" : {
        "a-geometry" : {
            "primitives" : [{
                "material" : "commonMaterials#glass"
            }]
        }
    },
    "nodes" : {
       "left-arm": {
            "children": [
                "commonNodes#arm"
            ]
        }
    }
}
```

Engines would have to be smart about caching to avoid duplicate resource creation.  We could also impose restrictions - if we can justify them - like external glTF files can't reference more external glTF files, but this feel artificial.

It would also be nice to have an open-source tool that takes a set of glTF files and then optimizes them to reference common external glTF files, e.g., if all the models have the same material.

What do you think of the schema proposed above?

> A dot symbol is used to address a specific attribute of a mesh: http://foo.bar.myDataFile.src#myMesh.colors

What is this used for?

**Comment by RemiArnaud** [comment]
Although available in COLLADA - an intermediate representation format - and rarely correctly implemented, I would not recommend generic external references in glTF - a presentation format.

The reason is that it becomes very hard to reference unique instances. 
main.gltf could instance 2 forests from the same forest.gltf. forest.gltf instance the same tree several times.
you may end up with 4 trees for example, with 4 different paths to it:

forest1->tree1->tree
forest1->tree2->tree
forest2->tree1->tree
forest2->tree2->tree

the only way to differentiate between those 4 trees is to provide their full path. 
If the user click on a tree, you have to return the full path to that tree to the application to know which tree it is.

What happen if you want to move the last of those trees, and only that tree?

you can't.
moving the tree node will move all the trees.
moving the tree1 node, will move two trees
moving the forest2 node, will move two different trees

In a run-time / presentation format, I'd recommend using a 'flat' scene, where instances get a new node.
There are several ways to do this, for example limiting external references to leaves objects (not container objects). So you could not instance a forest, you'd have to instance trees. 

the collada2gltf tool could create such 'flat scenes' from COLLADA documents using external references.
PS : the openCOLLADA Maya exporter has been fixed to correctly export external references.

**Comment by pjcozzi** [comment]
@RemiArnaud I believe your point is a more general glTF discussion, so I created #401.  Please chime in and let's converge on an approach.

As for external glTF references, I am open to reducing their scope, but let's decide on #401 first.

**Comment by mlimper** [comment]
> A dot symbol is used to address a specific attribute of a mesh: http://foo.bar.myDataFile.src#myMesh.colors
> What is this used for?

In our paper, this was mentioned as a way to perform data compositing, for example by overriding the original vertex colors of a mesh when using it again in some other place. But this is very advanced, and we don't have an implementation that supports this feature right now.

**Comment by pjcozzi** [comment]
>> A dot symbol is used to address a specific attribute of a mesh: http://foo.bar.myDataFile.src#myMesh.colors
What is this used for?

> In our paper, this was mentioned as a way to perform data compositing, for example by overriding the original vertex colors of a mesh when using it again in some other place. But this is very advanced, and we don't have an implementation that supports this feature right now.

I suggest we save it for when have an implementation.

Do you have any other feedback on what I proposed here, e.g., restrictions to make the implementation simple, etc.?

**Comment by mlimper** [comment]
We have only implemented the hash delimiter, I am not aware of any implementation obstacles regarding that

**Comment by pjcozzi** [comment]
Requested in #837.

**Comment by donmccurdy** [comment]
Closing this issue for now – we're definitely still open to considering glTF files that reference other external glTF files, but that idea isn't well-defined right now. If community members have strong use cases for this and some idea of how it should work, proposals are welcome.

**Comment by coderofsalvation** [comment]
if glTF sticks to JSON then why not follow the standard of [JSON references](https://opis.io/json-schema/2.x/references.html) using `$ref` and `$recursiveRef`.
It basically acts as overlays, and allows decorating the glTF with dynamic data found elsewhere using lazy-loading e.g.
