### ISSUE TITLE
collada2gltf.exe converter problem [model is moving when navigating]

### ISSUE THREAD

**Issue by mones12** [KhronosGroup/glTF#370]
Hi,
I was trying to convert a dae file with the collada2gltf.exe latest Windows build and I'm having some weird problems. If I use the Cesium online converter my model is perfect (snapped to ground and not moving) but when I use the .exe the model his kind of floating in the air and when you navigate the model moves. I have thousand of dae files to convert so the online option is not really practical. 

Thank you very much.

**Comment by pjcozzi** [comment]
@mones12 if you have any more details and are able to provide a sample model, please submit a new issue to https://github.com/KhronosGroup/COLLADA2GLTF
