### ISSUE TITLE
collada2gltf.exe converter problem, creating translucent model, from opaque model.

### ISSUE THREAD

**Issue by ghost** [KhronosGroup/glTF#373]
Hello, 

I`m trying to convert collada file using collada2gltf.exe v 0.8, but output model is translucent when i open it by the Cesium.

Add link for the archive with model files and screenshoot : https://www.dropbox.com/s/i8f6mfybx4d4pd1/converter.zip?dl=0

**Comment by pjcozzi** [comment]
Replaced by https://github.com/KhronosGroup/COLLADA2GLTF/issues/115
