### ISSUE TITLE
no gltf output but bin json glsl

### ISSUE THREAD

**Issue by chiliblast** [KhronosGroup/glTF#374]
I am trying to use offline model converter COLLADA2GLTF
I convert my 3ds files to fbx using 3ds, them import to blender and export to dae. Online converter works fine, but when I use offline converter, it outputs following files:
*.bin
*.json
*0FS.glsl
*0VS.glsl
Why does not it outputs only gltf file. If I use*.json file in my projects, it gives error.
Also I donot have the option -e for COLLADA2GLTF
Thanks,

**Comment by pjcozzi** [comment]
Is this still an issue with the latest version of the converter?

**Comment by chiliblast** [comment]
Issue was solved in latest version. Thanks

**Comment by pjcozzi** [comment]
Great, thanks.
