### ISSUE TITLE
glTF nor updated?

### ISSUE THREAD

**Issue by chiliblast** [KhronosGroup/glTF#376]
I have just downloaded from https://github.com/KhronosGroup/glTF/wiki/Converter-builds
V0.8: SHA1: df4892809111a8c6dbff4fab6c386a24745d344e 

for Windows.

When I run, it says msvcp120.dll is missing. I downloaded it.

Now when I run .exe, application does run.

I cannot see -e in /help

Why its not updated?

**Comment by pjcozzi** [comment]
Is this still an issue?  Perhaps #383 is also of interest to you.
