### ISSUE TITLE
Updating threejs loader. What branch should I target?

### ISSUE THREAD

**Issue by mrdoob** [KhronosGroup/glTF#379]
Hey guys,

I did some changed to the threejs loader in the threejs repo that just got reverted with your last PR (https://github.com/mrdoob/three.js/pull/6459). I thought I should update this repo directly with my changes so it doesn't happen again. What branch should I target my PR to?

Thanks!

**Comment by tparisi** [comment]
Ricardo, I'll look into this along with the short list of other items you've been pinging me on. The latest changes *should* be in master on glTF but I need to verify this. Also, we were planning on removing the Three.js loader from the glTF repo and make the "official" one the one that is your examples. That will help reduce confusion. Please stay tuned I promise I will try to get to this before end of tomorrow. Today is a weird all day meeting day

**Comment by mrdoob** [comment]
Sounds good!

**Comment by pjcozzi** [comment]
Any update here?  People have been asking for this (#389).

**Comment by pjcozzi** [comment]
OBE given @cx20's new loaded.

**Comment by emackey** [comment]
@pjcozzi Correction, @cx20 wrote the test page, but @richtr contributed the new loader.

**Comment by pjcozzi** [comment]
Ah, yes, sorry for the mix up.
