### ISSUE TITLE
one .JSON file will call to load another JSON

### ISSUE THREAD

**Issue by bhoske** [KhronosGroup/glTF#380]
Hello,

I am trying implement to call multiple JSON file from single entry .JSON file.
Explanation to my query :
Main assembly have a reference of child part /subassembly.  And If we call to main assembly, it will internally call to refereed child part/subassembly. Same thing I am trying to get in GLTF viewer. 

Please can you guild me to achieve these. 

Thanks.

**Comment by pjcozzi** [comment]
The glTF spec does not support this, but it may in the future.  See #37.

In the meantime, you could, of course, use multiple glTF files or incrementally load the buffers/images, which tend to be the bulk of the data.
