### ISSUE TITLE
Add option to calculate tangent & biNormal vectors

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF#381]
Some COLLADA exporters lack the ability to export tangent & biNormal vectors (looking at you, Blender).  With position, normal, and UV map data available, the converter could calculate the missing vectors and add them to the glTF model.  Can a commandline flag or something be added to cause this to happen?

**Comment by pjcozzi** [comment]
This isn't a short-term priority, but could be useful.  This [Cesium code](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/GeometryPipeline.js#L1077) could be useful.

**Comment by emackey** [comment]
This was resolved a long time ago.
