### ISSUE TITLE
32 bit converter build

### ISSUE THREAD

**Issue by JerryS1** [KhronosGroup/glTF#383]
Is there a 32 bit windows converter build?

**Comment by dpisarenko** [comment]
If someone is willing and able to create a 32-bit Windows 7 binary for a small fee, here is the Elance project: https://www.elance.com/j/create-bit-windows-binary-of-project-khronosgroup-gltf/75553354/

**Comment by dpisarenko** [comment]
FYI: I've created a Win32 binary. You can download it at http://altruix.cc/sources/32-bit-windows-binary-of-the-khronosgroup-gltf-converter/ .

**Comment by pjcozzi** [comment]
Thanks @dpisarenko.
