### ISSUE TITLE
Incorrect texturing with multiple UV maps

### ISSUE THREAD

**Issue by orlade** [KhronosGroup/glTF#384]
I'm trying to import a KMZ into Cesium by first converting the DAE inside into glTF with COLLADA2GTF. However when I import the glTF mesh into Cesium, it doesn't seem to apply the texture correctly to the geometry (the location is deliberately incorrect):

![cesium](https://cloud.githubusercontent.com/assets/4531277/7559621/f6470afa-f7fc-11e4-9eb7-8cbaa2de8d8a.PNG)

My guess is that it's because the DAE has multiple UV maps and for some reason either COLLADA2GLTF or Cesium can't handle that.

[Here is the source file as a KMZ](https://dl.dropboxusercontent.com/u/1683524/svf-existing.kmz), which you can unzip to get the DAE and images.

Here is what it should look like (KMZ in Google Earth):

![earth](https://cloud.githubusercontent.com/assets/4531277/7559432/5e152994-f7fa-11e4-9abb-dafffcb4d66e.PNG)

However, here is what the DAE alone looks like in Autodesk FBX Review. The second image is the same model as the first, but flipped upside-down.

![fbx1](https://cloud.githubusercontent.com/assets/4531277/7559434/5e182342-f7fa-11e4-928c-d39430e3bd84.PNG)

![fbx2](https://cloud.githubusercontent.com/assets/4531277/7559433/5e159e4c-f7fa-11e4-9107-8efe28683601.PNG)

Do you know either a) if this is a problem with COLLADA2GLTF that can be fixed, or b) if it's a problem with either the COLLADA model or with Cesium, in which case is there an obvious attribute that I can fix?

**Comment by pjcozzi** [comment]
@orlade any updates?  To help find the problem, have you tried the troubleshooting section here - https://cesiumjs.org/2014/03/03/Cesium-3D-Models-Tutorial/

@tfili any thoughts on the multiple texture coordinates?

**Comment by orlade** [comment]
@pjcozzi I'm afraid not. It wasn't a very common failure mode, so we didn't manage to get to the bottom of it before the end of the project. You can close this if it doesn't seem like a glTF issue.

As for an update on the project(s), [I replied to the mailing list](https://groups.google.com/d/msg/cesium-dev/qJ4r-9mUaJg/yiE-4WfEBlcJ).

**Comment by pjcozzi** [comment]
Let's leave this open in case it is a converter but, thanks.

**Comment by pjcozzi** [comment]
Replaced by https://github.com/KhronosGroup/COLLADA2GLTF/issues/116
