### ISSUE TITLE
linux build

### ISSUE THREAD

**Issue by joeblew99** [KhronosGroup/glTF#387]
i noticed the linux build issue just got fixed.

any chance a linux binary can be released to make life a bit easier.

**Comment by pjcozzi** [comment]
@fabrobinet any chance you could make a build?  I don't have a Linux machine handy.

**Comment by fabrobinet** [comment]
No... sorry. I just have OS X.

**Comment by kaktus40** [comment]
Hello,in a previous version, I could compile the converter but now I have the following error:
CMake Error: your CXX compiler: "/usr/bin/c++" was not found.   Please set CMAKE_CXX_COMPILER to a valid compiler path or name.

How can I set   CMAKE_CXX_COMPILER to gcc compiler?

**Comment by pjcozzi** [comment]
@tfili I know you are building on Windows, but do you have any idea what could have changed here?  Anything related to COLLADA2GLTF or perhaps @kaktus40's system?

**Comment by tfili** [comment]
Nothing has changed in over a month when we fixed the Linux build. That error looks like a badly configured cmake.  Without a compiler all cmake apps should fail to build.

**Comment by kaktus40** [comment]
Hello I found the solution. On My mint distribution, I installed build-essential and libxml2-dev( sudo apt-get install build-essential libxml2-dev ) and now I can launch the make of converter.
With some warnings I could compile the converter.
If you want I can send you the generated builds  of collada2gltf, OpenCOLLADAValidator and test_o3dgc

**Comment by pjcozzi** [comment]
Once we reach 1.0, it would be great if you could send us a Linux build for [here](https://github.com/KhronosGroup/glTF/wiki/Converter-builds).
