### ISSUE TITLE
THREE.js support / v0.8

### ISSUE THREAD

**Issue by digitaledge** [KhronosGroup/glTF#389]
Im wondering if the three.js loader is still supported by this repo?
Since the v0.7 release (almost 1 year back) the loader doesnt support skinned meshes and animations and three.js demos are still loading an old v0.6 model.

**Comment by pjcozzi** [comment]
See #379.

CC #356.

**Comment by pjcozzi** [comment]
The latest version of the three.js loader by @cx20 works with all the sample models, including those with skins, see https://github.com/cx20/gltf-test
