### ISSUE TITLE
blank texture in outputed gltf

### ISSUE THREAD

**Issue by yaozhihang** [KhronosGroup/glTF#391]
Hi,

I'm currently trying to convert one collada model to glTF format on Windows 7 OS. The result of the online-converter looks fine. But the offline-converter gives a very bad result. 

The collada2gltTF offline-converter which I'am using was built based on the source code from the current master branch. 

Could you please have a look at this issue? My original collada file and two screenshots of the converted gltf models kann be downloaded via the following dropbox-link: 
https://dl.dropboxusercontent.com/u/69071139/BugReport.zip 

thanks very in advance 

Zhihang

**Comment by pjcozzi** [comment]
Replaced by https://github.com/KhronosGroup/COLLADA2GLTF/issues/117
