### ISSUE TITLE
How load glTF model in C++?

### ISSUE THREAD

**Issue by petr-stety-stetka** [KhronosGroup/glTF#393]
How can I load a glTF model in C++ (for OpenGL)?

**Comment by pjcozzi** [comment]
There are several open-source glTF loaders for JavaScript/WebGL listed in the bottom of the [README.md](https://github.com/KhronosGroup/glTF/blob/master/README.md) for this repo.  I haven't seen any C++/OpenGL implementations yet, but it should be straightforward given the open-source JavaScript ones.  Let us know if you write one and we'll be happy to spread the word.

**Comment by VincentSC** [comment]
https://github.com/Lugdunum3D/glTF2-loader/tree/dev
https://github.com/syoyo/tinygltfloader

**Comment by xelatihy** [comment]
https://github.com/xelatihy/yocto-gl

But note that gltf 2 is still in draft so all C++ loaders only either subset glTF or have not been fully updated to the spec.

**Comment by nmpribeiro** [comment]
Hi, I am able to reproduce:

tests/gltf/yocto-gl/yocto/yocto_gl.cpp:12625:53: error: ‘class std::unordered_map<ygl::material_type, int>’ has no member named ‘at’
     set_program_uniform(prog.prog, mtype_id, mtypes.at(type));
                                                     ^
CMakeFiles/yocto_gl.dir/build.make:62: recipe for target 'CMakeFiles/yocto_gl.dir/yocto/yocto_gl.cpp.o' failed
make[2]: *** [CMakeFiles/yocto_gl.dir/yocto/yocto_gl.cpp.o] Error 1
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/yocto_gl.dir/all' failed
make[1]: *** [CMakeFiles/yocto_gl.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

OS: Linux Ubuntu 16.04
Compiler (I think...): gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)
