### ISSUE TITLE
How to calculate joint positions?

### ISSUE THREAD

**Issue by jephir** [KhronosGroup/glTF#403]
I'm trying to implement glTF skinning in my engine. The [Cesium_Man](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Apps/SampleData/models/CesiumMan) test model that I'm using is not displaying correctly, however I'm not sure if it's an error in my engine, or me not understanding how to calculate the joint positions.

![cman3](https://cloud.githubusercontent.com/assets/577585/9526431/49852bfc-4cb7-11e5-840d-4c055d5f2e99.PNG)

If I set all the rotations to the identity quaternion, it appears as below. My guess is that I'm doing something wrong with the rotations.
![cman2](https://cloud.githubusercontent.com/assets/577585/9526451/6271704e-4cb7-11e5-8ce3-363b41751b27.PNG)

I'm calculating the positions by starting at the root node for the skeleton and accumulating the transformations for each child:

``` go
type Joint interface {
    IsJointNamed(ID) bool
    ChildJoints() []Joint
    Transform(parent *f64.Mat4) f64.Mat4
}

type Skeleton struct {
    Name ID
    Root Joint
}

type JointInfo struct {
    Name            ID
    Transform       f64.Mat4
    ParentTransform *f64.Mat4
}

func (s Skeleton) JointInfo(jointName ID) *JointInfo {
    parent := mat4.Identity()
    return s.jointInfo(jointName, s.Root, &parent)
}

func (s Skeleton) jointInfo(jointName ID, joint Joint, parent *f64.Mat4) *JointInfo {
    t := joint.Transform(parent)
    if joint.IsJointNamed(jointName) {
        return &JointInfo{
            Name:            jointName,
            Transform:       t,
            ParentTransform: parent,
        }
    }

    for _, child := range joint.ChildJoints() {
        if info := s.jointInfo(jointName, child, &t); info != nil {
            return info
        }
    }

    return nil
}
```

``` go
func (n *Node) Transform(parent *f64.Mat4) f64.Mat4 {
    if n.Matrix != nil {
        return mat4.Mul(parent, n.Matrix)
    }
    s := mat4.Scale(n.Scale)
    q := quat.Normalize(n.Rotation) // GLTF quaternions might not be normalized
    r := mat4.FromQuat(&q)
    t := mat4.Translate(n.Translation)
    return mat4.Concat(parent, &s, &r, &t)
}
```

Any ideas for troubleshooting would be greatly appreciated!

**Comment by pjcozzi** [comment]
Have a look at the implementation in Cesium: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Model.js#L2526

> I'm trying to implement glTF skinning in my engine.

Cool, what engine are you working on?

**Comment by pjcozzi** [comment]
The new glTF Tutorial may also be useful: https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/README.md#gltf-tutorial
