### ISSUE TITLE
glTF 0.8 to 1.0 Guide

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#406]
To help 0.8 users upgrade.

I can write it.

**Comment by pjcozzi** [comment]
Notes in progress (CC @tfili, https://github.com/AnalyticalGraphicsInc/cesium/issues/3034)

* `mesh.primitive.primitive` -> `mesh.primitive.mode`
* `mesh.primitive.indices` are now optional
* `asset.profile` (string) to `asset.profile` (object) with `api` and `version` string properties
* `allExtensions` -> `extensionsUsed`
* Extensions: `CESIUM_binary_glTF` -> `KHR_binary_glTF`

**Comment by pjcozzi** [comment]
@tfili as of the changes we've made so far for 1.0 in COLLADA2GLTF and Cesium, is there anything missing above?

**Comment by tfili** [comment]
@pjcozzi I think that is everything.

**Comment by pjcozzi** [comment]
@tfili is there anything else in the [dev-0.9](https://github.com/KhronosGroup/glTF/compare/dev-0.9) branch that you want to merge into dev-1.0?  Let me know when we can delete dev-0.9.

**Comment by pjcozzi** [comment]
Added the guide to the wiki: https://github.com/KhronosGroup/glTF/wiki/glTF-0.8-to-1.0-Guide

**Comment by pjcozzi** [comment]
@tfili last call for anything in the dev-0.9 branch - do you need anything before I delete it?

**Comment by tfili** [comment]
There are a bunch of string -> constant changes. Not a big deal. The only other thing is quaternion stuff which I've already implemented.
