### ISSUE TITLE
Perspective camera schema needs xfov; also yfov says radians but s/b degrees

### ISSUE THREAD

**Issue by tparisi** [KhronosGroup/glTF#407]
xfov is missing from the schema. This is the horizontal field of view.

The yfov description says radians but we are using degrees. At least, the COLLADA converter is using degrees and so is the Three.js loader. I think degrees is fine.

**Comment by pjcozzi** [comment]
xfov is generally computed from yfov and aspect ratio.  For example, see [Matrix4.computePerspectiveFieldOfView](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/Matrix4.js#L640).

Storing both fovs is redundant and creates the possibility of inconsistency.  I suggest we do not add xfov.

I also suggest we update the converter to output radians since that is closer to GL, e.g. GLSL math functions use radians, not degrees.

**Comment by tparisi** [comment]
Do you have the ability to update the converter? If so we can tackle this issue. Right now I have sample content like the Duck that uses xfov instead of yfov. 

And yes we can change the fov to radians if you are able to update the converter and re-convert the models.

**Comment by RemiArnaud** [comment]
I don't care if we use radians or degrees for angle measurement, but can you make sure it is consistent. So that all angles are in the same unit in glTF please. 

-- Rémi

**Comment by pjcozzi** [comment]
@tfili can update the converter and models.

@RemiArnaud yes, of course, it will be consistent.

Leaving this open and labeled as `converter` for 1.0.

**Comment by tparisi** [comment]
Does anyone have a copy of the Virtual City model Fab and I were using? I'd
like that converted for testing, too, please.

Also, when you update the converter is there a downloadable build ready for
Mac OS? I break into a cold sweat when I need to rebuild the converter on
Mac with CMAKE etc..


On Wed, Sep 16, 2015 at 11:08 AM, Patrick Cozzi <notifications@github.com>
wrote:

> @tfili <https://github.com/tfili> can update the converter and models.
>
> @RemiArnaud <https://github.com/RemiArnaud> yes, of course, it will be
> consistent.
>
> Leaving this open and labeled as converter for 1.0.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KhronosGroup/glTF/issues/407#issuecomment-140824511>.
>



-- 


Tony Parisi                             tparisi@gmail.com
Founder, Third Eye                http://www.thirdeye.gl/
Follow me on Twitter!             http://twitter.com/auradeluxe
Read my blog at                     http://www.tonyparisi.com/
Learn WebGL                         http://learningwebgl.com/
Mobile                                    415.902.8002
Skype                                     auradeluxe

Read my books!
*Learning Virtual Reality*
http://www.amazon.com/Learning-Virtual-Reality-Experiences-Applications/dp/1491922834


*Programming 3D Applications in HTML5 and
WebGLhttp://www.amazon.com/Programming-Applications-HTML5-WebGL-Visualization/dp/1449362966
<http://www.amazon.com/Programming-Applications-HTML5-WebGL-Visualization/dp/1449362966>WebGL,
Up and Running*
http://www.amazon.com/dp/144932357X

**Comment by pjcozzi** [comment]
I don't have that model.  @tfili is master of the build at this point.  He can chime in.

**Comment by tparisi** [comment]
@tfili I'll add that model to the repo.... stay tuned.

**Comment by tparisi** [comment]
@tfili done. Note the README, this model is *not* for redistribution.

**Comment by tfili** [comment]
Right now the converter just outputs the COLLADA camera properties directly so you end up with 5 different types(xfov, yfov, xfov & yfov, xfov & ratio, yfov & ratio). I find this a little weird. I think we should probably convert them all to be yfov & aspect ratio and use radians.

The only issue I see is that a camera providing a single xfov or yfov are suppose to calculate to aspect ratio from the current viewport. Not sure what to do here.

@tparisi I've never built on Mac. Give it a try and if you have problems I can try and help.

**Comment by tparisi** [comment]
@tfili  what's the issue about aspect ratio? When you say you're not sure what to do what does that mean? If you supply a yfov and aspect ratio, the runtime can calculate xfov and we're all set.

**Comment by tfili** [comment]
@tparisi I know that part. However if you just provide a yfov, the collada spec says to use the application's viewport to get the aspect ratio. We don't have a 3d application to get that from.

**Comment by tparisi** [comment]
@tfili so are you saying that some COLLADA cameras come only with a yfov? I say just pass that through and then let the application do it at runtime using the same rule i.e. calculate the aspect ratio from the actual window aspect ratio. I don't think it should be the converter's job to figure it out. @pjcozzi thoughts?

**Comment by RemiArnaud** [comment]
I think not.

the xfov and yfov of the camera (or one of those + aspect ration) is needed to calculate the window size, not the other way around. Note that pixels are not necessary square, and depending on the display used, the window sizes will be different. Its not uncommon for a window to resize in both X and Y dimension automatically with user input.
If the camera is used to create a texture, you’d also need both xfov and aspect ratio.

however the application can decide to enable the user to update the aspect ratio, if it let the user change the window X and Y dimensions separate

— Remi

**Comment by pjcozzi** [comment]
We don't use this in Cesium, but I expect it would work like this:
* fovY is required
* Aspect ratio is optional

If aspect ratio is not provided, use the aspect ratio of the canvas (which the runtime has access to).

**Comment by tfili** [comment]
What about when only xfov is provided? I can't compute yfov without anything else. Has anyone seen this case? Can we just ignore it in the converter if it's really rare?

**Comment by tparisi** [comment]
Maybe produce a warning in the converter? Does this come up with the models in the current repo? Or Patrick's tests? Or the City I just uploaded?

**Comment by pjcozzi** [comment]
I agree with @tparisi; a warning is fine.  We don't want to have COLLADA (interchange) spill over into the glTF spec (runtime).

**Comment by RemiArnaud** [comment]
I think it defaults to 1

-- Rémi

**Comment by tparisi** [comment]
My Three.js loader code defaults to 1.

**Comment by pjcozzi** [comment]
Updated the schema in `spec-1.0` in 96efff585d2f028e19e1b0e45931b5bbeb8afad6.

@tfili is the converter update?  If so, we can close this.

**Comment by tfili** [comment]
Converter is updated in `dev-1.0` branch.

**Comment by pjcozzi** [comment]
:+1:
