### ISSUE TITLE
Directional and Spot lights need a direction vector

### ISSUE THREAD

**Issue by tparisi** [KhronosGroup/glTF#409]
If we're going to have lights at all-- which I think we should-- then we need a more complete spec for these two light types. They need a direction vector.

**Comment by pjcozzi** [comment]
Related to #93.

**Comment by pjcozzi** [comment]
@tparisi close as duplicate with #424 if you agree?

**Comment by tparisi** [comment]
Closing, moved to common materials extension. Duplicate of #424
