### ISSUE TITLE
COLLADA2GLTF doesn't build with rapidjson 1.0.2

### ISSUE THREAD

**Issue by reneengelhard** [KhronosGroup/glTF#417]
Hi,

we in Debian just upgraded our rapidjson package to the 1.0.2 release they released in spring. Because of the following only to experimental, though :)

I should note that in our collada2gltf packaging we fixed the build to use everything from the system, including rapidjson. (see http://anonscm.debian.org/cgit/pkg-multimedia/collada2gltf.git/tree/debian/patches/system-rapidjson.diff)

Unfortunately, the (already deprecated in 0.11/0.12 git) FileStream class/filestream.h got removed completely, so the build of COLLADA2GLTF with rapidjson 1.0.2 fails:

`
[  2%] Building CXX object CMakeFiles/collada2gltfConvert.dir/COLLADA2GLTFWriter.cpp.o
/usr/bin/c++   -DLIBXML_STATIC_FOR_DLL -DSTATIC_COLLADA2GLTF -DUSE_LIBPNG -DUSE_OPEN3DGC -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -std=c++11 -I/home/rene/tmp/collada2gltf-20140924 -I/home/rene/tmp/collada2gltf-20140924/GLTF -I/home/rene/tmp/collada2gltf-20140924/JSON -I/home/rene/tmp/collada2gltf-20140924/shaders -I/home/rene/tmp/collada2gltf-20140924/helpers -I/home/rene/tmp/collada2gltf-20140924/convert -I/home/rene/tmp/collada2gltf-20140924/assetModifiers -I/usr/include/rapidjson -I/usr/include/opencollada/COLLADAFramework -I/usr/include/opencollada/COLLADABaseUtils -I/usr/include/opencollada/COLLADASaxFrameworkLoader -I/usr/include/opencollada/GeneratedSaxParser -I/home/rene/tmp/collada2gltf-20140924/extensions/o3dgc-compression -I/usr/include/o3dgc    -fPIC -o CMakeFiles/collada2gltfConvert.dir/COLLADA2GLTFWriter.cpp.o -c /home/rene/tmp/collada2gltf-20140924/COLLADA2GLTFWriter.cpp
In file included from /home/rene/tmp/collada2gltf-20140924/COLLADA2GLTFWriter.h:30:0,
                 from /home/rene/tmp/collada2gltf-20140924/COLLADA2GLTFWriter.cpp:28:
/home/rene/tmp/collada2gltf-20140924/GLTF/GLTF.h:55:24: fatal error: filestream.h: No such file or directory
compilation terminated.
CMakeFiles/collada2gltfConvert.dir/build.make:65: recipe for target 'CMakeFiles/collada2gltfConvert.dir/COLLADA2GLTFWriter.cpp.o' failed
make[3]: *** [CMakeFiles/collada2gltfConvert.dir/COLLADA2GLTFWriter.cpp.o] Error 1
make[3]: Leaving directory '/home/rene/tmp/collada2gltf-20140924/obj-x86_64-linux-gnu'
CMakeFiles/Makefile2:70: recipe for target 'CMakeFiles/collada2gltfConvert.dir/all' failed
make[2]: *** [CMakeFiles/collada2gltfConvert.dir/all] Error 2
make[2]: Leaving directory '/home/rene/tmp/collada2gltf-20140924/obj-x86_64-linux-gnu'
Makefile:86: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/rene/tmp/collada2gltf-20140924/obj-x86_64-linux-gnu'
`

I think you want to use FileWriteStream/filewritestream.h now?

**Comment by pjcozzi** [comment]
Thanks for the report, @reneengelhard.  We are working on upgrading COLLADA2GLTF for the final glTF 1.0 spec.  We can look at upgrading RapidJSON afterward...sounds like COLLADA2GLTF is quite out of date.

**Comment by OlafvdSpek** [comment]
Any updates?

**Comment by pjcozzi** [comment]
No updates, but the branch to watch is https://github.com/KhronosGroup/COLLADA2GLTF/compare/master...lasalvavida:converter1.1

**Comment by pjcozzi** [comment]
@OlafvdSpek if this branch - https://github.com/KhronosGroup/COLLADA2GLTF/tree/2.0 - still has an issue, can you please submit an issue to https://github.com/KhronosGroup/COLLADA2GLTF/issues?
