### ISSUE TITLE
Remove converter directory

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#420]
Since we're going to have a lot more eyes on this repo after glTF 1.0, we should tidy it up a bit.

Can we move `converter/COLLADA2GLTF` to `COLLADA2GLTF` and then remove the empty `converter` directory?

@tfili is this hard?  I think the only potential issue is submodules and updating any links in the README.md and on the wiki.

**Comment by tfili** [comment]
@pjcozzi Checkout the pull request and make sure it works. It was pretty easy to do.

**Comment by tfili** [comment]
Fixed in dev-1.0 in #423.

**Comment by pjcozzi** [comment]
Leaving this open just as a reminder:
* [ ] Update wiki paths from `converter/COLLADA2GLTF` to `COLLADA2GLTF` when we merge spec-1.0.

**Comment by pjcozzi** [comment]
I did this as part of wiki cleanup.
