### ISSUE TITLE
Draft 1.0 spec feedback

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#430]
* [x] Let's explicitly say "dictionary property" when the spec first introduces a new top-level property, e.g.,:
   * "All buffers are stored in the assets buffers property."
   * "All accessors are stored in the asset's accessors property."
   * "Shader source files are stored in the asset's shaders property"
   * "All textures are stored in the asset's textures property"
   * "Images referred to by textures are stored in the images property of the asset."
   * "Samplers are stored in the samplers property of the asset"
   * "Cameras are stored in the asset's camera property"
   * "All animations are stored in the animations property of the asset."
   * "Materials are stored in the assets materials property"
   * "All skins are stored in the skins property of the asset"
* [x] "Todo:conformance - what if author supplies both matrix and TRS? Which wins? Undefined?"
   * The schema allows either a matrix or any combination of TRS properties, but not both.
* [x] "glTF uses a right-handed coordinate system with Y up and positive Z pointing out of the screen."
   * As discussed offline, this should be something like "glTF uses a right-handed coordinate system, that is, the cross product of x and y yields z.  glTF also defines the y axis as up."
* [x] "All angles are in radians unless otherwise specified."
   * Remove "unless otherwise specified"
* [x] "A buffer is data stored as a binary blob in a file."
   * Remove "in a file" since it may be a data uri.
* [x] "Buffer data is little endian."
   * Perhaps say this at the start of that section.
* [x] "The accessor specifies a component type (e.g. FLOAT) and a data type (e.g. VEC3), which when combined define the complete data type for each array"
   * "each array" should be "each array element" I believe.
* [x] "Primitives correspond to the data required for GL drawElements calls."
   * Or drawArrays.  Perhaps say "GL draw calls."
* [x] "Each primitive also specifies a material and a primitive type that coresponds to the GL primitive type (e.g. triangle set)"
   * "triangle set" -> "triangles" or "triangle list."  Triangle set is not a common GL term.
* [x] Did you update the rotation to quaternions for the Joint Hierarchy example?
* [x] "Render States" JSON example - fix the whitespace.
* [x] "Cameras define viewport projections"
   * This is an awkard definition.  Using GL terms, the viewport transform maps NDC to window coordinates.  Really, the glTF camera defines the projection matrix that transforms from view to clip coordinates.
* [x] "The following example defines a perspective camera with supplied values for Y field of view (in degrees)"
   * Use radians.
* [x] "The value in count must be less than or equal to number of entries in the shortest parameters value."
   * `count` was [removed](https://github.com/KhronosGroup/glTF/commit/6ed67481119b6d62ddb76341f52ee7f90397441a#diff-f302b887ff48fd51567790edef47402d).  All parameters must all have the same number of elements.
* [x] `"profile": "WebGL 1.0.2"`
   * This is an old example, see https://github.com/KhronosGroup/glTF/blob/spec-1.0/specification/schema/examples/asset.json
* [x] "Todo: Patrick what do we say about profiles, if anything?."
   * I think nothing since we only have one at this point.
* [x] "Binary Types Reference"
   * What exactly do you think this section needs to cover?  I think we could just skip it since we cover the binary layout in the "Accessor Attribute Size" and "BufferView and Accessor Byte Alignment" sections.
* [x] TODO.md
   * I checked this file out.  We should integrate some of the ""Design Principles" section and the note on camel case, but we don't need anything else.

**Comment by pjcozzi** [comment]
@tparisi can you please update the above task list to reflect your latest spec progress?

**Comment by pjcozzi** [comment]
@tparisi any update here?

**Comment by tparisi** [comment]
@pjcozzi fixed everything checked. For the unchecked items:

Joint Hierarchy - send me some reasonable data I can't make that up.
"Render States" whitespace - what's the issue? not seeing it. If you know, please just fix it.
Todo: please make changes as you see appropriate... I don't have a feel for what's good.
