### ISSUE TITLE
Skinning geometry with multiple primitives

### ISSUE THREAD

**Issue by tfili** [KhronosGroup/glTF#442]
If you have a node that has skinning, it references a geometry that can have multiple primitives. Are they all required to support skinning?

I don't think this is unreasonable and skinning is hard enough why leave this open to making more difficult.

**Comment by pjcozzi** [comment]
Agreed, for the case when a node has skinning, I added:

> all `primitives` in the referenced `meshes` contain `JOINT` and `WEIGHT` attributes and the referenced `material`/`technique` from each `primitive` has parameters with `JOINT` and `WEIGHT` semantics.

709025a88b8dda8c50f8157d5f23928aa8cb2277
