### ISSUE TITLE
Build of COLLADA2GLTF for glTF 1.0 and KHR_materials_common

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#443]
https://github.com/KhronosGroup/glTF/wiki/Converter-builds

**Comment by pjcozzi** [comment]
Let's not document the command-line argument for KHR_materials_common until we are done with the extension spec.

**Comment by tfili** [comment]
Removed option from help text in `dev-1.0` at a7a0d66f6de8851d27cdb9392386da8b87eaf897

**Comment by pjcozzi** [comment]
The Windows/Linux/Mac build is here: https://github.com/KhronosGroup/glTF/releases/tag/v1.0-draft
