### ISSUE TITLE
glTF Reference implementation?

### ISSUE THREAD

**Issue by pbeck** [KhronosGroup/glTF#445]
Will Khronos provide, or is there talk about doing a reference glTF reader lib implementation in native GL or WebGL, once it hits 1.0? 

There's work going on for three.js, a block for Cinder (https://github.com/jhurlbut/Cinder-glTF) and Cesium, but not all of them work, and they can't easily be used as libraries.

I'd be glad to contribute to such a project but I'm not sure my programming skills are strong enough to start :)

**Comment by pjcozzi** [comment]
Thanks for bringing Cinder to our attention, cool!

All of the known loaders are here: https://github.com/KhronosGroup/glTF/blob/master/README.md

We are really interested in an open-source barebones WebGL (or OpenGL) loader.  If you develop it, we are happy to help promote it.

**Comment by tparisi** [comment]
The Three.js loader is based on an underlying parsing library written by
Fabrice... is that what we're talking about? Kind of like SAX parser, it
calls callbacks on recognizing entities.


On Fri, Oct 16, 2015 at 9:12 AM, Patrick Cozzi <notifications@github.com>
wrote:

> Thanks for bringing Cinder to our attention, cool!
>
> All of the known loaders are here:
> https://github.com/KhronosGroup/glTF/blob/master/README.md
>
> We are really interested in an open-source barebones WebGL (or OpenGL)
> loader. If you develop it, we are happy to help promote it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KhronosGroup/glTF/issues/445#issuecomment-148757579>.
>



-- 


Tony Parisi                             tparisi@gmail.com
Follow me on Twitter!             http://twitter.com/auradeluxe
Read my blog at                     http://www.tonyparisi.com/
Learn WebGL                         http://learningwebgl.com/
Mobile                                    415.902.8002
Skype                                     auradeluxe

Read my books!
*Learning Virtual Reality*
http://www.amazon.com/Learning-Virtual-Reality-Experiences-Applications/dp/1491922834


*Programming 3D Applications in HTML5 and
WebGLhttp://www.amazon.com/Programming-Applications-HTML5-WebGL-Visualization/dp/1449362966
<http://www.amazon.com/Programming-Applications-HTML5-WebGL-Visualization/dp/1449362966>WebGL,
Up and Running*
http://www.amazon.com/dp/144932357X

**Comment by pbeck** [comment]
Ideally I was thinking of a C++ library bundled with a sample SDL-application for reading and displaying glTF support – that would also make a good starting point for many cross platform projects. I think glTF will be great for many mobile projects, and since WebGL support and performance is not yet uniform across devices getting good native libs are important.

**Comment by pjcozzi** [comment]
A C++ library would be awesome, go for it!

**Comment by tparisi** [comment]
Yes that would be fantastic! Godspeed;

**Comment by vinjn** [comment]
How about a glTF loader for assimp?
1. We can leverage common utils and the existent mesh / animation structure from assimp.
2. All the users of assimp will have glTF support with zero efforts.

**Comment by tparisi** [comment]
An exporter out of assimp would be even more useful...

**Comment by pjcozzi** [comment]
+1 on assimp support, see #51.

**Comment by pjcozzi** [comment]
Let's move this discussion to #456.
