### ISSUE TITLE
collada2gltf 1.0: converting dae that has units in centimeters

### ISSUE THREAD

**Issue by toloudis** [KhronosGroup/glTF#460]
I have a DAE that has a trivial animation (a few simple meshes separated in space, 2 keys, doing a simple translate and rotate) and the geometry comes through with apparently bad transforms.  If I change the line
 `<unit name="centimeter" meter="0.01"/>`
to
`<unit name="meter" meter="1.0"/>`
and move my camera appropriately, 
the conversion looks perfectly good.

Since there is no stock viewer for 1.0 yet, I am not sure if it's my viewer or the conversion that is bad.  The DAE looks correct in any viewer I try.

**Comment by pjcozzi** [comment]
Thanks for the report, @toloudis.  I believe COLLADA2GLTF is supposed to handle the unit conversion.  @tfili may have some ideas.

Also on November 2, you'll be able to drag and drop glTF 1.0 here for testing: http://cesiumjs.org/convertmodel.html

Also, what are you developing using glTF?

**Comment by tfili** [comment]
This scaling is definitely handled in the converter and it looks correct. Can you send us an example model that is showing the issue?

**Comment by toloudis** [comment]
@tfili, I just sent a test DAE to you by email.

**Comment by tfili** [comment]
It definitely looks like a bug in the converter. I'd have to look more at it. Is it OK if I attach the model to this bug, so I can make sure I have it when I get a chance to look at this?

**Comment by toloudis** [comment]
Yes, that's ok.

**Comment by tfili** [comment]
Thanks @toloudis.

Attached is the model. Just remove the `.txt` extension.

[test.dae.txt](https://github.com/KhronosGroup/glTF/files/18830/test.dae.txt)

**Comment by pjcozzi** [comment]
Replaced by https://github.com/KhronosGroup/COLLADA2GLTF/issues/118
