### ISSUE TITLE
Make inverseBindMatrices optional

### ISSUE THREAD

**Issue by ParticlePeter** [KhronosGroup/glTF#461]
In case of DualQuaternion inverseBindDQs are required (Matrix2x4) and can be supplied via extension.
A mesh can be exported with inverseBindMatrices/DQs pre-applied, hence neither of the two would be required in the glTf file. In both cases inverseBindMatrices entry is redundant.

**Comment by pjcozzi** [comment]
Thanks for the input, @ParticlePeter!  Just so I'm clear, even without dual quaternion skinning, inverse bind matrices may be pre-applied so they could be optional always?

**Comment by ParticlePeter** [comment]
Yes, the inverseBindMatrices can (and should for efficiency reasons) be applied to the mesh only once (on the CPU). The resulting mesh would be the bindMesh, applying skeleton/bone transforms to this mesh results in the expected skin animation.

**Comment by pjcozzi** [comment]
@ParticlePeter I updated the spec in the `1.0.1` branch in 5cf9a23269d4b5ed35c46c77017f92d31adc0f11.  Can you please review?

Also, can you confirm that
```
[joint-matrix] = [node-to-root^-1][joint-to-root][inverse-bind][bind-shape]
```
just becomes
```
[joint-matrix] = [node-to-root^-1][joint-to-root][bind-shape]
```
from [this code](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Model.js#L2975-L2986):
```javascript
           for (var m = 0; m < inverseBindMatricesLength; ++m) {
                // [joint-matrix] = [node-to-root^-1][joint-to-root][inverse-bind][bind-shape]
                if (!defined(computedJointMatrices[m])) {
                    computedJointMatrices[m] = new Matrix4();
                }
                computedJointMatrices[m] = Matrix4.multiplyTransformation(scratchObjectSpace, joints[m].transformToRoot, computedJointMatrices[m]);
                computedJointMatrices[m] = Matrix4.multiplyTransformation(computedJointMatrices[m], inverseBindMatrices[m], computedJointMatrices[m]);
                if (defined(bindShapeMatrix)) {
                    // Optimization for when bind shape matrix is the identity.
                    computedJointMatrices[m] = Matrix4.multiplyTransformation(computedJointMatrices[m], bindShapeMatrix, computedJointMatrices[m]);
                }
            }
```

**Comment by ParticlePeter** [comment]
I am not a js guy, and unfortunately not so deep in gltf as I wanted. This line doesn't look right to me, but I might be mistaken:
`computedJointMatrices[m] = Matrix4.multiplyTransformation(computedJointMatrices[m], inverseBindMatrices[m], computedJointMatrices[m]);`
I am not sure what in your case would be the matrix multiplication order but the inverseBindMatrices[m] are supposed to be the first things with which vertices are multiplied. So to my understanding it should be:
`computedJointMatrices[m] = Matrix4.multiplyTransformation(computedJointMatrices[m], computedJointMatrices[m], inverseBindMatrices[m]);`

**Comment by pjcozzi** [comment]
I _think_ this is right; the inverse bind matrix is on the right.  The function signature is [`Matrix4.multiplyTransformation = function(left, right, result)`](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Core/Matrix4.js#L1574)

**Comment by ParticlePeter** [comment]
In that case I agree. I assumed function(result, left, right) from just reading the code. But just for curiosity, what is the reason for: `result = Matrix4.multiplyTransform(left, right, result)` ?

**Comment by pjcozzi** [comment]
The `result =` is not needed in this case, but is a useful practice for when `result` is `undefined`.

Also, just to confirm, you are in agreement with the 1.0.1 spec change related to this issue?  See https://github.com/KhronosGroup/glTF/issues/461#issuecomment-223050316

**Comment by ParticlePeter** [comment]
Yes, in the sense that the `[inverse-bind]` can be omitted in the second case.
The way its written down is incorrect, as in both cases the operation would yield a `[skinned-shape]` and not a `[joint-matrix]`, but I guess that's what you meant.

**Comment by pjcozzi** [comment]
Ah yes, you are right.  Thanks for prompt response and continued support!

**Comment by pjcozzi** [comment]
Updated in #826
