### ISSUE TITLE
Proposal pull transforms and bones from accessor (partially possible through extensions)

### ISSUE THREAD

**Issue by ParticlePeter** [KhronosGroup/glTF#462]
Motivation: Looking at glTf from the OpneGL standpoint, in respect to instanced drawing and MultiDrawInderect, its nice to have (a huge amount of) transforms available as a binary chunk, directly upload-able to a TBO/UBO/SSBO.

Changes possible via extension:
- geometry, camera, light and skin pull data by index from an accessor
- multiple indices for instanced drawing (in shader possibly accessible by DrawID and InstanceID)
- works for global transforms, but local transforms must be resolved:

When local transformation is required (possible via extension):
- RootNode has an accessor reference, index and child nodes
- ChildNodes reference only accessor index and optional child nodes
- No other data is stored in nodes

To evaluate the hierarchy:
- apply animation to all (gloabl and local) transforms 
- traverse nodes, pull local transform data by index and compute global transforms
- upload global transforms to a GPU buffer or access indexed to set a uniform variable 

Required (minimal) changes to the Spec, supply alternatives via extensions (accessor and index):
- animation.channel.target make 'id' and 'path' properties optional
- skin make 'jointNames' optional

Interested in such an extension? Draft and example files can follow.

**Comment by pjcozzi** [comment]
Thanks for the input, @ParticlePeter.  Can you please provide a minimal JSON example?

**Comment by ParticlePeter** [comment]
Yes, will do, need some time for this. Would be a cube mesh transformed by three matrices enough?

**Comment by pjcozzi** [comment]
Sure, thanks!

**Comment by pjcozzi** [comment]
@lexaknyazev any thoughts on this?

**Comment by ParticlePeter** [comment]
Sorry that the example never reached this place, it actually did in proposal/issue #889 which is an evolution of this proposal. The [flat_nodes_proposal.zip](https://github.com/KhronosGroup/glTF/files/879926/flat_nodes_proposal.zip) demonstrates how the same concept but via spec changes.

**Comment by pjcozzi** [comment]
This is something we can consider for the next major glTF revision, but we are not currently actively discussing this.
