### ISSUE TITLE
Three.js glTF example loader broken?

### ISSUE THREAD

**Issue by pbeck** [KhronosGroup/glTF#463]
On both Safari and Chrome the latest three.js (what I assume is an) example loader (`glTF/loaders/threejs/index.html`) fails with
   
    ReferenceError: Can't find variable: glTFParser
    loadglTFLoader.js:874
    initScene127.0.0.1:241
    switchScene127.0.0.1:477
    onload127.0.0.1:154
    (anonymous function)127.0.0.1:580

I'm running the server with `python -m SimpleHTTPServer`

Is this code in progress or am I missing something?

Commit d78daf1e7950e6c22fe6bec1d07965e8a302e90d

**Comment by pjcozzi** [comment]
@tparisi is currently updating Three.js to support glTF 1.0.

@tparisi what is the latest?

**Comment by tparisi** [comment]
Latest is checked in to master. It supports user-defined shaders. TBD:

- Update loader to spec 1.0 and KHR_materials_common extension
- Fix outstanding skinning bug

**Comment by cx20** [comment]
I tried latest three.js glTF loader (glTF/loaders/threejs/index.html).
But, I was not able to display a duck.
Please tell me how to display it.

http://jsdo.it/cx20/UoBt

**Comment by cx20** [comment]
Additional information.

> http://jsdo.it/cx20/UoBt

[NG] GeForce GTX 660 + Windows 10 + Chrome 48.0.2564.109
[NG] GeForce GTX 660 + Windows 10 + Firefox 44.0
[NG] GeForce GTX 660 + Windows 10 + Edge 13.14257
[NG] GeForce GTX 660 + Windows 10 + IE 11.1000.14257.0
[NG] Intel HD Graphics + Windows 10 + Chrome 48.0.2564.109
[NG] Intel HD Graphics + Windows 10 + Firefox 44.0
[NG] Intel HD Graphics + Windows 10 + Edge 13.10586
[NG] Intel HD Graphics + Windows 10 + IE 11.103.10586.0
[OK] Intel HD Graphics 3000 + Mac OS X 10.10 + Chrome 47.0.2526.106
[OK] Intel HD Graphics 3000 + Mac OS X 10.10 + Firefox 38.0
[NG] Intel HD Graphics 3000 + Mac OS X 10.10 + Safari 601.2.7
[NG] iPhone OS 9.2.1 + Safari 601.1

**Comment by A1m7331** [comment]
I forked the repo and tried to open glTF/loaders/threejs/index.html but the screen stays black. Can someone tell me what's wrong?
Is glTF 1.0 already supported by this loader?

**Comment by pjcozzi** [comment]
@A1m7331 glTF 1.0 was added to three.js in https://github.com/mrdoob/three.js/pull/8316.

Can we close this?

**Comment by cx20** [comment]
This glTF Loader (glTF/loaders/threejs/index.html) contains two problems.

- `u_shininess` GLSL uniform variables is `undefined`. (https://github.com/mrdoob/three.js/issues/8381)
- Safari is unable to fetch Data URIs via `XMLHttpRequest`. (https://github.com/mrdoob/three.js/pull/9823)

The above problems have been resolved in the new glTF Loader. (https://github.com/mrdoob/three.js/pull/9786)
I will recommend that to modernize the libraries that are used in this example.

**Comment by emackey** [comment]
Hey guys, #740 deletes this whole loader and replaces it with a link to the newly official one in the Three.js repo.  This issue is now obsolete and can be closed.

**Comment by cx20** [comment]
@emackey I understood. I think this issue may be closed.
