### ISSUE TITLE
Animation Rotation Question

### ISSUE THREAD

**Issue by nopjia** [KhronosGroup/glTF#472]
Under [Animation](https://github.com/KhronosGroup/glTF/tree/master/specification#animations) section:

> The animation's parameters define the inputs to the animation: a set of floating point scalar values representing time (the "TIME" input); and sets of three-component floating-point vectors representing translation, rotation, and scale. Each of these inputs is stored in a buffer and accessed via an accessor.

Under [sampler.interpolation](https://github.com/KhronosGroup/glTF/tree/master/specification#samplerinterpolation):

> When an animation targets a node's rotation, and the animation's interpolation is "LINEAR", spherical linear interpolation (slerp) should be used to interpolate quaternions.

A couple questions:
- Providing a 3-component Euler angles alone is ambiguous. We're missing the rotation order. Without it you cannot correctly construct the rotation since different engines have different default rotation orders.
- Is it valid to directly store 4-component quaternions for rotation instead? This would solve the ambiguity plus avoid the conversion at runtime. If so, how do we distinguish it from the 3-component Euler rotation? Would it be "VEC4" under `accessor.type`?

**Comment by pjcozzi** [comment]
Hi @nopjia, I'm excited that you are checking out glTF!  Let me know what you think.

In glTF, animated rotations are defined by quaternions (x, y, z, w).  They were defined by axis-angle in and older version of the spec (#144), and this is just a typo.  I fixed it in the new [1.0-final](https://github.com/KhronosGroup/glTF/compare/1.0-final) branch.  Let me know if you find any other errors in the spec.

For an example glTF model with animated rotations, see https://github.com/KhronosGroup/glTF/tree/master/sampleModels/CesiumMilkTruck/glTF

**Comment by nopjia** [comment]
Thanks for the clarification @pjcozzi!

We've been using glTF 0.8 for a couple months now, and it has served us very well. We've been privately maintaining an Assimp exporter plugin in-house, which we hope to open-source at some point.

Will definitely give you feedback when I come across them, and hope to make more contributions in the future. Looking forward to the 1.0 spec!

**Comment by pjcozzi** [comment]
Wow, @nopjia that exporter would be great.  You might want to coordinate with @kimkulling: https://github.com/KhronosGroup/glTF/issues/456#issuecomment-155124570

**Comment by pjcozzi** [comment]
Nothing left to do here.
