### ISSUE TITLE
Specification is still called a "Draft"

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/glTF#473]
The first line of the specification says "Draft, Version 1.0". Since it's a [fully shipped specification](https://www.khronos.org/gltf/), it should no longer be considered a draft.

**Comment by pjcozzi** [comment]
Thanks for the input.  It is still technically a draft since the spec is going through Khronos ratification; however, we do not expect any significant changes.

**Comment by pjcozzi** [comment]
The spec is no longer a draft and "draft" was removed in #521.
