### ISSUE TITLE
Base64 variation specification

### ISSUE THREAD

**Issue by NicolBolas** [KhronosGroup/glTF#474]
Base64 encoding format does have a number of variations on it. Whether there is padding or not, or whether padding is optional or not. Whether it's the URL-safe version or not. And so forth.

The specification should state the specific variation of Base64 that is intended to be used. Is it RFC 4648, which matches JavaScript's requirement? Are user agents required to process other forms of Base64?

The [Wikipedia article on Base64](https://en.wikipedia.org/wiki/Base64#Variants_summary_table) has a list of all of the variations of Base64 encoding.

**Comment by pjcozzi** [comment]
@NicolBolas thanks for bringing this to our attention.  We'll tighten up the spec before we move it out of draft status.

Here is the loader we are for base64-encoded data uris: https://github.com/AnalyticalGraphicsInc/gltf-utilities/blob/master/gltfUtilities.js

@shunter @NicolBolas do you have any suggestions on wording?

**Comment by NicolBolas** [comment]
Since your decoder is using JavaScript's `atob`, you should probably just state that the Base64 format is RFC-4648. With a [link to it](https://tools.ietf.org/html/rfc4648), of course.

**Comment by pjcozzi** [comment]
Thanks again, @NicolBolas!  Updated in c2965bf2aac28e8371c33215f3d81510e85c770c (this is in the `1.0-final` branch).

Let us know if you have any other feedback on the spec.

Also, what are you building with glTF?

**Comment by NicolBolas** [comment]
> Also, what are you building with glTF?

Nothing... right now. I'm evaluating it for inclusion in [my SDK](http://alfonse.bitbucket.org/glsdk/). I was already working on a simple scene graph system, and I thought glTF could make for a useful file format for it. That's why I was concerned about glTF lacking so many features of modern desktop OpenGL, since I wanted the scene graph to be able to use some of those features.

**Comment by pjcozzi** [comment]
Ah, cool.  Thanks for sharing.
