### ISSUE TITLE
Virtual City Model - Shaders Not Displaying Correctly

### ISSUE THREAD

**Issue by tparisi** [KhronosGroup/glTF#477]
If you run the Virtual City model using the shaders version, you get largely black output, though some geometry is visible along outlines. Based on a little experimentation it appears that some vectors are backwards in Z, or at least, negating them results in visible output. I don't know if this is a converter issue, or the generated shaders are buggy, or if it's the importer.

@pjcozzi last we discussed this you said this model crashes Cesium. Any progress there? Would love to have a baseline for comparison. @tfili any thoughts on this?

**Comment by tfili** [comment]
All 3 versions of the model in master work correctly in Cesium.

**Comment by tparisi** [comment]
This is with the shaders on right? Not with the materials extension?

**Comment by tfili** [comment]
@tparisi That works correctly too.

**Comment by tparisi** [comment]
OK then - must be on my end w Three.js. Thanks

**Comment by tparisi** [comment]
I've got a bead on this, working on it.
