### ISSUE TITLE
Incorrect Skeletons in Cesium Man Sample Model

### ISSUE THREAD

**Issue by tparisi** [KhronosGroup/glTF#484]
The `skeletons` property in Cesium Man looks wrong. It has the whole array of joints in it instead of just the root of the skeleton. I had to add logic to the Three.js loader to only use the first element of the array instead of adding every skeleton, otherwise it did not animate correctly (unless of course I've got a bug somewhere which is totally possible). Here's the content:

```
            "skeletons": [
                "locator047Node",
                "locator051Node",
                "locator055Node",
                "locator059Node",
                "locator063Node",
                "locator071Node",
                "locator074Node",
                "locator079Node",
                "locator082Node",
                "locator087Node",
                "locator090Node",
                "locator103Node",
                "locator106Node",
                "locator111Node",
                "locator114Node",
                "locator119Node",
                "locator122Node",
                "locator135Node",
                "locator138Node"
            ],
```

**Comment by tparisi** [comment]
@pjcozzi @tfili

**Comment by tparisi** [comment]
@lilleyse can you also reconvert RiggedFigure? Seems to have the same `skeletons` issue where the property has all the joints instead of the just the root node...

**Comment by pjcozzi** [comment]
Can we close this?

**Comment by pjcozzi** [comment]
I believe we can close this.  Please reopen if not.
