### ISSUE TITLE
Brainsteam model missing parts

### ISSUE THREAD

**Issue by tparisi** [KhronosGroup/glTF#486]
![brainsteamscreenshot](https://cloud.githubusercontent.com/assets/422759/11430078/f1af29de-9435-11e5-9831-69aa0525d8be.png)

**Comment by pjcozzi** [comment]
@tparisi is this still an issue?  Can we close this?

**Comment by tparisi** [comment]
It's still an issue, we deprioritized fixing it. I would leave it open, maybe we can take another crack soon?

**Comment by pjcozzi** [comment]
Closing.  The latest three.js loads all sample models correctly.
