### ISSUE TITLE
Converted Models Have Non-unique IDs

### ISSUE THREAD

**Issue by tparisi** [KhronosGroup/glTF#488]
Check out Cesium Man for example: it has both a buffer and a node with the ID `Cesium_Man`. This is illegal and I think it's causing my Three.js loader some problems.

From the spec:

IDs for top-level glTF dictionary objects (`accessors`, `animations`, `buffers`, `bufferViews`, `cameras`, `images`, `materials`, `meshes`, `nodes`, `programs`, `samplers`, `scenes`, `shaders`, `skins`, `techniques`, and `textures`) are in the same namespace and are unique. 

@lilleyse this one's for you.

**Comment by pjcozzi** [comment]
Since this is a COLLADA2GLTF issue, it would be better for @tfili to look at it.  @lilleyse don't worry about this unless you think some hand-editing caused this.

**Comment by tparisi** [comment]
Sorry I though Sean had taken over the converter... sure thing please have a look Tom

**Comment by pjcozzi** [comment]
Replaced by https://github.com/KhronosGroup/COLLADA2GLTF/issues/119
