### ISSUE TITLE
General questions about glTF as a format vying for industry adoption

### ISSUE THREAD

**Issue by erlend-sh** [KhronosGroup/glTF#489]
I've noticed that glTF doesn't yet have its own discussion directory on the Khronos forum [like Collada does](https://forums.khronos.org/forumdisplay.php/116-COLLADA).

I have a couple general questions that don't really belong in an issue tracker. Is there a more appropriate place to ask non-development questions, or should I just post them here for the time being?

**Comment by pjcozzi** [comment]
@erlend-sh feel free to post them in this issue.

**Comment by erlend-sh** [comment]
Alrighty then. First couple of questions incoming.

Vulkan was released alongside an impressive roster of Working Group Participants, such as Unity3D, Epic, Blizzard, EA, Intel, Nvidia etc., so:

- Is there a list of partners / working group participants?
- Is Khronos actively reaching out to key collaborators?
 - Blender & the other major 3D modeling suites?
 - Unity3D, Epic et.al?
 - Companies like [Sketchfab](https://sketchfab.com/)

On that note, I put up a request for glTF support on Unity3D's feedback page:

https://feedback.unity3d.com/suggestions/support-import-and-loading-of-gltf-format

**Comment by pjcozzi** [comment]
> Is there a list of partners / working group participants?

The quotes in the press release give a pretty representative picture of the initial supporters: https://www.khronos.org/news/press/khronos-finalizes-gltf-1.0-specification

We also update this repo's [README.md](https://github.com/KhronosGroup/glTF/blob/master/README.md) as we become aware of new adoptions.

> Is Khronos actively reaching out to key collaborators?

Yes.  We are also engaging the open-source community, e.g., #456 and providing mentorship for projects like https://github.com/AnalyticalGraphicsInc/gltf-pipeline

If you have contacts at specific organizations, we would also welcome an introduction.  Email me at pjcozzi@siggraph.org

**Comment by vinjn** [comment]
@erlend-sh are you asking about Vulkan?

**Comment by pjcozzi** [comment]
For the latest 2.0 adoptions, keep an eye on #1030
