### ISSUE TITLE
Remove dummy loader

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#490]
https://github.com/KhronosGroup/glTF/tree/master/loaders/dummy

This is not up-to-date with the latest spec or sample models, and is not very illustrative.

I plan to remove it.  @tparisi let me know if you think otherwise.

**Comment by pjcozzi** [comment]
Still +1 from me especially since this was not updated to 2.0.  Any objections?

**Comment by emackey** [comment]
The whole `loaders` folder can go.  The other two already moved out.

**Comment by pjcozzi** [comment]
Agreed.  Can you open a PR for this?
