### ISSUE TITLE
C# loader missing files?

### ISSUE THREAD

**Issue by pzgulyas** [KhronosGroup/glTF#492]
Most probably it is a lame question, but: What do I miss when I'm not seeing the files under loaders/CSharp/glTFLoader/Schema/ directory, that loaders/CSharp/glTFLoader/glTFLoader.csproj references, thus not ableing to build CSharp.sln in a fresh git clone?

**Comment by pzgulyas** [comment]
My bad, I had to start the built Generator.exe manually to generate the files... I'm sorry for the confusion.

**Comment by pjcozzi** [comment]
No problem, let us know what you build with it!  @MattMcMullan will also be interested.

**Comment by MattMcMullan** [comment]
You're right, I would be interested. I'll also see if I can make that step automatic.

**Comment by pzgulyas** [comment]
Free desktop game OpenRails (openrails.org, written in C#) in long term needs a new runtime 3D asset format, and I'm just looking around, nothing specific. :) (Taking the opportunity, I would just let you know, the NuGet package for C# wrapper contains a lot of garbage. I know, it is a work in progress. :) )

**Comment by MattMcMullan** [comment]
Cool! I think I've seen my brother playing that before :)
Thanks for the heads up about the NuGet package. I'll have Xueru take a look at that while I'm at work.

**Comment by MattMcMullan** [comment]
The NuGet package has been updated.

**Comment by pjcozzi** [comment]
PR: #498
