### ISSUE TITLE
Problems installing 1.0 Mac Collada2GLTF

### ISSUE THREAD

**Issue by jcarpenter** [KhronosGroup/glTF#494]
I've tried installing from both compiled binaries and source, and have given up after several hours of research and dead ends. I'm a relative command line newb, so these issues may be down to inexperience, but I'm flagging in case these are bugs, and/or to encourage a bit more documentation for end-to-end Getting Started processes.

This is on latest El Capitan (10.11.1)

First I tried installing from compiled binary...
1. Downloaded 1.0 [collada2gltf_mac_v1.0-draft_x64.gz ](https://github.com/KhronosGroup/glTF/releases)
2. Ran `tar xvzf collada2gltf_mac_v1.0-draft_x64.gz`
3. Got following errors: `tar: Unrecognized archive format` and `tar: Error exit delayed from previous errors.`
4. Checked file type with `file collada2gltf_mac_v1.0-draft_x64.gz`
5. Got `gzip compressed data, was "collada2gltf", from FAT filesystem (MS-DOS, OS/2, NT), last modified: Thu Oct 22 10:32:31 2015, max compression`
6. Can successfully decompress by simply double-clicking the `.gz` file in Finder, but that returns a 16.5 MB `collada2gltf_mac_v1.0-draft_x64` file with no action on double click. Which is to say, I'm not sure what to do with it. 

I assume the process of installing via compiled binary is supposed to be something like [ImageMagick](http://www.imagemagick.org/script/binary-releases.php#macosx), wherein I extract the .gz then set environment variables. But hitting a brick wall on step 3 prevented that approach.

Next I tried to build from source...
1. Cloned repo
2. Installed dependencies (eg libpng. Already have XCode 7.1.1)
3. Successfully run `cmake -G Xcode`
4. Ran `xcodebuild -target collada2gltf`. Got `Build Succeeded` output
5. Got new directories in `COLLADA2GLTF.build/Debug`:
   - collada2gltf.build
   - collada2gltfConvert.build
   - ZERO_CHECK.build
6. Inside `collada2gltfConvert.build/Objects-normal/x84_64` there are 106 files with promising names like `animationConverter.o`. 
7. The documentation ends here, and I am unclear on what to do next.

Again, this may be user error. But I suspect others will have similar problems. A bit more documentation would go a long way here, I think.

I did also try the Cesium [converter](http://cesiumjs.org/convertmodel.html), fwiw, but hit issues there as well. Failure to get textures through the pipeline, mainly. I'll file those as separate issues.

**Comment by cvan** [comment]
It's a `.gz` file (not a `.tar.gz` file) so you'll want to do:

```bash
curl -L -O 'https://github.com/KhronosGroup/glTF/releases/download/v1.0-draft/collada2gltf_mac_v1.0-draft_x64.gz'
gunzip collada2gltf_mac_v1.0-draft_x64.gz
chmod +x collada2gltf
./collada2gltf
```

I also found a working [Mac build](https://github.com/AnalyticalGraphicsInc/collada2gltf-web-service/blob/master/collada2gltf/mac/collada2gltf) from the [Cesium converter](https://github.com/AnalyticalGraphicsInc/collada2gltf-web-service): 

```bash
curl -L -O 'https://github.com/AnalyticalGraphicsInc/collada2gltf-web-service/raw/master/collada2gltf/mac/collada2gltf'
chmod +x collada2gltf
./collada2gltf
```

**Comment by jcarpenter** [comment]
Awesome, thanks @cvan. I'll give the above a shot this week

**Comment by jcarpenter** [comment]
The first approach provided by @cvan worked perfectly. I'm now able to use the installed converter from command line. Those steps should be added to the docs, IMO.

**Comment by pjcozzi** [comment]
@cvan @jcarpenter thanks for the input.  I added this example to the release: https://github.com/KhronosGroup/glTF/releases/tag/v1.0-draft

@cvan FYI - the collada2gltf in the collada2gltf-web-service repo is the old glTF 0.8 version.  I submitted https://github.com/AnalyticalGraphicsInc/collada2gltf-web-service/issues/1.

By the way, what are you guys building with glTF?

**Comment by pjcozzi** [comment]
Closing this issue, but still please still feel free to comment here on your work.

**Comment by jcarpenter** [comment]
Nice, thanks @pjcozzi!

We're looking at using glTF in various WebVR projects, including our new WebGL markup framework. Here's an early example of what we're building: https://dl.dropboxusercontent.com/u/667711/mockups/aframe-shopping.mov

**Comment by pjcozzi** [comment]
Ah, very nice!  Thanks for sharing.  Please keep us posted on how it goes.

**Comment by pjcozzi** [comment]
Wow a very historic A-Frame thread!

Sorry, forgot to close this two years ago, https://github.com/KhronosGroup/glTF/issues/494#issuecomment-161309950

**Comment by cvan** [comment]
Heh, yes indeed! Nice fuzzies thinking about this. 2 years ago. @joshcarpenter: Good work, us! ⭐️
