### ISSUE TITLE
C# loader missing animation.sampler object

### ISSUE THREAD

**Issue by pzgulyas** [KhronosGroup/glTF#495]
The generated Animation.cs references the wrong sampler object. The "Samplers" dictionary points to the root property "Sampler", instead of the animation sampler. Probably the cs schema generator doesn't recognize, that there are two different "Sampler" objects in the hierarchy with the same name, but different content.

**Comment by pjcozzi** [comment]
@MattMcMullan what do you think?

**Comment by MattMcMullan** [comment]
I know exactly what's broken. I'll fix it when I get home and send a pull request.

I'm glad to see someone else exercising the API. I haven't gotten to animations in my sample renderer yet.

**Comment by MattMcMullan** [comment]
Pull request sent in. The version in the NuGet package has the fix.

**Comment by pjcozzi** [comment]
PR: #498

**Comment by MattMcMullan** [comment]
Can we close this issue?
