### ISSUE TITLE
C# loader image format System.Drawing.Bitmap is quite limited

### ISSUE THREAD

**Issue by pzgulyas** [KhronosGroup/glTF#497]
I'm really just exploring things, but I think hardwiring the texture container format into library makes its usability without modifications to be limited. If anyone considers it using with OpenTK / XNA / MonoGame / whatever, he needs to change the library in order to be able to use his own needed container. It might be better to expose the image data as byte[], with also making the mime-type/filename info available somehow. The latter info is currently lost. (And it would be considerable to explicitly name the DDS texture format in glTF spec as supported format, but that is a different issue. :) )

Filename would be good to have anyways, since if the file was not found at the default location (e.g. in the same directory as gltf itself), the main application may have other "ideas" where to search for (e.g. in a common textures folder).

**Comment by MattMcMullan** [comment]
We don't always have a filename. The minimum that you're guaranteed is a byte[] representing an image in some format, and a mime type representing what that format is.  We can extract the native storage format from the Bitmap quite easily ("RawFormat"), if that's a concern.  Loading a Bitmap object into OpenTK is easy, just look at [some](http://www.opentk.com/doc/graphics/textures/loading) of the [OpenTK samples](https://github.com/opentk/opentk/blob/13f79437d51a7a696495d269fefae8671059263c/Source/Examples/Utilities/LoaderGDI.cs).  [Conversion to a Texture2D](http://christophermpark.blogspot.com/2008/10/converting-systemdrawingbitmap-to-xna.html) for XNA or MonoGame is also quite easy and quite efficient if you use the format returned by RawFormat, as Bitmap will not have decoded the file.  This is incidentally a fairly easy way to extract the byte[] for the image if you still need it for something.

Adding support for alternate directories is already planned work in about the same time-frame as web-uri support.  The idea is to take an IFilesystem object similar to [this](https://msdn.microsoft.com/en-us/library/microsoft.owin.filesystems.ifilesystem(v=vs.113).aspx), but with a TryGetFileContentAsync function.  This allows for any layers of abstraction that you would like including shared textures folders, compressed asset libraries, dynamically grabbing missing assets from the host for a match, etc.  With this planned for the near future, I'm unconvinced of the need to add direct access to a file path that may or may not be there.

S3TC format textures are an issue that I'm currently trying to grapple with. I intend to use it for one of my projects, so we need to figure it out soonish.  I'm hoping to gather some opinions about DDS support in the next weekly glTF call.  Given positive feedback, the next step would be to contact somebody on the .net team internally and see about adding native DDS support to the Bitmap object. This would have the added advantage of easily loading various image formats into compressed textures.  I'll grab a copy of the codebase to see how feasible it looks, but from the interface it looks like I'll just need to supply encoders/decoders and add a value to the ImageFormat enum.

**Comment by pzgulyas** [comment]
Okay, than you for your answers, looking forward to the upcoming adjustments.

I have one more concern, or feature request: I see that at glb loading you implemented the image reading from a bufferview, offsetted in a buffer. Actually you could expose all other bufferviews as a dictionary of byte[] (or properly seeked BinaryStreams) the same way, since the logic of decoding them is the same; and since all programmers must have implemented the same subroutine in their program in order to read them, it would be better to have it directly in the library. They don't actually need the data of a buffer, they need to work with the data from bufferview.

**Comment by pjcozzi** [comment]
FYI - given the amount of interest in the C# loader, I added a new `C# loader` label to this repo: https://github.com/KhronosGroup/glTF/labels/C%23%20loader

**Comment by pjcozzi** [comment]
@sbtron should this be a new issue in the https://github.com/KhronosGroup/glTF-CSharp-Loader repo?

**Comment by bghgary** [comment]
@pzgulyas 

> It might be better to expose the image data as byte[]

I believe the C# loader no longer uses Bitmap and returns the bytes of the image now. 

> feature request: ... all other bufferviews could be exposed as a dictionary of byte[]

This is also handled in the C# loader now.

Please open an issue in the C# loader repo if the new version does not meet your requirements.

@pjcozzi Given this, I think we can close this issue.
