### ISSUE TITLE
Consider Git LFS for sample models

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#502]
https://github.com/blog/1986-announcing-git-large-file-storage-lfs

We don't want to store too many sample models or big ones in the Git repo.

**Comment by pjcozzi** [comment]
[Pricing](https://help.github.com/articles/billing-plans-for-git-large-file-storage/) is reasonable (free to 1 GB storage/bandwidth a month).  Then $5 a month per 50 GB storage/bandwidth.

However, it doesn't look like a user would be able to download a model directly from the repo using the GitHub website as I suspect many do today.  The [pointer files](https://help.github.com/articles/about-git-large-file-storage/) contain a hash, not a url to the asset.

Users would also need to install Git LFS in order to get the sample models through Git: https://help.github.com/enterprise/2.2/user/articles/collaboration-with-git-large-file-storage/

That makes the barrier to entry way too high.

We could:
* Put all sample models in a separate repo to avoid bloating this repo, and/or
* Host all sample models greater than, perhaps, 5 MB on another server, but still include direct links in the sample models README.md

**Comment by pjcozzi** [comment]
A fresh clone of the current repo (without submodules) is 368 MB.

GitHub recommends keeping a repo under 1 GB, and does not allow files > 100 MB. https://help.github.com/articles/what-is-my-disk-quota/

**Comment by lasalvavida** [comment]
As in this [issue](https://github.com/github/git-lfs/issues/908)

>> Git LFS objects can not be uploaded to this public fork.

>This is a behavior on GitHub's LFS server to prevent potential abuse. You can't upload LFS objects to a fork of public repository unless you have push access to the original public repository. I realize this is inconvenient. This is on my roadmap to fix.

Moving sample models to LFS is the best solution right now, but we don't want to lose the ability for people to open pull requests to contribute sample models. This will have to wait until this is fixed, which should hopefully be fairly soon.

**Comment by lasalvavida** [comment]
> GitHub doesn't allow new Git LFS objects on public forks unless the pusher a) the pusher has write access to the original or b) the original repo already has Git LFS content.

@pjcozzi It sounds like this has been resolved enough to try again, but I do not have push access so I can't say for sure

**Comment by pjcozzi** [comment]
> @pjcozzi It sounds like this has been resolved enough to try again, but I do not have push access so I can't say for sure

Can you experiment in a temporary repo and fork and and then advise?

**Comment by pjcozzi** [comment]
@lexaknyazev can you add your findings here based on our offline discussion?

**Comment by lexaknyazev** [comment]
We've decided to use a regular repo for now instead of LFS, because:
- aforementioned PR issues;
- inability to download models without git client (sure, it's not an issue for software developers, but we want models to be accessible for all users);
- bandwidth billing: 50GB/mo could be reached very quickly (all access to LFS counts).

**Comment by pjcozzi** [comment]
Closing since there's nothing actionable here.

Good notes though.

See https://github.com/KhronosGroup/glTF-Sample-Models
