### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by michaelknave** [KhronosGroup/glTF#504]
Can somebode tell me how to use the glTF converter in command line? There is no example 

Thanks

**Comment by pjcozzi** [comment]
The simplest way to use it is:
```
collada2gltf -f model.dae
```
Run just `collada2gltf` to see all the options.

**Comment by throni3git** [comment]
Is there an option to include the texture URLs or base64 versions into the gltf file?

**Comment by pjcozzi** [comment]
> Is there an option to include the texture URLs or base64 versions into the gltf file?

I believe it is `-e` to embed.  Run just `collada2gltf` to see all the options.

> Another question: i'm trying to wrap the textures and gltf/bin files into a zip, so THREE.glTFLoader.load() isn't appropriate. Is there a method that accepts the gltf content itself instead of setting up the complete XHR request around it?

I am not familiar with the Three.js implementation.

@tparisi might know.

**Comment by throni3git** [comment]
I tried -e, but it didn't do anything with textures. It does indeed embed the Shaders and the geometry into the gltf-file.

**Comment by pjcozzi** [comment]
`-e` should embed textures.  For example, we used it to create https://github.com/KhronosGroup/glTF/tree/master/sampleModels/boxTextured/glTF-Embedded.

It could be a bug in the converter or an issue with the source model.  Can you submit a separate issue with an example model?

**Comment by pjcozzi** [comment]
If there's still an issue here, please submit an issue to https://github.com/KhronosGroup/COLLADA2GLTF
