### ISSUE TITLE
Converter Exporting Phong Instead of Constant for Unlit Common Materials Export

### ISSUE THREAD

**Issue by tparisi** [KhronosGroup/glTF#511]
Looking at the Cesium Milk Truck model's base glTF, which doesn't have lighting, and then the Common Materials version, it seems like collada2gltf isn't correctly exported the material. The exported materials should be using the technique "CONSTANT" but the materials in the file all have "PHONG" instead.

**Comment by pjcozzi** [comment]
Replaced by https://github.com/KhronosGroup/COLLADA2GLTF/issues/120
