### ISSUE TITLE
Clarification regarding explicit definition of "binary_glTF"

### ISSUE THREAD

**Issue by Qantas94Heavy** [KhronosGroup/glTF#515]
In the KHR_binary_glTF extension document, it states the following:

> As mentioned above, Binary glTF introduces a buffer with id equal to "binary_glTF". This buffer is an implicit reference to the binary body of the Binary glTF asset. Its type property is "arraybuffer", and a runtime can ignore the uri property since the buffer refers to the Binary glTF body section, not an external resource. When a runtime encounters this buffer, it should use the Binary glTF body as the buffer. bufferViews that reference this buffer work as usual.

Does this mean that this buffer is already defined and as such does not need to be defined as a "dummy" object?

``` json
{
  "buffers": {
    "binary_glTF": {
      "byteLength": 123456,
      "uri": ""
    }
}
```

**Comment by Qantas94Heavy** [comment]
It turns out that this was to do with Cesium using the buffer name `"KHR_binary_glTF"` instead of `"binary_glTF"`, and it is in fact not meant to be needed -- closing.

**Comment by Qantas94Heavy** [comment]
After checking again, seems to not be the case.

Even now, it seems that this needs to be defined, even though it should be easily retrievable from the binary glTF file and it is mentioned as being "implicit". Cesium still throws an error if this is not defined.

**Comment by pjcozzi** [comment]
@Qantas94Heavy it does need to be defined.  For example, see a simple sample model like https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/1.0/Box/glTF-Binary

**Comment by pjcozzi** [comment]
I think this was answered.  Please re-open if that is not the case.
