### ISSUE TITLE
Unknown shader uniform param type on loading the sample models

### ISSUE THREAD

**Issue by rolandh-wikitude** [KhronosGroup/glTF#516]
Loading a model from the sampleModels folder with the glTFLoader (branch master from 30th Dec.) brings up the following error:
"Unknown shader uniform param type: 35666 - undefined" in glTFLoader.js, line 1017

Am I doing something wrong?

**Comment by pjcozzi** [comment]
Which sample model?  Was it [boxSemantics](https://github.com/KhronosGroup/glTF/tree/master/sampleModels/boxSemantics)?

@tparisi any ideas?

**Comment by rolandh-wikitude** [comment]
I tried with sampleModels/box/glTF/box.gltf and sampleModels/monster/glTF/monster.gltf

**Comment by pjcozzi** [comment]
If this is still an issue with the latest sample models and three.js loader, please submit an issue to https://github.com/KhronosGroup/glTF-Sample-Models
