### ISSUE TITLE
We should have all flavors of converted models in sampleModels folder (Binary, Materials_Common etc)

### ISSUE THREAD

**Issue by tparisi** [KhronosGroup/glTF#517]
@pjcozzi @tfili can we get glTF-Embedded, glTF-MaterialsCommon and glTF-Binary versions of each model in the sampleModels folder? This is for completeness and also will help me test the data: URI feature with Three.js.

FWIW I'm not implementing the Binary extension right now, so that won't help me for Three.js; however we should have them for completeness.

**Comment by pjcozzi** [comment]
There already are all of these variations for several of the models, for example: https://github.com/KhronosGroup/glTF/tree/master/sampleModels/boxAnimated

**Comment by tparisi** [comment]
Understood but it would be good to have them all if possible. Not highest priority. But for completeness.

**Comment by pjcozzi** [comment]
Fixed in #579.
