### ISSUE TITLE
Update KHR_materials_extension to newest draft

### ISSUE THREAD

**Issue by tfili** [KhronosGroup/glTF#523]
I believe the only change that is needed is removing `type` from the material values.

For example, this

```
"values": {
    "diffuse": {
        type: 35666,
        value: [0.5, 0.5, 0.5, 1]
    }
}
```

should be changed to this

```
"values": {
    "diffuse": [0.5, 0.5, 0.5, 1]
}
```

**Comment by tparisi** [comment]
are we removing `type` ? It's in the sample models...

**Comment by pjcozzi** [comment]
Yes, we plan to update the sample models by the end of the month: https://github.com/AnalyticalGraphicsInc/cesium/pull/3413#issue-126183096

**Comment by tparisi** [comment]
@pjcozzi OK then we'll need to update all loaders, too. e.g. Three.js. Please let me know when you update the samples and I'll do the loader.

**Comment by pjcozzi** [comment]
Will do.  End of the month, latest.

**Comment by pjcozzi** [comment]
@tparisi  here are the updated sample models courtesy of @tfili - https://github.com/KhronosGroup/glTF/pull/531

**Comment by pjcozzi** [comment]
@McNopper OK to close as duplicate with #947 and #945?

**Comment by UX3D-nopper** [comment]
Yes, as it is not valid anymore.
