### ISSUE TITLE
collada2gltf - optionally preserve vertex colors

### ISSUE THREAD

**Issue by torleif** [KhronosGroup/glTF#528]
when using the collada2gltf tool, it's stripping the vertex color information from the resulting gltf file

**Comment by AndresCuervo** [comment]
Is there a way to do this? I just ran into this problem, and was wondering if there's a workaround, possibly another conversion tool for now?

**Comment by donmccurdy** [comment]
There is more information in this bug on the COLLADA2GLTF repo: https://github.com/KhronosGroup/COLLADA2GLTF/issues/12

Modifying COLLADA2GLTF with the suggested fix has worked for me before, but I don't know enough about the code to say if it is safe to merge.

**Comment by donmccurdy** [comment]
The [blender exporter](https://github.com/KhronosGroup/glTF-Blender-Exporter) should also include vertex colors, but may take some tweaking (per the exporter's docs). Going to close this bug and consider it a duplicate of the COLLADA2GLTF#12.
