### ISSUE TITLE
collada2gltf blank textures

### ISSUE THREAD

**Issue by AndreyOrlov** [KhronosGroup/glTF#530]
Hello, 

I'm trying to convert collada model to gltf with last released version of collada2gltf converter. Generally it works  OK, but some parts of model are blank. But if you use converter with option -i (invert transparancy) you can see parts of model which are was blank. This behavior you can see with this model, for example https://3dwarehouse.sketchup.com/model.html?id=d133fa016f4e452b8287fae9e4c703ae

After normal convertation
![2016-02-01_17h12_50](https://cloud.githubusercontent.com/assets/2196469/12719537/aa44562c-c906-11e5-8b3a-f9fa712a8c3c.png)

After convertation with option -i
![2016-02-01_17h11_43](https://cloud.githubusercontent.com/assets/2196469/12719562/d8d9e722-c906-11e5-88f0-6711fdc7e959.png)

Online converter works fine though. Is this a problem of collada2gltf converter or there is needs some prepocessing? I would be apprciate to get any advice.

**Comment by pjcozzi** [comment]
The online Cesium converter does some preprocessing, and _might_ use `-i`.  @tfili would know for sure.

**Comment by tfili** [comment]
It doesn't use -i but there is some preprocessing. Did you look at the .gltf files with and without -i and see what the difference is? I can take a look at it later today.

**Comment by AndreyOrlov** [comment]
Yes, @tfili . Generally, difference is in deleting "transparency": -1 parameter or adding "transparency": 0 in case when texture doesn't have transparency parameter and adding or deleting transparency shaders. It looks ligical, I can't see anything unusual. Maybe, problem is in texture coordinates or something else, not in transparency and parameter -i?

**Comment by tfili** [comment]
The issue here is that the converter doesn't handle transparency maps.

I've introduced a band-aid #532 that will convert this model pretty well. Lets keep this open for handling transparency maps.

**Comment by AndreyOrlov** [comment]
Thank you!

**Comment by pjcozzi** [comment]
Replaced by https://github.com/KhronosGroup/COLLADA2GLTF/issues/121
