### ISSUE TITLE
Copyright notice says "All rights reserved"

### ISSUE THREAD

**Issue by ahcox** [KhronosGroup/glTF#536]
In examples such as [this](https://github.com/KhronosGroup/glTF/blob/master/COLLADA2GLTF/GLTFOpenCOLLADA.h) and [this](https://github.com/KhronosGroup/glTF/blob/master/COLLADA2GLTF/COLLADA2GLTFWriter.cpp) the phrase "All rights reserved." precedes the license proper. Is this not a contradiction of the license which specifies which rights are granted to users?

**Comment by pjcozzi** [comment]
Good eye, thanks @ahcox!

@fabrobinet do you know what the history of these files is?

I thought all code in the converter is under the 3-Clause BSD

**Comment by fabrobinet** [comment]
@pjcozzi yes, It is BSD-3 and this is consistent with https://opensource.org/licenses/BSD-3-Clause . But I don't want this to be restrictive (it wasn't the intend at the time), please feel free to unify licenses where I was involved at the time in a way that is consistent and acceptable for this project. Thanks.

**Comment by ahcox** [comment]
I had a look around and have seen this phrase next to or below the copyright notice of many open source projects. I am not a lawyer but I think the only problem is that it might confuse other people who are also not lawyers.

I would vote to close this issue if it doesn't bother the main developers. Sorry for the bother.

**Comment by emackey** [comment]
I'm not a lawyer either, but I believe this is (or used to be) the lawyer's version of a whitelist: Deny all, then allow specific uses.  @pjcozzi may want to leave this as a reminder to standardize the license messages across the project, however.

**Comment by pjcozzi** [comment]
We'll leave this open as a reminder to update.  Thanks for pointing this out, @ahcox!

**Comment by pjcozzi** [comment]
Replaced by https://github.com/KhronosGroup/COLLADA2GLTF/issues/122
