### ISSUE TITLE
KHR_binary_glTF Readme

### ISSUE THREAD

**Issue by konashredbiker** [KhronosGroup/glTF#538]
The [JSON Schema for image and shader](https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_binary_glTF#json-schema) in the KHR_binary_glTF Readme.md is 404.

Also it says "buffer with id equal to "binary_glTF"" several times. I thought when using the KHR_binary_glTF extension, the buffer id has to be "KHR_binary_glTF" now.

**Comment by emackey** [comment]
The 404s are fixed now.

**Comment by pjcozzi** [comment]
Thanks for the report, @konashredbiker.

The buffer name should be `"binary_glTF"`.  For example, here is the Cesium loader: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Model.js#L1132-L1135

**Comment by konashredbiker** [comment]
Thanks!
That explains, why in the sample models the buffer name is `"KHR_binary_glTF"`. It was a little bit confusing.

**Comment by pjcozzi** [comment]
@konashredbiker do the sample models in this repo still have the buffer name as `KHR_binary_glTF`?  If so that is an issue, and we need to regenerate them.

**Comment by konashredbiker** [comment]
Yes, at least the box sample models.

**Comment by pjcozzi** [comment]
Thanks for catching this, we will update the sample models.  I submitted #541.
