### ISSUE TITLE
collada2gltf is not working properly @ three.js glTF loading example

### ISSUE THREAD

**Issue by mikim** [KhronosGroup/glTF#540]
I used collada2gltf binary to convert a dae format to glTF.
https://github.com/KhronosGroup/glTF/releases (mac version)

I tested a converted glTF model using r74 glTF loading example.
https://github.com/mrdoob/three.js/releases 
http://threejs.org/examples/#webgl_loader_gltf 

I added a glTF model to the sceneList.
https://github.com/mrdoob/three.js/blob/master/examples/webgl_loader_gltf.html#L370

First, output json file was not parsed by 
https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/gltf/glTF-parser.js

I had to change "uri" to "path".
I had to add "instanceTechnique" key to "materials".

Then all error messages was gone.

But there was no model in the display. So can you figure this out?

**Comment by mikim** [comment]
Oh! examples provided here are working greatly.

But when I gave an option with compression Open3DGC, web browser give an error as follows:
Uncaught RangeError: Invalid typed array length at glTFLoader.js:442.

maybe @tparisi can figure this out?

**Comment by pjcozzi** [comment]
@mikim the compression work is not ready; it is still a work-in-progress, see #398.

**Comment by pjcozzi** [comment]
OBE.  Keep an eye on the Draco compression work: https://github.com/KhronosGroup/glTF/pull/874
