### ISSUE TITLE
Three.js loader cannot load the 22 MB GLTF file

### ISSUE THREAD

**Issue by pineliu** [KhronosGroup/glTF#543]
I used the Collada2GLTF tool to convert a 27MB DAE file to the GLTF format. The resulted model is 12MB gltf and 8 MB bin file. Then I tried to use the Three.js loader from the website to load it. It took more than 1 minutes to load then crashed Chrome. The example models are working fine. I am just wondering whether this is a known limitation of the Three.js loader, or it is something wrong with my model. The 27 DAE model can be loaded using the Three.js Collada Loader with about 20 seconds. Thank you very much!

**Comment by pjcozzi** [comment]
@lxspine does this model load reasonably in [Cesium's viewer](http://cesiumjs.org/convertmodel.html)?

**Comment by pjcozzi** [comment]
The latest version of the three.js loader by @cx20 works with all the sample models, see https://github.com/cx20/gltf-test
