### ISSUE TITLE
Accessor / primitive count

### ISSUE THREAD

**Issue by andrewvarga** [KhronosGroup/glTF#544]
I noticed that for a given primitive, all accessors have the same count value, which makes sense and corresponds to the spec:
https://github.com/KhronosGroup/glTF/blob/master/specification/README.md#user-content-meshes
"When the indices property is not defined, GL's drawArrays function should be used with a count equal to the count property of any of the accessors referenced by the attributes property (they are all equal for a given primitive)."

My question is, if they are all equal for a given primitive (which is logical since 1 primitive represents a draw call) then why isn't count specified for the primitive instead of being specified for each accessor?

**Comment by pjcozzi** [comment]
Accessors are also used by animations, and this allows accessors to standalone and fully describe the subset of the buffer view they reference.

**Comment by andrewvarga** [comment]
Thanks, that explains why count is part of the accessors but couldn't it be a part of the primitive too? Without that, implementations could choose the first accessor's count, which isn't very clean.

**Comment by pjcozzi** [comment]
It could I suppose, but it would be redundant.

**Comment by andrewvarga** [comment]
Yeah, but it's already redundant listing it for each accessor. But anyway it's not a big deal, I just thought to mention it as I think it would make it clearer for implementations that it's the same value for all accessors.

**Comment by pjcozzi** [comment]
Ah, I see.  Storing it in the primitive could also be redundant if two primitives use the same accessor.  In any case, this is minor enough that I would advise we break the spec over it.

**Comment by pjcozzi** [comment]
@lexaknyazev do you think we should consider this for a future spec version?

**Comment by lexaknyazev** [comment]
I think we should implement more flexible binding approach based on something like `ARB_indirect_parameters`.

**Comment by lexaknyazev** [comment]
Closing, since there's no further action here. Any advanced/indirect binding should come as an extension first.
