### ISSUE TITLE
glTF test models may contain extra unnecessary data at the begining of .bin file

### ISSUE THREAD

**Issue by shrekshao** [KhronosGroup/glTF#547]
Test with `box`, `duck`, each of them has 18, 6318 extra 4-byte-data at the begining of the .bin file. 

[Click for more details](https://github.com/WebGLSamples/WebGL2Samples/pull/95#issuecomment-195170544)

**Comment by pjcozzi** [comment]
Did you test any models that did or did not have this problem?  What format did you test?  Just glTF + separate .bin file?  Did you try embedded .bin with a data uri or binary glTF (.glb)?

@tfili any thoughts here?  This could be an important bug in COLLADA2GLTF?

**Comment by shrekshao** [comment]
The models generated by obj2gltf works fine.

The buggy models i tested are: box, duck, 2_cyclinder_engine. All in
glTF+.bin mode. I haven't tried the embedded ones yet

**Comment by pjcozzi** [comment]
Sounds like a COLLADA2GLTF bug that we'll want to fix.  Good eye, thanks for finding this.

**Comment by tfili** [comment]
I'm looking at `box.bin` and I'm not seeing a problem. The file is 840 bytes. The first 72 bytes are the indices made up by 36 `short`s (which makes sense with 2 triangles per side and the values are between 0 and 23). Then there are 2 `vec3` buffers made up 24 vertices containing positions and normals (288 bytes each), then a `vec2` buffer made of 24 texture coordinates (192 bytes).

72 + 288 + 288 + 192 = 840, so there doesn't appear to be any extra data in the model.

**Comment by pjcozzi** [comment]
@shrekshao please confirm and close this if it isn't an issue.

**Comment by shrekshao** [comment]
Oh that makes sense. It is our fault. Turns out that it is because our loader mess up with the byteoffset of the bufferview and accessor.  Thanks Tom for pointing this out for us. Really sorry about the trouble.
