### ISSUE TITLE
Move sampleModels to separate repository

### ISSUE THREAD

**Issue by MarcoHutter** [KhronosGroup/glTF#554]
The sampleModels directory may grow arbitrarily. Having to download potentially several hundred MBs just to have a look at a less-than-1MB spec is just impractical. 

(To some extent, it's already too late to fix this, as the current commits will always be part of an initial clone, but one might at least consider changing the current practice here)

**Comment by pjcozzi** [comment]
Agreed, see #502.

**Comment by MarcoHutter** [comment]
Apologies, then this is already covered by the issue you linked to, and can probably be closed.
