### ISSUE TITLE
Handling images in the embed mode

### ISSUE THREAD

**Issue by eran-pinhas** [KhronosGroup/glTF#558]
Currently the converter can handle only bin, shaders & textures. but it's possible to insert the image as `uri:"data:image/jpeg;base64,/....."`  insteat of the path. and reduce the files require to use the gltf file.

I've done that manually (and later using script) and it works great in cesium.

It also prevent the problem that the image files are not copied to the destination folder

**Comment by tfili** [comment]
Have you tried the -e option?

**Comment by eran-pinhas** [comment]
Yes I Did. it still uses the relative file path

**Comment by pjcozzi** [comment]
@eran-pinhas also try [gltf-pipeline](https://github.com/AnalyticalGraphicsInc/gltf-pipeline) after running COLLADA2GLTF.

If there is still a bug in COLLADA2GLTF, please submit to https://github.com/KhronosGroup/COLLADA2GLTF/
