### ISSUE TITLE
Ambiguous animation TIME input range across separate animation nodes

### ISSUE THREAD

**Issue by kbirk** [KhronosGroup/glTF#569]
In the `box-animated` sample model there are two animations nodes: `animation_0` and `animation_1`, each with the `Geometry-mesh020Node` node as their target.

- The rotation animation has a TIME input parameter of `[1.25, 2.5]`.
- The translation animation has a TIME input parameter of `[0, 1.25, 2.5, 3.708329916000366]`.

My viewer animation implementation takes the last value of the TIME input array and divides the current timestamp by it, using the remainder to determine which two keyframes to interpolate between for the given channel. This to me seems like the correct approach since it supports animation channels with different temporal lengths. For example, one node rotation using a `[ 0, 1]` TIME input and another rotating half the speed using a `[0, 2]` TIME input.  

This method when applied to the `box-animated` model using the two above TIME inputs results in a desync of ~1.7917 seconds per loop, which does not seem intended.

Is this simply an error in the `box-animated` model? Should the rotation channel instead contain four elements similar to the translation with the first and last values representing a rotation of 0 radians? I only make this assumption because the `monster`, `Cesium_Man`, `CesiumMilkTruck` and `brainsteam` models all animate correctly. 

Or is the way I determine the current keyframe incorrect? Should I instead assume all animations within a given 'group' share a total length? And I should use the largest TIME input value when calculating the keyframes?

**Comment by MarcoHutter** [comment]
One interpretation that worked for me (for the `boxAnimated` model - I did not yet try the other ones) was to extend the time that is covered by the animations, based on the minimum and maximum time of each animation. For the given example, the minimum and maximum time will be `0.0` and `3.708`, respectively. So the `rotation` part is interpreted as if it was `[0.0, 1.25, 2.5, 3.708]`. Times that are smaller than `1.25` or greater than `2.5` are simply mapped to the values that have been given for `1.25` and `2.5`. This results in a "reasonable" animation for the `boxAnimated` example (that is: It does what it is *likely* supposed to do). But there are still too many degrees of freedom to be sure that this is "correct".

**Comment by kbirk** [comment]
Thanks for the response. The approach you outlined seems to be the correct method for the `box-animated` sample model. 

Issue #573 you opened outlines the ambiguity exactly, which is: if I have `animation0` with a TIME input of `[0, 1]` and `animation1` with TIME input of `[0,2]`, should `animation0` loop once every 2 seconds, or twice?

**Comment by pjcozzi** [comment]
> if I have animation0 with a TIME input of [0, 1] and animation1 with TIME input of [0,2], should animation0 loop once every 2 seconds, or twice?

I believe the intention is for `animation0` to loop twice.  There is a global timeline and each animation maps to it independently.  @tparisi do you agree?

I labeled this issue as `1.0.1` to add clarity to the spec.

**Comment by kbirk** [comment]
@pjcozzi Thanks for the response.

Just to clarify your point about the global timeline. If I had the following animation inputs:

```
Animation0 = [ 0.0, 2.0 ]
Animation1= [ 2.0, 4.0 ]
Animation3 = [ 0.1, 6.0 ]

            0    1    2    3    4    5    6
Scene Time  |----|----|----|----|----|----|
Animation0  |---------|              
Animation1            |---------|   
Animation3  |-----------------------------|
```

What would be the intended behavior of Animation0 and Animation1 in this case?

**Comment by pjcozzi** [comment]
Sorry for the slow response; I have be focused on conference work, but am back now.

Ah, I see what you mean: should the spec define that, for example, `Animation0` and `Animation1` loop or clamp when outside of the `[0, 2]` and `[2, 4]` ranges, respectively?  I agree that the current spec is silent here and should be updated.

What do you suggest?

I don't think the spec can force repeat or clamp since it depends on the model/animation, e.g., walk cycle or landing gear.  The spec could say either is allowed...or, if we think it is important enough and known at converter/exporter time, we could add a property similar to texture wrap parameters.

**Comment by pjcozzi** [comment]
Also is this now duplicate with #573?

**Comment by kbirk** [comment]
Thanks for the response.

I agree that adding a property similar to the texture wrap parameters, or those found found in [Cesium's ModelAnimationLoop](https://cesiumjs.org/Cesium/Build/Documentation/ModelAnimationLoop.html) would remove the ambiguity.

I would say this is now similar enough to #573 that it could be closed.

**Comment by pjcozzi** [comment]
Agreed, closing as duplicate with #573, which is labeled for `1.0.1`.  Thanks again for the input!
