### ISSUE TITLE
uint32 indices

### ISSUE THREAD

**Issue by pixelnerve** [KhronosGroup/glTF#570]
Hello,

I've noticed that collada2gltf is splitting meshes and that accessor.componentType doesn't mention int32/uint32 types. Is there any plans to change that anytime soon ?

**Comment by lexaknyazev** [comment]
Neither WebGL 1.0, nor OpenGL ES 2.0 supports int32 indices without `OES_element_index_uint` extension. So core glTF spec doesn't mention int32 type.

**Comment by pixelnerve** [comment]
Yes. Will it be supported ? And how soon ?

**Comment by lexaknyazev** [comment]
Formally speaking, spec should already support int32 indices through extensions. It just lacks explicit examples of how to do it properly. Hope to have them with 1.0.1 update.
I wouldn't expect collada2gltf to implement that before spec update.

Maybe @pjcozzi or @lasalvavida could shed some light?

**Comment by pixelnerve** [comment]
Any pointers on how to make that work are welcome. Thanks @lexaknyazev

**Comment by pjcozzi** [comment]
As @lexaknyazev mentioned, given that uint32 indices are not in the core WebGL 1.0 spec, they would not be in the core glTF 1.0 spec.  However, the WebGL extension is widely supported and we could do a very simple glTF extension for it so a glTF renderer knows to (1) enable the WebGL extension and (2) allow uint32 as a validate datatype for indices.

@lexaknyazev or @pixelnerve would you like to try to write up the extension?  For details and examples, see the [glTF Extension Registry](https://github.com/KhronosGroup/glTF/blob/master/extensions/README.md).

**Comment by lexaknyazev** [comment]
@pjcozzi Since we don't have any formal example of WebGL extensions in glTF I've written some considerations on this topic [here (comment)](https://github.com/KhronosGroup/glTF/issues/563#issuecomment-213421633).

**Comment by pixelnerve** [comment]
32bit indices would need new data types: int32 and uint32 and disabling the splitting meshes method. Would also write the extension to the extension list.

**Comment by pjcozzi** [comment]
Related: #535

**Comment by pjcozzi** [comment]
Latest discussion is in https://github.com/KhronosGroup/glTF/issues/563#issuecomment-224095245

**Comment by pjcozzi** [comment]
See pull request #619.

**Comment by lexaknyazev** [comment]
@pjcozzi Can this issue be labeled as `resolved` or we need to wait for `collada2gltf` support?

**Comment by pjcozzi** [comment]
Let's leave as unresolved so we remember to update COLLADA2GLTF.

@lasalvavida would you like to make this change after your `i3dm` work?

**Comment by pjcozzi** [comment]
Replaced by https://github.com/KhronosGroup/COLLADA2GLTF/issues/123
