### ISSUE TITLE
Missing readme for brainsteam sample model

### ISSUE THREAD

**Issue by SaschaWillems** [KhronosGroup/glTF#572]
The [brainsteam](https://github.com/KhronosGroup/glTF/tree/master/sampleModels/brainsteam) sample doesn't contain a readme.txt (contrary to the other examples), lacking any information on usage restrictions.

**Comment by pjcozzi** [comment]
We also recently noticed this in #564 and are looking into it.

**Comment by lasalvavida** [comment]
Fixed by #626

**Comment by pjcozzi** [comment]
Thanks @SaschaWillems @lasalvavida!
