### ISSUE TITLE
Links between glTF files

### ISSUE THREAD

**Issue by MarcoHutter** [KhronosGroup/glTF#575]
The current specification for nodes refers to the children solely via IDs ( https://github.com/KhronosGroup/glTF/blob/master/specification/schema/node.schema.json#L14 ). Has it been considered to extend this, to support "embedding" glTF files in other glTF files, and to refer to these files via links (URIs)?  

I think that this might have several benefits and application cases. Consider a webshop where the product is displayed as a glTF model. Individual parts of the product may be customized - for example, the wheel rims of a car, or parts of some furniture. Right now, there would only be the options to either treat the glTF files as completely independent and manage the relationships solely in the application, or to create a single glTF file that reflects the whole model in one particular configuration (with the obvious drawbacks of the file being potentially large, resulting in long download- and parsing times). 

However, I also see that it may have drawbacks and caveats. Although the change in the spec might be minimal, the effects for the loaders might be considerable. For example, maintaining the "in-memory" representation of the model as a whole would have to take into account that "IDs" might be duplicated in the files - e.g. one file with a node named `root`, referring to another file that also contains a node named `root`. 

One could even argue that this contradicts the idea of glTF being a pure transmission format, but I'm not sure about that. So even if there are no plans right now, I'd like to know whether this could make sense for the applications foreseen for glTF. 

--- 

(Note: This question is to some extent inspired by [this stackoverflow question](http://stackoverflow.com/questions/34989434/cesium-gltf-model-hierarchy) - I was curious about that as well, and thought that I might bring it up here)

**Comment by pjcozzi** [comment]
Thanks for the input, @MarcoHutter.

This has been considered, see #37.  You are right that this has a lot of implementation implications; the proposed details are in https://github.com/KhronosGroup/glTF/issues/37#issuecomment-134750897.

If this is something you are interested in, you are encouraged to prototype some ideas and propose this as an extension.

(Also perhaps close this issue as a duplicate and continue discussion in #37 if you agree).

**Comment by MarcoHutter** [comment]
Sure, and apologies for the duplicated issue(s). (I shouldn't have trusted the issue search results, e.g. for the word "links"...)
