### ISSUE TITLE
GLTF Loader is not working in Safari (OSX/iOS)

### ISSUE THREAD

**Issue by tizzle** [KhronosGroup/glTF#578]
When visiting [the GLTFLoader example](http://threejs.org/examples/webgl_loader_gltf.html) on the threejs.org with Safari on my MacBook or on an iOS device, the models are not displayed properly.

When testing i ran into several issues, ranging from 
```Float32Array — glTFLoader.js:617 RangeError: Length out of range of buffer``` to 
```cleanup — webgl_loader_gltf.html:556 TypeError: null is not an object (evaluating 'gltf.animations')```.

Then i tried breaking the example down and got a different error: 
```value — glTFLoader.js:916:101 TypeError: undefined is not an object (evaluating 'ptype')```

Can you reproduce any of this?

Thanks a lot for your help and keep up the great work!

Cheers

Till

**Comment by tizzle** [comment]
I just saw there is a pull request over at three.js on this:
https://github.com/mrdoob/three.js/pull/9721

**Comment by pjcozzi** [comment]
OK to close this?

**Comment by tizzle** [comment]
It was merged to dev branch and should be in three.js master within a few weeks. Ok, to close, then. Thanks!
