### ISSUE TITLE
three.js glTF Loader - glTF models cannot be copied or cloned

### ISSUE THREAD

**Issue by kkananen** [KhronosGroup/glTF#591]
...continuing from three.js issue https://github.com/mrdoob/three.js/issues/8869 

I've patched up the three.js r76 glTF loader to behave (slightly) better in vizor.io editor (where we need to clone() whole hierarchies of objects loaded from glTFs).

A diff between our changes and the main glTF repo (this is a half-way-house at best and is still hacky but resolves the main issues): https://github.com/KhronosGroup/glTF/compare/master...vizorvr:vizor?expand=1
(a slightly easier to read diff against three.js: https://github.com/mrdoob/three.js/compare/master...vizorvr:master-glTF-changes?expand=1)
Main differences to the original are:
- glTFLoader can load() more than one item at a time (a load is executed in a THREE.glTFLoadContext [new class])
- we let THREE.js SkinnedMesh create the bones (in the modified version we ignore the THREE.Bone instances created by glTFLoader) 
- added rebind methods to both glTFAnimator and glTFShaders, which we call manually when copying/cloning glTF-loaded meshes. These rebind new animations/shaders correctly to the new object hierarchy

This still requires quite a bit of work:
- better control of animation timing on per-object-basis, i.e. feed the animation time to the object on update
- Ideally the engine (in our case, the vizor.io editor) should not have to know that objects are loaded from glTF, i.e. animations should follow three.js patterns as much as possible (= remove the need to call update on animations&shaders manually)
- lots of clean up, there is quite a bit of redundant data in the glTF loading process now (e.g. THREE.Bone instance which are ignored)

My primary concern is that I'd like to avoid our implementation diverging from the Kronos one. I've noticed there's already a glTFLoader2.js in the Kronos repo and I'd like to bring the implementations together so that we avoid doing the work twice. I can dedicate some time for this but can't make huge promises. 

Would be good to know your plans and if the changes make sense. 

ping @tparisi

**Comment by pjcozzi** [comment]
@tparisi what do you think?  I am not closely involved here, but +1 from me for @kkananen's potential contributions!

**Comment by pjcozzi** [comment]
@cx20 is this still an issue?  If so, should this be submitted to the three.js repo?

**Comment by pjcozzi** [comment]
Also asked in #683.

**Comment by emackey** [comment]
@pjcozzi your question is for @richtr.

**Comment by proteamer** [comment]
Yes, It's still actual issue.

**Comment by pjcozzi** [comment]
@proteamer can you please submit an issue to the three.js repo since that is appropriate place?

**Comment by donmccurdy** [comment]
We are tracking this on three.js here: https://github.com/mrdoob/three.js/issues/8869

Likely have better luck with `mesh.clone()` if you're using the `KHR_materials_common` extension, rather than GLSL. More examples of the problem (other than the known GLSL thing) are helpful, @proteamer. Thanks!

**Comment by pjcozzi** [comment]
@donmccurdy OK to close this issue in the glTF repo?

**Comment by donmccurdy** [comment]
Yes, there is now a more recent issue on the three.js repo: https://github.com/mrdoob/three.js/issues/11573
