### ISSUE TITLE
Spec inaccurately lists JOINTMATRIX as an attribute semantic

### ISSUE THREAD

**Issue by lasalvavida** [KhronosGroup/glTF#592]
In the [spec](https://github.com/KhronosGroup/glTF/tree/master/specification#parametersemantic), the semantic JOINTMATRIX is listed with the attribute semantics, but in the [CesiumMan](https://github.com/KhronosGroup/glTF/blob/0dd42b0c5e6db4c1eb7571739d01302cc40040ad/sampleModels/CesiumMan/glTF/CesiumMan.gltf#L2139) sample model, it is used as a uniform semantic.

I suspect the spec just needs a fix, @pjcozzi?

**Comment by pjcozzi** [comment]
Good catch, thanks @lasalvavida!  Can you please open a PR to fix the spec?  This can be into master since it is a spec bug fix.
