### ISSUE TITLE
Require accessor min/max for POSITION?

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#593]
See https://github.com/AnalyticalGraphicsInc/cesium/issues/3925

**Comment by pjcozzi** [comment]
Labeling as resolved.  See fdf433752303593af461e565ee6efd035c318637 in the `1.0.1` branch.

**Comment by lexaknyazev** [comment]
Just to be clear, why are `min|max` always required in https://github.com/KhronosGroup/glTF/commit/fdf433752303593af461e565ee6efd035c318637, not just for `POSITION`?
Are there any common use cases for `NORMAL` or `TEXCOORD`?

**Comment by lexaknyazev** [comment]
One more possibly worth mentioning constraint: `min|max` length must be one of [1, 2, 3, 4, 9, 16] and match accessor's `type`.

**Comment by pjcozzi** [comment]
> One more possibly worth mentioning constraint: min|max length must be one of [1, 2, 3, 4, 9, 16] and match accessor's type.

See #617.

> Just to be clear, why are min|max always required in fdf4337, not just for POSITION?
Are there any common use cases for NORMAL or TEXCOORD?

This is for simplicity and consistency.  Early on, we received some glTF feedback that *all* properties should be required.  We didn't agree as it can make things verbose; however, experience has shown that having some optional and some required properties has caused some implementation confusion for clients - which goes against one of our main goals: making glTF easy to implement consistency.  So I think requiring `min`/`max` only for `POSITION` starts to make the required/optional rules too complex and could lead to a less robust ecosystem.

**Comment by lexaknyazev** [comment]
> So I think requiring min/max only for POSITION starts to make the required/optional rules too complex and could lead to a less robust ecosystem.

I was curious because of opposite approach in [#616 (diff)](https://github.com/KhronosGroup/glTF/pull/616/files#diff-b20cdac71cf65c6672d2cc43c3f88861R94).

**Comment by pjcozzi** [comment]
Ah, yes, I think we should make [#616 (diff)](https://github.com/KhronosGroup/glTF/pull/616/files#diff-b20cdac71cf65c6672d2cc43c3f88861R94) apply to all attributes, not just `POSITION`.

@mlimper @lasalvavida what do you think?

>> Just to be clear, why are min|max always required in fdf4337, not just for POSITION?
Are there any common use cases for NORMAL or TEXCOORD?

> This is for simplicity and consistency. Early on, we received some glTF feedback that all properties should be required. We didn't agree as it can make things verbose; however, experience has shown that having some optional and some required properties has caused some implementation confusion for clients - which goes against one of our main goals: making glTF easy to implement consistency. So I think requiring min/max only for POSITION starts to make the required/optional rules too complex and could lead to a less robust ecosystem.

**Comment by mlimper** [comment]
It doesn't seem like a huge amount of work for implementers of glTF writers if we require them to also write min/max for other attributes, given that they would already provide this information for POSITION.
On the client side, requiring min/max will facilitate implementation... although I must admit that I currently don't have any important real-world use case in mind where one would need min/max for normals / texcoords. Maybe you could figure out that you are looking at an object where everything is viewed from the back (using normal min/max) and then not render it, if backface culling would be enabled?^^
To conclude, I would tend towards making min/max required for all attributes, for simplicity.

**Comment by pjcozzi** [comment]
Thanks for the input, @mlimper!

@lexaknyazev are you good with this?  The WEB3D_quantized_attributes spec will also go this direction.

**Comment by lexaknyazev** [comment]
> @lexaknyazev are you good with this? The WEB3D_quantized_attributes spec will also go this direction.

Consistency matters. 

> On the client side, requiring min/max will facilitate implementation

Validation will be simplier too.

**Comment by pjcozzi** [comment]
Thanks for the prompt response! :smile:

**Comment by pjcozzi** [comment]
Updated in #826
