### ISSUE TITLE
Add indices

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#60]
Since glTF requires indices (CC #14), the converter needs to add indices for non-indexed:
- `lines`
- `linestrips`
- `triangles`
- `trifans`
- `tristrips`

See the Geometry section of the [COLLADA spec](http://www.khronos.org/files/collada_spec_1_5.pdf)

**Comment by pjcozzi** [comment]
@tfili how hard is this to add to the converter?  Or perhaps we just not require indices in glTF, which would be trivial for the client, and better for point and line primitives.

**Comment by tfili** [comment]
I'd have to look at the code but I don't think it would be that hard. But if it's easy for the client to support and had a benefit, why not allow it?

**Comment by pjcozzi** [comment]
I am OK with not requiring indices in glTF.  @tparisi?

**Comment by tparisi** [comment]
Requiring indices for non-indexed is wasteful; remember we're also trying to be efficient for transmission.

Do we have a clear proposal for non-indexed types?

**Comment by pjcozzi** [comment]
> Do we have a clear proposal for non-indexed types?

`mesh.primitive.indices` (see [here](https://github.com/KhronosGroup/glTF/blob/master/specification/meshPrimitive.schema.json#L16) in the schema) would not be required in which case, the runtime would use `drawArrays`, not `drawElements`.  I have to take a closer look to see where we would get the `offset` and `count` properties for `drawArrays` (probably as optional properties on `mesh.primitive`) since they would no longer come from the accessor.  I'll follow-up with an example.

**Comment by mlimper** [comment]
Within our [SRC Paper](http://x3dom.org/src/files/Web3d2014_SRC.pdf), we used `count` for all accessors, but we didn't consider offset at that point (see the example JSON at the end of the paper).

**Comment by pjcozzi** [comment]
@mlimper are you suggesting that we simply make `mesh.primitive.indices` optional, and when it is not provided, then the `count` from any `accessor` referenced from the primitive's `attributes` (which is the same for all of them) can be used in a call to `drawArrays` with `offset = 0`.

I think that would work just fine.  Please confirm.

**Comment by mlimper** [comment]
> I think that would work just fine. Please confirm.

Yes, confirmed! Thanks for the clarification.

**Comment by pjcozzi** [comment]
I updated the draft 1.0 schema in 740ac80e8958ec5cff50e31123abb77d9475f436.

@tfili I'm leaving this issue open and labeled as `converter` so you can update the converter (and Cesium loader).

@tparisi here's some text for the draft 1.0 spec (perhaps as an **Implementation Note**):

---

## Primitive

Each `primitive` in `mesh.primitives` corresponds to one WebGL draw call (engines are, of course, free to batch draw calls).  When `primitive.indices` is defined, it references the accessor to use for index data, and GL's `drawElements` function should be used.  When `primitive.indices` is not defined, GL's `drawArrays` function should be used with a `count` equal to the `count` property of any of the accessors referenced by `primitive.attributes` (they are all equal for a given primitive).

**Comment by pjcozzi** [comment]
@tparisi I'm leaving this open and labeled `converter` for the converter changes.

**Comment by pjcozzi** [comment]
Discussed this with @tfili.  It could be a few days due to an OpenCOLLADA issue so the converter work here may get pushed post 1.0 since these models are not common in the wild.

**Comment by RemiArnaud** [comment]
Is there an OpenCOLLADA Pull Request ?

**Comment by pjcozzi** [comment]
@tfili I am fine with dropping the `post 1.0` label from this, updating the limitations wiki, and just doing it when it becomes priority.

If you agree, please remove the label and update the wiki.

**Comment by pjcozzi** [comment]
@tfili can you confirm that we can close this now since `indices` are not required?

**Comment by pjcozzi** [comment]
No longer an issue.  `indices` are not required.

See https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/mesh.primitive.schema.json#L16
