### ISSUE TITLE
Load glTF using OpenGL

### ISSUE THREAD

**Issue by fxkulou** [KhronosGroup/glTF#602]
I used the gltfLoader tool(C#),and I found that the method "LoadModel"  can get the gltf model,but I don't know how to draw the model by OpenGL,I didn't find any Coordinates in the gltf model,so I need some help,please!

**Comment by pjcozzi** [comment]
@MattMcMullan created the C# loader and may have some ideas for you.

**Comment by pjcozzi** [comment]
@sbtron sounds like a feature request for a sample renderer built on https://github.com/KhronosGroup/glTF-CSharp-Loader?

Nothing yet AFAIK: https://github.com/KhronosGroup/glTF#c-1

**Comment by donmccurdy** [comment]
Closing as this can be tracked in other repos.
