### ISSUE TITLE
Spec changes from 1.0 to 2.0

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#605]
This issue will be updated as we work on the 1.1 spec (also see the spec pull request, #784)

**1.0.1/1.1 was renumbered to 2.0**

**JSON format changes:**
- Removed indirection from `animation`: `sampler` now refers directly to accessors, #712 
- `material.parameter.value` and `technique.parameter.value` must be an array, #690
- Node can have only one mesh #821
- Top-level JSON objects are arrays now
- Added reqs on JSON encoding
- Added reqs on binary data alignment https://github.com/KhronosGroup/glTF/issues/802#issuecomment-270406859

**Additions:**
- Added `accessor.normalized`, #691, #706
- Added `"STEP"` as valid `animation.sampler.interpolation` value, #712 
- Added `glExtensionsUsed` property and `5125` (UNSIGNED_INT) `accessor.componentType` value, #619
- Added `extensionsRequired` property, #720, #721

**Removals:**
- Removed revision number from `profile.version`, #709
- Removed `buffer.type`, #786, #629
- Removed `technique.functions.scissor` and removed `3089` (`SCISSOR_TEST`) as a valid value for `technique.states.enable`, #681 
- Techniques, programs, and shaders were moved out to KHR_technique_webgl extension.

**Other edits:**
- `asset` is now required, #642
- `accessor.min` and `accessor.max` are now required, #593, and clarified that the JSON value and binary data must be the same, #628.
- Clarified `animation.sampler` and `animation.channel` restrictions, #712 
- `buffer.byteLength` and `bufferView.byteLength` are now required, #560.
- `skin.inverseBindMatrices` is now optional, #461.
- Attribute parameters can't have a `value` defined in the `technique` or `parameter`, https://github.com/KhronosGroup/glTF/issues/563#issuecomment-223155322.
- Only `TEXCOORD` and `COLOR` attribute semantics can be written in the form `[semantic]_[set_index]`, https://github.com/KhronosGroup/glTF/issues/563#issuecomment-223270789.
- `TEXCOORD` and `COLOR` attribute semantics **must** be written in the form `[semantic]_[set_index]`, e.g., just `TEXCOORD` should be `TEXCOORD_0`, and just `COLOR` should be `COLOR_0`, #649
- `camera.perspective.aspectRatio` and `camera.perspective.yfov` must now be `> 0`, not `>= 0`, https://github.com/KhronosGroup/glTF/issues/563#issuecomment-218789988.
- Application-specific parameter semantics must start with an underscore, e.g., `_TEMPERATURE` and `_SIMULATION_TIME`, https://github.com/KhronosGroup/glTF/issues/563#issuecomment-223391315.
- Properties in `technique.parameters` must be defined in `technique.uniforms` or `technique.attributes`, 
  https://github.com/KhronosGroup/glTF/issues/563#issuecomment-223148438.
- `technique.parameter.count` can only be defined when the semantic is `JOINTMATRIX` or an application-specific semantic is used.  It can never be defined for attribute parameters; only uniforms, d2f69457dc46a9c00307c27faf9e4cde4a5896d0
- `technique.parameter.semantic` is required when the parameter is an attribute, 28e113d277002404803b7618d86c1fc7caf71dd8
- Mesh-only models are allowed, e.g., without materials, #642
- Skeleton hierarchies (nodes containing jointName) must be separated from non-skeleton hierarchies., #647
- `technique.states.functions.blendColor` and `technique.states.functions.depthRange` parameters now must match WebGL function min/max, #707

For upcoming 2.0 changes, see [issues labeled "2.0" and not labeled "resolved"](https://github.com/KhronosGroup/glTF/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A2.0+-label%3Aresolved).

For all 2.0 issues, see [issues labeled "2.0"](https://github.com/KhronosGroup/glTF/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A2.0).

**Comment by javagl** [comment]
Apologies for bringing this up so late, but now that 1.1 is about to be finalized, I think that this is becoming increasingly important (and it's also relevant for all future updates of the spec).

I think we should *carefully* think about how to handle backwards compatibility. Right now, I see two (related) points that could severely affect backward compatibility:
- Removing properties
- Removing valid values of properties

For example, one change for 1.1 was the [removal of `technique.states.functions.scissor`](https://github.com/lexaknyazev/glTF/commit/991e99211e7c50664dde8ae48503c576d331d61b#diff-bda8893044dd126d0fdcfc2b9274465a). The `technique.states.functions` object contains the setting `"additionalProperties" : false`. This means that [such an object is not allowed to have any property that is not explicitly listed in the properties](http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.18). The problem I see here is that a loader that strictly obeys the schema would be allowed to report an error when it encounters such a `scissor` property. Given the schema, it does not know that this property was allowed in an earlier version. 

The point is: **A JSON that was valid in 1.0 is plainly *invalid* in 1.1.** 

(And this obviously cannot be solved by checking the `asset.version`...)

One strategy to handle this is to *never remove properties*. This is also suggested in [this stackoverflow answer](http://stackoverflow.com/a/13945074). I know that this has the potentially undesirable side-effect of keeping "deprecated" or "legacy" properties throughout the different versions. But I'm not sure whether there are better solutions for this...

--- 

Side notes:

- Yes, I know that this is not a problem for a JavaScript-based loader. The lax type checking will usually just throw the unknown properties into the resulting JSON object, and not cause any errors. *Users* of the resulting objects may have to insert something like an `if (defined(function.scissor)) { versionIs_1_0(): }` here and there. This is not nice either, but not as critical as in other contexts.

- The point *"Removed buffer.type, #786, #629"* is currently not implemented, as far as I see. Only the allowed value `text` was removed. Both are similarly critical in the sense that I described above.

- Related: https://github.com/javagl/JglTF/issues/5 . This, of course, is my problem, and this alone should not affect any decisions here. But the general question of backward compatibility should be tackled nevertheless.

**Comment by pjcozzi** [comment]
@javagl moving this discussion to #806 to keep this issue focused on changes from 1.0 to 1.1.

**Comment by pjcozzi** [comment]
@lexaknyazev can you please make sure this is up-to-date for GDC next week...including as we make changes?

**Comment by pjcozzi** [comment]
@lexaknyazev @bghgary @sbtron can you please update this 1.0 to 2.0 summary once the spec stabilizes?

**Comment by javagl** [comment]
Here are some points that I stumbled over while running a code generator (and 1.0-to-2.0 converter) against the 2.0 schema. I'm not sure whether they should be mentioned here (some of them may already be covered by links to issues where they are discussed), but I'll just drop this list here, and remove this comment later, if desired.

- The `asset.profile` and `asset.premultipliedAlpha` properties have been removed. 
- The `byteStride` property was moved from `accessor` to `bufferView` (https://github.com/KhronosGroup/glTF/issues/827 , https://github.com/KhronosGroup/glTF/pull/833 )
- The `animation.channel.target.id` was renamed to `animation.channel.target.node` ( https://github.com/KhronosGroup/glTF/commit/de1023f1c5a5d4e04744c26acbf2ddc6f8063971 - I think this was raised as an issue originally, but have to look closer)
- The `skin.bindShapeMatrix` has been removed. It is now assumed to be pre-multiplied with the mesh or the inverse bind matrices (https://github.com/KhronosGroup/glTF/issues/723, https://github.com/KhronosGroup/glTF/commit/6c4189946652e22742f0fe7892edf992c8552af1)

**Comment by pjcozzi** [comment]
@javagl just curious, what 1.0 to 2.0 converter are you using?  We would welcome your use and contributions to https://github.com/AnalyticalGraphicsInc/gltf-pipeline/pull/191

**Comment by mastayoda** [comment]
Hello @pjcozzi , is the  AnalyticalGraphicsInc/gltf-pipeline tool generating gltf 2.0 already? I can't find clear information in the repo of which version is using. Thanks in advance!

**Comment by pjcozzi** [comment]
@mastayoda there is initial work for a 1.0 to 2.0 conversion stage in gltf-pipeline in https://github.com/AnalyticalGraphicsInc/gltf-pipeline/pull/191, but it needs to be updated to include the latest 2.0 changes.  Contributions are welcome!

**Comment by mastayoda** [comment]
Thanks so much @pjcozzi ! I will contribute for sure! Our company is trying to move away from the 3D mesh format mess and we are loving gltf so far. We will be jumping into the Blender export/import project soon to support 2.0

**Comment by javagl** [comment]
Referring to the comment above (i.e. to keep this issue focussed on the changes), only the short answer: I internally created a small converter in JglTF, for "1.0" -> "2.0+Technique" conversion, but there are still many open issues, and it's probably worthwhile to focus on the official glTF tools for contributions.

**Comment by pjcozzi** [comment]
This all sounds great, @mastayoda and @javagl!

**Comment by pjcozzi** [comment]
@javagl or @sbtron any chance one or both of you want to update this?  Someone asked on gitter and this would also be useful for the COLLADA2GLTF/gltf-pipeline/obj2gltf/Cesium updates.

**Comment by javagl** [comment]
I can run the code generator on the latest (final) schema, and see whether the compiler complains at a certain point. This may not cover all changes (particularly not necessarily the *semantics* of changes), but could be a starter (in addition to my comment above https://github.com/KhronosGroup/glTF/issues/605#issuecomment-294300839 )

**Comment by pjcozzi** [comment]
Sounds like a great start, @javagl!  You are right that there will be many more subtle changes as well.

**Comment by javagl** [comment]
In the initial comment above, I don't see things like morph targets, PBR or the `CATMULLROMSPLINE` and `CUBICSPLINE` interpolation methods for `animation.sampler` being mentioned... (some of them may be "too big to be called a 'spec change'", though...)

After re-generating the code based on the latest schema, the following changes appeared in the diff (in addition to the points that I mentioned [above...](https://github.com/KhronosGroup/glTF/issues/605#issuecomment-294300839) )

* The `animation.channel.target.node` is now *optional* (to allow other targets in the future), as of https://github.com/KhronosGroup/glTF/commit/3d3db0455790d510e23505cd30da270c92502f43  

* The point from the initial comment 

    > accessor.min and accessor.max are now required, #593, and clarified that the JSON value and binary data must be the same, #628.

    is no longer true: They are optional now, as of https://github.com/KhronosGroup/glTF/commit/9de934af2d0c2e8d2dadb3c2f12d1c98510906ee (I found some related discussions, but not where the decision was made, @lexaknyazev )

* The maximum value of `bufferView.byteStride` has been changed from 255 to 252 in https://github.com/KhronosGroup/glTF/commit/6e6ae374e9e15a9b50960cead9d0888501fccf7a (not sure why...)

* For `camera.orthographic`, the `zfar` value must be greater than `znear`, as of https://github.com/KhronosGroup/glTF/commit/0b3dbdd23acbb7d92385967f8c31433469ff6475 

* node.children, scene.nodes, and skin.joints can't be empty when defined, as of https://github.com/KhronosGroup/glTF/commit/f44c3bd07a3425fc3458ff7892949121c5ce8867

* The components of the `node.rotation` quaternion must be in the range [-1,1], as of https://github.com/KhronosGroup/glTF/commit/75be81ffd59625abd36ff437a4e9a354f0f9b6fe

**Comment by lexaknyazev** [comment]
@javagl
- Accessors bounds are required only for positions (incl. morphs) and animation inputs. They don't make much sense for other cases.
- `byteStride` must be divisible by 4. So it can't be 253, 254, or 255.

**Comment by pjcozzi** [comment]
@javagl thanks for the input, you are very welcome to create a comprehensive 1.0 to 2.0 changelog as this one is clearly out-of-date.

**Comment by javagl** [comment]
`bufferView.byteOffset` and `accessor.byteOffset` are now optional, with 0 being the default.

(Yes, the TODO of creating a change log is still implicitly pending)

**Comment by pjcozzi** [comment]
I think it is OK to close this since there is no action here.

**Comment by pjcozzi** [comment]
@javagl a complete 1.0 to 2.0 list is still welcome if you have the bandwidth.
