### ISSUE TITLE
WEB3D_quantized_attributes decodedMax/decodedMin/decodeMatrix constraints

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#610]
@mlimper @lasalvavida what do you think about this feedback from @lexaknyazev (originally in #563)?

* [ ] 1. Should `decodedMax` and `decodedMin` array lengths be aligned with accessor's `type`?
* [ ] 2. Can we enforce `decodeMatrix` length to be just one of [4, 9 16] instead of [1-16]?

**Comment by lasalvavida** [comment]
I agree with both of these

**Comment by pjcozzi** [comment]
Sounds great, thanks for the fast response!

@lasalvavida can you open a pull request to update the extension spec?

**Comment by lasalvavida** [comment]
@pjcozzi Can we close this?

**Comment by pjcozzi** [comment]
Yes, fixed in #616.
