### ISSUE TITLE
Tessellate splines

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#62]
Not important for glTF 1.0 IMO.

Since glTF does not support spline geometry directly, the converter should tessellate splines into explicit geometry.

See Chapter 4 of the [COLLADA spec](http://www.khronos.org/files/collada_spec_1_5.pdf).

**Comment by pjcozzi** [comment]
How often are COLLADA splines used in practice?  We have not run into one of these models in Cesium.  Perhaps we just close this?

**Comment by RemiArnaud** [comment]
Honestly, I don't see the need for splines in a run-time format.

**Comment by pjcozzi** [comment]
Good point @RemiArnaud.
