### ISSUE TITLE
CityGML to glTF - geometry imprecision and feedback

### ISSUE THREAD

**Issue by anetefr** [KhronosGroup/glTF#621]
Hi all,
I spent quite some time playing with this useful conversion. I was converting CityGML to glTF (via COLLADA) by using CityGML2glTF (C2G) which is a .bat assembled by these tools. 

I came across a number of happenings, so here they are as a feedback. 
- Conversion didnt work because there was a three-point WallSurface. After it was removed process was ok.

- Some other geometry imperfections that were in the same building set, were not an issue. So some geometry issues are important in this process, and some are not. 

- As a control I introduced similar point errors and run a conversion. It worked even when the WallSurface was distorted beyond recognition. Which means there is  cache or something similar. Is there? 

- Error log (path:  does not exists or is not .....) is rather confusing to find a problem.

**Comment by pjcozzi** [comment]
@anetefr thanks for the feedback.  Sounds like a cool project.  Is CityGML2glTF open-source?

Do you know if these issues are in the CityGML to COLLADA conversion or in the COLLADA to CityGML conversion?  If the later, is the COLLADA is valid (e.g., loads in Mac Preview or Visual Studio)?

**Comment by anetefr** [comment]
@pjcozzi  Yes, its open - [https://github.com/900k/CityGML2glTF] . It essentially uses tools from Khronos group, just have them streamlined in a batch file. 

The issues seem to be in CityGML - COLLADA step. The whole process goes like this: CityGML -> COLLADA -> glTF.  Its not meant to convert other way around.

**Comment by pjcozzi** [comment]
The glTF folks did not write the CityGML to COLLADA converter; can you submit bugs to that project?

**Comment by anetefr** [comment]
2016-06-08 18:37 GMT+02:00 Patrick Cozzi <notifications@github.com>:

**Comment by anetefr** [comment]
ok, my mistake then! Thanks for letting me know!

2016-06-09 9:01 GMT+02:00 Anete Fridrihsone <anete.fridrihsone@gmail.com>:
