### ISSUE TITLE
Tightening up skinning

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#624]
Relevant parts of `RiggedSimple.gltf` (all default values omitted), issues below:

``` js
{
  "nodes": {
    "Armature": {
      "children": ["Bone"]
    },
    "Bone": {
      "children": ["Bone_001"],
      "jointName": "Bone"
    },
    "Bone_001": {
      "jointName": "Bone_001"
    },
    "Cylinder": {
      "meshes": ["Cylinder-mesh"],
      "skeletons": ["Bone"],
      "skin": "Armature_Cylinder-skin"
    },
    "node_4": {
      "children": ["Armature", "Cylinder"],
      "matrix": [/*Y_UP_Transform matrix*/]
    }
  },
  "skins": {
    "Armature_Cylinder-skin": {
      "inverseBindMatrices": "IBM_Armature_Cylinder-skin",
      "jointNames": ["Bone", "Bone_001"]
    }
  },
  "techniques": {
    "technique0": {
      "parameters": {
        "joint": {
          "semantic": "JOINT",
          "type": 35666
        },
        "jointMat": {
          "count": 2,
          "semantic": "JOINTMATRIX",
          "type": 35676
        },
        "weight": {
          "semantic": "WEIGHT",
          "type": 35666
        }
      }
    }
  }
}
```
1. Here we have one geometry node (`"Cylinder"`) and a skeleton node tree (`"Armature" -> "Bone" -> "Bone_001"`). Can any node from skeleton tree have `meshes`, `skeletons`, `camera` or `skin` properties?
2. Spec [says](https://github.com/KhronosGroup/glTF/tree/1.0.1/specification#skin-instances): 
   
   > The `skeletons` property contains one or more skeletons, each of which is the root of a node hierarchy.
   
   A top-level node of that tree is `"Armature"` not `"Bone"`. Is it a converter bug? If not why do we need that empty unused `"Armature"` node with one child?
3. Spec [spells](https://github.com/KhronosGroup/glTF/tree/1.0.1/specification#nodeskeletons) `skin.joints` instead of `skin.jointNames`.
4. Namespace of `node.jointName`. If it's glTF global, why not use `id` instead? If it is skeleton-tree limited, it can cause conflicts when `node.skeletons` contains two trees with the same `jointName`'s inside.
5. Unlike updated gltfOverview (which is really great) spec doesn't mention connections between `JOINT` attribute, indices of `JOINTMATRIX` uniform array and the order of `jointName`'s in `skin.jointNames` (same clarification about `inverseBindMatrices`).
6. Spec [says](https://github.com/KhronosGroup/glTF/tree/1.0.1/specification#geometry-and-meshes)
   
   > A node can either contain meshes or a single skinned mesh instance, but not both.
   
   Does it mean that `node.meshes.length` equals `1` when `node.skin` is defined?
7. Spec [says](https://github.com/KhronosGroup/glTF/tree/1.0.1/specification#skinjointnames-white_check_mark)
   
   > The array length is the same as the `count` property of the `inverseBindMatrices` accessor (when defined), and the same as the length of any skeleton array referencing the skin.
   
   Maybe wording can be refined here, because it's `node` what references the `skin` and a skeleton array. While "length of skeleton array" means total quantity of all nodes with `jointName` field from node-trees referenced in `skeletons` array.
8. Must all nodes in skeleton tree have `jointName` property?
9. Can `skin.jointNames.length` be less than `parameter.count` for JOINTMATRIX parameter? It can allow models with different skins have the same shader program.

**Comment by javagl** [comment]
Just minor remarks:

2. The Armature is likely a leftover from the Blender export, where "The Armature" has a special meaning: https://www.blender.org/manual/rigging/armatures/introduction.html - It's also contained in the original DAE: https://github.com/KhronosGroup/glTF/blob/master/sampleModels/RiggedSimple/collada/riggedSimple.dae#L191 

3. This is (fortunately) only the readme. The spec is right ( https://github.com/KhronosGroup/glTF/blob/1.0.1/specification/schema/skin.schema.json#L22 ) but it should be fixed in the readme as well. 

8. The description of `jointName` says *"Name used when this node is a joint in a skin"* sounds like it is not strictly necessary (only, obviously, when the node really is referred to in the `skin.jointNames`). Based on this description, it should be possible to have a skeleton like 

    nodeWithJointNameA -> nodeWithoutJointName -> nodeWithJointNameB

when the middle one is simply not needed in the skin, but this could indeed be stated more clearly.

---

(Side note: I appreciate the diligent care and efforts that you put into your issue descriptions!)

**Comment by lexaknyazev** [comment]
> Based on this description, it should be possible to have a skeleton like
`nodeWithJointNameA -> nodeWithoutJointName -> nodeWithJointNameB`
when the middle one is simply not needed in the skin, but this could indeed be stated more clearly.

I think in that case it makes sense to apply skeleton node constraints (see 1.) also to such `nodeWithoutJointName`.

**Comment by javagl** [comment]
I'm not sure about this. Right now, there seem to be no such constraints in the spec. One could argue that if someone wants to attach a `mesh` and a `camera` to the hand-skeleton-node of an animated figure (to model a camcorder), then he has the option to do so  - otherwise, he would have to duplicate the node structure, including the animations etc., which isn't desirable either. 

(Sure, imagining real application cases for a `skin` **in** a skeleton node is much harder. And in general, I agree that arbitrarily mixing a scene structure and a skeleton structure could become messy and confusing. But am not sure whether this should really strictly be forbidden via the spec)

**Comment by lexaknyazev** [comment]
> One could argue that if someone wants to attach a `mesh` and a `camera` to the hand-skeleton-node of an animated figure 

Camcorder case looks interesting. I think it will be better to append a child node with `mesh` and `camera` to hand-skeleton-node. Otherwise we won't have a `matrix` to control attached `mesh`.

**Comment by lexaknyazev** [comment]
> (Sure, imagining real application cases for a `skin` in a skeleton node is much harder. And in general, I agree that arbitrarily mixing a scene structure and a skeleton structure could become messy and confusing. But am not sure whether this should really strictly be forbidden via the spec)

I'm trying to look at this in the context of interoperability. If such cases are allowed the spec should define how to treat them, so different runtimes could render the same asset correctly. Otherwise `skin` in skeleton nodes should be forbidden.

There is always an `extra` property for application-specific usage.

**Comment by pjcozzi** [comment]
Thanks for the careful writeup, @lexaknyazev.

Also, thanks for the input @javagl.

> 1. Can any node from skeleton tree have meshes, skeletons, camera or skin properties?

I don't think the spec is explicit enough here, what do you suggest?

> 2. A top-level node of that tree is "Armature" not "Bone". Is it a converter bug? If not why do we need that empty unused "Armature" node with one child?

As @javagl said, I suspect this is extra data from the converter/source-data and that `"Bone"` could be referenced directly.

> 3. Spec spells skin.joints instead of skin.jointNames.

This is a mistake; `joints` was the old name.  Can you please open a PR into master to fix this?

> 4. Namespace of node.jointName. If it's glTF global, why not use id instead? If it is skeleton-tree limited, it can cause conflicts when node.skeletons contains two trees with the same jointName's inside.

I believe it is global.  I actually suggested using `id` at one point, see #216.  Given this, what do you suggest?

> 5. Unlike updated gltfOverview (which is really great) spec doesn't mention connections between JOINT attribute, indices of JOINTMATRIX uniform array and the order of jointName's in skin.jointNames (same clarification about inverseBindMatrices).

Can you open a PR into master to detail this?

> 6. Does it mean that node.meshes.length equals 1 when node.skin is defined?

Yes, can you please open a PR into master if you think this should be more explicit?

> 7. Maybe wording can be refined here, because it's node what references the skin and a skeleton array. While "length of skeleton array" means total quantity of all nodes with jointName field from node-trees referenced in skeletons array.

Agreed.  PR into master please? :)

> 8. Must all nodes in skeleton tree have jointName property?

Yes, at least this is what Cesium assumes: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Model.js#L1776-L1795

We could clarify in the 1.0.1 spec.

> 9. Can skin.jointNames.length be less than parameter.count for JOINTMATRIX parameter? It can allow models with different skins have the same shader program.

Sounds OK to me for 1.0.1.

**Comment by javagl** [comment]
> Yes, at least this is what Cesium assumes: https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Scene/Model.js#L1776-L1795

I'm not a JS expert, but from a quick glance at this code part, it seems that this is only used to find one *particular* node in the skeleton hierarchy - namely, one that is referred to via its `jointName` in the skin. So in a skeleton like `nodeWithJointNameA -> nodeWithoutJointName -> nodeWithJointNameB`, this function could be used to find the `nodeWithJointNameB`. (If I understood the quesiton correctly, it was about whether the `nodeWithoutJointName` may appear in a skeleton hierarchy *at all*).

**Comment by lexaknyazev** [comment]
>> Can any node from skeleton tree have meshes, skeletons, camera or skin properties?

> I don't think the spec is explicit enough here, what do you suggest?

First suggestion was to separate skeleton nodes from all others by forbidding `camera`, `skeletons`, `skin`, `meshes` fields in any node in a skeleton tree. COLLADA spec has `node.type` which can be `NODE` **or** `JOINT` with no further explanation. Camcorder case by @javagl looks interesting. Maybe, a non-joint node could be allowed in a skeleton tree for such case. This will make runtime a bit more complicated, though. @pjcozzi what do you think?

---

>> A top-level node of that tree is "Armature" not "Bone". Is it a converter bug? If not why do we need that empty unused "Armature" node with one child?

> As @javagl said, I suspect this is extra data from the converter/source-data and that "Bone" could be referenced directly.

My actual question was is it OK for top-level skeleton node to not be glTF root-level node? And if it is, what's the point in such scheme?

---

>> Namespace of `node.jointName`. If it's glTF global, why not use `id` instead? If it is skeleton-tree limited, it can cause conflicts when `node.skeletons` contains two trees with the same `jointName`'s inside.

> I believe it is global. I actually suggested using `id` at one point, see #216. Given this, what do you suggest?

COLLADA uses parent-scoped `sid` instead of global-scoped `id` for that purpose. Its definition of `skeleton` is a bit vague: "where a skin controller is to start to search for the joint nodes that it needs" (v.1.4.1, p.5-109). One could understand it like "if required joints are found in the first skeleton, ignore all else". On the other hand it can mean "find all matching joints from all skeletons for each `jointName` and affect them simultaneously". 

---

Let's say one wants to have two instances of the same skinned mesh with different animations.
Is it intended to have two copies of the same skeleton tree with different `id`s for such case (because `animation.channel.target` needs global `id`)?

---

I'll make all needed PRs in one batch after we resolve aforementioned issues.

**Comment by pjcozzi** [comment]
@lexaknyazev comments below.  I am also going to seek some feedback from folks who have done more work with skinning than me.  Will let you know if/when I hear back.

---

> First suggestion was to separate skeleton nodes from all others by forbidding camera, skeletons, skin, meshes fields in any node in a skeleton tree.

OK with me.

> Camcorder case by @javagl looks interesting. Maybe, a non-joint node could be allowed in a skeleton tree for such case. This will make runtime a bit more complicated, though. @pjcozzi what do you think?

I am hesitant here since skinning is already complicated for the runtime and I would only want to make it more complicated for very prominent use cases.

---

> My actual question was is it OK for top-level skeleton node to not be glTF root-level node? And if it is, what's the point in such scheme?

I would say no.  It would be easier to relax the spec later if prominent use cases arise.

---

> COLLADA uses parent-scoped sid instead of global-scoped id for that purpose. Its definition of skeleton is a bit vague: "where a skin controller is to start to search for the joint nodes that it needs" (v.1.4.1, p.5-109). One could understand it like "if required joints are found in the first skeleton, ignore all else". On the other hand it can mean "find all matching joints from all skeletons for each jointName and affect them simultaneously".

I'll ask the person who designed this part of the spec.

> Let's say one wants to have two instances of the same skinned mesh with different animations.
Is it intended to have two copies of the same skeleton tree with different ids for such case (because animation.channel.target needs global id)?

I think so, but will confirm.

**Comment by pjcozzi** [comment]
> I'll ask the person who designed this part of the spec.

I hope to have a call with him next week.  Sorry for the slow movement here.  Can we move forward with parts of this in the meantime, e.g.,

> First suggestion was to separate skeleton nodes from all others by forbidding camera, skeletons, skin, meshes fields in any node in a skeleton tree.

**Comment by lexaknyazev** [comment]
To sum it up:
#### 1.0
- small typos and clarifications

#### 1.0.1 
- Skeleton tree must contain __only__ skeleton nodes. No node from non-skeleton tree can contain `jointName`.
- Top-level skeleton node must be top-level glTF node.
- `skin.jointNames.length` can be less than `parameter.count` for JOINTMATRIX parameter.

**Comment by pjcozzi** [comment]
@lexaknyazev these are all OK with me.  Let's go with it!  Please open the PRs.

**Comment by lexaknyazev** [comment]
@javagl Is it OK to use your skinning attributes definitions from glTF Overview?

**Comment by javagl** [comment]
@lexaknyazev  Sure. 

(I tried to follow the proposed changes for 1.0.1, but will have to review the overview once everything has settled. Some of the new clarifications should probably be in the overview as well)

**Comment by lexaknyazev** [comment]
Looks like 
> Top-level skeleton node must be top-level glTF node.

is already enforced by 1.0:

> The `skeletons` property contains one or more skeletons, each of which is the root of a node hierarchy.

At the same, time node hierarchy in samples is different (`RiggedSimple.gltf`):
- `node_4`
 -  `Armature`
   - `Bone`
     - `Bone_001`
 - `Cylinder`

`Cylinder.skeletons[0]` points to `Bone`.

Should valid hierarchy be like this?
- `Bone`
  - `Bone_001`
- `node_4`
 - `Cylinder`

**Comment by pjcozzi** [comment]
> At the same, time node hierarchy in samples is different (RiggedSimple.gltf):

Sounds like a COLLADA2GLTF bug, I submitted #648.

**Comment by pjcozzi** [comment]
@lexaknyazev ready to close this?

**Comment by lexaknyazev** [comment]
> @lexaknyazev ready to close this?

As soon as we deal with `jointName` scope-related issues.

**Comment by pjcozzi** [comment]
Is this just:

> 4. Namespace of node.jointName. If it's glTF global, why not use id instead? If it is skeleton-tree limited, it can cause conflicts when node.skeletons contains two trees with the same jointName's inside.

I don't think these are supposed to be global since they are not the id for a top-level glTF object.  Could we just restrict it so two trees referenced by the same `node.skeletons` can't have the same `jointName`?

For background, see https://github.com/KhronosGroup/glTF/issues/216#issuecomment-50253620

**Comment by lexaknyazev** [comment]
> I hope to have a call with him next week

Did you manage to reach him? I think we are in need of more feedback here. Just three questions:

1. Is `jointName` global or skeleton-tree scoped? (Suppose latter.)
2. Are colliding `jointName`s from two or more referenced `skeleton`s allowed? (Suppose no.)
3. Let's say one wants to have two instances of the same skinned mesh with different animations.
Is it intended to have two copies of the same skeleton tree with different `id`s for such case (because `animation.channel.target` needs global `id`)?

**Comment by pjcozzi** [comment]
Your assumptions are correct for (1), (2), and (3).  (3) does not sound ideal; if it becomes a problem in practice I wonder if we can come up with other ways for an animation channel to target skinned meshes.

**Comment by pjcozzi** [comment]
@lexaknyazev I would go with your suggestions here, https://github.com/KhronosGroup/glTF/issues/624#issuecomment-232805219 unless @mre4ce suggests otherwise.

**Comment by javagl** [comment]
I tried to figure out the latest state regarding `node.jointName`, but it is not yet entirely clear for me. The **node** schema says

        "jointName" : {
            "allOf" : [ { "$ref" : "glTFid.schema.json" } ],
            "description" : "Name used when this node is a joint in a skin."
        },

This has **not** changed between 1.x and 2.0 (but the type of `glTFid` has changed from `string` to `integer`)

The **skin** schema says

        "jointNames" : {
            "type" : "array",
            "description" : "Joint names of the joints (nodes with a `jointName` property) in this skin.",
            "items" : {
                "$ref" : "glTFid.schema.json"
            },
            "uniqueItems" : true,
            "gltf_detailedDescription" : "Joint names of the joints (nodes with a `jointName` property) in this skin.  The array length is the same as the `count` property of the `inverseBindMatrices` accessor (when defined), and the same as the total quantity of all skeleton nodes from node-trees referenced by the skinned mesh instance node's `skeletons` array."
        },

**Iff** I understood this correctly, then the `skin.jointNames` will in fact be **global** node indices - couldn't the `node.jointName` be omitted then?

**Comment by lexaknyazev** [comment]
Current WG decision is to use [that set of changes](https://github.com/KhronosGroup/glTF/issues/723#issuecomment-254674004).
They haven't been integrated yet.

**Comment by pjcozzi** [comment]
Updated in #826
