### ISSUE TITLE
Little clarification on buffer.type

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#629]
Some time ago (#141, #233), `text` was added as a valid value for `buffer.type` enum for future compression support.

At the moment (1.0-1.0.1), spec doesn't define any compression method. Nor it defines what to do with assets with `buffer.type: "text"`.

Maybe it will be reasonable to remove `text` from valid values enum for`buffer.type` for 1.0.1, and propose it later via specific compression extension?

**Comment by pjcozzi** [comment]
Yes, I agree.  Thanks for catching this.

Can you please open a PR into the `1.0.1` branch with the spec/schema update?

**Comment by lexaknyazev** [comment]
Spec mentions also `text` in description ([L333](https://github.com/KhronosGroup/glTF/blame/1.0.1/specification/README.md#L333)). Should we change that?

**Comment by pjcozzi** [comment]
Yes, please.

**Comment by lexaknyazev** [comment]
@pjcozzi Could you label this issue as `resolved`?

**Comment by pjcozzi** [comment]
Yes, labeled.

**Comment by pjcozzi** [comment]
Updated in #826
