### ISSUE TITLE
where can I get glTF Example in glTF-1.0-Introduction-Oct15.pdf

### ISSUE THREAD

**Issue by liyihongcug** [KhronosGroup/glTF#638]
https://www.khronos.org/assets/uploads/developers/library/overview/glTF-1.0-Introduction-Oct15.pdf

Page 9/16  in glTF-1.0-Introduction-Oct15.pdf
website:localhost:8080  (page title seems  AGI Model inspector)
Left  (big)   glTF Example JSON Node (the truck)
with three children (sets of two wheels)

where can I get glTF website's code  (:localhost:8080)

**Comment by pjcozzi** [comment]
The code for that app is not open-source, but the model inspector tool will be part of this product: https://cesiumjs.com/

**Comment by javagl** [comment]
(From the title of the question, I first thought that it was about *the model itself*, but I'm not sure after reading the text. However, I think the model is https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Apps/SampleData/models/CesiumGround , just in case...)

**Comment by pjcozzi** [comment]
OK to close this?
