### ISSUE TITLE
CAN U give us some books about gltf?

### ISSUE THREAD

**Issue by liyihongcug** [KhronosGroup/glTF#641]
The books about gltf should be complete and have codes that can run in explorer.
I have searched for some days but these pdfs are not suitable.

if you agree, please paste its website below

**Comment by liyihongcug** [comment]
problems in working.
1  For example, I draw one Enitity in web explore in cesiumJs and after that I want to export the Entitty to one gltf file.  (I need simple sample that describe how to do  and so I can catch key point )
2  If I create one gltf in memory in Js client  , How can I load it .
  The problem is memory load. (cesiumjs is file loading and Now it is memory loading)
3 How to separate different Object in the same gltf file?
  var model = scene.primitives.add(Cesium.Model.fromGltf({
    url : 'SampleData/models/CesiumGround/Cesium_Ground.gltf',
In this way, you make the whole gltf as one Entity, Now I think if this gltf file has 2 real Entity,
whether can we handle with it (we can't always make one gltf as one Entity)
4 if you can introduce  osgconv command (from osdb --> obj  in osg) ,I will continue to ask some problems next.

**Comment by pjcozzi** [comment]
@liyihongcug it sounds like these are Cesium-specific questions.  Please ask these on the [Cesium forum](http://cesiumjs.org/forum.html).

**Comment by pjcozzi** [comment]
Closing.  Please post on the [Cesium forum](http://cesiumjs.org/forum.html) if you still have questions.
