### ISSUE TITLE
MIME type for KHR_binary_glTF

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#650]
Extension [mentions](https://github.com/KhronosGroup/glTF/blob/master/extensions/Khronos/KHR_binary_glTF/README.md#mime-type) `model/gltf+binary` which should be `model/gltf.binary`.

**Comment by pjcozzi** [comment]
Also see #412.

Cesium also uses `.`, not `+`, https://github.com/AnalyticalGraphicsInc/cesium/blob/master/server.js#L44, so this is an extension spec bug.

This still needs to be registered with IANA.

Good eye, thanks.
