### ISSUE TITLE
Terms collision in KHR_binary_glTF

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#653]
` KHR_binary_glTF` refers to the glTF data as "scene", while glTF spec has its own definition of "scene" (and can have many of them).

Maybe, we could come up with something better?

**Comment by pjcozzi** [comment]
I agree this is confusing.  This can be an extension spec bug fix post 1.0.1.

@mlimper do you have any ideas?  I know this is the best we could come up with at the time.  Maybe `glTF JSON` or `contents`?

**Comment by mlimper** [comment]
The current version says

> The structured glTF scene description, entitled the `scene`

I remeber that the words "scene description" and "scene" were already difficult at that point, but we didn't have a better idea... I like `content` or `contents`, where the sentence could make clear that it is about the *structured* content (in contrast to the *binary* content, which comes in the `body`). To be perfectly clear, one could also call it `glTFContent` or so. So, above sentence could become:

> The structured glTF content description, entitled the `glTFContent`

or just

> The structured glTF content description, entitled the `content`

**Comment by pjcozzi** [comment]
structured `glTFContent` is good with me.

@lexaknyazev if you agree, I'll make the change.

**Comment by lexaknyazev** [comment]
I like "structured glTF content" for the text part. But why repeat `glTF` in the field's names: `glTFContent`, `glTFContentLength`, `glTFContentFormat`?

**Comment by pjcozzi** [comment]
I agree, just `content` for the field name is OK.  I'll make the changes soon.
