### ISSUE TITLE
Should be able to specify alternate OpenCOLLADA location for CMake.

### ISSUE THREAD

**Issue by elfprince13** [KhronosGroup/glTF#654]
I'm working on another project that already has OpenCOLLADA as a submodule, and now has glTF as a submodule. The CMakeLists should really allow us to specify the use of that copy of OpenCOLLADA (and avoid initting the second submodule onto our filesystem at all).

**Comment by pjcozzi** [comment]
Replaced by https://github.com/KhronosGroup/COLLADA2GLTF/issues/125
