### ISSUE TITLE
'memcpy' Not Declared

### ISSUE THREAD

**Issue by KermMartian** [KhronosGroup/glTF#656]
`#include <cstring>` is missing from two files in order to define memcpy() for g++-based builds:
- COLLADA2GLTF/JSON/JSONNumber.cpp
- COLLADA2GLTF/helpers/geometryHelpers.cpp

**Comment by skrat** [comment]
Same problem here, Arch Linux, up to date

**Comment by pjcozzi** [comment]
Thanks for the report and fix.

@lasalvavida can you make this small change?

**Comment by lasalvavida** [comment]
@pjcozzi, @skrat has a pull request open #657 to resolve this issue already.

**Comment by pjcozzi** [comment]
> @pjcozzi, @skrat has a pull request open #657 to resolve this issue already.

Ah yes, I am still catching up since SIGGRAPH.  Thanks for the report and fix, @KermMartian and @skrat!
