### ISSUE TITLE
Better support for Vulkan

### ISSUE THREAD

**Issue by MarkY-LunarG** [KhronosGroup/glTF#663]
I'm in the middle of attempting to load the GLTF models into Vulkan and I've noticed a few items.  I believe these are more enhancements for a future version than a requirement for now since I can manually modify the samples to load:
1) Support SPIR-V shaders.
    a) Should be simple for external files by just having them labeled spv or spirv.
    b) For internal mime type content, you might have to have an additional flag in the shader JSON content.
2) Support GLSL 400 or newer
    a) uniform blocks (with defined layout, alignment and binding info in JSON)
    b) layout location definitions for input attributes (including location info in JSON)

The main issues I'm seeing, albeit I'm new to Vulkan, include properly setting up the attributes and uniforms to the GLSL shader definitions once I had to modify to use the new GLSL version.  For now, I define the attributes in the JSON in the order of the GLSL usage, so I can set the location.  Additionally, I do the same of the uniforms in the uniform block.

I'm attaching the changes I've made to the JSON and shader files.  There might be a better way to do this, but I wanted to give you some idea of what I've done (especially in the shaders to get Glslang to compile the shaders to SPIR-V).

[glTF-Vulkan.zip](https://github.com/KhronosGroup/glTF/files/390636/glTF-Vulkan.zip)

I looked for a GitLab version of this in case there was a discussion on requirements for Vulkan, but I didn't see it.  If there is one, let me know and I can start following it there.

**Comment by pjcozzi** [comment]
@MarkY-LunarG thanks for the notes on using glTF with Vulkan.  If you haven't already, you might want to sync-up with @chrisjebert1973 to share experiences here.  It would be awesome to get a comprehensive-ish wishlist based on your combined experiments with glTF and Vulkan.

**Comment by diegor8** [comment]
what about the way the geometry is represented ? glTF was designed to mimic opengl , so wouldnt using this format rwith vulkan requiere additional parsing , which would negate its main strength ?

**Comment by MarkY-LunarG** [comment]
I believe with the AMD Vulkan viewport transform extension, that should be negated.  But I haven't delved to deeply into that.

**Comment by diegor8** [comment]
But that extension wont be necesary for the version 1.1 because would have already adressed the problem , right?

**Comment by diegor8** [comment]
But that extension wont be necesary for the version 1.1 because would have already adressed the problem , right?

**Comment by emackey** [comment]
glTF 2.0 is cross-platform, and Vulkan renderers for it exist.  If any trouble spots between glTF 2.0 and Vulkan are still around, please open a new issue for them, thanks.
