### ISSUE TITLE
BoxWithoutIndices uses indices

### ISSUE THREAD

**Issue by dgough** [KhronosGroup/glTF#665]
The BoxWithoutIndices samples use indices in the mesh primitive. Is this a mistake? I thought the purpose of this sample was to not use indices.

[BoxWithoutIndices.gltf](https://github.com/KhronosGroup/glTF/blob/master/sampleModels/BoxWithoutIndices/glTF/BoxWithoutIndices.gltf#L109)

**Comment by lexaknyazev** [comment]
From model's [README.md](https://github.com/KhronosGroup/glTF/blob/master/sampleModels/BoxWithoutIndices/README.md):
> This version of the box model has all the indices in order 0-35. When you convert it to glTF, you need to remove the mesh.primitive.indices, so it just renders all vertices in order.

@lasalvavida, should that accessor be removed manually after converting, or there is some tool for it?

**Comment by lasalvavida** [comment]
I assume the indices were left included for testing purposes. A developer would get a renderer working with indices, then you can just delete the indices reference and the model should still be valid and render. 

The README is correct, but I agree that the name is confusing.

**Comment by dgough** [comment]
Thank you. Deleting the indices reference worked.

**Comment by pjcozzi** [comment]
I think that comment in the README.md referred to the COLLADA model, not the generated glTF models, which should have the indices deleted.  Perhaps we updated the glTF models at some point without making this manual change.

@lasalvavida can you update the glTF versions of this model?

**Comment by pjcozzi** [comment]
Updated in #680.  Thanks again @dgough!

**Comment by pjcozzi** [comment]
@dgough I also just saw your new project, https://github.com/dgough/kepler3d.  Let me know when it is far enough along and I would be happy to list it here: https://github.com/KhronosGroup/glTF#loaders-and-viewers

**Comment by dgough** [comment]
@pjcozzi Thank you. I'm not ready for people to start using it but I'll keep that in mind.
