### ISSUE TITLE
collada2gltf producing different gltf outputs

### ISSUE THREAD

**Issue by slozier** [KhronosGroup/glTF#669]
For certain files it seems collada2gltf does not always produce the same gltf output. I tried the latest collada2gltf release as well as running from the latest commit. The issue only occurs in release mode when running from source so my guess is some uninitialized memory in the buffer element...

I've attached the test file:
[bad.zip](https://github.com/KhronosGroup/glTF/files/397704/bad.zip)

As you can see below, it's producing a different file hash:

```
E:\> .\collada2gltf\collada2gltf.exe -f bad.dae -e
converting:bad.dae ... as bad.gltf
[geometry] 496 bytes
[animations] 0 bytes
[scene] total bytes:496
[completed conversion]
Runtime: 0.01 seconds
E:\> write-host (Get-FileHash bad.gltf).Hash
9541A32347553BCDE95991674979269C1DB4205DFA0085F8A5E4DC378D3E40C4
E:\> .\collada2gltf\collada2gltf.exe -f bad.dae -e
converting:bad.dae ... as bad.gltf
[geometry] 496 bytes
[animations] 0 bytes
[scene] total bytes:496
[completed conversion]
Runtime: 0.01 seconds
E:\> write-host (Get-FileHash bad.gltf).Hash
74FCBE213F46F550CBA51087CF01609684A432866316E39516C5D057B20E69F7
E:\> .\collada2gltf\collada2gltf.exe -f bad.dae -e
converting:bad.dae ... as bad.gltf
[geometry] 496 bytes
[animations] 0 bytes
[scene] total bytes:496
[completed conversion]
Runtime: 0.01 seconds
E:\> write-host (Get-FileHash bad.gltf).Hash
F5ED7790884CA17B9C9592C464C4025B16A8B7ADDBA864B7BFE6EAB6A05374BA
```

**Comment by javagl** [comment]
(Not being familiar with the code: Are you sure it's due to un-initialized buffers? It might also be due to some `unordered_map` or so. This is just a guess. A first relevant question would be whether the results are "valid" or not. Did you compare them in any way?)

**Comment by slozier** [comment]
@javagl My theory is based on the fact that when running in debug mode (which initializes all memory) the generated file is always the same.

As for validity I'm not sure, the JSON of the glTF file is certainly valid, the differences are popping up in the min/max values of certain accessors as well as the data uri of the buffer. Stepping though the code it appears that the min/max values are generated using the values in the buffer so if the buffer is "changing" then that explains the min/max values being different.

**Comment by pjcozzi** [comment]
@slozier thanks for the same model.  I agree that it would be good to know if this is a bug in COLLADA2GLTF or just the way it behaves.  Sounds like the former.

Most of us are fully committed on other things, but we would certainty welcome a pull request if you track this down.

**Comment by pjcozzi** [comment]
Replaced by https://github.com/KhronosGroup/COLLADA2GLTF/issues/126
