### ISSUE TITLE
accessor to "compressedData"

### ISSUE THREAD

**Issue by smalcom** [KhronosGroup/glTF#670]
At now accessors "byteOffset" mean that data of current mesh is decoded while all other meshes is encoded. It is very inconvenience. May be better that  all "byteOffset" has values meaning that all data is decoded?

**Comment by lasalvavida** [comment]
I'm not sure I understand the issue. `byteOffset` in an accessor should always point to the `byteOffset` in the corresponding `bufferView` as it exists in the `buffer`. What is your use case?

**Comment by smalcom** [comment]
I mean when compression is used.
Example. You have two meshes. For every of it you have 4 bytes of data. That data compressed to 2 bytes. So, you have buffer with encoded data:
---> M1_E0, M1_E1, M2_E0, M2_E1.

After decoding you'll get:
---> M1_D0, M1_D1, M1_D2, M1_D3, M2_D0, M2_D1, M2_D2, M2_D3.
"accessors" must to use values that point to decoded data - obviously. So, you'll expect "accessors" like
"accessor_0" : { byteOffset: 0, byteLength: 4}, "accessor_1" : { byteOffset: 4, byteLength: 4}
but in real life you'll get:
"accessor_0" : { byteOffset: 0, byteLength: 4}, "accessor_1" : { byteOffset: 2, byteLength: 4}
Yes, accessor of next mesh has offset and length which mean: current mesh data is decoded, all other data is encoded.
And when before you start to read data of current mesh (with encoded data ofcourse) you must decode region of "bufferView", after read finished delete decoded data. And after that you can repeat process: decode data of mesh, read, delete decoded data.

**Comment by smalcom** [comment]
the question is removed. I have understood why so it is necessary.
