### ISSUE TITLE
COLLADA2GLTF should live in its own repo

### ISSUE THREAD

**Issue by erlend-sh** [KhronosGroup/glTF#671]
Just like the [glTF validator](https://github.com/KhronosGroup/glTF-Validator) and other glTF utilities, [COLLADA2GLTF](https://github.com/KhronosGroup/glTF/tree/master/COLLADA2GLTF) ought to live in its own repository.

As far as I know it is completely self contained, and I find it confusing that it is showing up in [Releases](https://github.com/KhronosGroup/glTF/releases), which should rather be used to track the releases of the glTF specification.

**Comment by pjcozzi** [comment]
I agree.  We also want to separate the sample models and C# loader.  Timeline is TBA.

**Comment by pjcozzi** [comment]
COLLADA2GLTF is now here: https://github.com/KhronosGroup/COLLADA2GLTF
