### ISSUE TITLE
COLLADA2glTF Ignores -o Flag

### ISSUE THREAD

**Issue by KermMartian** [KhronosGroup/glTF#672]
COLLADA2glTF ignores the output path specified with the -o flag, instead just generating the output in the path computed by replacing the .dae in the input file with .gltf. To replicate, try (for example) the following:
`./foo/collada2gltf -r -e -f struct.dae -o struct.ascii.gltf -c Open3DGC -m ascii
converting:struct.dae ... as struct.gltf`

**Comment by pjcozzi** [comment]
Thanks for the bug report; this must have broke recently as I recall using this in the past.

@lasalvavida please look as time allows.

**Comment by pjcozzi** [comment]
@KermMartian btw, I was just checking out your research page...cool stuff...what are you building with glTF?

**Comment by KermMartian** [comment]
@lasalvavida The problem is a silly regression in COLLADA2GLTF/main.cpp, line 254, a & instead of &&:
``` if (!hasOutputPath & hasInputPath) {```

@pjcozzi Thanks! I'm exploring a project with a colleague around doing automated, large-scale, highly-detailed world reconstruction, and we're taking a look at CesiumJS + Tiles + glTF to see if it might be a useful part of our toolchain.

**Comment by pjcozzi** [comment]
@KermMartian thanks for tracking this down.  Sounds like a cool project, let me know how it goes; we're happy to promote your work through glTF and Cesium channels.

**Comment by pjcozzi** [comment]
Replaced by https://github.com/KhronosGroup/COLLADA2GLTF/issues/127
