### ISSUE TITLE
COLLADA2glTF Silently Fails on Zipped Models

### ISSUE THREAD

**Issue by KermMartian** [KhronosGroup/glTF#673]
Although COLLADA2glTF links against libz, making me assume it can understand model + textures zipped into a compressed archive, it generates a 474-byte gltf file containing no geometry. For example:
`baz@bar$ .foo/collada2gltf -r -e -f /somedir/struct.dae.zip -o /somedir/struct.gltf
converting:/somedir/struct.dae.zip ... as /somedir/struct.gltf
[Info]: current working directory:/someotherdir
[geometry] 0 bytes
[animations] 0 bytes
[scene] total bytes:0
[completed conversion]
Runtime: 0.00 seconds`

It should either properly convert the model, or explicitly emit an error.

**Comment by pjcozzi** [comment]
We could display a warning here (pull requests welcome, of course); it is better separation of concerns to have another stage in the content pipeline do this.

**Comment by pjcozzi** [comment]
Replaced by https://github.com/KhronosGroup/COLLADA2GLTF/issues/128
