### ISSUE TITLE
Format should support references and inline data

### ISSUE THREAD

**Issue by donny-dont** [KhronosGroup/glTF#68]
To avoid making additional HTTP requests the shader schema should have a space for putting the source code directly in the JSON. Within the schema there should either be a data uri or the source code.

**Comment by pjcozzi** [comment]
@tparisi for the draft 1.0 spec add:

> ## Uris
>
> glTF uses uris to reference buffers, shaders, and images resources.  These uris may point to external files or be [data URIs](https://developer.mozilla.org/en/data_URIs) to embed resources in the JSON.
>
> The allows the application to decide what the best approach.  If assets share many of the same geometry, animation, textures, or shaders, separate files may be preferred to reduce the total amount of data requested.  If an application cares more about single-file deployment, embedding data may be preferred even though it increases the overall size due to base64 encoding.  With separate files, applications can progressively load data and do not need to load data for parts of a model that are not visible.

Also, elsewhere the spec should state this:

> For compatibility with modern web browsers, the following image formats are supported: `.jpg`, `.png`, `.bmp`, and `.gif`.
