### ISSUE TITLE
How to clone a gltf model in threejs?

### ISSUE THREAD

**Issue by easyfrog** [KhronosGroup/glTF#683]
I use threejs gltf loader. But I don't know how to clone this model.
Is there some code can do this?

**Comment by pjcozzi** [comment]
I think your best bet is to ask the threejs community @tparisi if he is available.

**Comment by pjcozzi** [comment]
@easyfrog I'm going to consolidate this issue with #591, which may also move to the three.js repo which I suspect is the appropriate repo now.
