### ISSUE TITLE
Have to manually specify linking flags with ccmake on OS X

### ISSUE THREAD

**Issue by elfprince13** [KhronosGroup/glTF#693]
I have to manually specify:
`CMAKE_EXE_LINKER_FLAGS           -L/opt/local/lib -liconv -llzma -lz`
with `ccmake` on OS X (using MacPorts), or I get linking errors related to symbols from each of libxml2's dependencies.

**Comment by pjcozzi** [comment]
Replaced by new problems, lol, https://github.com/KhronosGroup/COLLADA2GLTF/issues/91, that will be fixed!
