### ISSUE TITLE
[PBR extension] Specify more concretely how scalar parameters and textures interact

### ISSUE THREAD

**Issue by mlimper** [KhronosGroup/glTF#698]

**Comment by mlimper** [comment]
The current draft extension spec says:

>The factors (diffuseFactor, specularFactor, glossinessFactor) scale the components given in the respective textures (diffuseTexture, specularGlossinessTexture). If a texture is not given, all respective texture components are assumed to have a value of 1.

(See [here](https://github.com/tsturm/glTF/tree/master/extensions/Vendor/FRAUNHOFER_materials_pbr#material-models))

Would that be OK?

**Comment by pjcozzi** [comment]
@erich666 what do you think?

**Comment by emackey** [comment]
This does sound consistent with behavior in Blender and other 3D rendering packages I've seen.

**Comment by erich666** [comment]
I agree, assume 1 for the texture, of course.

I'm happy to see the spec is clear in laying out that the diffuseFactor is multiplied by the texture color, vs. getting replaced by it. Wavefront OBJ didn't do so. 

@mlimper 
My one little comment is to make [the example](https://github.com/tsturm/glTF/tree/master/extensions/Vendor/FRAUNHOFER_materials_pbr) easier to read:

> For example, assume a value of (1.0, 0.5, 0.5) is read from an RGB diffuseTexture, and assume that diffuseFactor would be given as (0.1, 1.0, 0.1, 1.0). Then, the result would be (1.0 * 0.1, 0.5 * 1.0, 0.5 * 0.1, 1.0 * 1.0) = (0.1, 0.5, 0.05, 1.0);

I had real problems reading this, differentiating between 1.0 and 0.1. Please change this to something like:

> For example, assume a value of (1.0, 0.5, 0.3) is read from an RGB diffuseTexture, and assume that diffuseFactor would be given as (0.2, 1.0, 0.7, 1.0). Then, the result would be (1.0 * 0.2, 0.5 * 1.0, 0.3 * 0.7, 1.0 * 1.0) = (0.2, 0.5, 0.21, 1.0);

I don't even like all the 1.0's in the example, it'd be better yet if every one of the RGB values was something unique and not 1.0 or 0.0. Your call.

**Comment by mlimper** [comment]
> I don't even like all the 1.0's in the example, it'd be better yet if every one of the RGB values was something unique and not 1.0 or 0.0. Your call.

Done - thanks for the nice suggestion!
