### ISSUE TITLE
Add structure diagrams to spec

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#70]
I have lots of nice - but now outdated - diagrams like the one below that need to be updated and included in the spec:

![image](https://f.cloud.github.com/assets/782098/398037/f3e345d0-a84e-11e2-93a1-730b6b074c92.png)

**Comment by pjcozzi** [comment]
Added a few #441.  Leaving this open for post 1.0 so @slchow and I can add a few more.

**Comment by pjcozzi** [comment]
@lexaknyazev what do you think?  Is this still worth it?  Or is what we have sufficient?

**Comment by lexaknyazev** [comment]
I think that Marco's overview covers this.

**Comment by pjcozzi** [comment]
Sounds good!
