### ISSUE TITLE
[PBR extension] Gamma correction / sRGB encoding

### ISSUE THREAD

**Issue by mlimper** [KhronosGroup/glTF#700]
We should specify more clearly how gamma correction / linearization / sRGB encoding should work, and tighten the spec accordingly.

**Comment by pjcozzi** [comment]
Should this be specific to the extension?  Or in the core glTF spec?

**Comment by mlimper** [comment]
Here's the interpretation of @tsturm and myself:

When we use a glTF that comes with its own shader code, this shader code would already deal with the interpretation of the texture content, so in that case a specified color space might only serve as a hint / note.

For [KHR_materials_common](https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_materials_common) and for our PBR extension, however, it seems to make sense that we specify the color space explicitly.

We could state in the core spec that there is a possibility to give a hint about the color space of a [texture](https://github.com/KhronosGroup/glTF/tree/master/specification#textures) object. This hint might not even be necessary as an explicit new variable: EXT_sRGB (in WebGL 1) and WebGL 2 allow hardware-supported color space conversion by specifying the texture format accordingly.

**Comment by lexaknyazev** [comment]
Agree with everything.
Maybe we should also consider adding `framebuffer` concept to glTF for more efficient runtime implementation.

**Comment by lexaknyazev** [comment]
There's a little caveat with `format`:
when `EXT_sRGB` extension is used, values are `0x8C40 (SRGB_EXT)` and `0x8C42 (SRGB_ALPHA_EXT)`,
but when WebGL 2.0 (ES 3.0) is used, values are `0x8C41 (SRGB8)` and `0x8C43 (SRGB8_ALPHA8)`.

**Comment by cedricpinson** [comment]
We can just say in the spec what color space should be used for the different textures. Like
basecolor/diffuse/specular color should be srgb
metalness/roughness/glossiness should be linear

Then provide some shader code example to convert linear2srgb and srgb2linear

**Comment by pjcozzi** [comment]
@erich666 what do you think of @cedricpinson's suggestion?

**Comment by cedricpinson** [comment]
I forget to add the reference from allegorithmic https://www.allegorithmic.com/pbr-guide

**Comment by erich666** [comment]
> @erich666 what do you think of @cedricpinson's suggestion?

I like it, that sounds right to me. However, the full comment:

>basecolor/diffuse/specular color should be srgb
> metalness/roughness/glossiness should be linear

brings up a few questions. I'm not sure what basecolor is, vs. diffuse - I think there should just be one, sometimes called the albedo map; three.js just calls it "map". There's only diffuseColor and specularColor as solid colors in the PBR spec. 

Also, there's only diffuseTexture in the spec. Does the color map affect the diffuse and specular color, or just the diffuse color? In three.js it affects both, but there's no way to specify that only the specular color or only the diffuse color should be affected by the texture map, which I think is a flaw, or at least a drawback, in their shader system. Do you want to add a specularTexture (vs. specularGlossinessTexture, which you do have and which is something else)? I think for practical reasons I wouldn't, i.e., three.js doesn't support it (yes, I know there are other apps out there - I love Sketchfab. But the Sketchfab guys are more flexible, the three.js materials are public and unlikely to quickly change). @cedricpinson - do people make the separation between diffuse and specular maps?

I would make the solid color (diffuseFactor, specularFactor) specified in sRGB, so what you see on the screen is what you're specifying. The value of course needs to be linearized before using it in a shader, and the result converted back into sRGB for display.

There's also the whole gamma correction question itself. We find doing it as a post-process is a terrible idea in WebGL 1. Search for "gamma" in my comments [here](https://github.com/KhronosGroup/glTF/issues/697) for more on this. Here's the quick version:

> ...gamma correction in some form does matter. If you are not convinced for some reason, [try this demo](http://www.realtimerendering.com/udacity/?load=demo/unit9-gamma.js), turn off gamma correction and set both lights to 0.2 - the area they overlap is excessively bright compared to the separate light sources. Three.js, for backwards compatibility purposes, uses a gamma correction factor of 2.0, not 2.2. More importantly, each fragment is gamma corrected on output, vs. taking the final image and gamma correcting it. This matters for transparent objects and for antialiased edges. However, WebGL isn't really up to the task, and to do gamma correction properly you normally need to use 16 bits per channel and a post-processing pass at the end to get the final image - expensive for mobile or slower PCs.

Man, this whole subject has a lot of little bits to it...

**Comment by cedricpinson** [comment]
@erich666 names are different in metalness-roughness workflow vs specular-glossiness workflow.
in metalness-roughness we used often basecolor or albedo, and in specular-glossiness workflow it's called diffuse.

In Sketchfab channels are separated because it's more flexible, for performance it's better to merge them to reduce number of textures in shaders. Sometime people ask us to support packed format so we will probably support it but it does not seem to be an issue for people.

In tools like substance painter you can choose how you export data, it can be packed or separated. It depends how you want to use the data outside tools. Unity seems to have only one packed format, but I did not check personally on this. I dont know how Quixel export maps.

I will add some stats about channels usage on our platform, could be interesting

**Comment by bghgary** [comment]
Wanted to point out a couple of things.

First, in the PBR spec as it currently stands, it states:

> The factors (diffuseFactor, specularFactor, glossinessFactor) scale the components given in the respective textures (diffuseTexture, specularGlossinessTexture). If a texture is not given, all respective texture components are assumed to have a value of 1.
>
> For example, assume a value of (1.0, 0.5, 0.5) is read from an RGB diffuseTexture, and assume that diffuseFactor would be given as (0.1, 1.0, 0.1, 1.0). Then, the result would be (1.0 * 0.1, 0.5 * 1.0, 0.5 * 0.1, 1.0 * 1.0) = (0.1, 0.5, 0.05, 1.0);

and

> The factors (baseColorFactor, metallicFactor, roughnessFactor) scale the components given in the respective textures (baseColorTexture, metallicRoughnessTexture). If a texture is not given, all respective texture components are assumed to have a value of 1. This is similar to the handling of factors and texture within the specular-glossiness model.

The wording of this needs to be modified if some of the values are in sRGB space. Effectively, it should say that the parameters need to be converted to linear space before doing the math.

Second, one might argue that these factors should match what is happening with the textures. For example, from experimentation and browsing shader code, Unity PBR materials seem to use sRGB space for colors and metallic, while smoothness (i.e. glossiness or 1 - roughness) is linear. I believe this is to match what is happening with the textures. Unity always puts smoothness in the A channel for SpecGlossMap and MetallicGlossMap and thus smoothness is always linear. Metallic is in the R channel of the MetallicGlossMap and thus Unity uses sRGB space for metallic.

This is however different for the PBR spec. Glossiness is stored in the A channel (linear space) of the SpecularGlossinessTexture, but roughness is stored in the G channel (sRGB space) of MetallicRoughnessTexture.

This can get confusing very quickly. While I understand that sRGB colors will match what you see on screen, I think it's less confusing if everything is linear.

**Comment by mlimper** [comment]
> Effectively, it should say that the parameters need to be converted to linear space before doing the math.

Agreed.

> but roughness is stored in the G channel (sRGB space) of MetallicRoughnessTexture.

This is a good point. Actually, we will want the content of the MetallicRoughness Texture to be interpreted in linear space, as @cedricpinson already pointed out.

I was wondering how a naive Web implementation would behave in the following case:
* Create image for a metal-roughness map, store values in R and G channels, using your favorite content creation tool X
* Save the image in some format Y (PNG / JPEG /  ...)
* Load the image in a WebGL application to render a PBR asset

Some google searches later:

It looks like one might get different visual results, depending on X (image exporter) as well as on Y (image format): different formats allow for different ways to do gamma correction, and even a single format might be exported in different ways. Now, if I understand this correctly, the Web application will generally not be able to correctly convert all kinds of input images into linear space, as it is not able to efficiently tell how exactly an image was decoded. The browser will usually just try to read the image and convert its content for display, not for using the values for computations in a linear space, and different browsers might even do this in an inconsistent way...

Now, it seems these issues can be mitigated using `EXT_sRGB`, if available - if we could assume that, for textures like MetallicRoughness, everything inside the shader will be in linear space, regardless of the input image and its format, that would be really awesome.
But then there might be other issues with mipmap generation or using texture compression (according to this [post](https://www.khronos.org/webgl/public-mailing-list/archives/1212/msg00091.php)).

Do you all agree? Would that be a correct summary, or do you have any corrections / additions?

Finally (to end with something more positive and constructive ;- ) :
Even if these problems are really that complex and partially unsolved, the question is how much this affects the PBR spec. I guess restricting the image formats to be used because of some issues that we have right now, or anything like that, does not make sense. For now, we could tighten the spec a bit and say that the application should try to ensure (however that happens) that the values of certain textures are to be interpreted in linear space, while others should be interpreted in sRGB space. Getting the correct values inside the shaders is then the responsibility of the implementation / the browser / ..., but not of the PBR spec.

**Comment by lexaknyazev** [comment]
> The browser will usually just try to read the image and convert its content for display, not for using the values for computations in a linear space, and different browsers might even do this in an inconsistent way...

From my experience, browsers usually don't do any conversion except applying ICC profiles/intents. If texture in JPG/PNG format hasn't any additional color space flags, rendering should be safe. 
Otherwise, such conversions could be disabled with:
```javascript
gl.pixelStorei(gl.UNPACK_COLORSPACE_CONVERSION_WEBGL, gl.NONE);
```

The whole point of `EXT_sRGB` (and its slightly different implementation in WebGL 2) is to provide a way to use hardware sRGB/linear (and vice-versa) transformation, so someone could
- provide textures in sRGB space (to reduce banding) and effortlessly get linear values in shaders;
- output linear values from shaders and expect GPU to make final gamma correction.

**Comment by bghgary** [comment]
> For now, we could tighten the spec a bit and say that the application should try to ensure (however that happens) that the values of certain textures are to be interpreted in linear space, while others should be interpreted in sRGB space. Getting the correct values inside the shaders is then the responsibility of the implementation / the browser / ..., but not of the PBR spec.

I agree with this for textures. What about the non-texture values? Should these values match what we do with the textures? For example, if we say DiffuseTexture should be interpreted as sRGB, then does that mean DiffuseFactor is sRGB? If we say MetalRoughnessTexture should be interpreted as linear, then does that mean metallicFactor and roughnessFactor are linear? We should spell this out completely in the spec.

**Comment by mlimper** [comment]
I just changed the [spec](https://github.com/tsturm/glTF/tree/master/extensions/Vendor/FRAUNHOFER_materials_pbr#specular---glossiness) accordingly (see the small section below the table).

Would that work? If yes, I would like to close this one for now.

**Comment by bghgary** [comment]
The spec still needs the information on which texture is interpreted as sRGB and which is linear. Maybe add an extra column to the tables to indicate which space the values are in? I'll send a PR.

**Comment by mlimper** [comment]
Thanks! Can we close this one?

**Comment by bghgary** [comment]
I'm good with this now.
