### ISSUE TITLE
COLLADA2GLTF writes 1.0.2 to asset.profile.version

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#701]
COLLADA2GLTF writes `1.0.2` instead of `1.0.3` to `asset.profile.version`.

Btw, is there any real issue with assets having just `1.0`? This could reduce fragmentation. We can explicitly state in the glTF spec that implementations should refer to the latest API spec available. Javascript runtime doesn't know such specific API version anyway.

**Comment by pjcozzi** [comment]
> Btw, is there any real issue with assets having just 1.0?

I don't think the differences between `1.0.x` affect glTF so I agree about updating COLLADA2GLTF to write out `1.0`.

Can you open a PR for into `1.0.1` for the spec (and COLLADA2GLTF if you want)?

**Comment by lexaknyazev** [comment]
> Can you open a PR for into `1.0.1` for the spec (and COLLADA2GLTF if you want)?

OK

**Comment by pjcozzi** [comment]
Updated in #826
