### ISSUE TITLE
object names

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/glTF#703]
It is my understanding that a JSON object represent a rigid object. Object members may be omitted but an object has a known set of members with known names. However, glTF uses objects as arrays. For instance, the "nodes" property is an object that lists an arbitrary number of members with arbitrary member names. Maybe the idea is that this makes it easier to lookup objects (as members of another object instead of array elements) but imho this is counter intuitive and I would expect object lookups to occur after parsing anyway. Using objects as arrays also requires a JSON parser that can list all object members without knowing their names.

That aside, the objects that are listed may also have a "name" property. Not only does this introduce redundancy it is now also unclear which name should be used to lookup objects. For instance, take the "monster.gltf" file:

```
"meshes": {
    "monster-mesh": {
        "name": "monster"
    }
},
"nodes": {
    "monster": {
        "meshes": [
            "monster-mesh"
        ]
    }
},
```

The "monster" node refers to the "monster-mesh" mesh. This example suggests that you can only lookup this mesh by using the object name, not the "name" property. This then raises the question what purpose the "name" property serves?

**Comment by dgough** [comment]
> Whereas IDs are used for internal glTF references, _names_ are used for application-specific uses such as display. glTF objects that are commonly accessed from an application have a `name` string property for this purpose. These property values are not guaranteed to be unique as they are intended to contain values created when the asset was authored.

I think the intention is that the the IDs are used for loading the gltf file but are then discarded. The `name` is used by the application because those are what were set in the 3D modelling tool. The IDs tend to be auto generated to ensure they are unique within the json file.

Take a look at the nodes in [CesiumMilkTruck.gltf](https://github.com/KhronosGroup/glTF/blob/master/sampleModels/CesiumMilkTruck/glTF/CesiumMilkTruck.gltf#L359). The node IDs are generated strings like `"Geometry-mesh001Node"` but the names are human readable like `"Wheels"` and `"Cesium_Milk_Truck"`.

```json
"nodes": {
    "Geometry-mesh001Node": {
        "children": [],
        "meshes": ["Geometry-mesh001"],
        "name": "Wheels",
        "rotation": [0,0,-0.0884856,0.996077],
        "scale": [1,1,1],
        "translation": [1.43267,0.427722,-2.98023e-008]
    },
    "Geometry-mesh002Node": {
        "children": [
            "Geometry-mesh001Node",
            "meshInst962Node"
        ],
        "matrix": [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],
        "meshes": ["Geometry-mesh002"],
        "name": "Cesium_Milk_Truck"
    },
```

After I load the gltf file, the resulting Node objects would have the name `"Wheels"` and `"Cesium_Milk_Truck"`. The IDs are only used by the gltf loader.

```C++
auto scene = GLTFLoader().loadSceneFromFile("CesiumMilkTruck.gltf");
if (scene)
    scene->findFirstNodeByName("Cesium_Milk_Truck")->rotateY(PI);
```

**Comment by mre4ce** [comment]
Thanks for the explanation!

Might want to document in the spec that the "name" serves no purpose other than to provide a more user friendly name that can be used by the application to find and manipulate objects.

**Comment by tparisi** [comment]
I think the language in the spec already spells this out. If not please suggest some other language

**Comment by pjcozzi** [comment]
I agree with @tparisi that I think the spec is good here.  If anyone wants to add any additional clarity to the spec, pull requests are appreciated.
