### ISSUE TITLE
Tightening technique.parameter.functions

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#705]
Since `technique.parameter.functions` map directly to GL calls, it could be reasonable to restrict allowed float values:
- **blendColor:** Floating-point value clamped to `[0; 1]`
- **depthRange:** Floating-point value clamped to `[0; 1]`. Also, [WebGL-specific limitation](https://www.khronos.org/registry/webgl/specs/latest/1.0/#6.12):
  
  > WebGL API does not support depth ranges with where the near plane is mapped to a value greater than that of the far plane.

**Comment by pjcozzi** [comment]
+1 from me.  Can you please open a PR?

**Comment by pjcozzi** [comment]
Updated in #826
