### ISSUE TITLE
Infinite projection matrix.

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/glTF#722]
It doesn't look there is a way to specify an infinite projection matrix. For as long as I can remember I have used the convention that the projection matrix is infinite when "zfar <= znear". However, the spec states that "zfar must be greater than znear." While this would allow you to set zfar to infinite, I don't like working with exceptional floating point values and JSON doesn't support them either. Unless there are clear reasons not to, using an infinite projection matrix should probably be everyone's first choice.

```
Tightening the Precision of Perspective Rendering
Paul Upchurch, Mathieu Desbrun
Journal of Graphics Tools, Volume 16, Issue 1, 2012
```

**Comment by lexaknyazev** [comment]
At first glance, we can allow `camera.perspective.zfar` to be optional.
So if it's defined runtime uses "traditional" projection matrix, otherwise it can build infinite one.

If such change will be made, we must properly document both approaches in spec.

What do you think?

**Comment by mre4ce** [comment]
Seems a little cleaner than "zfar <= znear" although it does rely on JSON being able to omit properties. Arguably zfar = infinity would be the most intuitive solution but that isn't an option using JSON. Either way omitting zfar for an infinite projection works for me.

**Comment by lexaknyazev** [comment]
So updated `camera.perspective.zfar` spec could look like this:
```json
"zfar" : {
  "type" : "number",
  "description" : "The floating-point distance to the far clipping plane.",
  "minimum" : 0.0,
  "exclusiveMinimum" : true,
  "gltf_detailedDescription" : "The floating-point distance to the far clipping plane. When defined, zfar must be greater than znear. If zfar is undefined, runtime must use infinite projection matrix."
}
```

@pjcozzi Do you have any comments here? I'll make a PR.

**Comment by mre4ce** [comment]
That works for me. Interestingly this allows for different implementation options that all have the same effect. A parser can check whether "zfar" is set or a parser can default the value to zero in case "zfar" isn't set and then still check for "zfar <= znear". Thanks!

**Comment by lexaknyazev** [comment]
@pjcozzi @mre4ce Please review #727.

**Comment by pjcozzi** [comment]
Updated in #826
