### ISSUE TITLE
FBX to glTF or GLB problems

### ISSUE THREAD

**Issue by WilCodeBoer** [KhronosGroup/glTF#724]
I've been trying to use the FBX to glTF exporter but for some reason the tool doesn't include  the shaders when embedding the fbx. When I choose not to embed the shaders and buffers the model does get loaded into cesium but now the model's child is out of place by a bit leaving an open space in the model.

My question is, does anyone know this problem and if so the solution? And if not then my question is if there are better fbx to gltf exporters then the one on here?

Best Regards,
Wilco

**Comment by pjcozzi** [comment]
@Wilco-VDS the FBX converter is developed by Autodesk so I would suggest posting this issue in their repo: https://github.com/cyrillef/FBX-glTF

If you want to try another converter, [assimp](http://www.assimp.org/) can import FBX and export glTF.

**Comment by pjcozzi** [comment]
Also see https://github.com/facebookincubator/FBX2glTF by @zellski
