### ISSUE TITLE
How to use this .bat file in command window?

### ISSUE THREAD

**Issue by dayanc** [KhronosGroup/glTF#725]
Hi guys,
I am not a software expert, but I need to convert my CityGML cartographic designs to glTF format to visualize them in Cesium.js;
[https://github.com/900k/CityGML2glTF]
I am using this in command line:
c2g --C:\Users\ga78liy.ADS.000\Desktop\GTA-Munich-1_0_0.xml --a --LOD2 --MULTI_SURFACE

But it is not working.

I also tried to convert the COLLADA file to glTF with cesium online converter, But everytime I get an error.

**Comment by pjcozzi** [comment]
I suggest submitting an issue to the https://github.com/900k/CityGML2glTF repo so their developers see it.

For the Cesium online converter, have you tried using the command-line COLLADA2GLTF converter available in this repo?  If it also fails, please submit a new issue here with a copy of the model if you can.

Also, CityGML conversion for use in Cesium will be part of the upcoming https://cesiumjs.com/

**Comment by dayanc** [comment]
I really have no idea how to run this command line converter in Windows, Can you please provide me some materials and instructions?

**Comment by pjcozzi** [comment]
Perhaps the release instructions are useful: https://github.com/KhronosGroup/glTF/releases

**Comment by pjcozzi** [comment]
I don't think there are any other actions here.
