### ISSUE TITLE
glTF-webgl-viewer is stop working when iOS's os upgraded to iOS10 on safari

### ISSUE THREAD

**Issue by bhoske** [KhronosGroup/glTF#735]
When I tried to load url on iPad Air 2 in safari browser, gltf-viewer crashes/not working.

Tried with code on GitHub on following link-  https://github.com/montagejs/glTF-webgl-viewer
url : https://threejs.org/examples/webgl_loader_gltf.html

**Comment by bhoske** [comment]
After debugging, I have come to know that canvas is resizing at the time of rendering. canvas resizes due to texture mapping. Images have different size which will cause to canvas resize. it might be a issue. 
Also in iOS 10 release, it is mentioned that getContext will be call up to the 16 time only. These might be a issue to crash the link. 
So anybody have any idea or workaround to these, please put on post.
It will help me lot.

**Comment by pjcozzi** [comment]
@bhoske you may want to submit an issue to the glTF-webgl-viewer repo; I don't think anyone active in this repo follows that project (which also looks like it has not been updated in a while).

**Comment by bhoske** [comment]
@pjcozzi thanks for reply. Yes, Repo glTF-webgl-viewer was removed long back from "KhronosGroup". I was following that one. Just I was curious about glTF-viewer development activity. Also I failed to find repo of glTF viewer with release of gltf 1.0. 
 Any way thanks your feedback.

**Comment by emackey** [comment]
@bhoske The old glTF-webgl-viewer is obsolete and un-maintained.  Modern examples of glTF loading can be found in @cx20's repo:

https://github.com/cx20/gltf-test
