### ISSUE TITLE
FlipY flag in gltf ? 

### ISSUE THREAD

**Issue by AurL** [KhronosGroup/glTF#736]
Hi,

I have a question regarding this point in the glTF spec:

> **Implementation Note**: With WebGL API, the first pixel transferred from the `TexImageSource` (i.e., HTML Image object) to the WebGL implementation corresponds to the upper left corner of the source. Non-WebGL runtimes may need to flip Y axis to achieve correct texture rendering.

Do we really expect _almost_ all the 3D softwares to flip all their textures to fit this model so that referenced images are correctly oriented in the output glTF file?
Is there any plan on adding a flag to know if a texture actually needs to have the Flip-Y flag enabled?

I understand that glTF is built closely to OpenGL spec (that uses top/left corner as image origin), but when we think about it's use as transport format by 3d softwares (and also as a replacement of the proprietary FBX format), this point seems to bring a limit that could be seen as a real drawback.

What's the actual reason doing this ? Maybe I am missing something?

Any detail is welcome, thanks for your time!

**Comment by lexaknyazev** [comment]
glTF 1.0 targets mainly WebGL 1.0. Next version of the format should have pixel transfer flags.

**Comment by lexaknyazev** [comment]
Also see #674.

**Comment by donmccurdy** [comment]
I'm working on PBR support in THREE.GLTFLoader, and noticing that the Sketchfab/Unity glTF exporter [includes a `flipY` flag](https://github.com/sketchfab/Unity-glTF-Exporter/blob/master/GlTF_Texture.cs#L37).

Is this intended for the spec, or should I file a bug with the exporter?

**Comment by AurL** [comment]
It not intended for the spec or a bug actually. At the moment of the development, we added this flag in order to know what was the orientation of the textute. We added this flag as a fallback as we were generating files from Unity that has it set to true (contrary to glTF that has it false) 
It's not official, as mentionned in the README.

Moreover, materials doesn't perfectly fit the specification of the PBR extension. For example, we split metalness and roughness into two distinct textures. 

This code is being updated to fit with the progress of glTF 2.0, but for now you might find some out-of spec contents in our files

**Comment by donmccurdy** [comment]
Ok great, thanks!

**Comment by pjcozzi** [comment]
Thanks for the quick response, @AurL.  @donmccurdy we're really looking forward to glTF 2.0 support in three.js!

@lexaknyazev OK to close this?

**Comment by lexaknyazev** [comment]
Yes, this could be closed and texture origin should be defined as a part of #835.
