### ISSUE TITLE
Support Morph animation or Shape keys?

### ISSUE THREAD

**Issue by ar53n** [KhronosGroup/glTF#737]
Hello, i want create animation with shape keys or morph and use collada2gltf, but not worked. If not, whether such a possibility is planned?

**Comment by lexaknyazev** [comment]
There was a discussion about morph support (#210) but it didn't make into 1.0 spec.
It's possible that future version of glTF will support this feature.

Anyway, such functionality could be proposed via [extensions](https://github.com/KhronosGroup/glTF/tree/1.0.1/extensions) mechanism. Do you want to draft something up?

**Comment by pjcozzi** [comment]
We see this as an important feature; it didn't make 1.0 simply due to scope and timing.  +1 if you are up for proposing the schema.

**Comment by lexaknyazev** [comment]
@pjcozzi OK to close this?

**Comment by pjcozzi** [comment]
Yes, closing as duplicate with #210.
