### ISSUE TITLE
File extensions for external shaders

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#738]
While it's not required to use any specific filename extension for shader files, could we recommend usage of `.frag`/`.vert` instead of `.glsl`?

This could simplify pipeline integration with [glslang](https://github.com/KhronosGroup/glslang#execution-of-standalone-wrapper).

**Comment by javagl** [comment]
I wasn't aware that a reasonable convention existed here - I've seen `glsl`, `frag`/`vert`, `fs`/`vs`, `glslv`/`glslf` and others. (And I fell guilty of using `glsl` as well).

The *recommentation* to use `vert`/`frag` could certainly be mentioned somewhere. 

Related: http://stackoverflow.com/q/6432838

**Comment by pjcozzi** [comment]
Is this really worth the change?  Should glslang integration really drive us to change this when after dozens of implementations, this has not been a concern?

We are making fixes for 1.0.1, but we have to be careful that we just don't put every arbitrary change on the table.

**Comment by lexaknyazev** [comment]
`.glsl` file extension prevents tools from knowing shader language grammar until glTF is loaded. Anyway, this could be done later within each API extension (#733).

**Comment by pjcozzi** [comment]
Is it worth discussing this as part of KHR_technique_webgl?

**Comment by lexaknyazev** [comment]
Yeah, we should also ensure that shader sources could be loaded from bufferViews.

**Comment by lexaknyazev** [comment]
It's been decided that shader files can have any extension.
