### ISSUE TITLE
Clarification of transform order

### ISSUE THREAD

**Issue by erich666** [KhronosGroup/glTF#743]
In the [transforms section](https://github.com/KhronosGroup/glTF/blob/master/specification/README.md#transforms) it is probably worth adding something along the lines that "The TRS order means that first the scale is applied to the object's data, then the rotation, then the translation, to get the world position of the model." This is the norm, 90% of implementors will get it right, but we should go for 100%.

I would also, to emphasize this, put the code example in order of scale, rotation, and translation, not in the rotation, scale, translation order it's currently given.

```
    "rotation": [
        0,
        0,
        0,
        1
    ],
    "scale": [
        1,
        1,
        1
    ],
    "translation": [
        -17.7082,
        -11.4156,
        2.0922
    ]
```

Change to

```
    "scale": [
        1,
        1,
        1
    ],
    "rotation": [
        0,
        0,
        0,
        1
    ],
    "translation": [
        -17.7082,
        -11.4156,
        2.0922
    ]
```

It may be worth noting that the order TRS (reversed) is _always_ used, regardless of the order of the transforms in the file itself. This is often a point of confusion for my students using three.js, that the order they set these transforms does not influence the order in which these are applied.

If you really wanted to get fancy, I'd give an interesting set of scales, rotation, and translation (right now scale and rotation are default "do nothing"), and then also give the corresponding matrix that would do the equivalent concatenated transform. This then can help implementors as a reality check.

**Comment by javagl** [comment]
I also stumbled over this (and think that I saw a "wrong" implementation a while ago (was it in three.js? not sure about that). This point has explicitly been addressed in a recent commit https://github.com/KhronosGroup/glTF/commit/eb4afeaae8c3d9e320b84906d10b368cc0f26b3e but indeed, the example could be updated as well.

**Comment by erich666** [comment]
Thanks for the confirmation that it's not just me. Three.js is TRS (that is, read from right to left: scale first, then rotate, then translate).  [This lesson on](https://www.udacity.com/course/viewer#!/c-cs291/l-91073092/m-117955991) covers that. There's some Euler angle ordering that you can modify in three.js, but you can't change the overall TRS ordering. glTF doesn't have to worry about Euler angles since it uses quaternions.

**Comment by lexaknyazev** [comment]
> It may be worth noting that the order TRS (reversed) is always used, regardless of the order of the transforms in the file itself.

Wouldn't t it be too explicit, since JSON objects don't have any particular properties order? 

> If you really wanted to get fancy, I'd give an interesting set of scales, rotation, and translation (right now scale and rotation are default "do nothing"), and then also give the corresponding matrix that would do the equivalent concatenated transform. This then can help implementors as a reality check.

Sounds great! Do you want to open a PR into `master`?

**Comment by pjcozzi** [comment]
@erich666 did you see this in the spec:

> A node can have either a matrix or any combination of translation/rotation/scale (TRS) properties. TRS properties are converted to matrices and postmultiplied in the T * R * S order to compose the transformation matrix. If none are provided, the transform is the identity.

From here: https://github.com/KhronosGroup/glTF/tree/master/specification#node

Perhaps something like this needs to be in the tutorial section as well?

>> It may be worth noting that the order TRS (reversed) is always used, regardless of the order of the transforms in the file itself.

> Wouldn't t it be too explicit, since JSON objects don't have any particular properties order?

@lexaknyazev  is right that JSON objects do not define order, but for the human reader, I think this would be valuable, at least for the JSON in the spec, but probably not required for each sample model.

> Sounds great! Do you want to open a PR into master?

+1.  This would be a spec bug fix so it can go right into the 1.0 spec in master.

**Comment by erich666** [comment]
@pjcozzi I missed that, and I'm glad to see it's in there. I don't think it would hurt to say the same in the transform node section, but it's fine if you don't want to mess with it. I can also imagine implementors messing up "postmultiplied in the T * R * S order"; I like spelling it out, that the scale gets applied to the object's vertices first, then rotation, etc. The extra sentence seems worth it, IMO.

I wish I had time to submit pull requests, but sadly I have only a little time to work on this spec. Figuring out the quaternion to put for the rotation, well, I'd say there's a 50% chance I'd get the sign right without checking the matrix generated. However, for someone with a glTF viewer (hint, hint), all you do is put in a scale, a rotation, and a translation and see what the matrix is that's generated. Put those in.

**Comment by pjcozzi** [comment]
I added a spec clarification in #750.

**Comment by recp** [comment]
> Wouldn't t it be too explicit, since JSON objects don't have any particular properties order?

Associative arrays dont guarantee order but afaik indexed arrays do that,

we can build final matrix with something like this without check every transform name
e.g. if (node.scale != null) then ... if (node.rot != null)...
```
"transform": [
	{"name": "scale",       "val": [1, 1, 1]},
	{"name": "rotation",    "val": [0, 0, 0, 1]},
	{"name": "translation", "val": [-17.7082, -11.4156, 2.0922]},	
	{"name": "skew",        "val": [45.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0] },	
]

// this will be defined once
var transformMap = {
	"scale": function(data) {
		var matrix = [
			[data[0], 0, 0, 0], 
			[0, data[1], 0, 0], 
			[0, 0, data[2], 0],
			[0, 0,       0, 1]
		];
		
		/* build scale */
		return matrix;
	}, 
	"rotation": function(data) {
		/* build rotation from euler or quat */
		return matrix;
	},
	"translation": function(data) {
		/* build translation matrix or just translate immediately */
		return matrix;
	}
}

var matrix = IdentityMatrix;
for (int i = 0; i < transform.length; i++) {
	mat4_mul(matrix, transformMap[transform.name](transform.val));
}
```

**Comment by javagl** [comment]
@recp It may be an overly specific question, but: Which matrix library does this refer to? I'm asking because when I wrote a basic viewer using http://glmatrix.net/ , I noticed that there are dedicated methods for creating the final matrix, based on the presence of the TRS elements - and they are suspectedly more efficient than a sequence of multiplications. 

---

Right now, I'm using

    function computeLocalMatrix(nodeId) {
        var gltf = that.gltf;
        var node = gltf.nodes[nodeId];

        var localMatrix = glm.mat4.create();
        if (isDefined(node.matrix)) {
            glm.mat4.copy(localMatrix, node.matrix);
            return localMatrix;
        }

        if (isDefined(node.rotation)) {
            var translation = optional(node.translation, [0, 0, 0]);
            if (isDefined(node.scale)) {
                glm.mat4.fromRotationTranslationScale(localMatrix, node.rotation, translation, node.scale);
            } else {
                glm.mat4.fromRotationTranslation(localMatrix, node.rotation, translation);
            }
        } else {
            if (isDefined(node.translation)) {
                glm.mat4.translate(localMatrix, node.translation);
            }
            if (isDefined(node.scale)) {
                glm.mat4.translate(localMatrix, node.scale);
            }
        }
        return localMatrix;
    };

but still have to review this....

**Comment by recp** [comment]
@javagl I just tried to propose that all transforms could be located in "transform" node like in my comment, then we wouldnt need to test every indiviual transform existence and order element like `computeLocalMatrix` did.

**Comment by pjcozzi** [comment]
I _think_ the spec and tutorial are in good enough shape here.  Please comment...or better yet, open a pull request...if you think otherwise.

**Comment by agneet42** [comment]
Hi. So if I have a matrix as such, could someone tell me which correspond to translation? Thanks!

``` 
matrix: [   -0.99975,
                -0.00679829,
                0.0213218,
                0,
                0.00167596,
                0.927325,
                0.374254,
                0,
                -0.0223165,
                0.374196,
                -0.927081,
                0,
                -0.0115543,
                0.194711,
                -0.478297,
                1
            ]

**Comment by javagl** [comment]
This is explained, to some extent, in the [Local Transforms Of Nodes section of the tutorial](https://github.com/javagl/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_004_ScenesNodes.md#local-transforms-of-nodes). Strictly speaking, the translation will be given by the last elements of the matrix:

                -0.0115543,
                0.194711,
                -0.478297,
                1

meaning that it will translate about (-0.0115, 0.19, -0.47) in (x,y,z)-direction, **but** note that the matrix contains other transformations as well. For example, it has a scaling component along the x-axis (-0.99975, the first entry), so the overall transform that is described by this matrix is more than just a translation.

**Comment by agneet42** [comment]
@javagl thanks. That's what I needed to know!
