### ISSUE TITLE
"meshes" and "primitives" versus "models" and "surfaces"

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/glTF#744]
Currently a glTF file stores "meshes" where each mesh stores an array of "primitives". This would make sense except that in common graphics terminology a primitive is the simplest geometric object the system can handle, which would be a point, line or triangle. However, in glTF each primitive is a mesh itself. Wouldn't it make more sense to rename "meshes" to "models" and "primitives" to "surfaces". At least that would make a lot more sense for any artist I've ever worked with.

**Comment by javagl** [comment]
This can, indeed, be confusing (c.f. https://www.opengl.org/wiki/Primitive ), but it's unlikely that such a compatibility-breaking change will be integrated.

**Comment by mre4ce** [comment]
It seems reasonable to bring this up considering there's are a number of backwards compatibility breaking changes being discussed.

**Comment by pjcozzi** [comment]
I haven't been 100% thrilled with the terminology either, but I think this will be a tough sell to change for a minor revision unless there is strong support from the community; the breaking changes are generally because something was wrong or overly complex.

**Comment by pjcozzi** [comment]
@lexaknyazev from a practical perspective, perhaps not worth it at this point?

**Comment by lexaknyazev** [comment]
Not before glTF 3.0.
