### ISSUE TITLE
Remove node.matrix

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/glTF#745]
A node can currently store a separate translation, rotation and scale or it can store a matrix. I vote for removing the matrix because it forces an implementation to implement code to decompose the matrix into a separate translation, rotation and scale in case an animation only changes some but not all three. Afaik this is the only reason to even have code to decompose a matrix. If for some reason source data stores matrices then it'd be better to do the decomposition in the converter as opposed to adding complexity to the glTF format.

**Comment by lexaknyazev** [comment]
Can `node.matrix` contain something besides TRS (such as skew)?

**Comment by pjcozzi** [comment]
Engines should not need to decompose the matrix for animation; the spec requires that when a node is targeted for animation that it uses TRS since animations can only target those properties.

@mre4ce would you be OK with just a spec update here that make this more explicit?

**Comment by mre4ce** [comment]
Making this more explicit in the spec would be good thanks. I would still prefer to get rid of node.matrix just to reduce complexity but keeping it is not the end of the world :)

**Comment by pjcozzi** [comment]
I added a spec clarification in #750.

**Comment by donmccurdy** [comment]
Addressed in glTF 2.0.
