### ISSUE TITLE
Playing back the same animation on different sub-trees.

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/glTF#748]
A skin allows us to "attach" the same mesh to different sub-trees.

Is there a way to play back the same animation on different sub-trees, in particular with a different time offset?

To reduce storage you could have multiple animations that use the exact same source data but map to different nodes. Is that the correct way of thinking about this?

**Comment by lexaknyazev** [comment]
There's no way (in 1.0) to specify animation's behaviors, such as: loops, time offsets, auto-start, etc.
Default is to treat `input` accessor data as global timeline. However there were requests to add those features.

> To reduce storage you could have multiple animations that use the exact same source data but map to different nodes

I see nothing wrong with several `animation` objects using the same accessors.

**Comment by mre4ce** [comment]
Thanks for the quick response!

It quickly leads down the rabbit hole where you want animation blending, additive and subtractive animations, lead-in and lead-out animations, animation syncing, blend trees etc. I think simple global animations was the right call for 1.0 but it's probably worth thinking about future extensions.

**Comment by donmccurdy** [comment]
Merging this issue into https://github.com/KhronosGroup/glTF/issues/1448.
