### ISSUE TITLE
hint about interleaved vertex attributes in mesh

### ISSUE THREAD

**Issue by fabrobinet** [KhronosGroup/glTF#75]
As a developer, I'd like to know if the vertex attribute are interleaved without having to walkthrough strides/byteOffset to figure out. Then you need to know which is the attribute that goes first, a consequence might to have to use an array in semantics instead of map. Which for this specific case will make the client code easier anyway.

**Comment by pjcozzi** [comment]
This hasn't come up in several years so closing.  Please comment if anyone has a new use case...maybe and wants to contribute. 😄
