### ISSUE TITLE
Where is the latest version of O3DGC?

### ISSUE THREAD

**Issue by adishavit** [KhronosGroup/glTF#751]
Where are the latest file of O3DGC? 
Are they in the [`glTF/COLLADA2GLTF/dependencies/o3dgc/`](https://github.com/KhronosGroup/glTF/tree/master/COLLADA2GLTF/dependencies/o3dgc) folder or the `https://github.com/amd/rest3d` repo?
What is the status of O3DGC? 
Is it being actively worked on? Is it an integral part of glTF now?

**Comment by pjcozzi** [comment]
@adishavit the latest on this work is in #398.  It has not been investigated in over a year, but we welcome you to pick up and run with it.

**Comment by adishavit** [comment]
I found a memory leak bug in `TriangleListDecoder`. 
What repo do I need to make my PR to?

**Comment by pjcozzi** [comment]
@adishavit see https://github.com/KhronosGroup/glTF/pull/756#issuecomment-256768780
