### ISSUE TITLE
design discussion

### ISSUE THREAD

**Issue by RemiArnaud** [KhronosGroup/glTF#76]
Here's some excerpt from the duck.json file.

```
"meshes": {
        "LOD3spShape-lib": {
            "attributes": {
```
meshes is an object. Container for meshes.
'LOD3spShape-lib' is a mesh. So mesh root are their id string.

```
"attributes": {
                "attribute_18": {
```
same idea. attributes is a container, 'attribute_18' is an attribute, its root is its id

```
  "primitives": [
                {
                    "primitive": "TRIANGLES",
```
primitives is an array of weakly typed (as opposed to an object)
primitives are weakly typed. primitives do not have an id

why not this instead (strongly typed primitive)
```
"primitives" : {
    triangles : {
``` 

of maybe, we should give names to primitives?
```
 "primitives" : {
    "name_of_primtive" : {
        "primitive":"TRIANGLES"
```
Should'nt "primitive" renamed "type" ?

------

```
 "parameters": {
   "ambient": {
      "type": "FLOAT_VEC3",
```
parameters is a container of parameters. An object
'ambient' is a parameter. parameter root are the name of the parameter.

following strong typing design, this could be:
```
 "parameters": {
    "FLOAT_VEC3": {
        "name": "ambient",
```

but parameters can have a sid, so they can be the target of animations.
so maybe it should be:

```
"parameters": {
  "sid_of_parameter": {
       "type": "FLOAT_VEC3",
       "name": "ambient",
```

**Comment by pjcozzi** [comment]
Covered by https://github.com/KhronosGroup/glTF/issues/38#issuecomment-140764652
