### ISSUE TITLE
PBR student project ideas

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#763]
One of our students at Penn, @moneimne, plans to do their senior design project on glTF PBR (basically starting now-ish through May 2017) so I just want to take inventory on what he could contribute to.

_Please comment with ideas!_

* [ ] Gentle introduction to PBR tutorial, [glTF-Tutorials](https://github.com/KhronosGroup/glTF-Tutorials)
   * Could be a great warm-up project.
* [ ] [gltf-pipeline](https://github.com/AnalyticalGraphicsInc/gltf-pipeline) stage to generate GLSL shaders from PBR materials that can serve as a reference implementation.
   * What other content pipeline stages would be broadly useful to the community, e.g., for IBL?
* [ ] Full reference PBR viewer.  A few folks are already working on this: https://github.com/KhronosGroup/glTF/issues/697.  Still plenty to do.
* [ ] Add PBR to the Cesium glTF loader.
   * The Cesium team would be happy to help.
* [ ] Exporter support like contributing PBR to the [Blender glTF exporter](https://github.com/Kupoman/blendergltf).
   * Could be hard; I have no experience with Blender.
* [ ] Finalize the PBR extension spec (and related glTF spec changes), #643 and friends labeled [PBR](https://github.com/KhronosGroup/glTF/labels/PBR)
   * Perhaps not the best student project, but he could contribute input from his implementation experience.

@mlimper @erich666 @cedricpinson @lexaknyazev @emackey

**Comment by mlimper** [comment]
> What other content pipeline stages would be broadly useful to the community, e.g., for IBL?

Good question - IIRC some comments where made that IBL shouldn't be part of the spec (at least not part of the PBR extension), but of course that doesn't mean it wouldn't be useful to have tools for it.

> Full reference PBR viewer. A few folks are already working on this: #697. Still plenty to do.

Some support would be helpful - it might take some more days to sort out what could be separate tasks in this context, in the meanwhile your student could maybe already join our conversation in #697?

**Comment by pjcozzi** [comment]
CC @moneimne, the Penn student.

**Comment by cedricpinson** [comment]
blender export with good support of gltf and PBR is important. Blender is not so hard I did an exporter in the past. So as osg format is kind of similar it could used to see how it is done. https://github.com/cedricpinson/osgexport/

**Comment by mlimper** [comment]
@moneimne Do you have some bandwidth to contribute to the PBR example application (https://github.com/KhronosGroup/glTF/issues/697)?

**Comment by moneimne** [comment]
Yes, I'd love to help in any way I can. I read through #697 and it seems like you have already gone through a couple iterations of examples. Is there anything specific you had in mind that I could contribute with?

**Comment by mlimper** [comment]
> Yes, I'd love to help in any way I can

Great!

> Is there anything specific you had in mind that I could contribute with?

Yes! We were considering a runtime filtering of the environment map, as described [here](https://placeholderart.wordpress.com/2015/07/28/implementation-notes-runtime-environment-map-filtering-for-image-based-lighting/).
With my [latest commit](https://github.com/tsturm/glTF/commit/99491975663ec7ba1f21f5125e2aeea55da198ad) (already over two weeks ago), I added very basic support of an environment map. However, the actual hard work isn't done, which is the "correct" filtering of the environment map during runtime. If you could provide me with your email address (for example mailing to max.limper( at )igd (dot) fraunhofer(dot) de), I could also provide some example code.

**Comment by moneimne** [comment]
My email address is moneimne(at)seas(dot)upenn(dot)edu. 

I read through the linked article on runtime environment map filtering, but it may take me some time to familiarize myself with the techniques used. Do you have an approximate timeline that you expect the example application to follow?

**Comment by mlimper** [comment]
> Do you have an approximate timeline that you expect the example application to follow?

There is no hard timeline. Having this until the holidays could be nice, however ;-)

**Comment by pjcozzi** [comment]
Thanks again for everyone's input.

Closing this as a duplicate with @moneimne's roadmap: https://github.com/moneimne/WebGL-PBR/issues/1
