### ISSUE TITLE
Can not compile CSharp loader

### ISSUE THREAD

**Issue by OstryEU** [KhronosGroup/glTF#782]
I tried to compile 
glTF/loaders/CSharp/CSharp.sln
without success.

First problem I run into was:
glTF\loaders\CSharp\Generator\Program.cs
Row: 10
            var generator = new CodeGenerator(@"..\..\..\..\..\specification\schema\glTF.schema.json");
here is now "1.0", part of the path ( .
This one is easy to fix to:
            var generator = new CodeGenerator(@"..\..\..\..\..\specification\1.0\schema\glTF.schema.json");

The real problem is I get an Newtonsoft.Json.JsonReaderException parsing "glTF.schema.json" with following message:

Error reading string. Unexpected token: StartArray. Path 'dependencies.scene', line 207, position 20.

Any ideas, anyone?

**Comment by lexaknyazev** [comment]
C# Loader hasn't been updated for JSON-Schema v4 yet.
As a temporary solution, you can use v3 schemas from [this state](https://github.com/KhronosGroup/glTF/tree/28a68e86455af8d9d0be4ec8cefe8dc48f59e064/specification/schema).

**Comment by MattMcMullan** [comment]
I've got some local changes now that fix the problems with the parser.  The
code gen still needs some work. Progress is being made. I'll send a pull
request when it's all working again.

-Matt

**Comment by feliwir** [comment]
Another question: Will the Nuget package receive .NET core support eventually?

**Comment by pjcozzi** [comment]
> Will the Nuget package receive .NET core support eventually?

@sbtron do you know?

Otherwise, OK to close this?

**Comment by bghgary** [comment]
C# loader already supports .NET standard and has a new version on NuGet.
