### ISSUE TITLE
Should PBR be required in glTF Next?

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#785]
via @lexaknyazev 

> Considering that the lowest possible glTF support is geometry only, should we treat all material models (incl. PBR) as Khronos-defined extensions (like window managers in Vulkan)?

**Comment by emackey** [comment]
My vote is no.  If the core spec ships without a specific core material system, we won't reach an interoperable state where a generic glTF authoring system can produce complete working models for generic glTF rendering engines.

Granted there are so many players in glTF space now, that convergence appears difficult to attain.  Whatever system is chosen is never going to live up to everyone's expectations, not even as a lowest common denominator kind of system.  These high-expectation folks can go ahead and require their extensions with whatever they need, but their presence here should not thwart efforts to make a commonly usable format that can do better than a simple diffuse map.  The world needs a standard for transmitting and delivering models with at least mediocre modern shading, such as having a normal map.  It's almost 2017 and we still don't have a standard format for sharing models that include normal maps between unrelated applications.

**Comment by lexaknyazev** [comment]
Let me provide some context for this question from WG discussion.

Right now, glTF minimal conformance is defined (somewhere) as geometry-only. 
So, strictly speaking, runtime that supports only buffers/bufferViews/accessors/meshes can call itself glTF-conformant. 

If we really want to achieve interoperability, we should define glTF conformance a bit different.

We came up with several possible strategies:

1. Keep material model as an extension (formally), but develop it side-by-side with "glTF Next", release and ratify it under Khronos prefix simultaneously with the core spec, support it in all reference tools/implementations. Also such extension would be strongly encouraged for common usecases.

2. Define materials model as mandatory part of spec, require its support for "glTF Next"-conformance.

3. Define materials model as mandatory part of spec, define different conformance levels. Possibly define fallback behavior for runtimes that don't support materials.

**Comment by xelatihy** [comment]
My 2cents: 3. seems the best option.
