### ISSUE TITLE
glTF 2.0 buffer: does it need a type?

### ISSUE THREAD

**Issue by xelatihy** [KhronosGroup/glTF#786]
The buffer schema for glTF 1.1 in glTF/specification/1.1/schema/buffer.schema.json has an enum with only one possible value for the parameter value. Since only one value is possible, is this useful?

**Comment by javagl** [comment]
Some history behind this: https://github.com/KhronosGroup/glTF/issues/629  

Roughly: It once was allowed to also have the type `"text"`, but this is no longer supported. The property itself might only be kept for backward compatibility (to cope with `"additionalProperties" : false`), but maybe there will still be other buffer types in the future.

**Comment by lexaknyazev** [comment]
That field is meant to be linked with XHR's `responseType` (more info on [WHATWG](https://xhr.spec.whatwg.org/#the-responsetype-attribute) and [MDN](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Sending_and_Receiving_Binary_Data)):
```javascript
var oReq = new XMLHttpRequest();
oReq.open("GET", "buffer.bin", true);
oReq.responseType = "arraybuffer"; // <-- buffer.type

oReq.onload = function (oEvent) {
  var arrayBuffer = oReq.response;
    // ...
};

oReq.send(null);
```

`"text"` value existed for possible ASCII-based encoding of buffer data (with browser-provided gzip compression), however we don't have one in the core spec yet.

@pjcozzi what do you think of removing `buffer.type` completely?

**Comment by pjcozzi** [comment]
@xelatihy good eye, thanks.

@lexaknyazev +1 from me.

**Comment by pjcozzi** [comment]
@lexaknyazev I am in support of this?  Is this spec updated so we can label this `resolved`?

**Comment by lexaknyazev** [comment]
Spec and README.md updated.

**Comment by pjcozzi** [comment]
Great, thanks!

**Comment by pjcozzi** [comment]
Updated in #826
