### ISSUE TITLE
Update KHR_binary_glTF benchmark

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#790]
@pjcozzi 

- [ ] [Benchmark data](https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_binary_glTF/BenchData) for `KHR_binary_glTF` are based on Chrome version 43 (May 2015). Considering ever-changing nature of JS VMs, we should recheck [those numbers](https://github.com/KhronosGroup/glTF/tree/master/extensions/Khronos/KHR_binary_glTF/BenchData#detailed-results) and measure loading time on other platforms (at least: Firefox/Desktop, Safari/iOS, Chrome/Android).

- [ ] We should provide cmd-line scripts for auto-converting COLLADA files.

- [ ] Is it possible to add those models to glTF-Sample-Models repo?

**Comment by javagl** [comment]
Just a thought:

- [ ] Extend the benchmark to also cover optimizations that are done by the gltf-pipeline

(I haven't found many systematic benchmarks for this, and although https://cesiumjs.org/2016/08/08/Cesium-web3d-quantized-attributes/ is a start, I still wonder whether there are dedicated benchmarks regarding the performance (e.g. for reducing the number of draw calls))

**Comment by donmccurdy** [comment]
Closing as obsolete.
