### ISSUE TITLE
convert error

### ISSUE THREAD

**Issue by xuncanzhe** [KhronosGroup/glTF#800]
The error message occurs during the conversion. "Inconsistency error: this asset probably refers to invalid image Ids within <surface>". I can use other software to open the dae file. Could you help me determine the cause of the problem? convert tool or dae file. No exception hint when compiling the [tool.（centos7）

OneDrive file url: https://1drv.ms/u/s!AkXxHoUK23z6hOUF90HpSuQm76K-Vg

**Comment by pjcozzi** [comment]
Replaced by https://github.com/KhronosGroup/COLLADA2GLTF/issues/129
