### ISSUE TITLE
Investigate Draco as a mesh/point compression extension

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#816]
https://opensource.googleblog.com/2017/01/introducing-draco-compression-for-3d.html

Decode time doesn't look great, but perhaps this is similar to Open3DGC, #398

@mlimper do you have any experience here?

**Comment by mlimper** [comment]
No experience yet, just learning about it.

Looks like they are also able to compress mesh connectivity with two different methods, where one of the is the "classic" Edgebreaker algorithm (encoder code [here](https://github.com/google/draco/blob/master/compression/mesh/mesh_edgebreaker_traversal_predictive_encoder.h))

From the sources:
```
// The mesh connectivity data can be encoded using two modes that are controlled
// using a global encoder options flag called "compress_connectivity"
// 1. When "compress_connectivity" == true:
//      All point ids are first delta coded and then compressed using an entropy
//      coding.
// 2. When "compress_connectivity" == false:
//      All point ids are encoded directly using either 8, 16, or 32 bits per
//      value based on the maximum point id value.
```

Getting a reasonable local ordering and then storing deta via deltas with some entropy coding is a pretty established approach, but you'll always have to make sure that your decoding will still fast enough to be worth the effort. [WebGL-loader](https://code.google.com/archive/p/webgl-loader/) previously used zigzag coding of the deltas and UTF8 encoding to get some cheap variable-length coding method that already works well in the browser, as it is supported natively (you probably know the OpenGL insights article). Here, it looks like they are using [Emscripten](https://github.com/google/draco#javascript-decoder) to get a very optimized, fast decoder in JS.

**Comment by kmammou** [comment]
A compaison of Open3DGC vs Draco is available here http://kmamou.blogspot.ca/2017/03/open3dgc-vs-draco.html

**Comment by pjcozzi** [comment]
CC @jbrettle @FrankGalligan

**Comment by pjcozzi** [comment]
Replaced with #874.
