### ISSUE TITLE
Extensions schema requires objects

### ISSUE THREAD

**Issue by agrittmsft** [KhronosGroup/glTF#823]
The [extensions schema](https://github.com/KhronosGroup/glTF/blob/master/specification/1.0/schema/extension.schema.json) requires that the value of every property be an object. This has the effect of disallowing the following:

```
{
  "extensions" : {
    "KHR_extension_1" : {
       "foo" : "bar"
    },
    "KHR_extension_2" : [
      1,
      2,
      3
    ]
  }
}
```

I can't see any requirement for extension properties to be objects in the specification. Please could you clarify whether this is intended or whether that constraint should be removed from the schema?

**Comment by pjcozzi** [comment]
@agrittmsft thanks for the report, the intent is that each property in `extensions` has to be an object, but each sub-property (e.g., `foo` in the above example) can be anything the extension wants.

If you just want to store application-specific properties, use the `extras` property, which has no constraints.
