### ISSUE TITLE
glTF 2.0 asset profiles and caps

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#829]
With glTF 2.0 API-neutrality, we should review current signaling of expected platform capabilities.

Here're relevant parts:
```json
{
    "asset" : {
        "version" : "2.0",
        "premultipliedAlpha" : true,
        "profile" : {
            "api" : "WebGL",
            "version" : "1.0",
        }
    },
    "glExtensionsUsed": [
        "OES_element_index_uint"
    ]
}
```

1. Is `premultipliedAlpha` still relevant for GLSL-less materials?

2. Can we move `glExtensionsUsed` to `asset.profile`? `OES_element_index_uint` makes sense for WebGL 1.0, but must be implied with possible WebGL 2.0 profile.

At the current moment, 32-bit indices support is the only major platform issue for glTF assets, since we store raw vertex and index data. Rendering such asset on a platform without 32-bit indices support will require costly CPU processing.

**Comment by javagl** [comment]
Regarding the `glExtensionsUsed`, a pointer to the discussion about a pull request that is strongly related to this point: https://github.com/KhronosGroup/glTF/pull/807#issuecomment-271094983 - it might be that this property becomes obsolete with a more generic approach.

**Comment by lexaknyazev** [comment]
I totally agree with per-shader extension specifying when custom shaders are used, but I'm not sure how to address this issue with glTF 2.0 core.

**Comment by pjcozzi** [comment]
@sbtron do you have any input here?

> Is premultipliedAlpha still relevant for GLSL-less materials?

I _think_ it is not required without GLSL.

> Can we move glExtensionsUsed to asset.profile? OES_element_index_uint makes sense for WebGL 1.0, but must be implied with possible WebGL 2.0 profile.

OK with me.

**Comment by sbtron** [comment]
Yes premultipliesAlpha doesn't make sense without GLSL shader. Maybe it can go along with the glsl shader extension?
Similarly with glExtensionUsed could be included in the glsl extension. 
For the 32bit indices we could just say the glTF core can have a valid enum for 5125 (UNSIGNED_INT) and not require glExtensionUsed to be specified anymore.

**Comment by lexaknyazev** [comment]
> For the 32bit indices we could just say the glTF core can have a valid enum for 5125 (UNSIGNED_INT) and not require glExtensionUsed to be specified anymore.

Not all OpenGL ES 2.0 hardware support 32bit indices (e.g., ARM Mali-400). Moreover, on supported platforms such functionality must be enabled explicitly.

**Comment by lexaknyazev** [comment]
What do you think of adopting Vulkan approach to signaling required feature set? I.e., assume WebGL 1.0 features as a universal core and require everything else explicitly.

Just example:
```json
{
    "asset" : {
        "version" : "2.0",
        "features" : [
            "UINT_INDICES",
            "ES3_VERTEX_FORMATS"
        ]
    }
}
```

Vulkan manpage:
https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkPhysicalDeviceFeatures.html

**Comment by pjcozzi** [comment]
Vulkan approach is OK with me.  @sbtron likely has the best experience to say what will scale well.

**Comment by lexaknyazev** [comment]
@pjcozzi @sbtron 
Please confirm `asset` scheme for 2.0 (`profile` and `premultipliedAlpha` removed):

```json
{
    "asset" : {
        "version" : "2.0",
        "generator": "collada2gttf",
        "copyright": "©2017 Khronos Group"
    }
}
```

**Comment by sbtron** [comment]
yes this looks good.

**Comment by pjcozzi** [comment]
+1

**Comment by pjcozzi** [comment]
Updated in #826
