### ISSUE TITLE
glTF 2.0: should `channel.target.id` be `channel.target.node`?

### ISSUE THREAD

**Issue by dgough** [KhronosGroup/glTF#834]
In the glTF 2.0 spec, `channel.target` is described as:

> *Channels* connect the output values of the key frame animation to a specific node in the hierarchy. A channel's `sampler` property contains the index of one of the samplers present in the containing animation's `samplers` array. The `target` property is an object that identifies which node to animate using its `id` property, and which property of the node to animate using `path`. Valid path names are `"translation"`, `"rotation"`, and `"scale"`.

```json
"channels": [
    {
        "sampler": 0,
        "target": {
            "id": 1,
            "path": "rotation"
        }
    },
```

I was thinking perhaps `"id"` should instead be `"node"` in the channel target. The word `"id"` makes it look like that is the id of the "target" object instead of the index of the node that it is targeting. 

```json
        "target": {
            "node": 1,
            "path": "rotation"
        }
```

I think this makes it clearer that the node at index 1 is being targeted. 

* `channel.sampler` points to a `sampler`
* `bufferView.buffer` points to a `buffer`
* `accessor.bufferView` points to a `bufferView`
* `primitive.material` points to a `material`
* but `channel.target.id` points to a `node`

In a future version of glTF, you might want to be able to target things other than nodes.

**Comment by lexaknyazev** [comment]
+1.

For 2.0 we also need to target morphs.
CC @emilian0

**Comment by pjcozzi** [comment]
+1
