### ISSUE TITLE
split .gltf files to improve initial loading

### ISSUE THREAD

**Issue by duchangyu** [KhronosGroup/glTF#837]
Hi, 

When *.gltf file is getting larger and larger, it takes time to load the gltf file first and then reading *.bin file.  For example,  when gltf is as large as 30M, it may take seconds to download it first without   showing anything. It is too long for initial loading. 

Is there any way to improve the initial loading performance? For example, split large gltf into serval small linked gltf files? 

Thanks,
Daniel

**Comment by pjcozzi** [comment]
@duchangyu thanks for the idea.  See the discussion in #37.

This is not part of the current spec nor is it in the scope for glTF 2.0, but you could add a small container format pointing to several glTF files or check out [3D Tiles](https://github.com/AnalyticalGraphicsInc/3d-tiles) in the meantime.

If you do any work here, let us know your thoughts in #37.  For now, I will close this as duplicate with #37.
