### ISSUE TITLE
glTF schema - uri vs uriref

### ISSUE THREAD

**Issue by bghgary** [KhronosGroup/glTF#838]
I have been trying to validate some glTF 2.0 assets using [NJsonSchema](https://github.com/NJsonSchema/NJsonSchema) for testing purposes.

NJsonSchema reports that all of my relative URIs are errors. I did some research and it seems we should be using uriref as the format in the schema instead of uri. See http://json-schema.org/latest/json-schema-validation.html#rfc.section.7.3.7

I changed it locally to do my test and now it's validating with no errors. Does anyone have more experience with this who can verify we should be using urirefs?

https://github.com/sbtron/glTF/blob/2.0/specification/2.0/schema/buffer.schema.json#L11
https://github.com/sbtron/glTF/blob/2.0/specification/2.0/schema/image.schema.json#L11

**Comment by pjcozzi** [comment]
From the description, I agree that `uriref` sounds correct.

The schema probably has `uri` because that is all that was available in JSON Schema 3 (see the valid values for [format](https://tools.ietf.org/html/draft-zyp-json-schema-03#section-5.23)).

So +1 for this change.
