### ISSUE TITLE
Add support for program pipelines (aka separable programs) to techniques

### ISSUE THREAD

**Issue by thokra1** [KhronosGroup/glTF#840]
Historically, programs where constructed as unit where each pipeline stage in use had to be attached at link time. This changes with the introduction of separable programs and the corresponding program pipelines (see [GL_ARB_separate_shader_objects](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_separate_shader_objects.txt)).

While shaders can currently be mixed in a glTF _program_, there is no possibility of separately identifying uniforms belonging to a certain pipeline stage. From what I gather, it should be trivial to at least provide essential support for program pipelines by simply adding the information to which stage a certain uniform belongs. In non-separable programs, all uniforms belong to one program - this is, obviously, not the case when programs have separate constant storage.

The alternative would be to loop over all programs currently in the system and trying to determine which uniforms are active in that program and then trying to match against technique parameters. This deminishes the usefulness of techniques when using program pipelines.

A simple solution could be to add the corresponding stage to a _parameter_ which already maps to a certain uniform:
` [..,]
  "parameters": {
    "albedoTextureParameter": {
      "type": 35678,
      "stage": 35632
    }[..,]
  }
`
This way, applying materials values that map to a techniques parameter and a certain stage in a pipeline becomes trivial.

An alternative would be to expand the _uniforms_ syntax to include not only a parameter mappings but also the corresponding stage the uniform belongs to. This, however, would probably incur compatibility issues with valid glTF 1.0 assets.

**Comment by lexaknyazev** [comment]
[glTF 2.0](https://github.com/KhronosGroup/glTF/tree/2.0/specification/2.0) moves all API-specific technique/program/shader stuff out of core spec. 
Currently, we have only [KHR_technique_webgl](https://github.com/KhronosGroup/glTF/tree/2.0/extensions/Khronos/KHR_technique_webgl) extension draft (basically cut-n-paste from 1.0 spec).

There was a proposal for supplying different versions of same shader: https://github.com/KhronosGroup/glTF/pull/807.

Also maybe relevant: https://github.com/KhronosGroup/glTF/issues/789.

Enabling support for modern pipeline building approaches is definitely on the radar for post 2.0 work.
