### ISSUE TITLE
array indices, node.jointName, and skin.jointNames

### ISSUE THREAD

**Issue by bghgary** [KhronosGroup/glTF#841]
I'm trying to convert BabylonJS's glTF loader to 2.0 and I'm running into an issue.

It looks like there is a conflict between using array indices and the way glTF references joints. Skins references joints by name via a `jointName` property on a node. But now that we are using array indices, I'm not sure how this should work. Is the intention to continue to reference by name? Should this become a joint node index that points to the node index? Or a separate joint index perhaps?

The schema currently uses integers for node.jointName and skin.jointNames which doesn't make much sense. Names are not integers :)

**Comment by javagl** [comment]
There are some pending changes from https://github.com/KhronosGroup/glTF/issues/723#issuecomment-254674004 that are already on the TODO list of https://github.com/KhronosGroup/glTF/pull/826 - I think that the core of your question is already addressed there.

**Comment by bghgary** [comment]
Perfect, thanks! Closing since it's a dupe.
