### ISSUE TITLE
Is accessor.bufferView now optional in glTF 2.0?

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF#863]
In [2.0/specification/2.0/schema/accessor.schema.json](https://github.com/KhronosGroup/glTF/blob/2.0/specification/2.0/schema/accessor.schema.json), it is not listed as required:
```
"required": ["componentType", "count", "type", "max", "min"]
```
It was required in glTF 1.0: https://github.com/KhronosGroup/glTF/tree/master/specification/1.0#accessorbufferview-white_check_mark

@sbtron do you know if this was an intention change (I couldn't find the history in GitHub) or a typo when updating the schema to JSON Schema 4?

**Comment by lexaknyazev** [comment]
Undefined bufferView means that accessor "contains" only zeros. This is used together with `sparse` field.

**Comment by lexaknyazev** [comment]
Expected use case is keyframe data for animated weights of morph targets.

**Comment by pjcozzi** [comment]
Ah, I should have looked at the git history.  Can we make this more explicit in a `gltf_detailedDescription` field?

**Comment by bghgary** [comment]
@lexaknyazev Are you planning on updating the description in the schema?

**Comment by lexaknyazev** [comment]
See #970.
