### ISSUE TITLE
Request for vendor extension prefix BLENDER

### ISSUE THREAD

**Issue by stevenvergenz** [KhronosGroup/glTF#865]
@Kupoman, @Moguri, and I are working to formalize the nascent BLENDER_physics extension, which will be used to define object properties useful to physics engines, such as mass and collision mesh. Before we can submit a pull request with the full description, we are required to reserve the vendor prefix. So what do you say?

**Comment by pjcozzi** [comment]
Sure thing, can't wait for the extension!

Added in #866.
