### ISSUE TITLE
KHR_technique_webgl and binary shaders

### ISSUE THREAD

**Issue by lasalvavida** [KhronosGroup/glTF#868]
@lexaknyazev correct me if I'm wrong or there is already something in the work for this.

Currently I don't see a defined way to point shaders in KHR_technique_webgl to a binary bufferView. This was done in 1.0 like this:

```javascript
shaders: {
  shader: {
    extensions: {
      KHR_binary_glTF: {
        bufferView: "some buffer view"
      }
    }
  }
}
```

I would propose just allowing shaders to point into the bufferView for 2.0, which seems in line with what was done for images.

```javascript
shaders: [
  {
    bufferView: 0
  }
]
```

**Comment by lasalvavida** [comment]
I can make the PR for this if necessary

**Comment by pjcozzi** [comment]
+1

> I can make the PR for this if necessary

@lexaknyazev do you have a preference?

**Comment by lasalvavida** [comment]
Bump

**Comment by pjcozzi** [comment]
@lasalvavida can you make the PR to keep momentum here?  A lot of folks are swamped with finishing other spec work.

**Comment by pjcozzi** [comment]
@donmccurdy should this be considered for KHR_technique_webgl in the short-term?  Seems like yes to stay consistent with glTF 2.0., e.g., textures can be backed by buffers instead of just image files.

**Comment by donmccurdy** [comment]
Yes, i see `bufferView` mentioned in the extension text now (with #894), probably just a matter of finishing the description of the change under the Shader object’s properties.

**Comment by lexaknyazev** [comment]
This feedback has been included into `KHR_techniques_webgl`.
