### ISSUE TITLE
GLTF Slack or Gitter

### ISSUE THREAD

**Issue by robertlong** [KhronosGroup/glTF#869]
I recently published my [GLTF Loader for Unity](https://github.com/robertlong/UnityGLTFLoader) and have been looking for a Gitter or Slack to discuss possible collaborations or ask quick questions. Could we set one up?

Twitter direct messages are fine for one on one conversations, but I'd rather be able to discuss things in detail and in public for the community to participate.

**Comment by stevenvergenz** [comment]
It's might be too narrow for this medium, but the AltspaceVR community has been using our SDK slack channel for discussion of 1.0 asset generation and consumption. I'm in favor of creating a new team for spec contributors and stakeholders though, to avoid swamping new users with technobabble.

**Comment by pjcozzi** [comment]
There was some interest in a glTF Gitter at SIGGRAPH last year.  The only concern is that the glTF working group does not have the bandwidth to provide immediate answers like that.  Generally, folks have been using issues in this repo for all things glTF, not just spec changes.

If there's enough interest and people to support it, setting up a Gitter would be great.

**Comment by recp** [comment]
> The only concern is that the glTF working group does not have the bandwidth to provide immediate answers like that.

What about emailing list for non-specs questions?

**Comment by lexaknyazev** [comment]
Since Gitter gives unlimited history and public rooms, I think we can use it for quick chats.

Using GitHub Issues is becoming inconvenient, because sometimes people create new issues just for asking one small question. Current number of issues (189) doesn't represent the number of actual spec discussions.

**Comment by pjcozzi** [comment]
OK, we'll give Gitter a try.  Hopefully the recent GitLab acquisition doesn't impact us; doesn't sound that way since they actually plan to open source it.

@outofcontrol can you please set up Gitter for this repo?

**Comment by outofcontrol** [comment]
Seems someone already made a glitter.im/KhronosGroup community area complete with our logo, to which I don't have access to change. Anyone have an idea who? It would be nice to use that as it matches our Github account.

**Comment by outofcontrol** [comment]
Resolved... I think. https://gitter.im/KhronosGroup/glTF I"ve never used Gitter before, but let me know if I need to do more here. I believe it is setup so that any member of glTF team can admin the room. Feedback on how this goes would be nice as others might want to do the same.

**Comment by pjcozzi** [comment]
Thanks @outofcontrol, this all looks great!

Links added in #881
