### ISSUE TITLE
Secondary uv sets

### ISSUE THREAD

**Issue by Fabrice3D** [KhronosGroup/glTF#871]
Is there an example that shows how secondary uv sets are defined for lightmaps?
Was looking at threejs parser, and it looks like
'TEXCOORD_0' 'TEXCOORD0' 'TEXCOORD': are all for primary uv sets.
geometry.addAttribute( 'uv', bufferAttribute );

it's obvious the parser doesn't support them while possible in the engine
geometry.addAttribute( 'uv2', bufferAttribute);

As I see It should work within the format with no problem
I just wonder what is the id expected/recommended for secondary set for wider parsers support.
'TEXCOORD_1' or 'TEXCOORD1' ???

**Comment by javagl** [comment]
Regarding the last question, the [specification says](https://github.com/KhronosGroup/glTF/tree/2.0/specification/2.0#meshes) :

> `TEXCOORD` and `COLOR` attribute semantic property names must be of the form `[semantic]_[set_index]`, e.g., `TEXCOORD_0`, `TEXCOORD_1`, `COLOR_1`, etc. 

So the expected format is that with an `_` underscore.

**Comment by Fabrice3D** [comment]
Thx, expected and added it already this way (+ other variation, such TEXCOORDS2 just in case)
