### ISSUE TITLE
glTF 2.0 buffer.uri should not be a required property

### ISSUE THREAD

**Issue by robertlong** [KhronosGroup/glTF#872]
A [GLB Stored Buffer](https://github.com/KhronosGroup/glTF/tree/2.0/specification/2.0#glb-stored-buffer) requires the uri property to be undefined. However, the spec has it as a required property.

https://github.com/KhronosGroup/glTF/blob/2.0/specification/2.0/schema/buffer.schema.json#L26

We should remove the requirement.

**Comment by lexaknyazev** [comment]
Closed with #873.

**Comment by pjcozzi** [comment]
Good eye, thanks again @robertlong!
