### ISSUE TITLE
convert osgb file to gltf?

### ISSUE THREAD

**Issue by lihuadong1988** [KhronosGroup/glTF#875]
excuse me,i want to know how to convert osgb file to gltf, is there any tools that i can use?

**Comment by ruiying** [comment]
osgb -> obj -> gltf

**Comment by pjcozzi** [comment]
If you come across anything that does a direct conversion, please open a pull request to add it to https://github.com/KhronosGroup/glTF#gltf-tools

**Comment by pjcozzi** [comment]
Related - there is also a glTF loader in OSG.JS, https://github.com/cedricpinson/osgjs/blob/master/sources/osgPlugins/ReaderWriterGLTF.js

**Comment by fanvanzh** [comment]
try my repository:
https://github.com/fanvanzh/3dtiles

convert osgb to gltf\glb\3dtile directly。
