### ISSUE TITLE
non-physical appearances?

### ISSUE THREAD

**Issue by steveghee** [KhronosGroup/glTF#876]
Is there support for non-physical rendering?  This is beyond custom GLSL/HLSL shaders, as some non-physical effects require multiple-passes. There was a notion of 'passes' in previous spec versions, but it got removed prior to the 1.0 release. Any thoughts as to if and when that might be brought back?

**Comment by pjcozzi** [comment]
Hi @steveghee!  Multi-pass is for consideration post 2.0, #826, which is in the home stretch.  Any specific use cases you can provide is appreciated.

CC #163
