### ISSUE TITLE
Animation sampler input units in 2.0

### ISSUE THREAD

**Issue by stevenvergenz** [KhronosGroup/glTF#877]
> Each of the animation's samplers defines the input/output pair: a set of floating point scalar values representing time; and a set of three-component floating-point vectors representing translation or scale, or four-component floating-point vectors representing rotation.

Different applications have different expectations on the unit of the "time" field here. Since this says time is floating point, I'm assuming seconds were intended (?), but many applications use integer "frames", then a separate framerate field. What's the ruling on this?

**Comment by lexaknyazev** [comment]
> Different applications have different expectations on the unit of the "time" field here. Since this says time is floating point, I'm assuming seconds were intended (?)

CC @pjcozzi 

> many applications use integer "frames", then a separate framerate field

There was a [proposal](https://github.com/KhronosGroup/glTF/issues/731) to add fixed-framerate animation support.

**Comment by pjcozzi** [comment]
Good catch @stevenvergenz.

Looking at the sample models and the COLLADA spec, I believe the intention is that time is in seconds so I think we can classify this as a spec bug and update the 1.0 and 2.0 specs.

@lexaknyazev do you want to make the change?

**Comment by pjcozzi** [comment]
Updated in #826
