### ISSUE TITLE
glTF 2.0: Change JOINT and WEIGHT to form [semantic]_[set_index]

### ISSUE THREAD

**Issue by McNopper** [KhronosGroup/glTF#878]
Sooner or later, having maximum 4 values of joints and weights will be not enough.

I am fine, that at this point of time, maximum of 4 values are only valid.

To be future safe, I suggest the form like for COLOR or TEXCOORD e.g. JOINT_0 and WEIGHT_0.

**Comment by peteroupc** [comment]
I believe this is already the case in glTF 1.0. Note that the specification reads (with emphasis added):
	
> Attribute semantic property names can be of the form `[semantic]_[set_index]`, **e.g.**, `TEXCOORD_0`, `TEXCOORD_1`, etc.

In other words, the form `[semantic]_[set_index]` is available not just for `TEXCOORD`, but for every other attribute semantic, including `JOINT` and `WEIGHT`.

**Comment by McNopper** [comment]
Thanks for the info. So, actually, I want to have the restriction for JOINT and WEIGHT as well.

**Comment by lexaknyazev** [comment]
@McNopper 
Do you think that each 4 additional joints should use two more vertex attributes? There could be other ways to supply more joints (e.g., via packing).

Just for reference: three.js supports only 4 influences, BabylonJS can handle up to 8 (with two extra attributes).

CC @pjcozzi

**Comment by McNopper** [comment]
I want to increase the number of influences per vertex, just to be clear.

I understand, that currently some engines can only handle up to 4 inflcuences and that is the reason why I want this encoding:
For glTF 2.0, only JOINT_0 and WEIGHT_0 is allowed. But using an extension, it is possible to have more weigths and joints already e.g. JOINT_1 and WEIGHT_1 for having 8 influences and so on.

**Comment by pjcozzi** [comment]
Whatever everything thinks here will be fine with me.  I think we limited it because we didn't see more than 4 being used in practice.

**Comment by McNopper** [comment]
I am fine, if we just define, that JOINT_0 and WEIGHT_0 have to look like this plus for glTF 2.0 default is 4 influences. Whoever wants more at this point of time, needs to use an extension (to be defined).

Anyway, modern 3D engines, maybe not for the web, already support 8 influences e.g. Unreal Engine 4 supports 8 influences:
https://answers.unrealengine.com/questions/8117/bone-limitations.html

Having the the same rule as for TEXCOORD_X and COLOR_X, we are save for the future.

**Comment by meshula** [comment]
Hi all, I'm picking through the various commits and current state of the spec. My use case requires up to 8 influences per vertex. Is it still the case that skinning is restricted to 4 influences per vertex? My interest in gltf is to use standardized tools and formats. The spec explicitly calls out VEC4, and I see some discussion above about implementing a custom extension if 4 isn't enough, or packing the rest of the weights in JOINTS_1, but that's not really what I'm after as the interpretation of the resulting file wouldn't be standard across applications. Or have I misread this conversation?

**Comment by lexaknyazev** [comment]
The "standard" way is to use `JOINTS_n` / `WEIGHTS_n` for each additional 4 influences (preferably sorted by weights in descending order). Unfortunately, we cannot _require_ all implementations to support 8 influences right now.
