### ISSUE TITLE
glTF 2.0: Limit set_index for attributes to 0. Create extension for set_index > 0.

### ISSUE THREAD

**Issue by McNopper** [KhronosGroup/glTF#879]
I am not sure, if this is already specified, but set_index for attributes should be limited by default to one entry - i this case TEXCOORD_0 and COLOR_0.
If multiple entries has to be used, a specific extension does have to be present.

The reason for this is to avoid multiple shader combinations.

**Comment by McNopper** [comment]
In most cases, only one texture coordinate and color set is sufficient.
I understand, that there is a need for more sets, but to keep the core glTF 2.0 spec simple - especially its implementations - we should restrict for only one set.

**Comment by pjcozzi** [comment]
CC #878

**Comment by McNopper** [comment]
Fixed with this commit:
https://github.com/KhronosGroup/glTF/commit/fb8b472701bf54fc2dd80b1ade2dd312f42113ba
