### ISSUE TITLE
Animation sampler rotation format in 2.0

### ISSUE THREAD

**Issue by stevenvergenz** [KhronosGroup/glTF#882]
> Each of the animation's samplers defines the input/output pair: a set of floating point scalar values representing time; and a set of ... four-component floating-point vectors representing rotation.

What format should these rotation vectors take? Are they Euler angles? Quaternions? What order should the components come in? I'm guessing these were intended to be WXYZ quaternions, but they could also be XYZW quaternions. Some clarity here would be helpful.

**Comment by McNopper** [comment]
They are for sure quaternions and in the order XYZW.

**Comment by pjcozzi** [comment]
@McNopper is correct, but I'm sure if this is explicit enough in the spec.  There is this for `node.rotation`: https://github.com/KhronosGroup/glTF/tree/2.0/specification/1.0#noderotation

@lexaknyazev perhaps we should make the spec more clear, both 1.0 and 2.0?  Probably the same is true for translation and scale in keyframes.

**Comment by pjcozzi** [comment]
I meant "I'm **not** sure..."

**Comment by stevenvergenz** [comment]
It might be sufficient to add something to the Units section, declaring that all rotations are expressed as quaternions in XYZW order.

**Comment by pjcozzi** [comment]
Will update 2.0 [Units section](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#coordinate-system-and-units) to include info on rotation, translation, and scale.

Will update 2.0 schema/reference doc for animations to include info like the table in animations (https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#animations):

![image](https://user-images.githubusercontent.com/782098/31783010-c77113b4-b4ca-11e7-916b-dfef6ee232f1.png)

[wetzel](https://github.com/AnalyticalGraphicsInc/wetzel) is used to generate the reference doc from the schema - or a manual update is probably OK here. (#1013)

Thanks @javagl for making the update.

**Comment by pjcozzi** [comment]
Updated in #1136.
