### ISSUE TITLE
Animation root nodes in 2.0

### ISSUE THREAD

**Issue by stevenvergenz** [KhronosGroup/glTF#883]
Do you think glTF should have a concept of a "root" node for animations? Animation channels can choose individual nodes, but there's no coherence across channels in a single animation. I'm trying to map the glTF animation concept onto Unity, which requires choosing a single node to add the animation clip to, then refer to each animation target via a relative path from that root. I can choose the closest common ancestor, but that seems arbitrary to me.

For example, it makes sense to add all skeletal animations onto the root of a skeleton, not, for example, treat each channel as its own animation and add all hand poses on a hand, all leg poses on the hips, and all body poses on the spine.

**Comment by pjcozzi** [comment]
Sounds reasonable, but if this can be added in a backwards-compatible way, we might have to push to post 2.0 to control the scope and timeline.

**Comment by bghgary** [comment]
After some discussions with the working group, here are some thoughts on this issue.

Not all engines will have this issue. For engines that must require a root node to store animations (such as Unity), there are a few options:
1. Always create a new root node to hold the animations for the asset being loaded.
2. Only create a new root node for the animations if an animation targets more than one top-level node in a scene. If an animation does not target more than one top-level node, then just use the single top-level node for the root node.
3. Choose the closest common ancestor for the root node. If there is not a common ancestor, create a new root node to be the common ancestor.

Having to create a new root node is not great, but it shouldn't be a huge performance issue and is mostly mitigated if it only creates one when an animation targets multiple top-level nodes. We talked about possibly adding a warning or message to glTF-Validator indicating this might be an issue for some loaders to help avoid generating this kind of asset.

Given this, I don't think we need to do anything for the spec at this time. There is also the possibility of adding this in future dot versions of the spec if necessary.

**Comment by pjcozzi** [comment]
+1 as this sounds engine-specific.

Thanks for the input as always, @stevenvergenz!
