### ISSUE TITLE
keyFrames animation for vertexShaders

### ISSUE THREAD

**Issue by Fabrice3D** [KhronosGroup/glTF#886]
Busy on parsing the keyframes animations,  I can't find any info/example on how to couple
the keyframes to vertex shaders for the exporter I'm working on...

Here for instance raw exports from my editor Prefab3D to threejs using own format/scripts
http://closier.nl/webgl/modifiers/
http://closier.nl/webgl/bend/index2.html
here in app
![screen shot 2017-03-21 at 14 19 27](https://cloud.githubusercontent.com/assets/550453/24149296/4eb36a5a-0e42-11e7-92c3-2ae48b62bea5.jpg)

I'd like to be able to export these to gltf, but it's (very) unclear to me how to define the target object...
Any pointer would be welcome...

**Comment by pjcozzi** [comment]
Have you seen the simple animation glTF sample model: https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/1.0/BoxAnimated/glTF/BoxAnimated.gltf#L120-L142

**Comment by Fabrice3D** [comment]
The example describes in 2 animation objects per property (translation and rotation), and its target.id defines the accessor. But if the target.id is in case of a shader uniform, while I could do similar, i'm not so sure this would be executed by parsers. Probably because the case not being described, the animations objects are likely to be considered for joints/ keyframes anims for meshes. That's why I wonder if there would be an official example that could be followed and likely implemented the same way by more parsers. Tho, i'll see soon enough if its done by uploading to Sketchfab...

Also, if I construct multiple cameras, multiple animations for them, regarding target.path, if the target is a camera that I would want to toggle. Is there a dedicated path value or something else I should use to trigger the toggle?

Here's the output goal, where multiple camera's animated along own timelines are toggled. 
http://closier.nl/webgl/solowheel/

**Comment by pjcozzi** [comment]
> Also, if I construct multiple cameras, multiple animations for them, regarding target.path, if the target is a camera that I would want to toggle. Is there a dedicated path value or something else I should use to trigger the toggle?

I think #1137 is related.

If you have any other ideas/requests for documentation to help with animation implementations, please submit them to https://github.com/KhronosGroup/glTF-Tutorials
