### ISSUE TITLE
undefined Keyframes, how to handle them?

### ISSUE THREAD

**Issue by Fabrice3D** [KhronosGroup/glTF#893]
Using your animatedBox, https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/1.0
(The gif anim on the page helped a lot). It shows for the last frame, a box that has finished a rotation past frame and goes back to initial position.
If I load this gltf in the threejs loader example, i see the rotation stack gets 2 frames delay each iteration. Because threejs handles the stacks from starttime and endtime per clip, the anim data for rotations that is undefined for frame 0 and frame 4, this create async playback.

In my timeline (pict), the last rotation set on frame 3, is interpolated back to the rotation zero on frame 4. The gif anim, says otherwise.

For my implementation, I can simply fill the blancs, from time zero. and on last defined rotation, applied to the rest till the end and it will fix the problem for this animatedBox.

Question is, how to tell if the original animation was intended as the way it works in my timeline, using the rotation clip as an endless loop async as three js or the way the gif animation represent it?
The same freedom of interpretation occurs if you have 2 consecutive undefined path/rotation time in between start and end times.

![animatedbox](https://cloud.githubusercontent.com/assets/550453/24268967/d8b826b8-100f-11e7-8bc7-b62458fb4606.jpg)

**Comment by lexaknyazev** [comment]
glTF spec doesn't define animation behaviors such as autostart or loops. A note on that was [added](https://github.com/KhronosGroup/glTF/tree/2.0/specification/2.0#animations) to glTF 2.0.

CC @pjcozzi @lasalvavida 
Should GIFs be more explicit on that?

**Comment by Fabrice3D** [comment]
Thx for the reply lexaknyazev, 
Ok, correct me if i'm wrong,
If you say autostart and loops (and also nested clips stops) are ignored for now, then it is safe to say, that the current format data must be assumed to consider the updates from time 0 till the end. (unlike threejs player example). In the box example case, I can also then say that the gif represention is wrong as it should then interpolate the rotation back to zero. (3 to 4).

As i'm sure more dev's will try to parse these example files, it would be a great help to compair/validate. So if you could provide few updated very simple examples following the 1.0 specs and the draft 2.0 that would be very helpful... as of today, almost none of the models provided follows these, and your own online validator doesn't display the "ok" on most of them either.

**Comment by javagl** [comment]
Probably related: https://github.com/KhronosGroup/glTF/issues/573

**Comment by pjcozzi** [comment]
I believe this is now duplicate with #573 and #1137
