### ISSUE TITLE
glTF 2.0: Consider changing accessor type for output for CUBICSPLINE from SCALAR to VEC3

### ISSUE THREAD

**Issue by McNopper** [KhronosGroup/glTF#906]
This would allow, that output and input accessor still needs to have the same count in the animation sampler.
Furthermore, the output VEC3 does still contain in-tangent, spline vertex, and out-tangent. The order does not change.

In my opinion, this approach is more generic.

**Comment by bghgary** [comment]
The output isn't just scalars. It can already be a VEC3 or VEC4.

https://github.com/KhronosGroup/glTF/tree/2.0/specification/2.0#animations 
> Each of the animation's samplers defines the input/output pair: a set of floating point scalar values representing time in seconds; and a set of three-component floating-point vectors representing translation or scale, or four-component floating-point vectors representing rotation, or floating-point scalars used to animate Morph Targets.

**Comment by McNopper** [comment]
Sorry for not being precsise. Talking about this:
https://github.com/KhronosGroup/glTF/blob/2.0/specification/2.0/schema/animation.sampler.schema.json
"... except for `CUBICSPLINE` where output count is 3x the input count ..."
What I would like to change is, that the type of the accessor is VEC3 and not FLOAT. Having this change, allows to index into the CUBICSPLINE data with the same index as the key.
E.g. the nth key is also the nth CUBICSPLINE data. Currently it is 3 * n from my understanding, which is bypassing the purpose of the accessor.

**Comment by bghgary** [comment]
> What I would like to change is, that the type of the accessor is VEC3 and not FLOAT.

Yes, I understood what you meant. The schema description is talking about accessory's componentType, not type. The accessor type for output can already be a SCALAR, VEC3, or VEC4 as described in the readme. SCALAR is for morph target weights. VEC3 is for position or scale. VEC4 is for quaternion rotation. What you're proposing doesn't work because the spline can target position, scale, or rotation which is already a VEC3 or VEC4. You can't have a VEC3 of a VEC3/VEC4.

**Comment by McNopper** [comment]
Ah, now I got it. My mistake. In my engine, I can animate each channel separatelly and forgot, that it is different in gltf.

For VEC3/VEC3, MAT3 could be used but VEC3/VEC4 is the problem. I just do not like the idea, to make a manual offset, as normally the accessor is doing this for me.
