### ISSUE TITLE
accessors.type property should be an enum instead of a string.  Curent schema is inconsistent since pratically everything else is an enum.

### ISSUE THREAD

**Issue by AlexPfaffe** [KhronosGroup/glTF#908]
"accessors": [
        {
            "bufferView": 0,
            "byteOffset": 0,
            "componentType": 5123,
            "count": 12636,
            "max": [
                4212
            ],
            "min": [
                0
            ],
            "type": "SCALAR"    <=== use some ENUM value instead.

**Comment by emackey** [comment]
I think this is [already fixed](https://github.com/KhronosGroup/glTF/blob/bdd2517663efe123186b3be6f7afbcc9a2732bc8/specification/2.0/schema/accessor.schema.json#L67-L95) in glTF 2.0.

**Comment by lexaknyazev** [comment]
This was discussed as a part of 2.0 release, and WG conclusion was to keep non-API defined enums (`accessor.type`, `camera.type`, `animation.channel.target.path`, `animation.sampler.interpolation`, `material.alphaMode`) as strings.
