### ISSUE TITLE
Rendering points and line segments

### ISSUE THREAD

**Issue by peteroupc** [KhronosGroup/glTF#917]
The glTF 2.0 specification should include advice on rendering points and line segments (primitives with mode `LINES`, `LINE_STRIP`, `LINE_LOOP`, or `POINTS`), especially because the lighting calculations rely on vertex normals, which don't normally make much sense for line segments and points to have because they have no area.  The specification should especially mention how the base color, emission, per-vertex colors, and other parameters affect how line segments and points are rendered.

**Comment by pjcozzi** [comment]
Thanks for comment!

Discussed offline:

- if normals are defined, use full PBR model
- if normals are not defined, use full PBR model with the assumption that the line is lit from all directions

@emackey has volunteered to make the changed

**Comment by lexaknyazev** [comment]
@emackey While making those changes, please review existing impl. notes right before on attributes and lighting calculations (right before [morph targets](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#morph-targets)).

Also, spec should be more clear about:
- Does `TANGENT` attribute always requires `NORMAL`? (I assume yes.)
- Is it OK to have `POINTS` with `TANGENT`?

**Comment by emackey** [comment]
Do we have any sample models that show points and lines?

**Comment by pjcozzi** [comment]
@emackey did you make these spec updates?

**Comment by lexaknyazev** [comment]
@pjcozzi @emackey 
Any actions left?

**Comment by peteroupc** [comment]
> 
> 
> I didn't make any updates myself, but I recall there were changes at some point to the relevant part of the spec for unrelated reasons. This is what it looks like now:
> 
> https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#point-and-line-materials
> 
> If that's OK with everyone, I vote we close this.

I have no objections with what that section currently says.  Thus, this issue is closed now.
