### ISSUE TITLE
byteOffset and byteLength usage

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#920]
@pjcozzi @sbtron @bghgary 

`byteOffset` isn't consistent across the spec:

- Default `0`:
  - `accessor.byteOffset`
  - `accessor.sparse.indices.byteOffset`
  - `accessor.sparse.values.byteOffset`
- Required
  - `bufferView.byteOffset`

Why not make it zero by default everywhere?

---

`buffer.byteLength` is  `0` by default AND is required at the same time. We should remove default value. Also, why do we allow zero-length buffers?

**Comment by bghgary** [comment]
> Why not make it zero by default everywhere?

+1

> We should remove default value. 

+1 I noticed that earlier as well.

> Also, why do we allow zero-length buffers?

I can't think of any reason why we would want a zero-byte buffer.

**Comment by pjcozzi** [comment]
Agreed across the board.
