### ISSUE TITLE
accessor.byteOffset w/o bufferView

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#924]
@pjcozzi @emilian0 @bghgary 

What are valid usecases for `accessor.byteOffset` when `accessor.bufferView` isn't defined?

We've got two cases, when `accessor.bufferView` isn't defined:

1. Sparse accessor initialized with zeros. `byteOffset` makes no sense.
2. Accessor data provided by external means (e.g. Draco compression extension). `accessor.byteOffset` could be used to, e.g., utilize the same index buffer for different primitives. Sounds quite complicated.

Thoughts?

**Comment by pjcozzi** [comment]
Perhaps `byteOffset` requires that `bufferView` is defined.

**Comment by lexaknyazev** [comment]
@pjcozzi
That was my first intent.
For mangling with decompressed data such field could be reintroduced as an extension. 

@bghgary, is this OK with you?

**Comment by bghgary** [comment]
@lexaknyazev, I haven't looked at this or the Draco extension enough to say. All of the an assets I've created have accessor.byteOffset equal to zero since bufferView already has a byteOffset into the buffer. Are you proposing any changes to the schema?

**Comment by lexaknyazev** [comment]
@bghgary 
Possible change is that `byteOffset` could be defined only when `bufferView` is present, so it won't affect your assets unless they use Draco or sparse accessors.

**Comment by bghgary** [comment]
@lexaknyazev Sounds good.
