### ISSUE TITLE
The encoding of morph targets in the schema

### ISSUE THREAD

**Issue by javagl** [KhronosGroup/glTF#927]
The [current schema for `mesh.primitive.target`](https://github.com/KhronosGroup/glTF/blob/fb8b472701bf54fc2dd80b1ade2dd312f42113ba/specification/2.0/schema/mesh.primitive.schema.json#L64) says that it is an array of `mesh.primitive.target` objects. These objects are supposed to be dictionaries. The [schema for `mesh.primitive.target`](https://github.com/KhronosGroup/glTF/blob/9b131950c0e6a793dbe51a72f6e3ca52e13f2246/specification/2.0/schema/mesh.primitive.target.schema.json) is

    {
        "$schema": "http://json-schema.org/draft-04/schema",
        "title": "target",
        "allOf": [ { "$ref": "glTFid.schema.json" } ],
        "description": "A dictionary object specifying attributes displacements in a Morph Target, where each key corresponds to one of the three supported attribute semantic (`POSITION`, `NORMAL`, or `TANGENT`) and each value is the index of the accessor containing the attribute displacements' data."
    }

I think this means that these objects are just IDs (Integers). 

I'm not a JSON schema expert, but to my understanding, the schema for `mesh.primitive.target` should rather be (roughly!) something like this:

*(EDIT: This may be wrong, see the update below!)*

    {
        "$schema": "http://json-schema.org/draft-04/schema",
        "title": "target",
        "type": "object",
        "additionalProperties": {
            "type": { "$ref": "glTFid.schema.json" }
        }
        "description": "A dictionary object specifying attributes displacements in a Morph Target, where each key corresponds to one of the three supported attribute semantic (`POSITION`, `NORMAL`, or `TANGENT`) and each value is the index of the accessor containing the attribute displacements' data."
    }

That is: It is not just an integer, but really an object (dictionary), with arbitrary properties (as indicated by the `additionalProperties`), where the value of each property is an ID. 

Am I overlooking or misinterpreting something here?

--- 

**Update** : I think that `mesh.primitive.target` should be defined as this:

    {
        "$schema": "http://json-schema.org/draft-04/schema",
        "title": "target",
        "type": "object",
        "additionalProperties": {
            "allOf": [ { "$ref": "glTFid.schema.json" } ]
        },
        "description": "A dictionary object specifying attributes displacements in a Morph Target, where each key corresponds to one of the three supported attribute semantic (`POSITION`, `NORMAL`, or `TANGENT`) and each value is the index of the accessor containing the attribute displacements' data."
    }

(This way, my code generator creates the targets as `List<Map<String, Integer>> targets` (instead of `List<Integer> targets`), but of course, this does not mean much: The code generator may very well be buggy. However, the original definition for me looks like a `mesh.primitive.target` **is-a** ID, which probably isn't correct either...)

**Comment by lexaknyazev** [comment]
You're right. JSON-Schema for targets is broken. Also it seems to be unneeded, because each element of `targets` array has the same schema as `attributes` property.

**Comment by javagl** [comment]
I wasn't sure whether there might be the intention to give this dictionary a *name* in view of possible future extensions - to make sure that it can (one day) be more than just a dictionary...

    "targets": [
        {
            "NORMAL": 35,
            "POSITION": 33,
            "someAdditionalInfoAboutTheMorphTarget" : "theInfoWhichIsNotAnID"
        }
    ],

But if this is not the case, then it can just be a list of anonymous ("type-less") dictionaries.

**Comment by lexaknyazev** [comment]
> whether there might be the intention to give this dictionary a name in view of possible future extensions...

These dictionaries are pure dictionaries: each key maps to a vertex attribute, so there could not be any other properties in them.

**Comment by lexaknyazev** [comment]
@javagl 
See #928.

**Comment by javagl** [comment]
@lexaknyazev Thanks, looks fine for me.

So I think this can be closed when the PR is reviewed and accepted. 

BTW: The question that you raised in the PR might be related to https://github.com/KhronosGroup/glTF/issues/916 - but maybe I'm misinterpreting this.
