### ISSUE TITLE
glTF 2.0: Add "`zfar` must be greater than `znear`" to orthographics camera.

### ISSUE THREAD

**Issue by McNopper** [KhronosGroup/glTF#939]
see https://github.com/KhronosGroup/glTF/blob/2.0/specification/2.0/schema/camera.orthographic.schema.json

**Comment by lexaknyazev** [comment]
Fixed with https://github.com/KhronosGroup/glTF/commit/0b3dbdd23acbb7d92385967f8c31433469ff6475.
