### ISSUE TITLE
Default values for metallicFactor and emissiveFactor

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF#940]
Apologies if this was already covered someplace, I couldn't find an issue.  I ran into some odd interactions with default values that I'll try to document here.

The default value for `metallicFactor` is 1.0.  This seems odd at first glance, since classic Phong-type rendering is very non-metallic.  One might expect the default behavior to act as if the default was non-metal.  But this default value is actually quite good when a `metallicRoughnessTexture` is supplied, because the `metallicFactor` value gets multiplied with each texel from the texture.  So a default of 0 would cancel out the entire texture, which is less desirable.  So a default of 1 seems like a good choice, although converters will need to explicitly assign 0 when converting old models that lack metalness information.

Contrast this with `emissiveFactor`, where the default value is `[0,0,0]`.  This seems like a sane default, as anything else would cause the model to glow or turn white when an `emissiveTexture` was not supplied.  But a problem crops up when an `emissiveTexture` is supplied without an `emissiveFactor`.  The missing but implicitly-zero `emissiveFactor` causes the `emissiveTexture` to not have any effect at all.  It may not be immediately clear to the user why their supplied texture has no effect.  For the `emissiveTexture` to have its intended effect, one must manually set `emissiveFactor` to `[1,1,1]`.

None of this is a huge problem of course, it just seems very lumpy, in particular to have the different defaults like this.  I don't think switching any one default would necessarily make anything better, though, so maybe this is just something intentional that the model converters need to deal with.  The converters can work around this by explicitly setting these factor values to 0 when no information is supplied, and setting the factors to 1 when only a texturemap is supplied without a factor.  Thoughts?

**Comment by bghgary** [comment]
These default values are defined this way because they represent the smallest JSON for common cases (i.e. when textures are provided for baseColor and metallicRoughess). The emissive factors default to zero because it's not common, but I agree it's not consistent with the other factors.

While these defaults might be somewhat confusing at first, I don't think there are other defaults that make it better, like you said. Because of that, I would prefer to optimize for usage such that the JSON is as small as possible for the most common cases.

**Comment by pjcozzi** [comment]
@emackey is there any action here?

**Comment by emackey** [comment]
Nope.

**Comment by electrowolff** [comment]
Can the docs be updated to clarify that the default should be [0,0,0] unless there is a texture then the default should be [1,1,1]?

**Comment by emackey** [comment]
No, the docs are correct, the default metalness is officially [1,1,1].  This makes the reader/viewer implementations simpler and cleaner, and is something that exporters need to be aware of.

**Comment by electrowolff** [comment]
Oops I meant specifically for the emissiveFactor, or is that left up to the renderer to properly interpret as well?

**Comment by emackey** [comment]
Sorry, messed up my comment above.  Edited.

**Comment by emackey** [comment]
And to be clear:  If an exporter saves an emissive texture but no emmissive factor, then the texture is ineffective, multiplied by zero across the board.  Exporters need to set the factor when creating the file.

**Comment by electrowolff** [comment]
Ah gotcha, onus is on the exporter. Makes sense, thanks!
