### ISSUE TITLE
bufferView.byteStride default value accidentally removed

### ISSUE THREAD

**Issue by robertlong** [KhronosGroup/glTF#941]
It looks like the default value for `bufferView.byteStride` was accidentally removed in this commit:
https://github.com/KhronosGroup/glTF/commit/6e6ae374e9e15a9b50960cead9d0888501fccf7a#diff-d0accebdb554e203fb28c4c92fe31cbfL28 or is there something I'm missing about default values for properties which aren't required?

**Comment by lexaknyazev** [comment]
@robertlong 
Optional properties without default values are quite common in the spec.

Default value for `byteStride` was removed intentionally to make usage of this property more explicit.
Relevant parts from spec text:

**[Buffers and Buffer Views](https://github.com/KhronosGroup/glTF/tree/2.0/specification/2.0#buffers-and-buffer-views)**
> Buffer view could have `byteStride` property. It means byte-distance between consequential elements. This field is defined only for buffer views that contain vertex attributes.

**[Data Alignment](https://github.com/KhronosGroup/glTF/tree/2.0/specification/2.0#data-alignment)**
> When `byteStride` of referenced `bufferView` is not defined, it means that accessor elements are tightly packed, i.e., effective stride equals the size of the element. When `byteStride` is defined, it must be a multiple of the size of the accessor's component type. `byteStride` must be defined, when two or more accessors use the same `bufferView`.

**Comment by robertlong** [comment]
Ah, yeah this is much easier to understand now. I have byteStride wrong in UnityGLTFLoader. Now the whole `"multipleOf": 4` part makes sense. Thanks!
