### ISSUE TITLE
Register MIME Type for GLB File Format

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#943]
Since GLB file format is now a part of glTF 2.0 core spec, we should register its MIME Type with IANA.

According to [RFC 6838, Section 4.2](https://tools.ietf.org/html/rfc6838#section-4.2), we can use neither `.` (dot) because gltf is facet-less tree, nor `+` (plus) because it means registered structured syntax suffix (such as `+json` or `+xml`). So we've got two options (at least):
- `model/gltf-binary`
- `model/gltf_binary`

Thoughts?

CC @pjcozzi @sbtron @bghgary

**Comment by pjcozzi** [comment]
Replaces #650

CC #412

**Comment by pjcozzi** [comment]
> `model/gltf-binary`

+1

**Comment by emackey** [comment]
+1 for `model/gltf-binary`

We'll have to fix it in Cesium, which is currently using `model/gltf.binary`.

**Comment by sbtron** [comment]
Updated in #1000 . Still need to register with IANA

**Comment by sbtron** [comment]
gltf-binary is no registered with IANA-
https://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by pjcozzi** [comment]
Really exciting, congrats and thanks for taking the lead on this!
