### ISSUE TITLE
How to export model with webgl(gles) shaders and embed them into glTF?

### ISSUE THREAD

**Issue by linuxaged** [KhronosGroup/glTF#949]

**Comment by javagl** [comment]
Export - *from* where? The general structure of the model will heavily depend on (and be interweaved with) the shaders. They need to be fed with the right vertex attributes, need the right uniforms to be set, and so on. Technically, it is possible to include shaders in glTF. This was standard in 1.0, and will be possible in 2.0 via the [KHR_technique_webgl extension](https://github.com/KhronosGroup/glTF/tree/2.0/extensions/Khronos/KHR_technique_webgl) (which is currently in the process of being updated)

**Comment by linuxaged** [comment]
fixed: https://github.com/linuxaged/FBX-glTF/commit/489bc88cf4848f847229aa8fe82ed45a9b432b48
