### ISSUE TITLE
Direction of Y (green) channel in normal maps

### ISSUE THREAD

**Issue by emackey** [KhronosGroup/glTF#952]
Do we have an official specification on which direction Y (green) values go in normal maps?  Some programs allow the user to specify this.

For example, here is a screenshot of Substance Painter preparing to export to UE4:

![ue4_export](https://cloud.githubusercontent.com/assets/1235080/25919837/eee134c6-359d-11e7-9383-3bdbafeb4210.png)

Note there are two different options to choose from, `Normal DirectX` and `Normal OpenGL`.  Here is a hemisphere-shaped outward bump, exported with these different options:

![normal_comparison_full](https://cloud.githubusercontent.com/assets/1235080/25921573/ecb157ac-35a3-11e7-9790-c402b7fbaafa.png)

In the resulting export, the red and blue channels are not influenced by this choice.  Only the green channel is different, and it appears to be inverted.

![normal_comparison_greenonly](https://cloud.githubusercontent.com/assets/1235080/25921591/0279df8c-35a4-11e7-9eaa-e2bd02694704.png)

@mlimper [points out](https://github.com/AnalyticalGraphicsInc/obj2gltf/pull/67#issuecomment-300609683) other software has options to adapt to this:

> With our current export pipeline we can directly export textures for usage with the BabylonJS Web viewer. If we want to upload on Sketchfab, however, we'll have to go to the Sketchfab backend's 3D settings and uncheck "Flip green (-Y)" there, otherwise the normal maps wouldn't be interpreted correctly:

![image](https://cloud.githubusercontent.com/assets/1853237/25920815/029c8c74-3588-11e7-9e9d-7d89568cf180.png)

Getting it wrong, of course, leads to [strange consequences](https://github.com/donmccurdy/three-gltf-viewer/issues/10):

![threejs_normaltangent_notright](https://cloud.githubusercontent.com/assets/1235080/25786975/026e7880-336b-11e7-84bf-462a2fe2b111.png)

Is the correct sense of the green channel already defined somewhere?  Can we nail it down?

/cc @donmccurdy @mlimper @bghgary @sbtron @lexaknyazev

**Comment by bghgary** [comment]
This is specified here: https://github.com/KhronosGroup/glTF/tree/2.0/specification/2.0#materialnormaltexture

> The normal vectors use OpenGL conventions where +X is right and +Y is up. +Z points toward the viewer.

**Comment by emackey** [comment]
Well that settles that then.

@donmccurdy This means that (a) glTF 2.0 core texture format is not *exactly* the same as UE4 format, and (b) the ThreeJS glTF loader isn't interpreting them correctly at the moment, as we're tracking in donmccurdy/three-gltf-viewer#10.

**Comment by donmccurdy** [comment]
@bghgary is babylon.glTF2FileLoader using that convention? I thought that BabylonJS's default was `+X=left, +Y=down`, and I don't see any use of `invertNormalMapX|Y` in the implementation.

**Comment by bghgary** [comment]
> babylon.glTF2FileLoader using that convention?

Yes. The reason `invertNormalMapX` or `invertNormalMapY` are not set is because scene.useRightHandedSystem has been set to true.

https://github.com/BabylonJS/Babylon.js/blob/master/loaders/src/glTF/2.0/babylon.glTFLoader.ts#L1148

**Comment by donmccurdy** [comment]
I see, thanks!
