### ISSUE TITLE
Ambiguous camera definitions

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#953]
The description of `camera.type` says:
> Specifies if the camera uses a perspective or orthographic projection.  Based on this, either the camera's `perspective` or `orthographic` property will be defined.

This raises at least two questions:
1. Could `camera` contain both `perspective` and `orthographic`?
2. Since `type` is required and it's forward-compatible, should neither `perspective` nor `orthographic` be defined when `type` is not of known enum value?

@pjcozzi @bghgary @sbtron

**Comment by pjcozzi** [comment]
No super strong opinion, but if I had to pick I would go strict:

1. No.  I could see allowing both making mixing and matching a bit easier, but I don't think that is a practical use case for camera types.

2. Neither would be defined.

**Comment by bghgary** [comment]
@lexaknyazev Is there something to update in the schema for this?

**Comment by lexaknyazev** [comment]
@bghgary 
To prevent assets with both properties set, like this
```json
{
  "cameras": [
    {
      "type": "perspective",
      "perspective": {},
      "orthographic": {},
    }
  ]
}
```

We could tweak schema a bit:
```json
{
  "required": [ "type" ],
  "not": {
    "required": [ "perspective", "orthographic" ]
  }
}
```

**Comment by bghgary** [comment]
@lexaknyazev Sounds good.
