### ISSUE TITLE
glTF 2.0: Maximum number of morph targets missing

### ISSUE THREAD

**Issue by McNopper** [KhronosGroup/glTF#961]
It has been discussed somewhere, but I cannot find it in the spec.

**Comment by McNopper** [comment]
As "minItems" is 1 and no "maxItems" is present, I assume it has not yet been defined.

**Comment by javagl** [comment]
Just to have the cross link here: https://github.com/KhronosGroup/glTF/pull/977 

As discussed offline, there should be no limit that is inherent to the format, and renderers have to support at least 8 attributes (i.e. 8, 4 or 2 morph targets, depending on how many attributes they have).

**Comment by McNopper** [comment]
Fine with me, as I know can define my constant :-)
