### ISSUE TITLE
glTF 2.0: Morph target object without POSITION and/or empty alllowed?

### ISSUE THREAD

**Issue by McNopper** [KhronosGroup/glTF#967]
In the spec, it is defined, that currently only POSITION, NORMAL and TANGENT are allowed.
But it is not clearly stated, if e.g. POSITION has to be present and/or the target object can be empty.

**Comment by lexaknyazev** [comment]
It can't be empty:
https://github.com/KhronosGroup/glTF/blob/2.0/specification/2.0/schema/mesh.primitive.schema.json#L68

**Comment by McNopper** [comment]
Okay, got it, thx,
