### ISSUE TITLE
glTF 2.0: Clarify, why morph targets do not have same approach like other primitive parameters

### ISSUE THREAD

**Issue by McNopper** [KhronosGroup/glTF#968]
Currently implementing morph targets and I wonder, why morph target do not follow the same approach like the other primitve parameters.
Following could have been possible:

MORPH_POSITION_0
MORPH_POSITION_1

MORPH_NORMAL_0
MORPH_NORMAL_1

MORPH_TANGENT_0
MORPH_TANGENT_1

**Comment by McNopper** [comment]
Is it because of sparse arrays?

**Comment by lexaknyazev** [comment]
You can trace evolution of morph target syntax in #210. 
Having all attribute accessors together may have some debatable benefits, but I think we can't change syntax at this moment.

**Comment by McNopper** [comment]
Okay, thank you. I will internally "unroll" the data.
