### ISSUE TITLE
alternative for shaders and states 

### ISSUE THREAD

**Issue by fabrobinet** [KhronosGroup/glTF#97]
For engines ables to generate shaders based on light / material properties for common lighting model we should provide ways to ensure they are not forced to use glTF shaders and even states.

A first approach has been to "specify" parameters. So that just looking at shaders parameters will allow to regenerate shaders. This is documented [here](https://github.com/KhronosGroup/glTF/blob/master/specification/README.md#about_shaders)

This works for simple cases, but it misses at least 2 things:

First, the ability to associate a material property to texture.
Concretely, if one needs to regenarate a texture fetch for a specular map, he needs to know that say :TEXCOORD_2 is associated with the specular parameter that refer to a texture.
This will allow to write code such as `specularColor = texture2D(u_specularTexture, v_texcoord2). 
Thus, This association "material property"(like specular)  -> mesh attribute (TEXCOORD_2 in the example), is missing and this is tracked here:
https://github.com/KhronosGroup/glTF/issues/47

Then we also need to be able to regenerate state. So we should write higher level info, for instance double_sided information and so on... (possibly coming from COLLADA extras) here.

My proposal (a bit rough, but to get is idea..) is to add something like this in technique,
And we'll find a better name than "generator"..

```
"generator" : {   
               "type" : "COLLADA-1.4.1/commonProfile",
               "commonProfile" : {
                   "technique" : "Phong",
                   "diffuse" : "aColor"               <--- point to paramerer
               "texcoordsBindings" : {
                      "diffuse" : "TEXCOORD_0,
                      "specular": "TEXCOORD_2
                },
               "extras" : {
                   "double_sided" : true;                    
                }
               }
           },
```

**Comment by pjcozzi** [comment]
Closing as duplicate with #361.
