### ISSUE TITLE
GLTF Supported Texture Format question.

### ISSUE THREAD

**Issue by memmottse** [KhronosGroup/glTF#972]
Reading the specification pages I found
 .jpg, .png, .bmp, and .gif listed as supported in gltf 1.0
and 
.jpg, .png as supported in gltf 2.0
Does that mean those are the minimum number of supported formats, or does that mean that they are the only supported formats.  
I'm specifically asking because I'm trying to figure out where the ktx file format landed.

**Comment by pjcozzi** [comment]
Hi @memmottse!  jpg and png are the only formats in 2.0.  KTX will be post 2.0.  See https://github.com/KhronosGroup/glTF/issues/835#issuecomment-292038169

It was really a matter of scope so we can ship 2.0.

**Comment by memmottse** [comment]
Thanks!
