### ISSUE TITLE
My duck is shiny!

### ISSUE THREAD

**Issue by blitz-research** [KhronosGroup/glTF#978]
Hi,

The screenshot for the 2.0 duck model appears to be non-metallic, however the pbrMaterial in the gltf file doesn't specify any metalness in which case I thought it was supposed to default to '1'. This means my  renderer is drawing a very metal duck!

Which is correct, the screenshot or my renderer?

Bye!
Mark

**Comment by emackey** [comment]
Great question!  This may indicate differences between spec and implementation(s)...

/cc #940

**Comment by bghgary** [comment]
The default of roughness is also 1. That should make the duck not shiny. But I don't think the screenshot represents what it should look like.

**Comment by blitz-research** [comment]
> The default of roughness is also 1. That should make the duck not shiny.

You're right - this was a bug in my code. It actually looks a lot like the
screenshot now.

**Comment by cx20** [comment]
I tried testing several libraries and glTF formats.
https://cdn.rawgit.com/cx20/gltf-test/3c67282d439bcb4225708c45b9398327f1c399cd/index.html
It seems that the display results differ depending on the library even for the same model.

[Three.js r86dev+ glTF-Sample-Models/2.0/Duck/glTF/Duck.gltf result:](https://cdn.rawgit.com/cx20/gltf-test/3c67282d439bcb4225708c45b9398327f1c399cd/examples/threejs/index.html?category=sampleModels&model=Duck&scale=1&type=glTF)
![image](https://cloud.githubusercontent.com/assets/1833979/26428514/1150c5d2-411d-11e7-9041-2d1ad9a8fef3.png)

[Babylon.jsv3.0-alpha + glTF-Sample-Models/2.0/Duck/glTF/Duck.gltf result:](https://cdn.rawgit.com/cx20/gltf-test/3c67282d439bcb4225708c45b9398327f1c399cd/examples/babylonjs/index.html?category=sampleModels&model=Duck&scale=1&type=glTF)
![image](https://cloud.githubusercontent.com/assets/1833979/26428568/668a03b0-411d-11e7-92dc-cd96b18b9d02.png)

[Three.js r86dev + glTF-Sample-Models/2.0/Duck/glTF-pbrSpecularGlossiness/Duck.gltf result:](https://cdn.rawgit.com/cx20/gltf-test/3c67282d439bcb4225708c45b9398327f1c399cd/examples/threejs/index.html?category=sampleModels&model=Duck&scale=1&type=glTF-pbrSpecularGlossiness)
![image](https://cloud.githubusercontent.com/assets/1833979/26428601/9b7b2478-411d-11e7-8d7f-64da80feb43e.png)

[Babylon.js v3.0-alpha + glTF-Sample-Models/2.0/Duck/glTF-pbrSpecularGlossiness/Duck.gltf result:](https://cdn.rawgit.com/cx20/gltf-test/3c67282d439bcb4225708c45b9398327f1c399cd/examples/babylonjs/index.html?category=sampleModels&model=Duck&scale=1&type=glTF-pbrSpecularGlossiness)
![image](https://cloud.githubusercontent.com/assets/1833979/26428677/f3bc2c86-411d-11e7-94b9-727c29a3d73b.png)

**Comment by donmccurdy** [comment]
As for three.js r86, which is also shiny, the default `metalness=1` default seems to be the cause:

| metalness=0 | metalness=1 (default) |
|---|---|
| ![screen shot 2017-05-24 at 9 09 21 pm](https://cloud.githubusercontent.com/assets/1848368/26435628/7658f83a-40c5-11e7-888b-e97d0a35fca4.png)   |  ![screen shot 2017-05-24 at 9 09 27 pm](https://cloud.githubusercontent.com/assets/1848368/26435632/7a62ac6e-40c5-11e7-8f2c-af47e7347ec5.png)  |

I'm not sure what is correct here. three.js gives similar results on the MetalRoughSpheres example:

![screen shot 2017-05-24 at 9 13 03 pm](https://cloud.githubusercontent.com/assets/1848368/26435690/dd521828-40c5-11e7-9459-2a44bf84c56e.png)

**Comment by javagl** [comment]
A wild guess as a side note ( @cx20 ) : The difference between the models might stem from the fact that [the glossinessFactor is an array in the sample models](https://github.com/cx20/gltf-test/blob/e235b980dd5e57320bdfc9f017d1cd6b6a80367b/sampleModels/Duck/glTF-pbrSpecularGlossiness/Duck.gltf#L199) (which was identified as a [bug in COLLADA2GLTF](https://github.com/KhronosGroup/COLLADA2GLTF/issues/43) ), and that the engines thus probably don't process this value properly (but I haven't tested this yet).

**Comment by bghgary** [comment]
The specular-glossiness version of the duck is also not equivalent to the metallic-roughness version like it should be.

This is what the Duck model currently has:

```JSON
            "pbrMetallicRoughness": {
                "baseColorTexture": {
                    "index": 0
                }
            },
            "emissiveFactor": [
                0.0,
                0.0,
                0.0
            ],
            "extensions": {
                "KHR_materials_pbrSpecularGlossiness": {
                    "diffuseTexture": {
                        "index": 0
                    },
                    "specularFactor": [
                        0.0,
                        0.0,
                        0.0
                    ],
                    "glossinessFactor": [
                        0.30000001192092898
                    ]
                }
            }
```

I would expect it to look like this:

```JSON
           "pbrMetallicRoughness": {
                "baseColorTexture": {
                    "index": 0
                },
                "metallicFactor": 0
            },
            "emissiveFactor": [
                0.0,
                0.0,
                0.0
            ],
            "extensions": {
                "KHR_materials_pbrSpecularGlossiness": {
                    "diffuseTexture": {
                        "index": 0
                    },
                    "specularFactor": [
                        0.04,
                        0.04,
                        0.04
                    ],
                    "glossinessFactor": 0
                }
```

This second version should look identical in the same viewer between metallic-roughness and specular-glossiness.

**Comment by lasalvavida** [comment]
Noted. I'll have the `glossinessFactor` issue fixed shortly, and I'll have `metallicFactor` written as zero.

**Comment by emackey** [comment]
The Duck model was made non-metallic following converter updates and model regen in KhronosGroup/glTF-Sample-Models#76.  This can be closed.
