### ISSUE TITLE
glTF 2.0 BufferView.byteOffset may be optional

### ISSUE THREAD

**Issue by syoyo** [KhronosGroup/glTF#979]
According to the HTML spec page https://github.com/KhronosGroup/glTF/tree/2.0/specification/2.0#bufferview

`BufferView.byteOffset` is classified as `Required` field, but according to the JSON schema it has default value, thus I guess `BufferView.byteOffset` parameter need to be modified as optional parameter in the HTML page.

For example, `glTF-Sample-Models/2.0/Lantern/glTF/Lantern.gltf` lacks `byteOffset` field.

**Comment by lexaknyazev** [comment]
Properties Reference from that page is outdated. 
Please refer to [JSON-Schemas](https://github.com/KhronosGroup/glTF/tree/2.0/specification/2.0/schema) instead.

**Comment by syoyo** [comment]
Thanks! I see > Please refer to JSON-Schemas instead.

I will follow the definition of JSON schema to update our C++ glTF 2.0 parser: https://github.com/syoyo/tinygltf/tree/devel

Anyway, it would be better to update HTML page because I think most of glTF people only checks HTML page, not JSON schema.

**Comment by pjcozzi** [comment]
@syoyo we'll update the spec from the JSON schema soon.  We are putting the finishing touches on everything now.

**Comment by syoyo** [comment]
Thanks!
