### ISSUE TITLE
Tagging glTF with IFC types for BIM?

### ISSUE THREAD

**Issue by xeolabs** [KhronosGroup/glTF#981]
I'm raising this issue because I've heard lots of interest expressed in using glTF as the transmission format for [Building Information Modeling (BIM)](https://en.wikipedia.org/wiki/Building_information_modeling) applications. 

For BIM, certain nodes in the glTF scene graph would represent elements within the building model (such as walls, windows, support beams etc). Each those would need to be tagged with metadata to indicate its [IFC (Industry Foundation Class)](https://www.thenbs.com/knowledge/what-is-ifc) type, eg. "IfcWall", "IfcWindow" etc.

In glTF it seems that we can only put metadata on assets, otherwise I would tag the nodes with metadata containing the IFC types.

Any ideas on how glTF 1.0/2.0 could contain IFC types, or is there something I'm missing? Maybe something to consider for future glTF versions?

**Comment by lexaknyazev** [comment]
> Any ideas on how glTF 1.0/2.0 could contain IFC types

There are two ways of extending glTF 1.0/2.0 for different applications:

- Any entity of glTF file can have `extra` property for any app-specific information. E.g.,
  ```json
  {
      "asset": {
          "version": "2.0"
      },
      "nodes": [
          {
              "extra": "customData"
          }
      ]
  }
  ```
- To extend glTF in a more interoperable way, any organization or individual can propose a glTF extension that could be added to the [extensions registry](https://github.com/KhronosGroup/glTF/blob/2.0/extensions/README.md). E.g.,
  ```json
  {
      "asset": {
          "version": "2.0"
      },
      "extensionsUsed": [ 
          "EXT_IFC" 
      ],
      "nodes": [
          {
              "extensions": {
                  "EXT_IFC": {
                      "type": "IfcWindow"
                  }
              }
          }
      ]
  }
  ```
