### ISSUE TITLE
How should I apply default material to the models not containing NORMAL as attribute values?

### ISSUE THREAD

**Issue by kyasbal-1994** [KhronosGroup/glTF#984]
As long as I see the specifications of glTF2.0, it is documented that we should use default values for standard shader in glTF.

> The default material, used when a mesh does not specify a material, is defined to be a material with no properties specified. All the default values of material apply. Note that this material does not emit light and will be black unless some lighting is present in the scene.

However, default shader require some of attributes to use. These are POSITION and NORMAL.
I guess it is very exceptional case that there is no buffer of which semantics is POSITION.
But, I guess there was some of sample models that not contains material configurations and there was no NORMAL value to use. This kind of model can be seen in `Camera` sample in glTF-Sample-Models.

If I need to complement NORMAL from POSITION to use these basic shaders for this kind of models, I want to know specifications of complementing NOMRAL.
I know basic strategy to calculate normal from a single triangle. But, several cases are little bit tricky to complement.

1. How should I do for POINT,LINES or LINE_STRIP geometry to complement NORMAL?(These can have multiple NORMAL candidates to use)
2. If the model has index buffer, I guess NORMAL should have same length array with position array and each elements are contained in the index which is same as position elements for index consistency.
But, several faces can share a vertex. NORMAL should be spherical leaped if there were multiple faces sharing a vertex?

**Comment by lexaknyazev** [comment]
From [Meshes](https://github.com/KhronosGroup/glTF/tree/2.0/specification/2.0#meshes) section:
> **Implementation note:** When normals are not specified, implementations should calculate flat normals.

We should add docs about points/lines cases.

CC @bghgary @pjcozzi

**Comment by bghgary** [comment]
This is related to #917.

**Comment by pjcozzi** [comment]
@kyasbal-1994 thanks again for the input!

For triangles without normals, this is already defined to compute flat normals.

For points and line, we will make a spec update: https://github.com/KhronosGroup/glTF/issues/917#issuecomment-337971557
