### ISSUE TITLE
Storage of vertex attributes in sparse accessors

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#995]
Should we restrict usage of sparse accessors to morph targets and animation data only? E.g., should it be possible to use them as a source of static vertex data?

Consider this:
```
mesh 0
  POSITIONS -> accessor 0
  NORMALS -> accessor 1
mesh 1
  POSITIONS -> accessor 2
  NORMALS -> accessor 3

accessor 0 // positions for the first mesh
  bufferView -> 0
accessor 1 // normals for the first mesh
  bufferView -> 0
accessor 2 // positions for the second mesh
  bufferView -> 0
  sparse
    indices -> bufferView 1
    values -> bufferView 1
accessor 3 // normals for the second mesh
  bufferView -> 0
  sparse
    indices -> bufferView 1
    values -> bufferView 1

bufferView 0 // positions and normals for the first mesh
  byteStride // stride is defined because it's raw vertex data used by more than one accessor; vertex attributes could be interleaved
bufferView 1 // sparse data for the second mesh
```

The only drawback is that implementations will be required to support software (non-GPU) reading of (possibly interleaved) vertex data.

At the moment, spec doesn't define valid use cases for sparse accessors.

CC @pjcozzi @bghgary

**Comment by pjcozzi** [comment]
To keep runtimes simple, we could restrict in 2.0 and loosen in a future version if use cases beyond morph targets and animation come up.

**Comment by lexaknyazev** [comment]
> To keep runtimes simple

This part of implementation doesn't seem to be very difficult (compared to other 2.0 stuff).

**Comment by pjcozzi** [comment]
If there's no use case, I still wouldn't require it even if it is easy.

Your call.

**Comment by lexaknyazev** [comment]
I still think that we should keep this functionality, but we need to make docs a bit more explicit.

---

Let's start with vectors:
**VEC3, UNSIGNED_BYTE, 4 elements**
Base accessor (each value is aligned to 4-byte boundaries, i.e. `bufferView.byteStride` equals 4):
```
|00|01|02|03|04|05|06|07|08|09|0A|0B|0C|0D|0E|0F|
|==|==|==|==|==|==|==|==|==|==|==|==|==|==|==|==|
|vx|vy|vz|--|vx|vy|vz|--|vx|vy|vz|--|vx|vy|vz|--|
```
Now, let's say that `sparse` overrides first two values. Since CPU-targeted bufferView can't have `byteStride`, values must be dense. `sparse.values` will contain:
```
|00|01|02|03|04|05|
|==|==|==|==|==|==|
|sx|sy|sz|sx|sy|sz|
```
Does it look good?

---

Now, let's look at matrices:
**MAT3, UNSIGNED_BYTE, 2 elements**
Base accessor (each column is aligned to 4-byte boundaries, `bufferView.byteStride` equals 12):
```
| 00| 01| 02| 03| 04| 05| 06| 07| 08| 09| 0A| 0B| 0C| 0D| 0E| 0F| 10| 11| 12| 13| 14| 15| 16| 17|
|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|
|m00|m10|m20|---|m01|m11|m21|---|m02|m12|m22|---|m00|m10|m20|---|m01|m11|m21|---|m02|m12|m22|---|
```
Let's say that this time, `sparse` overrides only the first value. Since CPU-targeted bufferView can't have `byteStride`, values must be dense. `sparse.values` will contain:
```
| 00| 01| 02| 03| 04| 05| 06| 07| 08|
|===|===|===|===|===|===|===|===|===|
|s00|s10|s20|s01|s11|s21|s02|s12|s22|
```
Are you OK with this?

---
Must matrix column alignment be required for all accessors or only for vertex attributes? Consider this:
**Vertex attribute, MAT3, UNSIGNED_BYTE, 2 elements, `bufferView.byteStride` equals 12:**
```
| 00| 01| 02| 03| 04| 05| 06| 07| 08| 09| 0A| 0B| 0C| 0D| 0E| 0F| 10| 11| 12| 13| 14| 15| 16| 17|
|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|
|m00|m10|m20|---|m01|m11|m21|---|m02|m12|m22|---|m00|m10|m20|---|m01|m11|m21|---|m02|m12|m22|---|
```

**Not a vertex attribute, MAT3, UNSIGNED_BYTE, 2 elements, `bufferView.byteStride` equals 12:**
```
| 00| 01| 02| 03| 04| 05| 06| 07| 08| 09| 0A| 0B| 0C| 0D| 0E| 0F| 10| 11| 12| 13| 14| 15| 16| 17|
|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|===|
|m00|m10|m20|m01|m11|m21|m02|m12|m22|---|---|---|m00|m10|m20|m01|m11|m21|m02|m12|m22|---|---|---|
```

To eliminate such vagueness, I propose to clarify that column alignment applies to all matrix accessors regardless of their usage.

@pjcozzi @bghgary @sbtron

**Comment by bghgary** [comment]
> Should we restrict usage of sparse accessors to morph targets and animation data only?

I don't have a strong argument either way. If we do support sparse accessors on everything, then I am okay with everything you stated, including applying sparse data on the CPU.

> CPU-targeted bufferView can't have byteStride 

Where in the spec does it say this?

> clarify that column alignment applies to all matrix accessors regardless of their usage.

I think it is already worded this way?

**Comment by lexaknyazev** [comment]
>> CPU-targeted bufferView can't have byteStride

> Where in the spec does it say this?

By "CPU-targeted", I mean images or animation data. Literal [definition of `byteStride`](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/bufferView.schema.json#L29): "The stride, in bytes, between vertex attributes."

Also from [readme](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#buffers-and-buffer-views):
> Buffer view could have `byteStride` property. It means byte-distance between consequential elements. This field is defined only for buffer views that contain vertex attributes.

---

>> clarify that column alignment applies to all matrix accessors regardless of their usage.

>I think it is already worded this way?

That sentence is written right after vertex attributes alignment, so some readers may misinterpret it.
