### ISSUE TITLE
Matrix accessors alignment

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/glTF#996]
From [Data Alignment](https://github.com/KhronosGroup/glTF/tree/2.0/specification/2.0#data-alignment) section:
> vertex attributes must be aligned to 4-byte boundaries 

Spec should be more explicit on 2x2 and 3x3 matrices alignment, since OpenGL will treat each column as a separate attribute. E.g., elements of `MAT3` and `UNSIGNED_BYTE` must have length of 12 bytes, not 9.

Btw, these two types don't have spec-defined use cases.

**Comment by lexaknyazev** [comment]
Here're all three special cases for 2.0:

| `type` | `componentType`         | Byte length of one element |
|--------|-------------------------|----------------------------|
| MAT2   | BYTE<br>UNSIGNED_BYTE   | 8 (instead of 4)           |
| MAT3   | BYTE<br>UNSIGNED_BYTE   | 12 (instead of 9)          |
| MAT3   | SHORT<br>UNSIGNED_SHORT | 24 (instead of 18)         |

This list could become bigger with possible future non-square matrix support.

**Comment by pjcozzi** [comment]
Special cases seem fine.  I don't know how widely used BYTE/SHORT matrices will be in practice, but let's include this info in the spec.
